SUMMARY = "Cochineal fonts with LaTeX support"
DESCRIPTION = "Cochineal is a fork from the Crimson fonts (Roman, Italic, \
Bold, BoldItalic only) released under the OFL by Sebastian \
Kosch. These remarkable fonts are inspired by the famous \
oldstyle fonts in the garalde family (Garamond, Bembo) but, in \
the end, look more similar to Minion, though with smaller \
xheight and less plain in detail. The Crimson fonts on which \
these were based had roughly 4200 glyphs in the four styles \
mentioned above. Cochineal adds more than 1500 glyphs in those \
styles so that it is possible to make a TeX support collection \
that contains essentially all glyphs in all styles. Bringing \
the Semibold styles up the same level would have required \
adding about 2000 additional glyphs, which I could not even \
contemplate. The fonts are provided in OpenType and PostScript \
formats."
LICENSE = "OFL-1.1"

PV = "2023.201.1.077svn62063"

RPM_NAME = "texlive-cochineal-2023.201.1.077svn62063-53.1.noarch.rpm"
RPM_HASH = "6d17d6b7ed23cd5ae764c69f6287ebd51f362dfdf50d5ed9cca568c1e22c2061301b8561d498ac77b58879f9e06cef3c729eca8aac94edaaa906ce7d02c3df7c"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-Cochineal-Bol-alph.tfm \
tex-Cochineal-Bol-osf.tfm \
tex-Cochineal-BolIta-alph.tfm \
tex-Cochineal-Bold-dnom-ly1--base.tfm \
tex-Cochineal-Bold-dnom-ly1.tfm \
tex-Cochineal-Bold-dnom-ly1.vf \
tex-Cochineal-Bold-dnom-ot1.tfm \
tex-Cochineal-Bold-dnom-t1--base.tfm \
tex-Cochineal-Bold-dnom-t1.tfm \
tex-Cochineal-Bold-dnom-t1.vf \
tex-Cochineal-Bold-inf-ly1--base.tfm \
tex-Cochineal-Bold-inf-ly1.tfm \
tex-Cochineal-Bold-inf-ly1.vf \
tex-Cochineal-Bold-inf-ot1.tfm \
tex-Cochineal-Bold-inf-t1--base.tfm \
tex-Cochineal-Bold-inf-t1.tfm \
tex-Cochineal-Bold-inf-t1.vf \
tex-Cochineal-Bold-lf-lgr.tfm \
tex-Cochineal-Bold-lf-ly1--base.tfm \
tex-Cochineal-Bold-lf-ly1.tfm \
tex-Cochineal-Bold-lf-ly1.vf \
tex-Cochineal-Bold-lf-ot1.tfm \
tex-Cochineal-Bold-lf-ot2.tfm \
tex-Cochineal-Bold-lf-sc-ly1--base.tfm \
tex-Cochineal-Bold-lf-sc-ly1.tfm \
tex-Cochineal-Bold-lf-sc-ly1.vf \
tex-Cochineal-Bold-lf-sc-ot1--base.tfm \
tex-Cochineal-Bold-lf-sc-ot1.tfm \
tex-Cochineal-Bold-lf-sc-ot1.vf \
tex-Cochineal-Bold-lf-sc-t1--base.tfm \
tex-Cochineal-Bold-lf-sc-t1.tfm \
tex-Cochineal-Bold-lf-sc-t1.vf \
tex-Cochineal-Bold-lf-swash-ly1--base.tfm \
tex-Cochineal-Bold-lf-swash-ly1.tfm \
tex-Cochineal-Bold-lf-swash-ly1.vf \
tex-Cochineal-Bold-lf-swash-ot1.tfm \
tex-Cochineal-Bold-lf-swash-t1--base.tfm \
tex-Cochineal-Bold-lf-swash-t1.tfm \
tex-Cochineal-Bold-lf-swash-t1.vf \
tex-Cochineal-Bold-lf-t1--base.tfm \
tex-Cochineal-Bold-lf-t1.tfm \
tex-Cochineal-Bold-lf-t1.vf \
tex-Cochineal-Bold-osf-lgr.tfm \
tex-Cochineal-Bold-osf-ly1--base.tfm \
tex-Cochineal-Bold-osf-ly1.tfm \
tex-Cochineal-Bold-osf-ly1.vf \
tex-Cochineal-Bold-osf-ot1.tfm \
tex-Cochineal-Bold-osf-ot2.tfm \
tex-Cochineal-Bold-osf-sc-ly1--base.tfm \
tex-Cochineal-Bold-osf-sc-ly1.tfm \
tex-Cochineal-Bold-osf-sc-ly1.vf \
tex-Cochineal-Bold-osf-sc-ot1--base.tfm \
tex-Cochineal-Bold-osf-sc-ot1.tfm \
tex-Cochineal-Bold-osf-sc-ot1.vf \
tex-Cochineal-Bold-osf-sc-t1--base.tfm \
tex-Cochineal-Bold-osf-sc-t1.tfm \
tex-Cochineal-Bold-osf-sc-t1.vf \
tex-Cochineal-Bold-osf-swash-ly1--base.tfm \
tex-Cochineal-Bold-osf-swash-ly1.tfm \
tex-Cochineal-Bold-osf-swash-ly1.vf \
tex-Cochineal-Bold-osf-swash-ot1.tfm \
tex-Cochineal-Bold-osf-swash-t1--base.tfm \
tex-Cochineal-Bold-osf-swash-t1.tfm \
tex-Cochineal-Bold-osf-swash-t1.vf \
tex-Cochineal-Bold-osf-t1--base.tfm \
tex-Cochineal-Bold-osf-t1.tfm \
tex-Cochineal-Bold-osf-t1.vf \
tex-Cochineal-Bold-ot2.tfm \
tex-Cochineal-Bold-sup-ly1--base.tfm \
tex-Cochineal-Bold-sup-ly1.tfm \
tex-Cochineal-Bold-sup-ly1.vf \
tex-Cochineal-Bold-sup-ot1.tfm \
tex-Cochineal-Bold-sup-t1--base.tfm \
tex-Cochineal-Bold-sup-t1.tfm \
tex-Cochineal-Bold-sup-t1.vf \
tex-Cochineal-Bold-tlf-lgr.tfm \
tex-Cochineal-Bold-tlf-ly1--base.tfm \
tex-Cochineal-Bold-tlf-ly1.tfm \
tex-Cochineal-Bold-tlf-ly1.vf \
tex-Cochineal-Bold-tlf-ot1.tfm \
tex-Cochineal-Bold-tlf-ot2.tfm \
tex-Cochineal-Bold-tlf-sc-ly1--base.tfm \
tex-Cochineal-Bold-tlf-sc-ly1.tfm \
tex-Cochineal-Bold-tlf-sc-ly1.vf \
tex-Cochineal-Bold-tlf-sc-ot1--base.tfm \
tex-Cochineal-Bold-tlf-sc-ot1.tfm \
tex-Cochineal-Bold-tlf-sc-ot1.vf \
tex-Cochineal-Bold-tlf-sc-t1--base.tfm \
tex-Cochineal-Bold-tlf-sc-t1.tfm \
tex-Cochineal-Bold-tlf-sc-t1.vf \
tex-Cochineal-Bold-tlf-swash-ly1--base.tfm \
tex-Cochineal-Bold-tlf-swash-ly1.tfm \
tex-Cochineal-Bold-tlf-swash-ly1.vf \
tex-Cochineal-Bold-tlf-swash-ot1.tfm \
tex-Cochineal-Bold-tlf-swash-t1--base.tfm \
tex-Cochineal-Bold-tlf-swash-t1.tfm \
tex-Cochineal-Bold-tlf-swash-t1.vf \
tex-Cochineal-Bold-tlf-t1--base.tfm \
tex-Cochineal-Bold-tlf-t1.tfm \
tex-Cochineal-Bold-tlf-t1.vf \
tex-Cochineal-Bold-tlf-t2a.tfm \
tex-Cochineal-Bold-tosf-lgr.tfm \
tex-Cochineal-Bold-tosf-ly1--base.tfm \
tex-Cochineal-Bold-tosf-ly1.tfm \
tex-Cochineal-Bold-tosf-ly1.vf \
tex-Cochineal-Bold-tosf-ot1.tfm \
tex-Cochineal-Bold-tosf-ot2.tfm \
tex-Cochineal-Bold-tosf-sc-ly1--base.tfm \
tex-Cochineal-Bold-tosf-sc-ly1.tfm \
tex-Cochineal-Bold-tosf-sc-ly1.vf \
tex-Cochineal-Bold-tosf-sc-ot1--base.tfm \
tex-Cochineal-Bold-tosf-sc-ot1.tfm \
tex-Cochineal-Bold-tosf-sc-ot1.vf \
tex-Cochineal-Bold-tosf-sc-t1--base.tfm \
tex-Cochineal-Bold-tosf-sc-t1.tfm \
tex-Cochineal-Bold-tosf-sc-t1.vf \
tex-Cochineal-Bold-tosf-swash-ly1--base.tfm \
tex-Cochineal-Bold-tosf-swash-ly1.tfm \
tex-Cochineal-Bold-tosf-swash-ly1.vf \
tex-Cochineal-Bold-tosf-swash-ot1.tfm \
tex-Cochineal-Bold-tosf-swash-t1--base.tfm \
tex-Cochineal-Bold-tosf-swash-t1.tfm \
tex-Cochineal-Bold-tosf-swash-t1.vf \
tex-Cochineal-Bold-tosf-t1--base.tfm \
tex-Cochineal-Bold-tosf-t1.tfm \
tex-Cochineal-Bold-tosf-t1.vf \
tex-Cochineal-Bold-ts1--base.tfm \
tex-Cochineal-Bold-ts1.tfm \
tex-Cochineal-Bold-ts1.vf \
tex-Cochineal-BoldItalic-dnom-ly1--base.tfm \
tex-Cochineal-BoldItalic-dnom-ly1.tfm \
tex-Cochineal-BoldItalic-dnom-ly1.vf \
tex-Cochineal-BoldItalic-dnom-ot1.tfm \
tex-Cochineal-BoldItalic-dnom-t1--base.tfm \
tex-Cochineal-BoldItalic-dnom-t1.tfm \
tex-Cochineal-BoldItalic-dnom-t1.vf \
tex-Cochineal-BoldItalic-inf-ly1--base.tfm \
tex-Cochineal-BoldItalic-inf-ly1.tfm \
tex-Cochineal-BoldItalic-inf-ly1.vf \
tex-Cochineal-BoldItalic-inf-ot1.tfm \
tex-Cochineal-BoldItalic-inf-t1--base.tfm \
tex-Cochineal-BoldItalic-inf-t1.tfm \
tex-Cochineal-BoldItalic-inf-t1.vf \
tex-Cochineal-BoldItalic-lf-ly1--base.tfm \
tex-Cochineal-BoldItalic-lf-ly1.tfm \
tex-Cochineal-BoldItalic-lf-ly1.vf \
tex-Cochineal-BoldItalic-lf-ot1.tfm \
tex-Cochineal-BoldItalic-lf-ot2.tfm \
tex-Cochineal-BoldItalic-lf-sc-ly1--base.tfm \
tex-Cochineal-BoldItalic-lf-sc-ly1.tfm \
tex-Cochineal-BoldItalic-lf-sc-ly1.vf \
tex-Cochineal-BoldItalic-lf-sc-ot1--base.tfm \
tex-Cochineal-BoldItalic-lf-sc-ot1.tfm \
tex-Cochineal-BoldItalic-lf-sc-ot1.vf \
tex-Cochineal-BoldItalic-lf-sc-t1--base.tfm \
tex-Cochineal-BoldItalic-lf-sc-t1.tfm \
tex-Cochineal-BoldItalic-lf-sc-t1.vf \
tex-Cochineal-BoldItalic-lf-swash-ly1--base.tfm \
tex-Cochineal-BoldItalic-lf-swash-ly1.tfm \
tex-Cochineal-BoldItalic-lf-swash-ly1.vf \
tex-Cochineal-BoldItalic-lf-swash-ot1.tfm \
tex-Cochineal-BoldItalic-lf-swash-t1--base.tfm \
tex-Cochineal-BoldItalic-lf-swash-t1.tfm \
tex-Cochineal-BoldItalic-lf-swash-t1.vf \
tex-Cochineal-BoldItalic-lf-t1--base.tfm \
tex-Cochineal-BoldItalic-lf-t1.tfm \
tex-Cochineal-BoldItalic-lf-t1.vf \
tex-Cochineal-BoldItalic-osf-ly1--base.tfm \
tex-Cochineal-BoldItalic-osf-ly1.tfm \
tex-Cochineal-BoldItalic-osf-ly1.vf \
tex-Cochineal-BoldItalic-osf-ot1.tfm \
tex-Cochineal-BoldItalic-osf-ot2.tfm \
tex-Cochineal-BoldItalic-osf-sc-ly1--base.tfm \
tex-Cochineal-BoldItalic-osf-sc-ly1.tfm \
tex-Cochineal-BoldItalic-osf-sc-ly1.vf \
tex-Cochineal-BoldItalic-osf-sc-ot1--base.tfm \
tex-Cochineal-BoldItalic-osf-sc-ot1.tfm \
tex-Cochineal-BoldItalic-osf-sc-ot1.vf \
tex-Cochineal-BoldItalic-osf-sc-t1--base.tfm \
tex-Cochineal-BoldItalic-osf-sc-t1.tfm \
tex-Cochineal-BoldItalic-osf-sc-t1.vf \
tex-Cochineal-BoldItalic-osf-swash-ly1--base.tfm \
tex-Cochineal-BoldItalic-osf-swash-ly1.tfm \
tex-Cochineal-BoldItalic-osf-swash-ly1.vf \
tex-Cochineal-BoldItalic-osf-swash-ot1.tfm \
tex-Cochineal-BoldItalic-osf-swash-t1--base.tfm \
tex-Cochineal-BoldItalic-osf-swash-t1.tfm \
tex-Cochineal-BoldItalic-osf-swash-t1.vf \
tex-Cochineal-BoldItalic-osf-t1--base.tfm \
tex-Cochineal-BoldItalic-osf-t1.tfm \
tex-Cochineal-BoldItalic-osf-t1.vf \
tex-Cochineal-BoldItalic-ot2.tfm \
tex-Cochineal-BoldItalic-sup-ly1--base.tfm \
tex-Cochineal-BoldItalic-sup-ly1.tfm \
tex-Cochineal-BoldItalic-sup-ly1.vf \
tex-Cochineal-BoldItalic-sup-ot1.tfm \
tex-Cochineal-BoldItalic-sup-t1--base.tfm \
tex-Cochineal-BoldItalic-sup-t1.tfm \
tex-Cochineal-BoldItalic-sup-t1.vf \
tex-Cochineal-BoldItalic-tlf-lgr.tfm \
tex-Cochineal-BoldItalic-tlf-ly1--base.tfm \
tex-Cochineal-BoldItalic-tlf-ly1.tfm \
tex-Cochineal-BoldItalic-tlf-ly1.vf \
tex-Cochineal-BoldItalic-tlf-ot1.tfm \
tex-Cochineal-BoldItalic-tlf-ot2.tfm \
tex-Cochineal-BoldItalic-tlf-sc-ly1--base.tfm \
tex-Cochineal-BoldItalic-tlf-sc-ly1.tfm \
tex-Cochineal-BoldItalic-tlf-sc-ly1.vf \
tex-Cochineal-BoldItalic-tlf-sc-ot1--base.tfm \
tex-Cochineal-BoldItalic-tlf-sc-ot1.tfm \
tex-Cochineal-BoldItalic-tlf-sc-ot1.vf \
tex-Cochineal-BoldItalic-tlf-sc-t1--base.tfm \
tex-Cochineal-BoldItalic-tlf-sc-t1.tfm \
tex-Cochineal-BoldItalic-tlf-sc-t1.vf \
tex-Cochineal-BoldItalic-tlf-swash-ly1--base.tfm \
tex-Cochineal-BoldItalic-tlf-swash-ly1.tfm \
tex-Cochineal-BoldItalic-tlf-swash-ly1.vf \
tex-Cochineal-BoldItalic-tlf-swash-ot1.tfm \
tex-Cochineal-BoldItalic-tlf-swash-t1--base.tfm \
tex-Cochineal-BoldItalic-tlf-swash-t1.tfm \
tex-Cochineal-BoldItalic-tlf-swash-t1.vf \
tex-Cochineal-BoldItalic-tlf-t1--base.tfm \
tex-Cochineal-BoldItalic-tlf-t1.tfm \
tex-Cochineal-BoldItalic-tlf-t1.vf \
tex-Cochineal-BoldItalic-tlf-t2a.tfm \
tex-Cochineal-BoldItalic-tosf-ly1--base.tfm \
tex-Cochineal-BoldItalic-tosf-ly1.tfm \
tex-Cochineal-BoldItalic-tosf-ly1.vf \
tex-Cochineal-BoldItalic-tosf-ot1.tfm \
tex-Cochineal-BoldItalic-tosf-ot2.tfm \
tex-Cochineal-BoldItalic-tosf-sc-ly1--base.tfm \
tex-Cochineal-BoldItalic-tosf-sc-ly1.tfm \
tex-Cochineal-BoldItalic-tosf-sc-ly1.vf \
tex-Cochineal-BoldItalic-tosf-sc-ot1--base.tfm \
tex-Cochineal-BoldItalic-tosf-sc-ot1.tfm \
tex-Cochineal-BoldItalic-tosf-sc-ot1.vf \
tex-Cochineal-BoldItalic-tosf-sc-t1--base.tfm \
tex-Cochineal-BoldItalic-tosf-sc-t1.tfm \
tex-Cochineal-BoldItalic-tosf-sc-t1.vf \
tex-Cochineal-BoldItalic-tosf-swash-ly1--base.tfm \
tex-Cochineal-BoldItalic-tosf-swash-ly1.tfm \
tex-Cochineal-BoldItalic-tosf-swash-ly1.vf \
tex-Cochineal-BoldItalic-tosf-swash-ot1.tfm \
tex-Cochineal-BoldItalic-tosf-swash-t1--base.tfm \
tex-Cochineal-BoldItalic-tosf-swash-t1.tfm \
tex-Cochineal-BoldItalic-tosf-swash-t1.vf \
tex-Cochineal-BoldItalic-tosf-t1--base.tfm \
tex-Cochineal-BoldItalic-tosf-t1.tfm \
tex-Cochineal-BoldItalic-tosf-t1.vf \
tex-Cochineal-Bolditalic-lf-lgr.tfm \
tex-Cochineal-Bolditalic-osf-lgr.tfm \
tex-Cochineal-Bolditalic-tosf-lgr.tfm \
tex-Cochineal-Bolditalic-ts1--base.tfm \
tex-Cochineal-Bolditalic-ts1.tfm \
tex-Cochineal-Bolditalic-ts1.vf \
tex-Cochineal-Ita-alph.tfm \
tex-Cochineal-Italic-dnom-ly1--base.tfm \
tex-Cochineal-Italic-dnom-ly1.tfm \
tex-Cochineal-Italic-dnom-ly1.vf \
tex-Cochineal-Italic-dnom-ot1.tfm \
tex-Cochineal-Italic-dnom-t1--base.tfm \
tex-Cochineal-Italic-dnom-t1.tfm \
tex-Cochineal-Italic-dnom-t1.vf \
tex-Cochineal-Italic-inf-ly1--base.tfm \
tex-Cochineal-Italic-inf-ly1.tfm \
tex-Cochineal-Italic-inf-ly1.vf \
tex-Cochineal-Italic-inf-ot1.tfm \
tex-Cochineal-Italic-inf-t1--base.tfm \
tex-Cochineal-Italic-inf-t1.tfm \
tex-Cochineal-Italic-inf-t1.vf \
tex-Cochineal-Italic-lf-lgr.tfm \
tex-Cochineal-Italic-lf-ly1--base.tfm \
tex-Cochineal-Italic-lf-ly1.tfm \
tex-Cochineal-Italic-lf-ly1.vf \
tex-Cochineal-Italic-lf-ot1.tfm \
tex-Cochineal-Italic-lf-ot2.tfm \
tex-Cochineal-Italic-lf-sc-ly1--base.tfm \
tex-Cochineal-Italic-lf-sc-ly1.tfm \
tex-Cochineal-Italic-lf-sc-ly1.vf \
tex-Cochineal-Italic-lf-sc-ot1--base.tfm \
tex-Cochineal-Italic-lf-sc-ot1.tfm \
tex-Cochineal-Italic-lf-sc-ot1.vf \
tex-Cochineal-Italic-lf-sc-t1--base.tfm \
tex-Cochineal-Italic-lf-sc-t1.tfm \
tex-Cochineal-Italic-lf-sc-t1.vf \
tex-Cochineal-Italic-lf-swash-ly1--base.tfm \
tex-Cochineal-Italic-lf-swash-ly1.tfm \
tex-Cochineal-Italic-lf-swash-ly1.vf \
tex-Cochineal-Italic-lf-swash-ot1.tfm \
tex-Cochineal-Italic-lf-swash-t1--base.tfm \
tex-Cochineal-Italic-lf-swash-t1.tfm \
tex-Cochineal-Italic-lf-swash-t1.vf \
tex-Cochineal-Italic-lf-t1--base.tfm \
tex-Cochineal-Italic-lf-t1.tfm \
tex-Cochineal-Italic-lf-t1.vf \
tex-Cochineal-Italic-lf-th-ly1.tfm \
tex-Cochineal-Italic-lf-th-ot1.tfm \
tex-Cochineal-Italic-lf-th-t1.tfm \
tex-Cochineal-Italic-osf-lgr.tfm \
tex-Cochineal-Italic-osf-ly1--base.tfm \
tex-Cochineal-Italic-osf-ly1.tfm \
tex-Cochineal-Italic-osf-ly1.vf \
tex-Cochineal-Italic-osf-ot1.tfm \
tex-Cochineal-Italic-osf-ot2.tfm \
tex-Cochineal-Italic-osf-sc-ly1--base.tfm \
tex-Cochineal-Italic-osf-sc-ly1.tfm \
tex-Cochineal-Italic-osf-sc-ly1.vf \
tex-Cochineal-Italic-osf-sc-ot1--base.tfm \
tex-Cochineal-Italic-osf-sc-ot1.tfm \
tex-Cochineal-Italic-osf-sc-ot1.vf \
tex-Cochineal-Italic-osf-sc-t1--base.tfm \
tex-Cochineal-Italic-osf-sc-t1.tfm \
tex-Cochineal-Italic-osf-sc-t1.vf \
tex-Cochineal-Italic-osf-swash-ly1--base.tfm \
tex-Cochineal-Italic-osf-swash-ly1.tfm \
tex-Cochineal-Italic-osf-swash-ly1.vf \
tex-Cochineal-Italic-osf-swash-ot1.tfm \
tex-Cochineal-Italic-osf-swash-t1--base.tfm \
tex-Cochineal-Italic-osf-swash-t1.tfm \
tex-Cochineal-Italic-osf-swash-t1.vf \
tex-Cochineal-Italic-osf-t1--base.tfm \
tex-Cochineal-Italic-osf-t1.tfm \
tex-Cochineal-Italic-osf-t1.vf \
tex-Cochineal-Italic-osf-th-ly1.tfm \
tex-Cochineal-Italic-osf-th-ot1.tfm \
tex-Cochineal-Italic-osf-th-t1.tfm \
tex-Cochineal-Italic-ot2.tfm \
tex-Cochineal-Italic-sup-ly1--base.tfm \
tex-Cochineal-Italic-sup-ly1.tfm \
tex-Cochineal-Italic-sup-ly1.vf \
tex-Cochineal-Italic-sup-ot1.tfm \
tex-Cochineal-Italic-sup-t1--base.tfm \
tex-Cochineal-Italic-sup-t1.tfm \
tex-Cochineal-Italic-sup-t1.vf \
tex-Cochineal-Italic-tlf-lgr.tfm \
tex-Cochineal-Italic-tlf-ly1--base.tfm \
tex-Cochineal-Italic-tlf-ly1.tfm \
tex-Cochineal-Italic-tlf-ly1.vf \
tex-Cochineal-Italic-tlf-ot1.tfm \
tex-Cochineal-Italic-tlf-ot2.tfm \
tex-Cochineal-Italic-tlf-sc-ly1--base.tfm \
tex-Cochineal-Italic-tlf-sc-ly1.tfm \
tex-Cochineal-Italic-tlf-sc-ly1.vf \
tex-Cochineal-Italic-tlf-sc-ot1--base.tfm \
tex-Cochineal-Italic-tlf-sc-ot1.tfm \
tex-Cochineal-Italic-tlf-sc-ot1.vf \
tex-Cochineal-Italic-tlf-sc-t1--base.tfm \
tex-Cochineal-Italic-tlf-sc-t1.tfm \
tex-Cochineal-Italic-tlf-sc-t1.vf \
tex-Cochineal-Italic-tlf-swash-ly1--base.tfm \
tex-Cochineal-Italic-tlf-swash-ly1.tfm \
tex-Cochineal-Italic-tlf-swash-ly1.vf \
tex-Cochineal-Italic-tlf-swash-ot1.tfm \
tex-Cochineal-Italic-tlf-swash-t1--base.tfm \
tex-Cochineal-Italic-tlf-swash-t1.tfm \
tex-Cochineal-Italic-tlf-swash-t1.vf \
tex-Cochineal-Italic-tlf-t1--base.tfm \
tex-Cochineal-Italic-tlf-t1.tfm \
tex-Cochineal-Italic-tlf-t1.vf \
tex-Cochineal-Italic-tlf-t2a.tfm \
tex-Cochineal-Italic-tlf-th-ly1.tfm \
tex-Cochineal-Italic-tlf-th-ot1.tfm \
tex-Cochineal-Italic-tlf-th-t1.tfm \
tex-Cochineal-Italic-tosf-lgr.tfm \
tex-Cochineal-Italic-tosf-ly1--base.tfm \
tex-Cochineal-Italic-tosf-ly1.tfm \
tex-Cochineal-Italic-tosf-ly1.vf \
tex-Cochineal-Italic-tosf-ot1.tfm \
tex-Cochineal-Italic-tosf-ot2.tfm \
tex-Cochineal-Italic-tosf-sc-ly1--base.tfm \
tex-Cochineal-Italic-tosf-sc-ly1.tfm \
tex-Cochineal-Italic-tosf-sc-ly1.vf \
tex-Cochineal-Italic-tosf-sc-ot1--base.tfm \
tex-Cochineal-Italic-tosf-sc-ot1.tfm \
tex-Cochineal-Italic-tosf-sc-ot1.vf \
tex-Cochineal-Italic-tosf-sc-t1--base.tfm \
tex-Cochineal-Italic-tosf-sc-t1.tfm \
tex-Cochineal-Italic-tosf-sc-t1.vf \
tex-Cochineal-Italic-tosf-swash-ly1--base.tfm \
tex-Cochineal-Italic-tosf-swash-ly1.tfm \
tex-Cochineal-Italic-tosf-swash-ly1.vf \
tex-Cochineal-Italic-tosf-swash-ot1.tfm \
tex-Cochineal-Italic-tosf-swash-t1--base.tfm \
tex-Cochineal-Italic-tosf-swash-t1.tfm \
tex-Cochineal-Italic-tosf-swash-t1.vf \
tex-Cochineal-Italic-tosf-t1--base.tfm \
tex-Cochineal-Italic-tosf-t1.tfm \
tex-Cochineal-Italic-tosf-t1.vf \
tex-Cochineal-Italic-tosf-th-ly1.tfm \
tex-Cochineal-Italic-tosf-th-ot1.tfm \
tex-Cochineal-Italic-tosf-th-t1.tfm \
tex-Cochineal-Italic-ts1--base.tfm \
tex-Cochineal-Italic-ts1.tfm \
tex-Cochineal-Italic-ts1.vf \
tex-Cochineal-Roman-dnom-ly1.tfm \
tex-Cochineal-Roman-dnom-ot1.tfm \
tex-Cochineal-Roman-dnom-t1--base.tfm \
tex-Cochineal-Roman-dnom-t1.tfm \
tex-Cochineal-Roman-dnom-t1.vf \
tex-Cochineal-Roman-inf-ly1.tfm \
tex-Cochineal-Roman-inf-ot1.tfm \
tex-Cochineal-Roman-inf-t1--base.tfm \
tex-Cochineal-Roman-inf-t1.tfm \
tex-Cochineal-Roman-inf-t1.vf \
tex-Cochineal-Roman-lf-lgr.tfm \
tex-Cochineal-Roman-lf-ly1.tfm \
tex-Cochineal-Roman-lf-ot1.tfm \
tex-Cochineal-Roman-lf-ot2.tfm \
tex-Cochineal-Roman-lf-sc-ly1--base.tfm \
tex-Cochineal-Roman-lf-sc-ly1.tfm \
tex-Cochineal-Roman-lf-sc-ly1.vf \
tex-Cochineal-Roman-lf-sc-ot1--base.tfm \
tex-Cochineal-Roman-lf-sc-ot1.tfm \
tex-Cochineal-Roman-lf-sc-ot1.vf \
tex-Cochineal-Roman-lf-sc-t1--base.tfm \
tex-Cochineal-Roman-lf-sc-t1.tfm \
tex-Cochineal-Roman-lf-sc-t1.vf \
tex-Cochineal-Roman-lf-swash-ly1.tfm \
tex-Cochineal-Roman-lf-swash-ot1.tfm \
tex-Cochineal-Roman-lf-swash-t1--base.tfm \
tex-Cochineal-Roman-lf-swash-t1.tfm \
tex-Cochineal-Roman-lf-swash-t1.vf \
tex-Cochineal-Roman-lf-t1--base.tfm \
tex-Cochineal-Roman-lf-t1.tfm \
tex-Cochineal-Roman-lf-t1.vf \
tex-Cochineal-Roman-osf-lgr.tfm \
tex-Cochineal-Roman-osf-ly1.tfm \
tex-Cochineal-Roman-osf-ot1.tfm \
tex-Cochineal-Roman-osf-ot2.tfm \
tex-Cochineal-Roman-osf-sc-ly1--base.tfm \
tex-Cochineal-Roman-osf-sc-ly1.tfm \
tex-Cochineal-Roman-osf-sc-ly1.vf \
tex-Cochineal-Roman-osf-sc-ot1--base.tfm \
tex-Cochineal-Roman-osf-sc-ot1.tfm \
tex-Cochineal-Roman-osf-sc-ot1.vf \
tex-Cochineal-Roman-osf-sc-t1--base.tfm \
tex-Cochineal-Roman-osf-sc-t1.tfm \
tex-Cochineal-Roman-osf-sc-t1.vf \
tex-Cochineal-Roman-osf-swash-ly1.tfm \
tex-Cochineal-Roman-osf-swash-ot1.tfm \
tex-Cochineal-Roman-osf-swash-t1--base.tfm \
tex-Cochineal-Roman-osf-swash-t1.tfm \
tex-Cochineal-Roman-osf-swash-t1.vf \
tex-Cochineal-Roman-osf-t1--base.tfm \
tex-Cochineal-Roman-osf-t1.tfm \
tex-Cochineal-Roman-osf-t1.vf \
tex-Cochineal-Roman-ot2.tfm \
tex-Cochineal-Roman-sup-ly1.tfm \
tex-Cochineal-Roman-sup-ot1.tfm \
tex-Cochineal-Roman-sup-t1--base.tfm \
tex-Cochineal-Roman-sup-t1.tfm \
tex-Cochineal-Roman-sup-t1.vf \
tex-Cochineal-Roman-tlf-lgr.tfm \
tex-Cochineal-Roman-tlf-ly1.tfm \
tex-Cochineal-Roman-tlf-ot1.tfm \
tex-Cochineal-Roman-tlf-ot2.tfm \
tex-Cochineal-Roman-tlf-sc-ly1--base.tfm \
tex-Cochineal-Roman-tlf-sc-ly1.tfm \
tex-Cochineal-Roman-tlf-sc-ly1.vf \
tex-Cochineal-Roman-tlf-sc-ot1--base.tfm \
tex-Cochineal-Roman-tlf-sc-ot1.tfm \
tex-Cochineal-Roman-tlf-sc-ot1.vf \
tex-Cochineal-Roman-tlf-sc-t1--base.tfm \
tex-Cochineal-Roman-tlf-sc-t1.tfm \
tex-Cochineal-Roman-tlf-sc-t1.vf \
tex-Cochineal-Roman-tlf-swash-ly1.tfm \
tex-Cochineal-Roman-tlf-swash-ot1.tfm \
tex-Cochineal-Roman-tlf-swash-t1--base.tfm \
tex-Cochineal-Roman-tlf-swash-t1.tfm \
tex-Cochineal-Roman-tlf-swash-t1.vf \
tex-Cochineal-Roman-tlf-t1--base.tfm \
tex-Cochineal-Roman-tlf-t1.tfm \
tex-Cochineal-Roman-tlf-t1.vf \
tex-Cochineal-Roman-tlf-t2a.tfm \
tex-Cochineal-Roman-tosf-lgr.tfm \
tex-Cochineal-Roman-tosf-ly1.tfm \
tex-Cochineal-Roman-tosf-ot1.tfm \
tex-Cochineal-Roman-tosf-ot2.tfm \
tex-Cochineal-Roman-tosf-sc-ly1--base.tfm \
tex-Cochineal-Roman-tosf-sc-ly1.tfm \
tex-Cochineal-Roman-tosf-sc-ly1.vf \
tex-Cochineal-Roman-tosf-sc-ot1--base.tfm \
tex-Cochineal-Roman-tosf-sc-ot1.tfm \
tex-Cochineal-Roman-tosf-sc-ot1.vf \
tex-Cochineal-Roman-tosf-sc-t1--base.tfm \
tex-Cochineal-Roman-tosf-sc-t1.tfm \
tex-Cochineal-Roman-tosf-sc-t1.vf \
tex-Cochineal-Roman-tosf-swash-ly1.tfm \
tex-Cochineal-Roman-tosf-swash-ot1.tfm \
tex-Cochineal-Roman-tosf-swash-t1--base.tfm \
tex-Cochineal-Roman-tosf-swash-t1.tfm \
tex-Cochineal-Roman-tosf-swash-t1.vf \
tex-Cochineal-Roman-tosf-t1--base.tfm \
tex-Cochineal-Roman-tosf-t1.tfm \
tex-Cochineal-Roman-tosf-t1.vf \
tex-Cochineal-Roman-ts1--base.tfm \
tex-Cochineal-Roman-ts1.tfm \
tex-Cochineal-Roman-ts1.vf \
tex-Cochineal-alph.tfm \
tex-Cochineal-osf.tfm \
tex-Cochineal.map \
tex-LGRCochineal-LF.fd \
tex-LGRCochineal-OsF.fd \
tex-LGRCochineal-TLF.fd \
tex-LGRCochineal-TOsF.fd \
tex-LY1Cochineal-Dnom.fd \
tex-LY1Cochineal-Inf.fd \
tex-LY1Cochineal-LF.fd \
tex-LY1Cochineal-OsF.fd \
tex-LY1Cochineal-Sup.fd \
tex-LY1Cochineal-TLF.fd \
tex-LY1Cochineal-TOsF.fd \
tex-OT1Cochineal-Dnom.fd \
tex-OT1Cochineal-Inf.fd \
tex-OT1Cochineal-LF.fd \
tex-OT1Cochineal-OsF.fd \
tex-OT1Cochineal-Sup.fd \
tex-OT1Cochineal-TLF.fd \
tex-OT1Cochineal-TOsF.fd \
tex-OT2Cochineal-LF.fd \
tex-OT2Cochineal-OsF.fd \
tex-OT2Cochineal-TLF.fd \
tex-OT2Cochineal-TOsF.fd \
tex-T1Cochineal-Dnom.fd \
tex-T1Cochineal-Inf.fd \
tex-T1Cochineal-LF.fd \
tex-T1Cochineal-OsF.fd \
tex-T1Cochineal-Sup.fd \
tex-T1Cochineal-TLF.fd \
tex-T1Cochineal-TOsF.fd \
tex-T2ACochineal-TLF.fd \
tex-TS1Cochineal-LF.fd \
tex-TS1Cochineal-OsF.fd \
tex-TS1Cochineal-TLF.fd \
tex-TS1Cochineal-TOsF.fd \
tex-coch-2eakhu.enc \
tex-coch-2expjo.enc \
tex-coch-2gvyjv.enc \
tex-coch-2wxnkf.enc \
tex-coch-2zgday.enc \
tex-coch-3brrog.enc \
tex-coch-3q3crd.enc \
tex-coch-3r6zg3.enc \
tex-coch-3tt4zg.enc \
tex-coch-47bkd3.enc \
tex-coch-4agesf.enc \
tex-coch-4plcvc.enc \
tex-coch-5bitfe.enc \
tex-coch-5f3gw2.enc \
tex-coch-5o2hga.enc \
tex-coch-5tib5i.enc \
tex-coch-5tmqae.enc \
tex-coch-5xilzy.enc \
tex-coch-5xjvtq.enc \
tex-coch-6lje3b.enc \
tex-coch-6ry5ir.enc \
tex-coch-6uoyes.enc \
tex-coch-6wh55u.enc \
tex-coch-6xmcha.enc \
tex-coch-7fzfry.enc \
tex-coch-7trhhc.enc \
tex-coch-7v73vk.enc \
tex-coch-aeaj7m.enc \
tex-coch-aiajjq.enc \
tex-coch-alzuis.enc \
tex-coch-awf6hz.enc \
tex-coch-bat6hu.enc \
tex-coch-bhnmej.enc \
tex-coch-bi2nei.enc \
tex-coch-bjqtqq.enc \
tex-coch-bjtzvy.enc \
tex-coch-bnbjdf.enc \
tex-coch-bp2pg7.enc \
tex-coch-cacm2n.enc \
tex-coch-cbs7ow.enc \
tex-coch-cuw7wa.enc \
tex-coch-d2hjcw.enc \
tex-coch-da7weg.enc \
tex-coch-dbsvsj.enc \
tex-coch-ddt3vr.enc \
tex-coch-df5kan.enc \
tex-coch-djzri5.enc \
tex-coch-dwjlw5.enc \
tex-coch-dx3muq.enc \
tex-coch-dxwjai.enc \
tex-coch-e745te.enc \
tex-coch-e77avd.enc \
tex-coch-ekjpcs.enc \
tex-coch-eluj5m.enc \
tex-coch-ermyhb.enc \
tex-coch-fdemcn.enc \
tex-coch-fgurd2.enc \
tex-coch-g2axst.enc \
tex-coch-gcpa6j.enc \
tex-coch-gkpez6.enc \
tex-coch-grutwx.enc \
tex-coch-h2t4ei.enc \
tex-coch-hqneph.enc \
tex-coch-huz7n5.enc \
tex-coch-ibp3xz.enc \
tex-coch-ikkvry.enc \
tex-coch-j7mi7a.enc \
tex-coch-jgxutr.enc \
tex-coch-jhwmea.enc \
tex-coch-jhwq7e.enc \
tex-coch-kbpxlj.enc \
tex-coch-kbxkrg.enc \
tex-coch-kfj2qw.enc \
tex-coch-kfnsdu.enc \
tex-coch-klonus.enc \
tex-coch-ktoy4w.enc \
tex-coch-kuld3f.enc \
tex-coch-kxx5cy.enc \
tex-coch-kzot5v.enc \
tex-coch-l47tcy.enc \
tex-coch-l64ji6.enc \
tex-coch-lchlkf.enc \
tex-coch-ldgozj.enc \
tex-coch-liz2hd.enc \
tex-coch-lqmdx6.enc \
tex-coch-lropbz.enc \
tex-coch-lzqtrs.enc \
tex-coch-m4bmrm.enc \
tex-coch-max2ec.enc \
tex-coch-mo2enl.enc \
tex-coch-nj5yu3.enc \
tex-coch-nlwa7l.enc \
tex-coch-o4vutb.enc \
tex-coch-o5mx43.enc \
tex-coch-odnecf.enc \
tex-coch-okzdl2.enc \
tex-coch-ol4knl.enc \
tex-coch-opxmsy.enc \
tex-coch-oqmhja.enc \
tex-coch-otkq6i.enc \
tex-coch-p7j4gw.enc \
tex-coch-pf3hrr.enc \
tex-coch-pfcyih.enc \
tex-coch-pilffg.enc \
tex-coch-pqzq4p.enc \
tex-coch-q35ey5.enc \
tex-coch-q4ulxa.enc \
tex-coch-qkxc47.enc \
tex-coch-qqsbmj.enc \
tex-coch-qy633g.enc \
tex-coch-qyvxxn.enc \
tex-coch-qzhi24.enc \
tex-coch-r2kqsv.enc \
tex-coch-rix5n3.enc \
tex-coch-rv5tmq.enc \
tex-coch-s4niqi.enc \
tex-coch-saoql6.enc \
tex-coch-sc4bro.enc \
tex-coch-sq6y2y.enc \
tex-coch-sygphi.enc \
tex-coch-syo7sr.enc \
tex-coch-t2a.enc \
tex-coch-t556x2.enc \
tex-coch-t7e5d4.enc \
tex-coch-tfefcu.enc \
tex-coch-th736v.enc \
tex-coch-tjygyt.enc \
tex-coch-tkhq7f.enc \
tex-coch-tnxjqs.enc \
tex-coch-u3j4lk.enc \
tex-coch-uavkhn.enc \
tex-coch-uemkt3.enc \
tex-coch-uh66oa.enc \
tex-coch-uqbj7f.enc \
tex-coch-vew4u5.enc \
tex-coch-vpdkzq.enc \
tex-coch-w6vdgs.enc \
tex-coch-wa4y3o.enc \
tex-coch-wcbuwv.enc \
tex-coch-wnd62o.enc \
tex-coch-wpweoy.enc \
tex-coch-wuwrcy.enc \
tex-coch-x3v6nt.enc \
tex-coch-x4ugem.enc \
tex-coch-xaxcx7.enc \
tex-coch-xsridg.enc \
tex-coch-y3tmc2.enc \
tex-coch-ygltby.enc \
tex-coch-ylbzwi.enc \
tex-coch-yprnrw.enc \
tex-coch-z2oun7.enc \
tex-coch-zbphsw.enc \
tex-coch-zg5irv.enc \
tex-cochBMI.tfm \
tex-cochBRM.tfm \
tex-cochMI.tfm \
tex-cochMRM.tfm \
tex-cochTH-ec.enc \
tex-cochTH-lf-ly1.enc \
tex-cochTH-lf-ot1.enc \
tex-cochTH-lf-t1.enc \
tex-cochTH-osf-ly1.enc \
tex-cochTH-osf-ot1.enc \
tex-cochTH-osf-t1.enc \
tex-cochTH-tlf-ly1.enc \
tex-cochTH-tlf-ot1.enc \
tex-cochTH-tlf-t1.enc \
tex-cochTH-tosf-ly1.enc \
tex-cochTH-tosf-ot1.enc \
tex-cochTH-tosf-t1.enc \
tex-cochalph.enc \
tex-cochineal.sty \
tex-cochlf-lgr.enc \
tex-cochlf-ot2.enc \
tex-cochosf-lgr.enc \
tex-cochosf-ot2.enc \
tex-cochtabosf.enc \
tex-cochtlf-lgr.enc \
tex-cochtlf-ot2.enc \
tex-cochtosf-lgr.enc \
tex-cochtosf-ot2.enc \
tex-ly1mincochineal.fd \
tex-omlzcochmi.fd \
tex-ot1mincochineal.fd \
tex-t1mincochineal.fd \
tex-uzcochmia.fd \
tex-zcochbmi.tfm \
tex-zcochbmi.vf \
tex-zcochbmia.tfm \
tex-zcochbmia.vf \
tex-zcochmi.tfm \
tex-zcochmi.vf \
tex-zcochmia.tfm \
tex-zcochmia.vf \
texlive-cochineal"

RDEPENDS:${PN} += "/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-NewTXBMI.tfm \
tex-NewTXMI.tfm \
tex-etoolbox.sty \
tex-fontaxes.sty \
tex-fontenc.sty \
tex-fontspec.sty \
tex-ifluatex.sty \
tex-ifthen.sty \
tex-ifxetex.sty \
tex-mweights.sty \
tex-realscripts.sty \
tex-scalefnt.sty \
tex-stxscr.tfm \
tex-textcomp.sty \
tex-txbmiaSTbb.tfm \
tex-txbmiaX.tfm \
tex-txmiaSTbb.tfm \
tex-txmiaX.tfm \
tex-updmap.cfg \
tex-xkeyval.sty \
tex-xstring.sty \
texlive \
texlive-cochineal-fonts \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
