SUMMARY = "Development files for hashlink"
DESCRIPTION = "Contains the files required to compile to a native executable the HashLink/C \
code generated by the haxe compiler."
LICENSE = "MIT"

PV = "1.13"

RPM_NAME = "hashlink-devel-1.13-1.4.aarch64.rpm"
RPM_HASH = "ce876163f5b09acecdd129ee625b852dac77cd21fd409777b5f67dc19c7942d22d6fd19cd8ddd8b71c4db8b42e34f69ff334a4df2dcc924dfa47453163f1c1a2"

RPROVIDES:${PN} += "hashlink-devel"

RDEPENDS:${PN} += "hashlink-hdlls \
libhl1"

inherit rpm
