SUMMARY = "Severed fonts for texlive-allrunes"
DESCRIPTION = "The  separated fonts package for texlive-allrunes"
LICENSE = "LPPL-1.0"

PV = "2023.201.2.1.1svn42221"

RPM_NAME = "texlive-allrunes-fonts-2023.201.2.1.1svn42221-54.1.noarch.rpm"
RPM_HASH = "cb3380a5ac508ef21e07d246a04536b77e7a79df0652b2b59473232b11f112730a5ed904e7fc28b6a95ad3671ffac343d6a359c83716322d89d9f7ed19cdf69a"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "font--lang=aa \
font--lang=an \
font--lang=ay \
font--lang=bi \
font--lang=br \
font--lang=ch \
font--lang=co \
font--lang=crh \
font--lang=cs \
font--lang=csb \
font--lang=da \
font--lang=de \
font--lang=en \
font--lang=es \
font--lang=et \
font--lang=eu \
font--lang=fi \
font--lang=fil \
font--lang=fj \
font--lang=fo \
font--lang=fr \
font--lang=fur \
font--lang=fy \
font--lang=gd \
font--lang=gl \
font--lang=gv \
font--lang=ho \
font--lang=hsb \
font--lang=ht \
font--lang=hu \
font--lang=ia \
font--lang=id \
font--lang=ie \
font--lang=io \
font--lang=is \
font--lang=it \
font--lang=jv \
font--lang=kj \
font--lang=ku-tr \
font--lang=kwm \
font--lang=lb \
font--lang=lg \
font--lang=li \
font--lang=mg \
font--lang=ms \
font--lang=nb \
font--lang=nds \
font--lang=ng \
font--lang=nl \
font--lang=nn \
font--lang=no \
font--lang=nr \
font--lang=nso \
font--lang=oc \
font--lang=om \
font--lang=pap-an \
font--lang=pap-aw \
font--lang=pl \
font--lang=pt \
font--lang=rm \
font--lang=rn \
font--lang=rw \
font--lang=sc \
font--lang=sg \
font--lang=sk \
font--lang=sma \
font--lang=smj \
font--lang=sn \
font--lang=so \
font--lang=sq \
font--lang=ss \
font--lang=st \
font--lang=su \
font--lang=sv \
font--lang=sw \
font--lang=tk \
font--lang=tl \
font--lang=tn \
font--lang=tr \
font--lang=ts \
font--lang=uz \
font--lang=vo \
font--lang=vot \
font--lang=wa \
font--lang=wen \
font--lang=wo \
font--lang=xh \
font--lang=yap \
font--lang=za \
font--lang=zu \
font-fruabm \
font-fruabn \
font-fruabq \
font-fruabr \
font-fruabs \
font-fruabt \
font-fruacm \
font-fruacn \
font-fruacq \
font-fruacr \
font-fruacs \
font-fruact \
font-fruakm \
font-fruakn \
font-fruakq \
font-fruakr \
font-fruaks \
font-fruakt \
font-frualm \
font-frualn \
font-frualq \
font-frualr \
font-fruals \
font-frualt \
font-fruamm \
font-fruamn \
font-fruamq \
font-fruamr \
font-fruams \
font-fruamt \
font-fruanm \
font-fruann \
font-fruanq \
font-fruanr \
font-fruans \
font-fruant \
font-frucbm \
font-frucbn \
font-frucbq \
font-frucbr \
font-frucbs \
font-frucbt \
font-fruccm \
font-fruccn \
font-fruccq \
font-fruccr \
font-fruccs \
font-frucct \
font-fruckm \
font-fruckn \
font-fruckq \
font-fruckr \
font-frucks \
font-fruckt \
font-fruclm \
font-frucln \
font-fruclq \
font-fruclr \
font-frucls \
font-fruclt \
font-frucmm \
font-frucmn \
font-frucmq \
font-frucmr \
font-frucms \
font-frucmt \
font-frucnm \
font-frucnn \
font-frucnq \
font-frucnr \
font-frucns \
font-frucnt \
font-frulbm \
font-frulbn \
font-frulbq \
font-frulbr \
font-frulbs \
font-frulbt \
font-frulcm \
font-frulcn \
font-frulcq \
font-frulcr \
font-frulcs \
font-frulct \
font-frulkm \
font-frulkn \
font-frulkq \
font-frulkr \
font-frulks \
font-frulkt \
font-frullm \
font-frulln \
font-frullq \
font-frullr \
font-frulls \
font-frullt \
font-frulmm \
font-frulmn \
font-frulmq \
font-frulmr \
font-frulms \
font-frulmt \
font-frulnm \
font-frulnn \
font-frulnq \
font-frulnr \
font-frulns \
font-frulnt \
font-frumbm \
font-frumbn \
font-frumbq \
font-frumbr \
font-frumbs \
font-frumbt \
font-frumcm \
font-frumcn \
font-frumcq \
font-frumcr \
font-frumcs \
font-frumct \
font-frumkm \
font-frumkn \
font-frumkq \
font-frumkr \
font-frumks \
font-frumkt \
font-frumlm \
font-frumln \
font-frumlq \
font-frumlr \
font-frumls \
font-frumlt \
font-frummm \
font-frummn \
font-frummq \
font-frummr \
font-frumms \
font-frummt \
font-frumnm \
font-frumnn \
font-frumnq \
font-frumnr \
font-frumns \
font-frumnt \
font-frunbm \
font-frunbn \
font-frunbq \
font-frunbr \
font-frunbs \
font-frunbt \
font-fruncm \
font-fruncn \
font-fruncq \
font-fruncr \
font-fruncs \
font-frunct \
font-frunkm \
font-frunkn \
font-frunkq \
font-frunkr \
font-frunks \
font-frunkt \
font-frunlm \
font-frunln \
font-frunlq \
font-frunlr \
font-frunls \
font-frunlt \
font-frunmm \
font-frunmn \
font-frunmq \
font-frunmr \
font-frunms \
font-frunmt \
font-frunnm \
font-frunnn \
font-frunnq \
font-frunnr \
font-frunns \
font-frunnt \
font-frutbm \
font-frutbn \
font-frutbq \
font-frutbr \
font-frutbs \
font-frutbt \
font-frutcm \
font-frutcn \
font-frutcq \
font-frutcr \
font-frutcs \
font-frutct \
font-frutkm \
font-frutkn \
font-frutkq \
font-frutkr \
font-frutks \
font-frutkt \
font-frutlm \
font-frutln \
font-frutlq \
font-frutlr \
font-frutls \
font-frutlt \
font-frutmm \
font-frutmn \
font-frutmq \
font-frutmr \
font-frutms \
font-frutmt \
font-frutnm \
font-frutnn \
font-frutnq \
font-frutnr \
font-frutns \
font-frutnt \
texlive-allrunes-fonts"

RDEPENDS:${PN} += "/usr/bin/sh \
aaa-base \
coreutils \
fontconfig \
ghostscript-fonts-std \
perl"

inherit rpm
