SUMMARY = "A simple Django application to demonstrate RRD plots"
DESCRIPTION = "django-collectd-rest is a simple Django application to demonstrate RRD plots generated by collectd or any other rrd data. \
The application is built on top of django-rest-framework and provides REST API to access the plots."
LICENSE = "BSD-2-Clause"

PV = "0.2.4"

RPM_NAME = "python311-django-collectd-rest-0.2.4-1.3.aarch64.rpm"
RPM_HASH = "63ba629f01894da0d7fac3f6c437fcb96ea18cd312e1da168ea052bbdd226da37cc46a00469c35440aaf12f350c89f471ad8efb3dcfa6cc665230074145f3353"

RPROVIDES:${PN} += "python3.11dist-django-collectd-rest \
python311-django-collectd-rest \
python3dist-django-collectd-rest"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1 \
libc.so.6 \
librrd.so.8 \
python-abi \
python311-Django \
python311-djangorestframework \
rrdtool"

inherit rpm
