SUMMARY = "Customised BibTeX styles"
DESCRIPTION = "Package generating customized BibTeX bibliography styles from a \
generic file using docstrip driven by parameters generated by a \
menu application. Includes support for the Harvard style of \
citations."
LICENSE = "LPPL-1.0"

PV = "2023.209.4.33svn24729"

RPM_NAME = "texlive-custom-bib-2023.209.4.33svn24729-55.1.noarch.rpm"
RPM_HASH = "ba64372ff57de9b053b56fc5ed6be0f94f13bbc60934d575803de9b9d73d10b005329fc5ea821508a7f28a13c7990ecc7e38956f485a3e82732e95f82c071170"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-geophys.tex \
tex-makebst.tex \
tex-shorthnd.tex \
texlive-custom-bib"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
