SUMMARY = "Test applications using Selenium Remote Control"
DESCRIPTION = "This module is a the WWW::Selenium manpage subclass providing some methods \
useful for writing tests. For each Selenium command (open, click, type, \
...) there is a corresponding '<command>_ok' method that checks the return \
value (open_ok, click_ok, type_ok). \
 \
For each Selenium getter (get_title, ...) there are four autogenerated \
methods ('<getter>_is', '<getter>_isnt', '<getter>_like', \
'<getter>_unlike') to check the value of the attribute. \
 \
By calling the constructor with 'default_names' set to a true value your \
tests will be given a reasonable name should you choose not to provide one \
of your own. The test name should always be the third argument."
LICENSE = "Artistic-1.0 | GPL-1.0+"

PV = "1.36"

RPM_NAME = "perl-Test-WWW-Selenium-1.36-3.26.noarch.rpm"
RPM_HASH = "c84d245228e95e782d158e3f6525bcdce15235f7e284c4d8da7720ac297da39d74ed9d29e42a2996c27c45eba7be17f9627496c85b6539857fdc4c743545133d"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "perl-Devel--REPL--Plugin--Selenium \
perl-Test--WWW--Selenium \
perl-Test-WWW-Selenium \
perl-WWW--Selenium \
perl-WWW--Selenium--Util"

RDEPENDS:${PN} += "perl--MODULE-COMPAT-5.36.1 \
perl-HTTP--Headers \
perl-HTTP--Request \
perl-LWP--UserAgent \
perl-URI--Escape \
perl-namespace--clean"

inherit rpm
