SUMMARY = "Test applications using Selenium Remote Control"
DESCRIPTION = "This module is a the WWW::Selenium manpage subclass providing some methods \
useful for writing tests. For each Selenium command (open, click, type, \
...) there is a corresponding '<command>_ok' method that checks the return \
value (open_ok, click_ok, type_ok). \
 \
For each Selenium getter (get_title, ...) there are four autogenerated \
methods ('<getter>_is', '<getter>_isnt', '<getter>_like', \
'<getter>_unlike') to check the value of the attribute. \
 \
By calling the constructor with 'default_names' set to a true value your \
tests will be given a reasonable name should you choose not to provide one \
of your own. The test name should always be the third argument."
LICENSE = "Artistic-1.0 | GPL-1.0+"

PV = "1.36"

RPM_NAME = "perl-Test-WWW-Selenium-1.36-3.25.noarch.rpm"
RPM_HASH = "3c56565d2e208d19ad03da02bd070b94587447face79b4c2bb5337c4303e980398fe1c05575d1515c0acb6e944b38acce7cfc73f8e7ce52e50bff9ea8683290a"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "perl(Devel::REPL::Plugin::Selenium) \
perl(Test::WWW::Selenium) \
perl(WWW::Selenium) \
perl(WWW::Selenium::Util) \
perl-Test-WWW-Selenium"

RDEPENDS:${PN} += "perl(:MODULE_COMPAT_5.36.0) \
perl(HTTP::Headers) \
perl(HTTP::Request) \
perl(LWP::UserAgent) \
perl(URI::Escape) \
perl(namespace::clean)"

inherit rpm
