SUMMARY = "Development files for libt3key, a terminal key sequence db library"
DESCRIPTION = "libt3key is library that provides a database of mappings from escape \
sequences as generated by different consoles and terminals or \
emulators, to key symbols. \
 \
This subpackage contains libraries and header files for developing \
applications that want to make use of libt3key."
LICENSE = "GPL-3.0-only"

PV = "0.2.10"

RPM_NAME = "libt3key-devel-0.2.10-1.15.aarch64.rpm"
RPM_HASH = "471496f1835440d49947c82a581a95a97f797e405df9a78432156538e476622d43635bba0a610f574b89d0f0da20efad674b480c8205f60bbd95243be3a32545"

RPROVIDES:${PN} += "libt3key-devel \
pkgconfig-libt3key"

RDEPENDS:${PN} += "/usr/bin/pkg-config \
libt3key1 \
pkgconfig-libt3config \
pkgconfig-tinfo"

inherit rpm
