SUMMARY = "Using Utopia fonts in LaTeX documents"
DESCRIPTION = "Fourier-GUTenberg is a LaTeX typesetting system which uses \
Adobe Utopia as its standard base font. Fourier-GUTenberg \
provides all complementary typefaces needed to allow Utopia \
based TeX typesetting, including an extensive mathematics set \
and several other symbols. The system is absolutely \
stand-alone: apart from Utopia and Fourier, no other typefaces \
are required. The fourier fonts will also work with Adobe \
Utopia Expert fonts, which are only available for purchase. \
Utopia is a registered trademark of Adobe Systems Incorporated"
LICENSE = "LPPL-1.0"

PV = "2023.209.2.3svn61937"

RPM_NAME = "texlive-fourier-2023.209.2.3svn61937-53.1.noarch.rpm"
RPM_HASH = "3f6fef8b175765fe0581a5bf959e24514cf3be62fc06f46272b8e5bee27b4d5a24086007bd29655c815d60b4fe621c954add649f46a9fb11e9c7b7c62b44e401"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-fmlfutm.fd \
tex-fmlfutmi.fd \
tex-fmsfutm.fd \
tex-fmxfutm.fd \
tex-fourier-alt-black.tfm \
tex-fourier-alt-bold-sl.tfm \
tex-fourier-alt-bold.tfm \
tex-fourier-alt-boldita.tfm \
tex-fourier-alt-ita.tfm \
tex-fourier-alt-semi-sl.tfm \
tex-fourier-alt-semi.tfm \
tex-fourier-alt-semiita.tfm \
tex-fourier-alt-sl.tfm \
tex-fourier-alt.tfm \
tex-fourier-bb.tfm \
tex-fourier-ligs-it.tfm \
tex-fourier-mcl.tfm \
tex-fourier-mex.tfm \
tex-fourier-ml.tfm \
tex-fourier-mlb.tfm \
tex-fourier-mlit.tfm \
tex-fourier-mlitb.tfm \
tex-fourier-ms.tfm \
tex-fourier-orns.sty \
tex-fourier-orns.tfm \
tex-fourier-utopia-expert.map \
tex-fourier.map \
tex-fourier.sty \
tex-futb-sup.tfm \
tex-futb-sup.vf \
tex-futb8c.tfm \
tex-futb8c.vf \
tex-futb8r.tfm \
tex-futb8t.tfm \
tex-futb8t.vf \
tex-futb8x.tfm \
tex-futb9c.tfm \
tex-futb9c.vf \
tex-futb9d.tfm \
tex-futb9d.vf \
tex-futb9e.tfm \
tex-futb9e.vf \
tex-futbc8t.tfm \
tex-futbc8t.vf \
tex-futbi-sup.tfm \
tex-futbi-sup.vf \
tex-futbi8c.tfm \
tex-futbi8c.vf \
tex-futbi8r.tfm \
tex-futbi8t.tfm \
tex-futbi8t.vf \
tex-futbi8x.tfm \
tex-futbi9c.tfm \
tex-futbi9c.vf \
tex-futbi9d.tfm \
tex-futbi9d.vf \
tex-futbi9e.tfm \
tex-futbi9e.vf \
tex-futbo8c.tfm \
tex-futbo8c.vf \
tex-futbo8r.tfm \
tex-futbo8t.tfm \
tex-futbo8t.vf \
tex-futbo8x.tfm \
tex-futbo9c.tfm \
tex-futbo9c.vf \
tex-futbo9d.tfm \
tex-futbo9d.vf \
tex-futbo9e.tfm \
tex-futbo9e.vf \
tex-futboorn.tfm \
tex-futboorn.vf \
tex-futborn.tfm \
tex-futborn.vf \
tex-futc-sup.tfm \
tex-futc-sup.vf \
tex-futc8r.tfm \
tex-futc8x.tfm \
tex-futc9c.tfm \
tex-futc9c.vf \
tex-futc9d.tfm \
tex-futc9d.vf \
tex-futc9e.tfm \
tex-futc9e.vf \
tex-futcorn.tfm \
tex-futcorn.vf \
tex-futmi.tfm \
tex-futmi.vf \
tex-futmib.tfm \
tex-futmib.vf \
tex-futmii.tfm \
tex-futmii.vf \
tex-futmiib.tfm \
tex-futmiib.vf \
tex-futr-sup.tfm \
tex-futr-sup.vf \
tex-futr8c.tfm \
tex-futr8c.vf \
tex-futr8r.tfm \
tex-futr8t.tfm \
tex-futr8t.vf \
tex-futr8x.tfm \
tex-futr9c.tfm \
tex-futr9c.vf \
tex-futr9d.tfm \
tex-futr9d.vf \
tex-futr9e.tfm \
tex-futr9e.vf \
tex-futrc8r.tfm \
tex-futrc8t.tfm \
tex-futrc8t.vf \
tex-futrc9d.tfm \
tex-futrc9d.vf \
tex-futrc9e.tfm \
tex-futrc9e.vf \
tex-futrci9d.tfm \
tex-futrci9d.vf \
tex-futrci9e.tfm \
tex-futrci9e.vf \
tex-futrco8r.tfm \
tex-futrco9d.tfm \
tex-futrco9d.vf \
tex-futrd8r.tfm \
tex-futrd8t.tfm \
tex-futrd8t.vf \
tex-futri-sup.tfm \
tex-futri-sup.vf \
tex-futri8c.tfm \
tex-futri8c.vf \
tex-futri8r.tfm \
tex-futri8t.tfm \
tex-futri8t.vf \
tex-futri8x.tfm \
tex-futri9c.tfm \
tex-futri9c.vf \
tex-futri9d.tfm \
tex-futri9d.vf \
tex-futri9e.tfm \
tex-futri9e.vf \
tex-futro8c.tfm \
tex-futro8c.vf \
tex-futro8r.tfm \
tex-futro8t.tfm \
tex-futro8t.vf \
tex-futro8x.tfm \
tex-futro9c.tfm \
tex-futro9c.vf \
tex-futro9d.tfm \
tex-futro9d.vf \
tex-futro9e.tfm \
tex-futro9e.vf \
tex-futroorn.tfm \
tex-futroorn.vf \
tex-futrorn.tfm \
tex-futrorn.vf \
tex-futs-sup.tfm \
tex-futs-sup.vf \
tex-futs8r.tfm \
tex-futs8x.tfm \
tex-futs9c.tfm \
tex-futs9c.vf \
tex-futs9d.tfm \
tex-futs9d.vf \
tex-futs9e.tfm \
tex-futs9e.vf \
tex-futsc8r.tfm \
tex-futsc9d.tfm \
tex-futsc9d.vf \
tex-futsc9e.tfm \
tex-futsc9e.vf \
tex-futsci9d.tfm \
tex-futsci9d.vf \
tex-futsci9e.tfm \
tex-futsci9e.vf \
tex-futsco8r.tfm \
tex-futsco9d.vf \
tex-futsi-sup.tfm \
tex-futsi-sup.vf \
tex-futsi8r.tfm \
tex-futsi8x.tfm \
tex-futsi9c.tfm \
tex-futsi9c.vf \
tex-futsi9d.tfm \
tex-futsi9d.vf \
tex-futsi9e.tfm \
tex-futsi9e.vf \
tex-futso8r.tfm \
tex-futso8x.tfm \
tex-futso9c.tfm \
tex-futso9c.vf \
tex-futso9d.tfm \
tex-futso9d.vf \
tex-futso9e.tfm \
tex-futso9e.vf \
tex-futsoorn.tfm \
tex-futsoorn.vf \
tex-futsorn.tfm \
tex-futsorn.vf \
tex-futsy.tfm \
tex-futsy.vf \
tex-putb8a.tfm \
tex-putb8x.tfm \
tex-putbi8a.tfm \
tex-putbi8x.tfm \
tex-putbo8x.tfm \
tex-putc8a.tfm \
tex-putc8x.tfm \
tex-putr8a.tfm \
tex-putr8x.tfm \
tex-putrc8a.tfm \
tex-putrd8a.tfm \
tex-putri8a.tfm \
tex-putri8x.tfm \
tex-putro8x.tfm \
tex-puts8a.tfm \
tex-puts8x.tfm \
tex-putsc8a.tfm \
tex-putsi8a.tfm \
tex-putsi8x.tfm \
tex-putso8x.tfm \
tex-t1fut-sup.fd \
tex-t1futj.fd \
tex-t1futs.fd \
tex-t1futx.fd \
tex-ts1futj.fd \
tex-ts1futs.fd \
tex-ts1futx.fd \
tex-ufuts.fd \
texlive-fourier"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontenc.sty \
tex-fontspec.sty \
tex-iftex.sty \
tex-textcomp.sty \
tex-updmap.cfg \
texlive \
texlive-filesystem \
texlive-fourier-fonts \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
