SUMMARY = "Replace pk fonts in PostScript with Type 1 fonts"
DESCRIPTION = "The perl script pkfix looks for DVIPSBitmapFont comments in \
PostScript files, generated by 'not too old' dvips, and \
replaces them by type 1 versions of the fonts, if possible."
LICENSE = "LPPL-1.0"

PV = "2023.209.1.7svn26032"

RPM_NAME = "texlive-pkfix-2023.209.1.7svn26032-52.1.noarch.rpm"
RPM_HASH = "c66f0f953de6e5b7cbfb3a7a56b3d036a30c5552d6004497aaa08de99b5d3b84de042dd20ca98aea0f6e037083d83e77164acc9eda3a8d87e309e79b2198d0d6"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "texlive-pkfix"

RDEPENDS:${PN} += "/usr/bin/perl \
/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
perl-Getopt--Long \
perl-strict \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-pkfix-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
