SUMMARY = "Replace pk fonts in PostScript with Type 1 fonts"
DESCRIPTION = "The perl script pkfix looks for DVIPSBitmapFont comments in \
PostScript files, generated by 'not too old' dvips, and \
replaces them by type 1 versions of the fonts, if possible."
LICENSE = "LPPL-1.0"

PV = "2023.201.1.7svn26032"

RPM_NAME = "texlive-pkfix-2023.201.1.7svn26032-51.1.noarch.rpm"
RPM_HASH = "3320f16c2a9c1cf14cf6b6658a72622aab56ab627949ce8eeb6c27910699c1d1da686ace1599eb25d9f8d405431a6d16c1cc4289ef3c3926ffb9c8f65f44997e"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "texlive-pkfix"

RDEPENDS:${PN} += "/usr/bin/perl \
/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
perl-Getopt--Long \
perl-strict \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-pkfix-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
