SUMMARY = "Playfair Display fonts with LaTeX support"
DESCRIPTION = "This package provides the PlayFairDisplay family of fonts, \
designed by Claus Eggers Sorensen, for use with LaTeX, \
pdfLaTeX, XeLaTeX and LuaLaTeX. PlayFairDisplay is well suited \
for titling and headlines. It has an extra large x-height and \
short descenders. It can be set with no leading if space is \
tight, for instance in news headlines, or for stylistic effect \
in titles. Capitals are extra short, and only very slightly \
heavier than the lowercase characters. This helps achieve a \
more even typographical colour when typesetting proper nouns \
and initialisms."
LICENSE = "OFL-1.1"

PV = "2023.201.svn64857"

RPM_NAME = "texlive-playfair-2023.201.svn64857-52.1.noarch.rpm"
RPM_HASH = "51952e9b3a27d365d9022047133d47919cb8b853d8406a2da52b69e623ca0916603e3633be6b954e49da032cb5467070cdb7c4b308be4dcfdf9a8a55260f63d6"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-LY1PlyfrDisplay-LF.fd \
tex-LY1PlyfrDisplay-OsF.fd \
tex-LY1PlyfrDisplay-Sup.fd \
tex-OT1PlyfrDisplay-LF.fd \
tex-OT1PlyfrDisplay-OsF.fd \
tex-OT1PlyfrDisplay-Sup.fd \
tex-PlayfairDisplay.map \
tex-PlayfairDisplay.sty \
tex-PlyfrDisplay-Black-lf-ly1--base.tfm \
tex-PlyfrDisplay-Black-lf-ly1.tfm \
tex-PlyfrDisplay-Black-lf-ly1.vf \
tex-PlyfrDisplay-Black-lf-ot1.tfm \
tex-PlyfrDisplay-Black-lf-sc-ly1--base.tfm \
tex-PlyfrDisplay-Black-lf-sc-ly1.tfm \
tex-PlyfrDisplay-Black-lf-sc-ly1.vf \
tex-PlyfrDisplay-Black-lf-sc-ot1--base.tfm \
tex-PlyfrDisplay-Black-lf-sc-ot1.tfm \
tex-PlyfrDisplay-Black-lf-sc-ot1.vf \
tex-PlyfrDisplay-Black-lf-sc-t1--base.tfm \
tex-PlyfrDisplay-Black-lf-sc-t1.tfm \
tex-PlyfrDisplay-Black-lf-sc-t1.vf \
tex-PlyfrDisplay-Black-lf-t1--base.tfm \
tex-PlyfrDisplay-Black-lf-t1.tfm \
tex-PlyfrDisplay-Black-lf-t1.vf \
tex-PlyfrDisplay-Black-lf-ts1--base.tfm \
tex-PlyfrDisplay-Black-lf-ts1.tfm \
tex-PlyfrDisplay-Black-lf-ts1.vf \
tex-PlyfrDisplay-Black-osf-ly1--base.tfm \
tex-PlyfrDisplay-Black-osf-ly1.tfm \
tex-PlyfrDisplay-Black-osf-ly1.vf \
tex-PlyfrDisplay-Black-osf-ot1.tfm \
tex-PlyfrDisplay-Black-osf-sc-ly1--base.tfm \
tex-PlyfrDisplay-Black-osf-sc-ly1.tfm \
tex-PlyfrDisplay-Black-osf-sc-ly1.vf \
tex-PlyfrDisplay-Black-osf-sc-ot1--base.tfm \
tex-PlyfrDisplay-Black-osf-sc-ot1.tfm \
tex-PlyfrDisplay-Black-osf-sc-ot1.vf \
tex-PlyfrDisplay-Black-osf-sc-t1--base.tfm \
tex-PlyfrDisplay-Black-osf-sc-t1.tfm \
tex-PlyfrDisplay-Black-osf-sc-t1.vf \
tex-PlyfrDisplay-Black-osf-t1--base.tfm \
tex-PlyfrDisplay-Black-osf-t1.tfm \
tex-PlyfrDisplay-Black-osf-t1.vf \
tex-PlyfrDisplay-Black-osf-ts1--base.tfm \
tex-PlyfrDisplay-Black-osf-ts1.tfm \
tex-PlyfrDisplay-Black-osf-ts1.vf \
tex-PlyfrDisplay-Black-sup-ly1--base.tfm \
tex-PlyfrDisplay-Black-sup-ly1.tfm \
tex-PlyfrDisplay-Black-sup-ly1.vf \
tex-PlyfrDisplay-Black-sup-ot1.tfm \
tex-PlyfrDisplay-Black-sup-t1--base.tfm \
tex-PlyfrDisplay-Black-sup-t1.tfm \
tex-PlyfrDisplay-Black-sup-t1.vf \
tex-PlyfrDisplay-BlackItalic-lf-ly1--base.tfm \
tex-PlyfrDisplay-BlackItalic-lf-ly1.tfm \
tex-PlyfrDisplay-BlackItalic-lf-ly1.vf \
tex-PlyfrDisplay-BlackItalic-lf-ot1.tfm \
tex-PlyfrDisplay-BlackItalic-lf-sc-ly1--base.tfm \
tex-PlyfrDisplay-BlackItalic-lf-sc-ly1.tfm \
tex-PlyfrDisplay-BlackItalic-lf-sc-ly1.vf \
tex-PlyfrDisplay-BlackItalic-lf-sc-ot1--base.tfm \
tex-PlyfrDisplay-BlackItalic-lf-sc-ot1.tfm \
tex-PlyfrDisplay-BlackItalic-lf-sc-ot1.vf \
tex-PlyfrDisplay-BlackItalic-lf-sc-t1--base.tfm \
tex-PlyfrDisplay-BlackItalic-lf-sc-t1.tfm \
tex-PlyfrDisplay-BlackItalic-lf-sc-t1.vf \
tex-PlyfrDisplay-BlackItalic-lf-t1--base.tfm \
tex-PlyfrDisplay-BlackItalic-lf-t1.tfm \
tex-PlyfrDisplay-BlackItalic-lf-t1.vf \
tex-PlyfrDisplay-BlackItalic-lf-ts1--base.tfm \
tex-PlyfrDisplay-BlackItalic-lf-ts1.tfm \
tex-PlyfrDisplay-BlackItalic-lf-ts1.vf \
tex-PlyfrDisplay-BlackItalic-osf-ly1--base.tfm \
tex-PlyfrDisplay-BlackItalic-osf-ly1.tfm \
tex-PlyfrDisplay-BlackItalic-osf-ly1.vf \
tex-PlyfrDisplay-BlackItalic-osf-ot1.tfm \
tex-PlyfrDisplay-BlackItalic-osf-sc-ly1--base.tfm \
tex-PlyfrDisplay-BlackItalic-osf-sc-ly1.tfm \
tex-PlyfrDisplay-BlackItalic-osf-sc-ly1.vf \
tex-PlyfrDisplay-BlackItalic-osf-sc-ot1--base.tfm \
tex-PlyfrDisplay-BlackItalic-osf-sc-ot1.tfm \
tex-PlyfrDisplay-BlackItalic-osf-sc-ot1.vf \
tex-PlyfrDisplay-BlackItalic-osf-sc-t1--base.tfm \
tex-PlyfrDisplay-BlackItalic-osf-sc-t1.tfm \
tex-PlyfrDisplay-BlackItalic-osf-sc-t1.vf \
tex-PlyfrDisplay-BlackItalic-osf-t1--base.tfm \
tex-PlyfrDisplay-BlackItalic-osf-t1.tfm \
tex-PlyfrDisplay-BlackItalic-osf-t1.vf \
tex-PlyfrDisplay-BlackItalic-osf-ts1--base.tfm \
tex-PlyfrDisplay-BlackItalic-osf-ts1.tfm \
tex-PlyfrDisplay-BlackItalic-osf-ts1.vf \
tex-PlyfrDisplay-BlackItalic-sup-ly1--base.tfm \
tex-PlyfrDisplay-BlackItalic-sup-ly1.tfm \
tex-PlyfrDisplay-BlackItalic-sup-ly1.vf \
tex-PlyfrDisplay-BlackItalic-sup-ot1.tfm \
tex-PlyfrDisplay-BlackItalic-sup-t1--base.tfm \
tex-PlyfrDisplay-BlackItalic-sup-t1.tfm \
tex-PlyfrDisplay-BlackItalic-sup-t1.vf \
tex-PlyfrDisplay-Bold-lf-ly1--base.tfm \
tex-PlyfrDisplay-Bold-lf-ly1.tfm \
tex-PlyfrDisplay-Bold-lf-ly1.vf \
tex-PlyfrDisplay-Bold-lf-ot1.tfm \
tex-PlyfrDisplay-Bold-lf-sc-ly1--base.tfm \
tex-PlyfrDisplay-Bold-lf-sc-ly1.tfm \
tex-PlyfrDisplay-Bold-lf-sc-ly1.vf \
tex-PlyfrDisplay-Bold-lf-sc-ot1--base.tfm \
tex-PlyfrDisplay-Bold-lf-sc-ot1.tfm \
tex-PlyfrDisplay-Bold-lf-sc-ot1.vf \
tex-PlyfrDisplay-Bold-lf-sc-t1--base.tfm \
tex-PlyfrDisplay-Bold-lf-sc-t1.tfm \
tex-PlyfrDisplay-Bold-lf-sc-t1.vf \
tex-PlyfrDisplay-Bold-lf-t1--base.tfm \
tex-PlyfrDisplay-Bold-lf-t1.tfm \
tex-PlyfrDisplay-Bold-lf-t1.vf \
tex-PlyfrDisplay-Bold-lf-ts1--base.tfm \
tex-PlyfrDisplay-Bold-lf-ts1.tfm \
tex-PlyfrDisplay-Bold-lf-ts1.vf \
tex-PlyfrDisplay-Bold-osf-ly1--base.tfm \
tex-PlyfrDisplay-Bold-osf-ly1.tfm \
tex-PlyfrDisplay-Bold-osf-ly1.vf \
tex-PlyfrDisplay-Bold-osf-ot1.tfm \
tex-PlyfrDisplay-Bold-osf-sc-ly1--base.tfm \
tex-PlyfrDisplay-Bold-osf-sc-ly1.tfm \
tex-PlyfrDisplay-Bold-osf-sc-ly1.vf \
tex-PlyfrDisplay-Bold-osf-sc-ot1--base.tfm \
tex-PlyfrDisplay-Bold-osf-sc-ot1.tfm \
tex-PlyfrDisplay-Bold-osf-sc-ot1.vf \
tex-PlyfrDisplay-Bold-osf-sc-t1--base.tfm \
tex-PlyfrDisplay-Bold-osf-sc-t1.tfm \
tex-PlyfrDisplay-Bold-osf-sc-t1.vf \
tex-PlyfrDisplay-Bold-osf-t1--base.tfm \
tex-PlyfrDisplay-Bold-osf-t1.tfm \
tex-PlyfrDisplay-Bold-osf-t1.vf \
tex-PlyfrDisplay-Bold-osf-ts1--base.tfm \
tex-PlyfrDisplay-Bold-osf-ts1.tfm \
tex-PlyfrDisplay-Bold-osf-ts1.vf \
tex-PlyfrDisplay-Bold-sup-ly1--base.tfm \
tex-PlyfrDisplay-Bold-sup-ly1.tfm \
tex-PlyfrDisplay-Bold-sup-ly1.vf \
tex-PlyfrDisplay-Bold-sup-ot1.tfm \
tex-PlyfrDisplay-Bold-sup-t1--base.tfm \
tex-PlyfrDisplay-Bold-sup-t1.tfm \
tex-PlyfrDisplay-Bold-sup-t1.vf \
tex-PlyfrDisplay-BoldItalic-lf-ly1--base.tfm \
tex-PlyfrDisplay-BoldItalic-lf-ly1.tfm \
tex-PlyfrDisplay-BoldItalic-lf-ly1.vf \
tex-PlyfrDisplay-BoldItalic-lf-ot1.tfm \
tex-PlyfrDisplay-BoldItalic-lf-sc-ly1--base.tfm \
tex-PlyfrDisplay-BoldItalic-lf-sc-ly1.tfm \
tex-PlyfrDisplay-BoldItalic-lf-sc-ly1.vf \
tex-PlyfrDisplay-BoldItalic-lf-sc-ot1--base.tfm \
tex-PlyfrDisplay-BoldItalic-lf-sc-ot1.tfm \
tex-PlyfrDisplay-BoldItalic-lf-sc-ot1.vf \
tex-PlyfrDisplay-BoldItalic-lf-sc-t1--base.tfm \
tex-PlyfrDisplay-BoldItalic-lf-sc-t1.tfm \
tex-PlyfrDisplay-BoldItalic-lf-sc-t1.vf \
tex-PlyfrDisplay-BoldItalic-lf-t1--base.tfm \
tex-PlyfrDisplay-BoldItalic-lf-t1.tfm \
tex-PlyfrDisplay-BoldItalic-lf-t1.vf \
tex-PlyfrDisplay-BoldItalic-lf-ts1--base.tfm \
tex-PlyfrDisplay-BoldItalic-lf-ts1.tfm \
tex-PlyfrDisplay-BoldItalic-lf-ts1.vf \
tex-PlyfrDisplay-BoldItalic-osf-ly1--base.tfm \
tex-PlyfrDisplay-BoldItalic-osf-ly1.tfm \
tex-PlyfrDisplay-BoldItalic-osf-ly1.vf \
tex-PlyfrDisplay-BoldItalic-osf-ot1.tfm \
tex-PlyfrDisplay-BoldItalic-osf-sc-ly1--base.tfm \
tex-PlyfrDisplay-BoldItalic-osf-sc-ly1.tfm \
tex-PlyfrDisplay-BoldItalic-osf-sc-ly1.vf \
tex-PlyfrDisplay-BoldItalic-osf-sc-ot1--base.tfm \
tex-PlyfrDisplay-BoldItalic-osf-sc-ot1.tfm \
tex-PlyfrDisplay-BoldItalic-osf-sc-ot1.vf \
tex-PlyfrDisplay-BoldItalic-osf-sc-t1--base.tfm \
tex-PlyfrDisplay-BoldItalic-osf-sc-t1.tfm \
tex-PlyfrDisplay-BoldItalic-osf-sc-t1.vf \
tex-PlyfrDisplay-BoldItalic-osf-t1--base.tfm \
tex-PlyfrDisplay-BoldItalic-osf-t1.tfm \
tex-PlyfrDisplay-BoldItalic-osf-t1.vf \
tex-PlyfrDisplay-BoldItalic-osf-ts1--base.tfm \
tex-PlyfrDisplay-BoldItalic-osf-ts1.tfm \
tex-PlyfrDisplay-BoldItalic-osf-ts1.vf \
tex-PlyfrDisplay-BoldItalic-sup-ly1--base.tfm \
tex-PlyfrDisplay-BoldItalic-sup-ly1.tfm \
tex-PlyfrDisplay-BoldItalic-sup-ly1.vf \
tex-PlyfrDisplay-BoldItalic-sup-ot1.tfm \
tex-PlyfrDisplay-BoldItalic-sup-t1--base.tfm \
tex-PlyfrDisplay-BoldItalic-sup-t1.tfm \
tex-PlyfrDisplay-BoldItalic-sup-t1.vf \
tex-PlyfrDisplay-Italic-lf-ly1--base.tfm \
tex-PlyfrDisplay-Italic-lf-ly1.tfm \
tex-PlyfrDisplay-Italic-lf-ly1.vf \
tex-PlyfrDisplay-Italic-lf-ot1.tfm \
tex-PlyfrDisplay-Italic-lf-sc-ly1--base.tfm \
tex-PlyfrDisplay-Italic-lf-sc-ly1.tfm \
tex-PlyfrDisplay-Italic-lf-sc-ly1.vf \
tex-PlyfrDisplay-Italic-lf-sc-ot1--base.tfm \
tex-PlyfrDisplay-Italic-lf-sc-ot1.tfm \
tex-PlyfrDisplay-Italic-lf-sc-ot1.vf \
tex-PlyfrDisplay-Italic-lf-sc-t1--base.tfm \
tex-PlyfrDisplay-Italic-lf-sc-t1.tfm \
tex-PlyfrDisplay-Italic-lf-sc-t1.vf \
tex-PlyfrDisplay-Italic-lf-t1--base.tfm \
tex-PlyfrDisplay-Italic-lf-t1.tfm \
tex-PlyfrDisplay-Italic-lf-t1.vf \
tex-PlyfrDisplay-Italic-lf-ts1--base.tfm \
tex-PlyfrDisplay-Italic-lf-ts1.tfm \
tex-PlyfrDisplay-Italic-lf-ts1.vf \
tex-PlyfrDisplay-Italic-osf-ly1--base.tfm \
tex-PlyfrDisplay-Italic-osf-ly1.tfm \
tex-PlyfrDisplay-Italic-osf-ly1.vf \
tex-PlyfrDisplay-Italic-osf-ot1.tfm \
tex-PlyfrDisplay-Italic-osf-sc-ly1--base.tfm \
tex-PlyfrDisplay-Italic-osf-sc-ly1.tfm \
tex-PlyfrDisplay-Italic-osf-sc-ly1.vf \
tex-PlyfrDisplay-Italic-osf-sc-ot1--base.tfm \
tex-PlyfrDisplay-Italic-osf-sc-ot1.tfm \
tex-PlyfrDisplay-Italic-osf-sc-ot1.vf \
tex-PlyfrDisplay-Italic-osf-sc-t1--base.tfm \
tex-PlyfrDisplay-Italic-osf-sc-t1.tfm \
tex-PlyfrDisplay-Italic-osf-sc-t1.vf \
tex-PlyfrDisplay-Italic-osf-t1--base.tfm \
tex-PlyfrDisplay-Italic-osf-t1.tfm \
tex-PlyfrDisplay-Italic-osf-t1.vf \
tex-PlyfrDisplay-Italic-osf-ts1--base.tfm \
tex-PlyfrDisplay-Italic-osf-ts1.tfm \
tex-PlyfrDisplay-Italic-osf-ts1.vf \
tex-PlyfrDisplay-Italic-sup-ly1--base.tfm \
tex-PlyfrDisplay-Italic-sup-ly1.tfm \
tex-PlyfrDisplay-Italic-sup-ly1.vf \
tex-PlyfrDisplay-Italic-sup-ot1.tfm \
tex-PlyfrDisplay-Italic-sup-t1--base.tfm \
tex-PlyfrDisplay-Italic-sup-t1.tfm \
tex-PlyfrDisplay-Italic-sup-t1.vf \
tex-PlyfrDisplay-Regular-lf-ly1--base.tfm \
tex-PlyfrDisplay-Regular-lf-ly1.tfm \
tex-PlyfrDisplay-Regular-lf-ly1.vf \
tex-PlyfrDisplay-Regular-lf-ot1.tfm \
tex-PlyfrDisplay-Regular-lf-sc-ly1--base.tfm \
tex-PlyfrDisplay-Regular-lf-sc-ly1.tfm \
tex-PlyfrDisplay-Regular-lf-sc-ly1.vf \
tex-PlyfrDisplay-Regular-lf-sc-ot1--base.tfm \
tex-PlyfrDisplay-Regular-lf-sc-ot1.tfm \
tex-PlyfrDisplay-Regular-lf-sc-ot1.vf \
tex-PlyfrDisplay-Regular-lf-sc-t1--base.tfm \
tex-PlyfrDisplay-Regular-lf-sc-t1.tfm \
tex-PlyfrDisplay-Regular-lf-sc-t1.vf \
tex-PlyfrDisplay-Regular-lf-t1--base.tfm \
tex-PlyfrDisplay-Regular-lf-t1.tfm \
tex-PlyfrDisplay-Regular-lf-t1.vf \
tex-PlyfrDisplay-Regular-lf-ts1--base.tfm \
tex-PlyfrDisplay-Regular-lf-ts1.tfm \
tex-PlyfrDisplay-Regular-lf-ts1.vf \
tex-PlyfrDisplay-Regular-osf-ly1--base.tfm \
tex-PlyfrDisplay-Regular-osf-ly1.tfm \
tex-PlyfrDisplay-Regular-osf-ly1.vf \
tex-PlyfrDisplay-Regular-osf-ot1.tfm \
tex-PlyfrDisplay-Regular-osf-sc-ly1--base.tfm \
tex-PlyfrDisplay-Regular-osf-sc-ly1.tfm \
tex-PlyfrDisplay-Regular-osf-sc-ly1.vf \
tex-PlyfrDisplay-Regular-osf-sc-ot1--base.tfm \
tex-PlyfrDisplay-Regular-osf-sc-ot1.tfm \
tex-PlyfrDisplay-Regular-osf-sc-ot1.vf \
tex-PlyfrDisplay-Regular-osf-sc-t1--base.tfm \
tex-PlyfrDisplay-Regular-osf-sc-t1.tfm \
tex-PlyfrDisplay-Regular-osf-sc-t1.vf \
tex-PlyfrDisplay-Regular-osf-t1--base.tfm \
tex-PlyfrDisplay-Regular-osf-t1.tfm \
tex-PlyfrDisplay-Regular-osf-t1.vf \
tex-PlyfrDisplay-Regular-osf-ts1--base.tfm \
tex-PlyfrDisplay-Regular-osf-ts1.tfm \
tex-PlyfrDisplay-Regular-osf-ts1.vf \
tex-PlyfrDisplay-Regular-sup-ly1--base.tfm \
tex-PlyfrDisplay-Regular-sup-ly1.tfm \
tex-PlyfrDisplay-Regular-sup-ly1.vf \
tex-PlyfrDisplay-Regular-sup-ot1.tfm \
tex-PlyfrDisplay-Regular-sup-t1--base.tfm \
tex-PlyfrDisplay-Regular-sup-t1.tfm \
tex-PlyfrDisplay-Regular-sup-t1.vf \
tex-T1PlyfrDisplay-LF.fd \
tex-T1PlyfrDisplay-OsF.fd \
tex-T1PlyfrDisplay-Sup.fd \
tex-TS1PlyfrDisplay-LF.fd \
tex-TS1PlyfrDisplay-OsF.fd \
tex-plyfr-3udzka.enc \
tex-plyfr-4avjba.enc \
tex-plyfr-4srszf.enc \
tex-plyfr-b7y4dd.enc \
tex-plyfr-chpa4l.enc \
tex-plyfr-eb5cw4.enc \
tex-plyfr-fmyrgi.enc \
tex-plyfr-gb53zg.enc \
tex-plyfr-h54wtc.enc \
tex-plyfr-he4k5f.enc \
tex-plyfr-j7rmxo.enc \
tex-plyfr-jk5hji.enc \
tex-plyfr-jowrio.enc \
tex-plyfr-kdf3ua.enc \
tex-plyfr-kzslp6.enc \
tex-plyfr-me7kyw.enc \
tex-plyfr-q6cjrr.enc \
tex-plyfr-qfnkfj.enc \
tex-plyfr-vw64ij.enc \
tex-plyfr-ygz7pk.enc \
texlive-playfair"

RDEPENDS:${PN} += "/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontaxes.sty \
tex-fontenc.sty \
tex-fontspec.sty \
tex-ifluatex.sty \
tex-ifxetex.sty \
tex-mweights.sty \
tex-textcomp.sty \
tex-updmap.cfg \
tex-xkeyval.sty \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-playfair-fonts \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
