SUMMARY = "Client nsswitch/pam/ssh integration for consuming kanidm"
DESCRIPTION = "A localhost resolver and libraries that allow a system to resolve posix \
identities to a kanidm instance."
LICENSE = "MPL-2.0"

PV = "1.1.0~beta13~git2.5d1e2f9"

RPM_NAME = "kanidm-unixd-clients-1.1.0~beta13~git2.5d1e2f9-1.1.aarch64.rpm"
RPM_HASH = "3bc1385caf82b6c1aa816ea0a8b324846606e131d325d3be4ddb0a42473526dc1aba1b1d43e8926dbe6b7f7169e84abf62222e4ea76138b7e3bbe7d585a39ae0"

RPROVIDES:${PN} += "bundled-rust-crate-adler \
bundled-rust-crate-ahash \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-allocator-api2 \
bundled-rust-crate-anstream \
bundled-rust-crate-anstyle \
bundled-rust-crate-anstyle-parse \
bundled-rust-crate-anstyle-query \
bundled-rust-crate-argon2 \
bundled-rust-crate-async-compression \
bundled-rust-crate-async-recursion \
bundled-rust-crate-async-trait \
bundled-rust-crate-authenticator-ctap2-2021 \
bundled-rust-crate-autocfg \
bundled-rust-crate-base32 \
bundled-rust-crate-base64 \
bundled-rust-crate-base64ct \
bundled-rust-crate-base64urlsafedata \
bundled-rust-crate-bindgen \
bundled-rust-crate-bit-set \
bundled-rust-crate-bit-vec \
bundled-rust-crate-bitfield \
bundled-rust-crate-bitflags \
bundled-rust-crate-blake2 \
bundled-rust-crate-block-buffer \
bundled-rust-crate-bumpalo \
bundled-rust-crate-bytemuck \
bundled-rust-crate-byteorder \
bundled-rust-crate-bytes \
bundled-rust-crate-cc \
bundled-rust-crate-cexpr \
bundled-rust-crate-cfg-if \
bundled-rust-crate-checked-int-cast \
bundled-rust-crate-clang-sys \
bundled-rust-crate-clap \
bundled-rust-crate-clap-builder \
bundled-rust-crate-clap-complete \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-color-quant \
bundled-rust-crate-colorchoice \
bundled-rust-crate-compact-jwt \
bundled-rust-crate-console \
bundled-rust-crate-cookie \
bundled-rust-crate-cookie-store \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crypto-common \
bundled-rust-crate-csv \
bundled-rust-crate-csv-core \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-deranged \
bundled-rust-crate-derive-builder \
bundled-rust-crate-derive-builder-core \
bundled-rust-crate-derive-builder-macro \
bundled-rust-crate-dialoguer \
bundled-rust-crate-digest \
bundled-rust-crate-dirs \
bundled-rust-crate-dirs-sys \
bundled-rust-crate-dunce \
bundled-rust-crate-either \
bundled-rust-crate-encoding-rs \
bundled-rust-crate-enumflags2 \
bundled-rust-crate-enumflags2-derive \
bundled-rust-crate-equivalent \
bundled-rust-crate-fallible-iterator \
bundled-rust-crate-fallible-streaming-iterator \
bundled-rust-crate-fancy-regex \
bundled-rust-crate-fastrand \
bundled-rust-crate-file-id \
bundled-rust-crate-filetime \
bundled-rust-crate-flate2 \
bundled-rust-crate-fnv \
bundled-rust-crate-foreign-types \
bundled-rust-crate-foreign-types-shared \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-concurrency \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-generic-array \
bundled-rust-crate-getrandom \
bundled-rust-crate-git2 \
bundled-rust-crate-glob \
bundled-rust-crate-h2 \
bundled-rust-crate-half \
bundled-rust-crate-hashbrown \
bundled-rust-crate-hashlink \
bundled-rust-crate-heck \
bundled-rust-crate-hex \
bundled-rust-crate-hostname-validator \
bundled-rust-crate-http \
bundled-rust-crate-http-body \
bundled-rust-crate-httparse \
bundled-rust-crate-httpdate \
bundled-rust-crate-hyper \
bundled-rust-crate-hyper-tls \
bundled-rust-crate-ident-case \
bundled-rust-crate-idna \
bundled-rust-crate-image \
bundled-rust-crate-indexmap \
bundled-rust-crate-inotify \
bundled-rust-crate-inotify-sys \
bundled-rust-crate-ipnet \
bundled-rust-crate-is-terminal \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jobserver \
bundled-rust-crate-js-sys \
bundled-rust-crate-kanidm-build-profiles \
bundled-rust-crate-kanidm-client \
bundled-rust-crate-kanidm-lib-crypto \
bundled-rust-crate-kanidm-lib-file-permissions \
bundled-rust-crate-kanidm-proto \
bundled-rust-crate-kanidm-tools \
bundled-rust-crate-kanidm-unix-int \
bundled-rust-crate-kanidm-utils-users \
bundled-rust-crate-lazy-static \
bundled-rust-crate-lazycell \
bundled-rust-crate-libc \
bundled-rust-crate-libgit2-sys \
bundled-rust-crate-libloading \
bundled-rust-crate-libnss \
bundled-rust-crate-libsqlite3-sys \
bundled-rust-crate-libssh2-sys \
bundled-rust-crate-libudev \
bundled-rust-crate-libudev-sys \
bundled-rust-crate-libz-sys \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-lru \
bundled-rust-crate-matchers \
bundled-rust-crate-matches \
bundled-rust-crate-mbox \
bundled-rust-crate-memchr \
bundled-rust-crate-mime \
bundled-rust-crate-minimal-lexical \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-native-tls \
bundled-rust-crate-nom \
bundled-rust-crate-notify \
bundled-rust-crate-notify-debouncer-full \
bundled-rust-crate-nss-kanidm \
bundled-rust-crate-nu-ansi-term \
bundled-rust-crate-num-cpus \
bundled-rust-crate-num-derive \
bundled-rust-crate-num-enum \
bundled-rust-crate-num-enum-derive \
bundled-rust-crate-num-integer \
bundled-rust-crate-num-iter \
bundled-rust-crate-num-rational \
bundled-rust-crate-num-threads \
bundled-rust-crate-num-traits \
bundled-rust-crate-oid \
bundled-rust-crate-once-cell \
bundled-rust-crate-openssl \
bundled-rust-crate-openssl-macros \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-openssl-sys \
bundled-rust-crate-overload \
bundled-rust-crate-pam-kanidm \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-password-hash \
bundled-rust-crate-paste \
bundled-rust-crate-paste-impl \
bundled-rust-crate-peeking-take-while \
bundled-rust-crate-peg \
bundled-rust-crate-peg-macros \
bundled-rust-crate-peg-runtime \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-pest \
bundled-rust-crate-picky-asn1 \
bundled-rust-crate-picky-asn1-der \
bundled-rust-crate-picky-asn1-x509 \
bundled-rust-crate-pin-project \
bundled-rust-crate-pin-project-internal \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pin-utils \
bundled-rust-crate-pkg-config \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-prettyplease \
bundled-rust-crate-proc-macro-crate \
bundled-rust-crate-proc-macro-hack \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-psl-types \
bundled-rust-crate-publicsuffix \
bundled-rust-crate-qrcode \
bundled-rust-crate-quick-error \
bundled-rust-crate-quote \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-reference-counted-singleton \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-reqwest \
bundled-rust-crate-rpassword \
bundled-rust-crate-rtoolbox \
bundled-rust-crate-runloop \
bundled-rust-crate-rusqlite \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rustix \
bundled-rust-crate-ryu \
bundled-rust-crate-same-file \
bundled-rust-crate-scim-proto \
bundled-rust-crate-scopeguard \
bundled-rust-crate-selinux \
bundled-rust-crate-selinux-sys \
bundled-rust-crate-semver \
bundled-rust-crate-semver-parser \
bundled-rust-crate-serde \
bundled-rust-crate-serde-bytes \
bundled-rust-crate-serde-cbor \
bundled-rust-crate-serde-cbor-2 \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-urlencoded \
bundled-rust-crate-serde-wasm-bindgen \
bundled-rust-crate-sha2 \
bundled-rust-crate-sharded-slab \
bundled-rust-crate-shell-words \
bundled-rust-crate-shellexpand \
bundled-rust-crate-shlex \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-sketching \
bundled-rust-crate-slab \
bundled-rust-crate-smallvec \
bundled-rust-crate-socket2 \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-strsim \
bundled-rust-crate-subtle \
bundled-rust-crate-syn \
bundled-rust-crate-target-lexicon \
bundled-rust-crate-tempfile \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-local \
bundled-rust-crate-time \
bundled-rust-crate-time-core \
bundled-rust-crate-time-macros \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-native-tls \
bundled-rust-crate-tokio-util \
bundled-rust-crate-toml \
bundled-rust-crate-toml-datetime \
bundled-rust-crate-toml-edit \
bundled-rust-crate-tower-service \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-tracing-forest \
bundled-rust-crate-tracing-log \
bundled-rust-crate-tracing-serde \
bundled-rust-crate-tracing-subscriber \
bundled-rust-crate-try-lock \
bundled-rust-crate-tss-esapi \
bundled-rust-crate-tss-esapi-sys \
bundled-rust-crate-typenum \
bundled-rust-crate-ucd-trie \
bundled-rust-crate-unicode-bidi \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-normalization \
bundled-rust-crate-unicode-width \
bundled-rust-crate-url \
bundled-rust-crate-urlencoding \
bundled-rust-crate-utf8parse \
bundled-rust-crate-uuid \
bundled-rust-crate-vcpkg \
bundled-rust-crate-version-check \
bundled-rust-crate-walkdir \
bundled-rust-crate-want \
bundled-rust-crate-wasm-bindgen \
bundled-rust-crate-wasm-bindgen-backend \
bundled-rust-crate-wasm-bindgen-macro \
bundled-rust-crate-wasm-bindgen-macro-support \
bundled-rust-crate-wasm-bindgen-shared \
bundled-rust-crate-web-sys \
bundled-rust-crate-webauthn-authenticator-rs \
bundled-rust-crate-webauthn-rs-proto \
bundled-rust-crate-which \
bundled-rust-crate-windows \
bundled-rust-crate-winnow \
bundled-rust-crate-zeroize \
bundled-rust-crate-zeroize-derive \
bundled-rust-crate-zstd \
bundled-rust-crate-zstd-safe \
bundled-rust-crate-zstd-sys \
bundled-rust-crate-zxcvbn \
kanidm-unixd-clients \
libnss-kanidm.so.2"

RDEPENDS:${PN} += "/usr/bin/sh \
kanidm-clients \
libc.so.6 \
libcrypto.so.3 \
libgcc-s.so.1 \
libm.so.6 \
libpam.so.0 \
libselinux.so.1 \
libssl.so.3 \
libtss2-esys.so.0 \
libtss2-mu.so.0 \
libtss2-tctildr.so.0 \
system-user-tss \
tpm2.0-tools"

inherit rpm
