SUMMARY = "Launch jobs, organize the output, and dissect the results"
DESCRIPTION = "Lancet is designed to help you organize the output of your research \
tools, store it, and dissect the data you have collected. The output \
of a single simulation or analysis rarely contains all the data you \
need; Lancet helps you generate data from many runs and analyse it \
using your own Python code. \
 \
Parameter spaces often need to be explored for the purpose of \
plotting, tuning, or analysis. Lancet helps you extract the \
information you care about from potentially enormous volumes of data \
generated by such parameter exploration."
LICENSE = "BSD-3-Clause"

PV = "0.9.0"

RPM_NAME = "python310-lancet-ioam-0.9.0-2.22.noarch.rpm"
RPM_HASH = "53e10f91421b43d3a14ebedf9c026e8b562affb0ee2c2f286b4e2f2a7c32bcb11053252a32873ebf31226ac6c7d759ce2bc981a09fffaae3fd17f36406809153"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "python3-lancet-ioam \
python3.10dist-lancet-ioam \
python310-lancet-ioam \
python3dist-lancet-ioam"

RDEPENDS:${PN} += "python-abi"

inherit rpm
