SUMMARY = "Launch jobs, organize the output, and dissect the results"
DESCRIPTION = "Lancet is designed to help you organize the output of your research \
tools, store it, and dissect the data you have collected. The output \
of a single simulation or analysis rarely contains all the data you \
need; Lancet helps you generate data from many runs and analyse it \
using your own Python code. \
 \
Parameter spaces often need to be explored for the purpose of \
plotting, tuning, or analysis. Lancet helps you extract the \
information you care about from potentially enormous volumes of data \
generated by such parameter exploration."
LICENSE = "BSD-3-Clause"

PV = "0.9.0"

RPM_NAME = "python310-lancet-ioam-0.9.0-2.23.noarch.rpm"
RPM_HASH = "8c2f7adabe0aecdcbd272323d7c1c7e5d185a45fbdbaee3aa117f2d5f1477c40759d0bbcabcfc3004b830707ab71ffd0c685b47e56b3060b83ec3ec40928405e"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "python3.10dist-lancet-ioam \
python310-lancet-ioam \
python3dist-lancet-ioam"

RDEPENDS:${PN} += "python-abi"

inherit rpm
