SUMMARY = "A simple class for electronic presentations"
DESCRIPTION = "The elpres class is intended to be used for presentations on a \
screen or with a beamer/projector. It is derived from LaTeX's \
article class and can be used with with LaTeX, pdfLaTeX, and \
LuaLaTeX. The default 'virtual paper size' of presentations \
generated by this class corresponds to a 4:3 (width:height) \
aspect ratio. Other aspect ratios for widescreen monitors \
(16:9, 16:10) may be selected."
LICENSE = "LPPL-1.0"

PV = "2023.209.1.0.1svn60209"

RPM_NAME = "texlive-elpres-2023.209.1.0.1svn60209-54.2.noarch.rpm"
RPM_HASH = "b26f576474f44383dc2851b9df158fd91e9e7ecba1d12a55ec9eeecd163ed175545e8436b02aace804fa0a94429fc93cc2c95d45fe6fdc8cde8fc81d7ec99583"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-elpres.cls \
tex-elpresbluelightgrayscheme.sty \
tex-elpresgrayscheme.sty \
tex-elpreswhitebluescheme.sty \
tex-elpreswhiteredscheme.sty \
tex-elpreswhitetealscheme.sty \
texlive-elpres"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-article.cls \
tex-courier.sty \
tex-fancyhdr.sty \
tex-graphicx.sty \
tex-helvet.sty \
tex-hyperref.sty \
tex-ifthen.sty \
tex-mathptmx.sty \
tex-xcolor.sty \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
