SUMMARY = "An OCaml dependency toolkit -- Development files"
DESCRIPTION = "This package contains development files for package ocaml-dose."
LICENSE = "LGPL-3.0-or-later"

PV = "7.0.0"

RPM_NAME = "ocaml-dose-devel-7.0.0-1.12.aarch64.rpm"
RPM_HASH = "482c54d8a8576924aa1db71b2c3d06377bbdb32924cba319f477f38d882100c150b434cc35f24330767072ae6c43d8eef39ce07ca0cf6e4adcfe6c2feef36b1c"

RPROVIDES:${PN} += "ocaml(Dose_algo) \
ocaml(Dose_algo__Defaultgraphs) \
ocaml(Dose_algo__Depsolver) \
ocaml(Dose_algo__Depsolver_int) \
ocaml(Dose_algo__Diagnostic) \
ocaml(Dose_algo__Dominators) \
ocaml(Dose_algo__Flatten) \
ocaml(Dose_algo__Statistics) \
ocaml(Dose_algo__Strongconflicts) \
ocaml(Dose_algo__Strongconflicts_int) \
ocaml(Dose_algo__Strongdeps) \
ocaml(Dose_common) \
ocaml(Dose_common__CudfAdd) \
ocaml(Dose_common__CudfDiff) \
ocaml(Dose_common__CudfSolver) \
ocaml(Dose_common__EdosSolver) \
ocaml(Dose_common__GitVersionInfo) \
ocaml(Dose_common__Shell_lexer) \
ocaml(Dose_common__Util) \
ocaml(Dose_common__VersionInfo) \
ocaml(Dose_versioning) \
ocaml(Dose_versioning__Debian) \
ocaml(Dose_versioning__Semver) \
ocaml(Dose_versioning__SemverNode) \
ocaml(Dose_versioning__Utils) \
ocaml-dose-devel \
ocaml-dose-devel(aarch-64) \
ocamlfind(dose3) \
ocamlfind(dose3.algo) \
ocamlfind(dose3.common) \
ocamlfind(dose3.versioning) \
ocamlx(Dose_algo) \
ocamlx(Dose_algo__Defaultgraphs) \
ocamlx(Dose_algo__Depsolver) \
ocamlx(Dose_algo__Depsolver_int) \
ocamlx(Dose_algo__Diagnostic) \
ocamlx(Dose_algo__Dominators) \
ocamlx(Dose_algo__Flatten) \
ocamlx(Dose_algo__Statistics) \
ocamlx(Dose_algo__Strongconflicts) \
ocamlx(Dose_algo__Strongconflicts_int) \
ocamlx(Dose_algo__Strongdeps) \
ocamlx(Dose_common) \
ocamlx(Dose_common__CudfAdd) \
ocamlx(Dose_common__CudfDiff) \
ocamlx(Dose_common__CudfSolver) \
ocamlx(Dose_common__EdosSolver) \
ocamlx(Dose_common__GitVersionInfo) \
ocamlx(Dose_common__Shell_lexer) \
ocamlx(Dose_common__Util) \
ocamlx(Dose_common__VersionInfo) \
ocamlx(Dose_versioning) \
ocamlx(Dose_versioning__Debian) \
ocamlx(Dose_versioning__Semver) \
ocamlx(Dose_versioning__SemverNode) \
ocamlx(Dose_versioning__Utils)"
RDEPENDS:${PN} += "ocaml(CamlinternalFormatBasics) \
ocaml(CamlinternalLazy) \
ocaml(CamlinternalOO) \
ocaml(Cudf) \
ocaml(Cudf_checker) \
ocaml(Cudf_conf) \
ocaml(Cudf_parser) \
ocaml(Cudf_printer) \
ocaml(Cudf_types) \
ocaml(Cudf_types_pp) \
ocaml(Enum) \
ocaml(ExtArray) \
ocaml(ExtBuffer) \
ocaml(ExtBytes) \
ocaml(ExtHashtbl) \
ocaml(ExtLib) \
ocaml(ExtList) \
ocaml(ExtString) \
ocaml(Graph) \
ocaml(Graph__) \
ocaml(Graph__Builder) \
ocaml(Graph__Components) \
ocaml(Graph__Dominator) \
ocaml(Graph__Dot) \
ocaml(Graph__Dot_ast) \
ocaml(Graph__Gml) \
ocaml(Graph__Graphml) \
ocaml(Graph__Graphviz) \
ocaml(Graph__Imperative) \
ocaml(Graph__Oper) \
ocaml(Graph__Path) \
ocaml(Graph__Sig) \
ocaml(Graph__Topological) \
ocaml(Graph__Traverse) \
ocaml(IO) \
ocaml(Option) \
ocaml(PMap) \
ocaml(Re) \
ocaml(Re__) \
ocaml(Re__Automata) \
ocaml(Re__Category) \
ocaml(Re__Core) \
ocaml(Re__Cset) \
ocaml(Re__Group) \
ocaml(Re__Pcre) \
ocaml(Re__Pmark) \
ocaml(Re_pcre) \
ocaml(Std) \
ocaml(Stdlib) \
ocaml(Stdlib__Array) \
ocaml(Stdlib__Bigarray) \
ocaml(Stdlib__Buffer) \
ocaml(Stdlib__Bytes) \
ocaml(Stdlib__Char) \
ocaml(Stdlib__Complex) \
ocaml(Stdlib__Digest) \
ocaml(Stdlib__Either) \
ocaml(Stdlib__Filename) \
ocaml(Stdlib__Format) \
ocaml(Stdlib__Hashtbl) \
ocaml(Stdlib__Int32) \
ocaml(Stdlib__Int64) \
ocaml(Stdlib__Lazy) \
ocaml(Stdlib__Lexing) \
ocaml(Stdlib__List) \
ocaml(Stdlib__Map) \
ocaml(Stdlib__Marshal) \
ocaml(Stdlib__Nativeint) \
ocaml(Stdlib__Obj) \
ocaml(Stdlib__Printf) \
ocaml(Stdlib__Queue) \
ocaml(Stdlib__Random) \
ocaml(Stdlib__Scanf) \
ocaml(Stdlib__Seq) \
ocaml(Stdlib__Set) \
ocaml(Stdlib__String) \
ocaml(Stdlib__Sys) \
ocaml(Stdlib__Uchar) \
ocaml(Unix) \
ocaml-dose \
ocamlfind(cudf) \
ocamlfind(extlib) \
ocamlfind(ocamlgraph) \
ocamlfind(re.pcre) \
ocamlfind(stdlib-shims) \
ocamlfind(unix) \
ocamlx(CamlinternalLazy) \
ocamlx(CamlinternalOO) \
ocamlx(Cudf) \
ocamlx(Cudf_checker) \
ocamlx(Cudf_parser) \
ocamlx(Cudf_printer) \
ocamlx(Cudf_types_pp) \
ocamlx(Enum) \
ocamlx(ExtArray) \
ocamlx(ExtBuffer) \
ocamlx(ExtHashtbl) \
ocamlx(ExtLib) \
ocamlx(ExtList) \
ocamlx(ExtString) \
ocamlx(Graph__Builder) \
ocamlx(Graph__Components) \
ocamlx(Graph__Dominator) \
ocamlx(Graph__Dot) \
ocamlx(Graph__Gml) \
ocamlx(Graph__Graphml) \
ocamlx(Graph__Graphviz) \
ocamlx(Graph__Imperative) \
ocamlx(Graph__Oper) \
ocamlx(Graph__Path) \
ocamlx(Graph__Topological) \
ocamlx(Graph__Traverse) \
ocamlx(Option) \
ocamlx(PMap) \
ocamlx(Re_pcre) \
ocamlx(Stdlib) \
ocamlx(Stdlib__Array) \
ocamlx(Stdlib__Buffer) \
ocamlx(Stdlib__Char) \
ocamlx(Stdlib__Digest) \
ocamlx(Stdlib__Filename) \
ocamlx(Stdlib__Format) \
ocamlx(Stdlib__Hashtbl) \
ocamlx(Stdlib__Int32) \
ocamlx(Stdlib__Lexing) \
ocamlx(Stdlib__List) \
ocamlx(Stdlib__Map) \
ocamlx(Stdlib__Marshal) \
ocamlx(Stdlib__Printf) \
ocamlx(Stdlib__Queue) \
ocamlx(Stdlib__Random) \
ocamlx(Stdlib__Scanf) \
ocamlx(Stdlib__Set) \
ocamlx(Stdlib__String) \
ocamlx(Stdlib__Sys) \
ocamlx(Unix)"

inherit rpm
