SUMMARY = "Lua Documentation for lpeg"
DESCRIPTION = "Documentation and examples included with the library, sometimes \
generated by luadoc or ldoc."
LICENSE = "MIT"

PV = "1.1.0"

RPM_NAME = "lua51-lpeg-doc-1.1.0-1.1.noarch.rpm"
RPM_HASH = "0f15b6b87f988fd9bb7655d1fc255d674a606c22b1715f56d941f1b1d1f488e281441354a16d6f0932a71a4630316642e73a0035dc2fecd313c8da002ce8dae5"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "lua51-lpeg-doc"

RDEPENDS:${PN} += "lua51-lpeg"

inherit rpm
