SUMMARY = "Lua Documentation for lpeg"
DESCRIPTION = "Documentation and examples included with the library, sometimes \
generated by luadoc or ldoc."
LICENSE = "MIT"

PV = "1.0.2"

RPM_NAME = "lua51-lpeg-doc-1.0.2-6.3.noarch.rpm"
RPM_HASH = "b492faaafef4afe18885e0998108f1ccf882a620aa5d62d36da0845e4f22f51b0ac46b2a02af0f21643baef905a20bd63101baf55e98667bbd472c0e5fca8424"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "lua51-lpeg-doc"

RDEPENDS:${PN} += "lua51-lpeg"

inherit rpm
