SUMMARY = "Core hyphenation support files"
DESCRIPTION = "Includes Knuth's original hyphen.tex, zerohyph.tex to disable \
hyphenation, language.us which starts the autogenerated files \
language.dat and language.def (and default versions of those), \
etc."
LICENSE = "LPPL-1.0"

PV = "2023.209.svn66413"

RPM_NAME = "texlive-hyphen-base-2023.209.svn66413-54.1.noarch.rpm"
RPM_HASH = "40fc64a0be8298c387038000937509c66cac2c96e71178586adea2f063b6401813e6329c1d9894f9791294fb83842c95b340fa29f1186e04f07266712ca5d72e"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "config-texlive-hyphen-base \
tex-dumyhyph.tex \
tex-hyphen.tex \
tex-hypht1.tex \
tex-language.dat \
tex-language.dat.lua \
tex-language.def \
tex-language.us.def \
tex-zerohyph.tex \
texlive-hyphen-base"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
