SUMMARY = "Core hyphenation support files"
DESCRIPTION = "Includes Knuth's original hyphen.tex, zerohyph.tex to disable \
hyphenation, language.us which starts the autogenerated files \
language.dat and language.def (and default versions of those), \
etc."
LICENSE = "LPPL-1.0"

PV = "2023.208.svn66413"

RPM_NAME = "texlive-hyphen-base-2023.208.svn66413-53.1.noarch.rpm"
RPM_HASH = "b5daad53202e5f5186b6299dcdf2e8481921edddbbf2a660a35a4f96be10af3f21775fefa97555ac93a24b3937cc4fca96393e33deeb0416b3576c4f3e47ec4c"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "config-texlive-hyphen-base \
tex-dumyhyph.tex \
tex-hyphen.tex \
tex-hypht1.tex \
tex-language.dat \
tex-language.dat.lua \
tex-language.def \
tex-language.us.def \
tex-zerohyph.tex \
texlive-hyphen-base"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
