SUMMARY = "GNU patch"
DESCRIPTION = "The GNU patch program is used to apply diffs between original and \
changed files (generated by the diff command) to the original files."
LICENSE = "GPL-3.0-or-later"

PV = "2.7.6"

RPM_NAME = "patch-2.7.6-6.8.aarch64.rpm"
RPM_HASH = "c5fe270616d22ff14c00e60ca383867114f1639f831b78c2f922eb48566d302b21ee3ab9efdf7daed0fa622e614494ab47e14d7eb847f1727fea7d19427f7194"

RPROVIDES:${PN} += "patch \
patch(aarch-64)"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1()(64bit) \
ld-linux-aarch64.so.1(GLIBC_2.17)(64bit) \
libc.so.6(GLIBC_2.34)(64bit)"

inherit rpm
