SUMMARY = "GNU patch"
DESCRIPTION = "The GNU patch program is used to apply diffs between original and \
changed files (generated by the diff command) to the original files."
LICENSE = "GPL-3.0-or-later"

PV = "2.7.6"

RPM_NAME = "patch-2.7.6-6.10.aarch64.rpm"
RPM_HASH = "5c54e530a1dc75ca690abf815c1cddf53afdb841dc7f4ee90c3dd9c669825651b1c9dcbb18966b6e0559ef066e72caed9158747a70ed74ff6e5b65c81c58ecf9"

RPROVIDES:${PN} += "patch"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1 \
libc.so.6"

inherit rpm
