SUMMARY = "The Tilde Toolkit's terminal key sequence database library"
DESCRIPTION = "libt3key is library that provides a database of mappings from escape \
sequences as generated by different consoles and terminals or \
emulators, to key symbols."
LICENSE = "GPL-3.0-only"

PV = "0.2.10"

RPM_NAME = "libt3key1-0.2.10-1.15.aarch64.rpm"
RPM_HASH = "76e24e3bf9049895f83f6a758617dd0a5cce75de5c6daa7b2c2a53d6714e5bcc288336094a39c9babaa52c12e0635dd8aee3eceef1850a30cfffe4e0cf6b1d68"

RPROVIDES:${PN} += "libt3key.so.1 \
libt3key1"

RDEPENDS:${PN} += "/sbin/ldconfig \
ld-linux-aarch64.so.1 \
libc.so.6 \
libt3config.so.0 \
libtinfo.so.6"

inherit rpm
