SUMMARY = "Lightning-fast and Powerful Code Editor written in Rust"
DESCRIPTION = "Lapce is written in pure Rust, with the UI in Druid \
It uses Xi-Editor's Rope Science for text editing, and the \
Wgpu Graphics API for rendering."
LICENSE = "(0BSD | Apache-2.0 | MIT) & (Apache-2.0 | MIT) & (Apache-2.0 | BSL-1.0) & (Apache-2.0 | ISC | MIT) & (Apache-2.0 | MIT) & (Apache-2.0 | MIT | Zlib) & MIT & (Artistic-2.0 | CC0-1.0) & BSD-2-Clause & BSD-3-Clause & BSL-1.0 & CC0-1.0 & ISC & MIT & (MIT | Unlicense) & MPL-2.0 & MPL-2.0+ & Zlib & zlib-acknowledgement & Apache-2.0"

PV = "0.2.8"

RPM_NAME = "lapce-0.2.8-2.1.aarch64.rpm"
RPM_HASH = "befc9ae2914cf7062e26e0e579273bd5d43a33be536770c710e2e6d52d4330222a825fcef1386b7d9ee4e3816fe587c5f044bcc3a3f47a27899910a9daba659b"

RPROVIDES:${PN} += "bundled-rust-crate-Inflector \
bundled-rust-crate-addr2line \
bundled-rust-crate-adler \
bundled-rust-crate-ahash \
bundled-rust-crate-aho-corasick \
bundled-rust-crate-alacritty-config \
bundled-rust-crate-alacritty-config-derive \
bundled-rust-crate-alacritty-terminal \
bundled-rust-crate-ambient-authority \
bundled-rust-crate-ansi-term \
bundled-rust-crate-anyhow \
bundled-rust-crate-arc-swap \
bundled-rust-crate-arrayref \
bundled-rust-crate-arrayvec \
bundled-rust-crate-async-channel \
bundled-rust-crate-async-task \
bundled-rust-crate-async-trait \
bundled-rust-crate-atk \
bundled-rust-crate-atk-sys \
bundled-rust-crate-atomic-waker \
bundled-rust-crate-atty \
bundled-rust-crate-autocfg \
bundled-rust-crate-backtrace \
bundled-rust-crate-base64 \
bundled-rust-crate-bincode \
bundled-rust-crate-bit-field \
bundled-rust-crate-bitflags \
bundled-rust-crate-bitmaps \
bundled-rust-crate-block-buffer \
bundled-rust-crate-blocking \
bundled-rust-crate-bstr \
bundled-rust-crate-bumpalo \
bundled-rust-crate-bytecount \
bundled-rust-crate-bytemuck \
bundled-rust-crate-bytemuck-derive \
bundled-rust-crate-byteorder \
bundled-rust-crate-bytes \
bundled-rust-crate-cache-padded \
bundled-rust-crate-cairo-rs \
bundled-rust-crate-cairo-sys-rs \
bundled-rust-crate-cap-fs-ext \
bundled-rust-crate-cap-primitives \
bundled-rust-crate-cap-rand \
bundled-rust-crate-cap-std \
bundled-rust-crate-cap-time-ext \
bundled-rust-crate-cc \
bundled-rust-crate-cfg-expr \
bundled-rust-crate-cfg-if \
bundled-rust-crate-chrono \
bundled-rust-crate-clap \
bundled-rust-crate-clap-derive \
bundled-rust-crate-clap-lex \
bundled-rust-crate-cmake \
bundled-rust-crate-color-quant \
bundled-rust-crate-combine \
bundled-rust-crate-concurrent-queue \
bundled-rust-crate-config \
bundled-rust-crate-const-cstr \
bundled-rust-crate-cpp-demangle \
bundled-rust-crate-cpufeatures \
bundled-rust-crate-cranelift-bforest \
bundled-rust-crate-cranelift-codegen \
bundled-rust-crate-cranelift-codegen-meta \
bundled-rust-crate-cranelift-codegen-shared \
bundled-rust-crate-cranelift-entity \
bundled-rust-crate-cranelift-frontend \
bundled-rust-crate-cranelift-isle \
bundled-rust-crate-cranelift-native \
bundled-rust-crate-cranelift-wasm \
bundled-rust-crate-crc32fast \
bundled-rust-crate-crossbeam-channel \
bundled-rust-crate-crossbeam-deque \
bundled-rust-crate-crossbeam-epoch \
bundled-rust-crate-crossbeam-utils \
bundled-rust-crate-crypto-common \
bundled-rust-crate-darling \
bundled-rust-crate-darling-core \
bundled-rust-crate-darling-macro \
bundled-rust-crate-data-url \
bundled-rust-crate-digest \
bundled-rust-crate-directories \
bundled-rust-crate-directories-next \
bundled-rust-crate-dirs \
bundled-rust-crate-dirs-next \
bundled-rust-crate-dirs-sys \
bundled-rust-crate-dirs-sys-next \
bundled-rust-crate-dlib \
bundled-rust-crate-druid \
bundled-rust-crate-druid-derive \
bundled-rust-crate-druid-shell \
bundled-rust-crate-dyn-clone \
bundled-rust-crate-either \
bundled-rust-crate-encoding-rs \
bundled-rust-crate-encoding-rs-io \
bundled-rust-crate-env-logger \
bundled-rust-crate-euclid \
bundled-rust-crate-event-listener \
bundled-rust-crate-exr \
bundled-rust-crate-fallible-iterator \
bundled-rust-crate-fastrand \
bundled-rust-crate-fern \
bundled-rust-crate-field-offset \
bundled-rust-crate-file-per-thread-logger \
bundled-rust-crate-filetime \
bundled-rust-crate-fixedbitset \
bundled-rust-crate-flate2 \
bundled-rust-crate-float-cmp \
bundled-rust-crate-float-next-after \
bundled-rust-crate-float-ord \
bundled-rust-crate-fluent-bundle \
bundled-rust-crate-fluent-langneg \
bundled-rust-crate-fluent-syntax \
bundled-rust-crate-flume \
bundled-rust-crate-fnv \
bundled-rust-crate-font-kit \
bundled-rust-crate-fontconfig-parser \
bundled-rust-crate-fontdb \
bundled-rust-crate-foreign-types \
bundled-rust-crate-foreign-types-shared \
bundled-rust-crate-form-urlencoded \
bundled-rust-crate-fount \
bundled-rust-crate-freetype \
bundled-rust-crate-freetype-sys \
bundled-rust-crate-fs-extra \
bundled-rust-crate-fs-set-times \
bundled-rust-crate-fs2 \
bundled-rust-crate-futures \
bundled-rust-crate-futures-channel \
bundled-rust-crate-futures-core \
bundled-rust-crate-futures-executor \
bundled-rust-crate-futures-io \
bundled-rust-crate-futures-lite \
bundled-rust-crate-futures-macro \
bundled-rust-crate-futures-sink \
bundled-rust-crate-futures-task \
bundled-rust-crate-futures-util \
bundled-rust-crate-fuzzy-matcher \
bundled-rust-crate-fxhash \
bundled-rust-crate-gdk \
bundled-rust-crate-gdk-pixbuf \
bundled-rust-crate-gdk-pixbuf-sys \
bundled-rust-crate-gdk-sys \
bundled-rust-crate-generic-array \
bundled-rust-crate-getopts \
bundled-rust-crate-getrandom \
bundled-rust-crate-gif \
bundled-rust-crate-gimli \
bundled-rust-crate-gio \
bundled-rust-crate-gio-sys \
bundled-rust-crate-git2 \
bundled-rust-crate-gl-loader \
bundled-rust-crate-glam \
bundled-rust-crate-glib \
bundled-rust-crate-glib-macros \
bundled-rust-crate-glib-sys \
bundled-rust-crate-glob \
bundled-rust-crate-globset \
bundled-rust-crate-glow \
bundled-rust-crate-gobject-sys \
bundled-rust-crate-grep-matcher \
bundled-rust-crate-grep-regex \
bundled-rust-crate-grep-searcher \
bundled-rust-crate-gtk \
bundled-rust-crate-gtk-sys \
bundled-rust-crate-gtk3-macros \
bundled-rust-crate-h2 \
bundled-rust-crate-half \
bundled-rust-crate-hashbrown \
bundled-rust-crate-heck \
bundled-rust-crate-http \
bundled-rust-crate-http-body \
bundled-rust-crate-httparse \
bundled-rust-crate-httpdate \
bundled-rust-crate-human-sort \
bundled-rust-crate-humantime \
bundled-rust-crate-hyper \
bundled-rust-crate-hyper-tls \
bundled-rust-crate-iana-time-zone \
bundled-rust-crate-ident-case \
bundled-rust-crate-idna \
bundled-rust-crate-ignore \
bundled-rust-crate-im \
bundled-rust-crate-image \
bundled-rust-crate-include-dir \
bundled-rust-crate-include-dir-impl \
bundled-rust-crate-indexmap \
bundled-rust-crate-inotify \
bundled-rust-crate-inotify-sys \
bundled-rust-crate-instant \
bundled-rust-crate-interprocess \
bundled-rust-crate-intl-memoizer \
bundled-rust-crate-intl-pluralrules \
bundled-rust-crate-intmap \
bundled-rust-crate-io-extras \
bundled-rust-crate-io-lifetimes \
bundled-rust-crate-iovec \
bundled-rust-crate-ipnet \
bundled-rust-crate-is-terminal \
bundled-rust-crate-itertools \
bundled-rust-crate-itoa \
bundled-rust-crate-jobserver \
bundled-rust-crate-jpeg-decoder \
bundled-rust-crate-jsonrpc-lite \
bundled-rust-crate-keyboard-types \
bundled-rust-crate-kurbo \
bundled-rust-crate-lapce-core \
bundled-rust-crate-lapce-data \
bundled-rust-crate-lapce-proxy \
bundled-rust-crate-lapce-rpc \
bundled-rust-crate-lapce-ui \
bundled-rust-crate-lapce-xi-rope \
bundled-rust-crate-lazy-static \
bundled-rust-crate-lazycell \
bundled-rust-crate-leb128 \
bundled-rust-crate-lebe \
bundled-rust-crate-libc \
bundled-rust-crate-libgit2-sys \
bundled-rust-crate-libloading \
bundled-rust-crate-libssh2-sys \
bundled-rust-crate-libz-sys \
bundled-rust-crate-linked-hash-map \
bundled-rust-crate-linux-raw-sys \
bundled-rust-crate-locale-config \
bundled-rust-crate-lock-api \
bundled-rust-crate-log \
bundled-rust-crate-log-panics \
bundled-rust-crate-lsp-types \
bundled-rust-crate-lyon \
bundled-rust-crate-lyon-algorithms \
bundled-rust-crate-lyon-geom \
bundled-rust-crate-lyon-path \
bundled-rust-crate-lyon-tessellation \
bundled-rust-crate-matches \
bundled-rust-crate-maybe-owned \
bundled-rust-crate-memchr \
bundled-rust-crate-memfd \
bundled-rust-crate-memmap2 \
bundled-rust-crate-memoffset \
bundled-rust-crate-mime \
bundled-rust-crate-minimal-lexical \
bundled-rust-crate-miniz-oxide \
bundled-rust-crate-mio \
bundled-rust-crate-mio-extras \
bundled-rust-crate-mio-uds \
bundled-rust-crate-nanorand \
bundled-rust-crate-native-tls \
bundled-rust-crate-net2 \
bundled-rust-crate-nix \
bundled-rust-crate-nom \
bundled-rust-crate-notify \
bundled-rust-crate-num-cpus \
bundled-rust-crate-num-integer \
bundled-rust-crate-num-rational \
bundled-rust-crate-num-threads \
bundled-rust-crate-num-traits \
bundled-rust-crate-object \
bundled-rust-crate-once-cell \
bundled-rust-crate-opaque-debug \
bundled-rust-crate-open \
bundled-rust-crate-openssl \
bundled-rust-crate-openssl-macros \
bundled-rust-crate-openssl-probe \
bundled-rust-crate-openssl-src \
bundled-rust-crate-openssl-sys \
bundled-rust-crate-os-str-bytes \
bundled-rust-crate-pango \
bundled-rust-crate-pango-sys \
bundled-rust-crate-parking \
bundled-rust-crate-parking-lot \
bundled-rust-crate-parking-lot-core \
bundled-rust-crate-parley \
bundled-rust-crate-paste \
bundled-rust-crate-pathdiff \
bundled-rust-crate-pathfinder-geometry \
bundled-rust-crate-pathfinder-simd \
bundled-rust-crate-percent-encoding \
bundled-rust-crate-pest \
bundled-rust-crate-petgraph \
bundled-rust-crate-pico-args \
bundled-rust-crate-piet \
bundled-rust-crate-piet-wgpu \
bundled-rust-crate-pin-project \
bundled-rust-crate-pin-project-internal \
bundled-rust-crate-pin-project-lite \
bundled-rust-crate-pin-utils \
bundled-rust-crate-pkg-config \
bundled-rust-crate-png \
bundled-rust-crate-ppv-lite86 \
bundled-rust-crate-proc-macro-crate \
bundled-rust-crate-proc-macro-error \
bundled-rust-crate-proc-macro-error-attr \
bundled-rust-crate-proc-macro-hack \
bundled-rust-crate-proc-macro2 \
bundled-rust-crate-psm \
bundled-rust-crate-psp-types \
bundled-rust-crate-pulldown-cmark \
bundled-rust-crate-quote \
bundled-rust-crate-rand \
bundled-rust-crate-rand-chacha \
bundled-rust-crate-rand-core \
bundled-rust-crate-rand-xoshiro \
bundled-rust-crate-rayon \
bundled-rust-crate-rayon-core \
bundled-rust-crate-rctree \
bundled-rust-crate-regalloc2 \
bundled-rust-crate-regex \
bundled-rust-crate-regex-automata \
bundled-rust-crate-regex-syntax \
bundled-rust-crate-reqwest \
bundled-rust-crate-resvg \
bundled-rust-crate-rgb \
bundled-rust-crate-roxmltree \
bundled-rust-crate-rustc-demangle \
bundled-rust-crate-rustc-hash \
bundled-rust-crate-rustc-version \
bundled-rust-crate-rustix \
bundled-rust-crate-rustybuzz \
bundled-rust-crate-ryu \
bundled-rust-crate-safe-arch \
bundled-rust-crate-same-file \
bundled-rust-crate-scoped-threadpool \
bundled-rust-crate-scopeguard \
bundled-rust-crate-self-cell \
bundled-rust-crate-semver \
bundled-rust-crate-semver-parser \
bundled-rust-crate-serde \
bundled-rust-crate-serde-derive \
bundled-rust-crate-serde-json \
bundled-rust-crate-serde-repr \
bundled-rust-crate-serde-urlencoded \
bundled-rust-crate-serde-yaml \
bundled-rust-crate-sha2 \
bundled-rust-crate-sharded-slab \
bundled-rust-crate-shellexpand \
bundled-rust-crate-sid \
bundled-rust-crate-signal-hook \
bundled-rust-crate-signal-hook-mio \
bundled-rust-crate-signal-hook-registry \
bundled-rust-crate-simplecss \
bundled-rust-crate-siphasher \
bundled-rust-crate-sized-chunks \
bundled-rust-crate-slab \
bundled-rust-crate-sled \
bundled-rust-crate-slice-group-by \
bundled-rust-crate-slotmap \
bundled-rust-crate-smallvec \
bundled-rust-crate-socket2 \
bundled-rust-crate-spin \
bundled-rust-crate-spinning \
bundled-rust-crate-stable-deref-trait \
bundled-rust-crate-strsim \
bundled-rust-crate-structdesc \
bundled-rust-crate-strum \
bundled-rust-crate-strum-macros \
bundled-rust-crate-svgfilters \
bundled-rust-crate-svgtypes \
bundled-rust-crate-swash \
bundled-rust-crate-syn \
bundled-rust-crate-system-deps \
bundled-rust-crate-system-interface \
bundled-rust-crate-tar \
bundled-rust-crate-target-lexicon \
bundled-rust-crate-termcolor \
bundled-rust-crate-textwrap \
bundled-rust-crate-thiserror \
bundled-rust-crate-thiserror-impl \
bundled-rust-crate-thread-id \
bundled-rust-crate-thread-local \
bundled-rust-crate-threadpool \
bundled-rust-crate-tiff \
bundled-rust-crate-time \
bundled-rust-crate-tiny-skia \
bundled-rust-crate-tinystr \
bundled-rust-crate-tinyvec \
bundled-rust-crate-tinyvec-macros \
bundled-rust-crate-tokio \
bundled-rust-crate-tokio-macros \
bundled-rust-crate-tokio-native-tls \
bundled-rust-crate-tokio-socks \
bundled-rust-crate-tokio-util \
bundled-rust-crate-toml \
bundled-rust-crate-toml-edit \
bundled-rust-crate-tower-service \
bundled-rust-crate-tracing \
bundled-rust-crate-tracing-attributes \
bundled-rust-crate-tracing-core \
bundled-rust-crate-tracing-subscriber \
bundled-rust-crate-trash \
bundled-rust-crate-tree-sitter \
bundled-rust-crate-tree-sitter-bash \
bundled-rust-crate-tree-sitter-c \
bundled-rust-crate-tree-sitter-c-sharp \
bundled-rust-crate-tree-sitter-clojure \
bundled-rust-crate-tree-sitter-cmake \
bundled-rust-crate-tree-sitter-cpp \
bundled-rust-crate-tree-sitter-css \
bundled-rust-crate-tree-sitter-d \
bundled-rust-crate-tree-sitter-dart \
bundled-rust-crate-tree-sitter-dockerfile \
bundled-rust-crate-tree-sitter-elixir \
bundled-rust-crate-tree-sitter-elm \
bundled-rust-crate-tree-sitter-erlang \
bundled-rust-crate-tree-sitter-glimmer \
bundled-rust-crate-tree-sitter-glsl \
bundled-rust-crate-tree-sitter-go \
bundled-rust-crate-tree-sitter-hare \
bundled-rust-crate-tree-sitter-haskell \
bundled-rust-crate-tree-sitter-haxe \
bundled-rust-crate-tree-sitter-hcl \
bundled-rust-crate-tree-sitter-html \
bundled-rust-crate-tree-sitter-java \
bundled-rust-crate-tree-sitter-javascript \
bundled-rust-crate-tree-sitter-json \
bundled-rust-crate-tree-sitter-julia \
bundled-rust-crate-tree-sitter-kotlin \
bundled-rust-crate-tree-sitter-latex \
bundled-rust-crate-tree-sitter-lua \
bundled-rust-crate-tree-sitter-md \
bundled-rust-crate-tree-sitter-nix \
bundled-rust-crate-tree-sitter-ocaml \
bundled-rust-crate-tree-sitter-php \
bundled-rust-crate-tree-sitter-prisma-io \
bundled-rust-crate-tree-sitter-protobuf \
bundled-rust-crate-tree-sitter-python \
bundled-rust-crate-tree-sitter-ql \
bundled-rust-crate-tree-sitter-r \
bundled-rust-crate-tree-sitter-ruby \
bundled-rust-crate-tree-sitter-rust \
bundled-rust-crate-tree-sitter-scheme \
bundled-rust-crate-tree-sitter-scss \
bundled-rust-crate-tree-sitter-sql \
bundled-rust-crate-tree-sitter-svelte \
bundled-rust-crate-tree-sitter-swift \
bundled-rust-crate-tree-sitter-toml \
bundled-rust-crate-tree-sitter-typescript \
bundled-rust-crate-tree-sitter-vue \
bundled-rust-crate-tree-sitter-wgsl \
bundled-rust-crate-tree-sitter-xml \
bundled-rust-crate-tree-sitter-yaml \
bundled-rust-crate-tree-sitter-zig \
bundled-rust-crate-try-lock \
bundled-rust-crate-ttf-parser \
bundled-rust-crate-type-map \
bundled-rust-crate-typenum \
bundled-rust-crate-ucd-trie \
bundled-rust-crate-unic-bidi \
bundled-rust-crate-unic-char-property \
bundled-rust-crate-unic-char-range \
bundled-rust-crate-unic-common \
bundled-rust-crate-unic-langid \
bundled-rust-crate-unic-langid-impl \
bundled-rust-crate-unic-ucd-bidi \
bundled-rust-crate-unic-ucd-version \
bundled-rust-crate-unicase \
bundled-rust-crate-unicode-bidi \
bundled-rust-crate-unicode-bidi-mirroring \
bundled-rust-crate-unicode-ccc \
bundled-rust-crate-unicode-general-category \
bundled-rust-crate-unicode-ident \
bundled-rust-crate-unicode-normalization \
bundled-rust-crate-unicode-script \
bundled-rust-crate-unicode-segmentation \
bundled-rust-crate-unicode-vo \
bundled-rust-crate-unicode-width \
bundled-rust-crate-url \
bundled-rust-crate-usvg \
bundled-rust-crate-utf8parse \
bundled-rust-crate-uuid \
bundled-rust-crate-version-check \
bundled-rust-crate-version-compare \
bundled-rust-crate-vte \
bundled-rust-crate-vte-generate-state-changes \
bundled-rust-crate-waker-fn \
bundled-rust-crate-walkdir \
bundled-rust-crate-want \
bundled-rust-crate-wasi-cap-std-sync \
bundled-rust-crate-wasi-common \
bundled-rust-crate-wasi-experimental-http-wasmtime \
bundled-rust-crate-wasm-encoder \
bundled-rust-crate-wasmparser \
bundled-rust-crate-wasmtime \
bundled-rust-crate-wasmtime-asm-macros \
bundled-rust-crate-wasmtime-cache \
bundled-rust-crate-wasmtime-cranelift \
bundled-rust-crate-wasmtime-environ \
bundled-rust-crate-wasmtime-fiber \
bundled-rust-crate-wasmtime-jit \
bundled-rust-crate-wasmtime-jit-debug \
bundled-rust-crate-wasmtime-runtime \
bundled-rust-crate-wasmtime-types \
bundled-rust-crate-wasmtime-wasi \
bundled-rust-crate-wast \
bundled-rust-crate-wat \
bundled-rust-crate-weezl \
bundled-rust-crate-which \
bundled-rust-crate-wiggle \
bundled-rust-crate-wiggle-generate \
bundled-rust-crate-wiggle-macro \
bundled-rust-crate-witx \
bundled-rust-crate-xattr \
bundled-rust-crate-xi-unicode \
bundled-rust-crate-xmlparser \
bundled-rust-crate-xmlwriter \
bundled-rust-crate-yaml-rust \
bundled-rust-crate-yazi \
bundled-rust-crate-yeslogic-fontconfig-sys \
bundled-rust-crate-zeno \
bundled-rust-crate-zstd \
bundled-rust-crate-zstd-safe \
bundled-rust-crate-zstd-sys \
lapce"

RDEPENDS:${PN} += "libc.so.6 \
libcairo-gobject.so.2 \
libcairo.so.2 \
libfontconfig.so.1 \
libfreetype.so.6 \
libgcc-s.so.1 \
libgdk-3.so.0 \
libgdk-pixbuf-2.0.so.0 \
libgio-2.0.so.0 \
libglib-2.0.so.0 \
libgobject-2.0.so.0 \
libgtk-3.so.0 \
libm.so.6 \
libpango-1.0.so.0 \
libstdc++.so.6 \
libz.so.1"

inherit rpm
