SUMMARY = "A TrueType font for mediaevalists"
DESCRIPTION = "Junicode is a TrueType font with many OpenType features for \
antiquarians (especially medievalists) based on typefaces used \
by the Oxford Press in the late 17th and early 18th centuries. \
It works well with Xe(La)TeX."
LICENSE = "OFL-1.1"

PV = "2023.209.1.0.2svn61719"

RPM_NAME = "texlive-junicode-2023.209.1.0.2svn61719-56.1.noarch.rpm"
RPM_HASH = "d33d57cc21fbe3d40019bcb4f454da6d57f77c91dfaf6dafaafb2973c358f3383a98d4fca088022461604d072ff0c0e15f4fa89d01874c97a2c145827f29f400"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-Junicode-Bold-sup-ly1.tfm \
tex-Junicode-Bold-sup-ot1.tfm \
tex-Junicode-Bold-sup-t1--base.tfm \
tex-Junicode-Bold-sup-t1.tfm \
tex-Junicode-Bold-sup-t1.vf \
tex-Junicode-Bold-sup-t3--base.tfm \
tex-Junicode-Bold-sup-t3.tfm \
tex-Junicode-Bold-sup-t3.vf \
tex-Junicode-Bold-sup-ts3.tfm \
tex-Junicode-Bold-tlf-ly1.tfm \
tex-Junicode-Bold-tlf-ot1--base.tfm \
tex-Junicode-Bold-tlf-ot1.tfm \
tex-Junicode-Bold-tlf-ot1.vf \
tex-Junicode-Bold-tlf-sc-ly1--base.tfm \
tex-Junicode-Bold-tlf-sc-ly1.tfm \
tex-Junicode-Bold-tlf-sc-ly1.vf \
tex-Junicode-Bold-tlf-sc-ot1--base.tfm \
tex-Junicode-Bold-tlf-sc-ot1.tfm \
tex-Junicode-Bold-tlf-sc-ot1.vf \
tex-Junicode-Bold-tlf-sc-t1--base.tfm \
tex-Junicode-Bold-tlf-sc-t1.tfm \
tex-Junicode-Bold-tlf-sc-t1.vf \
tex-Junicode-Bold-tlf-sc-t3--base.tfm \
tex-Junicode-Bold-tlf-sc-t3.tfm \
tex-Junicode-Bold-tlf-sc-t3.vf \
tex-Junicode-Bold-tlf-sc-ts3.tfm \
tex-Junicode-Bold-tlf-swash-ly1--base.tfm \
tex-Junicode-Bold-tlf-swash-ly1.tfm \
tex-Junicode-Bold-tlf-swash-ly1.vf \
tex-Junicode-Bold-tlf-swash-ot1--base.tfm \
tex-Junicode-Bold-tlf-swash-ot1.tfm \
tex-Junicode-Bold-tlf-swash-ot1.vf \
tex-Junicode-Bold-tlf-swash-t1--base.tfm \
tex-Junicode-Bold-tlf-swash-t1.tfm \
tex-Junicode-Bold-tlf-swash-t1.vf \
tex-Junicode-Bold-tlf-swash-t3--base.tfm \
tex-Junicode-Bold-tlf-swash-t3.tfm \
tex-Junicode-Bold-tlf-swash-t3.vf \
tex-Junicode-Bold-tlf-swash-ts3.tfm \
tex-Junicode-Bold-tlf-t1--base.tfm \
tex-Junicode-Bold-tlf-t1.tfm \
tex-Junicode-Bold-tlf-t1.vf \
tex-Junicode-Bold-tlf-t3--base.tfm \
tex-Junicode-Bold-tlf-t3.tfm \
tex-Junicode-Bold-tlf-t3.vf \
tex-Junicode-Bold-tlf-ts1--base.tfm \
tex-Junicode-Bold-tlf-ts1.tfm \
tex-Junicode-Bold-tlf-ts1.vf \
tex-Junicode-Bold-tlf-ts3.tfm \
tex-Junicode-Bold-tosf-ly1.tfm \
tex-Junicode-Bold-tosf-ot1--base.tfm \
tex-Junicode-Bold-tosf-ot1.tfm \
tex-Junicode-Bold-tosf-ot1.vf \
tex-Junicode-Bold-tosf-sc-ly1--base.tfm \
tex-Junicode-Bold-tosf-sc-ly1.tfm \
tex-Junicode-Bold-tosf-sc-ly1.vf \
tex-Junicode-Bold-tosf-sc-ot1--base.tfm \
tex-Junicode-Bold-tosf-sc-ot1.tfm \
tex-Junicode-Bold-tosf-sc-ot1.vf \
tex-Junicode-Bold-tosf-sc-t1--base.tfm \
tex-Junicode-Bold-tosf-sc-t1.tfm \
tex-Junicode-Bold-tosf-sc-t1.vf \
tex-Junicode-Bold-tosf-sc-t3--base.tfm \
tex-Junicode-Bold-tosf-sc-t3.tfm \
tex-Junicode-Bold-tosf-sc-t3.vf \
tex-Junicode-Bold-tosf-sc-ts3.tfm \
tex-Junicode-Bold-tosf-swash-ly1--base.tfm \
tex-Junicode-Bold-tosf-swash-ly1.tfm \
tex-Junicode-Bold-tosf-swash-ly1.vf \
tex-Junicode-Bold-tosf-swash-ot1--base.tfm \
tex-Junicode-Bold-tosf-swash-ot1.tfm \
tex-Junicode-Bold-tosf-swash-ot1.vf \
tex-Junicode-Bold-tosf-swash-t1--base.tfm \
tex-Junicode-Bold-tosf-swash-t1.tfm \
tex-Junicode-Bold-tosf-swash-t1.vf \
tex-Junicode-Bold-tosf-swash-t3--base.tfm \
tex-Junicode-Bold-tosf-swash-t3.tfm \
tex-Junicode-Bold-tosf-swash-t3.vf \
tex-Junicode-Bold-tosf-swash-ts3.tfm \
tex-Junicode-Bold-tosf-t1--base.tfm \
tex-Junicode-Bold-tosf-t1.tfm \
tex-Junicode-Bold-tosf-t1.vf \
tex-Junicode-Bold-tosf-t3--base.tfm \
tex-Junicode-Bold-tosf-t3.tfm \
tex-Junicode-Bold-tosf-t3.vf \
tex-Junicode-Bold-tosf-ts1--base.tfm \
tex-Junicode-Bold-tosf-ts1.tfm \
tex-Junicode-Bold-tosf-ts1.vf \
tex-Junicode-Bold-tosf-ts3.tfm \
tex-Junicode-BoldItalic-sup-ly1.tfm \
tex-Junicode-BoldItalic-sup-ot1.tfm \
tex-Junicode-BoldItalic-sup-t1--base.tfm \
tex-Junicode-BoldItalic-sup-t1.tfm \
tex-Junicode-BoldItalic-sup-t1.vf \
tex-Junicode-BoldItalic-sup-t3--base.tfm \
tex-Junicode-BoldItalic-sup-t3.tfm \
tex-Junicode-BoldItalic-sup-t3.vf \
tex-Junicode-BoldItalic-sup-ts3.tfm \
tex-Junicode-BoldItalic-tlf-ly1.tfm \
tex-Junicode-BoldItalic-tlf-ot1--base.tfm \
tex-Junicode-BoldItalic-tlf-ot1.tfm \
tex-Junicode-BoldItalic-tlf-ot1.vf \
tex-Junicode-BoldItalic-tlf-swash-ly1--base.tfm \
tex-Junicode-BoldItalic-tlf-swash-ly1.tfm \
tex-Junicode-BoldItalic-tlf-swash-ly1.vf \
tex-Junicode-BoldItalic-tlf-swash-ot1--base.tfm \
tex-Junicode-BoldItalic-tlf-swash-ot1.tfm \
tex-Junicode-BoldItalic-tlf-swash-ot1.vf \
tex-Junicode-BoldItalic-tlf-swash-t1--base.tfm \
tex-Junicode-BoldItalic-tlf-swash-t1.tfm \
tex-Junicode-BoldItalic-tlf-swash-t1.vf \
tex-Junicode-BoldItalic-tlf-swash-t3--base.tfm \
tex-Junicode-BoldItalic-tlf-swash-t3.tfm \
tex-Junicode-BoldItalic-tlf-swash-t3.vf \
tex-Junicode-BoldItalic-tlf-swash-ts3.tfm \
tex-Junicode-BoldItalic-tlf-t1--base.tfm \
tex-Junicode-BoldItalic-tlf-t1.tfm \
tex-Junicode-BoldItalic-tlf-t1.vf \
tex-Junicode-BoldItalic-tlf-t3--base.tfm \
tex-Junicode-BoldItalic-tlf-t3.tfm \
tex-Junicode-BoldItalic-tlf-t3.vf \
tex-Junicode-BoldItalic-tlf-ts1--base.tfm \
tex-Junicode-BoldItalic-tlf-ts1.tfm \
tex-Junicode-BoldItalic-tlf-ts1.vf \
tex-Junicode-BoldItalic-tlf-ts3.tfm \
tex-Junicode-BoldItalic-tosf-ly1.tfm \
tex-Junicode-BoldItalic-tosf-ot1--base.tfm \
tex-Junicode-BoldItalic-tosf-ot1.tfm \
tex-Junicode-BoldItalic-tosf-ot1.vf \
tex-Junicode-BoldItalic-tosf-swash-ly1--base.tfm \
tex-Junicode-BoldItalic-tosf-swash-ly1.tfm \
tex-Junicode-BoldItalic-tosf-swash-ly1.vf \
tex-Junicode-BoldItalic-tosf-swash-ot1--base.tfm \
tex-Junicode-BoldItalic-tosf-swash-ot1.tfm \
tex-Junicode-BoldItalic-tosf-swash-ot1.vf \
tex-Junicode-BoldItalic-tosf-swash-t1--base.tfm \
tex-Junicode-BoldItalic-tosf-swash-t1.tfm \
tex-Junicode-BoldItalic-tosf-swash-t1.vf \
tex-Junicode-BoldItalic-tosf-swash-t3--base.tfm \
tex-Junicode-BoldItalic-tosf-swash-t3.tfm \
tex-Junicode-BoldItalic-tosf-swash-t3.vf \
tex-Junicode-BoldItalic-tosf-swash-ts3.tfm \
tex-Junicode-BoldItalic-tosf-t1--base.tfm \
tex-Junicode-BoldItalic-tosf-t1.tfm \
tex-Junicode-BoldItalic-tosf-t1.vf \
tex-Junicode-BoldItalic-tosf-t3--base.tfm \
tex-Junicode-BoldItalic-tosf-t3.tfm \
tex-Junicode-BoldItalic-tosf-t3.vf \
tex-Junicode-BoldItalic-tosf-ts1--base.tfm \
tex-Junicode-BoldItalic-tosf-ts1.tfm \
tex-Junicode-BoldItalic-tosf-ts1.vf \
tex-Junicode-BoldItalic-tosf-ts3.tfm \
tex-Junicode-Italic-inf-ly1.tfm \
tex-Junicode-Italic-inf-ot1.tfm \
tex-Junicode-Italic-inf-t1--base.tfm \
tex-Junicode-Italic-inf-t1.tfm \
tex-Junicode-Italic-inf-t1.vf \
tex-Junicode-Italic-inf-t3--base.tfm \
tex-Junicode-Italic-inf-t3.tfm \
tex-Junicode-Italic-inf-t3.vf \
tex-Junicode-Italic-inf-ts3--base.tfm \
tex-Junicode-Italic-inf-ts3.tfm \
tex-Junicode-Italic-inf-ts3.vf \
tex-Junicode-Italic-sup-ly1.tfm \
tex-Junicode-Italic-sup-ot1.tfm \
tex-Junicode-Italic-sup-t1--base.tfm \
tex-Junicode-Italic-sup-t1.tfm \
tex-Junicode-Italic-sup-t1.vf \
tex-Junicode-Italic-sup-t3--base.tfm \
tex-Junicode-Italic-sup-t3.tfm \
tex-Junicode-Italic-sup-t3.vf \
tex-Junicode-Italic-sup-ts3--base.tfm \
tex-Junicode-Italic-sup-ts3.tfm \
tex-Junicode-Italic-sup-ts3.vf \
tex-Junicode-Italic-tlf-ly1.tfm \
tex-Junicode-Italic-tlf-ot1.tfm \
tex-Junicode-Italic-tlf-sc-ly1--base.tfm \
tex-Junicode-Italic-tlf-sc-ly1.tfm \
tex-Junicode-Italic-tlf-sc-ly1.vf \
tex-Junicode-Italic-tlf-sc-ot1--base.tfm \
tex-Junicode-Italic-tlf-sc-ot1.tfm \
tex-Junicode-Italic-tlf-sc-ot1.vf \
tex-Junicode-Italic-tlf-sc-t1--base.tfm \
tex-Junicode-Italic-tlf-sc-t1.tfm \
tex-Junicode-Italic-tlf-sc-t1.vf \
tex-Junicode-Italic-tlf-sc-t3--base.tfm \
tex-Junicode-Italic-tlf-sc-t3.tfm \
tex-Junicode-Italic-tlf-sc-t3.vf \
tex-Junicode-Italic-tlf-sc-ts3--base.tfm \
tex-Junicode-Italic-tlf-sc-ts3.tfm \
tex-Junicode-Italic-tlf-sc-ts3.vf \
tex-Junicode-Italic-tlf-swash-ly1.tfm \
tex-Junicode-Italic-tlf-swash-ot1--base.tfm \
tex-Junicode-Italic-tlf-swash-ot1.tfm \
tex-Junicode-Italic-tlf-swash-ot1.vf \
tex-Junicode-Italic-tlf-swash-t1--base.tfm \
tex-Junicode-Italic-tlf-swash-t1.tfm \
tex-Junicode-Italic-tlf-swash-t1.vf \
tex-Junicode-Italic-tlf-swash-t3--base.tfm \
tex-Junicode-Italic-tlf-swash-t3.tfm \
tex-Junicode-Italic-tlf-swash-t3.vf \
tex-Junicode-Italic-tlf-swash-ts3--base.tfm \
tex-Junicode-Italic-tlf-swash-ts3.tfm \
tex-Junicode-Italic-tlf-swash-ts3.vf \
tex-Junicode-Italic-tlf-t1--base.tfm \
tex-Junicode-Italic-tlf-t1.tfm \
tex-Junicode-Italic-tlf-t1.vf \
tex-Junicode-Italic-tlf-t3--base.tfm \
tex-Junicode-Italic-tlf-t3.tfm \
tex-Junicode-Italic-tlf-t3.vf \
tex-Junicode-Italic-tlf-ts1--base.tfm \
tex-Junicode-Italic-tlf-ts1.tfm \
tex-Junicode-Italic-tlf-ts1.vf \
tex-Junicode-Italic-tlf-ts3--base.tfm \
tex-Junicode-Italic-tlf-ts3.tfm \
tex-Junicode-Italic-tlf-ts3.vf \
tex-Junicode-Italic-tosf-ly1.tfm \
tex-Junicode-Italic-tosf-ot1.tfm \
tex-Junicode-Italic-tosf-sc-ly1--base.tfm \
tex-Junicode-Italic-tosf-sc-ly1.tfm \
tex-Junicode-Italic-tosf-sc-ly1.vf \
tex-Junicode-Italic-tosf-sc-ot1--base.tfm \
tex-Junicode-Italic-tosf-sc-ot1.tfm \
tex-Junicode-Italic-tosf-sc-ot1.vf \
tex-Junicode-Italic-tosf-sc-t1--base.tfm \
tex-Junicode-Italic-tosf-sc-t1.tfm \
tex-Junicode-Italic-tosf-sc-t1.vf \
tex-Junicode-Italic-tosf-sc-t3--base.tfm \
tex-Junicode-Italic-tosf-sc-t3.tfm \
tex-Junicode-Italic-tosf-sc-t3.vf \
tex-Junicode-Italic-tosf-sc-ts3--base.tfm \
tex-Junicode-Italic-tosf-sc-ts3.tfm \
tex-Junicode-Italic-tosf-sc-ts3.vf \
tex-Junicode-Italic-tosf-swash-ly1.tfm \
tex-Junicode-Italic-tosf-swash-ot1--base.tfm \
tex-Junicode-Italic-tosf-swash-ot1.tfm \
tex-Junicode-Italic-tosf-swash-ot1.vf \
tex-Junicode-Italic-tosf-swash-t1--base.tfm \
tex-Junicode-Italic-tosf-swash-t1.tfm \
tex-Junicode-Italic-tosf-swash-t1.vf \
tex-Junicode-Italic-tosf-swash-t3--base.tfm \
tex-Junicode-Italic-tosf-swash-t3.tfm \
tex-Junicode-Italic-tosf-swash-t3.vf \
tex-Junicode-Italic-tosf-swash-ts3--base.tfm \
tex-Junicode-Italic-tosf-swash-ts3.tfm \
tex-Junicode-Italic-tosf-swash-ts3.vf \
tex-Junicode-Italic-tosf-t1--base.tfm \
tex-Junicode-Italic-tosf-t1.tfm \
tex-Junicode-Italic-tosf-t1.vf \
tex-Junicode-Italic-tosf-t3--base.tfm \
tex-Junicode-Italic-tosf-t3.tfm \
tex-Junicode-Italic-tosf-t3.vf \
tex-Junicode-Italic-tosf-ts1--base.tfm \
tex-Junicode-Italic-tosf-ts1.tfm \
tex-Junicode-Italic-tosf-ts1.vf \
tex-Junicode-Italic-tosf-ts3--base.tfm \
tex-Junicode-Italic-tosf-ts3.tfm \
tex-Junicode-Italic-tosf-ts3.vf \
tex-Junicode-inf-ly1.tfm \
tex-Junicode-inf-ot1.tfm \
tex-Junicode-inf-t1--base.tfm \
tex-Junicode-inf-t1.tfm \
tex-Junicode-inf-t1.vf \
tex-Junicode-inf-t3--base.tfm \
tex-Junicode-inf-t3.tfm \
tex-Junicode-inf-t3.vf \
tex-Junicode-inf-ts3--base.tfm \
tex-Junicode-inf-ts3.tfm \
tex-Junicode-inf-ts3.vf \
tex-Junicode-sup-ly1.tfm \
tex-Junicode-sup-ot1.tfm \
tex-Junicode-sup-t1--base.tfm \
tex-Junicode-sup-t1.tfm \
tex-Junicode-sup-t1.vf \
tex-Junicode-sup-t3--base.tfm \
tex-Junicode-sup-t3.tfm \
tex-Junicode-sup-t3.vf \
tex-Junicode-sup-ts3--base.tfm \
tex-Junicode-sup-ts3.tfm \
tex-Junicode-sup-ts3.vf \
tex-Junicode-tlf-ly1.tfm \
tex-Junicode-tlf-ot1.tfm \
tex-Junicode-tlf-sc-ly1--base.tfm \
tex-Junicode-tlf-sc-ly1.tfm \
tex-Junicode-tlf-sc-ly1.vf \
tex-Junicode-tlf-sc-ot1--base.tfm \
tex-Junicode-tlf-sc-ot1.tfm \
tex-Junicode-tlf-sc-ot1.vf \
tex-Junicode-tlf-sc-t1--base.tfm \
tex-Junicode-tlf-sc-t1.tfm \
tex-Junicode-tlf-sc-t1.vf \
tex-Junicode-tlf-sc-t3--base.tfm \
tex-Junicode-tlf-sc-t3.tfm \
tex-Junicode-tlf-sc-t3.vf \
tex-Junicode-tlf-sc-ts3--base.tfm \
tex-Junicode-tlf-sc-ts3.tfm \
tex-Junicode-tlf-sc-ts3.vf \
tex-Junicode-tlf-swash-ly1.tfm \
tex-Junicode-tlf-swash-ot1--base.tfm \
tex-Junicode-tlf-swash-ot1.tfm \
tex-Junicode-tlf-swash-ot1.vf \
tex-Junicode-tlf-swash-t1--base.tfm \
tex-Junicode-tlf-swash-t1.tfm \
tex-Junicode-tlf-swash-t1.vf \
tex-Junicode-tlf-swash-t3--base.tfm \
tex-Junicode-tlf-swash-t3.tfm \
tex-Junicode-tlf-swash-t3.vf \
tex-Junicode-tlf-swash-ts3--base.tfm \
tex-Junicode-tlf-swash-ts3.tfm \
tex-Junicode-tlf-swash-ts3.vf \
tex-Junicode-tlf-t1--base.tfm \
tex-Junicode-tlf-t1.tfm \
tex-Junicode-tlf-t1.vf \
tex-Junicode-tlf-t3--base.tfm \
tex-Junicode-tlf-t3.tfm \
tex-Junicode-tlf-t3.vf \
tex-Junicode-tlf-ts1--base.tfm \
tex-Junicode-tlf-ts1.tfm \
tex-Junicode-tlf-ts1.vf \
tex-Junicode-tlf-ts3--base.tfm \
tex-Junicode-tlf-ts3.tfm \
tex-Junicode-tlf-ts3.vf \
tex-Junicode-tosf-ly1.tfm \
tex-Junicode-tosf-ot1.tfm \
tex-Junicode-tosf-sc-ly1--base.tfm \
tex-Junicode-tosf-sc-ly1.tfm \
tex-Junicode-tosf-sc-ly1.vf \
tex-Junicode-tosf-sc-ot1--base.tfm \
tex-Junicode-tosf-sc-ot1.tfm \
tex-Junicode-tosf-sc-ot1.vf \
tex-Junicode-tosf-sc-t1--base.tfm \
tex-Junicode-tosf-sc-t1.tfm \
tex-Junicode-tosf-sc-t1.vf \
tex-Junicode-tosf-sc-t3--base.tfm \
tex-Junicode-tosf-sc-t3.tfm \
tex-Junicode-tosf-sc-t3.vf \
tex-Junicode-tosf-sc-ts3--base.tfm \
tex-Junicode-tosf-sc-ts3.tfm \
tex-Junicode-tosf-sc-ts3.vf \
tex-Junicode-tosf-swash-ly1.tfm \
tex-Junicode-tosf-swash-ot1--base.tfm \
tex-Junicode-tosf-swash-ot1.tfm \
tex-Junicode-tosf-swash-ot1.vf \
tex-Junicode-tosf-swash-t1--base.tfm \
tex-Junicode-tosf-swash-t1.tfm \
tex-Junicode-tosf-swash-t1.vf \
tex-Junicode-tosf-swash-t3--base.tfm \
tex-Junicode-tosf-swash-t3.tfm \
tex-Junicode-tosf-swash-t3.vf \
tex-Junicode-tosf-swash-ts3--base.tfm \
tex-Junicode-tosf-swash-ts3.tfm \
tex-Junicode-tosf-swash-ts3.vf \
tex-Junicode-tosf-t1--base.tfm \
tex-Junicode-tosf-t1.tfm \
tex-Junicode-tosf-t1.vf \
tex-Junicode-tosf-t3--base.tfm \
tex-Junicode-tosf-t3.tfm \
tex-Junicode-tosf-t3.vf \
tex-Junicode-tosf-ts1--base.tfm \
tex-Junicode-tosf-ts1.tfm \
tex-Junicode-tosf-ts1.vf \
tex-Junicode-tosf-ts3--base.tfm \
tex-Junicode-tosf-ts3.tfm \
tex-Junicode-tosf-ts3.vf \
tex-Junicode.map \
tex-LY1Junicode-Inf.fd \
tex-LY1Junicode-Sup.fd \
tex-LY1Junicode-TLF.fd \
tex-LY1Junicode-TOsF.fd \
tex-OT1Junicode-Inf.fd \
tex-OT1Junicode-Sup.fd \
tex-OT1Junicode-TLF.fd \
tex-OT1Junicode-TOsF.fd \
tex-T1Junicode-Inf.fd \
tex-T1Junicode-Sup.fd \
tex-T1Junicode-TLF.fd \
tex-T1Junicode-TOsF.fd \
tex-T3Junicode-Inf.fd \
tex-T3Junicode-Sup.fd \
tex-T3Junicode-TLF.fd \
tex-T3Junicode-TOsF.fd \
tex-TS1Junicode-TLF.fd \
tex-TS1Junicode-TOsF.fd \
tex-TS3Junicode-Inf.fd \
tex-TS3Junicode-Sup.fd \
tex-TS3Junicode-TLF.fd \
tex-TS3Junicode-TOsF.fd \
tex-a-2bpv3m.enc \
tex-a-2mm3c2.enc \
tex-a-2p6ois.enc \
tex-a-2sfipb.enc \
tex-a-3lniep.enc \
tex-a-3oiwi3.enc \
tex-a-3volwp.enc \
tex-a-3xz3h2.enc \
tex-a-4n6crv.enc \
tex-a-4wispq.enc \
tex-a-4ycye2.enc \
tex-a-5swlfy.enc \
tex-a-6u5uu4.enc \
tex-a-7ds3wq.enc \
tex-a-b5lvdl.enc \
tex-a-b5zcir.enc \
tex-a-bt27yq.enc \
tex-a-buzzjq.enc \
tex-a-bxn3t2.enc \
tex-a-c3r5id.enc \
tex-a-ciujvo.enc \
tex-a-czanfn.enc \
tex-a-daqx6o.enc \
tex-a-ddgo45.enc \
tex-a-dh7eks.enc \
tex-a-dsxmxh.enc \
tex-a-e224kq.enc \
tex-a-e24h5d.enc \
tex-a-eegkrc.enc \
tex-a-egdeql.enc \
tex-a-equvmx.enc \
tex-a-ewwy5y.enc \
tex-a-eyvcqg.enc \
tex-a-fb4xbs.enc \
tex-a-fsg22v.enc \
tex-a-ghwqhd.enc \
tex-a-gus7sm.enc \
tex-a-h747e4.enc \
tex-a-hlkg6v.enc \
tex-a-hzunuz.enc \
tex-a-iahbda.enc \
tex-a-iapetj.enc \
tex-a-iqg3f5.enc \
tex-a-jddr6t.enc \
tex-a-jg27fn.enc \
tex-a-jjpsim.enc \
tex-a-jtxgor.enc \
tex-a-l3mb37.enc \
tex-a-leirnf.enc \
tex-a-lzmc63.enc \
tex-a-m5vvpo.enc \
tex-a-msm5ja.enc \
tex-a-myi6mz.enc \
tex-a-n574it.enc \
tex-a-n5rwri.enc \
tex-a-ncdqoi.enc \
tex-a-nfgurc.enc \
tex-a-ng574l.enc \
tex-a-nxovao.enc \
tex-a-ocfo6w.enc \
tex-a-ofg65e.enc \
tex-a-ovuqp7.enc \
tex-a-oyqcvc.enc \
tex-a-oz2voy.enc \
tex-a-p42lhv.enc \
tex-a-pjlm4h.enc \
tex-a-pyi5bn.enc \
tex-a-q5oomy.enc \
tex-a-qojq43.enc \
tex-a-qrnvns.enc \
tex-a-r5vqsy.enc \
tex-a-re7epd.enc \
tex-a-reswd7.enc \
tex-a-riy3vj.enc \
tex-a-rld3th.enc \
tex-a-rq7kaz.enc \
tex-a-rufiuz.enc \
tex-a-senygh.enc \
tex-a-skkj5j.enc \
tex-a-tgx5t5.enc \
tex-a-ud6k5n.enc \
tex-a-ue6kia.enc \
tex-a-uqrabr.enc \
tex-a-uteiqb.enc \
tex-a-uui4bo.enc \
tex-a-vd2fo2.enc \
tex-a-w3oimd.enc \
tex-a-wqhzsa.enc \
tex-a-x5gcu6.enc \
tex-a-xafpoq.enc \
tex-a-xzdxuw.enc \
tex-a-yabl64.enc \
tex-a-yt7kgf.enc \
tex-a-z2b6ll.enc \
tex-a-zbjpie.enc \
tex-a-zw22co.enc \
tex-a-zyf2d6.enc \
tex-junicode.sty \
tex-mt-Junicode.cfg \
texlive-junicode"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontaxes.sty \
tex-mweights.sty \
tex-textcomp.sty \
tex-updmap.cfg \
tex-xkeyval.sty \
texlive \
texlive-filesystem \
texlive-junicode-fonts \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
