SUMMARY = "An alternative to babel for XeLaTeX and LuaLaTeX"
DESCRIPTION = "This package provides a complete Babel replacement for users of \
LuaLaTeX and XeLaTeX; it relies on the fontspec package, \
version 2.0 at least."
LICENSE = "LPPL-1.0"

PV = "2023.201.1.60svn65792"

RPM_NAME = "texlive-polyglossia-2023.201.1.60svn65792-52.1.noarch.rpm"
RPM_HASH = "05dde8ec57ac613ea4c91264ecf03a0f391bf58ca3d9757c7e4eae2b1012cd7d026ee2f9e9af8952a61812c6ea9f6874c1e823f6e393fd4e6ec794f6b88fbd34"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-arabicdigits.map \
tex-arabicnumbers.sty \
tex-babel-hebrewalph.def \
tex-babelsh.def \
tex-bengalidigits.map \
tex-bengalidigits.sty \
tex-cal-util.def \
tex-devanagaridigits.map \
tex-devanagaridigits.sty \
tex-farsical.sty \
tex-farsidigits.map \
tex-gloss-acadien.ldf \
tex-gloss-aeb.ldf \
tex-gloss-af.ldf \
tex-gloss-afb.ldf \
tex-gloss-afrikaans.ldf \
tex-gloss-albanian.ldf \
tex-gloss-am.ldf \
tex-gloss-american.ldf \
tex-gloss-amharic.ldf \
tex-gloss-apd.ldf \
tex-gloss-ar-IQ.ldf \
tex-gloss-ar-JO.ldf \
tex-gloss-ar-LB.ldf \
tex-gloss-ar-MR.ldf \
tex-gloss-ar-PS.ldf \
tex-gloss-ar-SY.ldf \
tex-gloss-ar-YE.ldf \
tex-gloss-ar.ldf \
tex-gloss-arabic.ldf \
tex-gloss-armenian.ldf \
tex-gloss-arq.ldf \
tex-gloss-ary.ldf \
tex-gloss-arz.ldf \
tex-gloss-ast.ldf \
tex-gloss-asturian.ldf \
tex-gloss-australian.ldf \
tex-gloss-austrian.ldf \
tex-gloss-ayl.ldf \
tex-gloss-bahasa.ldf \
tex-gloss-bahasai.ldf \
tex-gloss-bahasam.ldf \
tex-gloss-basque.ldf \
tex-gloss-be-tarask.ldf \
tex-gloss-be.ldf \
tex-gloss-belarusian.ldf \
tex-gloss-bengali.ldf \
tex-gloss-bg.ldf \
tex-gloss-bn.ldf \
tex-gloss-bo.ldf \
tex-gloss-bosnian.ldf \
tex-gloss-br.ldf \
tex-gloss-brazil.ldf \
tex-gloss-breton.ldf \
tex-gloss-british.ldf \
tex-gloss-bs.ldf \
tex-gloss-bulgarian.ldf \
tex-gloss-ca.ldf \
tex-gloss-canadian.ldf \
tex-gloss-canadien.ldf \
tex-gloss-catalan.ldf \
tex-gloss-chinese.ldf \
tex-gloss-ckb-Arab.ldf \
tex-gloss-ckb-Latn.ldf \
tex-gloss-ckb.ldf \
tex-gloss-cop.ldf \
tex-gloss-coptic.ldf \
tex-gloss-croatian.ldf \
tex-gloss-cy.ldf \
tex-gloss-cz.ldf \
tex-gloss-czech.ldf \
tex-gloss-da.ldf \
tex-gloss-danish.ldf \
tex-gloss-de-AT-1901.ldf \
tex-gloss-de-AT-1996.ldf \
tex-gloss-de-AT.ldf \
tex-gloss-de-CH-1901.ldf \
tex-gloss-de-CH-1996.ldf \
tex-gloss-de-CH.ldf \
tex-gloss-de-DE-1901.ldf \
tex-gloss-de-DE-1996.ldf \
tex-gloss-de-DE.ldf \
tex-gloss-de-Latf-AT-1901.ldf \
tex-gloss-de-Latf-AT-1996.ldf \
tex-gloss-de-Latf-AT.ldf \
tex-gloss-de-Latf-CH-1901.ldf \
tex-gloss-de-Latf-CH-1996.ldf \
tex-gloss-de-Latf-CH.ldf \
tex-gloss-de-Latf-DE-1901.ldf \
tex-gloss-de-Latf-DE-1996.ldf \
tex-gloss-de-Latf-DE.ldf \
tex-gloss-de-Latf.ldf \
tex-gloss-de.ldf \
tex-gloss-divehi.ldf \
tex-gloss-dsb.ldf \
tex-gloss-dutch.ldf \
tex-gloss-dv.ldf \
tex-gloss-el-monoton.ldf \
tex-gloss-el-polyton.ldf \
tex-gloss-el.ldf \
tex-gloss-en-AU.ldf \
tex-gloss-en-CA.ldf \
tex-gloss-en-GB.ldf \
tex-gloss-en-NZ.ldf \
tex-gloss-en-US.ldf \
tex-gloss-en.ldf \
tex-gloss-english.ldf \
tex-gloss-eo.ldf \
tex-gloss-es-ES.ldf \
tex-gloss-es-MX.ldf \
tex-gloss-es.ldf \
tex-gloss-esperanto.ldf \
tex-gloss-estonian.ldf \
tex-gloss-et.ldf \
tex-gloss-eu.ldf \
tex-gloss-fa.ldf \
tex-gloss-farsi.ldf \
tex-gloss-fi.ldf \
tex-gloss-finnish.ldf \
tex-gloss-fr-CA.ldf \
tex-gloss-fr-CH.ldf \
tex-gloss-fr-FR.ldf \
tex-gloss-fr.ldf \
tex-gloss-french.ldf \
tex-gloss-friulan.ldf \
tex-gloss-friulian.ldf \
tex-gloss-fur.ldf \
tex-gloss-ga.ldf \
tex-gloss-gaelic.ldf \
tex-gloss-galician.ldf \
tex-gloss-gd.ldf \
tex-gloss-georgian.ldf \
tex-gloss-german.ldf \
tex-gloss-germanb.ldf \
tex-gloss-gl.ldf \
tex-gloss-grc.ldf \
tex-gloss-greek.ldf \
tex-gloss-he.ldf \
tex-gloss-hebrew.ldf \
tex-gloss-hi.ldf \
tex-gloss-hindi.ldf \
tex-gloss-hr.ldf \
tex-gloss-hsb.ldf \
tex-gloss-hu.ldf \
tex-gloss-hungarian.ldf \
tex-gloss-hy.ldf \
tex-gloss-ia.ldf \
tex-gloss-icelandic.ldf \
tex-gloss-id.ldf \
tex-gloss-interlingua.ldf \
tex-gloss-irish.ldf \
tex-gloss-is.ldf \
tex-gloss-it.ldf \
tex-gloss-italian.ldf \
tex-gloss-ja.ldf \
tex-gloss-japanese.ldf \
tex-gloss-ka.ldf \
tex-gloss-kannada.ldf \
tex-gloss-khmer.ldf \
tex-gloss-km.ldf \
tex-gloss-kmr-Arab.ldf \
tex-gloss-kmr-Latn.ldf \
tex-gloss-kmr.ldf \
tex-gloss-kn.ldf \
tex-gloss-ko.ldf \
tex-gloss-korean.ldf \
tex-gloss-ku-Arab.ldf \
tex-gloss-ku-Latn.ldf \
tex-gloss-ku.ldf \
tex-gloss-kurdish.ldf \
tex-gloss-kurmanji.ldf \
tex-gloss-la-x-classic.ldf \
tex-gloss-la-x-ecclesia.ldf \
tex-gloss-la-x-medieval.ldf \
tex-gloss-la.ldf \
tex-gloss-lao.ldf \
tex-gloss-latin.ldf \
tex-gloss-latinclassic.ldf \
tex-gloss-latinecclesiastic.ldf \
tex-gloss-latinmedieval.ldf \
tex-gloss-latvian.ldf \
tex-gloss-lithuanian.ldf \
tex-gloss-lo.ldf \
tex-gloss-lowersorbian.ldf \
tex-gloss-lsorbian.ldf \
tex-gloss-lt.ldf \
tex-gloss-lv.ldf \
tex-gloss-macedonian.ldf \
tex-gloss-magyar.ldf \
tex-gloss-malay.ldf \
tex-gloss-malayalam.ldf \
tex-gloss-marathi.ldf \
tex-gloss-mk.ldf \
tex-gloss-ml.ldf \
tex-gloss-mn.ldf \
tex-gloss-mongolian.ldf \
tex-gloss-mr.ldf \
tex-gloss-naustrian.ldf \
tex-gloss-nb.ldf \
tex-gloss-newzealand.ldf \
tex-gloss-ngerman.ldf \
tex-gloss-nko.ldf \
tex-gloss-norsk.ldf \
tex-gloss-norwegian.ldf \
tex-gloss-nswissgerman.ldf \
tex-gloss-nynorsk.ldf \
tex-gloss-occitan.ldf \
tex-gloss-pa.ldf \
tex-gloss-persian.ldf \
tex-gloss-piedmontese.ldf \
tex-gloss-polish.ldf \
tex-gloss-polutonikogreek.ldf \
tex-gloss-portuges.ldf \
tex-gloss-portuguese.ldf \
tex-gloss-punjabi.ldf \
tex-gloss-romanian.ldf \
tex-gloss-romansh.ldf \
tex-gloss-russian.ldf \
tex-gloss-sami.ldf \
tex-gloss-samin.ldf \
tex-gloss-sanskrit.ldf \
tex-gloss-scottish.ldf \
tex-gloss-serbian.ldf \
tex-gloss-serbianc.ldf \
tex-gloss-slovak.ldf \
tex-gloss-slovene.ldf \
tex-gloss-slovenian.ldf \
tex-gloss-sorbian.ldf \
tex-gloss-spanish.ldf \
tex-gloss-spanishmx.ldf \
tex-gloss-swedish.ldf \
tex-gloss-swissgerman.ldf \
tex-gloss-syriac.ldf \
tex-gloss-tamil.ldf \
tex-gloss-telugu.ldf \
tex-gloss-thai.ldf \
tex-gloss-tibetan.ldf \
tex-gloss-turkish.ldf \
tex-gloss-turkmen.ldf \
tex-gloss-ug.ldf \
tex-gloss-ukrainian.ldf \
tex-gloss-uppersorbian.ldf \
tex-gloss-urdu.ldf \
tex-gloss-usorbian.ldf \
tex-gloss-uyghur.ldf \
tex-gloss-vietnamese.ldf \
tex-gloss-welsh.ldf \
tex-gloss-zh-CN.ldf \
tex-gloss-zh-TW.ldf \
tex-gurmukhidigits.map \
tex-gurmukhidigits.sty \
tex-hebrewcal.sty \
tex-hijrical.sty \
tex-nkonumbers.sty \
tex-polyglossia.sty \
tex-thaidigits.map \
tex-xgreek-fixes.def \
tex-xpg-cyrillicnumbers.sty \
texlive-polyglossia"

RDEPENDS:${PN} += "/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-bidi.sty \
tex-calc.sty \
tex-etoolbox.sty \
tex-expl3.sty \
tex-fontspec.sty \
tex-iftex.sty \
tex-l3keys2e.sty \
tex-luabidi.sty \
tex-luatexbase.sty \
tex-makecmds.sty \
tex-xkeyval.sty \
tex-xparse.sty \
texlive \
texlive-etoolbox \
texlive-filehook \
texlive-filesystem \
texlive-fontspec \
texlive-iftex \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-makecmds \
texlive-scripts \
texlive-scripts-bin \
texlive-xkeyval"

inherit rpm
