SUMMARY = "Plot-manipulation macros for use in MetaPost"
DESCRIPTION = "MetaPlot is a set of MetaPost macros for manipulating \
pre-generated plots (and similar objects), and formatting them \
for inclusion in a MetaPost figure. The intent is that the \
plots can be generated by some outside program, in an abstract \
manner that does not require making decisions about on-page \
sizing and layout, and then they can be imported into MetaPlot \
and arranged using the full capabilities of MetaPost. Metaplot \
also includes a very flexible set of macros for generating plot \
axes, which may be useful in other contexts as well. Presently, \
MetaPlot is in something of a pre-release beta state; it is \
quite functional, but the syntax of the commands is still \
potentially in flux."
LICENSE = "LPPL-1.0"

PV = "2023.201.0.0.91svn15878"

RPM_NAME = "texlive-metaplot-2023.201.0.0.91svn15878-54.1.noarch.rpm"
RPM_HASH = "17d58a720678852be5f2c9a88dfb630bec4c2d75d0a352ca0b09c7fe9cafba321b15da353c5eabe619a1e2288d7935693eca54066d900fba9539bd828a23cb7d"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "texlive-metaplot"
RDEPENDS:${PN} += "/bin/sh coreutils ed findutils grep sed texlive texlive-filesystem texlive-kpathsea texlive-kpathsea-bin texlive-scripts texlive-scripts-bin"

inherit rpm
