SUMMARY = "Launch jobs, organize the output, and dissect the results"
DESCRIPTION = "Lancet is designed to help you organize the output of your research \
tools, store it, and dissect the data you have collected. The output \
of a single simulation or analysis rarely contains all the data you \
need; Lancet helps you generate data from many runs and analyse it \
using your own Python code. \
 \
Parameter spaces often need to be explored for the purpose of \
plotting, tuning, or analysis. Lancet helps you extract the \
information you care about from potentially enormous volumes of data \
generated by such parameter exploration."
LICENSE = "BSD-3-Clause"

PV = "0.9.0"

RPM_NAME = "python311-lancet-ioam-0.9.0-2.23.noarch.rpm"
RPM_HASH = "9faf05d474dd3115f8a663299fa26dd553517d99f65f83bae0f4ac6bb49dcd8e07cf7faeae26991852b987134eb3d63af6819783101165f0fdd02edfd8fd04a4"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "python3-lancet-ioam \
python3.11dist-lancet-ioam \
python311-lancet-ioam \
python3dist-lancet-ioam"

RDEPENDS:${PN} += "python-abi"

inherit rpm
