SUMMARY = "Lua bindings for libprelude"
DESCRIPTION = "Lua bindings for libprelude generated by SWIG."
LICENSE = "LGPL-2.1-only & LGPL-2.1-or-later"

PV = "5.2.0"

RPM_NAME = "lua-libprelude-5.2.0-2.17.aarch64.rpm"
RPM_HASH = "0c25a3c987286da6536bd8a8f77e961c95608111a0e65c93365f5302ba1fc80217c0bb29f741e8095cb8f897b86d3c61b9a8a9e44462ef69b4959521b9a21376"

RPROVIDES:${PN} += "lua-libprelude"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1 \
libc.so.6 \
libgcc-s.so.1 \
liblua5.4.so.5 \
libprelude.so.28 \
libprelude28 \
libpreludecpp.so.12 \
libstdc++.so.6 \
lua"

inherit rpm
