SUMMARY = "Lua bindings for libprelude"
DESCRIPTION = "Lua bindings for libprelude generated by SWIG."
LICENSE = "LGPL-2.1-only & LGPL-2.1-or-later"

PV = "5.2.0"

RPM_NAME = "lua-libprelude-5.2.0-2.14.aarch64.rpm"
RPM_HASH = "81e5a8f7150d6548de31231fc791a4411e599e92d4504299a534584f7efa5ae2ed5946575d6d594412e4424470be7aadf5c3eb957631fe0f680c7ded23a11a6c"

RPROVIDES:${PN} += "lua-libprelude"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1 \
libc.so.6 \
libgcc-s.so.1 \
liblua5.4.so.5 \
libprelude.so.28 \
libprelude28 \
libpreludecpp.so.12 \
libstdc++.so.6 \
lua"

inherit rpm
