SUMMARY = "Support for the ancient \\emline macro"
DESCRIPTION = "Occasional Documents appear, that use graphics generated by \
texcad from the emtex distribution. These documents often use \
the \\emline macro, which produced lines at an arbitrary \
orientation. The present package emulates the macro, using \
TikZ."
LICENSE = "SUSE-Public-Domain"

PV = "2023.209.1.0svn23440"

RPM_NAME = "texlive-tsemlines-2023.209.1.0svn23440-53.1.noarch.rpm"
RPM_HASH = "ae87e22058a4b3b03d092db06be894d25e2adb8ca5b589d4ddfb53f0d126ca0cd5955a5d5d5d113768c192c2025473d98c7d3dc93a73d155eabd35c490543c66"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-tsemlines.sty \
texlive-tsemlines"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
