SUMMARY = "Thai fonts for LaTeX from TLWG"
DESCRIPTION = "A collection of free Thai fonts, supplied as FontForge sources, \
and with LaTeX .fd files."
LICENSE = "GPL-2.0-or-later"

PV = "2023.201.0.0.7.3svn60817"

RPM_NAME = "texlive-fonts-tlwg-2023.201.0.0.7.3svn60817-52.1.noarch.rpm"
RPM_HASH = "cc3b77e611f7c61c7c28cdc3538a4340b80260f85072b45f14c3367ca14123b9a3f349f739590e605a31b1a3ece83d1483bfbb37f00b315e141ce1b931b269bd"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex(fonts-tlwg.sty) \
tex(garuda.tfm) \
tex(garuda.vf) \
tex(garuda_b.tfm) \
tex(garuda_b.vf) \
tex(garuda_bo.tfm) \
tex(garuda_bo.vf) \
tex(garuda_o.tfm) \
tex(garuda_o.vf) \
tex(kinnari.tfm) \
tex(kinnari.vf) \
tex(kinnari_b.tfm) \
tex(kinnari_b.vf) \
tex(kinnari_bi.tfm) \
tex(kinnari_bi.vf) \
tex(kinnari_bo.tfm) \
tex(kinnari_bo.vf) \
tex(kinnari_i.tfm) \
tex(kinnari_i.vf) \
tex(kinnari_o.tfm) \
tex(kinnari_o.vf) \
tex(laksaman.tfm) \
tex(laksaman.vf) \
tex(laksaman_b.tfm) \
tex(laksaman_b.vf) \
tex(laksaman_bi.tfm) \
tex(laksaman_bi.vf) \
tex(laksaman_i.tfm) \
tex(laksaman_i.vf) \
tex(loma.tfm) \
tex(loma.vf) \
tex(loma_b.tfm) \
tex(loma_b.vf) \
tex(loma_bo.tfm) \
tex(loma_bo.vf) \
tex(loma_o.tfm) \
tex(loma_o.vf) \
tex(lthgaruda.fd) \
tex(lthkinnari.fd) \
tex(lthlaksaman.fd) \
tex(lthloma.fd) \
tex(lthnorasi.fd) \
tex(lthnorasij.fd) \
tex(lthnorj.fd) \
tex(lthnorx.fd) \
tex(lthpurisa.fd) \
tex(lthsawasdee.fd) \
tex(lthtlwg-osf-sc.enc) \
tex(lthtlwg-osf.enc) \
tex(lthtlwg-sc.enc) \
tex(lthtlwg.enc) \
tex(lthttype.fd) \
tex(lthttypist.fd) \
tex(lthumpush.fd) \
tex(lthwaree.fd) \
tex(nectec.map) \
tex(nf.map) \
tex(norasi-osf-sc.tfm) \
tex(norasi-osf-sc.vf) \
tex(norasi-osf.tfm) \
tex(norasi-osf.vf) \
tex(norasi-sc.tfm) \
tex(norasi-sc.vf) \
tex(norasi.tfm) \
tex(norasi.vf) \
tex(norasi_b-osf-sc.tfm) \
tex(norasi_b-osf-sc.vf) \
tex(norasi_b-osf.tfm) \
tex(norasi_b-osf.vf) \
tex(norasi_b-sc.tfm) \
tex(norasi_b-sc.vf) \
tex(norasi_b.tfm) \
tex(norasi_b.vf) \
tex(norasi_bi-osf-sc.tfm) \
tex(norasi_bi-osf-sc.vf) \
tex(norasi_bi-osf.tfm) \
tex(norasi_bi-osf.vf) \
tex(norasi_bi-sc.tfm) \
tex(norasi_bi-sc.vf) \
tex(norasi_bi.tfm) \
tex(norasi_bi.vf) \
tex(norasi_bo-osf-sc.tfm) \
tex(norasi_bo-osf-sc.vf) \
tex(norasi_bo-osf.tfm) \
tex(norasi_bo-osf.vf) \
tex(norasi_bo-sc.tfm) \
tex(norasi_bo-sc.vf) \
tex(norasi_bo.tfm) \
tex(norasi_bo.vf) \
tex(norasi_i-osf-sc.tfm) \
tex(norasi_i-osf-sc.vf) \
tex(norasi_i-osf.tfm) \
tex(norasi_i-osf.vf) \
tex(norasi_i-sc.tfm) \
tex(norasi_i-sc.vf) \
tex(norasi_i.tfm) \
tex(norasi_i.vf) \
tex(norasi_o-osf-sc.tfm) \
tex(norasi_o-osf-sc.vf) \
tex(norasi_o-osf.tfm) \
tex(norasi_o-osf.vf) \
tex(norasi_o-sc.tfm) \
tex(norasi_o-sc.vf) \
tex(norasi_o.tfm) \
tex(norasi_o.vf) \
tex(purisa.tfm) \
tex(purisa.vf) \
tex(purisa_b.tfm) \
tex(purisa_b.vf) \
tex(purisa_bo.tfm) \
tex(purisa_bo.vf) \
tex(purisa_o.tfm) \
tex(purisa_o.vf) \
tex(rgaruda.tfm) \
tex(rgaruda_b.tfm) \
tex(rgaruda_bo.tfm) \
tex(rgaruda_o.tfm) \
tex(rkinnari.tfm) \
tex(rkinnari_b.tfm) \
tex(rkinnari_bi.tfm) \
tex(rkinnari_bo.tfm) \
tex(rkinnari_i.tfm) \
tex(rkinnari_o.tfm) \
tex(rlaksaman.tfm) \
tex(rlaksaman_b.tfm) \
tex(rlaksaman_bi.tfm) \
tex(rlaksaman_i.tfm) \
tex(rloma.tfm) \
tex(rloma_b.tfm) \
tex(rloma_bo.tfm) \
tex(rloma_o.tfm) \
tex(rnorasi-osf-sc.tfm) \
tex(rnorasi-osf.tfm) \
tex(rnorasi-sc.tfm) \
tex(rnorasi.tfm) \
tex(rnorasi_b-osf-sc.tfm) \
tex(rnorasi_b-osf.tfm) \
tex(rnorasi_b-sc.tfm) \
tex(rnorasi_b.tfm) \
tex(rnorasi_bi-osf-sc.tfm) \
tex(rnorasi_bi-osf.tfm) \
tex(rnorasi_bi-sc.tfm) \
tex(rnorasi_bi.tfm) \
tex(rnorasi_bo-osf-sc.tfm) \
tex(rnorasi_bo-osf.tfm) \
tex(rnorasi_bo-sc.tfm) \
tex(rnorasi_bo.tfm) \
tex(rnorasi_i-osf-sc.tfm) \
tex(rnorasi_i-osf.tfm) \
tex(rnorasi_i-sc.tfm) \
tex(rnorasi_i.tfm) \
tex(rnorasi_o-osf-sc.tfm) \
tex(rnorasi_o-osf.tfm) \
tex(rnorasi_o-sc.tfm) \
tex(rnorasi_o.tfm) \
tex(rpurisa.tfm) \
tex(rpurisa_b.tfm) \
tex(rpurisa_bo.tfm) \
tex(rpurisa_o.tfm) \
tex(rsawasdee.tfm) \
tex(rsawasdee_b.tfm) \
tex(rsawasdee_bo.tfm) \
tex(rsawasdee_o.tfm) \
tex(rttype.tfm) \
tex(rttype_b.tfm) \
tex(rttype_bo.tfm) \
tex(rttype_o.tfm) \
tex(rttypist.tfm) \
tex(rttypist_b.tfm) \
tex(rttypist_bo.tfm) \
tex(rttypist_o.tfm) \
tex(rumpush.tfm) \
tex(rumpush_b.tfm) \
tex(rumpush_bo.tfm) \
tex(rumpush_l.tfm) \
tex(rumpush_lo.tfm) \
tex(rumpush_o.tfm) \
tex(rwaree.tfm) \
tex(rwaree_b.tfm) \
tex(rwaree_bo.tfm) \
tex(rwaree_o.tfm) \
tex(sawasdee.tfm) \
tex(sawasdee.vf) \
tex(sawasdee_b.tfm) \
tex(sawasdee_b.vf) \
tex(sawasdee_bo.tfm) \
tex(sawasdee_bo.vf) \
tex(sawasdee_o.tfm) \
tex(sawasdee_o.vf) \
tex(sipa.map) \
tex(tlwg.map) \
tex(ttype.tfm) \
tex(ttype.vf) \
tex(ttype_b.tfm) \
tex(ttype_b.vf) \
tex(ttype_bo.tfm) \
tex(ttype_bo.vf) \
tex(ttype_o.tfm) \
tex(ttype_o.vf) \
tex(ttypist.tfm) \
tex(ttypist.vf) \
tex(ttypist_b.tfm) \
tex(ttypist_b.vf) \
tex(ttypist_bo.tfm) \
tex(ttypist_bo.vf) \
tex(ttypist_o.tfm) \
tex(ttypist_o.vf) \
tex(umpush.tfm) \
tex(umpush.vf) \
tex(umpush_b.tfm) \
tex(umpush_b.vf) \
tex(umpush_bo.tfm) \
tex(umpush_bo.vf) \
tex(umpush_l.tfm) \
tex(umpush_l.vf) \
tex(umpush_lo.tfm) \
tex(umpush_lo.vf) \
tex(umpush_o.tfm) \
tex(umpush_o.vf) \
tex(waree.tfm) \
tex(waree.vf) \
tex(waree_b.tfm) \
tex(waree_b.vf) \
tex(waree_bo.tfm) \
tex(waree_bo.vf) \
tex(waree_o.tfm) \
tex(waree_o.vf) \
texlive-fonts-tlwg"

RDEPENDS:${PN} += "/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex(updmap.cfg) \
tex(xkeyval.sty) \
texlive \
texlive-filesystem \
texlive-fonts-tlwg-fonts \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
