SUMMARY = "Fonts for the Korean language"
DESCRIPTION = "Support for Korean documents written in Korean standard KSC \
codes for LaTeX2e."
LICENSE = "LPPL-1.0"

PV = "2023.201.svn16791"

RPM_NAME = "texlive-uhc-2023.201.svn16791-53.1.noarch.rpm"
RPM_HASH = "1973e33d6721d6213fd81e5c4f30ab5c3a06dd0a35dda46d7a05693b7032a8a1af79556b845454f47b135c8a8054d9b7a838f49aec180fb95f7bc582aa9dfec1"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-umj.map \
tex-umj00.tfm \
tex-umj01.tfm \
tex-umj02.tfm \
tex-umj03.tfm \
tex-umj04.tfm \
tex-umj05.tfm \
tex-umj10.tfm \
tex-umj11.tfm \
tex-umj12.tfm \
tex-umj13.tfm \
tex-umj14.tfm \
tex-umj15.tfm \
tex-umj16.tfm \
tex-umj17.tfm \
tex-umj20.tfm \
tex-umj21.tfm \
tex-umj22.tfm \
tex-umj23.tfm \
tex-umj24.tfm \
tex-umj25.tfm \
tex-umj26.tfm \
tex-umj27.tfm \
tex-umj28.tfm \
tex-umj29.tfm \
tex-umj30.tfm \
tex-umj31.tfm \
tex-umj32.tfm \
tex-umj33.tfm \
tex-umj34.tfm \
tex-umj35.tfm \
tex-umj36.tfm \
tex-umj37.tfm \
tex-umj38.tfm \
tex-umjc00.tfm \
tex-umjc01.tfm \
tex-umjc02.tfm \
tex-umjc03.tfm \
tex-umjc04.tfm \
tex-umjc05.tfm \
tex-umjc10.tfm \
tex-umjc11.tfm \
tex-umjc12.tfm \
tex-umjc13.tfm \
tex-umjc14.tfm \
tex-umjc15.tfm \
tex-umjc16.tfm \
tex-umjc17.tfm \
tex-umjc20.tfm \
tex-umjc21.tfm \
tex-umjc22.tfm \
tex-umjc23.tfm \
tex-umjc24.tfm \
tex-umjc25.tfm \
tex-umjc26.tfm \
tex-umjc27.tfm \
tex-umjc28.tfm \
tex-umjc29.tfm \
tex-umjc30.tfm \
tex-umjc31.tfm \
tex-umjc32.tfm \
tex-umjc33.tfm \
tex-umjc34.tfm \
tex-umjc35.tfm \
tex-umjc36.tfm \
tex-umjc37.tfm \
tex-umjc38.tfm \
tex-umjco00.tfm \
tex-umjco01.tfm \
tex-umjco02.tfm \
tex-umjco03.tfm \
tex-umjco04.tfm \
tex-umjco05.tfm \
tex-umjco10.tfm \
tex-umjco11.tfm \
tex-umjco12.tfm \
tex-umjco13.tfm \
tex-umjco14.tfm \
tex-umjco15.tfm \
tex-umjco16.tfm \
tex-umjco17.tfm \
tex-umjco20.tfm \
tex-umjco21.tfm \
tex-umjco22.tfm \
tex-umjco23.tfm \
tex-umjco24.tfm \
tex-umjco25.tfm \
tex-umjco26.tfm \
tex-umjco27.tfm \
tex-umjco28.tfm \
tex-umjco29.tfm \
tex-umjco30.tfm \
tex-umjco31.tfm \
tex-umjco32.tfm \
tex-umjco33.tfm \
tex-umjco34.tfm \
tex-umjco35.tfm \
tex-umjco36.tfm \
tex-umjco37.tfm \
tex-umjco38.tfm \
tex-umjo00.tfm \
tex-umjo01.tfm \
tex-umjo02.tfm \
tex-umjo03.tfm \
tex-umjo04.tfm \
tex-umjo05.tfm \
tex-umjo10.tfm \
tex-umjo11.tfm \
tex-umjo12.tfm \
tex-umjo13.tfm \
tex-umjo14.tfm \
tex-umjo15.tfm \
tex-umjo16.tfm \
tex-umjo17.tfm \
tex-umjo20.tfm \
tex-umjo21.tfm \
tex-umjo22.tfm \
tex-umjo23.tfm \
tex-umjo24.tfm \
tex-umjo25.tfm \
tex-umjo26.tfm \
tex-umjo27.tfm \
tex-umjo28.tfm \
tex-umjo29.tfm \
tex-umjo30.tfm \
tex-umjo31.tfm \
tex-umjo32.tfm \
tex-umjo33.tfm \
tex-umjo34.tfm \
tex-umjo35.tfm \
tex-umjo36.tfm \
tex-umjo37.tfm \
tex-umjo38.tfm \
tex-umju00.tfm \
tex-umju01.tfm \
tex-umju02.tfm \
tex-umju03.tfm \
tex-umju04.tfm \
tex-umju05.tfm \
tex-umju10.tfm \
tex-umju11.tfm \
tex-umju12.tfm \
tex-umju13.tfm \
tex-umju14.tfm \
tex-umju15.tfm \
tex-umju16.tfm \
tex-umju17.tfm \
tex-umju20.tfm \
tex-umju21.tfm \
tex-umju22.tfm \
tex-umju23.tfm \
tex-umju24.tfm \
tex-umju25.tfm \
tex-umju26.tfm \
tex-umju27.tfm \
tex-umju28.tfm \
tex-umju29.tfm \
tex-umju30.tfm \
tex-umju31.tfm \
tex-umju32.tfm \
tex-umju33.tfm \
tex-umju34.tfm \
tex-umju35.tfm \
tex-umju36.tfm \
tex-umju37.tfm \
tex-umju38.tfm \
tex-umjuo00.tfm \
tex-umjuo01.tfm \
tex-umjuo02.tfm \
tex-umjuo03.tfm \
tex-umjuo04.tfm \
tex-umjuo05.tfm \
tex-umjuo10.tfm \
tex-umjuo11.tfm \
tex-umjuo12.tfm \
tex-umjuo13.tfm \
tex-umjuo14.tfm \
tex-umjuo15.tfm \
tex-umjuo16.tfm \
tex-umjuo17.tfm \
tex-umjuo20.tfm \
tex-umjuo21.tfm \
tex-umjuo22.tfm \
tex-umjuo23.tfm \
tex-umjuo24.tfm \
tex-umjuo25.tfm \
tex-umjuo26.tfm \
tex-umjuo27.tfm \
tex-umjuo28.tfm \
tex-umjuo29.tfm \
tex-umjuo30.tfm \
tex-umjuo31.tfm \
tex-umjuo32.tfm \
tex-umjuo33.tfm \
tex-umjuo34.tfm \
tex-umjuo35.tfm \
tex-umjuo36.tfm \
tex-umjuo37.tfm \
tex-umjuo38.tfm \
tex-umjx00.tfm \
tex-umjx01.tfm \
tex-umjx02.tfm \
tex-umjx03.tfm \
tex-umjx04.tfm \
tex-umjx05.tfm \
tex-umjx10.tfm \
tex-umjx11.tfm \
tex-umjx12.tfm \
tex-umjx13.tfm \
tex-umjx14.tfm \
tex-umjx15.tfm \
tex-umjx16.tfm \
tex-umjx17.tfm \
tex-umjx20.tfm \
tex-umjx21.tfm \
tex-umjx22.tfm \
tex-umjx23.tfm \
tex-umjx24.tfm \
tex-umjx25.tfm \
tex-umjx26.tfm \
tex-umjx27.tfm \
tex-umjx28.tfm \
tex-umjx29.tfm \
tex-umjx30.tfm \
tex-umjx31.tfm \
tex-umjx32.tfm \
tex-umjx33.tfm \
tex-umjx34.tfm \
tex-umjx35.tfm \
tex-umjx36.tfm \
tex-umjx37.tfm \
tex-umjx38.tfm \
tex-umjxo00.tfm \
tex-umjxo01.tfm \
tex-umjxo02.tfm \
tex-umjxo03.tfm \
tex-umjxo04.tfm \
tex-umjxo05.tfm \
tex-umjxo10.tfm \
tex-umjxo11.tfm \
tex-umjxo12.tfm \
tex-umjxo13.tfm \
tex-umjxo14.tfm \
tex-umjxo15.tfm \
tex-umjxo16.tfm \
tex-umjxo17.tfm \
tex-umjxo20.tfm \
tex-umjxo21.tfm \
tex-umjxo22.tfm \
tex-umjxo23.tfm \
tex-umjxo24.tfm \
tex-umjxo25.tfm \
tex-umjxo26.tfm \
tex-umjxo27.tfm \
tex-umjxo28.tfm \
tex-umjxo29.tfm \
tex-umjxo30.tfm \
tex-umjxo31.tfm \
tex-umjxo32.tfm \
tex-umjxo33.tfm \
tex-umjxo34.tfm \
tex-umjxo35.tfm \
tex-umjxo36.tfm \
tex-umjxo37.tfm \
tex-umjxo38.tfm \
tex-uwmj00.tfm \
tex-uwmj00.vf \
tex-uwmj01.tfm \
tex-uwmj01.vf \
tex-uwmj02.tfm \
tex-uwmj02.vf \
tex-uwmj03.tfm \
tex-uwmj03.vf \
tex-uwmj04.tfm \
tex-uwmj04.vf \
tex-uwmj20.tfm \
tex-uwmj20.vf \
tex-uwmj21.tfm \
tex-uwmj21.vf \
tex-uwmj22.tfm \
tex-uwmj22.vf \
tex-uwmj23.tfm \
tex-uwmj23.vf \
tex-uwmj24.tfm \
tex-uwmj24.vf \
tex-uwmj25.tfm \
tex-uwmj25.vf \
tex-uwmj26.tfm \
tex-uwmj26.vf \
tex-uwmj30.tfm \
tex-uwmj30.vf \
tex-uwmj31.tfm \
tex-uwmj31.vf \
tex-uwmj32.tfm \
tex-uwmj32.vf \
tex-uwmj33.tfm \
tex-uwmj33.vf \
tex-uwmj4e.tfm \
tex-uwmj4e.vf \
tex-uwmj4f.tfm \
tex-uwmj4f.vf \
tex-uwmj50.tfm \
tex-uwmj50.vf \
tex-uwmj51.tfm \
tex-uwmj51.vf \
tex-uwmj52.tfm \
tex-uwmj52.vf \
tex-uwmj53.tfm \
tex-uwmj53.vf \
tex-uwmj54.tfm \
tex-uwmj54.vf \
tex-uwmj55.tfm \
tex-uwmj55.vf \
tex-uwmj56.tfm \
tex-uwmj56.vf \
tex-uwmj57.tfm \
tex-uwmj57.vf \
tex-uwmj58.tfm \
tex-uwmj58.vf \
tex-uwmj59.tfm \
tex-uwmj59.vf \
tex-uwmj5a.tfm \
tex-uwmj5a.vf \
tex-uwmj5b.tfm \
tex-uwmj5b.vf \
tex-uwmj5c.tfm \
tex-uwmj5c.vf \
tex-uwmj5d.tfm \
tex-uwmj5d.vf \
tex-uwmj5e.tfm \
tex-uwmj5e.vf \
tex-uwmj5f.tfm \
tex-uwmj5f.vf \
tex-uwmj60.tfm \
tex-uwmj60.vf \
tex-uwmj61.tfm \
tex-uwmj61.vf \
tex-uwmj62.tfm \
tex-uwmj62.vf \
tex-uwmj63.tfm \
tex-uwmj63.vf \
tex-uwmj64.tfm \
tex-uwmj64.vf \
tex-uwmj65.tfm \
tex-uwmj65.vf \
tex-uwmj66.tfm \
tex-uwmj66.vf \
tex-uwmj67.tfm \
tex-uwmj67.vf \
tex-uwmj68.tfm \
tex-uwmj68.vf \
tex-uwmj69.tfm \
tex-uwmj69.vf \
tex-uwmj6a.tfm \
tex-uwmj6a.vf \
tex-uwmj6b.tfm \
tex-uwmj6b.vf \
tex-uwmj6c.tfm \
tex-uwmj6c.vf \
tex-uwmj6d.tfm \
tex-uwmj6d.vf \
tex-uwmj6e.tfm \
tex-uwmj6e.vf \
tex-uwmj6f.tfm \
tex-uwmj6f.vf \
tex-uwmj70.tfm \
tex-uwmj70.vf \
tex-uwmj71.tfm \
tex-uwmj71.vf \
tex-uwmj72.tfm \
tex-uwmj72.vf \
tex-uwmj73.tfm \
tex-uwmj73.vf \
tex-uwmj74.tfm \
tex-uwmj74.vf \
tex-uwmj75.tfm \
tex-uwmj75.vf \
tex-uwmj76.tfm \
tex-uwmj76.vf \
tex-uwmj77.tfm \
tex-uwmj77.vf \
tex-uwmj78.tfm \
tex-uwmj78.vf \
tex-uwmj79.tfm \
tex-uwmj79.vf \
tex-uwmj7a.tfm \
tex-uwmj7a.vf \
tex-uwmj7b.tfm \
tex-uwmj7b.vf \
tex-uwmj7c.tfm \
tex-uwmj7c.vf \
tex-uwmj7d.tfm \
tex-uwmj7d.vf \
tex-uwmj7e.tfm \
tex-uwmj7e.vf \
tex-uwmj7f.tfm \
tex-uwmj7f.vf \
tex-uwmj80.tfm \
tex-uwmj80.vf \
tex-uwmj81.tfm \
tex-uwmj81.vf \
tex-uwmj82.tfm \
tex-uwmj82.vf \
tex-uwmj83.tfm \
tex-uwmj83.vf \
tex-uwmj84.tfm \
tex-uwmj84.vf \
tex-uwmj85.tfm \
tex-uwmj85.vf \
tex-uwmj86.tfm \
tex-uwmj86.vf \
tex-uwmj87.tfm \
tex-uwmj87.vf \
tex-uwmj88.tfm \
tex-uwmj88.vf \
tex-uwmj89.tfm \
tex-uwmj89.vf \
tex-uwmj8a.tfm \
tex-uwmj8a.vf \
tex-uwmj8b.tfm \
tex-uwmj8b.vf \
tex-uwmj8c.tfm \
tex-uwmj8c.vf \
tex-uwmj8d.tfm \
tex-uwmj8d.vf \
tex-uwmj8e.tfm \
tex-uwmj8e.vf \
tex-uwmj8f.tfm \
tex-uwmj8f.vf \
tex-uwmj90.tfm \
tex-uwmj90.vf \
tex-uwmj91.tfm \
tex-uwmj91.vf \
tex-uwmj92.tfm \
tex-uwmj92.vf \
tex-uwmj93.tfm \
tex-uwmj93.vf \
tex-uwmj94.tfm \
tex-uwmj94.vf \
tex-uwmj95.tfm \
tex-uwmj95.vf \
tex-uwmj96.tfm \
tex-uwmj96.vf \
tex-uwmj97.tfm \
tex-uwmj97.vf \
tex-uwmj98.tfm \
tex-uwmj98.vf \
tex-uwmj99.tfm \
tex-uwmj99.vf \
tex-uwmj9a.tfm \
tex-uwmj9a.vf \
tex-uwmj9b.tfm \
tex-uwmj9b.vf \
tex-uwmj9c.tfm \
tex-uwmj9c.vf \
tex-uwmj9d.tfm \
tex-uwmj9d.vf \
tex-uwmj9e.tfm \
tex-uwmj9e.vf \
tex-uwmj9f.tfm \
tex-uwmj9f.vf \
tex-uwmjac.tfm \
tex-uwmjac.vf \
tex-uwmjad.tfm \
tex-uwmjad.vf \
tex-uwmjae.tfm \
tex-uwmjae.vf \
tex-uwmjaf.tfm \
tex-uwmjaf.vf \
tex-uwmjb0.tfm \
tex-uwmjb0.vf \
tex-uwmjb1.tfm \
tex-uwmjb1.vf \
tex-uwmjb2.tfm \
tex-uwmjb2.vf \
tex-uwmjb3.tfm \
tex-uwmjb3.vf \
tex-uwmjb4.tfm \
tex-uwmjb4.vf \
tex-uwmjb5.tfm \
tex-uwmjb5.vf \
tex-uwmjb6.tfm \
tex-uwmjb6.vf \
tex-uwmjb7.tfm \
tex-uwmjb7.vf \
tex-uwmjb8.tfm \
tex-uwmjb8.vf \
tex-uwmjb9.tfm \
tex-uwmjb9.vf \
tex-uwmjba.tfm \
tex-uwmjba.vf \
tex-uwmjbb.tfm \
tex-uwmjbb.vf \
tex-uwmjbc.tfm \
tex-uwmjbc.vf \
tex-uwmjbd.tfm \
tex-uwmjbd.vf \
tex-uwmjbe.tfm \
tex-uwmjbe.vf \
tex-uwmjbf.tfm \
tex-uwmjbf.vf \
tex-uwmjc0.tfm \
tex-uwmjc0.vf \
tex-uwmjc00.tfm \
tex-uwmjc00.vf \
tex-uwmjc01.tfm \
tex-uwmjc01.vf \
tex-uwmjc02.tfm \
tex-uwmjc02.vf \
tex-uwmjc03.tfm \
tex-uwmjc03.vf \
tex-uwmjc04.tfm \
tex-uwmjc04.vf \
tex-uwmjc1.tfm \
tex-uwmjc1.vf \
tex-uwmjc2.tfm \
tex-uwmjc2.vf \
tex-uwmjc20.tfm \
tex-uwmjc20.vf \
tex-uwmjc21.tfm \
tex-uwmjc21.vf \
tex-uwmjc22.tfm \
tex-uwmjc22.vf \
tex-uwmjc23.tfm \
tex-uwmjc23.vf \
tex-uwmjc24.tfm \
tex-uwmjc24.vf \
tex-uwmjc25.tfm \
tex-uwmjc25.vf \
tex-uwmjc26.tfm \
tex-uwmjc26.vf \
tex-uwmjc3.tfm \
tex-uwmjc3.vf \
tex-uwmjc30.tfm \
tex-uwmjc30.vf \
tex-uwmjc31.tfm \
tex-uwmjc31.vf \
tex-uwmjc32.tfm \
tex-uwmjc32.vf \
tex-uwmjc33.tfm \
tex-uwmjc33.vf \
tex-uwmjc4.tfm \
tex-uwmjc4.vf \
tex-uwmjc4e.tfm \
tex-uwmjc4e.vf \
tex-uwmjc4f.tfm \
tex-uwmjc4f.vf \
tex-uwmjc5.tfm \
tex-uwmjc5.vf \
tex-uwmjc50.tfm \
tex-uwmjc50.vf \
tex-uwmjc51.tfm \
tex-uwmjc51.vf \
tex-uwmjc52.tfm \
tex-uwmjc52.vf \
tex-uwmjc53.tfm \
tex-uwmjc53.vf \
tex-uwmjc54.tfm \
tex-uwmjc54.vf \
tex-uwmjc55.tfm \
tex-uwmjc55.vf \
tex-uwmjc56.tfm \
tex-uwmjc56.vf \
tex-uwmjc57.tfm \
tex-uwmjc57.vf \
tex-uwmjc58.tfm \
tex-uwmjc58.vf \
tex-uwmjc59.tfm \
tex-uwmjc59.vf \
tex-uwmjc5a.tfm \
tex-uwmjc5a.vf \
tex-uwmjc5b.tfm \
tex-uwmjc5b.vf \
tex-uwmjc5c.tfm \
tex-uwmjc5c.vf \
tex-uwmjc5d.tfm \
tex-uwmjc5d.vf \
tex-uwmjc5e.tfm \
tex-uwmjc5e.vf \
tex-uwmjc5f.tfm \
tex-uwmjc5f.vf \
tex-uwmjc6.tfm \
tex-uwmjc6.vf \
tex-uwmjc60.tfm \
tex-uwmjc60.vf \
tex-uwmjc61.tfm \
tex-uwmjc61.vf \
tex-uwmjc62.tfm \
tex-uwmjc62.vf \
tex-uwmjc63.tfm \
tex-uwmjc63.vf \
tex-uwmjc64.tfm \
tex-uwmjc64.vf \
tex-uwmjc65.tfm \
tex-uwmjc65.vf \
tex-uwmjc66.tfm \
tex-uwmjc66.vf \
tex-uwmjc67.tfm \
tex-uwmjc67.vf \
tex-uwmjc68.tfm \
tex-uwmjc68.vf \
tex-uwmjc69.tfm \
tex-uwmjc69.vf \
tex-uwmjc6a.tfm \
tex-uwmjc6a.vf \
tex-uwmjc6b.tfm \
tex-uwmjc6b.vf \
tex-uwmjc6c.tfm \
tex-uwmjc6c.vf \
tex-uwmjc6d.tfm \
tex-uwmjc6d.vf \
tex-uwmjc6e.tfm \
tex-uwmjc6e.vf \
tex-uwmjc6f.tfm \
tex-uwmjc6f.vf \
tex-uwmjc7.tfm \
tex-uwmjc7.vf \
tex-uwmjc70.tfm \
tex-uwmjc70.vf \
tex-uwmjc71.tfm \
tex-uwmjc71.vf \
tex-uwmjc72.tfm \
tex-uwmjc72.vf \
tex-uwmjc73.tfm \
tex-uwmjc73.vf \
tex-uwmjc74.tfm \
tex-uwmjc74.vf \
tex-uwmjc75.tfm \
tex-uwmjc75.vf \
tex-uwmjc76.tfm \
tex-uwmjc76.vf \
tex-uwmjc77.tfm \
tex-uwmjc77.vf \
tex-uwmjc78.tfm \
tex-uwmjc78.vf \
tex-uwmjc79.tfm \
tex-uwmjc79.vf \
tex-uwmjc7a.tfm \
tex-uwmjc7a.vf \
tex-uwmjc7b.tfm \
tex-uwmjc7b.vf \
tex-uwmjc7c.tfm \
tex-uwmjc7c.vf \
tex-uwmjc7d.tfm \
tex-uwmjc7d.vf \
tex-uwmjc7e.tfm \
tex-uwmjc7e.vf \
tex-uwmjc7f.tfm \
tex-uwmjc7f.vf \
tex-uwmjc8.tfm \
tex-uwmjc8.vf \
tex-uwmjc80.tfm \
tex-uwmjc80.vf \
tex-uwmjc81.tfm \
tex-uwmjc81.vf \
tex-uwmjc82.tfm \
tex-uwmjc82.vf \
tex-uwmjc83.tfm \
tex-uwmjc83.vf \
tex-uwmjc84.tfm \
tex-uwmjc84.vf \
tex-uwmjc85.tfm \
tex-uwmjc85.vf \
tex-uwmjc86.tfm \
tex-uwmjc86.vf \
tex-uwmjc87.tfm \
tex-uwmjc87.vf \
tex-uwmjc88.tfm \
tex-uwmjc88.vf \
tex-uwmjc89.tfm \
tex-uwmjc89.vf \
tex-uwmjc8a.tfm \
tex-uwmjc8a.vf \
tex-uwmjc8b.tfm \
tex-uwmjc8b.vf \
tex-uwmjc8c.tfm \
tex-uwmjc8c.vf \
tex-uwmjc8d.tfm \
tex-uwmjc8d.vf \
tex-uwmjc8e.tfm \
tex-uwmjc8e.vf \
tex-uwmjc8f.tfm \
tex-uwmjc8f.vf \
tex-uwmjc9.tfm \
tex-uwmjc9.vf \
tex-uwmjc90.tfm \
tex-uwmjc90.vf \
tex-uwmjc91.tfm \
tex-uwmjc91.vf \
tex-uwmjc92.tfm \
tex-uwmjc92.vf \
tex-uwmjc93.tfm \
tex-uwmjc93.vf \
tex-uwmjc94.tfm \
tex-uwmjc94.vf \
tex-uwmjc95.tfm \
tex-uwmjc95.vf \
tex-uwmjc96.tfm \
tex-uwmjc96.vf \
tex-uwmjc97.tfm \
tex-uwmjc97.vf \
tex-uwmjc98.tfm \
tex-uwmjc98.vf \
tex-uwmjc99.tfm \
tex-uwmjc99.vf \
tex-uwmjc9a.tfm \
tex-uwmjc9a.vf \
tex-uwmjc9b.tfm \
tex-uwmjc9b.vf \
tex-uwmjc9c.tfm \
tex-uwmjc9c.vf \
tex-uwmjc9d.tfm \
tex-uwmjc9d.vf \
tex-uwmjc9e.tfm \
tex-uwmjc9e.vf \
tex-uwmjc9f.tfm \
tex-uwmjc9f.vf \
tex-uwmjca.tfm \
tex-uwmjca.vf \
tex-uwmjcac.tfm \
tex-uwmjcac.vf \
tex-uwmjcad.tfm \
tex-uwmjcad.vf \
tex-uwmjcae.tfm \
tex-uwmjcae.vf \
tex-uwmjcaf.tfm \
tex-uwmjcaf.vf \
tex-uwmjcb.tfm \
tex-uwmjcb.vf \
tex-uwmjcb0.tfm \
tex-uwmjcb0.vf \
tex-uwmjcb1.tfm \
tex-uwmjcb1.vf \
tex-uwmjcb2.tfm \
tex-uwmjcb2.vf \
tex-uwmjcb3.tfm \
tex-uwmjcb3.vf \
tex-uwmjcb4.tfm \
tex-uwmjcb4.vf \
tex-uwmjcb5.tfm \
tex-uwmjcb5.vf \
tex-uwmjcb6.tfm \
tex-uwmjcb6.vf \
tex-uwmjcb7.tfm \
tex-uwmjcb7.vf \
tex-uwmjcb8.tfm \
tex-uwmjcb8.vf \
tex-uwmjcb9.tfm \
tex-uwmjcb9.vf \
tex-uwmjcba.tfm \
tex-uwmjcba.vf \
tex-uwmjcbb.tfm \
tex-uwmjcbb.vf \
tex-uwmjcbc.tfm \
tex-uwmjcbc.vf \
tex-uwmjcbd.tfm \
tex-uwmjcbd.vf \
tex-uwmjcbe.tfm \
tex-uwmjcbe.vf \
tex-uwmjcbf.tfm \
tex-uwmjcbf.vf \
tex-uwmjcc.tfm \
tex-uwmjcc.vf \
tex-uwmjcc0.tfm \
tex-uwmjcc0.vf \
tex-uwmjcc1.tfm \
tex-uwmjcc1.vf \
tex-uwmjcc2.tfm \
tex-uwmjcc2.vf \
tex-uwmjcc3.tfm \
tex-uwmjcc3.vf \
tex-uwmjcc4.tfm \
tex-uwmjcc4.vf \
tex-uwmjcc5.tfm \
tex-uwmjcc5.vf \
tex-uwmjcc6.tfm \
tex-uwmjcc6.vf \
tex-uwmjcc7.tfm \
tex-uwmjcc7.vf \
tex-uwmjcc8.tfm \
tex-uwmjcc8.vf \
tex-uwmjcc9.tfm \
tex-uwmjcc9.vf \
tex-uwmjcca.tfm \
tex-uwmjcca.vf \
tex-uwmjccb.tfm \
tex-uwmjccb.vf \
tex-uwmjccc.tfm \
tex-uwmjccc.vf \
tex-uwmjccd.tfm \
tex-uwmjccd.vf \
tex-uwmjcce.tfm \
tex-uwmjcce.vf \
tex-uwmjccf.tfm \
tex-uwmjccf.vf \
tex-uwmjcd.tfm \
tex-uwmjcd.vf \
tex-uwmjcd0.tfm \
tex-uwmjcd0.vf \
tex-uwmjcd1.tfm \
tex-uwmjcd1.vf \
tex-uwmjcd2.tfm \
tex-uwmjcd2.vf \
tex-uwmjcd3.tfm \
tex-uwmjcd3.vf \
tex-uwmjcd4.tfm \
tex-uwmjcd4.vf \
tex-uwmjcd5.tfm \
tex-uwmjcd5.vf \
tex-uwmjcd6.tfm \
tex-uwmjcd6.vf \
tex-uwmjcd7.tfm \
tex-uwmjcd7.vf \
tex-uwmjce.tfm \
tex-uwmjce.vf \
tex-uwmjcf.tfm \
tex-uwmjcf.vf \
tex-uwmjcf9.tfm \
tex-uwmjcf9.vf \
tex-uwmjcfa.tfm \
tex-uwmjcfa.vf \
tex-uwmjcff.tfm \
tex-uwmjcff.vf \
tex-uwmjco00.tfm \
tex-uwmjco00.vf \
tex-uwmjco01.tfm \
tex-uwmjco01.vf \
tex-uwmjco02.tfm \
tex-uwmjco02.vf \
tex-uwmjco03.tfm \
tex-uwmjco03.vf \
tex-uwmjco04.tfm \
tex-uwmjco04.vf \
tex-uwmjco20.tfm \
tex-uwmjco20.vf \
tex-uwmjco21.tfm \
tex-uwmjco21.vf \
tex-uwmjco22.tfm \
tex-uwmjco22.vf \
tex-uwmjco23.tfm \
tex-uwmjco23.vf \
tex-uwmjco24.tfm \
tex-uwmjco24.vf \
tex-uwmjco25.tfm \
tex-uwmjco25.vf \
tex-uwmjco26.tfm \
tex-uwmjco26.vf \
tex-uwmjco30.tfm \
tex-uwmjco30.vf \
tex-uwmjco31.tfm \
tex-uwmjco31.vf \
tex-uwmjco32.tfm \
tex-uwmjco32.vf \
tex-uwmjco33.tfm \
tex-uwmjco33.vf \
tex-uwmjco4e.tfm \
tex-uwmjco4e.vf \
tex-uwmjco4f.tfm \
tex-uwmjco4f.vf \
tex-uwmjco50.tfm \
tex-uwmjco50.vf \
tex-uwmjco51.tfm \
tex-uwmjco51.vf \
tex-uwmjco52.tfm \
tex-uwmjco52.vf \
tex-uwmjco53.tfm \
tex-uwmjco53.vf \
tex-uwmjco54.tfm \
tex-uwmjco54.vf \
tex-uwmjco55.tfm \
tex-uwmjco55.vf \
tex-uwmjco56.tfm \
tex-uwmjco56.vf \
tex-uwmjco57.tfm \
tex-uwmjco57.vf \
tex-uwmjco58.tfm \
tex-uwmjco58.vf \
tex-uwmjco59.tfm \
tex-uwmjco59.vf \
tex-uwmjco5a.tfm \
tex-uwmjco5a.vf \
tex-uwmjco5b.tfm \
tex-uwmjco5b.vf \
tex-uwmjco5c.tfm \
tex-uwmjco5c.vf \
tex-uwmjco5d.tfm \
tex-uwmjco5d.vf \
tex-uwmjco5e.tfm \
tex-uwmjco5e.vf \
tex-uwmjco5f.tfm \
tex-uwmjco5f.vf \
tex-uwmjco60.tfm \
tex-uwmjco60.vf \
tex-uwmjco61.tfm \
tex-uwmjco61.vf \
tex-uwmjco62.tfm \
tex-uwmjco62.vf \
tex-uwmjco63.tfm \
tex-uwmjco63.vf \
tex-uwmjco64.tfm \
tex-uwmjco64.vf \
tex-uwmjco65.tfm \
tex-uwmjco65.vf \
tex-uwmjco66.tfm \
tex-uwmjco66.vf \
tex-uwmjco67.tfm \
tex-uwmjco67.vf \
tex-uwmjco68.tfm \
tex-uwmjco68.vf \
tex-uwmjco69.tfm \
tex-uwmjco69.vf \
tex-uwmjco6a.tfm \
tex-uwmjco6a.vf \
tex-uwmjco6b.tfm \
tex-uwmjco6b.vf \
tex-uwmjco6c.tfm \
tex-uwmjco6c.vf \
tex-uwmjco6d.tfm \
tex-uwmjco6d.vf \
tex-uwmjco6e.tfm \
tex-uwmjco6e.vf \
tex-uwmjco6f.tfm \
tex-uwmjco6f.vf \
tex-uwmjco70.tfm \
tex-uwmjco70.vf \
tex-uwmjco71.tfm \
tex-uwmjco71.vf \
tex-uwmjco72.tfm \
tex-uwmjco72.vf \
tex-uwmjco73.tfm \
tex-uwmjco73.vf \
tex-uwmjco74.tfm \
tex-uwmjco74.vf \
tex-uwmjco75.tfm \
tex-uwmjco75.vf \
tex-uwmjco76.tfm \
tex-uwmjco76.vf \
tex-uwmjco77.tfm \
tex-uwmjco77.vf \
tex-uwmjco78.tfm \
tex-uwmjco78.vf \
tex-uwmjco79.tfm \
tex-uwmjco79.vf \
tex-uwmjco7a.tfm \
tex-uwmjco7a.vf \
tex-uwmjco7b.tfm \
tex-uwmjco7b.vf \
tex-uwmjco7c.tfm \
tex-uwmjco7c.vf \
tex-uwmjco7d.tfm \
tex-uwmjco7d.vf \
tex-uwmjco7e.tfm \
tex-uwmjco7e.vf \
tex-uwmjco7f.tfm \
tex-uwmjco7f.vf \
tex-uwmjco80.tfm \
tex-uwmjco80.vf \
tex-uwmjco81.tfm \
tex-uwmjco81.vf \
tex-uwmjco82.tfm \
tex-uwmjco82.vf \
tex-uwmjco83.tfm \
tex-uwmjco83.vf \
tex-uwmjco84.tfm \
tex-uwmjco84.vf \
tex-uwmjco85.tfm \
tex-uwmjco85.vf \
tex-uwmjco86.tfm \
tex-uwmjco86.vf \
tex-uwmjco87.tfm \
tex-uwmjco87.vf \
tex-uwmjco88.tfm \
tex-uwmjco88.vf \
tex-uwmjco89.tfm \
tex-uwmjco89.vf \
tex-uwmjco8a.tfm \
tex-uwmjco8a.vf \
tex-uwmjco8b.tfm \
tex-uwmjco8b.vf \
tex-uwmjco8c.tfm \
tex-uwmjco8c.vf \
tex-uwmjco8d.tfm \
tex-uwmjco8d.vf \
tex-uwmjco8e.tfm \
tex-uwmjco8e.vf \
tex-uwmjco8f.tfm \
tex-uwmjco8f.vf \
tex-uwmjco90.tfm \
tex-uwmjco90.vf \
tex-uwmjco91.tfm \
tex-uwmjco91.vf \
tex-uwmjco92.tfm \
tex-uwmjco92.vf \
tex-uwmjco93.tfm \
tex-uwmjco93.vf \
tex-uwmjco94.tfm \
tex-uwmjco94.vf \
tex-uwmjco95.tfm \
tex-uwmjco95.vf \
tex-uwmjco96.tfm \
tex-uwmjco96.vf \
tex-uwmjco97.tfm \
tex-uwmjco97.vf \
tex-uwmjco98.tfm \
tex-uwmjco98.vf \
tex-uwmjco99.tfm \
tex-uwmjco99.vf \
tex-uwmjco9a.tfm \
tex-uwmjco9a.vf \
tex-uwmjco9b.tfm \
tex-uwmjco9b.vf \
tex-uwmjco9c.tfm \
tex-uwmjco9c.vf \
tex-uwmjco9d.tfm \
tex-uwmjco9d.vf \
tex-uwmjco9e.tfm \
tex-uwmjco9e.vf \
tex-uwmjco9f.tfm \
tex-uwmjco9f.vf \
tex-uwmjcoac.tfm \
tex-uwmjcoac.vf \
tex-uwmjcoad.tfm \
tex-uwmjcoad.vf \
tex-uwmjcoae.tfm \
tex-uwmjcoae.vf \
tex-uwmjcoaf.tfm \
tex-uwmjcoaf.vf \
tex-uwmjcob0.tfm \
tex-uwmjcob0.vf \
tex-uwmjcob1.tfm \
tex-uwmjcob1.vf \
tex-uwmjcob2.tfm \
tex-uwmjcob2.vf \
tex-uwmjcob3.tfm \
tex-uwmjcob3.vf \
tex-uwmjcob4.tfm \
tex-uwmjcob4.vf \
tex-uwmjcob5.tfm \
tex-uwmjcob5.vf \
tex-uwmjcob6.tfm \
tex-uwmjcob6.vf \
tex-uwmjcob7.tfm \
tex-uwmjcob7.vf \
tex-uwmjcob8.tfm \
tex-uwmjcob8.vf \
tex-uwmjcob9.tfm \
tex-uwmjcob9.vf \
tex-uwmjcoba.tfm \
tex-uwmjcoba.vf \
tex-uwmjcobb.tfm \
tex-uwmjcobb.vf \
tex-uwmjcobc.tfm \
tex-uwmjcobc.vf \
tex-uwmjcobd.tfm \
tex-uwmjcobd.vf \
tex-uwmjcobe.tfm \
tex-uwmjcobe.vf \
tex-uwmjcobf.tfm \
tex-uwmjcobf.vf \
tex-uwmjcoc0.tfm \
tex-uwmjcoc0.vf \
tex-uwmjcoc1.tfm \
tex-uwmjcoc1.vf \
tex-uwmjcoc2.tfm \
tex-uwmjcoc2.vf \
tex-uwmjcoc3.tfm \
tex-uwmjcoc3.vf \
tex-uwmjcoc4.tfm \
tex-uwmjcoc4.vf \
tex-uwmjcoc5.tfm \
tex-uwmjcoc5.vf \
tex-uwmjcoc6.tfm \
tex-uwmjcoc6.vf \
tex-uwmjcoc7.tfm \
tex-uwmjcoc7.vf \
tex-uwmjcoc8.tfm \
tex-uwmjcoc8.vf \
tex-uwmjcoc9.tfm \
tex-uwmjcoc9.vf \
tex-uwmjcoca.tfm \
tex-uwmjcoca.vf \
tex-uwmjcocb.tfm \
tex-uwmjcocb.vf \
tex-uwmjcocc.tfm \
tex-uwmjcocc.vf \
tex-uwmjcocd.tfm \
tex-uwmjcocd.vf \
tex-uwmjcoce.tfm \
tex-uwmjcoce.vf \
tex-uwmjcocf.tfm \
tex-uwmjcocf.vf \
tex-uwmjcod0.tfm \
tex-uwmjcod0.vf \
tex-uwmjcod1.tfm \
tex-uwmjcod1.vf \
tex-uwmjcod2.tfm \
tex-uwmjcod2.vf \
tex-uwmjcod3.tfm \
tex-uwmjcod3.vf \
tex-uwmjcod4.tfm \
tex-uwmjcod4.vf \
tex-uwmjcod5.tfm \
tex-uwmjcod5.vf \
tex-uwmjcod6.tfm \
tex-uwmjcod6.vf \
tex-uwmjcod7.tfm \
tex-uwmjcod7.vf \
tex-uwmjcof9.tfm \
tex-uwmjcof9.vf \
tex-uwmjcofa.tfm \
tex-uwmjcofa.vf \
tex-uwmjcoff.tfm \
tex-uwmjcoff.vf \
tex-uwmjd0.tfm \
tex-uwmjd0.vf \
tex-uwmjd1.tfm \
tex-uwmjd1.vf \
tex-uwmjd2.tfm \
tex-uwmjd2.vf \
tex-uwmjd3.tfm \
tex-uwmjd3.vf \
tex-uwmjd4.tfm \
tex-uwmjd4.vf \
tex-uwmjd5.tfm \
tex-uwmjd5.vf \
tex-uwmjd6.tfm \
tex-uwmjd6.vf \
tex-uwmjd7.tfm \
tex-uwmjd7.vf \
tex-uwmjf9.tfm \
tex-uwmjf9.vf \
tex-uwmjfa.tfm \
tex-uwmjfa.vf \
tex-uwmjff.tfm \
tex-uwmjff.vf \
tex-uwmjo00.tfm \
tex-uwmjo00.vf \
tex-uwmjo01.tfm \
tex-uwmjo01.vf \
tex-uwmjo02.tfm \
tex-uwmjo02.vf \
tex-uwmjo03.tfm \
tex-uwmjo03.vf \
tex-uwmjo04.tfm \
tex-uwmjo04.vf \
tex-uwmjo20.tfm \
tex-uwmjo20.vf \
tex-uwmjo21.tfm \
tex-uwmjo21.vf \
tex-uwmjo22.tfm \
tex-uwmjo22.vf \
tex-uwmjo23.tfm \
tex-uwmjo23.vf \
tex-uwmjo24.tfm \
tex-uwmjo24.vf \
tex-uwmjo25.tfm \
tex-uwmjo25.vf \
tex-uwmjo26.tfm \
tex-uwmjo26.vf \
tex-uwmjo30.tfm \
tex-uwmjo30.vf \
tex-uwmjo31.tfm \
tex-uwmjo31.vf \
tex-uwmjo32.tfm \
tex-uwmjo32.vf \
tex-uwmjo33.tfm \
tex-uwmjo33.vf \
tex-uwmjo4e.tfm \
tex-uwmjo4e.vf \
tex-uwmjo4f.tfm \
tex-uwmjo4f.vf \
tex-uwmjo50.tfm \
tex-uwmjo50.vf \
tex-uwmjo51.tfm \
tex-uwmjo51.vf \
tex-uwmjo52.tfm \
tex-uwmjo52.vf \
tex-uwmjo53.tfm \
tex-uwmjo53.vf \
tex-uwmjo54.tfm \
tex-uwmjo54.vf \
tex-uwmjo55.tfm \
tex-uwmjo55.vf \
tex-uwmjo56.tfm \
tex-uwmjo56.vf \
tex-uwmjo57.tfm \
tex-uwmjo57.vf \
tex-uwmjo58.tfm \
tex-uwmjo58.vf \
tex-uwmjo59.tfm \
tex-uwmjo59.vf \
tex-uwmjo5a.tfm \
tex-uwmjo5a.vf \
tex-uwmjo5b.tfm \
tex-uwmjo5b.vf \
tex-uwmjo5c.tfm \
tex-uwmjo5c.vf \
tex-uwmjo5d.tfm \
tex-uwmjo5d.vf \
tex-uwmjo5e.tfm \
tex-uwmjo5e.vf \
tex-uwmjo5f.tfm \
tex-uwmjo5f.vf \
tex-uwmjo60.tfm \
tex-uwmjo60.vf \
tex-uwmjo61.tfm \
tex-uwmjo61.vf \
tex-uwmjo62.tfm \
tex-uwmjo62.vf \
tex-uwmjo63.tfm \
tex-uwmjo63.vf \
tex-uwmjo64.tfm \
tex-uwmjo64.vf \
tex-uwmjo65.tfm \
tex-uwmjo65.vf \
tex-uwmjo66.tfm \
tex-uwmjo66.vf \
tex-uwmjo67.tfm \
tex-uwmjo67.vf \
tex-uwmjo68.tfm \
tex-uwmjo68.vf \
tex-uwmjo69.tfm \
tex-uwmjo69.vf \
tex-uwmjo6a.tfm \
tex-uwmjo6a.vf \
tex-uwmjo6b.tfm \
tex-uwmjo6b.vf \
tex-uwmjo6c.tfm \
tex-uwmjo6c.vf \
tex-uwmjo6d.tfm \
tex-uwmjo6d.vf \
tex-uwmjo6e.tfm \
tex-uwmjo6e.vf \
tex-uwmjo6f.tfm \
tex-uwmjo6f.vf \
tex-uwmjo70.tfm \
tex-uwmjo70.vf \
tex-uwmjo71.tfm \
tex-uwmjo71.vf \
tex-uwmjo72.tfm \
tex-uwmjo72.vf \
tex-uwmjo73.tfm \
tex-uwmjo73.vf \
tex-uwmjo74.tfm \
tex-uwmjo74.vf \
tex-uwmjo75.tfm \
tex-uwmjo75.vf \
tex-uwmjo76.tfm \
tex-uwmjo76.vf \
tex-uwmjo77.tfm \
tex-uwmjo77.vf \
tex-uwmjo78.tfm \
tex-uwmjo78.vf \
tex-uwmjo79.tfm \
tex-uwmjo79.vf \
tex-uwmjo7a.tfm \
tex-uwmjo7a.vf \
tex-uwmjo7b.tfm \
tex-uwmjo7b.vf \
tex-uwmjo7c.tfm \
tex-uwmjo7c.vf \
tex-uwmjo7d.tfm \
tex-uwmjo7d.vf \
tex-uwmjo7e.tfm \
tex-uwmjo7e.vf \
tex-uwmjo7f.tfm \
tex-uwmjo7f.vf \
tex-uwmjo80.tfm \
tex-uwmjo80.vf \
tex-uwmjo81.tfm \
tex-uwmjo81.vf \
tex-uwmjo82.tfm \
tex-uwmjo82.vf \
tex-uwmjo83.tfm \
tex-uwmjo83.vf \
tex-uwmjo84.tfm \
tex-uwmjo84.vf \
tex-uwmjo85.tfm \
tex-uwmjo85.vf \
tex-uwmjo86.tfm \
tex-uwmjo86.vf \
tex-uwmjo87.tfm \
tex-uwmjo87.vf \
tex-uwmjo88.tfm \
tex-uwmjo88.vf \
tex-uwmjo89.tfm \
tex-uwmjo89.vf \
tex-uwmjo8a.tfm \
tex-uwmjo8a.vf \
tex-uwmjo8b.tfm \
tex-uwmjo8b.vf \
tex-uwmjo8c.tfm \
tex-uwmjo8c.vf \
tex-uwmjo8d.tfm \
tex-uwmjo8d.vf \
tex-uwmjo8e.tfm \
tex-uwmjo8e.vf \
tex-uwmjo8f.tfm \
tex-uwmjo8f.vf \
tex-uwmjo90.tfm \
tex-uwmjo90.vf \
tex-uwmjo91.tfm \
tex-uwmjo91.vf \
tex-uwmjo92.tfm \
tex-uwmjo92.vf \
tex-uwmjo93.tfm \
tex-uwmjo93.vf \
tex-uwmjo94.tfm \
tex-uwmjo94.vf \
tex-uwmjo95.tfm \
tex-uwmjo95.vf \
tex-uwmjo96.tfm \
tex-uwmjo96.vf \
tex-uwmjo97.tfm \
tex-uwmjo97.vf \
tex-uwmjo98.tfm \
tex-uwmjo98.vf \
tex-uwmjo99.tfm \
tex-uwmjo99.vf \
tex-uwmjo9a.tfm \
tex-uwmjo9a.vf \
tex-uwmjo9b.tfm \
tex-uwmjo9b.vf \
tex-uwmjo9c.tfm \
tex-uwmjo9c.vf \
tex-uwmjo9d.tfm \
tex-uwmjo9d.vf \
tex-uwmjo9e.tfm \
tex-uwmjo9e.vf \
tex-uwmjo9f.tfm \
tex-uwmjo9f.vf \
tex-uwmjoac.tfm \
tex-uwmjoac.vf \
tex-uwmjoad.tfm \
tex-uwmjoad.vf \
tex-uwmjoae.tfm \
tex-uwmjoae.vf \
tex-uwmjoaf.tfm \
tex-uwmjoaf.vf \
tex-uwmjob0.tfm \
tex-uwmjob0.vf \
tex-uwmjob1.tfm \
tex-uwmjob1.vf \
tex-uwmjob2.tfm \
tex-uwmjob2.vf \
tex-uwmjob3.tfm \
tex-uwmjob3.vf \
tex-uwmjob4.tfm \
tex-uwmjob4.vf \
tex-uwmjob5.tfm \
tex-uwmjob5.vf \
tex-uwmjob6.tfm \
tex-uwmjob6.vf \
tex-uwmjob7.tfm \
tex-uwmjob7.vf \
tex-uwmjob8.tfm \
tex-uwmjob8.vf \
tex-uwmjob9.tfm \
tex-uwmjob9.vf \
tex-uwmjoba.tfm \
tex-uwmjoba.vf \
tex-uwmjobb.tfm \
tex-uwmjobb.vf \
tex-uwmjobc.tfm \
tex-uwmjobc.vf \
tex-uwmjobd.tfm \
tex-uwmjobd.vf \
tex-uwmjobe.tfm \
tex-uwmjobe.vf \
tex-uwmjobf.tfm \
tex-uwmjobf.vf \
tex-uwmjoc0.tfm \
tex-uwmjoc0.vf \
tex-uwmjoc1.tfm \
tex-uwmjoc1.vf \
tex-uwmjoc2.tfm \
tex-uwmjoc2.vf \
tex-uwmjoc3.tfm \
tex-uwmjoc3.vf \
tex-uwmjoc4.tfm \
tex-uwmjoc4.vf \
tex-uwmjoc5.tfm \
tex-uwmjoc5.vf \
tex-uwmjoc6.tfm \
tex-uwmjoc6.vf \
tex-uwmjoc7.tfm \
tex-uwmjoc7.vf \
tex-uwmjoc8.tfm \
tex-uwmjoc8.vf \
tex-uwmjoc9.tfm \
tex-uwmjoc9.vf \
tex-uwmjoca.tfm \
tex-uwmjoca.vf \
tex-uwmjocb.tfm \
tex-uwmjocb.vf \
tex-uwmjocc.tfm \
tex-uwmjocc.vf \
tex-uwmjocd.tfm \
tex-uwmjocd.vf \
tex-uwmjoce.tfm \
tex-uwmjoce.vf \
tex-uwmjocf.tfm \
tex-uwmjocf.vf \
tex-uwmjod0.tfm \
tex-uwmjod0.vf \
tex-uwmjod1.tfm \
tex-uwmjod1.vf \
tex-uwmjod2.tfm \
tex-uwmjod2.vf \
tex-uwmjod3.tfm \
tex-uwmjod3.vf \
tex-uwmjod4.tfm \
tex-uwmjod4.vf \
tex-uwmjod5.tfm \
tex-uwmjod5.vf \
tex-uwmjod6.tfm \
tex-uwmjod6.vf \
tex-uwmjod7.tfm \
tex-uwmjod7.vf \
tex-uwmjof9.tfm \
tex-uwmjof9.vf \
tex-uwmjofa.tfm \
tex-uwmjofa.vf \
tex-uwmjoff.tfm \
tex-uwmjoff.vf \
tex-uwmju00.tfm \
tex-uwmju00.vf \
tex-uwmju01.tfm \
tex-uwmju01.vf \
tex-uwmju02.tfm \
tex-uwmju02.vf \
tex-uwmju03.tfm \
tex-uwmju03.vf \
tex-uwmju04.tfm \
tex-uwmju04.vf \
tex-uwmju20.tfm \
tex-uwmju20.vf \
tex-uwmju21.tfm \
tex-uwmju21.vf \
tex-uwmju22.tfm \
tex-uwmju22.vf \
tex-uwmju23.tfm \
tex-uwmju23.vf \
tex-uwmju24.tfm \
tex-uwmju24.vf \
tex-uwmju25.tfm \
tex-uwmju25.vf \
tex-uwmju26.tfm \
tex-uwmju26.vf \
tex-uwmju30.tfm \
tex-uwmju30.vf \
tex-uwmju31.tfm \
tex-uwmju31.vf \
tex-uwmju32.tfm \
tex-uwmju32.vf \
tex-uwmju33.tfm \
tex-uwmju33.vf \
tex-uwmju4e.tfm \
tex-uwmju4e.vf \
tex-uwmju4f.tfm \
tex-uwmju4f.vf \
tex-uwmju50.tfm \
tex-uwmju50.vf \
tex-uwmju51.tfm \
tex-uwmju51.vf \
tex-uwmju52.tfm \
tex-uwmju52.vf \
tex-uwmju53.tfm \
tex-uwmju53.vf \
tex-uwmju54.tfm \
tex-uwmju54.vf \
tex-uwmju55.tfm \
tex-uwmju55.vf \
tex-uwmju56.tfm \
tex-uwmju56.vf \
tex-uwmju57.tfm \
tex-uwmju57.vf \
tex-uwmju58.tfm \
tex-uwmju58.vf \
tex-uwmju59.tfm \
tex-uwmju59.vf \
tex-uwmju5a.tfm \
tex-uwmju5a.vf \
tex-uwmju5b.tfm \
tex-uwmju5b.vf \
tex-uwmju5c.tfm \
tex-uwmju5c.vf \
tex-uwmju5d.tfm \
tex-uwmju5d.vf \
tex-uwmju5e.tfm \
tex-uwmju5e.vf \
tex-uwmju5f.tfm \
tex-uwmju5f.vf \
tex-uwmju60.tfm \
tex-uwmju60.vf \
tex-uwmju61.tfm \
tex-uwmju61.vf \
tex-uwmju62.tfm \
tex-uwmju62.vf \
tex-uwmju63.tfm \
tex-uwmju63.vf \
tex-uwmju64.tfm \
tex-uwmju64.vf \
tex-uwmju65.tfm \
tex-uwmju65.vf \
tex-uwmju66.tfm \
tex-uwmju66.vf \
tex-uwmju67.tfm \
tex-uwmju67.vf \
tex-uwmju68.tfm \
tex-uwmju68.vf \
tex-uwmju69.tfm \
tex-uwmju69.vf \
tex-uwmju6a.tfm \
tex-uwmju6a.vf \
tex-uwmju6b.tfm \
tex-uwmju6b.vf \
tex-uwmju6c.tfm \
tex-uwmju6c.vf \
tex-uwmju6d.tfm \
tex-uwmju6d.vf \
tex-uwmju6e.tfm \
tex-uwmju6e.vf \
tex-uwmju6f.tfm \
tex-uwmju6f.vf \
tex-uwmju70.tfm \
tex-uwmju70.vf \
tex-uwmju71.tfm \
tex-uwmju71.vf \
tex-uwmju72.tfm \
tex-uwmju72.vf \
tex-uwmju73.tfm \
tex-uwmju73.vf \
tex-uwmju74.tfm \
tex-uwmju74.vf \
tex-uwmju75.tfm \
tex-uwmju75.vf \
tex-uwmju76.tfm \
tex-uwmju76.vf \
tex-uwmju77.tfm \
tex-uwmju77.vf \
tex-uwmju78.tfm \
tex-uwmju78.vf \
tex-uwmju79.tfm \
tex-uwmju79.vf \
tex-uwmju7a.tfm \
tex-uwmju7a.vf \
tex-uwmju7b.tfm \
tex-uwmju7b.vf \
tex-uwmju7c.tfm \
tex-uwmju7c.vf \
tex-uwmju7d.tfm \
tex-uwmju7d.vf \
tex-uwmju7e.tfm \
tex-uwmju7e.vf \
tex-uwmju7f.tfm \
tex-uwmju7f.vf \
tex-uwmju80.tfm \
tex-uwmju80.vf \
tex-uwmju81.tfm \
tex-uwmju81.vf \
tex-uwmju82.tfm \
tex-uwmju82.vf \
tex-uwmju83.tfm \
tex-uwmju83.vf \
tex-uwmju84.tfm \
tex-uwmju84.vf \
tex-uwmju85.tfm \
tex-uwmju85.vf \
tex-uwmju86.tfm \
tex-uwmju86.vf \
tex-uwmju87.tfm \
tex-uwmju87.vf \
tex-uwmju88.tfm \
tex-uwmju88.vf \
tex-uwmju89.tfm \
tex-uwmju89.vf \
tex-uwmju8a.tfm \
tex-uwmju8a.vf \
tex-uwmju8b.tfm \
tex-uwmju8b.vf \
tex-uwmju8c.tfm \
tex-uwmju8c.vf \
tex-uwmju8d.tfm \
tex-uwmju8d.vf \
tex-uwmju8e.tfm \
tex-uwmju8e.vf \
tex-uwmju8f.tfm \
tex-uwmju8f.vf \
tex-uwmju90.tfm \
tex-uwmju90.vf \
tex-uwmju91.tfm \
tex-uwmju91.vf \
tex-uwmju92.tfm \
tex-uwmju92.vf \
tex-uwmju93.tfm \
tex-uwmju93.vf \
tex-uwmju94.tfm \
tex-uwmju94.vf \
tex-uwmju95.tfm \
tex-uwmju95.vf \
tex-uwmju96.tfm \
tex-uwmju96.vf \
tex-uwmju97.tfm \
tex-uwmju97.vf \
tex-uwmju98.tfm \
tex-uwmju98.vf \
tex-uwmju99.tfm \
tex-uwmju99.vf \
tex-uwmju9a.tfm \
tex-uwmju9a.vf \
tex-uwmju9b.tfm \
tex-uwmju9b.vf \
tex-uwmju9c.tfm \
tex-uwmju9c.vf \
tex-uwmju9d.tfm \
tex-uwmju9d.vf \
tex-uwmju9e.tfm \
tex-uwmju9e.vf \
tex-uwmju9f.tfm \
tex-uwmju9f.vf \
tex-uwmjuac.tfm \
tex-uwmjuac.vf \
tex-uwmjuad.tfm \
tex-uwmjuad.vf \
tex-uwmjuae.tfm \
tex-uwmjuae.vf \
tex-uwmjuaf.tfm \
tex-uwmjuaf.vf \
tex-uwmjub0.tfm \
tex-uwmjub0.vf \
tex-uwmjub1.tfm \
tex-uwmjub1.vf \
tex-uwmjub2.tfm \
tex-uwmjub2.vf \
tex-uwmjub3.tfm \
tex-uwmjub3.vf \
tex-uwmjub4.tfm \
tex-uwmjub4.vf \
tex-uwmjub5.tfm \
tex-uwmjub5.vf \
tex-uwmjub6.tfm \
tex-uwmjub6.vf \
tex-uwmjub7.tfm \
tex-uwmjub7.vf \
tex-uwmjub8.tfm \
tex-uwmjub8.vf \
tex-uwmjub9.tfm \
tex-uwmjub9.vf \
tex-uwmjuba.tfm \
tex-uwmjuba.vf \
tex-uwmjubb.tfm \
tex-uwmjubb.vf \
tex-uwmjubc.tfm \
tex-uwmjubc.vf \
tex-uwmjubd.tfm \
tex-uwmjubd.vf \
tex-uwmjube.tfm \
tex-uwmjube.vf \
tex-uwmjubf.tfm \
tex-uwmjubf.vf \
tex-uwmjuc0.tfm \
tex-uwmjuc0.vf \
tex-uwmjuc1.tfm \
tex-uwmjuc1.vf \
tex-uwmjuc2.tfm \
tex-uwmjuc2.vf \
tex-uwmjuc3.tfm \
tex-uwmjuc3.vf \
tex-uwmjuc4.tfm \
tex-uwmjuc4.vf \
tex-uwmjuc5.tfm \
tex-uwmjuc5.vf \
tex-uwmjuc6.tfm \
tex-uwmjuc6.vf \
tex-uwmjuc7.tfm \
tex-uwmjuc7.vf \
tex-uwmjuc8.tfm \
tex-uwmjuc8.vf \
tex-uwmjuc9.tfm \
tex-uwmjuc9.vf \
tex-uwmjuca.tfm \
tex-uwmjuca.vf \
tex-uwmjucb.tfm \
tex-uwmjucb.vf \
tex-uwmjucc.tfm \
tex-uwmjucc.vf \
tex-uwmjucd.tfm \
tex-uwmjucd.vf \
tex-uwmjuce.tfm \
tex-uwmjuce.vf \
tex-uwmjucf.tfm \
tex-uwmjucf.vf \
tex-uwmjud0.tfm \
tex-uwmjud0.vf \
tex-uwmjud1.tfm \
tex-uwmjud1.vf \
tex-uwmjud2.tfm \
tex-uwmjud2.vf \
tex-uwmjud3.tfm \
tex-uwmjud3.vf \
tex-uwmjud4.tfm \
tex-uwmjud4.vf \
tex-uwmjud5.tfm \
tex-uwmjud5.vf \
tex-uwmjud6.tfm \
tex-uwmjud6.vf \
tex-uwmjud7.tfm \
tex-uwmjud7.vf \
tex-uwmjuf9.tfm \
tex-uwmjuf9.vf \
tex-uwmjufa.tfm \
tex-uwmjufa.vf \
tex-uwmjuff.tfm \
tex-uwmjuff.vf \
tex-uwmjuo00.tfm \
tex-uwmjuo00.vf \
tex-uwmjuo01.tfm \
tex-uwmjuo01.vf \
tex-uwmjuo02.tfm \
tex-uwmjuo02.vf \
tex-uwmjuo03.tfm \
tex-uwmjuo03.vf \
tex-uwmjuo04.tfm \
tex-uwmjuo04.vf \
tex-uwmjuo20.tfm \
tex-uwmjuo20.vf \
tex-uwmjuo21.tfm \
tex-uwmjuo21.vf \
tex-uwmjuo22.tfm \
tex-uwmjuo22.vf \
tex-uwmjuo23.tfm \
tex-uwmjuo23.vf \
tex-uwmjuo24.tfm \
tex-uwmjuo24.vf \
tex-uwmjuo25.tfm \
tex-uwmjuo25.vf \
tex-uwmjuo26.tfm \
tex-uwmjuo26.vf \
tex-uwmjuo30.tfm \
tex-uwmjuo30.vf \
tex-uwmjuo31.tfm \
tex-uwmjuo31.vf \
tex-uwmjuo32.tfm \
tex-uwmjuo32.vf \
tex-uwmjuo33.tfm \
tex-uwmjuo33.vf \
tex-uwmjuo4e.tfm \
tex-uwmjuo4e.vf \
tex-uwmjuo4f.tfm \
tex-uwmjuo4f.vf \
tex-uwmjuo50.tfm \
tex-uwmjuo50.vf \
tex-uwmjuo51.tfm \
tex-uwmjuo51.vf \
tex-uwmjuo52.tfm \
tex-uwmjuo52.vf \
tex-uwmjuo53.tfm \
tex-uwmjuo53.vf \
tex-uwmjuo54.tfm \
tex-uwmjuo54.vf \
tex-uwmjuo55.tfm \
tex-uwmjuo55.vf \
tex-uwmjuo56.tfm \
tex-uwmjuo56.vf \
tex-uwmjuo57.tfm \
tex-uwmjuo57.vf \
tex-uwmjuo58.tfm \
tex-uwmjuo58.vf \
tex-uwmjuo59.tfm \
tex-uwmjuo59.vf \
tex-uwmjuo5a.tfm \
tex-uwmjuo5a.vf \
tex-uwmjuo5b.tfm \
tex-uwmjuo5b.vf \
tex-uwmjuo5c.tfm \
tex-uwmjuo5c.vf \
tex-uwmjuo5d.tfm \
tex-uwmjuo5d.vf \
tex-uwmjuo5e.tfm \
tex-uwmjuo5e.vf \
tex-uwmjuo5f.tfm \
tex-uwmjuo5f.vf \
tex-uwmjuo60.tfm \
tex-uwmjuo60.vf \
tex-uwmjuo61.tfm \
tex-uwmjuo61.vf \
tex-uwmjuo62.tfm \
tex-uwmjuo62.vf \
tex-uwmjuo63.tfm \
tex-uwmjuo63.vf \
tex-uwmjuo64.tfm \
tex-uwmjuo64.vf \
tex-uwmjuo65.tfm \
tex-uwmjuo65.vf \
tex-uwmjuo66.tfm \
tex-uwmjuo66.vf \
tex-uwmjuo67.tfm \
tex-uwmjuo67.vf \
tex-uwmjuo68.tfm \
tex-uwmjuo68.vf \
tex-uwmjuo69.tfm \
tex-uwmjuo69.vf \
tex-uwmjuo6a.tfm \
tex-uwmjuo6a.vf \
tex-uwmjuo6b.tfm \
tex-uwmjuo6b.vf \
tex-uwmjuo6c.tfm \
tex-uwmjuo6c.vf \
tex-uwmjuo6d.tfm \
tex-uwmjuo6d.vf \
tex-uwmjuo6e.tfm \
tex-uwmjuo6e.vf \
tex-uwmjuo6f.tfm \
tex-uwmjuo6f.vf \
tex-uwmjuo70.tfm \
tex-uwmjuo70.vf \
tex-uwmjuo71.tfm \
tex-uwmjuo71.vf \
tex-uwmjuo72.tfm \
tex-uwmjuo72.vf \
tex-uwmjuo73.tfm \
tex-uwmjuo73.vf \
tex-uwmjuo74.tfm \
tex-uwmjuo74.vf \
tex-uwmjuo75.tfm \
tex-uwmjuo75.vf \
tex-uwmjuo76.tfm \
tex-uwmjuo76.vf \
tex-uwmjuo77.tfm \
tex-uwmjuo77.vf \
tex-uwmjuo78.tfm \
tex-uwmjuo78.vf \
tex-uwmjuo79.tfm \
tex-uwmjuo79.vf \
tex-uwmjuo7a.tfm \
tex-uwmjuo7a.vf \
tex-uwmjuo7b.tfm \
tex-uwmjuo7b.vf \
tex-uwmjuo7c.tfm \
tex-uwmjuo7c.vf \
tex-uwmjuo7d.tfm \
tex-uwmjuo7d.vf \
tex-uwmjuo7e.tfm \
tex-uwmjuo7e.vf \
tex-uwmjuo7f.tfm \
tex-uwmjuo7f.vf \
tex-uwmjuo80.tfm \
tex-uwmjuo80.vf \
tex-uwmjuo81.tfm \
tex-uwmjuo81.vf \
tex-uwmjuo82.tfm \
tex-uwmjuo82.vf \
tex-uwmjuo83.tfm \
tex-uwmjuo83.vf \
tex-uwmjuo84.tfm \
tex-uwmjuo84.vf \
tex-uwmjuo85.tfm \
tex-uwmjuo85.vf \
tex-uwmjuo86.tfm \
tex-uwmjuo86.vf \
tex-uwmjuo87.tfm \
tex-uwmjuo87.vf \
tex-uwmjuo88.tfm \
tex-uwmjuo88.vf \
tex-uwmjuo89.tfm \
tex-uwmjuo89.vf \
tex-uwmjuo8a.tfm \
tex-uwmjuo8a.vf \
tex-uwmjuo8b.tfm \
tex-uwmjuo8b.vf \
tex-uwmjuo8c.tfm \
tex-uwmjuo8c.vf \
tex-uwmjuo8d.tfm \
tex-uwmjuo8d.vf \
tex-uwmjuo8e.tfm \
tex-uwmjuo8e.vf \
tex-uwmjuo8f.tfm \
tex-uwmjuo8f.vf \
tex-uwmjuo90.tfm \
tex-uwmjuo90.vf \
tex-uwmjuo91.tfm \
tex-uwmjuo91.vf \
tex-uwmjuo92.tfm \
tex-uwmjuo92.vf \
tex-uwmjuo93.tfm \
tex-uwmjuo93.vf \
tex-uwmjuo94.tfm \
tex-uwmjuo94.vf \
tex-uwmjuo95.tfm \
tex-uwmjuo95.vf \
tex-uwmjuo96.tfm \
tex-uwmjuo96.vf \
tex-uwmjuo97.tfm \
tex-uwmjuo97.vf \
tex-uwmjuo98.tfm \
tex-uwmjuo98.vf \
tex-uwmjuo99.tfm \
tex-uwmjuo99.vf \
tex-uwmjuo9a.tfm \
tex-uwmjuo9a.vf \
tex-uwmjuo9b.tfm \
tex-uwmjuo9b.vf \
tex-uwmjuo9c.tfm \
tex-uwmjuo9c.vf \
tex-uwmjuo9d.tfm \
tex-uwmjuo9d.vf \
tex-uwmjuo9e.tfm \
tex-uwmjuo9e.vf \
tex-uwmjuo9f.tfm \
tex-uwmjuo9f.vf \
tex-uwmjuoac.tfm \
tex-uwmjuoac.vf \
tex-uwmjuoad.tfm \
tex-uwmjuoad.vf \
tex-uwmjuoae.tfm \
tex-uwmjuoae.vf \
tex-uwmjuoaf.tfm \
tex-uwmjuoaf.vf \
tex-uwmjuob0.tfm \
tex-uwmjuob0.vf \
tex-uwmjuob1.tfm \
tex-uwmjuob1.vf \
tex-uwmjuob2.tfm \
tex-uwmjuob2.vf \
tex-uwmjuob3.tfm \
tex-uwmjuob3.vf \
tex-uwmjuob4.tfm \
tex-uwmjuob4.vf \
tex-uwmjuob5.tfm \
tex-uwmjuob5.vf \
tex-uwmjuob6.tfm \
tex-uwmjuob6.vf \
tex-uwmjuob7.tfm \
tex-uwmjuob7.vf \
tex-uwmjuob8.tfm \
tex-uwmjuob8.vf \
tex-uwmjuob9.tfm \
tex-uwmjuob9.vf \
tex-uwmjuoba.tfm \
tex-uwmjuoba.vf \
tex-uwmjuobb.tfm \
tex-uwmjuobb.vf \
tex-uwmjuobc.tfm \
tex-uwmjuobc.vf \
tex-uwmjuobd.tfm \
tex-uwmjuobd.vf \
tex-uwmjuobe.tfm \
tex-uwmjuobe.vf \
tex-uwmjuobf.tfm \
tex-uwmjuobf.vf \
tex-uwmjuoc0.tfm \
tex-uwmjuoc0.vf \
tex-uwmjuoc1.tfm \
tex-uwmjuoc1.vf \
tex-uwmjuoc2.tfm \
tex-uwmjuoc2.vf \
tex-uwmjuoc3.tfm \
tex-uwmjuoc3.vf \
tex-uwmjuoc4.tfm \
tex-uwmjuoc4.vf \
tex-uwmjuoc5.tfm \
tex-uwmjuoc5.vf \
tex-uwmjuoc6.tfm \
tex-uwmjuoc6.vf \
tex-uwmjuoc7.tfm \
tex-uwmjuoc7.vf \
tex-uwmjuoc8.tfm \
tex-uwmjuoc8.vf \
tex-uwmjuoc9.tfm \
tex-uwmjuoc9.vf \
tex-uwmjuoca.tfm \
tex-uwmjuoca.vf \
tex-uwmjuocb.tfm \
tex-uwmjuocb.vf \
tex-uwmjuocc.tfm \
tex-uwmjuocc.vf \
tex-uwmjuocd.tfm \
tex-uwmjuocd.vf \
tex-uwmjuoce.tfm \
tex-uwmjuoce.vf \
tex-uwmjuocf.tfm \
tex-uwmjuocf.vf \
tex-uwmjuod0.tfm \
tex-uwmjuod0.vf \
tex-uwmjuod1.tfm \
tex-uwmjuod1.vf \
tex-uwmjuod2.tfm \
tex-uwmjuod2.vf \
tex-uwmjuod3.tfm \
tex-uwmjuod3.vf \
tex-uwmjuod4.tfm \
tex-uwmjuod4.vf \
tex-uwmjuod5.tfm \
tex-uwmjuod5.vf \
tex-uwmjuod6.tfm \
tex-uwmjuod6.vf \
tex-uwmjuod7.tfm \
tex-uwmjuod7.vf \
tex-uwmjuof9.tfm \
tex-uwmjuof9.vf \
tex-uwmjuofa.tfm \
tex-uwmjuofa.vf \
tex-uwmjuoff.tfm \
tex-uwmjuoff.vf \
tex-uwmjx00.tfm \
tex-uwmjx00.vf \
tex-uwmjx01.tfm \
tex-uwmjx01.vf \
tex-uwmjx02.tfm \
tex-uwmjx02.vf \
tex-uwmjx03.tfm \
tex-uwmjx03.vf \
tex-uwmjx04.tfm \
tex-uwmjx04.vf \
tex-uwmjx20.tfm \
tex-uwmjx20.vf \
tex-uwmjx21.tfm \
tex-uwmjx21.vf \
tex-uwmjx22.tfm \
tex-uwmjx22.vf \
tex-uwmjx23.tfm \
tex-uwmjx23.vf \
tex-uwmjx24.tfm \
tex-uwmjx24.vf \
tex-uwmjx25.tfm \
tex-uwmjx25.vf \
tex-uwmjx26.tfm \
tex-uwmjx26.vf \
tex-uwmjx30.tfm \
tex-uwmjx30.vf \
tex-uwmjx31.tfm \
tex-uwmjx31.vf \
tex-uwmjx32.tfm \
tex-uwmjx32.vf \
tex-uwmjx33.tfm \
tex-uwmjx33.vf \
tex-uwmjx4e.tfm \
tex-uwmjx4e.vf \
tex-uwmjx4f.tfm \
tex-uwmjx4f.vf \
tex-uwmjx50.tfm \
tex-uwmjx50.vf \
tex-uwmjx51.tfm \
tex-uwmjx51.vf \
tex-uwmjx52.tfm \
tex-uwmjx52.vf \
tex-uwmjx53.tfm \
tex-uwmjx53.vf \
tex-uwmjx54.tfm \
tex-uwmjx54.vf \
tex-uwmjx55.tfm \
tex-uwmjx55.vf \
tex-uwmjx56.tfm \
tex-uwmjx56.vf \
tex-uwmjx57.tfm \
tex-uwmjx57.vf \
tex-uwmjx58.tfm \
tex-uwmjx58.vf \
tex-uwmjx59.tfm \
tex-uwmjx59.vf \
tex-uwmjx5a.tfm \
tex-uwmjx5a.vf \
tex-uwmjx5b.tfm \
tex-uwmjx5b.vf \
tex-uwmjx5c.tfm \
tex-uwmjx5c.vf \
tex-uwmjx5d.tfm \
tex-uwmjx5d.vf \
tex-uwmjx5e.tfm \
tex-uwmjx5e.vf \
tex-uwmjx5f.tfm \
tex-uwmjx5f.vf \
tex-uwmjx60.tfm \
tex-uwmjx60.vf \
tex-uwmjx61.tfm \
tex-uwmjx61.vf \
tex-uwmjx62.tfm \
tex-uwmjx62.vf \
tex-uwmjx63.tfm \
tex-uwmjx63.vf \
tex-uwmjx64.tfm \
tex-uwmjx64.vf \
tex-uwmjx65.tfm \
tex-uwmjx65.vf \
tex-uwmjx66.tfm \
tex-uwmjx66.vf \
tex-uwmjx67.tfm \
tex-uwmjx67.vf \
tex-uwmjx68.tfm \
tex-uwmjx68.vf \
tex-uwmjx69.tfm \
tex-uwmjx69.vf \
tex-uwmjx6a.tfm \
tex-uwmjx6a.vf \
tex-uwmjx6b.tfm \
tex-uwmjx6b.vf \
tex-uwmjx6c.tfm \
tex-uwmjx6c.vf \
tex-uwmjx6d.tfm \
tex-uwmjx6d.vf \
tex-uwmjx6e.tfm \
tex-uwmjx6e.vf \
tex-uwmjx6f.tfm \
tex-uwmjx6f.vf \
tex-uwmjx70.tfm \
tex-uwmjx70.vf \
tex-uwmjx71.tfm \
tex-uwmjx71.vf \
tex-uwmjx72.tfm \
tex-uwmjx72.vf \
tex-uwmjx73.tfm \
tex-uwmjx73.vf \
tex-uwmjx74.tfm \
tex-uwmjx74.vf \
tex-uwmjx75.tfm \
tex-uwmjx75.vf \
tex-uwmjx76.tfm \
tex-uwmjx76.vf \
tex-uwmjx77.tfm \
tex-uwmjx77.vf \
tex-uwmjx78.tfm \
tex-uwmjx78.vf \
tex-uwmjx79.tfm \
tex-uwmjx79.vf \
tex-uwmjx7a.tfm \
tex-uwmjx7a.vf \
tex-uwmjx7b.tfm \
tex-uwmjx7b.vf \
tex-uwmjx7c.tfm \
tex-uwmjx7c.vf \
tex-uwmjx7d.tfm \
tex-uwmjx7d.vf \
tex-uwmjx7e.tfm \
tex-uwmjx7e.vf \
tex-uwmjx7f.tfm \
tex-uwmjx7f.vf \
tex-uwmjx80.tfm \
tex-uwmjx80.vf \
tex-uwmjx81.tfm \
tex-uwmjx81.vf \
tex-uwmjx82.tfm \
tex-uwmjx82.vf \
tex-uwmjx83.tfm \
tex-uwmjx83.vf \
tex-uwmjx84.tfm \
tex-uwmjx84.vf \
tex-uwmjx85.tfm \
tex-uwmjx85.vf \
tex-uwmjx86.tfm \
tex-uwmjx86.vf \
tex-uwmjx87.tfm \
tex-uwmjx87.vf \
tex-uwmjx88.tfm \
tex-uwmjx88.vf \
tex-uwmjx89.tfm \
tex-uwmjx89.vf \
tex-uwmjx8a.tfm \
tex-uwmjx8a.vf \
tex-uwmjx8b.tfm \
tex-uwmjx8b.vf \
tex-uwmjx8c.tfm \
tex-uwmjx8c.vf \
tex-uwmjx8d.tfm \
tex-uwmjx8d.vf \
tex-uwmjx8e.tfm \
tex-uwmjx8e.vf \
tex-uwmjx8f.tfm \
tex-uwmjx8f.vf \
tex-uwmjx90.tfm \
tex-uwmjx90.vf \
tex-uwmjx91.tfm \
tex-uwmjx91.vf \
tex-uwmjx92.tfm \
tex-uwmjx92.vf \
tex-uwmjx93.tfm \
tex-uwmjx93.vf \
tex-uwmjx94.tfm \
tex-uwmjx94.vf \
tex-uwmjx95.tfm \
tex-uwmjx95.vf \
tex-uwmjx96.tfm \
tex-uwmjx96.vf \
tex-uwmjx97.tfm \
tex-uwmjx97.vf \
tex-uwmjx98.tfm \
tex-uwmjx98.vf \
tex-uwmjx99.tfm \
tex-uwmjx99.vf \
tex-uwmjx9a.tfm \
tex-uwmjx9a.vf \
tex-uwmjx9b.tfm \
tex-uwmjx9b.vf \
tex-uwmjx9c.tfm \
tex-uwmjx9c.vf \
tex-uwmjx9d.tfm \
tex-uwmjx9d.vf \
tex-uwmjx9e.tfm \
tex-uwmjx9e.vf \
tex-uwmjx9f.tfm \
tex-uwmjx9f.vf \
tex-uwmjxac.tfm \
tex-uwmjxac.vf \
tex-uwmjxad.tfm \
tex-uwmjxad.vf \
tex-uwmjxae.tfm \
tex-uwmjxae.vf \
tex-uwmjxaf.tfm \
tex-uwmjxaf.vf \
tex-uwmjxb0.tfm \
tex-uwmjxb0.vf \
tex-uwmjxb1.tfm \
tex-uwmjxb1.vf \
tex-uwmjxb2.tfm \
tex-uwmjxb2.vf \
tex-uwmjxb3.tfm \
tex-uwmjxb3.vf \
tex-uwmjxb4.tfm \
tex-uwmjxb4.vf \
tex-uwmjxb5.tfm \
tex-uwmjxb5.vf \
tex-uwmjxb6.tfm \
tex-uwmjxb6.vf \
tex-uwmjxb7.tfm \
tex-uwmjxb7.vf \
tex-uwmjxb8.tfm \
tex-uwmjxb8.vf \
tex-uwmjxb9.tfm \
tex-uwmjxb9.vf \
tex-uwmjxba.tfm \
tex-uwmjxba.vf \
tex-uwmjxbb.tfm \
tex-uwmjxbb.vf \
tex-uwmjxbc.tfm \
tex-uwmjxbc.vf \
tex-uwmjxbd.tfm \
tex-uwmjxbd.vf \
tex-uwmjxbe.tfm \
tex-uwmjxbe.vf \
tex-uwmjxbf.tfm \
tex-uwmjxbf.vf \
tex-uwmjxc0.tfm \
tex-uwmjxc0.vf \
tex-uwmjxc1.tfm \
tex-uwmjxc1.vf \
tex-uwmjxc2.tfm \
tex-uwmjxc2.vf \
tex-uwmjxc3.tfm \
tex-uwmjxc3.vf \
tex-uwmjxc4.tfm \
tex-uwmjxc4.vf \
tex-uwmjxc5.tfm \
tex-uwmjxc5.vf \
tex-uwmjxc6.tfm \
tex-uwmjxc6.vf \
tex-uwmjxc7.tfm \
tex-uwmjxc7.vf \
tex-uwmjxc8.tfm \
tex-uwmjxc8.vf \
tex-uwmjxc9.tfm \
tex-uwmjxc9.vf \
tex-uwmjxca.tfm \
tex-uwmjxca.vf \
tex-uwmjxcb.tfm \
tex-uwmjxcb.vf \
tex-uwmjxcc.tfm \
tex-uwmjxcc.vf \
tex-uwmjxcd.tfm \
tex-uwmjxcd.vf \
tex-uwmjxce.tfm \
tex-uwmjxce.vf \
tex-uwmjxcf.tfm \
tex-uwmjxcf.vf \
tex-uwmjxd0.tfm \
tex-uwmjxd0.vf \
tex-uwmjxd1.tfm \
tex-uwmjxd1.vf \
tex-uwmjxd2.tfm \
tex-uwmjxd2.vf \
tex-uwmjxd3.tfm \
tex-uwmjxd3.vf \
tex-uwmjxd4.tfm \
tex-uwmjxd4.vf \
tex-uwmjxd5.tfm \
tex-uwmjxd5.vf \
tex-uwmjxd6.tfm \
tex-uwmjxd6.vf \
tex-uwmjxd7.tfm \
tex-uwmjxd7.vf \
tex-uwmjxf9.tfm \
tex-uwmjxf9.vf \
tex-uwmjxfa.tfm \
tex-uwmjxfa.vf \
tex-uwmjxff.tfm \
tex-uwmjxff.vf \
tex-uwmjxo00.tfm \
tex-uwmjxo00.vf \
tex-uwmjxo01.tfm \
tex-uwmjxo01.vf \
tex-uwmjxo02.tfm \
tex-uwmjxo02.vf \
tex-uwmjxo03.tfm \
tex-uwmjxo03.vf \
tex-uwmjxo04.tfm \
tex-uwmjxo04.vf \
tex-uwmjxo20.tfm \
tex-uwmjxo20.vf \
tex-uwmjxo21.tfm \
tex-uwmjxo21.vf \
tex-uwmjxo22.tfm \
tex-uwmjxo22.vf \
tex-uwmjxo23.tfm \
tex-uwmjxo23.vf \
tex-uwmjxo24.tfm \
tex-uwmjxo24.vf \
tex-uwmjxo25.tfm \
tex-uwmjxo25.vf \
tex-uwmjxo26.tfm \
tex-uwmjxo26.vf \
tex-uwmjxo30.tfm \
tex-uwmjxo30.vf \
tex-uwmjxo31.tfm \
tex-uwmjxo31.vf \
tex-uwmjxo32.tfm \
tex-uwmjxo32.vf \
tex-uwmjxo33.tfm \
tex-uwmjxo33.vf \
tex-uwmjxo4e.tfm \
tex-uwmjxo4e.vf \
tex-uwmjxo4f.tfm \
tex-uwmjxo4f.vf \
tex-uwmjxo50.tfm \
tex-uwmjxo50.vf \
tex-uwmjxo51.tfm \
tex-uwmjxo51.vf \
tex-uwmjxo52.tfm \
tex-uwmjxo52.vf \
tex-uwmjxo53.tfm \
tex-uwmjxo53.vf \
tex-uwmjxo54.tfm \
tex-uwmjxo54.vf \
tex-uwmjxo55.tfm \
tex-uwmjxo55.vf \
tex-uwmjxo56.tfm \
tex-uwmjxo56.vf \
tex-uwmjxo57.tfm \
tex-uwmjxo57.vf \
tex-uwmjxo58.tfm \
tex-uwmjxo58.vf \
tex-uwmjxo59.tfm \
tex-uwmjxo59.vf \
tex-uwmjxo5a.tfm \
tex-uwmjxo5a.vf \
tex-uwmjxo5b.tfm \
tex-uwmjxo5b.vf \
tex-uwmjxo5c.tfm \
tex-uwmjxo5c.vf \
tex-uwmjxo5d.tfm \
tex-uwmjxo5d.vf \
tex-uwmjxo5e.tfm \
tex-uwmjxo5e.vf \
tex-uwmjxo5f.tfm \
tex-uwmjxo5f.vf \
tex-uwmjxo60.tfm \
tex-uwmjxo60.vf \
tex-uwmjxo61.tfm \
tex-uwmjxo61.vf \
tex-uwmjxo62.tfm \
tex-uwmjxo62.vf \
tex-uwmjxo63.tfm \
tex-uwmjxo63.vf \
tex-uwmjxo64.tfm \
tex-uwmjxo64.vf \
tex-uwmjxo65.tfm \
tex-uwmjxo65.vf \
tex-uwmjxo66.tfm \
tex-uwmjxo66.vf \
tex-uwmjxo67.tfm \
tex-uwmjxo67.vf \
tex-uwmjxo68.tfm \
tex-uwmjxo68.vf \
tex-uwmjxo69.tfm \
tex-uwmjxo69.vf \
tex-uwmjxo6a.tfm \
tex-uwmjxo6a.vf \
tex-uwmjxo6b.tfm \
tex-uwmjxo6b.vf \
tex-uwmjxo6c.tfm \
tex-uwmjxo6c.vf \
tex-uwmjxo6d.tfm \
tex-uwmjxo6d.vf \
tex-uwmjxo6e.tfm \
tex-uwmjxo6e.vf \
tex-uwmjxo6f.tfm \
tex-uwmjxo6f.vf \
tex-uwmjxo70.tfm \
tex-uwmjxo70.vf \
tex-uwmjxo71.tfm \
tex-uwmjxo71.vf \
tex-uwmjxo72.tfm \
tex-uwmjxo72.vf \
tex-uwmjxo73.tfm \
tex-uwmjxo73.vf \
tex-uwmjxo74.tfm \
tex-uwmjxo74.vf \
tex-uwmjxo75.tfm \
tex-uwmjxo75.vf \
tex-uwmjxo76.tfm \
tex-uwmjxo76.vf \
tex-uwmjxo77.tfm \
tex-uwmjxo77.vf \
tex-uwmjxo78.tfm \
tex-uwmjxo78.vf \
tex-uwmjxo79.tfm \
tex-uwmjxo79.vf \
tex-uwmjxo7a.tfm \
tex-uwmjxo7a.vf \
tex-uwmjxo7b.tfm \
tex-uwmjxo7b.vf \
tex-uwmjxo7c.tfm \
tex-uwmjxo7c.vf \
tex-uwmjxo7d.tfm \
tex-uwmjxo7d.vf \
tex-uwmjxo7e.tfm \
tex-uwmjxo7e.vf \
tex-uwmjxo7f.tfm \
tex-uwmjxo7f.vf \
tex-uwmjxo80.tfm \
tex-uwmjxo80.vf \
tex-uwmjxo81.tfm \
tex-uwmjxo81.vf \
tex-uwmjxo82.tfm \
tex-uwmjxo82.vf \
tex-uwmjxo83.tfm \
tex-uwmjxo83.vf \
tex-uwmjxo84.tfm \
tex-uwmjxo84.vf \
tex-uwmjxo85.tfm \
tex-uwmjxo85.vf \
tex-uwmjxo86.tfm \
tex-uwmjxo86.vf \
tex-uwmjxo87.tfm \
tex-uwmjxo87.vf \
tex-uwmjxo88.tfm \
tex-uwmjxo88.vf \
tex-uwmjxo89.tfm \
tex-uwmjxo89.vf \
tex-uwmjxo8a.tfm \
tex-uwmjxo8a.vf \
tex-uwmjxo8b.tfm \
tex-uwmjxo8b.vf \
tex-uwmjxo8c.tfm \
tex-uwmjxo8c.vf \
tex-uwmjxo8d.tfm \
tex-uwmjxo8d.vf \
tex-uwmjxo8e.tfm \
tex-uwmjxo8e.vf \
tex-uwmjxo8f.tfm \
tex-uwmjxo8f.vf \
tex-uwmjxo90.tfm \
tex-uwmjxo90.vf \
tex-uwmjxo91.tfm \
tex-uwmjxo91.vf \
tex-uwmjxo92.tfm \
tex-uwmjxo92.vf \
tex-uwmjxo93.tfm \
tex-uwmjxo93.vf \
tex-uwmjxo94.tfm \
tex-uwmjxo94.vf \
tex-uwmjxo95.tfm \
tex-uwmjxo95.vf \
tex-uwmjxo96.tfm \
tex-uwmjxo96.vf \
tex-uwmjxo97.tfm \
tex-uwmjxo97.vf \
tex-uwmjxo98.tfm \
tex-uwmjxo98.vf \
tex-uwmjxo99.tfm \
tex-uwmjxo99.vf \
tex-uwmjxo9a.tfm \
tex-uwmjxo9a.vf \
tex-uwmjxo9b.tfm \
tex-uwmjxo9b.vf \
tex-uwmjxo9c.tfm \
tex-uwmjxo9c.vf \
tex-uwmjxo9d.tfm \
tex-uwmjxo9d.vf \
tex-uwmjxo9e.tfm \
tex-uwmjxo9e.vf \
tex-uwmjxo9f.tfm \
tex-uwmjxo9f.vf \
tex-uwmjxoac.tfm \
tex-uwmjxoac.vf \
tex-uwmjxoad.tfm \
tex-uwmjxoad.vf \
tex-uwmjxoae.tfm \
tex-uwmjxoae.vf \
tex-uwmjxoaf.tfm \
tex-uwmjxoaf.vf \
tex-uwmjxob0.tfm \
tex-uwmjxob0.vf \
tex-uwmjxob1.tfm \
tex-uwmjxob1.vf \
tex-uwmjxob2.tfm \
tex-uwmjxob2.vf \
tex-uwmjxob3.tfm \
tex-uwmjxob3.vf \
tex-uwmjxob4.tfm \
tex-uwmjxob4.vf \
tex-uwmjxob5.tfm \
tex-uwmjxob5.vf \
tex-uwmjxob6.tfm \
tex-uwmjxob6.vf \
tex-uwmjxob7.tfm \
tex-uwmjxob7.vf \
tex-uwmjxob8.tfm \
tex-uwmjxob8.vf \
tex-uwmjxob9.tfm \
tex-uwmjxob9.vf \
tex-uwmjxoba.tfm \
tex-uwmjxoba.vf \
tex-uwmjxobb.tfm \
tex-uwmjxobb.vf \
tex-uwmjxobc.tfm \
tex-uwmjxobc.vf \
tex-uwmjxobd.tfm \
tex-uwmjxobd.vf \
tex-uwmjxobe.tfm \
tex-uwmjxobe.vf \
tex-uwmjxobf.tfm \
tex-uwmjxobf.vf \
tex-uwmjxoc0.tfm \
tex-uwmjxoc0.vf \
tex-uwmjxoc1.tfm \
tex-uwmjxoc1.vf \
tex-uwmjxoc2.tfm \
tex-uwmjxoc2.vf \
tex-uwmjxoc3.tfm \
tex-uwmjxoc3.vf \
tex-uwmjxoc4.tfm \
tex-uwmjxoc4.vf \
tex-uwmjxoc5.tfm \
tex-uwmjxoc5.vf \
tex-uwmjxoc6.tfm \
tex-uwmjxoc6.vf \
tex-uwmjxoc7.tfm \
tex-uwmjxoc7.vf \
tex-uwmjxoc8.tfm \
tex-uwmjxoc8.vf \
tex-uwmjxoc9.tfm \
tex-uwmjxoc9.vf \
tex-uwmjxoca.tfm \
tex-uwmjxoca.vf \
tex-uwmjxocb.tfm \
tex-uwmjxocb.vf \
tex-uwmjxocc.tfm \
tex-uwmjxocc.vf \
tex-uwmjxocd.tfm \
tex-uwmjxocd.vf \
tex-uwmjxoce.tfm \
tex-uwmjxoce.vf \
tex-uwmjxocf.tfm \
tex-uwmjxocf.vf \
tex-uwmjxod0.tfm \
tex-uwmjxod0.vf \
tex-uwmjxod1.tfm \
tex-uwmjxod1.vf \
tex-uwmjxod2.tfm \
tex-uwmjxod2.vf \
tex-uwmjxod3.tfm \
tex-uwmjxod3.vf \
tex-uwmjxod4.tfm \
tex-uwmjxod4.vf \
tex-uwmjxod5.tfm \
tex-uwmjxod5.vf \
tex-uwmjxod6.tfm \
tex-uwmjxod6.vf \
tex-uwmjxod7.tfm \
tex-uwmjxod7.vf \
tex-uwmjxof9.tfm \
tex-uwmjxof9.vf \
tex-uwmjxofa.tfm \
tex-uwmjxofa.vf \
tex-uwmjxoff.tfm \
tex-uwmjxoff.vf \
tex-wmj0.tfm \
tex-wmj0.vf \
tex-wmj04.tfm \
tex-wmj04.vf \
tex-wmj05.tfm \
tex-wmj05.vf \
tex-wmj06.tfm \
tex-wmj06.vf \
tex-wmj07.tfm \
tex-wmj07.vf \
tex-wmj1.tfm \
tex-wmj1.vf \
tex-wmj10.tfm \
tex-wmj10.vf \
tex-wmj11.tfm \
tex-wmj11.vf \
tex-wmj12.tfm \
tex-wmj12.vf \
tex-wmj13.tfm \
tex-wmj13.vf \
tex-wmj14.tfm \
tex-wmj14.vf \
tex-wmj15.tfm \
tex-wmj15.vf \
tex-wmj16.tfm \
tex-wmj16.vf \
tex-wmj17.tfm \
tex-wmj17.vf \
tex-wmj18.tfm \
tex-wmj18.vf \
tex-wmj19.tfm \
tex-wmj19.vf \
tex-wmj2.tfm \
tex-wmj2.vf \
tex-wmj20.tfm \
tex-wmj20.vf \
tex-wmj21.tfm \
tex-wmj21.vf \
tex-wmj22.tfm \
tex-wmj22.vf \
tex-wmj23.tfm \
tex-wmj23.vf \
tex-wmj24.tfm \
tex-wmj24.vf \
tex-wmj25.tfm \
tex-wmj25.vf \
tex-wmj26.tfm \
tex-wmj26.vf \
tex-wmj27.tfm \
tex-wmj27.vf \
tex-wmj28.tfm \
tex-wmj28.vf \
tex-wmj29.tfm \
tex-wmj29.vf \
tex-wmj3.tfm \
tex-wmj3.vf \
tex-wmj4.tfm \
tex-wmj4.vf \
tex-wmj5.tfm \
tex-wmj5.vf \
tex-wmj6.tfm \
tex-wmj6.vf \
tex-wmj7.tfm \
tex-wmj7.vf \
tex-wmj8.tfm \
tex-wmj8.vf \
tex-wmj9.tfm \
tex-wmj9.vf \
tex-wmjc0.tfm \
tex-wmjc0.vf \
tex-wmjc04.tfm \
tex-wmjc04.vf \
tex-wmjc05.tfm \
tex-wmjc05.vf \
tex-wmjc06.tfm \
tex-wmjc06.vf \
tex-wmjc07.tfm \
tex-wmjc07.vf \
tex-wmjc1.tfm \
tex-wmjc1.vf \
tex-wmjc10.tfm \
tex-wmjc10.vf \
tex-wmjc11.tfm \
tex-wmjc11.vf \
tex-wmjc12.tfm \
tex-wmjc12.vf \
tex-wmjc13.tfm \
tex-wmjc13.vf \
tex-wmjc14.tfm \
tex-wmjc14.vf \
tex-wmjc15.tfm \
tex-wmjc15.vf \
tex-wmjc16.tfm \
tex-wmjc16.vf \
tex-wmjc17.tfm \
tex-wmjc17.vf \
tex-wmjc18.tfm \
tex-wmjc18.vf \
tex-wmjc19.tfm \
tex-wmjc19.vf \
tex-wmjc2.tfm \
tex-wmjc2.vf \
tex-wmjc20.tfm \
tex-wmjc20.vf \
tex-wmjc21.tfm \
tex-wmjc21.vf \
tex-wmjc22.tfm \
tex-wmjc22.vf \
tex-wmjc23.tfm \
tex-wmjc23.vf \
tex-wmjc24.tfm \
tex-wmjc24.vf \
tex-wmjc25.tfm \
tex-wmjc25.vf \
tex-wmjc26.tfm \
tex-wmjc26.vf \
tex-wmjc27.tfm \
tex-wmjc27.vf \
tex-wmjc28.tfm \
tex-wmjc28.vf \
tex-wmjc29.tfm \
tex-wmjc29.vf \
tex-wmjc3.tfm \
tex-wmjc3.vf \
tex-wmjc4.tfm \
tex-wmjc4.vf \
tex-wmjc5.tfm \
tex-wmjc5.vf \
tex-wmjc6.tfm \
tex-wmjc6.vf \
tex-wmjc7.tfm \
tex-wmjc7.vf \
tex-wmjc8.tfm \
tex-wmjc8.vf \
tex-wmjc9.tfm \
tex-wmjc9.vf \
tex-wmjco0.tfm \
tex-wmjco0.vf \
tex-wmjco04.tfm \
tex-wmjco04.vf \
tex-wmjco05.tfm \
tex-wmjco05.vf \
tex-wmjco06.tfm \
tex-wmjco06.vf \
tex-wmjco07.tfm \
tex-wmjco07.vf \
tex-wmjco1.tfm \
tex-wmjco1.vf \
tex-wmjco10.tfm \
tex-wmjco10.vf \
tex-wmjco11.tfm \
tex-wmjco11.vf \
tex-wmjco12.tfm \
tex-wmjco12.vf \
tex-wmjco13.tfm \
tex-wmjco13.vf \
tex-wmjco14.tfm \
tex-wmjco14.vf \
tex-wmjco15.tfm \
tex-wmjco15.vf \
tex-wmjco16.tfm \
tex-wmjco16.vf \
tex-wmjco17.tfm \
tex-wmjco17.vf \
tex-wmjco18.tfm \
tex-wmjco18.vf \
tex-wmjco19.tfm \
tex-wmjco19.vf \
tex-wmjco2.tfm \
tex-wmjco2.vf \
tex-wmjco20.tfm \
tex-wmjco20.vf \
tex-wmjco21.tfm \
tex-wmjco21.vf \
tex-wmjco22.tfm \
tex-wmjco22.vf \
tex-wmjco23.tfm \
tex-wmjco23.vf \
tex-wmjco24.tfm \
tex-wmjco24.vf \
tex-wmjco25.tfm \
tex-wmjco25.vf \
tex-wmjco26.tfm \
tex-wmjco26.vf \
tex-wmjco27.tfm \
tex-wmjco27.vf \
tex-wmjco28.tfm \
tex-wmjco28.vf \
tex-wmjco29.tfm \
tex-wmjco29.vf \
tex-wmjco3.tfm \
tex-wmjco3.vf \
tex-wmjco4.tfm \
tex-wmjco4.vf \
tex-wmjco5.tfm \
tex-wmjco5.vf \
tex-wmjco6.tfm \
tex-wmjco6.vf \
tex-wmjco7.tfm \
tex-wmjco7.vf \
tex-wmjco8.tfm \
tex-wmjco8.vf \
tex-wmjco9.tfm \
tex-wmjco9.vf \
tex-wmjo0.tfm \
tex-wmjo0.vf \
tex-wmjo04.tfm \
tex-wmjo04.vf \
tex-wmjo05.tfm \
tex-wmjo05.vf \
tex-wmjo06.tfm \
tex-wmjo06.vf \
tex-wmjo07.tfm \
tex-wmjo07.vf \
tex-wmjo1.tfm \
tex-wmjo1.vf \
tex-wmjo10.tfm \
tex-wmjo10.vf \
tex-wmjo11.tfm \
tex-wmjo11.vf \
tex-wmjo12.tfm \
tex-wmjo12.vf \
tex-wmjo13.tfm \
tex-wmjo13.vf \
tex-wmjo14.tfm \
tex-wmjo14.vf \
tex-wmjo15.tfm \
tex-wmjo15.vf \
tex-wmjo16.tfm \
tex-wmjo16.vf \
tex-wmjo17.tfm \
tex-wmjo17.vf \
tex-wmjo18.tfm \
tex-wmjo18.vf \
tex-wmjo19.tfm \
tex-wmjo19.vf \
tex-wmjo2.tfm \
tex-wmjo2.vf \
tex-wmjo20.tfm \
tex-wmjo20.vf \
tex-wmjo21.tfm \
tex-wmjo21.vf \
tex-wmjo22.tfm \
tex-wmjo22.vf \
tex-wmjo23.tfm \
tex-wmjo23.vf \
tex-wmjo24.tfm \
tex-wmjo24.vf \
tex-wmjo25.tfm \
tex-wmjo25.vf \
tex-wmjo26.tfm \
tex-wmjo26.vf \
tex-wmjo27.tfm \
tex-wmjo27.vf \
tex-wmjo28.tfm \
tex-wmjo28.vf \
tex-wmjo29.tfm \
tex-wmjo29.vf \
tex-wmjo3.tfm \
tex-wmjo3.vf \
tex-wmjo4.tfm \
tex-wmjo4.vf \
tex-wmjo5.tfm \
tex-wmjo5.vf \
tex-wmjo6.tfm \
tex-wmjo6.vf \
tex-wmjo7.tfm \
tex-wmjo7.vf \
tex-wmjo8.tfm \
tex-wmjo8.vf \
tex-wmjo9.tfm \
tex-wmjo9.vf \
tex-wmju0.tfm \
tex-wmju0.vf \
tex-wmju04.tfm \
tex-wmju04.vf \
tex-wmju05.tfm \
tex-wmju05.vf \
tex-wmju06.tfm \
tex-wmju06.vf \
tex-wmju07.tfm \
tex-wmju07.vf \
tex-wmju1.tfm \
tex-wmju1.vf \
tex-wmju10.tfm \
tex-wmju10.vf \
tex-wmju11.tfm \
tex-wmju11.vf \
tex-wmju12.tfm \
tex-wmju12.vf \
tex-wmju13.tfm \
tex-wmju13.vf \
tex-wmju14.tfm \
tex-wmju14.vf \
tex-wmju15.tfm \
tex-wmju15.vf \
tex-wmju16.tfm \
tex-wmju16.vf \
tex-wmju17.tfm \
tex-wmju17.vf \
tex-wmju18.tfm \
tex-wmju18.vf \
tex-wmju19.tfm \
tex-wmju19.vf \
tex-wmju2.tfm \
tex-wmju2.vf \
tex-wmju20.tfm \
tex-wmju20.vf \
tex-wmju21.tfm \
tex-wmju21.vf \
tex-wmju22.tfm \
tex-wmju22.vf \
tex-wmju23.tfm \
tex-wmju23.vf \
tex-wmju24.tfm \
tex-wmju24.vf \
tex-wmju25.tfm \
tex-wmju25.vf \
tex-wmju26.tfm \
tex-wmju26.vf \
tex-wmju27.tfm \
tex-wmju27.vf \
tex-wmju28.tfm \
tex-wmju28.vf \
tex-wmju29.tfm \
tex-wmju29.vf \
tex-wmju3.tfm \
tex-wmju3.vf \
tex-wmju4.tfm \
tex-wmju4.vf \
tex-wmju5.tfm \
tex-wmju5.vf \
tex-wmju6.tfm \
tex-wmju6.vf \
tex-wmju7.tfm \
tex-wmju7.vf \
tex-wmju8.tfm \
tex-wmju8.vf \
tex-wmju9.tfm \
tex-wmju9.vf \
tex-wmjuo0.tfm \
tex-wmjuo0.vf \
tex-wmjuo04.tfm \
tex-wmjuo04.vf \
tex-wmjuo05.tfm \
tex-wmjuo05.vf \
tex-wmjuo06.tfm \
tex-wmjuo06.vf \
tex-wmjuo07.tfm \
tex-wmjuo07.vf \
tex-wmjuo1.tfm \
tex-wmjuo1.vf \
tex-wmjuo10.tfm \
tex-wmjuo10.vf \
tex-wmjuo11.tfm \
tex-wmjuo11.vf \
tex-wmjuo12.tfm \
tex-wmjuo12.vf \
tex-wmjuo13.tfm \
tex-wmjuo13.vf \
tex-wmjuo14.tfm \
tex-wmjuo14.vf \
tex-wmjuo15.tfm \
tex-wmjuo15.vf \
tex-wmjuo16.tfm \
tex-wmjuo16.vf \
tex-wmjuo17.tfm \
tex-wmjuo17.vf \
tex-wmjuo18.tfm \
tex-wmjuo18.vf \
tex-wmjuo19.tfm \
tex-wmjuo19.vf \
tex-wmjuo2.tfm \
tex-wmjuo2.vf \
tex-wmjuo20.tfm \
tex-wmjuo20.vf \
tex-wmjuo21.tfm \
tex-wmjuo21.vf \
tex-wmjuo22.tfm \
tex-wmjuo22.vf \
tex-wmjuo23.tfm \
tex-wmjuo23.vf \
tex-wmjuo24.tfm \
tex-wmjuo24.vf \
tex-wmjuo25.tfm \
tex-wmjuo25.vf \
tex-wmjuo26.tfm \
tex-wmjuo26.vf \
tex-wmjuo27.tfm \
tex-wmjuo27.vf \
tex-wmjuo28.tfm \
tex-wmjuo28.vf \
tex-wmjuo29.tfm \
tex-wmjuo29.vf \
tex-wmjuo3.tfm \
tex-wmjuo3.vf \
tex-wmjuo4.tfm \
tex-wmjuo4.vf \
tex-wmjuo5.tfm \
tex-wmjuo5.vf \
tex-wmjuo6.tfm \
tex-wmjuo6.vf \
tex-wmjuo7.tfm \
tex-wmjuo7.vf \
tex-wmjuo8.tfm \
tex-wmjuo8.vf \
tex-wmjuo9.tfm \
tex-wmjuo9.vf \
tex-wmjx0.tfm \
tex-wmjx0.vf \
tex-wmjx04.tfm \
tex-wmjx04.vf \
tex-wmjx05.tfm \
tex-wmjx05.vf \
tex-wmjx06.tfm \
tex-wmjx06.vf \
tex-wmjx07.tfm \
tex-wmjx07.vf \
tex-wmjx1.tfm \
tex-wmjx1.vf \
tex-wmjx10.tfm \
tex-wmjx10.vf \
tex-wmjx11.tfm \
tex-wmjx11.vf \
tex-wmjx12.tfm \
tex-wmjx12.vf \
tex-wmjx13.tfm \
tex-wmjx13.vf \
tex-wmjx14.tfm \
tex-wmjx14.vf \
tex-wmjx15.tfm \
tex-wmjx15.vf \
tex-wmjx16.tfm \
tex-wmjx16.vf \
tex-wmjx17.tfm \
tex-wmjx17.vf \
tex-wmjx18.tfm \
tex-wmjx18.vf \
tex-wmjx19.tfm \
tex-wmjx19.vf \
tex-wmjx2.tfm \
tex-wmjx2.vf \
tex-wmjx20.tfm \
tex-wmjx20.vf \
tex-wmjx21.tfm \
tex-wmjx21.vf \
tex-wmjx22.tfm \
tex-wmjx22.vf \
tex-wmjx23.tfm \
tex-wmjx23.vf \
tex-wmjx24.tfm \
tex-wmjx24.vf \
tex-wmjx25.tfm \
tex-wmjx25.vf \
tex-wmjx26.tfm \
tex-wmjx26.vf \
tex-wmjx27.tfm \
tex-wmjx27.vf \
tex-wmjx28.tfm \
tex-wmjx28.vf \
tex-wmjx29.tfm \
tex-wmjx29.vf \
tex-wmjx3.tfm \
tex-wmjx3.vf \
tex-wmjx4.tfm \
tex-wmjx4.vf \
tex-wmjx5.tfm \
tex-wmjx5.vf \
tex-wmjx6.tfm \
tex-wmjx6.vf \
tex-wmjx7.tfm \
tex-wmjx7.vf \
tex-wmjx8.tfm \
tex-wmjx8.vf \
tex-wmjx9.tfm \
tex-wmjx9.vf \
tex-wmjxo0.tfm \
tex-wmjxo0.vf \
tex-wmjxo04.tfm \
tex-wmjxo04.vf \
tex-wmjxo05.tfm \
tex-wmjxo05.vf \
tex-wmjxo06.tfm \
tex-wmjxo06.vf \
tex-wmjxo07.tfm \
tex-wmjxo07.vf \
tex-wmjxo1.tfm \
tex-wmjxo1.vf \
tex-wmjxo10.tfm \
tex-wmjxo10.vf \
tex-wmjxo11.tfm \
tex-wmjxo11.vf \
tex-wmjxo12.tfm \
tex-wmjxo12.vf \
tex-wmjxo13.tfm \
tex-wmjxo13.vf \
tex-wmjxo14.tfm \
tex-wmjxo14.vf \
tex-wmjxo15.tfm \
tex-wmjxo15.vf \
tex-wmjxo16.tfm \
tex-wmjxo16.vf \
tex-wmjxo17.tfm \
tex-wmjxo17.vf \
tex-wmjxo18.tfm \
tex-wmjxo18.vf \
tex-wmjxo19.tfm \
tex-wmjxo19.vf \
tex-wmjxo2.tfm \
tex-wmjxo2.vf \
tex-wmjxo20.tfm \
tex-wmjxo20.vf \
tex-wmjxo21.tfm \
tex-wmjxo21.vf \
tex-wmjxo22.tfm \
tex-wmjxo22.vf \
tex-wmjxo23.tfm \
tex-wmjxo23.vf \
tex-wmjxo24.tfm \
tex-wmjxo24.vf \
tex-wmjxo25.tfm \
tex-wmjxo25.vf \
tex-wmjxo26.tfm \
tex-wmjxo26.vf \
tex-wmjxo27.tfm \
tex-wmjxo27.vf \
tex-wmjxo28.tfm \
tex-wmjxo28.vf \
tex-wmjxo29.tfm \
tex-wmjxo29.vf \
tex-wmjxo3.tfm \
tex-wmjxo3.vf \
tex-wmjxo4.tfm \
tex-wmjxo4.vf \
tex-wmjxo5.tfm \
tex-wmjxo5.vf \
tex-wmjxo6.tfm \
tex-wmjxo6.vf \
tex-wmjxo7.tfm \
tex-wmjxo7.vf \
tex-wmjxo8.tfm \
tex-wmjxo8.vf \
tex-wmjxo9.tfm \
tex-wmjxo9.vf \
texlive-uhc"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-updmap.cfg \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin \
texlive-uhc-fonts"

inherit rpm
