SUMMARY = "An extension to pgfplots' \\addplot macro"
DESCRIPTION = "This package is an extension to pgfplots. It extends the \
\\addplot macro by a facility which allows modification of data \
files while they are read. With luaaddplot it is no longer \
necessary to pre-process data files generated by measuring \
devices with external scripts. This package can be used with \
plain LuaTeX or LuaLaTeX."
LICENSE = "LPPL-1.0"

PV = "2023.208.1.0svn62842"

RPM_NAME = "texlive-luaaddplot-2023.208.1.0svn62842-53.1.noarch.rpm"
RPM_HASH = "842ac6d21838d1caa72d7b8e6e396d4c30e9ca146fa442e81bb60a5fba8b4b35862068f230bf0d8d9e6c080a43ff56bf955234e99f8693768ae8354417e90b10"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-luaaddplot.sty \
tex-luaaddplot.tex \
texlive-luaaddplot"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
