SUMMARY = "LaTeX support for the Ibarra Real Nova family of fonts"
DESCRIPTION = "The Ibarra Real Nova is a revival of a typeface designed by \
Geronimo Gil for the publication of Don Quixote for the Real \
Academia de la Lengua in 1780. Joaquin Ibarra was the printer."
LICENSE = "OFL-1.1"

PV = "2023.208.svn64567"

RPM_NAME = "texlive-ibarra-2023.208.svn64567-53.1.noarch.rpm"
RPM_HASH = "a9930f91173018772a4e94bc12ff78da589f0a85cf08d4ba2f900e20b192cfa65d05b9f96a90bc08a831c6463f54ed3eb4e658c191b02d94cf983f11567557c6"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-IbarraRealNova-Bold-lf-ly1--base.tfm \
tex-IbarraRealNova-Bold-lf-ly1.tfm \
tex-IbarraRealNova-Bold-lf-ly1.vf \
tex-IbarraRealNova-Bold-lf-ot1.tfm \
tex-IbarraRealNova-Bold-lf-sc-ly1--base.tfm \
tex-IbarraRealNova-Bold-lf-sc-ly1.tfm \
tex-IbarraRealNova-Bold-lf-sc-ly1.vf \
tex-IbarraRealNova-Bold-lf-sc-ot1--base.tfm \
tex-IbarraRealNova-Bold-lf-sc-ot1.tfm \
tex-IbarraRealNova-Bold-lf-sc-ot1.vf \
tex-IbarraRealNova-Bold-lf-sc-t1--base.tfm \
tex-IbarraRealNova-Bold-lf-sc-t1.tfm \
tex-IbarraRealNova-Bold-lf-sc-t1.vf \
tex-IbarraRealNova-Bold-lf-t1--base.tfm \
tex-IbarraRealNova-Bold-lf-t1.tfm \
tex-IbarraRealNova-Bold-lf-t1.vf \
tex-IbarraRealNova-Bold-lf-ts1--base.tfm \
tex-IbarraRealNova-Bold-lf-ts1.tfm \
tex-IbarraRealNova-Bold-lf-ts1.vf \
tex-IbarraRealNova-Bold-osf-ly1--base.tfm \
tex-IbarraRealNova-Bold-osf-ly1.tfm \
tex-IbarraRealNova-Bold-osf-ly1.vf \
tex-IbarraRealNova-Bold-osf-ot1.tfm \
tex-IbarraRealNova-Bold-osf-sc-ly1--base.tfm \
tex-IbarraRealNova-Bold-osf-sc-ly1.tfm \
tex-IbarraRealNova-Bold-osf-sc-ly1.vf \
tex-IbarraRealNova-Bold-osf-sc-ot1--base.tfm \
tex-IbarraRealNova-Bold-osf-sc-ot1.tfm \
tex-IbarraRealNova-Bold-osf-sc-ot1.vf \
tex-IbarraRealNova-Bold-osf-sc-t1--base.tfm \
tex-IbarraRealNova-Bold-osf-sc-t1.tfm \
tex-IbarraRealNova-Bold-osf-sc-t1.vf \
tex-IbarraRealNova-Bold-osf-t1--base.tfm \
tex-IbarraRealNova-Bold-osf-t1.tfm \
tex-IbarraRealNova-Bold-osf-t1.vf \
tex-IbarraRealNova-Bold-osf-ts1--base.tfm \
tex-IbarraRealNova-Bold-osf-ts1.tfm \
tex-IbarraRealNova-Bold-osf-ts1.vf \
tex-IbarraRealNova-Bold-sup-ly1--base.tfm \
tex-IbarraRealNova-Bold-sup-ly1.tfm \
tex-IbarraRealNova-Bold-sup-ly1.vf \
tex-IbarraRealNova-Bold-sup-ot1.tfm \
tex-IbarraRealNova-Bold-sup-t1--base.tfm \
tex-IbarraRealNova-Bold-sup-t1.tfm \
tex-IbarraRealNova-Bold-sup-t1.vf \
tex-IbarraRealNova-BoldItalic-lf-ly1--base.tfm \
tex-IbarraRealNova-BoldItalic-lf-ly1.tfm \
tex-IbarraRealNova-BoldItalic-lf-ly1.vf \
tex-IbarraRealNova-BoldItalic-lf-ot1.tfm \
tex-IbarraRealNova-BoldItalic-lf-sc-ly1--base.tfm \
tex-IbarraRealNova-BoldItalic-lf-sc-ly1.tfm \
tex-IbarraRealNova-BoldItalic-lf-sc-ly1.vf \
tex-IbarraRealNova-BoldItalic-lf-sc-ot1--base.tfm \
tex-IbarraRealNova-BoldItalic-lf-sc-ot1.tfm \
tex-IbarraRealNova-BoldItalic-lf-sc-ot1.vf \
tex-IbarraRealNova-BoldItalic-lf-sc-t1--base.tfm \
tex-IbarraRealNova-BoldItalic-lf-sc-t1.tfm \
tex-IbarraRealNova-BoldItalic-lf-sc-t1.vf \
tex-IbarraRealNova-BoldItalic-lf-t1--base.tfm \
tex-IbarraRealNova-BoldItalic-lf-t1.tfm \
tex-IbarraRealNova-BoldItalic-lf-t1.vf \
tex-IbarraRealNova-BoldItalic-lf-ts1--base.tfm \
tex-IbarraRealNova-BoldItalic-lf-ts1.tfm \
tex-IbarraRealNova-BoldItalic-lf-ts1.vf \
tex-IbarraRealNova-BoldItalic-osf-ly1--base.tfm \
tex-IbarraRealNova-BoldItalic-osf-ly1.tfm \
tex-IbarraRealNova-BoldItalic-osf-ly1.vf \
tex-IbarraRealNova-BoldItalic-osf-ot1.tfm \
tex-IbarraRealNova-BoldItalic-osf-sc-ly1--base.tfm \
tex-IbarraRealNova-BoldItalic-osf-sc-ly1.tfm \
tex-IbarraRealNova-BoldItalic-osf-sc-ly1.vf \
tex-IbarraRealNova-BoldItalic-osf-sc-ot1--base.tfm \
tex-IbarraRealNova-BoldItalic-osf-sc-ot1.tfm \
tex-IbarraRealNova-BoldItalic-osf-sc-ot1.vf \
tex-IbarraRealNova-BoldItalic-osf-sc-t1--base.tfm \
tex-IbarraRealNova-BoldItalic-osf-sc-t1.tfm \
tex-IbarraRealNova-BoldItalic-osf-sc-t1.vf \
tex-IbarraRealNova-BoldItalic-osf-t1--base.tfm \
tex-IbarraRealNova-BoldItalic-osf-t1.tfm \
tex-IbarraRealNova-BoldItalic-osf-t1.vf \
tex-IbarraRealNova-BoldItalic-osf-ts1--base.tfm \
tex-IbarraRealNova-BoldItalic-osf-ts1.tfm \
tex-IbarraRealNova-BoldItalic-osf-ts1.vf \
tex-IbarraRealNova-BoldItalic-sup-ly1--base.tfm \
tex-IbarraRealNova-BoldItalic-sup-ly1.tfm \
tex-IbarraRealNova-BoldItalic-sup-ly1.vf \
tex-IbarraRealNova-BoldItalic-sup-ot1.tfm \
tex-IbarraRealNova-BoldItalic-sup-t1--base.tfm \
tex-IbarraRealNova-BoldItalic-sup-t1.tfm \
tex-IbarraRealNova-BoldItalic-sup-t1.vf \
tex-IbarraRealNova-Italic-lf-ly1--base.tfm \
tex-IbarraRealNova-Italic-lf-ly1.tfm \
tex-IbarraRealNova-Italic-lf-ly1.vf \
tex-IbarraRealNova-Italic-lf-ot1.tfm \
tex-IbarraRealNova-Italic-lf-sc-ly1--base.tfm \
tex-IbarraRealNova-Italic-lf-sc-ly1.tfm \
tex-IbarraRealNova-Italic-lf-sc-ly1.vf \
tex-IbarraRealNova-Italic-lf-sc-ot1--base.tfm \
tex-IbarraRealNova-Italic-lf-sc-ot1.tfm \
tex-IbarraRealNova-Italic-lf-sc-ot1.vf \
tex-IbarraRealNova-Italic-lf-sc-t1--base.tfm \
tex-IbarraRealNova-Italic-lf-sc-t1.tfm \
tex-IbarraRealNova-Italic-lf-sc-t1.vf \
tex-IbarraRealNova-Italic-lf-t1--base.tfm \
tex-IbarraRealNova-Italic-lf-t1.tfm \
tex-IbarraRealNova-Italic-lf-t1.vf \
tex-IbarraRealNova-Italic-lf-ts1--base.tfm \
tex-IbarraRealNova-Italic-lf-ts1.tfm \
tex-IbarraRealNova-Italic-lf-ts1.vf \
tex-IbarraRealNova-Italic-osf-ly1--base.tfm \
tex-IbarraRealNova-Italic-osf-ly1.tfm \
tex-IbarraRealNova-Italic-osf-ly1.vf \
tex-IbarraRealNova-Italic-osf-ot1.tfm \
tex-IbarraRealNova-Italic-osf-sc-ly1--base.tfm \
tex-IbarraRealNova-Italic-osf-sc-ly1.tfm \
tex-IbarraRealNova-Italic-osf-sc-ly1.vf \
tex-IbarraRealNova-Italic-osf-sc-ot1--base.tfm \
tex-IbarraRealNova-Italic-osf-sc-ot1.tfm \
tex-IbarraRealNova-Italic-osf-sc-ot1.vf \
tex-IbarraRealNova-Italic-osf-sc-t1--base.tfm \
tex-IbarraRealNova-Italic-osf-sc-t1.tfm \
tex-IbarraRealNova-Italic-osf-sc-t1.vf \
tex-IbarraRealNova-Italic-osf-t1--base.tfm \
tex-IbarraRealNova-Italic-osf-t1.tfm \
tex-IbarraRealNova-Italic-osf-t1.vf \
tex-IbarraRealNova-Italic-osf-ts1--base.tfm \
tex-IbarraRealNova-Italic-osf-ts1.tfm \
tex-IbarraRealNova-Italic-osf-ts1.vf \
tex-IbarraRealNova-Italic-sup-ly1--base.tfm \
tex-IbarraRealNova-Italic-sup-ly1.tfm \
tex-IbarraRealNova-Italic-sup-ly1.vf \
tex-IbarraRealNova-Italic-sup-ot1.tfm \
tex-IbarraRealNova-Italic-sup-t1--base.tfm \
tex-IbarraRealNova-Italic-sup-t1.tfm \
tex-IbarraRealNova-Italic-sup-t1.vf \
tex-IbarraRealNova-Regular-lf-ly1--base.tfm \
tex-IbarraRealNova-Regular-lf-ly1.tfm \
tex-IbarraRealNova-Regular-lf-ly1.vf \
tex-IbarraRealNova-Regular-lf-ot1.tfm \
tex-IbarraRealNova-Regular-lf-sc-ly1--base.tfm \
tex-IbarraRealNova-Regular-lf-sc-ly1.tfm \
tex-IbarraRealNova-Regular-lf-sc-ly1.vf \
tex-IbarraRealNova-Regular-lf-sc-ot1--base.tfm \
tex-IbarraRealNova-Regular-lf-sc-ot1.tfm \
tex-IbarraRealNova-Regular-lf-sc-ot1.vf \
tex-IbarraRealNova-Regular-lf-sc-t1--base.tfm \
tex-IbarraRealNova-Regular-lf-sc-t1.tfm \
tex-IbarraRealNova-Regular-lf-sc-t1.vf \
tex-IbarraRealNova-Regular-lf-t1--base.tfm \
tex-IbarraRealNova-Regular-lf-t1.tfm \
tex-IbarraRealNova-Regular-lf-t1.vf \
tex-IbarraRealNova-Regular-lf-ts1--base.tfm \
tex-IbarraRealNova-Regular-lf-ts1.tfm \
tex-IbarraRealNova-Regular-lf-ts1.vf \
tex-IbarraRealNova-Regular-osf-ly1--base.tfm \
tex-IbarraRealNova-Regular-osf-ly1.tfm \
tex-IbarraRealNova-Regular-osf-ly1.vf \
tex-IbarraRealNova-Regular-osf-ot1.tfm \
tex-IbarraRealNova-Regular-osf-sc-ly1--base.tfm \
tex-IbarraRealNova-Regular-osf-sc-ly1.tfm \
tex-IbarraRealNova-Regular-osf-sc-ly1.vf \
tex-IbarraRealNova-Regular-osf-sc-ot1--base.tfm \
tex-IbarraRealNova-Regular-osf-sc-ot1.tfm \
tex-IbarraRealNova-Regular-osf-sc-ot1.vf \
tex-IbarraRealNova-Regular-osf-sc-t1--base.tfm \
tex-IbarraRealNova-Regular-osf-sc-t1.tfm \
tex-IbarraRealNova-Regular-osf-sc-t1.vf \
tex-IbarraRealNova-Regular-osf-t1--base.tfm \
tex-IbarraRealNova-Regular-osf-t1.tfm \
tex-IbarraRealNova-Regular-osf-t1.vf \
tex-IbarraRealNova-Regular-osf-ts1--base.tfm \
tex-IbarraRealNova-Regular-osf-ts1.tfm \
tex-IbarraRealNova-Regular-osf-ts1.vf \
tex-IbarraRealNova-Regular-sup-ly1--base.tfm \
tex-IbarraRealNova-Regular-sup-ly1.tfm \
tex-IbarraRealNova-Regular-sup-ly1.vf \
tex-IbarraRealNova-Regular-sup-ot1.tfm \
tex-IbarraRealNova-Regular-sup-t1--base.tfm \
tex-IbarraRealNova-Regular-sup-t1.tfm \
tex-IbarraRealNova-Regular-sup-t1.vf \
tex-IbarraRealNova-SemiBold-lf-ly1--base.tfm \
tex-IbarraRealNova-SemiBold-lf-ly1.tfm \
tex-IbarraRealNova-SemiBold-lf-ly1.vf \
tex-IbarraRealNova-SemiBold-lf-ot1.tfm \
tex-IbarraRealNova-SemiBold-lf-sc-ly1--base.tfm \
tex-IbarraRealNova-SemiBold-lf-sc-ly1.tfm \
tex-IbarraRealNova-SemiBold-lf-sc-ly1.vf \
tex-IbarraRealNova-SemiBold-lf-sc-ot1--base.tfm \
tex-IbarraRealNova-SemiBold-lf-sc-ot1.tfm \
tex-IbarraRealNova-SemiBold-lf-sc-ot1.vf \
tex-IbarraRealNova-SemiBold-lf-sc-t1--base.tfm \
tex-IbarraRealNova-SemiBold-lf-sc-t1.tfm \
tex-IbarraRealNova-SemiBold-lf-sc-t1.vf \
tex-IbarraRealNova-SemiBold-lf-t1--base.tfm \
tex-IbarraRealNova-SemiBold-lf-t1.tfm \
tex-IbarraRealNova-SemiBold-lf-t1.vf \
tex-IbarraRealNova-SemiBold-lf-ts1--base.tfm \
tex-IbarraRealNova-SemiBold-lf-ts1.tfm \
tex-IbarraRealNova-SemiBold-lf-ts1.vf \
tex-IbarraRealNova-SemiBold-osf-ly1--base.tfm \
tex-IbarraRealNova-SemiBold-osf-ly1.tfm \
tex-IbarraRealNova-SemiBold-osf-ly1.vf \
tex-IbarraRealNova-SemiBold-osf-ot1.tfm \
tex-IbarraRealNova-SemiBold-osf-sc-ly1--base.tfm \
tex-IbarraRealNova-SemiBold-osf-sc-ly1.tfm \
tex-IbarraRealNova-SemiBold-osf-sc-ly1.vf \
tex-IbarraRealNova-SemiBold-osf-sc-ot1--base.tfm \
tex-IbarraRealNova-SemiBold-osf-sc-ot1.tfm \
tex-IbarraRealNova-SemiBold-osf-sc-ot1.vf \
tex-IbarraRealNova-SemiBold-osf-sc-t1--base.tfm \
tex-IbarraRealNova-SemiBold-osf-sc-t1.tfm \
tex-IbarraRealNova-SemiBold-osf-sc-t1.vf \
tex-IbarraRealNova-SemiBold-osf-t1--base.tfm \
tex-IbarraRealNova-SemiBold-osf-t1.tfm \
tex-IbarraRealNova-SemiBold-osf-t1.vf \
tex-IbarraRealNova-SemiBold-osf-ts1--base.tfm \
tex-IbarraRealNova-SemiBold-osf-ts1.tfm \
tex-IbarraRealNova-SemiBold-osf-ts1.vf \
tex-IbarraRealNova-SemiBold-sup-ly1--base.tfm \
tex-IbarraRealNova-SemiBold-sup-ly1.tfm \
tex-IbarraRealNova-SemiBold-sup-ly1.vf \
tex-IbarraRealNova-SemiBold-sup-ot1.tfm \
tex-IbarraRealNova-SemiBold-sup-t1--base.tfm \
tex-IbarraRealNova-SemiBold-sup-t1.tfm \
tex-IbarraRealNova-SemiBold-sup-t1.vf \
tex-IbarraRealNova-SemiBoldItalic-lf-ly1--base.tfm \
tex-IbarraRealNova-SemiBoldItalic-lf-ly1.tfm \
tex-IbarraRealNova-SemiBoldItalic-lf-ly1.vf \
tex-IbarraRealNova-SemiBoldItalic-lf-ot1.tfm \
tex-IbarraRealNova-SemiBoldItalic-lf-sc-ly1--base.tfm \
tex-IbarraRealNova-SemiBoldItalic-lf-sc-ly1.tfm \
tex-IbarraRealNova-SemiBoldItalic-lf-sc-ly1.vf \
tex-IbarraRealNova-SemiBoldItalic-lf-sc-ot1--base.tfm \
tex-IbarraRealNova-SemiBoldItalic-lf-sc-ot1.tfm \
tex-IbarraRealNova-SemiBoldItalic-lf-sc-ot1.vf \
tex-IbarraRealNova-SemiBoldItalic-lf-sc-t1--base.tfm \
tex-IbarraRealNova-SemiBoldItalic-lf-sc-t1.tfm \
tex-IbarraRealNova-SemiBoldItalic-lf-sc-t1.vf \
tex-IbarraRealNova-SemiBoldItalic-lf-t1--base.tfm \
tex-IbarraRealNova-SemiBoldItalic-lf-t1.tfm \
tex-IbarraRealNova-SemiBoldItalic-lf-t1.vf \
tex-IbarraRealNova-SemiBoldItalic-lf-ts1--base.tfm \
tex-IbarraRealNova-SemiBoldItalic-lf-ts1.tfm \
tex-IbarraRealNova-SemiBoldItalic-lf-ts1.vf \
tex-IbarraRealNova-SemiBoldItalic-osf-ly1--base.tfm \
tex-IbarraRealNova-SemiBoldItalic-osf-ly1.tfm \
tex-IbarraRealNova-SemiBoldItalic-osf-ly1.vf \
tex-IbarraRealNova-SemiBoldItalic-osf-ot1.tfm \
tex-IbarraRealNova-SemiBoldItalic-osf-sc-ly1--base.tfm \
tex-IbarraRealNova-SemiBoldItalic-osf-sc-ly1.tfm \
tex-IbarraRealNova-SemiBoldItalic-osf-sc-ly1.vf \
tex-IbarraRealNova-SemiBoldItalic-osf-sc-ot1--base.tfm \
tex-IbarraRealNova-SemiBoldItalic-osf-sc-ot1.tfm \
tex-IbarraRealNova-SemiBoldItalic-osf-sc-ot1.vf \
tex-IbarraRealNova-SemiBoldItalic-osf-sc-t1--base.tfm \
tex-IbarraRealNova-SemiBoldItalic-osf-sc-t1.tfm \
tex-IbarraRealNova-SemiBoldItalic-osf-sc-t1.vf \
tex-IbarraRealNova-SemiBoldItalic-osf-t1--base.tfm \
tex-IbarraRealNova-SemiBoldItalic-osf-t1.tfm \
tex-IbarraRealNova-SemiBoldItalic-osf-t1.vf \
tex-IbarraRealNova-SemiBoldItalic-osf-ts1--base.tfm \
tex-IbarraRealNova-SemiBoldItalic-osf-ts1.tfm \
tex-IbarraRealNova-SemiBoldItalic-osf-ts1.vf \
tex-IbarraRealNova-SemiBoldItalic-sup-ly1--base.tfm \
tex-IbarraRealNova-SemiBoldItalic-sup-ly1.tfm \
tex-IbarraRealNova-SemiBoldItalic-sup-ly1.vf \
tex-IbarraRealNova-SemiBoldItalic-sup-ot1.tfm \
tex-IbarraRealNova-SemiBoldItalic-sup-t1--base.tfm \
tex-IbarraRealNova-SemiBoldItalic-sup-t1.tfm \
tex-IbarraRealNova-SemiBoldItalic-sup-t1.vf \
tex-LY1IbarraRealNova-LF.fd \
tex-LY1IbarraRealNova-OsF.fd \
tex-LY1IbarraRealNova-Sup.fd \
tex-OT1IbarraRealNova-LF.fd \
tex-OT1IbarraRealNova-OsF.fd \
tex-OT1IbarraRealNova-Sup.fd \
tex-T1IbarraRealNova-LF.fd \
tex-T1IbarraRealNova-OsF.fd \
tex-T1IbarraRealNova-Sup.fd \
tex-TS1IbarraRealNova-LF.fd \
tex-TS1IbarraRealNova-OsF.fd \
tex-ibarra.map \
tex-ibarra.sty \
tex-ibrr-2qacnp.enc \
tex-ibrr-6jlwjs.enc \
tex-ibrr-a3lg2q.enc \
tex-ibrr-bqfkme.enc \
tex-ibrr-eocuub.enc \
tex-ibrr-gj2f64.enc \
tex-ibrr-ifilzm.enc \
tex-ibrr-j5nrvp.enc \
tex-ibrr-miztrm.enc \
tex-ibrr-qbzklr.enc \
tex-ibrr-rszbuw.enc \
tex-ibrr-s4svbt.enc \
tex-ibrr-xjlkg7.enc \
tex-ibrr-xx2mp7.enc \
tex-ibrr-yt2suz.enc \
tex-ibrr-yyhfj4.enc \
texlive-ibarra"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontaxes.sty \
tex-fontenc.sty \
tex-fontspec.sty \
tex-ifluatex.sty \
tex-ifxetex.sty \
tex-mweights.sty \
tex-textcomp.sty \
tex-updmap.cfg \
tex-xkeyval.sty \
texlive \
texlive-filesystem \
texlive-ibarra-fonts \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
