SUMMARY = "LaTeX support for the Ibarra Real Nova family of fonts"
DESCRIPTION = "The Ibarra Real Nova is a revival of a typeface designed by \
Geronimo Gil for the publication of Don Quixote for the Real \
Academia de la Lengua in 1780. Joaquin Ibarra was the printer."
LICENSE = "OFL-1.1"

PV = "2023.201.svn64567"

RPM_NAME = "texlive-ibarra-2023.201.svn64567-52.1.noarch.rpm"
RPM_HASH = "235f5915f9bab414c8edcf157c422e992670fc8ff81191942475c2459c191521514f6d6f90678397998269a80965c87163938f12778dec92e98f13a631b0dac9"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex(IbarraRealNova-Bold-lf-ly1--base.tfm) \
tex(IbarraRealNova-Bold-lf-ly1.tfm) \
tex(IbarraRealNova-Bold-lf-ly1.vf) \
tex(IbarraRealNova-Bold-lf-ot1.tfm) \
tex(IbarraRealNova-Bold-lf-sc-ly1--base.tfm) \
tex(IbarraRealNova-Bold-lf-sc-ly1.tfm) \
tex(IbarraRealNova-Bold-lf-sc-ly1.vf) \
tex(IbarraRealNova-Bold-lf-sc-ot1--base.tfm) \
tex(IbarraRealNova-Bold-lf-sc-ot1.tfm) \
tex(IbarraRealNova-Bold-lf-sc-ot1.vf) \
tex(IbarraRealNova-Bold-lf-sc-t1--base.tfm) \
tex(IbarraRealNova-Bold-lf-sc-t1.tfm) \
tex(IbarraRealNova-Bold-lf-sc-t1.vf) \
tex(IbarraRealNova-Bold-lf-t1--base.tfm) \
tex(IbarraRealNova-Bold-lf-t1.tfm) \
tex(IbarraRealNova-Bold-lf-t1.vf) \
tex(IbarraRealNova-Bold-lf-ts1--base.tfm) \
tex(IbarraRealNova-Bold-lf-ts1.tfm) \
tex(IbarraRealNova-Bold-lf-ts1.vf) \
tex(IbarraRealNova-Bold-osf-ly1--base.tfm) \
tex(IbarraRealNova-Bold-osf-ly1.tfm) \
tex(IbarraRealNova-Bold-osf-ly1.vf) \
tex(IbarraRealNova-Bold-osf-ot1.tfm) \
tex(IbarraRealNova-Bold-osf-sc-ly1--base.tfm) \
tex(IbarraRealNova-Bold-osf-sc-ly1.tfm) \
tex(IbarraRealNova-Bold-osf-sc-ly1.vf) \
tex(IbarraRealNova-Bold-osf-sc-ot1--base.tfm) \
tex(IbarraRealNova-Bold-osf-sc-ot1.tfm) \
tex(IbarraRealNova-Bold-osf-sc-ot1.vf) \
tex(IbarraRealNova-Bold-osf-sc-t1--base.tfm) \
tex(IbarraRealNova-Bold-osf-sc-t1.tfm) \
tex(IbarraRealNova-Bold-osf-sc-t1.vf) \
tex(IbarraRealNova-Bold-osf-t1--base.tfm) \
tex(IbarraRealNova-Bold-osf-t1.tfm) \
tex(IbarraRealNova-Bold-osf-t1.vf) \
tex(IbarraRealNova-Bold-osf-ts1--base.tfm) \
tex(IbarraRealNova-Bold-osf-ts1.tfm) \
tex(IbarraRealNova-Bold-osf-ts1.vf) \
tex(IbarraRealNova-Bold-sup-ly1--base.tfm) \
tex(IbarraRealNova-Bold-sup-ly1.tfm) \
tex(IbarraRealNova-Bold-sup-ly1.vf) \
tex(IbarraRealNova-Bold-sup-ot1.tfm) \
tex(IbarraRealNova-Bold-sup-t1--base.tfm) \
tex(IbarraRealNova-Bold-sup-t1.tfm) \
tex(IbarraRealNova-Bold-sup-t1.vf) \
tex(IbarraRealNova-BoldItalic-lf-ly1--base.tfm) \
tex(IbarraRealNova-BoldItalic-lf-ly1.tfm) \
tex(IbarraRealNova-BoldItalic-lf-ly1.vf) \
tex(IbarraRealNova-BoldItalic-lf-ot1.tfm) \
tex(IbarraRealNova-BoldItalic-lf-sc-ly1--base.tfm) \
tex(IbarraRealNova-BoldItalic-lf-sc-ly1.tfm) \
tex(IbarraRealNova-BoldItalic-lf-sc-ly1.vf) \
tex(IbarraRealNova-BoldItalic-lf-sc-ot1--base.tfm) \
tex(IbarraRealNova-BoldItalic-lf-sc-ot1.tfm) \
tex(IbarraRealNova-BoldItalic-lf-sc-ot1.vf) \
tex(IbarraRealNova-BoldItalic-lf-sc-t1--base.tfm) \
tex(IbarraRealNova-BoldItalic-lf-sc-t1.tfm) \
tex(IbarraRealNova-BoldItalic-lf-sc-t1.vf) \
tex(IbarraRealNova-BoldItalic-lf-t1--base.tfm) \
tex(IbarraRealNova-BoldItalic-lf-t1.tfm) \
tex(IbarraRealNova-BoldItalic-lf-t1.vf) \
tex(IbarraRealNova-BoldItalic-lf-ts1--base.tfm) \
tex(IbarraRealNova-BoldItalic-lf-ts1.tfm) \
tex(IbarraRealNova-BoldItalic-lf-ts1.vf) \
tex(IbarraRealNova-BoldItalic-osf-ly1--base.tfm) \
tex(IbarraRealNova-BoldItalic-osf-ly1.tfm) \
tex(IbarraRealNova-BoldItalic-osf-ly1.vf) \
tex(IbarraRealNova-BoldItalic-osf-ot1.tfm) \
tex(IbarraRealNova-BoldItalic-osf-sc-ly1--base.tfm) \
tex(IbarraRealNova-BoldItalic-osf-sc-ly1.tfm) \
tex(IbarraRealNova-BoldItalic-osf-sc-ly1.vf) \
tex(IbarraRealNova-BoldItalic-osf-sc-ot1--base.tfm) \
tex(IbarraRealNova-BoldItalic-osf-sc-ot1.tfm) \
tex(IbarraRealNova-BoldItalic-osf-sc-ot1.vf) \
tex(IbarraRealNova-BoldItalic-osf-sc-t1--base.tfm) \
tex(IbarraRealNova-BoldItalic-osf-sc-t1.tfm) \
tex(IbarraRealNova-BoldItalic-osf-sc-t1.vf) \
tex(IbarraRealNova-BoldItalic-osf-t1--base.tfm) \
tex(IbarraRealNova-BoldItalic-osf-t1.tfm) \
tex(IbarraRealNova-BoldItalic-osf-t1.vf) \
tex(IbarraRealNova-BoldItalic-osf-ts1--base.tfm) \
tex(IbarraRealNova-BoldItalic-osf-ts1.tfm) \
tex(IbarraRealNova-BoldItalic-osf-ts1.vf) \
tex(IbarraRealNova-BoldItalic-sup-ly1--base.tfm) \
tex(IbarraRealNova-BoldItalic-sup-ly1.tfm) \
tex(IbarraRealNova-BoldItalic-sup-ly1.vf) \
tex(IbarraRealNova-BoldItalic-sup-ot1.tfm) \
tex(IbarraRealNova-BoldItalic-sup-t1--base.tfm) \
tex(IbarraRealNova-BoldItalic-sup-t1.tfm) \
tex(IbarraRealNova-BoldItalic-sup-t1.vf) \
tex(IbarraRealNova-Italic-lf-ly1--base.tfm) \
tex(IbarraRealNova-Italic-lf-ly1.tfm) \
tex(IbarraRealNova-Italic-lf-ly1.vf) \
tex(IbarraRealNova-Italic-lf-ot1.tfm) \
tex(IbarraRealNova-Italic-lf-sc-ly1--base.tfm) \
tex(IbarraRealNova-Italic-lf-sc-ly1.tfm) \
tex(IbarraRealNova-Italic-lf-sc-ly1.vf) \
tex(IbarraRealNova-Italic-lf-sc-ot1--base.tfm) \
tex(IbarraRealNova-Italic-lf-sc-ot1.tfm) \
tex(IbarraRealNova-Italic-lf-sc-ot1.vf) \
tex(IbarraRealNova-Italic-lf-sc-t1--base.tfm) \
tex(IbarraRealNova-Italic-lf-sc-t1.tfm) \
tex(IbarraRealNova-Italic-lf-sc-t1.vf) \
tex(IbarraRealNova-Italic-lf-t1--base.tfm) \
tex(IbarraRealNova-Italic-lf-t1.tfm) \
tex(IbarraRealNova-Italic-lf-t1.vf) \
tex(IbarraRealNova-Italic-lf-ts1--base.tfm) \
tex(IbarraRealNova-Italic-lf-ts1.tfm) \
tex(IbarraRealNova-Italic-lf-ts1.vf) \
tex(IbarraRealNova-Italic-osf-ly1--base.tfm) \
tex(IbarraRealNova-Italic-osf-ly1.tfm) \
tex(IbarraRealNova-Italic-osf-ly1.vf) \
tex(IbarraRealNova-Italic-osf-ot1.tfm) \
tex(IbarraRealNova-Italic-osf-sc-ly1--base.tfm) \
tex(IbarraRealNova-Italic-osf-sc-ly1.tfm) \
tex(IbarraRealNova-Italic-osf-sc-ly1.vf) \
tex(IbarraRealNova-Italic-osf-sc-ot1--base.tfm) \
tex(IbarraRealNova-Italic-osf-sc-ot1.tfm) \
tex(IbarraRealNova-Italic-osf-sc-ot1.vf) \
tex(IbarraRealNova-Italic-osf-sc-t1--base.tfm) \
tex(IbarraRealNova-Italic-osf-sc-t1.tfm) \
tex(IbarraRealNova-Italic-osf-sc-t1.vf) \
tex(IbarraRealNova-Italic-osf-t1--base.tfm) \
tex(IbarraRealNova-Italic-osf-t1.tfm) \
tex(IbarraRealNova-Italic-osf-t1.vf) \
tex(IbarraRealNova-Italic-osf-ts1--base.tfm) \
tex(IbarraRealNova-Italic-osf-ts1.tfm) \
tex(IbarraRealNova-Italic-osf-ts1.vf) \
tex(IbarraRealNova-Italic-sup-ly1--base.tfm) \
tex(IbarraRealNova-Italic-sup-ly1.tfm) \
tex(IbarraRealNova-Italic-sup-ly1.vf) \
tex(IbarraRealNova-Italic-sup-ot1.tfm) \
tex(IbarraRealNova-Italic-sup-t1--base.tfm) \
tex(IbarraRealNova-Italic-sup-t1.tfm) \
tex(IbarraRealNova-Italic-sup-t1.vf) \
tex(IbarraRealNova-Regular-lf-ly1--base.tfm) \
tex(IbarraRealNova-Regular-lf-ly1.tfm) \
tex(IbarraRealNova-Regular-lf-ly1.vf) \
tex(IbarraRealNova-Regular-lf-ot1.tfm) \
tex(IbarraRealNova-Regular-lf-sc-ly1--base.tfm) \
tex(IbarraRealNova-Regular-lf-sc-ly1.tfm) \
tex(IbarraRealNova-Regular-lf-sc-ly1.vf) \
tex(IbarraRealNova-Regular-lf-sc-ot1--base.tfm) \
tex(IbarraRealNova-Regular-lf-sc-ot1.tfm) \
tex(IbarraRealNova-Regular-lf-sc-ot1.vf) \
tex(IbarraRealNova-Regular-lf-sc-t1--base.tfm) \
tex(IbarraRealNova-Regular-lf-sc-t1.tfm) \
tex(IbarraRealNova-Regular-lf-sc-t1.vf) \
tex(IbarraRealNova-Regular-lf-t1--base.tfm) \
tex(IbarraRealNova-Regular-lf-t1.tfm) \
tex(IbarraRealNova-Regular-lf-t1.vf) \
tex(IbarraRealNova-Regular-lf-ts1--base.tfm) \
tex(IbarraRealNova-Regular-lf-ts1.tfm) \
tex(IbarraRealNova-Regular-lf-ts1.vf) \
tex(IbarraRealNova-Regular-osf-ly1--base.tfm) \
tex(IbarraRealNova-Regular-osf-ly1.tfm) \
tex(IbarraRealNova-Regular-osf-ly1.vf) \
tex(IbarraRealNova-Regular-osf-ot1.tfm) \
tex(IbarraRealNova-Regular-osf-sc-ly1--base.tfm) \
tex(IbarraRealNova-Regular-osf-sc-ly1.tfm) \
tex(IbarraRealNova-Regular-osf-sc-ly1.vf) \
tex(IbarraRealNova-Regular-osf-sc-ot1--base.tfm) \
tex(IbarraRealNova-Regular-osf-sc-ot1.tfm) \
tex(IbarraRealNova-Regular-osf-sc-ot1.vf) \
tex(IbarraRealNova-Regular-osf-sc-t1--base.tfm) \
tex(IbarraRealNova-Regular-osf-sc-t1.tfm) \
tex(IbarraRealNova-Regular-osf-sc-t1.vf) \
tex(IbarraRealNova-Regular-osf-t1--base.tfm) \
tex(IbarraRealNova-Regular-osf-t1.tfm) \
tex(IbarraRealNova-Regular-osf-t1.vf) \
tex(IbarraRealNova-Regular-osf-ts1--base.tfm) \
tex(IbarraRealNova-Regular-osf-ts1.tfm) \
tex(IbarraRealNova-Regular-osf-ts1.vf) \
tex(IbarraRealNova-Regular-sup-ly1--base.tfm) \
tex(IbarraRealNova-Regular-sup-ly1.tfm) \
tex(IbarraRealNova-Regular-sup-ly1.vf) \
tex(IbarraRealNova-Regular-sup-ot1.tfm) \
tex(IbarraRealNova-Regular-sup-t1--base.tfm) \
tex(IbarraRealNova-Regular-sup-t1.tfm) \
tex(IbarraRealNova-Regular-sup-t1.vf) \
tex(IbarraRealNova-SemiBold-lf-ly1--base.tfm) \
tex(IbarraRealNova-SemiBold-lf-ly1.tfm) \
tex(IbarraRealNova-SemiBold-lf-ly1.vf) \
tex(IbarraRealNova-SemiBold-lf-ot1.tfm) \
tex(IbarraRealNova-SemiBold-lf-sc-ly1--base.tfm) \
tex(IbarraRealNova-SemiBold-lf-sc-ly1.tfm) \
tex(IbarraRealNova-SemiBold-lf-sc-ly1.vf) \
tex(IbarraRealNova-SemiBold-lf-sc-ot1--base.tfm) \
tex(IbarraRealNova-SemiBold-lf-sc-ot1.tfm) \
tex(IbarraRealNova-SemiBold-lf-sc-ot1.vf) \
tex(IbarraRealNova-SemiBold-lf-sc-t1--base.tfm) \
tex(IbarraRealNova-SemiBold-lf-sc-t1.tfm) \
tex(IbarraRealNova-SemiBold-lf-sc-t1.vf) \
tex(IbarraRealNova-SemiBold-lf-t1--base.tfm) \
tex(IbarraRealNova-SemiBold-lf-t1.tfm) \
tex(IbarraRealNova-SemiBold-lf-t1.vf) \
tex(IbarraRealNova-SemiBold-lf-ts1--base.tfm) \
tex(IbarraRealNova-SemiBold-lf-ts1.tfm) \
tex(IbarraRealNova-SemiBold-lf-ts1.vf) \
tex(IbarraRealNova-SemiBold-osf-ly1--base.tfm) \
tex(IbarraRealNova-SemiBold-osf-ly1.tfm) \
tex(IbarraRealNova-SemiBold-osf-ly1.vf) \
tex(IbarraRealNova-SemiBold-osf-ot1.tfm) \
tex(IbarraRealNova-SemiBold-osf-sc-ly1--base.tfm) \
tex(IbarraRealNova-SemiBold-osf-sc-ly1.tfm) \
tex(IbarraRealNova-SemiBold-osf-sc-ly1.vf) \
tex(IbarraRealNova-SemiBold-osf-sc-ot1--base.tfm) \
tex(IbarraRealNova-SemiBold-osf-sc-ot1.tfm) \
tex(IbarraRealNova-SemiBold-osf-sc-ot1.vf) \
tex(IbarraRealNova-SemiBold-osf-sc-t1--base.tfm) \
tex(IbarraRealNova-SemiBold-osf-sc-t1.tfm) \
tex(IbarraRealNova-SemiBold-osf-sc-t1.vf) \
tex(IbarraRealNova-SemiBold-osf-t1--base.tfm) \
tex(IbarraRealNova-SemiBold-osf-t1.tfm) \
tex(IbarraRealNova-SemiBold-osf-t1.vf) \
tex(IbarraRealNova-SemiBold-osf-ts1--base.tfm) \
tex(IbarraRealNova-SemiBold-osf-ts1.tfm) \
tex(IbarraRealNova-SemiBold-osf-ts1.vf) \
tex(IbarraRealNova-SemiBold-sup-ly1--base.tfm) \
tex(IbarraRealNova-SemiBold-sup-ly1.tfm) \
tex(IbarraRealNova-SemiBold-sup-ly1.vf) \
tex(IbarraRealNova-SemiBold-sup-ot1.tfm) \
tex(IbarraRealNova-SemiBold-sup-t1--base.tfm) \
tex(IbarraRealNova-SemiBold-sup-t1.tfm) \
tex(IbarraRealNova-SemiBold-sup-t1.vf) \
tex(IbarraRealNova-SemiBoldItalic-lf-ly1--base.tfm) \
tex(IbarraRealNova-SemiBoldItalic-lf-ly1.tfm) \
tex(IbarraRealNova-SemiBoldItalic-lf-ly1.vf) \
tex(IbarraRealNova-SemiBoldItalic-lf-ot1.tfm) \
tex(IbarraRealNova-SemiBoldItalic-lf-sc-ly1--base.tfm) \
tex(IbarraRealNova-SemiBoldItalic-lf-sc-ly1.tfm) \
tex(IbarraRealNova-SemiBoldItalic-lf-sc-ly1.vf) \
tex(IbarraRealNova-SemiBoldItalic-lf-sc-ot1--base.tfm) \
tex(IbarraRealNova-SemiBoldItalic-lf-sc-ot1.tfm) \
tex(IbarraRealNova-SemiBoldItalic-lf-sc-ot1.vf) \
tex(IbarraRealNova-SemiBoldItalic-lf-sc-t1--base.tfm) \
tex(IbarraRealNova-SemiBoldItalic-lf-sc-t1.tfm) \
tex(IbarraRealNova-SemiBoldItalic-lf-sc-t1.vf) \
tex(IbarraRealNova-SemiBoldItalic-lf-t1--base.tfm) \
tex(IbarraRealNova-SemiBoldItalic-lf-t1.tfm) \
tex(IbarraRealNova-SemiBoldItalic-lf-t1.vf) \
tex(IbarraRealNova-SemiBoldItalic-lf-ts1--base.tfm) \
tex(IbarraRealNova-SemiBoldItalic-lf-ts1.tfm) \
tex(IbarraRealNova-SemiBoldItalic-lf-ts1.vf) \
tex(IbarraRealNova-SemiBoldItalic-osf-ly1--base.tfm) \
tex(IbarraRealNova-SemiBoldItalic-osf-ly1.tfm) \
tex(IbarraRealNova-SemiBoldItalic-osf-ly1.vf) \
tex(IbarraRealNova-SemiBoldItalic-osf-ot1.tfm) \
tex(IbarraRealNova-SemiBoldItalic-osf-sc-ly1--base.tfm) \
tex(IbarraRealNova-SemiBoldItalic-osf-sc-ly1.tfm) \
tex(IbarraRealNova-SemiBoldItalic-osf-sc-ly1.vf) \
tex(IbarraRealNova-SemiBoldItalic-osf-sc-ot1--base.tfm) \
tex(IbarraRealNova-SemiBoldItalic-osf-sc-ot1.tfm) \
tex(IbarraRealNova-SemiBoldItalic-osf-sc-ot1.vf) \
tex(IbarraRealNova-SemiBoldItalic-osf-sc-t1--base.tfm) \
tex(IbarraRealNova-SemiBoldItalic-osf-sc-t1.tfm) \
tex(IbarraRealNova-SemiBoldItalic-osf-sc-t1.vf) \
tex(IbarraRealNova-SemiBoldItalic-osf-t1--base.tfm) \
tex(IbarraRealNova-SemiBoldItalic-osf-t1.tfm) \
tex(IbarraRealNova-SemiBoldItalic-osf-t1.vf) \
tex(IbarraRealNova-SemiBoldItalic-osf-ts1--base.tfm) \
tex(IbarraRealNova-SemiBoldItalic-osf-ts1.tfm) \
tex(IbarraRealNova-SemiBoldItalic-osf-ts1.vf) \
tex(IbarraRealNova-SemiBoldItalic-sup-ly1--base.tfm) \
tex(IbarraRealNova-SemiBoldItalic-sup-ly1.tfm) \
tex(IbarraRealNova-SemiBoldItalic-sup-ly1.vf) \
tex(IbarraRealNova-SemiBoldItalic-sup-ot1.tfm) \
tex(IbarraRealNova-SemiBoldItalic-sup-t1--base.tfm) \
tex(IbarraRealNova-SemiBoldItalic-sup-t1.tfm) \
tex(IbarraRealNova-SemiBoldItalic-sup-t1.vf) \
tex(LY1IbarraRealNova-LF.fd) \
tex(LY1IbarraRealNova-OsF.fd) \
tex(LY1IbarraRealNova-Sup.fd) \
tex(OT1IbarraRealNova-LF.fd) \
tex(OT1IbarraRealNova-OsF.fd) \
tex(OT1IbarraRealNova-Sup.fd) \
tex(T1IbarraRealNova-LF.fd) \
tex(T1IbarraRealNova-OsF.fd) \
tex(T1IbarraRealNova-Sup.fd) \
tex(TS1IbarraRealNova-LF.fd) \
tex(TS1IbarraRealNova-OsF.fd) \
tex(ibarra.map) \
tex(ibarra.sty) \
tex(ibrr_2qacnp.enc) \
tex(ibrr_6jlwjs.enc) \
tex(ibrr_a3lg2q.enc) \
tex(ibrr_bqfkme.enc) \
tex(ibrr_eocuub.enc) \
tex(ibrr_gj2f64.enc) \
tex(ibrr_ifilzm.enc) \
tex(ibrr_j5nrvp.enc) \
tex(ibrr_miztrm.enc) \
tex(ibrr_qbzklr.enc) \
tex(ibrr_rszbuw.enc) \
tex(ibrr_s4svbt.enc) \
tex(ibrr_xjlkg7.enc) \
tex(ibrr_xx2mp7.enc) \
tex(ibrr_yt2suz.enc) \
tex(ibrr_yyhfj4.enc) \
texlive-ibarra"

RDEPENDS:${PN} += "/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex(fontaxes.sty) \
tex(fontenc.sty) \
tex(fontspec.sty) \
tex(ifluatex.sty) \
tex(ifxetex.sty) \
tex(mweights.sty) \
tex(textcomp.sty) \
tex(updmap.cfg) \
tex(xkeyval.sty) \
texlive \
texlive-filesystem \
texlive-ibarra-fonts \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
