SUMMARY = "Plot-manipulation macros for use in MetaPost"
DESCRIPTION = "MetaPlot is a set of MetaPost macros for manipulating \
pre-generated plots (and similar objects), and formatting them \
for inclusion in a MetaPost figure. The intent is that the \
plots can be generated by some outside program, in an abstract \
manner that does not require making decisions about on-page \
sizing and layout, and then they can be imported into MetaPlot \
and arranged using the full capabilities of MetaPost. Metaplot \
also includes a very flexible set of macros for generating plot \
axes, which may be useful in other contexts as well. Presently, \
MetaPlot is in something of a pre-release beta state; it is \
quite functional, but the syntax of the commands is still \
potentially in flux."
LICENSE = "LPPL-1.0"

PV = "2023.209.0.0.91svn15878"

RPM_NAME = "texlive-metaplot-2023.209.0.0.91svn15878-55.1.noarch.rpm"
RPM_HASH = "19d716c58347f3f82434caf1b30ebca4baf743dfab387a78ce226176ee999b68a79160e1668d13545afd0286bed015d929b03d4228f853a31189183973ead0b4"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "texlive-metaplot"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
