SUMMARY = "Automatic generation of record lenses for microlens"
DESCRIPTION = "This package lets you automatically generate lenses for data types; code was \
extracted from the lens package, and therefore generated lenses are fully \
compatible with ones generated by lens (and can be used both from lens and \
microlens). \
 \
This package is a part of the <http://hackage.haskell.org/package/microlens \
microlens> family; see the readme \
<https://github.com/stevenfontanella/microlens#readme on Github>."
LICENSE = "BSD-3-Clause"

PV = "0.4.3.12"

RPM_NAME = "ghc-microlens-th-0.4.3.12-1.2.aarch64.rpm"
RPM_HASH = "9448be74c66fd4574c31e733422e8c531396c495356d5d44282e8a8c0e0e479856c8dadba32753308ebd7a6be2d8f6471af0c761ab02ae1c83877b9eba206c55"

RPROVIDES:${PN} += "ghc-microlens-th \
libHSmicrolens-th-0.4.3.12-A1OnPrF7gbKLp2skY17lAG-ghc9.4.5.so"

RDEPENDS:${PN} += "libHSarray-0.5.4.0-ghc9.4.5.so \
libHSbase-4.17.1.0-ghc9.4.5.so \
libHScontainers-0.6.7-ghc9.4.5.so \
libHSdeepseq-1.4.8.0-ghc9.4.5.so \
libHSghc-bignum-1.3-ghc9.4.5.so \
libHSghc-boot-th-9.4.5-ghc9.4.5.so \
libHSghc-prim-0.9.0-ghc9.4.5.so \
libHSmicrolens-0.4.13.1-ARwI8t2x86cAxRs56XPcG1-ghc9.4.5.so \
libHSpretty-1.1.3.6-ghc9.4.5.so \
libHStemplate-haskell-2.19.0.0-ghc9.4.5.so \
libHSth-abstraction-0.4.5.0-8bY5lBPMorfFW3yG6gFNZT-ghc9.4.5.so \
libHStransformers-0.5.6.2-ghc9.4.5.so \
libc.so.6 \
libgmp.so.10 \
libm.so.6"

inherit rpm
