SUMMARY = "Antykwa Torunska: a Type 1 family of a Polish traditional type"
DESCRIPTION = "Antykwa Torunska is a serif font designed by the late Polish \
typographer Zygfryd Gardzielewski, reconstructed and digitized \
as Type 1."
LICENSE = "LPPL-1.3c"

PV = "2023.201.2.08svn18651"

RPM_NAME = "texlive-antt-2023.201.2.08svn18651-54.1.noarch.rpm"
RPM_HASH = "a5623370d729af680a8c8ec203f0bfe63f2aabaf8c60aa24d6f71c75e348eeb0bc6ca4cb5972e55d9c109170a6f52fb19be5e3224dfdddff390f7bc537bcc11d"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-antt-cs.enc \
tex-antt-cs.map \
tex-antt-ec.enc \
tex-antt-ec.map \
tex-antt-el.enc \
tex-antt-el.map \
tex-antt-ex.enc \
tex-antt-ex.map \
tex-antt-exp.enc \
tex-antt-exp.map \
tex-antt-greek.enc \
tex-antt-greek.map \
tex-antt-math.tex \
tex-antt-mi.enc \
tex-antt-mi.map \
tex-antt-qx.enc \
tex-antt-qx.map \
tex-antt-rm.enc \
tex-antt-rm.map \
tex-antt-sy.enc \
tex-antt-sy.map \
tex-antt-t2a.enc \
tex-antt-t2a.map \
tex-antt-t2b.enc \
tex-antt-t2b.map \
tex-antt-t2c.enc \
tex-antt-t2c.map \
tex-antt-t5.enc \
tex-antt-t5.map \
tex-antt-texnansi.enc \
tex-antt-texnansi.map \
tex-antt-ts1.enc \
tex-antt-ts1.map \
tex-antt-wncy.enc \
tex-antt-wncy.map \
tex-antt.map \
tex-anttcap-cs.enc \
tex-anttcap-ec.enc \
tex-anttcap-qx.enc \
tex-anttcap-t5.enc \
tex-anttcap-texnansi.enc \
tex-anttor.sty \
tex-antyktor.sty \
tex-cs-anttb.tfm \
tex-cs-anttbcap.tfm \
tex-cs-anttbi.tfm \
tex-cs-anttbicap.tfm \
tex-cs-anttcb.tfm \
tex-cs-anttcbcap.tfm \
tex-cs-anttcbi.tfm \
tex-cs-anttcbicap.tfm \
tex-cs-anttcl.tfm \
tex-cs-anttclcap.tfm \
tex-cs-anttcli.tfm \
tex-cs-anttclicap.tfm \
tex-cs-anttcm.tfm \
tex-cs-anttcmcap.tfm \
tex-cs-anttcmi.tfm \
tex-cs-anttcmicap.tfm \
tex-cs-anttcr.tfm \
tex-cs-anttcrcap.tfm \
tex-cs-anttcri.tfm \
tex-cs-anttcricap.tfm \
tex-cs-anttl.tfm \
tex-cs-anttlcap.tfm \
tex-cs-anttli.tfm \
tex-cs-anttlicap.tfm \
tex-cs-anttm.tfm \
tex-cs-anttmcap.tfm \
tex-cs-anttmi.tfm \
tex-cs-anttmicap.tfm \
tex-cs-anttr.tfm \
tex-cs-anttrcap.tfm \
tex-cs-anttri.tfm \
tex-cs-anttricap.tfm \
tex-ec-anttb.tfm \
tex-ec-anttbcap.tfm \
tex-ec-anttbi.tfm \
tex-ec-anttbicap.tfm \
tex-ec-anttcb.tfm \
tex-ec-anttcbcap.tfm \
tex-ec-anttcbi.tfm \
tex-ec-anttcbicap.tfm \
tex-ec-anttcl.tfm \
tex-ec-anttclcap.tfm \
tex-ec-anttcli.tfm \
tex-ec-anttclicap.tfm \
tex-ec-anttcm.tfm \
tex-ec-anttcmcap.tfm \
tex-ec-anttcmi.tfm \
tex-ec-anttcmicap.tfm \
tex-ec-anttcr.tfm \
tex-ec-anttcrcap.tfm \
tex-ec-anttcri.tfm \
tex-ec-anttcricap.tfm \
tex-ec-anttl.tfm \
tex-ec-anttlcap.tfm \
tex-ec-anttli.tfm \
tex-ec-anttlicap.tfm \
tex-ec-anttm.tfm \
tex-ec-anttmcap.tfm \
tex-ec-anttmi.tfm \
tex-ec-anttmicap.tfm \
tex-ec-anttr.tfm \
tex-ec-anttrcap.tfm \
tex-ec-anttri.tfm \
tex-ec-anttricap.tfm \
tex-el-anttb.tfm \
tex-el-anttbi.tfm \
tex-el-anttcb.tfm \
tex-el-anttcbi.tfm \
tex-el-anttcl.tfm \
tex-el-anttcli.tfm \
tex-el-anttcm.tfm \
tex-el-anttcmi.tfm \
tex-el-anttcr.tfm \
tex-el-anttcri.tfm \
tex-el-anttl.tfm \
tex-el-anttli.tfm \
tex-el-anttm.tfm \
tex-el-anttmi.tfm \
tex-el-anttr.tfm \
tex-el-anttri.tfm \
tex-ex-anttb.tfm \
tex-ex-anttcb.tfm \
tex-ex-anttcl.tfm \
tex-ex-anttcm.tfm \
tex-ex-anttcr.tfm \
tex-ex-anttl.tfm \
tex-ex-anttm.tfm \
tex-ex-anttr.tfm \
tex-exp-anttb.tfm \
tex-exp-anttbi.tfm \
tex-exp-anttcb.tfm \
tex-exp-anttcbi.tfm \
tex-exp-anttcl.tfm \
tex-exp-anttcli.tfm \
tex-exp-anttcm.tfm \
tex-exp-anttcmi.tfm \
tex-exp-anttcr.tfm \
tex-exp-anttcri.tfm \
tex-exp-anttl.tfm \
tex-exp-anttli.tfm \
tex-exp-anttm.tfm \
tex-exp-anttmi.tfm \
tex-exp-anttr.tfm \
tex-exp-anttri.tfm \
tex-greek-anttb.tfm \
tex-greek-anttbi.tfm \
tex-greek-anttcb.tfm \
tex-greek-anttcbi.tfm \
tex-greek-anttcl.tfm \
tex-greek-anttcli.tfm \
tex-greek-anttcm.tfm \
tex-greek-anttcmi.tfm \
tex-greek-anttcr.tfm \
tex-greek-anttcri.tfm \
tex-greek-anttl.tfm \
tex-greek-anttli.tfm \
tex-greek-anttm.tfm \
tex-greek-anttmi.tfm \
tex-greek-anttr.tfm \
tex-greek-anttri.tfm \
tex-il2antt.fd \
tex-il2anttc.fd \
tex-il2anttl.fd \
tex-il2anttlc.fd \
tex-ly1antt.fd \
tex-ly1anttc.fd \
tex-ly1anttl.fd \
tex-ly1anttlc.fd \
tex-mi-anttbi.tfm \
tex-mi-anttcbi.tfm \
tex-mi-anttcli.tfm \
tex-mi-anttcmi.tfm \
tex-mi-anttcri.tfm \
tex-mi-anttli.tfm \
tex-mi-anttmi.tfm \
tex-mi-anttri.tfm \
tex-omlantt.fd \
tex-omlanttc.fd \
tex-omlanttl.fd \
tex-omlanttlc.fd \
tex-omsantt.fd \
tex-omsanttc.fd \
tex-omsanttl.fd \
tex-omsanttlc.fd \
tex-omxantt.fd \
tex-omxanttc.fd \
tex-omxanttl.fd \
tex-omxanttlc.fd \
tex-ot1antt.fd \
tex-ot1anttc.fd \
tex-ot1anttcm.fd \
tex-ot1anttl.fd \
tex-ot1anttlc.fd \
tex-ot1anttlcm.fd \
tex-ot1anttlm.fd \
tex-ot1anttm.fd \
tex-ot2antt.fd \
tex-ot2anttc.fd \
tex-ot2anttl.fd \
tex-ot2anttlc.fd \
tex-ot4antt.fd \
tex-ot4anttc.fd \
tex-ot4anttl.fd \
tex-ot4anttlc.fd \
tex-qx-anttb.tfm \
tex-qx-anttbcap.tfm \
tex-qx-anttbi.tfm \
tex-qx-anttbicap.tfm \
tex-qx-anttcb.tfm \
tex-qx-anttcbcap.tfm \
tex-qx-anttcbi.tfm \
tex-qx-anttcbicap.tfm \
tex-qx-anttcl.tfm \
tex-qx-anttclcap.tfm \
tex-qx-anttcli.tfm \
tex-qx-anttclicap.tfm \
tex-qx-anttcm.tfm \
tex-qx-anttcmcap.tfm \
tex-qx-anttcmi.tfm \
tex-qx-anttcmicap.tfm \
tex-qx-anttcr.tfm \
tex-qx-anttcrcap.tfm \
tex-qx-anttcri.tfm \
tex-qx-anttcricap.tfm \
tex-qx-anttl.tfm \
tex-qx-anttlcap.tfm \
tex-qx-anttli.tfm \
tex-qx-anttlicap.tfm \
tex-qx-anttm.tfm \
tex-qx-anttmcap.tfm \
tex-qx-anttmi.tfm \
tex-qx-anttmicap.tfm \
tex-qx-anttr.tfm \
tex-qx-anttrcap.tfm \
tex-qx-anttri.tfm \
tex-qx-anttricap.tfm \
tex-qxantt.fd \
tex-qxanttc.fd \
tex-qxanttl.fd \
tex-qxanttlc.fd \
tex-rm-anttb.tfm \
tex-rm-anttbi.tfm \
tex-rm-anttcb.tfm \
tex-rm-anttcbi.tfm \
tex-rm-anttcl.tfm \
tex-rm-anttcli.tfm \
tex-rm-anttcm.tfm \
tex-rm-anttcmi.tfm \
tex-rm-anttcr.tfm \
tex-rm-anttcri.tfm \
tex-rm-anttl.tfm \
tex-rm-anttli.tfm \
tex-rm-anttm.tfm \
tex-rm-anttmi.tfm \
tex-rm-anttr.tfm \
tex-rm-anttri.tfm \
tex-sy-anttbz.tfm \
tex-sy-anttcbz.tfm \
tex-sy-anttclz.tfm \
tex-sy-anttcmz.tfm \
tex-sy-anttcrz.tfm \
tex-sy-anttlz.tfm \
tex-sy-anttmz.tfm \
tex-sy-anttrz.tfm \
tex-t1antt.fd \
tex-t1anttc.fd \
tex-t1anttl.fd \
tex-t1anttlc.fd \
tex-t2a-anttb.tfm \
tex-t2a-anttbi.tfm \
tex-t2a-anttcb.tfm \
tex-t2a-anttcbi.tfm \
tex-t2a-anttcl.tfm \
tex-t2a-anttcli.tfm \
tex-t2a-anttcm.tfm \
tex-t2a-anttcmi.tfm \
tex-t2a-anttcr.tfm \
tex-t2a-anttcri.tfm \
tex-t2a-anttl.tfm \
tex-t2a-anttli.tfm \
tex-t2a-anttm.tfm \
tex-t2a-anttmi.tfm \
tex-t2a-anttr.tfm \
tex-t2a-anttri.tfm \
tex-t2aantt.fd \
tex-t2aanttc.fd \
tex-t2aanttl.fd \
tex-t2aanttlc.fd \
tex-t2b-anttb.tfm \
tex-t2b-anttbi.tfm \
tex-t2b-anttcb.tfm \
tex-t2b-anttcbi.tfm \
tex-t2b-anttcl.tfm \
tex-t2b-anttcli.tfm \
tex-t2b-anttcm.tfm \
tex-t2b-anttcmi.tfm \
tex-t2b-anttcr.tfm \
tex-t2b-anttcri.tfm \
tex-t2b-anttl.tfm \
tex-t2b-anttli.tfm \
tex-t2b-anttm.tfm \
tex-t2b-anttmi.tfm \
tex-t2b-anttr.tfm \
tex-t2b-anttri.tfm \
tex-t2bantt.fd \
tex-t2banttc.fd \
tex-t2banttl.fd \
tex-t2banttlc.fd \
tex-t2c-anttb.tfm \
tex-t2c-anttbi.tfm \
tex-t2c-anttcb.tfm \
tex-t2c-anttcbi.tfm \
tex-t2c-anttcl.tfm \
tex-t2c-anttcli.tfm \
tex-t2c-anttcm.tfm \
tex-t2c-anttcmi.tfm \
tex-t2c-anttcr.tfm \
tex-t2c-anttcri.tfm \
tex-t2c-anttl.tfm \
tex-t2c-anttli.tfm \
tex-t2c-anttm.tfm \
tex-t2c-anttmi.tfm \
tex-t2c-anttr.tfm \
tex-t2c-anttri.tfm \
tex-t2cantt.fd \
tex-t2canttc.fd \
tex-t2canttl.fd \
tex-t2canttlc.fd \
tex-t5-anttb.tfm \
tex-t5-anttbcap.tfm \
tex-t5-anttbi.tfm \
tex-t5-anttbicap.tfm \
tex-t5-anttcb.tfm \
tex-t5-anttcbcap.tfm \
tex-t5-anttcbi.tfm \
tex-t5-anttcbicap.tfm \
tex-t5-anttcl.tfm \
tex-t5-anttclcap.tfm \
tex-t5-anttcli.tfm \
tex-t5-anttclicap.tfm \
tex-t5-anttcm.tfm \
tex-t5-anttcmcap.tfm \
tex-t5-anttcmi.tfm \
tex-t5-anttcmicap.tfm \
tex-t5-anttcr.tfm \
tex-t5-anttcrcap.tfm \
tex-t5-anttcri.tfm \
tex-t5-anttcricap.tfm \
tex-t5-anttl.tfm \
tex-t5-anttlcap.tfm \
tex-t5-anttli.tfm \
tex-t5-anttlicap.tfm \
tex-t5-anttm.tfm \
tex-t5-anttmcap.tfm \
tex-t5-anttmi.tfm \
tex-t5-anttmicap.tfm \
tex-t5-anttr.tfm \
tex-t5-anttrcap.tfm \
tex-t5-anttri.tfm \
tex-t5-anttricap.tfm \
tex-t5antt.fd \
tex-t5anttc.fd \
tex-t5anttl.fd \
tex-t5anttlc.fd \
tex-texnansi-anttb.tfm \
tex-texnansi-anttbcap.tfm \
tex-texnansi-anttbi.tfm \
tex-texnansi-anttbicap.tfm \
tex-texnansi-anttcb.tfm \
tex-texnansi-anttcbcap.tfm \
tex-texnansi-anttcbi.tfm \
tex-texnansi-anttcbicap.tfm \
tex-texnansi-anttcl.tfm \
tex-texnansi-anttclcap.tfm \
tex-texnansi-anttcli.tfm \
tex-texnansi-anttclicap.tfm \
tex-texnansi-anttcm.tfm \
tex-texnansi-anttcmcap.tfm \
tex-texnansi-anttcmi.tfm \
tex-texnansi-anttcmicap.tfm \
tex-texnansi-anttcr.tfm \
tex-texnansi-anttcrcap.tfm \
tex-texnansi-anttcri.tfm \
tex-texnansi-anttcricap.tfm \
tex-texnansi-anttl.tfm \
tex-texnansi-anttlcap.tfm \
tex-texnansi-anttli.tfm \
tex-texnansi-anttlicap.tfm \
tex-texnansi-anttm.tfm \
tex-texnansi-anttmcap.tfm \
tex-texnansi-anttmi.tfm \
tex-texnansi-anttmicap.tfm \
tex-texnansi-anttr.tfm \
tex-texnansi-anttrcap.tfm \
tex-texnansi-anttri.tfm \
tex-texnansi-anttricap.tfm \
tex-ts1-anttb.tfm \
tex-ts1-anttbi.tfm \
tex-ts1-anttcb.tfm \
tex-ts1-anttcbi.tfm \
tex-ts1-anttcl.tfm \
tex-ts1-anttcli.tfm \
tex-ts1-anttcm.tfm \
tex-ts1-anttcmi.tfm \
tex-ts1-anttcr.tfm \
tex-ts1-anttcri.tfm \
tex-ts1-anttl.tfm \
tex-ts1-anttli.tfm \
tex-ts1-anttm.tfm \
tex-ts1-anttmi.tfm \
tex-ts1-anttr.tfm \
tex-ts1-anttri.tfm \
tex-ts1antt.fd \
tex-ts1anttc.fd \
tex-ts1anttl.fd \
tex-ts1anttlc.fd \
tex-wncy-anttb.tfm \
tex-wncy-anttbi.tfm \
tex-wncy-anttcb.tfm \
tex-wncy-anttcbi.tfm \
tex-wncy-anttcl.tfm \
tex-wncy-anttcli.tfm \
tex-wncy-anttcm.tfm \
tex-wncy-anttcmi.tfm \
tex-wncy-anttcr.tfm \
tex-wncy-anttcri.tfm \
tex-wncy-anttl.tfm \
tex-wncy-anttli.tfm \
tex-wncy-anttm.tfm \
tex-wncy-anttmi.tfm \
tex-wncy-anttr.tfm \
tex-wncy-anttri.tfm \
texlive-antt"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-updmap.cfg \
texlive \
texlive-antt-fonts \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
