SUMMARY = "A simple Django application to demonstrate RRD plots"
DESCRIPTION = "django-collectd-rest is a simple Django application to demonstrate RRD plots generated by collectd or any other rrd data. \
The application is built on top of django-rest-framework and provides REST API to access the plots."
LICENSE = "BSD-2-Clause"

PV = "0.2.4"

RPM_NAME = "python310-django-collectd-rest-0.2.4-1.5.aarch64.rpm"
RPM_HASH = "ade80fba36061860520ecf708573b7d7e267345e02374d5025bbac088b44d976de20da27615899dedb79082c2fe4d154a0b59d4e2779201ccaabc45fc0deff7b"

RPROVIDES:${PN} += "python3.10dist-django-collectd-rest \
python310-django-collectd-rest \
python3dist-django-collectd-rest"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1 \
libc.so.6 \
librrd.so.8 \
python-abi \
python310-Django \
python310-djangorestframework \
rrdtool"

inherit rpm
