SUMMARY = "Organize Data in Tables"
DESCRIPTION = "Organization of data in table form is a time-honored and useful method of \
data representation. While columns of data are trivially generated by \
computer through formatted output, even simple tasks like keeping titles \
aligned with the data columns are not trivial, and the one-shot solutions \
one comes up with tend to be particularly hard to maintain. Text::Table \
allows you to create and maintain tables that adapt to alignment \
requirements as you use them."
LICENSE = "ISC"

PV = "1.135"

RPM_NAME = "perl-Text-Table-1.135-1.4.noarch.rpm"
RPM_HASH = "a744107eed8ee6e03aaf675e1f217b0af73b76dd3654adc095fc5f82d0024829a6b405a4c4fec91229989d156c1b31cabf45512b2f1904cf6edfd05c54164c8b"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "perl-Text--Table \
perl-Text-Table"

RDEPENDS:${PN} += "perl--MODULE-COMPAT-5.38.0 \
perl-Text--Aligner"

inherit rpm
