SUMMARY = "Organize Data in Tables"
DESCRIPTION = "Organization of data in table form is a time-honored and useful method of \
data representation. While columns of data are trivially generated by \
computer through formatted output, even simple tasks like keeping titles \
aligned with the data columns are not trivial, and the one-shot solutions \
one comes up with tend to be particularly hard to maintain. Text::Table \
allows you to create and maintain tables that adapt to alignment \
requirements as you use them."
LICENSE = "ISC"

PV = "1.135"

RPM_NAME = "perl-Text-Table-1.135-1.3.noarch.rpm"
RPM_HASH = "8b20022846a5d97b302b0ab24eb8dc9debdd2ca4adb416f5916c07d03fc7aa632faf48a4908fd4801ef3645107a82ee65cd23c4d5f23d1112bd7044d8a67b186"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "perl-Text--Table \
perl-Text-Table"

RDEPENDS:${PN} += "perl--MODULE-COMPAT-5.36.1 \
perl-Text--Aligner"

inherit rpm
