SUMMARY = "Gateway between Kafka and Humio for Velociraptor Artifacts"
DESCRIPTION = "This tool is used to consume events generated by the Kafka Velociraptor plugin \
and post them to a Humio cluster."
LICENSE = "AGPL-3.0-only"

PV = "0.6.7.5~git81.01be570"

RPM_NAME = "velociraptor-kafka-humio-gateway-0.6.7.5~git81.01be570-4.1.aarch64.rpm"
RPM_HASH = "20263de136442952231ff5846f86a6259ee4b1c327abc0117281a4875b5248234c5749a75e1f5c1b1284eee487065ab3d6178248fce28f243ac5d9e8e79af986"

RPROVIDES:${PN} += "config-velociraptor-kafka-humio-gateway \
group-velociraptor-kafka \
user-velociraptor-kafka \
velociraptor-kafka-humio-gateway"

RDEPENDS:${PN} += "/usr/bin/sh \
libc.so.6"

inherit rpm
