SUMMARY = "Gateway between Kafka and Humio for Velociraptor Artifacts"
DESCRIPTION = "This tool is used to consume events generated by the Kafka Velociraptor plugin \
and post them to a Humio cluster."
LICENSE = "AGPL-3.0-only"

PV = "0.6.7.5~git81.01be570"

RPM_NAME = "velociraptor-kafka-humio-gateway-0.6.7.5~git81.01be570-3.3.aarch64.rpm"
RPM_HASH = "2e9e1e0171cdbecf93887cdff466752d596c4dffa4d7901a8aba90f40c37cb8d3fd46ae5918a3eafeb3b756f704c04c16bee6e1e8e9273712112499af5ad3ad8"

RPROVIDES:${PN} += "config-velociraptor-kafka-humio-gateway \
group-velociraptor-kafka \
user-velociraptor-kafka \
velociraptor-kafka-humio-gateway"

RDEPENDS:${PN} += "/usr/bin/sh \
libc.so.6"

inherit rpm
