SUMMARY = "Gateway between Kafka and Humio for Velociraptor Artifacts"
DESCRIPTION = "This tool is used to consume events generated by the Kafka Velociraptor plugin \
and post them to a Humio cluster."
LICENSE = "AGPL-3.0-only"

PV = "0.6.7.5~git78.2bef6fc"

RPM_NAME = "velociraptor-kafka-humio-gateway-0.6.7.5~git78.2bef6fc-2.1.aarch64.rpm"
RPM_HASH = "910a4e8242ca90481094f33e9ab24c832d6ba27643fef79bdeef47523d15d52d664d974241569d42be878870a2c963054890646fae5c8090ea24300f6b1adbda"

RPROVIDES:${PN} += "config(velociraptor-kafka-humio-gateway) group(velociraptor-kafka) user(velociraptor-kafka) velociraptor-kafka-humio-gateway velociraptor-kafka-humio-gateway(aarch-64)"
RDEPENDS:${PN} += "/bin/sh libc.so.6(GLIBC_2.34)(64bit)"

inherit rpm
