SUMMARY = "A sophisticated typesetting engine"
DESCRIPTION = "TeX is a typesetting system that incorporates a macro \
processor. A TeX source document specifies or incorporates a \
number of macro definitions that instruct the TeX engine how to \
typeset the document. The TeX engine also uses font metrics \
generated by Metafont, or by any of several other mechanisms \
that incorporate fonts from other sources into an environment \
suitable for TeX. TeX has been, and continues, a basis and an \
inspiration for several other programs, including e-TeX and \
PDFTeX. The distribution includes the source of Knuth's TeX \
book; this source is there to read, as an example of writing \
TeX -- it should not be processed without Knuth's direct \
permission."
LICENSE = "SUSE-TeX"

PV = "2023.201.3.141592653svn66186"

RPM_NAME = "texlive-tex-2023.201.3.141592653svn66186-54.1.noarch.rpm"
RPM_HASH = "476a8273a261953440b9a11be2e80bf02de8dbbcdcde49ed888c8bc3e67d9291e5d2e614e2c825ba5c0a37c2e03051bada0539838c578cc76f09b72e9728d4d6"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "man-initex.1 \
man-tex.1 \
texlive-tex"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-language.dat \
tex-language.dat.lua \
tex-language.def \
tex-null.tex \
texlive \
texlive-amsfonts \
texlive-cm \
texlive-cm-super \
texlive-ec \
texlive-epsf \
texlive-filesystem \
texlive-hyph-utf8 \
texlive-hyphen-base \
texlive-knuth-lib \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-manfnt \
texlive-plain \
texlive-scripts \
texlive-scripts-bin \
texlive-tex-bin"

inherit rpm
