SUMMARY = "Severed fonts for texlive-qualitype"
DESCRIPTION = "The  separated fonts package for texlive-qualitype"
LICENSE = "OFL-1.1"

PV = "2023.209.svn54512"

RPM_NAME = "texlive-qualitype-fonts-2023.209.svn54512-54.2.noarch.rpm"
RPM_HASH = "b490de4fa35f026337c2b3bc663362264f19fe2061b95a57accbc1e1209527c3821b32634ba41fe6969e3dcbc5847fb31a024998d5954b3666ffbdf9bed22fc6"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "font--lang=aa \
font--lang=an \
font--lang=ay \
font--lang=bi \
font--lang=br \
font--lang=ch \
font--lang=co \
font--lang=da \
font--lang=de \
font--lang=en \
font--lang=es \
font--lang=et \
font--lang=eu \
font--lang=fi \
font--lang=fil \
font--lang=fj \
font--lang=fo \
font--lang=fr \
font--lang=fur \
font--lang=fy \
font--lang=gd \
font--lang=gl \
font--lang=gv \
font--lang=ho \
font--lang=ht \
font--lang=ia \
font--lang=id \
font--lang=ie \
font--lang=io \
font--lang=is \
font--lang=it \
font--lang=jv \
font--lang=kj \
font--lang=kwm \
font--lang=lb \
font--lang=li \
font--lang=mg \
font--lang=ms \
font--lang=nb \
font--lang=nds \
font--lang=ng \
font--lang=nl \
font--lang=nn \
font--lang=no \
font--lang=nr \
font--lang=nso \
font--lang=oc \
font--lang=om \
font--lang=pap-an \
font--lang=pap-aw \
font--lang=pt \
font--lang=rm \
font--lang=rn \
font--lang=rw \
font--lang=sc \
font--lang=sg \
font--lang=sma \
font--lang=smj \
font--lang=sn \
font--lang=so \
font--lang=sq \
font--lang=ss \
font--lang=st \
font--lang=su \
font--lang=sv \
font--lang=sw \
font--lang=tl \
font--lang=tn \
font--lang=ts \
font--lang=uz \
font--lang=vo \
font--lang=vot \
font--lang=wa \
font--lang=xh \
font--lang=yap \
font--lang=za \
font--lang=zu \
font-qtabbie \
font-qtagatetype \
font-qtancientolive \
font-qtantiquepost \
font-qtarabian \
font-qtarnieb \
font-qtartiston \
font-qtatchen \
font-qtavanti \
font-qtbasker \
font-qtbeckman \
font-qtbengal \
font-qtblackforest \
font-qtblimpo \
font-qtbodini \
font-qtbodiniposter \
font-qtbookmann \
font-qtboulevard \
font-qtbrushstroke \
font-qtcaligulatype \
font-qtcanaithtype \
font-qtcascadetype \
font-qtcaslan \
font-qtcaslanopen \
font-qtcasual \
font-qtchancerytype \
font-qtchicagoland \
font-qtclaytablet \
font-qtcloisteredmonk \
font-qtcoronation \
font-qtdeuce \
font-qtdingbits \
font-qtdoghaus \
font-qtdoghausheavy \
font-qtdoghauslight \
font-qtdublinirish \
font-qteratype \
font-qteurotype \
font-qtfloraline \
font-qtflorencia \
font-qtfraktur \
font-qtfrank \
font-qtfrankheavy \
font-qtfrizquad \
font-qtfuture \
font-qtfutureposter \
font-qtgaromand \
font-qtghoulface \
font-qtgraphlite \
font-qtgraveure \
font-qtgreece \
font-qthandwriting \
font-qtheidelbergtype \
font-qthelvet-black \
font-qthelvet-boldoutline \
font-qthelvetcnd \
font-qthelvetcnd-black \
font-qthelvetcnd-light \
font-qthoboken \
font-qthowardtype \
font-qthowardtypefat \
font-qtimpromptu \
font-qtjupiter \
font-qtkooper \
font-qtkorrin \
font-qtkung-fu \
font-qtlautrectype \
font-qtlettergoth \
font-qtlinoscroll \
font-qtlinostroke \
font-qtlondonscroll \
font-qtmagicmarker \
font-qtmerryscript \
font-qtmilitary \
font-qtokcorral \
font-qtokcorral-cnd \
font-qtokcorral-ext \
font-qtoldgoudy \
font-qtoptimum \
font-qtpalatine \
font-qtpandora \
font-qtparisfrance \
font-qtpeignoir \
font-qtpeignoir-lite \
font-qtpiltdown \
font-qtpristine \
font-qtrobotic2000 \
font-qtsandiego \
font-qtschoolcentury \
font-qtslogantype \
font-qtsnowcaps \
font-qtstorytimecaps \
font-qttechtone \
font-qttheatre \
font-qttimeoutline \
font-qttumbleweed \
font-qtusa-uncial \
font-qtvagaround \
font-qtweise \
font-qtwestend \
texlive-qualitype-fonts"

RDEPENDS:${PN} += "/usr/bin/sh \
aaa-base \
coreutils \
fontconfig \
ghostscript-fonts-std \
perl"

inherit rpm
