SUMMARY = "Include a DVI page into MetaPost output"
DESCRIPTION = "DVItoMP is one of the auxiliary programs available to any \
MetaPost package; it converts a DVI file into a MetaPost file. \
Using it, one can envisage including a DVI page into an EPS \
files generated by MetaPost. Such files allow pages to include \
other pages."
LICENSE = "SUSE-Public-Domain"

PV = "2023.201.1.00svn29349"

RPM_NAME = "texlive-dviincl-2023.201.1.00svn29349-53.2.noarch.rpm"
RPM_HASH = "d74ff27d3de22329071b704c5c4fe4e4cb1c2c3f1bb9b24698e9f2ceadb789069f175fe29333f197810ba45c0f4d36d05f7c7c9662ec0bc8ed45789255227051"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "texlive-dviincl"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
