SUMMARY = "Include a DVI page into MetaPost output"
DESCRIPTION = "DVItoMP is one of the auxiliary programs available to any \
MetaPost package; it converts a DVI file into a MetaPost file. \
Using it, one can envisage including a DVI page into an EPS \
files generated by MetaPost. Such files allow pages to include \
other pages."
LICENSE = "SUSE-Public-Domain"

PV = "2023.209.1.00svn29349"

RPM_NAME = "texlive-dviincl-2023.209.1.00svn29349-54.2.noarch.rpm"
RPM_HASH = "1e9f4476ac470ac4658bd39bf43ad81938e0d8f309fd4977b6a1292d2710cfbc2f6a0064db9ef82a1839981d1f4b4345b8fc5fb0357970d490e411c75186739b"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "texlive-dviincl"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
