SUMMARY = "Include a DVI page into MetaPost output"
DESCRIPTION = "DVItoMP is one of the auxiliary programs available to any \
MetaPost package; it converts a DVI file into a MetaPost file. \
Using it, one can envisage including a DVI page into an EPS \
files generated by MetaPost. Such files allow pages to include \
other pages."
LICENSE = "SUSE-Public-Domain"

PV = "2023.209.1.00svn29349"

RPM_NAME = "texlive-dviincl-2023.209.1.00svn29349-54.1.noarch.rpm"
RPM_HASH = "7c1816bd77408a1b89c5789300d76da671d71c57d1a31f0b299b082274fe5d14ea0d3a3c204f9c8270d13e2905812641f2eeeff733994d37ca63eda46650ee38"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "texlive-dviincl"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
