SUMMARY = "Advanced general-purpose multimedia player"
DESCRIPTION = "mpv is a movie player based on MPlayer and mplayer2. It supports a wide variety \
of video file formats, audio and video codecs, and subtitle types."
LICENSE = "GPL-2.0-or-later"

PV = "0.35.1+git.20230315.e1727553"

RPM_NAME = "mpv-0.35.1+git.20230315.e1727553-1.4.aarch64.rpm"
RPM_HASH = "149c6ff5e22b987d3de752b11ad1ce5083bce468091b87dd9bdc4916b8469a4a4fa6064fb87916bd8b0b683162ce89e1e907b23ecf1b1521924c0968c11e2a3c"

RPROVIDES:${PN} += "application() \
application(mpv.desktop) \
config(mpv) \
metainfo() \
metainfo(mpv.metainfo.xml) \
mimehandler(application/mxf) \
mimehandler(application/ogg) \
mimehandler(application/sdp) \
mimehandler(application/smil) \
mimehandler(application/streamingmedia) \
mimehandler(application/vnd.apple.mpegurl) \
mimehandler(application/vnd.ms-asf) \
mimehandler(application/vnd.rn-realmedia) \
mimehandler(application/vnd.rn-realmedia-vbr) \
mimehandler(application/x-cue) \
mimehandler(application/x-extension-m4a) \
mimehandler(application/x-extension-mp4) \
mimehandler(application/x-matroska) \
mimehandler(application/x-mpegurl) \
mimehandler(application/x-ogg) \
mimehandler(application/x-ogm) \
mimehandler(application/x-ogm-audio) \
mimehandler(application/x-ogm-video) \
mimehandler(application/x-shorten) \
mimehandler(application/x-smil) \
mimehandler(application/x-streamingmedia) \
mimehandler(audio/3gpp) \
mimehandler(audio/3gpp2) \
mimehandler(audio/AMR) \
mimehandler(audio/aac) \
mimehandler(audio/ac3) \
mimehandler(audio/aiff) \
mimehandler(audio/amr-wb) \
mimehandler(audio/dv) \
mimehandler(audio/eac3) \
mimehandler(audio/flac) \
mimehandler(audio/m3u) \
mimehandler(audio/m4a) \
mimehandler(audio/mp1) \
mimehandler(audio/mp2) \
mimehandler(audio/mp3) \
mimehandler(audio/mp4) \
mimehandler(audio/mpeg) \
mimehandler(audio/mpeg2) \
mimehandler(audio/mpeg3) \
mimehandler(audio/mpegurl) \
mimehandler(audio/mpg) \
mimehandler(audio/musepack) \
mimehandler(audio/ogg) \
mimehandler(audio/opus) \
mimehandler(audio/rn-mpeg) \
mimehandler(audio/scpls) \
mimehandler(audio/vnd.dolby.heaac.1) \
mimehandler(audio/vnd.dolby.heaac.2) \
mimehandler(audio/vnd.dts) \
mimehandler(audio/vnd.dts.hd) \
mimehandler(audio/vnd.rn-realaudio) \
mimehandler(audio/vorbis) \
mimehandler(audio/wav) \
mimehandler(audio/webm) \
mimehandler(audio/x-aac) \
mimehandler(audio/x-adpcm) \
mimehandler(audio/x-aiff) \
mimehandler(audio/x-ape) \
mimehandler(audio/x-m4a) \
mimehandler(audio/x-matroska) \
mimehandler(audio/x-mp1) \
mimehandler(audio/x-mp2) \
mimehandler(audio/x-mp3) \
mimehandler(audio/x-mpegurl) \
mimehandler(audio/x-mpg) \
mimehandler(audio/x-ms-asf) \
mimehandler(audio/x-ms-wma) \
mimehandler(audio/x-musepack) \
mimehandler(audio/x-pls) \
mimehandler(audio/x-pn-au) \
mimehandler(audio/x-pn-realaudio) \
mimehandler(audio/x-pn-wav) \
mimehandler(audio/x-pn-windows-pcm) \
mimehandler(audio/x-realaudio) \
mimehandler(audio/x-scpls) \
mimehandler(audio/x-shorten) \
mimehandler(audio/x-tta) \
mimehandler(audio/x-vorbis) \
mimehandler(audio/x-vorbis+ogg) \
mimehandler(audio/x-wav) \
mimehandler(audio/x-wavpack) \
mimehandler(video/3gp) \
mimehandler(video/3gpp) \
mimehandler(video/3gpp2) \
mimehandler(video/avi) \
mimehandler(video/divx) \
mimehandler(video/dv) \
mimehandler(video/fli) \
mimehandler(video/flv) \
mimehandler(video/mkv) \
mimehandler(video/mp2t) \
mimehandler(video/mp4) \
mimehandler(video/mp4v-es) \
mimehandler(video/mpeg) \
mimehandler(video/msvideo) \
mimehandler(video/ogg) \
mimehandler(video/quicktime) \
mimehandler(video/vnd.divx) \
mimehandler(video/vnd.mpegurl) \
mimehandler(video/vnd.rn-realvideo) \
mimehandler(video/webm) \
mimehandler(video/x-avi) \
mimehandler(video/x-flc) \
mimehandler(video/x-flic) \
mimehandler(video/x-flv) \
mimehandler(video/x-m4v) \
mimehandler(video/x-matroska) \
mimehandler(video/x-mpeg2) \
mimehandler(video/x-mpeg3) \
mimehandler(video/x-ms-afs) \
mimehandler(video/x-ms-asf) \
mimehandler(video/x-ms-wmv) \
mimehandler(video/x-ms-wmx) \
mimehandler(video/x-ms-wvxvideo) \
mimehandler(video/x-msvideo) \
mimehandler(video/x-ogm) \
mimehandler(video/x-ogm+ogg) \
mimehandler(video/x-theora) \
mimehandler(video/x-theora+ogg) \
mplayer2 \
mpv \
mpv(aarch-64)"
RDEPENDS:${PN} += "hicolor-icon-theme \
ld-linux-aarch64.so.1()(64bit) \
ld-linux-aarch64.so.1(GLIBC_2.17)(64bit) \
libEGL.so.1()(64bit) \
libX11.so.6()(64bit) \
libXext.so.6()(64bit) \
libXinerama.so.1()(64bit) \
libXpresent.so.1()(64bit) \
libXrandr.so.2()(64bit) \
libXss.so.1()(64bit) \
libXv.so.1()(64bit) \
libarchive.so.13()(64bit) \
libasound.so.2()(64bit) \
libasound.so.2(ALSA_0.9)(64bit) \
libasound.so.2(ALSA_0.9.0rc4)(64bit) \
libass.so.9()(64bit) \
libavcodec.so.60()(64bit) \
libavcodec.so.60(LIBAVCODEC_60.3_SUSE)(64bit) \
libavdevice.so.60()(64bit) \
libavdevice.so.60(LIBAVDEVICE_60.1_SUSE)(64bit) \
libavfilter.so.9()(64bit) \
libavfilter.so.9(LIBAVFILTER_9.3_SUSE)(64bit) \
libavformat.so.60()(64bit) \
libavformat.so.60(LIBAVFORMAT_60.3_SUSE)(64bit) \
libavutil.so.58()(64bit) \
libavutil.so.58(LIBAVUTIL_58.2_SUSE)(64bit) \
libbluray.so.2()(64bit) \
libc.so.6(GLIBC_2.34)(64bit) \
libcaca.so.0()(64bit) \
libcdio.so.19()(64bit) \
libcdio.so.19(CDIO_19)(64bit) \
libcdio_cdda.so.2()(64bit) \
libcdio_cdda.so.2(CDIO_CDDA_2)(64bit) \
libcdio_paranoia.so.2()(64bit) \
libcdio_paranoia.so.2(CDIO_PARANOIA_2)(64bit) \
libdrm.so.2()(64bit) \
libdvdnav.so.4()(64bit) \
libgbm.so.1()(64bit) \
libjack.so.0()(64bit) \
libjpeg.so.8()(64bit) \
libjpeg.so.8(LIBJPEG_8.0)(64bit) \
liblcms2.so.2()(64bit) \
liblua5.1.so.5()(64bit) \
libm.so.6()(64bit) \
libm.so.6(GLIBC_2.17)(64bit) \
libm.so.6(GLIBC_2.27)(64bit) \
libm.so.6(GLIBC_2.29)(64bit) \
libopenal.so.1()(64bit) \
libpipewire-0.3.so.0()(64bit) \
libplacebo.so.264()(64bit) \
libpulse.so.0()(64bit) \
libpulse.so.0(PULSE_0)(64bit) \
librubberband.so.2()(64bit) \
libshaderc_shared.so.1()(64bit) \
libsixel.so.1()(64bit) \
libswresample.so.4()(64bit) \
libswresample.so.4(LIBSWRESAMPLE_4.10_SUSE)(64bit) \
libswscale.so.7()(64bit) \
libswscale.so.7(LIBSWSCALE_7.1_SUSE)(64bit) \
libuchardet.so.0()(64bit) \
libva-drm.so.2()(64bit) \
libva-wayland.so.2()(64bit) \
libva-x11.so.2()(64bit) \
libva.so.2()(64bit) \
libva.so.2(VA_API_0.33.0)(64bit) \
libvapoursynth-script.so.0()(64bit) \
libvdpau.so.1()(64bit) \
libvulkan.so.1()(64bit) \
libwayland-client.so.0()(64bit) \
libwayland-cursor.so.0()(64bit) \
libwayland-egl.so.1()(64bit) \
libxkbcommon.so.0()(64bit) \
libxkbcommon.so.0(V_0.5.0)(64bit) \
libz.so.1()(64bit) \
libzimg.so.2()(64bit) \
update-desktop-files"

inherit rpm
