SUMMARY = "Lua Documentation for lpeg"
DESCRIPTION = "Documentation and examples included with the library, sometimes \
generated by luadoc or ldoc."
LICENSE = "MIT"

PV = "1.1.0"

RPM_NAME = "lua53-lpeg-doc-1.1.0-1.1.noarch.rpm"
RPM_HASH = "aea08bbff96beb3d5460e19f95422f4c905d8b1bfe5b9ea64e3470c832de712ad17c8750100118b75a1382e941f5fe97c790e00b83ca5c738987ac038a9a9383"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "lua53-lpeg-doc"

RDEPENDS:${PN} += "lua53-lpeg"

inherit rpm
