SUMMARY = "Lua Documentation for lpeg"
DESCRIPTION = "Documentation and examples included with the library, sometimes \
generated by luadoc or ldoc."
LICENSE = "MIT"

PV = "1.0.2"

RPM_NAME = "lua53-lpeg-doc-1.0.2-6.3.noarch.rpm"
RPM_HASH = "13ac9024ae4b06b124b14ac245d0630f79b68586fe375b607cd9855132030fc4d397813a76becc05ced0e58b1cd672fbadcf5c3dbe360664321f8aaa6323eca7"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "lua53-lpeg-doc"
RDEPENDS:${PN} += "lua53-lpeg"

inherit rpm
