SUMMARY = "Spotify client running as a UNIX daemon"
DESCRIPTION = "Spotifyd streams music just like the official client, but is more lightweight \
and supports more platforms. Spotifyd also supports the Spotify Connect \
protocol, which makes it show up as a device that can be controlled from \
the official clients."
LICENSE = "GPL-3.0-or-later"

PV = "0.3.3"

RPM_NAME = "spotifyd-0.3.3-10.3.aarch64.rpm"
RPM_HASH = "afb8d93e21ef4851ad3f5911e034026a07bf8c02ccd557f613d3b58af1610c5dda4e0ac03e2b2cb91a18d365f73e1bd4015ed2f0f44bafaef69e90b5b095e25b"

RPROVIDES:${PN} += "bundled(rust-crate:addr2line) \
bundled(rust-crate:adler) \
bundled(rust-crate:aes) \
bundled(rust-crate:aes-ctr) \
bundled(rust-crate:aes-soft) \
bundled(rust-crate:aho-corasick) \
bundled(rust-crate:alsa) \
bundled(rust-crate:alsa-sys) \
bundled(rust-crate:ansi_term) \
bundled(rust-crate:async-io) \
bundled(rust-crate:async-lock) \
bundled(rust-crate:async-trait) \
bundled(rust-crate:atty) \
bundled(rust-crate:autocfg) \
bundled(rust-crate:backtrace) \
bundled(rust-crate:base64) \
bundled(rust-crate:bitflags) \
bundled(rust-crate:block-buffer) \
bundled(rust-crate:block-modes) \
bundled(rust-crate:block-padding) \
bundled(rust-crate:boxfnonce) \
bundled(rust-crate:byteorder) \
bundled(rust-crate:bytes) \
bundled(rust-crate:cc) \
bundled(rust-crate:cfg-if) \
bundled(rust-crate:chrono) \
bundled(rust-crate:cipher) \
bundled(rust-crate:clap) \
bundled(rust-crate:color-eyre) \
bundled(rust-crate:color-spantrace) \
bundled(rust-crate:concurrent-queue) \
bundled(rust-crate:cpufeatures) \
bundled(rust-crate:crossbeam-utils) \
bundled(rust-crate:crypto-mac) \
bundled(rust-crate:ctr) \
bundled(rust-crate:daemonize) \
bundled(rust-crate:darling) \
bundled(rust-crate:darling_core) \
bundled(rust-crate:darling_macro) \
bundled(rust-crate:dbus) \
bundled(rust-crate:dbus-crossroads) \
bundled(rust-crate:dbus-tokio) \
bundled(rust-crate:derivative) \
bundled(rust-crate:derive_builder) \
bundled(rust-crate:derive_builder_core) \
bundled(rust-crate:digest) \
bundled(rust-crate:dirs) \
bundled(rust-crate:dirs-sys) \
bundled(rust-crate:dotenv) \
bundled(rust-crate:either) \
bundled(rust-crate:encoding_rs) \
bundled(rust-crate:enumflags2) \
bundled(rust-crate:enumflags2_derive) \
bundled(rust-crate:env_logger) \
bundled(rust-crate:error-chain) \
bundled(rust-crate:event-listener) \
bundled(rust-crate:eyre) \
bundled(rust-crate:failure) \
bundled(rust-crate:failure_derive) \
bundled(rust-crate:fastrand) \
bundled(rust-crate:fern) \
bundled(rust-crate:fnv) \
bundled(rust-crate:foreign-types) \
bundled(rust-crate:foreign-types-shared) \
bundled(rust-crate:form_urlencoded) \
bundled(rust-crate:futures) \
bundled(rust-crate:futures-channel) \
bundled(rust-crate:futures-core) \
bundled(rust-crate:futures-executor) \
bundled(rust-crate:futures-io) \
bundled(rust-crate:futures-lite) \
bundled(rust-crate:futures-macro) \
bundled(rust-crate:futures-sink) \
bundled(rust-crate:futures-task) \
bundled(rust-crate:futures-util) \
bundled(rust-crate:gcc) \
bundled(rust-crate:generic-array) \
bundled(rust-crate:gethostname) \
bundled(rust-crate:getrandom) \
bundled(rust-crate:gimli) \
bundled(rust-crate:glob) \
bundled(rust-crate:h2) \
bundled(rust-crate:hashbrown) \
bundled(rust-crate:heck) \
bundled(rust-crate:hex) \
bundled(rust-crate:hkdf) \
bundled(rust-crate:hmac) \
bundled(rust-crate:hostname) \
bundled(rust-crate:http) \
bundled(rust-crate:http-body) \
bundled(rust-crate:httparse) \
bundled(rust-crate:httpdate) \
bundled(rust-crate:humantime) \
bundled(rust-crate:hyper) \
bundled(rust-crate:hyper-tls) \
bundled(rust-crate:iana-time-zone) \
bundled(rust-crate:ident_case) \
bundled(rust-crate:idna) \
bundled(rust-crate:if-addrs) \
bundled(rust-crate:indenter) \
bundled(rust-crate:indexmap) \
bundled(rust-crate:iovec) \
bundled(rust-crate:ipnet) \
bundled(rust-crate:itertools) \
bundled(rust-crate:itoa) \
bundled(rust-crate:keyring) \
bundled(rust-crate:lazy_static) \
bundled(rust-crate:lewton) \
bundled(rust-crate:libc) \
bundled(rust-crate:libdbus-sys) \
bundled(rust-crate:libmdns) \
bundled(rust-crate:libpulse-binding) \
bundled(rust-crate:libpulse-simple-binding) \
bundled(rust-crate:libpulse-simple-sys) \
bundled(rust-crate:libpulse-sys) \
bundled(rust-crate:librespot-audio) \
bundled(rust-crate:librespot-connect) \
bundled(rust-crate:librespot-core) \
bundled(rust-crate:librespot-metadata) \
bundled(rust-crate:librespot-playback) \
bundled(rust-crate:librespot-protocol) \
bundled(rust-crate:librespot-tremor) \
bundled(rust-crate:lock_api) \
bundled(rust-crate:log) \
bundled(rust-crate:match_cfg) \
bundled(rust-crate:matches) \
bundled(rust-crate:maybe-uninit) \
bundled(rust-crate:memchr) \
bundled(rust-crate:memoffset) \
bundled(rust-crate:mime) \
bundled(rust-crate:mime_guess) \
bundled(rust-crate:miniz_oxide) \
bundled(rust-crate:mio) \
bundled(rust-crate:multimap) \
bundled(rust-crate:native-tls) \
bundled(rust-crate:nb-connect) \
bundled(rust-crate:net2) \
bundled(rust-crate:nix) \
bundled(rust-crate:nom8) \
bundled(rust-crate:num) \
bundled(rust-crate:num-bigint) \
bundled(rust-crate:num-complex) \
bundled(rust-crate:num-derive) \
bundled(rust-crate:num-integer) \
bundled(rust-crate:num-iter) \
bundled(rust-crate:num-rational) \
bundled(rust-crate:num-traits) \
bundled(rust-crate:num_cpus) \
bundled(rust-crate:object) \
bundled(rust-crate:ogg) \
bundled(rust-crate:ogg-sys) \
bundled(rust-crate:once_cell) \
bundled(rust-crate:opaque-debug) \
bundled(rust-crate:openssl) \
bundled(rust-crate:openssl-macros) \
bundled(rust-crate:openssl-probe) \
bundled(rust-crate:openssl-sys) \
bundled(rust-crate:owo-colors) \
bundled(rust-crate:parking) \
bundled(rust-crate:parking_lot) \
bundled(rust-crate:parking_lot_core) \
bundled(rust-crate:pbkdf2) \
bundled(rust-crate:percent-encoding) \
bundled(rust-crate:pin-project) \
bundled(rust-crate:pin-project-internal) \
bundled(rust-crate:pin-project-lite) \
bundled(rust-crate:pin-utils) \
bundled(rust-crate:pkg-config) \
bundled(rust-crate:polling) \
bundled(rust-crate:ppv-lite86) \
bundled(rust-crate:priority-queue) \
bundled(rust-crate:proc-macro-crate) \
bundled(rust-crate:proc-macro-error) \
bundled(rust-crate:proc-macro-error-attr) \
bundled(rust-crate:proc-macro2) \
bundled(rust-crate:protobuf) \
bundled(rust-crate:protobuf-codegen) \
bundled(rust-crate:protobuf-codegen-pure) \
bundled(rust-crate:quick-error) \
bundled(rust-crate:quote) \
bundled(rust-crate:rand) \
bundled(rust-crate:rand_chacha) \
bundled(rust-crate:rand_core) \
bundled(rust-crate:rand_hc) \
bundled(rust-crate:rand_isaac) \
bundled(rust-crate:rand_jitter) \
bundled(rust-crate:rand_os) \
bundled(rust-crate:rand_pcg) \
bundled(rust-crate:rand_xorshift) \
bundled(rust-crate:random) \
bundled(rust-crate:regex) \
bundled(rust-crate:regex-syntax) \
bundled(rust-crate:remove_dir_all) \
bundled(rust-crate:reqwest) \
bundled(rust-crate:rspotify) \
bundled(rust-crate:rustc-demangle) \
bundled(rust-crate:rustc-serialize) \
bundled(rust-crate:rustc_version) \
bundled(rust-crate:ryu) \
bundled(rust-crate:scoped-tls) \
bundled(rust-crate:scopeguard) \
bundled(rust-crate:secret-service) \
bundled(rust-crate:semver) \
bundled(rust-crate:semver-parser) \
bundled(rust-crate:serde) \
bundled(rust-crate:serde_derive) \
bundled(rust-crate:serde_json) \
bundled(rust-crate:serde_repr) \
bundled(rust-crate:serde_urlencoded) \
bundled(rust-crate:sha-1) \
bundled(rust-crate:sha2) \
bundled(rust-crate:shannon) \
bundled(rust-crate:sharded-slab) \
bundled(rust-crate:shell-words) \
bundled(rust-crate:signal-hook-registry) \
bundled(rust-crate:slab) \
bundled(rust-crate:smallvec) \
bundled(rust-crate:socket2) \
bundled(rust-crate:spotifyd) \
bundled(rust-crate:static_assertions) \
bundled(rust-crate:strsim) \
bundled(rust-crate:structopt) \
bundled(rust-crate:structopt-derive) \
bundled(rust-crate:subtle) \
bundled(rust-crate:syn) \
bundled(rust-crate:synstructure) \
bundled(rust-crate:syslog) \
bundled(rust-crate:tempfile) \
bundled(rust-crate:termcolor) \
bundled(rust-crate:textwrap) \
bundled(rust-crate:thiserror) \
bundled(rust-crate:thiserror-impl) \
bundled(rust-crate:thread_local) \
bundled(rust-crate:time) \
bundled(rust-crate:tinyvec) \
bundled(rust-crate:tinyvec_macros) \
bundled(rust-crate:tokio) \
bundled(rust-crate:tokio-compat) \
bundled(rust-crate:tokio-compat-02) \
bundled(rust-crate:tokio-current-thread) \
bundled(rust-crate:tokio-executor) \
bundled(rust-crate:tokio-io) \
bundled(rust-crate:tokio-macros) \
bundled(rust-crate:tokio-native-tls) \
bundled(rust-crate:tokio-reactor) \
bundled(rust-crate:tokio-socks) \
bundled(rust-crate:tokio-stream) \
bundled(rust-crate:tokio-sync) \
bundled(rust-crate:tokio-timer) \
bundled(rust-crate:tokio-tls) \
bundled(rust-crate:tokio-util) \
bundled(rust-crate:toml) \
bundled(rust-crate:toml_datetime) \
bundled(rust-crate:toml_edit) \
bundled(rust-crate:tower-service) \
bundled(rust-crate:tracing) \
bundled(rust-crate:tracing-attributes) \
bundled(rust-crate:tracing-core) \
bundled(rust-crate:tracing-error) \
bundled(rust-crate:tracing-futures) \
bundled(rust-crate:tracing-subscriber) \
bundled(rust-crate:try-lock) \
bundled(rust-crate:typenum) \
bundled(rust-crate:unicase) \
bundled(rust-crate:unicode-bidi) \
bundled(rust-crate:unicode-ident) \
bundled(rust-crate:unicode-normalization) \
bundled(rust-crate:unicode-segmentation) \
bundled(rust-crate:unicode-width) \
bundled(rust-crate:unicode-xid) \
bundled(rust-crate:url) \
bundled(rust-crate:uuid) \
bundled(rust-crate:vec_map) \
bundled(rust-crate:vergen) \
bundled(rust-crate:version_check) \
bundled(rust-crate:waker-fn) \
bundled(rust-crate:want) \
bundled(rust-crate:webbrowser) \
bundled(rust-crate:xdg) \
bundled(rust-crate:zbus) \
bundled(rust-crate:zbus_macros) \
bundled(rust-crate:zerocopy) \
bundled(rust-crate:zerocopy-derive) \
bundled(rust-crate:zvariant) \
bundled(rust-crate:zvariant_derive) \
spotifyd \
spotifyd(aarch-64)"
RDEPENDS:${PN} += "/bin/sh \
libasound.so.2()(64bit) \
libasound.so.2(ALSA_0.9)(64bit) \
libasound.so.2(ALSA_0.9.0rc4)(64bit) \
libc.so.6(GLIBC_2.34)(64bit) \
libcrypto.so.3()(64bit) \
libcrypto.so.3(OPENSSL_3.0.0)(64bit) \
libdbus-1.so.3()(64bit) \
libdbus-1.so.3(LIBDBUS_1_3)(64bit) \
libgcc_s.so.1()(64bit) \
libgcc_s.so.1(GCC_3.0)(64bit) \
libgcc_s.so.1(GCC_3.3)(64bit) \
libgcc_s.so.1(GCC_4.2.0)(64bit) \
libm.so.6()(64bit) \
libm.so.6(GLIBC_2.17)(64bit) \
libm.so.6(GLIBC_2.27)(64bit) \
libm.so.6(GLIBC_2.29)(64bit) \
libpulse-simple.so.0()(64bit) \
libpulse-simple.so.0(PULSE_0)(64bit) \
libpulse.so.0()(64bit) \
libpulse.so.0(PULSE_0)(64bit) \
libssl.so.3()(64bit) \
libssl.so.3(OPENSSL_3.0.0)(64bit)"

inherit rpm
