SUMMARY = "HTML formatted API documention for Log for C++"
DESCRIPTION = "The log4cpp-doc package contains HTML formatted API documention generated by \
the popular doxygen documentation generation tool."
LICENSE = "LGPL-2.1-only"

PV = "1.1.3"

RPM_NAME = "log4cpp-doc-1.1.3-2.19.noarch.rpm"
RPM_HASH = "acc9f3e3ec331a89fd05d6f6043f5ac97570f6e1da6fb19eb91cf45dffdb5c0fa031311820b9c6f44c758c4472b693221e7457b9d647076fbe6ae5bee2d40f1a"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "log4cpp-doc"

RDEPENDS:${PN} += ""

inherit rpm
