SUMMARY = "Romanian hyphenation patterns"
DESCRIPTION = "Hyphenation patterns for Romanian in T1/EC and UTF-8 encodings. \
The UTF-8 patterns use U+0219 for the character 's with comma \
accent' and U+021B for 't with comma accent', but we may \
consider using U+015F and U+0163 as well in the future. \
Generated by PatGen2-output hyphen-level 9."
LICENSE = "LPPL-1.0"

PV = "2023.209.svn58652"

RPM_NAME = "texlive-hyphen-romanian-2023.209.svn58652-54.1.noarch.rpm"
RPM_HASH = "9ca0338936a98783a082687076356cd010b2c0b3c6da8cbc0f7247690a1a7c398f073e0d3b74fe6e8fc3ee61982b265f6bcde27a8825b925fb52d860a79e1795"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-hyph-ro.ec.tex \
tex-hyph-ro.tex \
tex-loadhyph-ro.tex \
texlive-hyphen-romanian"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-language.dat \
tex-language.dat.lua \
tex-language.def \
texlive \
texlive-filesystem \
texlive-hyph-utf8 \
texlive-hyphen-base \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
