SUMMARY = "Romanian hyphenation patterns"
DESCRIPTION = "Hyphenation patterns for Romanian in T1/EC and UTF-8 encodings. \
The UTF-8 patterns use U+0219 for the character 's with comma \
accent' and U+021B for 't with comma accent', but we may \
consider using U+015F and U+0163 as well in the future. \
Generated by PatGen2-output hyphen-level 9."
LICENSE = "LPPL-1.0"

PV = "2023.208.svn58652"

RPM_NAME = "texlive-hyphen-romanian-2023.208.svn58652-53.1.noarch.rpm"
RPM_HASH = "9e8cfa29c703b40683ce1ff522dcdafa64d91afeadca2424d4733586467303c3099f6cd82cd98c14d28a81fb172090e530fc32b85c470fbdc46c1119f56c5cb2"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-hyph-ro.ec.tex \
tex-hyph-ro.tex \
tex-loadhyph-ro.tex \
texlive-hyphen-romanian"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-language.dat \
tex-language.dat.lua \
tex-language.def \
texlive \
texlive-filesystem \
texlive-hyph-utf8 \
texlive-hyphen-base \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
