SUMMARY = "Development files for opam"
DESCRIPTION = "The opam-devel package contains libraries and signature files for \
developing applications that use opam."
LICENSE = "LGPL-2.1-only-WITH-OCaml-LGPL-linking-exception"

PV = "2.1.5"

RPM_NAME = "opam-devel-2.1.5-1.1.aarch64.rpm"
RPM_HASH = "15471224e074daff40130fa48231fdbbac9528da906b33e7ee82f4f2a5d66052b30c97ba8c3d8956d939ce9d221bcb8e841e5d349957f31848c04ef504014c5f"

RPROVIDES:${PN} += "ocaml-Opam-admin-top \
ocaml-OpamACL \
ocaml-OpamAction \
ocaml-OpamActionGraph \
ocaml-OpamAdminCheck \
ocaml-OpamAdminCommand \
ocaml-OpamAdminRepoUpgrade \
ocaml-OpamArg \
ocaml-OpamArgTools \
ocaml-OpamAuxCommands \
ocaml-OpamBase64Compat \
ocaml-OpamBuiltin0install \
ocaml-OpamBuiltinMccs \
ocaml-OpamBuiltinZ3 \
ocaml-OpamCLIVersion \
ocaml-OpamCached \
ocaml-OpamCliMain \
ocaml-OpamClient \
ocaml-OpamClientConfig \
ocaml-OpamCommands \
ocaml-OpamCompat \
ocaml-OpamConfigCommand \
ocaml-OpamConsole \
ocaml-OpamCoreConfig \
ocaml-OpamCudf \
ocaml-OpamCudfSolver \
ocaml-OpamCudfSolverSig \
ocaml-OpamDarcs \
ocaml-OpamDirTrack \
ocaml-OpamDoseCompat \
ocaml-OpamDownload \
ocaml-OpamEnv \
ocaml-OpamFile \
ocaml-OpamFileTools \
ocaml-OpamFilename \
ocaml-OpamFilter \
ocaml-OpamFormat \
ocaml-OpamFormatConfig \
ocaml-OpamFormatUpgrade \
ocaml-OpamFormula \
ocaml-OpamGit \
ocaml-OpamGitVersion \
ocaml-OpamGlobalState \
ocaml-OpamHTTP \
ocaml-OpamHash \
ocaml-OpamHg \
ocaml-OpamInitDefaults \
ocaml-OpamInterpLexer \
ocaml-OpamJson \
ocaml-OpamLineLexer \
ocaml-OpamListCommand \
ocaml-OpamLocal \
ocaml-OpamLockCommand \
ocaml-OpamPackage \
ocaml-OpamPackageVar \
ocaml-OpamParallel \
ocaml-OpamPath \
ocaml-OpamPinCommand \
ocaml-OpamPinned \
ocaml-OpamPp \
ocaml-OpamProcess \
ocaml-OpamRepository \
ocaml-OpamRepositoryBackend \
ocaml-OpamRepositoryCommand \
ocaml-OpamRepositoryConfig \
ocaml-OpamRepositoryName \
ocaml-OpamRepositoryPath \
ocaml-OpamRepositoryState \
ocaml-OpamSHA \
ocaml-OpamScript \
ocaml-OpamSolution \
ocaml-OpamSolver \
ocaml-OpamSolverConfig \
ocaml-OpamSpdxList \
ocaml-OpamStateConfig \
ocaml-OpamStateTypes \
ocaml-OpamStd \
ocaml-OpamStubs \
ocaml-OpamStubsTypes \
ocaml-OpamSwitch \
ocaml-OpamSwitchAction \
ocaml-OpamSwitchCommand \
ocaml-OpamSwitchState \
ocaml-OpamSysInteract \
ocaml-OpamSysPkg \
ocaml-OpamSysPoll \
ocaml-OpamSystem \
ocaml-OpamTypes \
ocaml-OpamTypesBase \
ocaml-OpamUpdate \
ocaml-OpamUrl \
ocaml-OpamVCS \
ocaml-OpamVariable \
ocaml-OpamVersion \
ocaml-OpamVersionCompare \
ocamlfind-opam \
ocamlfind-opam-admin \
ocamlfind-opam-admin.top \
ocamlfind-opam-client \
ocamlfind-opam-core \
ocamlfind-opam-format \
ocamlfind-opam-installer \
ocamlfind-opam-repository \
ocamlfind-opam-solver \
ocamlfind-opam-state \
ocamlx-Opam-admin-top \
ocamlx-OpamACL \
ocamlx-OpamAction \
ocamlx-OpamActionGraph \
ocamlx-OpamAdminCheck \
ocamlx-OpamAdminCommand \
ocamlx-OpamAdminRepoUpgrade \
ocamlx-OpamArg \
ocamlx-OpamArgTools \
ocamlx-OpamAuxCommands \
ocamlx-OpamBase64Compat \
ocamlx-OpamBuiltin0install \
ocamlx-OpamBuiltinMccs \
ocamlx-OpamBuiltinZ3 \
ocamlx-OpamCLIVersion \
ocamlx-OpamCached \
ocamlx-OpamCliMain \
ocamlx-OpamClient \
ocamlx-OpamClientConfig \
ocamlx-OpamCommands \
ocamlx-OpamCompat \
ocamlx-OpamConfigCommand \
ocamlx-OpamConsole \
ocamlx-OpamCoreConfig \
ocamlx-OpamCudf \
ocamlx-OpamCudfSolver \
ocamlx-OpamCudfSolverSig \
ocamlx-OpamDarcs \
ocamlx-OpamDirTrack \
ocamlx-OpamDoseCompat \
ocamlx-OpamDownload \
ocamlx-OpamEnv \
ocamlx-OpamFile \
ocamlx-OpamFileTools \
ocamlx-OpamFilename \
ocamlx-OpamFilter \
ocamlx-OpamFormat \
ocamlx-OpamFormatConfig \
ocamlx-OpamFormatUpgrade \
ocamlx-OpamFormula \
ocamlx-OpamGit \
ocamlx-OpamGitVersion \
ocamlx-OpamGlobalState \
ocamlx-OpamHTTP \
ocamlx-OpamHash \
ocamlx-OpamHg \
ocamlx-OpamInitDefaults \
ocamlx-OpamInterpLexer \
ocamlx-OpamJson \
ocamlx-OpamLineLexer \
ocamlx-OpamListCommand \
ocamlx-OpamLocal \
ocamlx-OpamLockCommand \
ocamlx-OpamPackage \
ocamlx-OpamPackageVar \
ocamlx-OpamParallel \
ocamlx-OpamPath \
ocamlx-OpamPinCommand \
ocamlx-OpamPinned \
ocamlx-OpamPp \
ocamlx-OpamProcess \
ocamlx-OpamRepository \
ocamlx-OpamRepositoryBackend \
ocamlx-OpamRepositoryCommand \
ocamlx-OpamRepositoryConfig \
ocamlx-OpamRepositoryName \
ocamlx-OpamRepositoryPath \
ocamlx-OpamRepositoryState \
ocamlx-OpamSHA \
ocamlx-OpamScript \
ocamlx-OpamSolution \
ocamlx-OpamSolver \
ocamlx-OpamSolverConfig \
ocamlx-OpamSpdxList \
ocamlx-OpamStateConfig \
ocamlx-OpamStd \
ocamlx-OpamStubs \
ocamlx-OpamStubsTypes \
ocamlx-OpamSwitch \
ocamlx-OpamSwitchAction \
ocamlx-OpamSwitchCommand \
ocamlx-OpamSwitchState \
ocamlx-OpamSysInteract \
ocamlx-OpamSysPkg \
ocamlx-OpamSysPoll \
ocamlx-OpamSystem \
ocamlx-OpamTypesBase \
ocamlx-OpamUpdate \
ocamlx-OpamUrl \
ocamlx-OpamVCS \
ocamlx-OpamVariable \
ocamlx-OpamVersion \
ocamlx-OpamVersionCompare \
opam-devel"

RDEPENDS:${PN} += "ocaml-Base64 \
ocaml-Base64-- \
ocaml-CamlinternalFormatBasics \
ocaml-CamlinternalLazy \
ocaml-Cmdliner \
ocaml-Cudf \
ocaml-Cudf-conf \
ocaml-Cudf-parser \
ocaml-Cudf-printer \
ocaml-Cudf-types \
ocaml-Dose-algo \
ocaml-Dose-algo--Defaultgraphs \
ocaml-Dose-algo--Depsolver \
ocaml-Dose-algo--Diagnostic \
ocaml-Dose-common \
ocaml-Dose-common--CudfAdd \
ocaml-Dose-common--CudfSolver \
ocaml-Dose-common--Util \
ocaml-Enum \
ocaml-ExtArray \
ocaml-ExtBuffer \
ocaml-ExtBytes \
ocaml-ExtHashtbl \
ocaml-ExtLib \
ocaml-ExtList \
ocaml-ExtString \
ocaml-Graph \
ocaml-Graph-- \
ocaml-Graph--Builder \
ocaml-Graph--Components \
ocaml-Graph--Dot \
ocaml-Graph--Dot-ast \
ocaml-Graph--Gml \
ocaml-Graph--Graphml \
ocaml-Graph--Graphviz \
ocaml-Graph--Imperative \
ocaml-Graph--Oper \
ocaml-Graph--Sig \
ocaml-Graph--Topological \
ocaml-Graph--Traverse \
ocaml-IO \
ocaml-Mccs \
ocaml-OpamBaseParser \
ocaml-OpamLexer \
ocaml-OpamParser \
ocaml-OpamParserTypes \
ocaml-OpamPrinter \
ocaml-Option \
ocaml-Re \
ocaml-Re-- \
ocaml-Re--Automata \
ocaml-Re--Category \
ocaml-Re--Core \
ocaml-Re--Cset \
ocaml-Re--Glob \
ocaml-Re--Group \
ocaml-Re--Pcre \
ocaml-Re--Pmark \
ocaml-Std \
ocaml-Stdlib \
ocaml-Stdlib--Array \
ocaml-Stdlib--Bigarray \
ocaml-Stdlib--Buffer \
ocaml-Stdlib--Bytes \
ocaml-Stdlib--Char \
ocaml-Stdlib--Complex \
ocaml-Stdlib--Digest \
ocaml-Stdlib--Either \
ocaml-Stdlib--Filename \
ocaml-Stdlib--Format \
ocaml-Stdlib--Hashtbl \
ocaml-Stdlib--Int32 \
ocaml-Stdlib--Int64 \
ocaml-Stdlib--Lazy \
ocaml-Stdlib--Lexing \
ocaml-Stdlib--List \
ocaml-Stdlib--Map \
ocaml-Stdlib--Marshal \
ocaml-Stdlib--Nativeint \
ocaml-Stdlib--Obj \
ocaml-Stdlib--Parsing \
ocaml-Stdlib--Printexc \
ocaml-Stdlib--Printf \
ocaml-Stdlib--Queue \
ocaml-Stdlib--Random \
ocaml-Stdlib--Result \
ocaml-Stdlib--Scanf \
ocaml-Stdlib--Seq \
ocaml-Stdlib--Set \
ocaml-Stdlib--String \
ocaml-Stdlib--Sys \
ocaml-Stdlib--Uchar \
ocaml-Unix \
ocamlfind-base64 \
ocamlfind-bigarray \
ocamlfind-cmdliner \
ocamlfind-compiler-libs.toplevel \
ocamlfind-cudf \
ocamlfind-dose3.algo \
ocamlfind-mccs \
ocamlfind-ocamlgraph \
ocamlfind-opam-file-format \
ocamlfind-re \
ocamlfind-unix \
ocamlx-Base64 \
ocamlx-CamlinternalLazy \
ocamlx-Cmdliner \
ocamlx-Cudf \
ocamlx-Cudf-parser \
ocamlx-Cudf-printer \
ocamlx-Dose-algo--Defaultgraphs \
ocamlx-Dose-algo--Depsolver \
ocamlx-Dose-algo--Diagnostic \
ocamlx-Dose-common--CudfAdd \
ocamlx-Dose-common--CudfSolver \
ocamlx-Graph--Components \
ocamlx-Graph--Graphviz \
ocamlx-Graph--Imperative \
ocamlx-Graph--Oper \
ocamlx-Graph--Topological \
ocamlx-Graph--Traverse \
ocamlx-Mccs \
ocamlx-OpamLexer \
ocamlx-OpamParser \
ocamlx-OpamPrinter \
ocamlx-Re \
ocamlx-Re--Glob \
ocamlx-Re--Pcre \
ocamlx-Stdlib \
ocamlx-Stdlib--Array \
ocamlx-Stdlib--Bigarray \
ocamlx-Stdlib--Buffer \
ocamlx-Stdlib--Bytes \
ocamlx-Stdlib--Char \
ocamlx-Stdlib--Digest \
ocamlx-Stdlib--Filename \
ocamlx-Stdlib--Format \
ocamlx-Stdlib--Hashtbl \
ocamlx-Stdlib--Int32 \
ocamlx-Stdlib--Int64 \
ocamlx-Stdlib--Lazy \
ocamlx-Stdlib--Lexing \
ocamlx-Stdlib--List \
ocamlx-Stdlib--Map \
ocamlx-Stdlib--Marshal \
ocamlx-Stdlib--Parsing \
ocamlx-Stdlib--Printexc \
ocamlx-Stdlib--Printf \
ocamlx-Stdlib--Queue \
ocamlx-Stdlib--Random \
ocamlx-Stdlib--Scanf \
ocamlx-Stdlib--Set \
ocamlx-Stdlib--String \
ocamlx-Stdlib--Sys \
ocamlx-Stdlib--Uchar \
ocamlx-Unix \
opam"

inherit rpm
