SUMMARY = "Documentation for poezio"
DESCRIPTION = "Documentation generated by the poezio package, but split out due to size."
LICENSE = "MIT"

PV = "0.14"

RPM_NAME = "poezio-doc-0.14-1.3.noarch.rpm"
RPM_HASH = "fa2ae6e31f09f9c6fffad17c46933a38f5b3246f97d5639a82653041965a76f95a26a4bad108313170ba34ca2f43810508bc914e01542ae1929cf9565308ccda"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "poezio-doc"
RDEPENDS:${PN} += ""

inherit rpm
