SUMMARY = "The Small Developer Kernel for KVM"
DESCRIPTION = "This kernel is intended for kernel developers to use in simple virtual \
machines.  It contains only the device drivers necessary to use a \
KVM virtual machine *without* device passthrough enabled.  Common \
local and network file systems are enabled.  All device mapper targets \
are enabled.  Only the network and graphics drivers for devices that qemu \
emulates are enabled.  Many subsystems enabled in the default kernel \
are entirely disabled.  This kernel is meant to be small and to build \
very quickly.  The configuration may change arbitrarily between builds. \
 \
 \
Source Timestamp: 2023-08-17 04:57:43 +0000 \
GIT Revision: 2a5b3f66898e9ecfa282f4399923c9546d3bc54d \
GIT Branch: stable"
LICENSE = "GPL-2.0-only"

PV = "6.4.11"

RPM_NAME = "kernel-kvmsmall-6.4.11-1.2.aarch64.rpm"
RPM_HASH = "a007e75f88b4d7fd92de24c87d8c3b58008e438ac34f85ece8ed645b68bba8c3365c0b756214dbaf1755bb68e3b038248ff19eb7e00ffe302b0f44edab78a827"

RPROVIDES:${PN} += "kernel \
kernel-base \
kernel-kvmsmall \
kernel-kvmsmall-6.4.11-1 \
kernel-kvmsmall-aarch64 \
kernel-kvmsmall-base-srchash-2a5b3f66898e9ecfa282f4399923c9546d3bc54d \
kernel-kvmsmall-srchash-2a5b3f66898e9ecfa282f4399923c9546d3bc54d \
kernel-srchash-2a5b3f66898e9ecfa282f4399923c9546d3bc54d \
kernel-uname-r \
kmod-8021q.ko \
kmod-8139cp.ko \
kmod-8139too.ko \
kmod-8250-base.ko \
kmod-8250-bcm2835aux.ko \
kmod-8250-bcm7271.ko \
kmod-8250-em.ko \
kmod-8250-mtk.ko \
kmod-8250-of.ko \
kmod-8250-pci.ko \
kmod-8250-pci1xxxx.ko \
kmod-8250-pericom.ko \
kmod-8250-tegra.ko \
kmod-8250.ko \
kmod-8255.ko \
kmod-88pg86x.ko \
kmod-9p.ko \
kmod-9pnet-fd.ko \
kmod-9pnet-virtio.ko \
kmod-9pnet.ko \
kmod-BusLogic.ko \
kmod-a53-pll.ko \
kmod-a7-pll.ko \
kmod-ac.ko \
kmod-ac100.ko \
kmod-acbel-fsg032.ko \
kmod-acpi-configfs.ko \
kmod-acpi-ipmi.ko \
kmod-acpi-mdio.ko \
kmod-acpi-tad.ko \
kmod-adiantum.ko \
kmod-adin.ko \
kmod-adin1100.ko \
kmod-adm1177.ko \
kmod-adm1266.ko \
kmod-adp8860-bl.ko \
kmod-adp8870-bl.ko \
kmod-adv7511.ko \
kmod-aead.ko \
kmod-aegis128.ko \
kmod-aer-inject.ko \
kmod-aes-arm64.ko \
kmod-aes-ce-blk.ko \
kmod-aes-ce-ccm.ko \
kmod-aes-ce-cipher.ko \
kmod-aes-generic.ko \
kmod-aes-neon-blk.ko \
kmod-aes-neon-bs.ko \
kmod-aes-ti.ko \
kmod-af-alg.ko \
kmod-af-key.ko \
kmod-af-packet-diag.ko \
kmod-af-packet.ko \
kmod-ah4.ko \
kmod-ah6.ko \
kmod-ahci-brcm.ko \
kmod-ahci-ceva.ko \
kmod-ahci-dwc.ko \
kmod-ahci-imx.ko \
kmod-ahci-mtk.ko \
kmod-ahci-mvebu.ko \
kmod-ahci-qoriq.ko \
kmod-ahci-seattle.ko \
kmod-ahci-sunxi.ko \
kmod-ahci-tegra.ko \
kmod-ahci-xgene.ko \
kmod-ahci.ko \
kmod-aht10.ko \
kmod-akcipher.ko \
kmod-al-mc-edac.ko \
kmod-algif-aead.ko \
kmod-algif-hash.ko \
kmod-algif-rng.ko \
kmod-algif-skcipher.ko \
kmod-alibaba-uncore-drw-pmu.ko \
kmod-amba-pl010.ko \
kmod-amba-pl011.ko \
kmod-amd8111e.ko \
kmod-amlogic-thermal.ko \
kmod-amt.ko \
kmod-analogix-anx6345.ko \
kmod-analogix-anx78xx.ko \
kmod-analogix-dp.ko \
kmod-ansi-cprng.ko \
kmod-anx7625.ko \
kmod-ao-cec-g12a.ko \
kmod-ao-cec.ko \
kmod-aoe.ko \
kmod-apbps2.ko \
kmod-apcs-msm8916.ko \
kmod-apcs-msm8996.ko \
kmod-apcs-sdx55.ko \
kmod-apple-admac.ko \
kmod-apple-dart.ko \
kmod-apple-mailbox.ko \
kmod-apple-mfi-fastcharge.ko \
kmod-apple-rtkit.ko \
kmod-apple-sart.ko \
kmod-apple-soc-cpufreq.ko \
kmod-apple-wdt.ko \
kmod-apr.ko \
kmod-apss-ipq-pll.ko \
kmod-apss-ipq6018.ko \
kmod-aquacomputer-d5next.ko \
kmod-arcxcnn-bl.ko \
kmod-aria-generic.ko \
kmod-arm-cci.ko \
kmod-arm-ccn.ko \
kmod-arm-cmn.ko \
kmod-arm-dmc620-pmu.ko \
kmod-arm-dsu-pmu.ko \
kmod-arm-mhuv2.ko \
kmod-arm-scpi.ko \
kmod-arm-smc-wdt.ko \
kmod-arm-smccc-trng.ko \
kmod-arm-smmu-v3.ko \
kmod-arm-smmu.ko \
kmod-arm-smmuv3-pmu.ko \
kmod-arm-spe-pmu.ko \
kmod-arm64-reloc-test.ko \
kmod-armada-37xx-cpufreq.ko \
kmod-armada-37xx-rwtm-mailbox.ko \
kmod-armada-37xx-wdt.ko \
kmod-armada-8k-cpufreq.ko \
kmod-armada-thermal.ko \
kmod-arp-tables.ko \
kmod-arpt-mangle.ko \
kmod-arptable-filter.ko \
kmod-as370-hwmon.ko \
kmod-asn1-decoder.ko \
kmod-asn1-encoder.ko \
kmod-async-memcpy.ko \
kmod-async-pq.ko \
kmod-async-raid6-recov.ko \
kmod-async-tx.ko \
kmod-async-xor.ko \
kmod-at803x.ko \
kmod-ata-piix.ko \
kmod-atc260x-core.ko \
kmod-atc260x-i2c.ko \
kmod-atc260x-onkey.ko \
kmod-atc260x-poweroff.ko \
kmod-atc260x-regulator.ko \
kmod-atkbd.ko \
kmod-atmel-captouch.ko \
kmod-atmel-hlcdc.ko \
kmod-auth-rpcgss.ko \
kmod-authenc.ko \
kmod-authencesn.ko \
kmod-autofs4.ko \
kmod-auxadc-thermal.ko \
kmod-axg-aoclk.ko \
kmod-axg-audio.ko \
kmod-axg.ko \
kmod-axi-fan-control.ko \
kmod-axp20x-pek.ko \
kmod-axp20x-regulator.ko \
kmod-axp20x-rsb.ko \
kmod-axp20x.ko \
kmod-ba431-rng.ko \
kmod-backlight.ko \
kmod-bam-dma.ko \
kmod-bareudp.ko \
kmod-battery.ko \
kmod-bcache.ko \
kmod-bcm-flexrm-mailbox.ko \
kmod-bcm-pdc-mailbox.ko \
kmod-bcm-phy-lib.ko \
kmod-bcm-sba-raid.ko \
kmod-bcm-vk.ko \
kmod-bcm2711-thermal.ko \
kmod-bcm2835-dma.ko \
kmod-bcm2835-mailbox.ko \
kmod-bcm2835-rng.ko \
kmod-bcm2835-thermal.ko \
kmod-bcm2835-wdt.ko \
kmod-bcm54140.ko \
kmod-bcm63xx-uart.ko \
kmod-bcm7038-wdt.ko \
kmod-bcm84881.ko \
kmod-bd6107.ko \
kmod-bd71815-regulator.ko \
kmod-bd71828-regulator.ko \
kmod-bd718x7-regulator.ko \
kmod-bd9571mwv-regulator.ko \
kmod-bd9571mwv.ko \
kmod-bd9576-regulator.ko \
kmod-bd9576-wdt.ko \
kmod-bd99954-charger.ko \
kmod-bdc.ko \
kmod-bel-pfe.ko \
kmod-bfq.ko \
kmod-binfmt-misc.ko \
kmod-binfmt-script.ko \
kmod-blake2b-generic.ko \
kmod-blocklayoutdriver.ko \
kmod-blowfish-common.ko \
kmod-blowfish-generic.ko \
kmod-bochs.ko \
kmod-bonding.ko \
kmod-bpa-rs600.ko \
kmod-bpfilter.ko \
kmod-bq24190-charger.ko \
kmod-bq24257-charger.ko \
kmod-bq24735-charger.ko \
kmod-bq2515x-charger.ko \
kmod-bq256xx-charger.ko \
kmod-bq25890-charger.ko \
kmod-bq25980-charger.ko \
kmod-br-netfilter.ko \
kmod-brcmstb-avs-cpufreq.ko \
kmod-brcmstb-dpfe.ko \
kmod-brcmstb-gisb.ko \
kmod-brcmstb-memc.ko \
kmod-brcmstb-thermal.ko \
kmod-brcmstb-usb-pinmap.ko \
kmod-brd.ko \
kmod-bridge.ko \
kmod-bsd-comp.ko \
kmod-bsg.ko \
kmod-btrfs.ko \
kmod-button.ko \
kmod-cachefiles.ko \
kmod-cadence-wdt.ko \
kmod-camcc-sc7180.ko \
kmod-camcc-sc7280.ko \
kmod-camcc-sdm845.ko \
kmod-camcc-sm6350.ko \
kmod-camcc-sm8250.ko \
kmod-camcc-sm8450.ko \
kmod-camellia-generic.ko \
kmod-cap11xx.ko \
kmod-capsule-loader.ko \
kmod-cast-common.ko \
kmod-cast5-generic.ko \
kmod-cast6-generic.ko \
kmod-cavium-rng-vf.ko \
kmod-cavium-rng.ko \
kmod-cbc.ko \
kmod-ccm.ko \
kmod-cctrng.ko \
kmod-cdc-acm.ko \
kmod-cdns-dphy-rx.ko \
kmod-cdns-dphy.ko \
kmod-cdns-dsi.ko \
kmod-cdns-mhdp8546.ko \
kmod-cdns-usb-common.ko \
kmod-cdns3-imx.ko \
kmod-cdns3-pci-wrap.ko \
kmod-cdns3.ko \
kmod-cdnsp-udc-pci.ko \
kmod-cdrom.ko \
kmod-cdx-controller.ko \
kmod-cec-gpio.ko \
kmod-cec.ko \
kmod-ceph.ko \
kmod-cfb.ko \
kmod-cfbcopyarea.ko \
kmod-cfbfillrect.ko \
kmod-cfbimgblt.ko \
kmod-ch.ko \
kmod-ch7322.ko \
kmod-chacha-generic.ko \
kmod-chacha-neon.ko \
kmod-chacha20poly1305.ko \
kmod-chipone-icn6211.ko \
kmod-chrontel-ch7033.ko \
kmod-ci-hdrc-imx.ko \
kmod-ci-hdrc-msm.ko \
kmod-ci-hdrc-pci.ko \
kmod-ci-hdrc-tegra.ko \
kmod-ci-hdrc-usb2.ko \
kmod-ci-hdrc.ko \
kmod-cifs-arc4.ko \
kmod-cifs-md4.ko \
kmod-cifs.ko \
kmod-cirrus.ko \
kmod-clk-apmixed.ko \
kmod-clk-apple-nco.ko \
kmod-clk-axi-clkgen.ko \
kmod-clk-bcm2711-dvp.ko \
kmod-clk-bd718x7.ko \
kmod-clk-cbf-8996.ko \
kmod-clk-cdce706.ko \
kmod-clk-cdce925.ko \
kmod-clk-cpu-8996.ko \
kmod-clk-cpu-dyndiv.ko \
kmod-clk-cpumux.ko \
kmod-clk-dualdiv.ko \
kmod-clk-exynos-audss.ko \
kmod-clk-exynos-clkout.ko \
kmod-clk-fsl-flexspi.ko \
kmod-clk-gate.ko \
kmod-clk-hi3519.ko \
kmod-clk-hi655x.ko \
kmod-clk-imx-lpcg-scu.ko \
kmod-clk-imx-scu.ko \
kmod-clk-imx8mm.ko \
kmod-clk-imx8mn.ko \
kmod-clk-imx8mp-audiomix.ko \
kmod-clk-imx8mp.ko \
kmod-clk-imx8mq.ko \
kmod-clk-imx8ulp.ko \
kmod-clk-imx93.ko \
kmod-clk-lochnagar.ko \
kmod-clk-max77686.ko \
kmod-clk-max9485.ko \
kmod-clk-mpll.ko \
kmod-clk-mt2712-apmixedsys.ko \
kmod-clk-mt2712-bdp.ko \
kmod-clk-mt2712-img.ko \
kmod-clk-mt2712-jpgdec.ko \
kmod-clk-mt2712-mfg.ko \
kmod-clk-mt2712-mm.ko \
kmod-clk-mt2712-vdec.ko \
kmod-clk-mt2712-venc.ko \
kmod-clk-mt2712.ko \
kmod-clk-mt6765-audio.ko \
kmod-clk-mt6765-cam.ko \
kmod-clk-mt6765-img.ko \
kmod-clk-mt6765-mipi0a.ko \
kmod-clk-mt6765-mm.ko \
kmod-clk-mt6765-vcodec.ko \
kmod-clk-mt6765.ko \
kmod-clk-mt6779-aud.ko \
kmod-clk-mt6779-cam.ko \
kmod-clk-mt6779-img.ko \
kmod-clk-mt6779-ipe.ko \
kmod-clk-mt6779-mfg.ko \
kmod-clk-mt6779-mm.ko \
kmod-clk-mt6779-vdec.ko \
kmod-clk-mt6779-venc.ko \
kmod-clk-mt6779.ko \
kmod-clk-mt6795-apmixedsys.ko \
kmod-clk-mt6795-infracfg.ko \
kmod-clk-mt6795-mfg.ko \
kmod-clk-mt6795-mm.ko \
kmod-clk-mt6795-pericfg.ko \
kmod-clk-mt6795-topckgen.ko \
kmod-clk-mt6795-vdecsys.ko \
kmod-clk-mt6795-vencsys.ko \
kmod-clk-mt6797-img.ko \
kmod-clk-mt6797-mm.ko \
kmod-clk-mt6797-vdec.ko \
kmod-clk-mt6797-venc.ko \
kmod-clk-mt6797.ko \
kmod-clk-mt7622-apmixedsys.ko \
kmod-clk-mt7622-aud.ko \
kmod-clk-mt7622-eth.ko \
kmod-clk-mt7622-hif.ko \
kmod-clk-mt7622-infracfg.ko \
kmod-clk-mt7622.ko \
kmod-clk-mt7981-apmixed.ko \
kmod-clk-mt7981-eth.ko \
kmod-clk-mt7981-infracfg.ko \
kmod-clk-mt7981-topckgen.ko \
kmod-clk-mt7986-apmixed.ko \
kmod-clk-mt7986-eth.ko \
kmod-clk-mt7986-infracfg.ko \
kmod-clk-mt7986-topckgen.ko \
kmod-clk-mt8167-apmixedsys.ko \
kmod-clk-mt8167-aud.ko \
kmod-clk-mt8167-img.ko \
kmod-clk-mt8167-mfgcfg.ko \
kmod-clk-mt8167-mm.ko \
kmod-clk-mt8167-vdec.ko \
kmod-clk-mt8167.ko \
kmod-clk-mt8173-apmixedsys.ko \
kmod-clk-mt8173-img.ko \
kmod-clk-mt8173-infracfg.ko \
kmod-clk-mt8173-mm.ko \
kmod-clk-mt8173-pericfg.ko \
kmod-clk-mt8173-topckgen.ko \
kmod-clk-mt8173-vdecsys.ko \
kmod-clk-mt8173-vencsys.ko \
kmod-clk-mt8183-apmixedsys.ko \
kmod-clk-mt8183-audio.ko \
kmod-clk-mt8183-cam.ko \
kmod-clk-mt8183-img.ko \
kmod-clk-mt8183-ipu-adl.ko \
kmod-clk-mt8183-ipu-conn.ko \
kmod-clk-mt8183-ipu0.ko \
kmod-clk-mt8183-ipu1.ko \
kmod-clk-mt8183-mfgcfg.ko \
kmod-clk-mt8183-mm.ko \
kmod-clk-mt8183-vdec.ko \
kmod-clk-mt8183-venc.ko \
kmod-clk-mt8183.ko \
kmod-clk-mt8186-apmixedsys.ko \
kmod-clk-mt8186-cam.ko \
kmod-clk-mt8186-img.ko \
kmod-clk-mt8186-imp-iic-wrap.ko \
kmod-clk-mt8186-infra-ao.ko \
kmod-clk-mt8186-ipe.ko \
kmod-clk-mt8186-mcu.ko \
kmod-clk-mt8186-mdp.ko \
kmod-clk-mt8186-mfg.ko \
kmod-clk-mt8186-mm.ko \
kmod-clk-mt8186-topckgen.ko \
kmod-clk-mt8186-vdec.ko \
kmod-clk-mt8186-venc.ko \
kmod-clk-mt8186-wpe.ko \
kmod-clk-mt8188-adsp-audio26m.ko \
kmod-clk-mt8188-apmixedsys.ko \
kmod-clk-mt8188-cam.ko \
kmod-clk-mt8188-ccu.ko \
kmod-clk-mt8188-img.ko \
kmod-clk-mt8188-imp-iic-wrap.ko \
kmod-clk-mt8188-infra-ao.ko \
kmod-clk-mt8188-ipe.ko \
kmod-clk-mt8188-mfg.ko \
kmod-clk-mt8188-peri-ao.ko \
kmod-clk-mt8188-topckgen.ko \
kmod-clk-mt8188-vdec.ko \
kmod-clk-mt8188-vdo0.ko \
kmod-clk-mt8188-vdo1.ko \
kmod-clk-mt8188-venc.ko \
kmod-clk-mt8188-vpp0.ko \
kmod-clk-mt8188-vpp1.ko \
kmod-clk-mt8188-wpe.ko \
kmod-clk-mt8192-apmixedsys.ko \
kmod-clk-mt8192-aud.ko \
kmod-clk-mt8192-cam.ko \
kmod-clk-mt8192-img.ko \
kmod-clk-mt8192-imp-iic-wrap.ko \
kmod-clk-mt8192-ipe.ko \
kmod-clk-mt8192-mdp.ko \
kmod-clk-mt8192-mfg.ko \
kmod-clk-mt8192-mm.ko \
kmod-clk-mt8192-msdc.ko \
kmod-clk-mt8192-scp-adsp.ko \
kmod-clk-mt8192-vdec.ko \
kmod-clk-mt8192-venc.ko \
kmod-clk-mt8192.ko \
kmod-clk-mt8195-apmixedsys.ko \
kmod-clk-mt8195-apusys-pll.ko \
kmod-clk-mt8195-cam.ko \
kmod-clk-mt8195-ccu.ko \
kmod-clk-mt8195-img.ko \
kmod-clk-mt8195-imp-iic-wrap.ko \
kmod-clk-mt8195-infra-ao.ko \
kmod-clk-mt8195-ipe.ko \
kmod-clk-mt8195-mfg.ko \
kmod-clk-mt8195-peri-ao.ko \
kmod-clk-mt8195-scp-adsp.ko \
kmod-clk-mt8195-topckgen.ko \
kmod-clk-mt8195-vdec.ko \
kmod-clk-mt8195-vdo0.ko \
kmod-clk-mt8195-vdo1.ko \
kmod-clk-mt8195-venc.ko \
kmod-clk-mt8195-vpp0.ko \
kmod-clk-mt8195-vpp1.ko \
kmod-clk-mt8195-wpe.ko \
kmod-clk-mt8365-apmixedsys.ko \
kmod-clk-mt8365-apu.ko \
kmod-clk-mt8365-cam.ko \
kmod-clk-mt8365-mfg.ko \
kmod-clk-mt8365-mm.ko \
kmod-clk-mt8365-vdec.ko \
kmod-clk-mt8365-venc.ko \
kmod-clk-mt8365.ko \
kmod-clk-mt8516-apmixedsys.ko \
kmod-clk-mt8516-aud.ko \
kmod-clk-mt8516.ko \
kmod-clk-mtk.ko \
kmod-clk-mux.ko \
kmod-clk-phase.ko \
kmod-clk-pll.ko \
kmod-clk-plldig.ko \
kmod-clk-pwm.ko \
kmod-clk-qcom.ko \
kmod-clk-raspberrypi.ko \
kmod-clk-regmap.ko \
kmod-clk-renesas-pcie.ko \
kmod-clk-rk808.ko \
kmod-clk-rpm.ko \
kmod-clk-rpmh.ko \
kmod-clk-scmi.ko \
kmod-clk-scpi.ko \
kmod-clk-si514.ko \
kmod-clk-si521xx.ko \
kmod-clk-si544.ko \
kmod-clk-smd-rpm.ko \
kmod-clk-sprd.ko \
kmod-clk-versaclock5.ko \
kmod-clk-versaclock7.ko \
kmod-clk-vexpress-osc.ko \
kmod-clk-xlnx-clock-wizard.ko \
kmod-cmac.ko \
kmod-cmd-db.ko \
kmod-cn.ko \
kmod-cn10k-rng.ko \
kmod-comedi-8255.ko \
kmod-comedi-usb.ko \
kmod-comedi.ko \
kmod-configfs.ko \
kmod-configs.ko \
kmod-cordic.ko \
kmod-coresight-catu.ko \
kmod-coresight-cpu-debug.ko \
kmod-coresight-cti.ko \
kmod-coresight-etb10.ko \
kmod-coresight-etm4x.ko \
kmod-coresight-funnel.ko \
kmod-coresight-replicator.ko \
kmod-coresight-stm.ko \
kmod-coresight-tmc.ko \
kmod-coresight-tpda.ko \
kmod-coresight-tpdm.ko \
kmod-coresight-tpiu.ko \
kmod-coresight-trbe.ko \
kmod-coresight.ko \
kmod-corsair-cpro.ko \
kmod-corsair-psu.ko \
kmod-cortina.ko \
kmod-cppc-cpufreq.ko \
kmod-cpr.ko \
kmod-cpufreq-conservative.ko \
kmod-cpufreq-dt.ko \
kmod-cpufreq-ondemand.ko \
kmod-cpufreq-performance.ko \
kmod-cpufreq-powersave.ko \
kmod-cpufreq-userspace.ko \
kmod-crasher.ko \
kmod-crc-ccitt.ko \
kmod-crc-itu-t.ko \
kmod-crc-t10dif.ko \
kmod-crc16.ko \
kmod-crc32-generic.ko \
kmod-crc32.ko \
kmod-crc32c-generic.ko \
kmod-crc4.ko \
kmod-crc64-rocksoft-generic.ko \
kmod-crc64-rocksoft.ko \
kmod-crc64.ko \
kmod-crc7.ko \
kmod-crc8.ko \
kmod-crct10dif-ce.ko \
kmod-crct10dif-common.ko \
kmod-crct10dif-generic.ko \
kmod-crg-hi3798cv200.ko \
kmod-cryptd.ko \
kmod-crypto-acompress.ko \
kmod-crypto-algapi.ko \
kmod-crypto-hash.ko \
kmod-crypto-null.ko \
kmod-crypto-user.ko \
kmod-crypto.ko \
kmod-cryptomgr.ko \
kmod-ctr.ko \
kmod-cts.ko \
kmod-curve25519-generic.ko \
kmod-cuse.ko \
kmod-custom-method.ko \
kmod-cw2015-battery.ko \
kmod-cxl-acpi.ko \
kmod-cxl-core.ko \
kmod-cxl-mem.ko \
kmod-cxl-pci.ko \
kmod-cxl-pmem.ko \
kmod-cxl-port.ko \
kmod-cypress-sf.ko \
kmod-da7280.ko \
kmod-da9121-regulator.ko \
kmod-dax-cxl.ko \
kmod-dax-hmem.ko \
kmod-dax-pmem.ko \
kmod-dax.ko \
kmod-deflate.ko \
kmod-delta-ahe50dc-fan.ko \
kmod-des-generic.ko \
kmod-device-dax.ko \
kmod-dh-generic.ko \
kmod-digsig.ko \
kmod-dispcc-qcm2290.ko \
kmod-dispcc-sc7180.ko \
kmod-dispcc-sc7280.ko \
kmod-dispcc-sc8280xp.ko \
kmod-dispcc-sdm845.ko \
kmod-dispcc-sm6115.ko \
kmod-dispcc-sm6125.ko \
kmod-dispcc-sm6350.ko \
kmod-dispcc-sm6375.ko \
kmod-dispcc-sm8250.ko \
kmod-dispcc-sm8450.ko \
kmod-dispcc-sm8550.ko \
kmod-display-connector.ko \
kmod-dlink-dir685-touchkeys.ko \
kmod-dlm.ko \
kmod-dm-bio-prison.ko \
kmod-dm-bufio.ko \
kmod-dm-cache-smq.ko \
kmod-dm-cache.ko \
kmod-dm-clone.ko \
kmod-dm-crypt.ko \
kmod-dm-delay.ko \
kmod-dm-dust.ko \
kmod-dm-ebs.ko \
kmod-dm-era.ko \
kmod-dm-flakey.ko \
kmod-dm-historical-service-time.ko \
kmod-dm-integrity.ko \
kmod-dm-io-affinity.ko \
kmod-dm-log-userspace.ko \
kmod-dm-log-writes.ko \
kmod-dm-log.ko \
kmod-dm-mirror.ko \
kmod-dm-mod.ko \
kmod-dm-multipath.ko \
kmod-dm-persistent-data.ko \
kmod-dm-queue-length.ko \
kmod-dm-raid.ko \
kmod-dm-region-hash.ko \
kmod-dm-round-robin.ko \
kmod-dm-service-time.ko \
kmod-dm-snapshot.ko \
kmod-dm-switch.ko \
kmod-dm-thin-pool.ko \
kmod-dm-unstripe.ko \
kmod-dm-verity.ko \
kmod-dm-writecache.ko \
kmod-dm-zero.ko \
kmod-dm-zoned.ko \
kmod-dma-axi-dmac.ko \
kmod-dmc520-edac.ko \
kmod-dmi-sysfs.ko \
kmod-dns-resolver.ko \
kmod-dp83869.ko \
kmod-dp83td510.ko \
kmod-dpaa2-console.ko \
kmod-dpaa2-qdma.ko \
kmod-dpdmai.ko \
kmod-dps920ab.ko \
kmod-drbd.ko \
kmod-drbg.ko \
kmod-drivetemp.ko \
kmod-drm-display-helper.ko \
kmod-drm-dma-helper.ko \
kmod-drm-dp-aux-bus.ko \
kmod-drm-kms-helper.ko \
kmod-drm-mipi-dsi.ko \
kmod-drm-panel-orientation-quirks.ko \
kmod-drm-shmem-helper.ko \
kmod-drm-ttm-helper.ko \
kmod-drm-vram-helper.ko \
kmod-drm.ko \
kmod-drop-monitor.ko \
kmod-drv260x.ko \
kmod-dt9812.ko \
kmod-dw-axi-dmac-platform.ko \
kmod-dw-dmac-core.ko \
kmod-dw-drm-dsi.ko \
kmod-dw-hdmi-cec.ko \
kmod-dw-hdmi.ko \
kmod-dw-mipi-dsi.ko \
kmod-dw-wdt.ko \
kmod-dw-xdata-pcie.ko \
kmod-dwc2-pci.ko \
kmod-dwc2.ko \
kmod-dwc3-exynos.ko \
kmod-dwc3-haps.ko \
kmod-dwc3-imx8mp.ko \
kmod-dwc3-meson-g12a.ko \
kmod-dwc3-of-simple.ko \
kmod-dwc3-pci.ko \
kmod-dwc3-qcom.ko \
kmod-dwc3-xilinx.ko \
kmod-dwc3.ko \
kmod-e100.ko \
kmod-e1000.ko \
kmod-e1000e.ko \
kmod-ebt-802-3.ko \
kmod-ebt-among.ko \
kmod-ebt-arp.ko \
kmod-ebt-arpreply.ko \
kmod-ebt-dnat.ko \
kmod-ebt-ip.ko \
kmod-ebt-ip6.ko \
kmod-ebt-limit.ko \
kmod-ebt-log.ko \
kmod-ebt-mark-m.ko \
kmod-ebt-mark.ko \
kmod-ebt-nflog.ko \
kmod-ebt-pkttype.ko \
kmod-ebt-redirect.ko \
kmod-ebt-snat.ko \
kmod-ebt-stp.ko \
kmod-ebt-vlan.ko \
kmod-ebtable-broute.ko \
kmod-ebtable-filter.ko \
kmod-ebtable-nat.ko \
kmod-ebtables.ko \
kmod-ecb.ko \
kmod-ecc.ko \
kmod-ecdh-generic.ko \
kmod-ecdsa-generic.ko \
kmod-echainiv.ko \
kmod-ecrdsa-generic.ko \
kmod-ecryptfs.ko \
kmod-edac-core.ko \
kmod-eeprom-93cx6.ko \
kmod-efi-pstore.ko \
kmod-efibc.ko \
kmod-efivarfs.ko \
kmod-ehci-exynos.ko \
kmod-ehci-hcd.ko \
kmod-ehci-npcm7xx.ko \
kmod-ehci-orion.ko \
kmod-ehci-pci.ko \
kmod-ehci-platform.ko \
kmod-emc2305.ko \
kmod-encrypted-keys.ko \
kmod-erofs.ko \
kmod-erst-dbg.ko \
kmod-esp4-offload.ko \
kmod-esp4.ko \
kmod-esp6-offload.ko \
kmod-esp6.ko \
kmod-essiv.ko \
kmod-ethoc.ko \
kmod-etnaviv.ko \
kmod-evdev.ko \
kmod-exfat.ko \
kmod-exportfs.ko \
kmod-ext4.ko \
kmod-extcon-core.ko \
kmod-extcon-gpio.ko \
kmod-extcon-max3355.ko \
kmod-extcon-ptn5150.ko \
kmod-extcon-qcom-spmi-misc.ko \
kmod-extcon-sm5502.ko \
kmod-exynos-bus.ko \
kmod-exynos-chipid.ko \
kmod-exynos-interconnect.ko \
kmod-exynos-lpass.ko \
kmod-exynos-nocp.ko \
kmod-exynos-ppmu.ko \
kmod-exynos-thermal.ko \
kmod-exynos-trng.ko \
kmod-exynos-usi.ko \
kmod-f2fs.ko \
kmod-failover.ko \
kmod-fan.ko \
kmod-fan53555.ko \
kmod-fan53880.ko \
kmod-fastrpc.ko \
kmod-fat.ko \
kmod-faulty.ko \
kmod-fb-sys-fops.ko \
kmod-fb.ko \
kmod-fcoe.ko \
kmod-fcrypt.ko \
kmod-fealnx.ko \
kmod-fec.ko \
kmod-ff-memless.ko \
kmod-ffa-module.ko \
kmod-firmware-class.ko \
kmod-fixed-phy.ko \
kmod-fixed.ko \
kmod-font.ko \
kmod-fou.ko \
kmod-fou6.ko \
kmod-fscache.ko \
kmod-fsl-dpa.ko \
kmod-fsl-dpaa-fman-port.ko \
kmod-fsl-dpaa-fman.ko \
kmod-fsl-dpaa-mac.ko \
kmod-fsl-dpaa2-eth.ko \
kmod-fsl-edma-common.ko \
kmod-fsl-edma.ko \
kmod-fsl-enetc-core.ko \
kmod-fsl-enetc-ierb.ko \
kmod-fsl-enetc-mdio.ko \
kmod-fsl-enetc-vf.ko \
kmod-fsl-enetc.ko \
kmod-fsl-imx8-ddr-perf.ko \
kmod-fsl-ldb.ko \
kmod-fsl-linflexuart.ko \
kmod-fsl-lpuart.ko \
kmod-fsl-mc-dpio.ko \
kmod-fsl-pq-mdio.ko \
kmod-fsl-qdma.ko \
kmod-fsp-3y.ko \
kmod-funcore.ko \
kmod-funeth.ko \
kmod-fuse.ko \
kmod-fwnode-mdio.ko \
kmod-g-acm-ms.ko \
kmod-g-cdc.ko \
kmod-g-dbgp.ko \
kmod-g-ether.ko \
kmod-g-ffs.ko \
kmod-g-hid.ko \
kmod-g-mass-storage.ko \
kmod-g-multi.ko \
kmod-g-ncm.ko \
kmod-g-printer.ko \
kmod-g-serial.ko \
kmod-g12a-aoclk.ko \
kmod-g12a.ko \
kmod-gadgetfs.ko \
kmod-garp.ko \
kmod-gateworks-gsc.ko \
kmod-gcc-ipq6018.ko \
kmod-gcc-mdm9607.ko \
kmod-gcc-msm8909.ko \
kmod-gcc-msm8916.ko \
kmod-gcc-msm8939.ko \
kmod-gcc-msm8953.ko \
kmod-gcc-msm8976.ko \
kmod-gcc-msm8994.ko \
kmod-gcc-msm8998.ko \
kmod-gcc-qcm2290.ko \
kmod-gcc-qcs404.ko \
kmod-gcc-qdu1000.ko \
kmod-gcc-sa8775p.ko \
kmod-gcc-sc7180.ko \
kmod-gcc-sc7280.ko \
kmod-gcc-sc8180x.ko \
kmod-gcc-sc8280xp.ko \
kmod-gcc-sdm660.ko \
kmod-gcc-sdm845.ko \
kmod-gcc-sdx55.ko \
kmod-gcc-sdx65.ko \
kmod-gcc-sm6115.ko \
kmod-gcc-sm6125.ko \
kmod-gcc-sm6350.ko \
kmod-gcc-sm6375.ko \
kmod-gcc-sm7150.ko \
kmod-gcc-sm8150.ko \
kmod-gcc-sm8250.ko \
kmod-gcc-sm8350.ko \
kmod-gcc-sm8450.ko \
kmod-gcc-sm8550.ko \
kmod-gcm.ko \
kmod-geniv.ko \
kmod-gf128mul.ko \
kmod-ghash-ce.ko \
kmod-ghash-generic.ko \
kmod-gianfar-driver.ko \
kmod-glob.ko \
kmod-gm12u320.ko \
kmod-governor-passive.ko \
kmod-governor-performance.ko \
kmod-governor-powersave.ko \
kmod-governor-simpleondemand.ko \
kmod-governor-userspace.ko \
kmod-gpi.ko \
kmod-gpio-74xx-mmio.ko \
kmod-gpio-aggregator.ko \
kmod-gpio-backlight.ko \
kmod-gpio-bd71815.ko \
kmod-gpio-bd71828.ko \
kmod-gpio-bd9571mwv.ko \
kmod-gpio-brcmstb.ko \
kmod-gpio-cadence.ko \
kmod-gpio-charger.ko \
kmod-gpio-decoder.ko \
kmod-gpio-dwapb.ko \
kmod-gpio-eic-sprd.ko \
kmod-gpio-fan.ko \
kmod-gpio-fxl6408.ko \
kmod-gpio-generic.ko \
kmod-gpio-grgpio.ko \
kmod-gpio-gw-pld.ko \
kmod-gpio-hisi.ko \
kmod-gpio-idio-16.ko \
kmod-gpio-keys-polled.ko \
kmod-gpio-keys.ko \
kmod-gpio-latch.ko \
kmod-gpio-lp873x.ko \
kmod-gpio-lp87565.ko \
kmod-gpio-max7300.ko \
kmod-gpio-max730x.ko \
kmod-gpio-max732x.ko \
kmod-gpio-max77620.ko \
kmod-gpio-max77650.ko \
kmod-gpio-mb86s7x.ko \
kmod-gpio-mockup.ko \
kmod-gpio-mouse.ko \
kmod-gpio-mxc.ko \
kmod-gpio-pca953x.ko \
kmod-gpio-pca9570.ko \
kmod-gpio-pcf857x.ko \
kmod-gpio-pci-idio-16.ko \
kmod-gpio-pcie-idio-24.ko \
kmod-gpio-pl061.ko \
kmod-gpio-raspberrypi-exp.ko \
kmod-gpio-rcar.ko \
kmod-gpio-regmap.ko \
kmod-gpio-regulator.ko \
kmod-gpio-rockchip.ko \
kmod-gpio-sim.ko \
kmod-gpio-sprd.ko \
kmod-gpio-syscon.ko \
kmod-gpio-tegra.ko \
kmod-gpio-tegra186.ko \
kmod-gpio-thunderx.ko \
kmod-gpio-tpic2810.ko \
kmod-gpio-vibra.ko \
kmod-gpio-virtio.ko \
kmod-gpio-visconti.ko \
kmod-gpio-wcd934x.ko \
kmod-gpio-xgene-sb.ko \
kmod-gpio-xgs-iproc.ko \
kmod-gpio-xilinx.ko \
kmod-gpio-xlp.ko \
kmod-gpio-zynq.ko \
kmod-gpio-zynqmp-modepin.ko \
kmod-gpu-sched.ko \
kmod-gpucc-msm8998.ko \
kmod-gpucc-sc7180.ko \
kmod-gpucc-sc7280.ko \
kmod-gpucc-sc8280xp.ko \
kmod-gpucc-sdm660.ko \
kmod-gpucc-sdm845.ko \
kmod-gpucc-sm6115.ko \
kmod-gpucc-sm6125.ko \
kmod-gpucc-sm6350.ko \
kmod-gpucc-sm6375.ko \
kmod-gpucc-sm8150.ko \
kmod-gpucc-sm8250.ko \
kmod-gpucc-sm8350.ko \
kmod-grace.ko \
kmod-gre.ko \
kmod-gsc-hwmon.ko \
kmod-gud.ko \
kmod-gxbb-aoclk.ko \
kmod-gxbb.ko \
kmod-hclge.ko \
kmod-hclgevf.ko \
kmod-hctr2.ko \
kmod-hdlcd.ko \
kmod-hdma-mgmt.ko \
kmod-hdma.ko \
kmod-hed.ko \
kmod-hfpll.ko \
kmod-hi3660-mailbox.ko \
kmod-hi6220-mailbox.ko \
kmod-hi6220-reset.ko \
kmod-hi6421-pmic-core.ko \
kmod-hi6421-regulator.ko \
kmod-hi6421v530-regulator.ko \
kmod-hi655x-pmic.ko \
kmod-hi655x-regulator.ko \
kmod-hibmc-drm.ko \
kmod-hid-asus.ko \
kmod-hid-bigbenff.ko \
kmod-hid-bpf.ko \
kmod-hid-corsair.ko \
kmod-hid-cp2112.ko \
kmod-hid-creative-sb0540.ko \
kmod-hid-elan.ko \
kmod-hid-evision.ko \
kmod-hid-ft260.ko \
kmod-hid-generic.ko \
kmod-hid-glorious.ko \
kmod-hid-gt683r.ko \
kmod-hid-ite.ko \
kmod-hid-jabra.ko \
kmod-hid-led.ko \
kmod-hid-letsketch.ko \
kmod-hid-lg-g15.ko \
kmod-hid-logitech-dj.ko \
kmod-hid-logitech-hidpp.ko \
kmod-hid-logitech.ko \
kmod-hid-mcp2221.ko \
kmod-hid-megaworld.ko \
kmod-hid-nintendo.ko \
kmod-hid-playstation.ko \
kmod-hid-pxrc.ko \
kmod-hid-razer.ko \
kmod-hid-semitek.ko \
kmod-hid-sigmamicro.ko \
kmod-hid-sony.ko \
kmod-hid-topre.ko \
kmod-hid-u2fzero.ko \
kmod-hid-vivaldi-common.ko \
kmod-hid-vivaldi.ko \
kmod-hid-vrc2.ko \
kmod-hid-wiimote.ko \
kmod-hid-xiaomi.ko \
kmod-hid.ko \
kmod-hip04-eth.ko \
kmod-hisi-dma.ko \
kmod-hisi-femac.ko \
kmod-hisi-hikey-usb.ko \
kmod-hisi-pcie-pmu.ko \
kmod-hisi-powerkey.ko \
kmod-hisi-ptt.ko \
kmod-hisi-rng.ko \
kmod-hisi-sas-main.ko \
kmod-hisi-sas-v1-hw.ko \
kmod-hisi-sas-v2-hw.ko \
kmod-hisi-sas-v3-hw.ko \
kmod-hisi-thermal.ko \
kmod-hisi-uncore-cpa-pmu.ko \
kmod-hisi-uncore-ddrc-pmu.ko \
kmod-hisi-uncore-hha-pmu.ko \
kmod-hisi-uncore-l3c-pmu.ko \
kmod-hisi-uncore-pa-pmu.ko \
kmod-hisi-uncore-pmu.ko \
kmod-hisi-uncore-sllc-pmu.ko \
kmod-hix5hd2-gmac.ko \
kmod-hmac.ko \
kmod-hnae.ko \
kmod-hnae3.ko \
kmod-hns-dsaf.ko \
kmod-hns-enet-drv.ko \
kmod-hns-mdio.ko \
kmod-hns3-pmu.ko \
kmod-hns3.ko \
kmod-host1x.ko \
kmod-hpwdt.ko \
kmod-hte-tegra194.ko \
kmod-hwmon.ko \
kmod-hwpoison-inject.ko \
kmod-i2c-algo-bit.ko \
kmod-i2c-altera.ko \
kmod-i2c-apple.ko \
kmod-i2c-bcm-iproc.ko \
kmod-i2c-bcm2835.ko \
kmod-i2c-brcmstb.ko \
kmod-i2c-cadence.ko \
kmod-i2c-cbus-gpio.ko \
kmod-i2c-core.ko \
kmod-i2c-cp2615.ko \
kmod-i2c-demux-pinctrl.ko \
kmod-i2c-gpio.ko \
kmod-i2c-hid-acpi.ko \
kmod-i2c-hid-of-elan.ko \
kmod-i2c-hid-of-goodix.ko \
kmod-i2c-hid-of.ko \
kmod-i2c-hid.ko \
kmod-i2c-hisi.ko \
kmod-i2c-hix5hd2.ko \
kmod-i2c-imx-lpi2c.ko \
kmod-i2c-imx.ko \
kmod-i2c-mchp-pci1xxxx.ko \
kmod-i2c-meson.ko \
kmod-i2c-mt65xx.ko \
kmod-i2c-mux-gpio.ko \
kmod-i2c-mux-gpmux.ko \
kmod-i2c-mux-ltc4306.ko \
kmod-i2c-mux-mlxcpld.ko \
kmod-i2c-mux-pca9541.ko \
kmod-i2c-mux-pca954x.ko \
kmod-i2c-mux-pinctrl.ko \
kmod-i2c-mux-reg.ko \
kmod-i2c-mux.ko \
kmod-i2c-mv64xxx.ko \
kmod-i2c-npcm7xx.ko \
kmod-i2c-owl.ko \
kmod-i2c-pxa.ko \
kmod-i2c-qcom-cci.ko \
kmod-i2c-qcom-geni.ko \
kmod-i2c-qup.ko \
kmod-i2c-rcar.ko \
kmod-i2c-riic.ko \
kmod-i2c-rk3x.ko \
kmod-i2c-rzv2m.ko \
kmod-i2c-s3c2410.ko \
kmod-i2c-sh-mobile.ko \
kmod-i2c-slave-eeprom.ko \
kmod-i2c-smbus.ko \
kmod-i2c-sprd.ko \
kmod-i2c-synquacer.ko \
kmod-i2c-tegra-bpmp.ko \
kmod-i2c-tegra.ko \
kmod-i2c-thunderx.ko \
kmod-i2c-virtio.ko \
kmod-i2c-xgene-slimpro.ko \
kmod-i2c-xiic.ko \
kmod-i2c-xlp9xx.ko \
kmod-i6300esb.ko \
kmod-ibm-panel.ko \
kmod-icc-bcm-voter.ko \
kmod-icc-bwmon.ko \
kmod-icc-osm-l3.ko \
kmod-icc-rpmh.ko \
kmod-icc-smd-rpm.ko \
kmod-ifb.ko \
kmod-ifcvf.ko \
kmod-ife.ko \
kmod-ila.ko \
kmod-ims-pcu.ko \
kmod-imx-bus.ko \
kmod-imx-cpufreq-dt.ko \
kmod-imx-dcss.ko \
kmod-imx-dma.ko \
kmod-imx-dsp-rproc.ko \
kmod-imx-dsp.ko \
kmod-imx-earlycon.ko \
kmod-imx-interconnect.ko \
kmod-imx-keypad.ko \
kmod-imx-lcdc.ko \
kmod-imx-lcdif.ko \
kmod-imx-mailbox.ko \
kmod-imx-rproc.ko \
kmod-imx-sc-key.ko \
kmod-imx-sc-thermal.ko \
kmod-imx-sc-wdt.ko \
kmod-imx-scu.ko \
kmod-imx-sdma.ko \
kmod-imx-thermal.ko \
kmod-imx-weim.ko \
kmod-imx.ko \
kmod-imx2-wdt.ko \
kmod-imx7ulp-wdt.ko \
kmod-imx8m-blk-ctrl.ko \
kmod-imx8m-ddrc.ko \
kmod-imx8mm-interconnect.ko \
kmod-imx8mm-thermal.ko \
kmod-imx8mn-interconnect.ko \
kmod-imx8mp-blk-ctrl.ko \
kmod-imx8mp-interconnect.ko \
kmod-imx8mq-interconnect.ko \
kmod-imx8qm-ldb.ko \
kmod-imx8qxp-ldb.ko \
kmod-imx8qxp-pixel-combiner.ko \
kmod-imx8qxp-pixel-link.ko \
kmod-imx8qxp-pxl2dpi.ko \
kmod-imx93-blk-ctrl.ko \
kmod-imx93-pd.ko \
kmod-imx93-src.ko \
kmod-imxfb.ko \
kmod-ina238.ko \
kmod-inet-diag.ko \
kmod-input-core.ko \
kmod-input-leds.ko \
kmod-inspur-ipsps.ko \
kmod-interconnect-qcom.ko \
kmod-interval-tree-test.ko \
kmod-io-domain.ko \
kmod-ionic.ko \
kmod-iova.ko \
kmod-ip-gre.ko \
kmod-ip-set-bitmap-ip.ko \
kmod-ip-set-bitmap-ipmac.ko \
kmod-ip-set-bitmap-port.ko \
kmod-ip-set-hash-ip.ko \
kmod-ip-set-hash-ipmac.ko \
kmod-ip-set-hash-ipmark.ko \
kmod-ip-set-hash-ipport.ko \
kmod-ip-set-hash-ipportip.ko \
kmod-ip-set-hash-ipportnet.ko \
kmod-ip-set-hash-mac.ko \
kmod-ip-set-hash-net.ko \
kmod-ip-set-hash-netiface.ko \
kmod-ip-set-hash-netnet.ko \
kmod-ip-set-hash-netport.ko \
kmod-ip-set-hash-netportnet.ko \
kmod-ip-set-list-set.ko \
kmod-ip-set.ko \
kmod-ip-tables.ko \
kmod-ip-tunnel.ko \
kmod-ip-vs-dh.ko \
kmod-ip-vs-fo.ko \
kmod-ip-vs-ftp.ko \
kmod-ip-vs-lblc.ko \
kmod-ip-vs-lblcr.ko \
kmod-ip-vs-lc.ko \
kmod-ip-vs-mh.ko \
kmod-ip-vs-nq.ko \
kmod-ip-vs-ovf.ko \
kmod-ip-vs-pe-sip.ko \
kmod-ip-vs-rr.ko \
kmod-ip-vs-sed.ko \
kmod-ip-vs-sh.ko \
kmod-ip-vs-twos.ko \
kmod-ip-vs-wlc.ko \
kmod-ip-vs-wrr.ko \
kmod-ip-vs.ko \
kmod-ip-vti.ko \
kmod-ip5xxx-power.ko \
kmod-ip6-gre.ko \
kmod-ip6-tables.ko \
kmod-ip6-tunnel.ko \
kmod-ip6-udp-tunnel.ko \
kmod-ip6-vti.ko \
kmod-ip6t-NPT.ko \
kmod-ip6t-REJECT.ko \
kmod-ip6t-SYNPROXY.ko \
kmod-ip6t-ah.ko \
kmod-ip6t-eui64.ko \
kmod-ip6t-frag.ko \
kmod-ip6t-hbh.ko \
kmod-ip6t-ipv6header.ko \
kmod-ip6t-mh.ko \
kmod-ip6t-rpfilter.ko \
kmod-ip6t-rt.ko \
kmod-ip6t-srh.ko \
kmod-ip6table-filter.ko \
kmod-ip6table-mangle.ko \
kmod-ip6table-nat.ko \
kmod-ip6table-raw.ko \
kmod-ip6table-security.ko \
kmod-ipcomp.ko \
kmod-ipcomp6.ko \
kmod-ipip.ko \
kmod-ipmb-dev-int.ko \
kmod-ipmi-devintf.ko \
kmod-ipmi-ipmb.ko \
kmod-ipmi-msghandler.ko \
kmod-ipmi-poweroff.ko \
kmod-ipmi-si.ko \
kmod-ipmi-watchdog.ko \
kmod-iproc-rng200.ko \
kmod-ipt-ECN.ko \
kmod-ipt-REJECT.ko \
kmod-ipt-SYNPROXY.ko \
kmod-ipt-ah.ko \
kmod-ipt-rpfilter.ko \
kmod-iptable-filter.ko \
kmod-iptable-mangle.ko \
kmod-iptable-nat.ko \
kmod-iptable-raw.ko \
kmod-iptable-security.ko \
kmod-ipv6.ko \
kmod-ipvlan.ko \
kmod-ipvtap.ko \
kmod-iqs269a.ko \
kmod-iqs626a.ko \
kmod-iqs62x-keys.ko \
kmod-iqs62x.ko \
kmod-iqs7222.ko \
kmod-ir35221.ko \
kmod-ir36021.ko \
kmod-irq-bcm7038-l1.ko \
kmod-irq-bcm7120-l2.ko \
kmod-irq-brcmstb-l2.ko \
kmod-irq-imx-mu-msi.ko \
kmod-irq-meson-gpio.ko \
kmod-irq-mvebu-pic.ko \
kmod-irq-qcom-mpm.ko \
kmod-irqbypass.ko \
kmod-iscsi-boot-sysfs.ko \
kmod-iscsi-ibft.ko \
kmod-iscsi-tcp.ko \
kmod-isl9305.ko \
kmod-isofs.ko \
kmod-isp1704-charger.ko \
kmod-ite-it6505.ko \
kmod-ite-it66121.ko \
kmod-jbd2.ko \
kmod-jitterentropy-rng.ko \
kmod-joydev.ko \
kmod-k3dma.ko \
kmod-kcm.ko \
kmod-kcomedilib.ko \
kmod-kcs-bmc-cdev-ipmi.ko \
kmod-kcs-bmc-npcm7xx.ko \
kmod-kcs-bmc-serio.ko \
kmod-kcs-bmc.ko \
kmod-kdf-sp800108.ko \
kmod-keembay-wdt.ko \
kmod-keywrap.ko \
kmod-kgdboc.ko \
kmod-khadas-mcu-fan.ko \
kmod-khadas-mcu.ko \
kmod-kirin-drm.ko \
kmod-kmem.ko \
kmod-komeda.ko \
kmod-kpp.ko \
kmod-ksmbd.ko \
kmod-ktd253-backlight.ko \
kmod-ktz8866.ko \
kmod-kvm.ko \
kmod-kyber-iosched.ko \
kmod-l2tp-core.ko \
kmod-l2tp-eth.ko \
kmod-l2tp-ip.ko \
kmod-l2tp-ip6.ko \
kmod-l2tp-netlink.ko \
kmod-lan743x.ko \
kmod-lan966x-serdes.ko \
kmod-layerscape-edac-mod.ko \
kmod-lcd.ko \
kmod-led-bl.ko \
kmod-led-class-flash.ko \
kmod-led-class-multicolor.ko \
kmod-led-class.ko \
kmod-leds-an30259a.ko \
kmod-leds-as3645a.ko \
kmod-leds-aw2013.ko \
kmod-leds-bd2606mvv.ko \
kmod-leds-bd2802.ko \
kmod-leds-blinkm.ko \
kmod-leds-gpio.ko \
kmod-leds-is31fl319x.ko \
kmod-leds-is31fl32xx.ko \
kmod-leds-lm3530.ko \
kmod-leds-lm3532.ko \
kmod-leds-lm355x.ko \
kmod-leds-lm3601x.ko \
kmod-leds-lm3642.ko \
kmod-leds-lm3692x.ko \
kmod-leds-lm3697.ko \
kmod-leds-lp3944.ko \
kmod-leds-lp3952.ko \
kmod-leds-lp50xx.ko \
kmod-leds-lp5521.ko \
kmod-leds-lp5523.ko \
kmod-leds-lp5562.ko \
kmod-leds-lp55xx-common.ko \
kmod-leds-lp8501.ko \
kmod-leds-lp8860.ko \
kmod-leds-lt3593.ko \
kmod-leds-max77650.ko \
kmod-leds-menf21bmc.ko \
kmod-leds-mlxreg.ko \
kmod-leds-mt6360.ko \
kmod-leds-pca9532.ko \
kmod-leds-pca955x.ko \
kmod-leds-pca963x.ko \
kmod-leds-pwm-multicolor.ko \
kmod-leds-pwm.ko \
kmod-leds-rt4505.ko \
kmod-leds-rt8515.ko \
kmod-leds-sgm3140.ko \
kmod-leds-tca6507.ko \
kmod-leds-ti-lmu-common.ko \
kmod-ledtrig-activity.ko \
kmod-ledtrig-audio.ko \
kmod-ledtrig-backlight.ko \
kmod-ledtrig-camera.ko \
kmod-ledtrig-default-on.ko \
kmod-ledtrig-heartbeat.ko \
kmod-ledtrig-netdev.ko \
kmod-ledtrig-oneshot.ko \
kmod-ledtrig-pattern.ko \
kmod-ledtrig-timer.ko \
kmod-ledtrig-transient.ko \
kmod-ledtrig-tty.ko \
kmod-ledtrig-usbport.ko \
kmod-libaes.ko \
kmod-libahci-platform.ko \
kmod-libahci.ko \
kmod-libarc4.ko \
kmod-libata.ko \
kmod-libceph.ko \
kmod-libchacha.ko \
kmod-libchacha20poly1305.ko \
kmod-libcomposite.ko \
kmod-libcrc32c.ko \
kmod-libcryptoutils.ko \
kmod-libcurve25519-generic.ko \
kmod-libcurve25519.ko \
kmod-libdes.ko \
kmod-libfc.ko \
kmod-libfcoe.ko \
kmod-libiscsi-tcp.ko \
kmod-libiscsi.ko \
kmod-libnvdimm.ko \
kmod-libphy.ko \
kmod-libpoly1305.ko \
kmod-libps2.ko \
kmod-libsas.ko \
kmod-libsha1.ko \
kmod-libsha256.ko \
kmod-libwx.ko \
kmod-lima.ko \
kmod-linear-ranges.ko \
kmod-linear.ko \
kmod-linkstation-poweroff.ko \
kmod-litex-liteeth.ko \
kmod-lkdtm.ko \
kmod-llc.ko \
kmod-llc2.ko \
kmod-llcc-qcom.ko \
kmod-lm3630a-bl.ko \
kmod-lm3639-bl.ko \
kmod-lm8323.ko \
kmod-lmh.ko \
kmod-lochnagar-hwmon.ko \
kmod-lochnagar-regulator.ko \
kmod-lockd.ko \
kmod-logicvc-drm.ko \
kmod-lontium-lt8912b.ko \
kmod-lontium-lt9211.ko \
kmod-lontium-lt9611.ko \
kmod-lontium-lt9611uxc.ko \
kmod-loop.ko \
kmod-lp855x-bl.ko \
kmod-lp873x-regulator.ko \
kmod-lp873x.ko \
kmod-lp87565-regulator.ko \
kmod-lp87565.ko \
kmod-lpass-gfm-sm8250.ko \
kmod-lpassaudiocc-sc7280.ko \
kmod-lpasscc-sc7280.ko \
kmod-lpasscc-sdm845.ko \
kmod-lpasscorecc-sc7180.ko \
kmod-lpasscorecc-sc7280.ko \
kmod-lru-cache.ko \
kmod-lrw.ko \
kmod-lt3651-charger.ko \
kmod-lt7182s.ko \
kmod-ltc2947-core.ko \
kmod-ltc2947-i2c.ko \
kmod-ltc2992.ko \
kmod-ltc3589.ko \
kmod-ltc3676.ko \
kmod-ltc4162-l-charger.ko \
kmod-lv5207lp.ko \
kmod-lvds-codec.ko \
kmod-lvts-thermal.ko \
kmod-lz4-compress.ko \
kmod-lz4-decompress.ko \
kmod-lz4.ko \
kmod-lz4hc-compress.ko \
kmod-lz4hc.ko \
kmod-lzo-compress.ko \
kmod-lzo-decompress.ko \
kmod-lzo-rle.ko \
kmod-lzo.ko \
kmod-macvlan.ko \
kmod-macvtap.ko \
kmod-mailbox-xgene-slimpro.ko \
kmod-mali-dp.ko \
kmod-marvell-88x2222.ko \
kmod-marvell-cn10k-ddr-pmu.ko \
kmod-marvell-cn10k-tad-pmu.ko \
kmod-marvell.ko \
kmod-matrix-keymap.ko \
kmod-matrix-keypad.ko \
kmod-max127.ko \
kmod-max14656-charger-detector.ko \
kmod-max15301.ko \
kmod-max16601.ko \
kmod-max20086-regulator.ko \
kmod-max20411-regulator.ko \
kmod-max20730.ko \
kmod-max31730.ko \
kmod-max31760.ko \
kmod-max597x-regulator.ko \
kmod-max6620.ko \
kmod-max77620-regulator.ko \
kmod-max77620-thermal.ko \
kmod-max77620-wdt.ko \
kmod-max77650-charger.ko \
kmod-max77650-onkey.ko \
kmod-max77650-regulator.ko \
kmod-max77650.ko \
kmod-max77714.ko \
kmod-max77826-regulator.ko \
kmod-max77976-charger.ko \
kmod-max8893.ko \
kmod-mbcache.ko \
kmod-mc34vr500.ko \
kmod-mchp-pci1xxxx-gp.ko \
kmod-mchp-pci1xxxx-gpio.ko \
kmod-mcp16502.ko \
kmod-mctp-i2c.ko \
kmod-mctp-serial.ko \
kmod-md-cluster.ko \
kmod-md-mod.ko \
kmod-md4.ko \
kmod-md5.ko \
kmod-mdio-cavium.ko \
kmod-mdio-devres.ko \
kmod-mdio-hisi-femac.ko \
kmod-mdio-i2c.ko \
kmod-mdio-ipq4019.ko \
kmod-mdio-ipq8064.ko \
kmod-mdio-mux-bcm-iproc.ko \
kmod-mdio-mux-gpio.ko \
kmod-mdio-mux-meson-g12a.ko \
kmod-mdio-mux-meson-gxl.ko \
kmod-mdio-mux-mmioreg.ko \
kmod-mdio-mux-multiplexer.ko \
kmod-mdio-mux.ko \
kmod-mdio-mvusb.ko \
kmod-mdio-octeon.ko \
kmod-mdio-sun4i.ko \
kmod-mdio-thunder.ko \
kmod-mdio-xgene.ko \
kmod-mdt-loader.ko \
kmod-mediatek-cpufreq-hw.ko \
kmod-mediatek-cpufreq.ko \
kmod-mediatek-drm-hdmi.ko \
kmod-mediatek-drm.ko \
kmod-mediatek-ge.ko \
kmod-megachips-stdpxxxx-ge-b850v3-fw.ko \
kmod-memory-notifier-error-inject.ko \
kmod-mena21-wdt.ko \
kmod-menf21bmc.ko \
kmod-meson-aoclk.ko \
kmod-meson-canvas.ko \
kmod-meson-clk-measure.ko \
kmod-meson-drm.ko \
kmod-meson-dw-hdmi.ko \
kmod-meson-ee-pwrc.ko \
kmod-meson-eeclk.ko \
kmod-meson-gx-pwrc-vpu.ko \
kmod-meson-gxbb-wdt.ko \
kmod-meson-gxl.ko \
kmod-meson-rng.ko \
kmod-meson-secure-pwrc.ko \
kmod-meson-sm.ko \
kmod-meson-uart.ko \
kmod-meson-wdt.ko \
kmod-mfd-core.ko \
kmod-mhi-ep.ko \
kmod-mhi-net.ko \
kmod-mhi-pci-generic.ko \
kmod-mhi-wwan-ctrl.ko \
kmod-mhi-wwan-mbim.ko \
kmod-mhi.ko \
kmod-michael-mic.ko \
kmod-microchip-t1s.ko \
kmod-mii.ko \
kmod-mip6.ko \
kmod-mmcc-msm8994.ko \
kmod-mmcc-msm8998.ko \
kmod-mmcc-sdm660.ko \
kmod-motorcomm.ko \
kmod-mousedev.ko \
kmod-mp2629.ko \
kmod-mp2888.ko \
kmod-mp2975.ko \
kmod-mp5023.ko \
kmod-mp5416.ko \
kmod-mp8859.ko \
kmod-mp886x.ko \
kmod-mpi.ko \
kmod-mpi3mr.ko \
kmod-mpq7920.ko \
kmod-mpq7932.ko \
kmod-mptcp-diag.ko \
kmod-mq-deadline.ko \
kmod-mr75203.ko \
kmod-mrp.ko \
kmod-msdos.ko \
kmod-msm-serial.ko \
kmod-msm.ko \
kmod-mss-sc7180.ko \
kmod-mt6360-charger.ko \
kmod-mt6360-core.ko \
kmod-mt6360-regulator.ko \
kmod-mt6380-regulator.ko \
kmod-mt6779-keypad.ko \
kmod-mtk-adsp-ipc.ko \
kmod-mtk-adsp-mailbox.ko \
kmod-mtk-cci-devfreq.ko \
kmod-mtk-cmdq-helper.ko \
kmod-mtk-cmdq-mailbox.ko \
kmod-mtk-cqdma.ko \
kmod-mtk-devapc.ko \
kmod-mtk-dp.ko \
kmod-mtk-eint.ko \
kmod-mtk-eth.ko \
kmod-mtk-hsdma.ko \
kmod-mtk-iommu.ko \
kmod-mtk-mmsys.ko \
kmod-mtk-mutex.ko \
kmod-mtk-pmic-wrap.ko \
kmod-mtk-regulator-coupler.ko \
kmod-mtk-rng.ko \
kmod-mtk-rpmsg.ko \
kmod-mtk-scp-ipi.ko \
kmod-mtk-scp.ko \
kmod-mtk-smi.ko \
kmod-mtk-star-emac.ko \
kmod-mtk-svs.ko \
kmod-mtk-t7xx.ko \
kmod-mtk-uart-apdma.ko \
kmod-mtk-wdt.ko \
kmod-mtu3.ko \
kmod-multipath.ko \
kmod-mux-adg792a.ko \
kmod-mux-core.ko \
kmod-mux-gpio.ko \
kmod-mux-mmio.ko \
kmod-mx3fb.ko \
kmod-mxc-clk.ko \
kmod-mxl-gpy.ko \
kmod-n-null.ko \
kmod-nbd.ko \
kmod-ncn26000.ko \
kmod-nct6775-core.ko \
kmod-nct6775-i2c.ko \
kmod-nd-btt.ko \
kmod-nd-pmem.ko \
kmod-nd-virtio.ko \
kmod-net-failover.ko \
kmod-netconsole.ko \
kmod-netdev-notifier-error-inject.ko \
kmod-netdevsim.ko \
kmod-netfs.ko \
kmod-netlink-diag.ko \
kmod-nf-conncount.ko \
kmod-nf-conntrack-amanda.ko \
kmod-nf-conntrack-bridge.ko \
kmod-nf-conntrack-broadcast.ko \
kmod-nf-conntrack-ftp.ko \
kmod-nf-conntrack-h323.ko \
kmod-nf-conntrack-irc.ko \
kmod-nf-conntrack-netbios-ns.ko \
kmod-nf-conntrack-netlink.ko \
kmod-nf-conntrack-pptp.ko \
kmod-nf-conntrack-sane.ko \
kmod-nf-conntrack-sip.ko \
kmod-nf-conntrack-snmp.ko \
kmod-nf-conntrack-tftp.ko \
kmod-nf-conntrack.ko \
kmod-nf-defrag-ipv4.ko \
kmod-nf-defrag-ipv6.ko \
kmod-nf-dup-ipv4.ko \
kmod-nf-dup-ipv6.ko \
kmod-nf-dup-netdev.ko \
kmod-nf-flow-table-inet.ko \
kmod-nf-flow-table.ko \
kmod-nf-log-syslog.ko \
kmod-nf-nat-amanda.ko \
kmod-nf-nat-ftp.ko \
kmod-nf-nat-h323.ko \
kmod-nf-nat-irc.ko \
kmod-nf-nat-pptp.ko \
kmod-nf-nat-sip.ko \
kmod-nf-nat-snmp-basic.ko \
kmod-nf-nat-tftp.ko \
kmod-nf-nat.ko \
kmod-nf-reject-ipv4.ko \
kmod-nf-reject-ipv6.ko \
kmod-nf-socket-ipv4.ko \
kmod-nf-socket-ipv6.ko \
kmod-nf-synproxy-core.ko \
kmod-nf-tables.ko \
kmod-nf-tproxy-ipv4.ko \
kmod-nf-tproxy-ipv6.ko \
kmod-nfit.ko \
kmod-nfnetlink-acct.ko \
kmod-nfnetlink-cthelper.ko \
kmod-nfnetlink-cttimeout.ko \
kmod-nfnetlink-hook.ko \
kmod-nfnetlink-log.ko \
kmod-nfnetlink-osf.ko \
kmod-nfnetlink-queue.ko \
kmod-nfnetlink.ko \
kmod-nfs-acl.ko \
kmod-nfs-layout-flexfiles.ko \
kmod-nfs-layout-nfsv41-files.ko \
kmod-nfs.ko \
kmod-nfsd.ko \
kmod-nfsv2.ko \
kmod-nfsv3.ko \
kmod-nfsv4.ko \
kmod-nft-chain-nat.ko \
kmod-nft-compat.ko \
kmod-nft-connlimit.ko \
kmod-nft-ct.ko \
kmod-nft-dup-ipv4.ko \
kmod-nft-dup-ipv6.ko \
kmod-nft-dup-netdev.ko \
kmod-nft-fib-inet.ko \
kmod-nft-fib-ipv4.ko \
kmod-nft-fib-ipv6.ko \
kmod-nft-fib-netdev.ko \
kmod-nft-fib.ko \
kmod-nft-flow-offload.ko \
kmod-nft-fwd-netdev.ko \
kmod-nft-hash.ko \
kmod-nft-limit.ko \
kmod-nft-log.ko \
kmod-nft-masq.ko \
kmod-nft-meta-bridge.ko \
kmod-nft-nat.ko \
kmod-nft-numgen.ko \
kmod-nft-osf.ko \
kmod-nft-queue.ko \
kmod-nft-quota.ko \
kmod-nft-redir.ko \
kmod-nft-reject-bridge.ko \
kmod-nft-reject-inet.ko \
kmod-nft-reject-ipv4.ko \
kmod-nft-reject-ipv6.ko \
kmod-nft-reject-netdev.ko \
kmod-nft-reject.ko \
kmod-nft-socket.ko \
kmod-nft-synproxy.ko \
kmod-nft-tproxy.ko \
kmod-nft-tunnel.ko \
kmod-nft-xfrm.ko \
kmod-ngbe.ko \
kmod-nhpoly1305-neon.ko \
kmod-nhpoly1305.ko \
kmod-ni-usb6501.ko \
kmod-nitro-enclaves.ko \
kmod-nlmon.ko \
kmod-nls-ascii.ko \
kmod-nls-base.ko \
kmod-nls-cp437.ko \
kmod-nls-iso8859-1.ko \
kmod-nls-utf8.ko \
kmod-notifier-error-inject.ko \
kmod-npcm-rng.ko \
kmod-npcm-wdt.ko \
kmod-ns-thermal.ko \
kmod-ntfs3.ko \
kmod-null-blk.ko \
kmod-nvme-apple.ko \
kmod-nvme-core.ko \
kmod-nvme-fabrics.ko \
kmod-nvme-tcp.ko \
kmod-nvmem-apple-efuses.ko \
kmod-nvmem-bcm-ocotp.ko \
kmod-nvmem-imx-iim.ko \
kmod-nvmem-imx-ocotp-scu.ko \
kmod-nvmem-imx-ocotp.ko \
kmod-nvmem-layerscape-sfp.ko \
kmod-nvmem-meson-efuse.ko \
kmod-nvmem-meson-mx-efuse.ko \
kmod-nvmem-mtk-efuse.ko \
kmod-nvmem-qfprom.ko \
kmod-nvmem-reboot-mode.ko \
kmod-nvmem-rmem.ko \
kmod-nvmem-rockchip-efuse.ko \
kmod-nvmem-rockchip-otp.ko \
kmod-nvmem-snvs-lpgpr.ko \
kmod-nvmem-sprd-efuse.ko \
kmod-nvmem-sunxi-sid.ko \
kmod-nvmem-zynqmp-nvmem.ko \
kmod-nwl-dsi.ko \
kmod-nxp-bbnsm-pwrkey.ko \
kmod-nxp-c45-tja11xx.ko \
kmod-nxp-cbtx.ko \
kmod-nxp-ptn3460.ko \
kmod-nzxt-kraken2.ko \
kmod-nzxt-smart2.ko \
kmod-ocfs2-dlm.ko \
kmod-ocfs2-dlmfs.ko \
kmod-ocfs2-nodemanager.ko \
kmod-ocfs2-stack-o2cb.ko \
kmod-ocfs2-stack-user.ko \
kmod-ocfs2-stackglue.ko \
kmod-ocfs2.ko \
kmod-ocmem.ko \
kmod-odroid-go-ultra-poweroff.ko \
kmod-of-mdio.ko \
kmod-of-pmem.ko \
kmod-of-reconfig-notifier-error-inject.ko \
kmod-of-xilinx-wdt.ko \
kmod-ofb.ko \
kmod-oid-registry.ko \
kmod-omap-rng.ko \
kmod-onboard-usb-hub.ko \
kmod-onie-tlv.ko \
kmod-open-dice.ko \
kmod-optee-rng.ko \
kmod-optee.ko \
kmod-overlay.ko \
kmod-owl-dma.ko \
kmod-owl-emac.ko \
kmod-owl-uart.ko \
kmod-p8022.ko \
kmod-panel-arm-versatile.ko \
kmod-panel-asus-z00t-tm5p5-n35596.ko \
kmod-panel-boe-bf060y8m-aj0.ko \
kmod-panel-boe-himax8279d.ko \
kmod-panel-boe-tv101wum-nl6.ko \
kmod-panel-dsi-cm.ko \
kmod-panel-ebbg-ft8719.ko \
kmod-panel-edp.ko \
kmod-panel-elida-kd35t133.ko \
kmod-panel-feixin-k101-im2ba02.ko \
kmod-panel-feiyang-fy07024di26a30d.ko \
kmod-panel-ilitek-ili9881c.ko \
kmod-panel-innolux-p079zca.ko \
kmod-panel-jdi-fhd-r63452.ko \
kmod-panel-jdi-lt070me05000.ko \
kmod-panel-khadas-ts050.ko \
kmod-panel-kingdisplay-kd097d04.ko \
kmod-panel-leadtek-ltk050h3146w.ko \
kmod-panel-leadtek-ltk500hd1829.ko \
kmod-panel-lvds.ko \
kmod-panel-mantix-mlaf057we51.ko \
kmod-panel-novatek-nt35510.ko \
kmod-panel-novatek-nt35560.ko \
kmod-panel-novatek-nt35950.ko \
kmod-panel-novatek-nt36523.ko \
kmod-panel-novatek-nt36672a.ko \
kmod-panel-olimex-lcd-olinuxino.ko \
kmod-panel-orisetech-otm8009a.ko \
kmod-panel-osd-osd101t2587-53ts.ko \
kmod-panel-panasonic-vvx10f034n00.ko \
kmod-panel-raspberrypi-touchscreen.ko \
kmod-panel-raydium-rm67191.ko \
kmod-panel-raydium-rm68200.ko \
kmod-panel-ronbo-rb070d30.ko \
kmod-panel-samsung-s6d16d0.ko \
kmod-panel-samsung-s6e3ha2.ko \
kmod-panel-samsung-s6e63j0x03.ko \
kmod-panel-samsung-s6e63m0.ko \
kmod-panel-samsung-s6e88a0-ams452ef01.ko \
kmod-panel-samsung-s6e8aa0.ko \
kmod-panel-samsung-sofef00.ko \
kmod-panel-seiko-43wvf1g.ko \
kmod-panel-sharp-lq101r1sx01.ko \
kmod-panel-sharp-ls037v7dw01.ko \
kmod-panel-sharp-ls043t1le01.ko \
kmod-panel-sharp-ls060t1sx01.ko \
kmod-panel-simple.ko \
kmod-panel-sitronix-st7701.ko \
kmod-panel-sitronix-st7703.ko \
kmod-panel-sony-td4353-jdi.ko \
kmod-panel-sony-tulip-truly-nt35521.ko \
kmod-panel-tdo-tl070wsh30.ko \
kmod-panel-truly-nt35597.ko \
kmod-panel-visionox-rm69299.ko \
kmod-panel-xinpeng-xpp055c272.ko \
kmod-panfrost.ko \
kmod-parade-ps8622.ko \
kmod-parade-ps8640.ko \
kmod-pata-imx.ko \
kmod-pca9450-regulator.ko \
kmod-pcbc.ko \
kmod-pci-aardvark.ko \
kmod-pci-epf-ntb.ko \
kmod-pci-exynos.ko \
kmod-pci-host-common.ko \
kmod-pci-host-generic.ko \
kmod-pci-meson.ko \
kmod-pci-stub.ko \
kmod-pcie-altera-msi.ko \
kmod-pcie-altera.ko \
kmod-pcie-apple.ko \
kmod-pcie-brcmstb.ko \
kmod-pcie-iproc-platform.ko \
kmod-pcie-iproc.ko \
kmod-pcie-kirin.ko \
kmod-pcie-mediatek-gen3.ko \
kmod-pcie-mediatek.ko \
kmod-pcie-qcom-ep.ko \
kmod-pcie-rockchip-host.ko \
kmod-pcie-tegra194.ko \
kmod-pcips2.ko \
kmod-pcnet32.ko \
kmod-pcrypt.ko \
kmod-pcs-lynx.ko \
kmod-pcs-mtk-lynxi.ko \
kmod-pdr-interface.ko \
kmod-pds-core.ko \
kmod-pf8x00-regulator.ko \
kmod-pfr-telemetry.ko \
kmod-pfr-update.ko \
kmod-pfuze100-regulator.ko \
kmod-phy-armada38x-comphy.ko \
kmod-phy-bcm-ns-usb2.ko \
kmod-phy-bcm-ns-usb3.ko \
kmod-phy-bcm-ns2-pcie.ko \
kmod-phy-bcm-ns2-usbdrd.ko \
kmod-phy-bcm-sr-pcie.ko \
kmod-phy-bcm-sr-usb.ko \
kmod-phy-berlin-sata.ko \
kmod-phy-berlin-usb.ko \
kmod-phy-brcm-sata.ko \
kmod-phy-brcm-usb-dvr.ko \
kmod-phy-cadence-salvo.ko \
kmod-phy-cadence-sierra.ko \
kmod-phy-cadence-torrent.ko \
kmod-phy-can-transceiver.ko \
kmod-phy-exynos-dp-video.ko \
kmod-phy-exynos-mipi-video.ko \
kmod-phy-exynos-ufs.ko \
kmod-phy-fsl-imx8-mipi-dphy.ko \
kmod-phy-fsl-imx8m-pcie.ko \
kmod-phy-fsl-imx8mq-usb.ko \
kmod-phy-fsl-imx8qm-lvds-phy.ko \
kmod-phy-fsl-lynx-28g.ko \
kmod-phy-generic.ko \
kmod-phy-hi3660-usb3.ko \
kmod-phy-hi3670-pcie.ko \
kmod-phy-hi3670-usb3.ko \
kmod-phy-hi6220-usb.ko \
kmod-phy-hisi-inno-usb2.ko \
kmod-phy-histb-combphy.ko \
kmod-phy-intel-keembay-emmc.ko \
kmod-phy-intel-keembay-usb.ko \
kmod-phy-mapphone-mdm6600.ko \
kmod-phy-meson-axg-mipi-dphy.ko \
kmod-phy-meson-axg-mipi-pcie-analog.ko \
kmod-phy-meson-axg-pcie.ko \
kmod-phy-meson-g12a-mipi-dphy-analog.ko \
kmod-phy-meson-g12a-usb2.ko \
kmod-phy-meson-g12a-usb3-pcie.ko \
kmod-phy-meson-gxl-usb2.ko \
kmod-phy-meson8b-usb2.ko \
kmod-phy-mtk-dp.ko \
kmod-phy-mtk-hdmi-drv.ko \
kmod-phy-mtk-mipi-dsi-drv.ko \
kmod-phy-mtk-pcie.ko \
kmod-phy-mtk-tphy.ko \
kmod-phy-mtk-ufs.ko \
kmod-phy-mtk-xsphy.ko \
kmod-phy-mvebu-a3700-comphy.ko \
kmod-phy-mvebu-a3700-utmi.ko \
kmod-phy-mvebu-cp110-comphy.ko \
kmod-phy-mvebu-cp110-utmi.ko \
kmod-phy-mxs-usb.ko \
kmod-phy-ocelot-serdes.ko \
kmod-phy-pxa-28nm-hsic.ko \
kmod-phy-pxa-28nm-usb2.ko \
kmod-phy-qcom-apq8064-sata.ko \
kmod-phy-qcom-edp.ko \
kmod-phy-qcom-eusb2-repeater.ko \
kmod-phy-qcom-ipq806x-sata.ko \
kmod-phy-qcom-ipq806x-usb.ko \
kmod-phy-qcom-pcie2.ko \
kmod-phy-qcom-qmp-combo.ko \
kmod-phy-qcom-qmp-pcie-msm8996.ko \
kmod-phy-qcom-qmp-pcie.ko \
kmod-phy-qcom-qmp-ufs.ko \
kmod-phy-qcom-qmp-usb.ko \
kmod-phy-qcom-qusb2.ko \
kmod-phy-qcom-snps-eusb2.ko \
kmod-phy-qcom-snps-femto-v2.ko \
kmod-phy-qcom-usb-hs-28nm.ko \
kmod-phy-qcom-usb-hs.ko \
kmod-phy-qcom-usb-hsic.ko \
kmod-phy-qcom-usb-ss.ko \
kmod-phy-rcar-gen2.ko \
kmod-phy-rcar-gen3-pcie.ko \
kmod-phy-rcar-gen3-usb2.ko \
kmod-phy-rcar-gen3-usb3.ko \
kmod-phy-rockchip-dp.ko \
kmod-phy-rockchip-dphy-rx0.ko \
kmod-phy-rockchip-emmc.ko \
kmod-phy-rockchip-inno-csidphy.ko \
kmod-phy-rockchip-inno-dsidphy.ko \
kmod-phy-rockchip-inno-hdmi.ko \
kmod-phy-rockchip-inno-usb2.ko \
kmod-phy-rockchip-naneng-combphy.ko \
kmod-phy-rockchip-pcie.ko \
kmod-phy-rockchip-snps-pcie3.ko \
kmod-phy-rockchip-typec.ko \
kmod-phy-rockchip-usb.ko \
kmod-phy-sun4i-usb.ko \
kmod-phy-sun50i-usb3.ko \
kmod-phy-sun6i-mipi-dphy.ko \
kmod-phy-sun9i-usb.ko \
kmod-phy-tegra-usb.ko \
kmod-phy-tegra-xusb.ko \
kmod-phy-tegra194-p2u.ko \
kmod-phy-xgene.ko \
kmod-phy-zynqmp.ko \
kmod-phylink.ko \
kmod-pim4328.ko \
kmod-pinctrl-apple-gpio.ko \
kmod-pinctrl-axp209.ko \
kmod-pinctrl-bcm2835.ko \
kmod-pinctrl-bcm4908.ko \
kmod-pinctrl-cy8c95x0.ko \
kmod-pinctrl-imx.ko \
kmod-pinctrl-imx8dxl.ko \
kmod-pinctrl-imx8mm.ko \
kmod-pinctrl-imx8mn.ko \
kmod-pinctrl-imx8mp.ko \
kmod-pinctrl-imx8mq.ko \
kmod-pinctrl-imx8qm.ko \
kmod-pinctrl-imx8qxp.ko \
kmod-pinctrl-imx8ulp.ko \
kmod-pinctrl-imx93.ko \
kmod-pinctrl-ipq5332.ko \
kmod-pinctrl-ipq6018.ko \
kmod-pinctrl-ipq9574.ko \
kmod-pinctrl-keembay.ko \
kmod-pinctrl-lochnagar.ko \
kmod-pinctrl-lpass-lpi.ko \
kmod-pinctrl-max77620.ko \
kmod-pinctrl-mcp23s08-i2c.ko \
kmod-pinctrl-mcp23s08.ko \
kmod-pinctrl-meson-a1.ko \
kmod-pinctrl-meson-axg-pmx.ko \
kmod-pinctrl-meson-axg.ko \
kmod-pinctrl-meson-g12a.ko \
kmod-pinctrl-meson-gxbb.ko \
kmod-pinctrl-meson-gxl.ko \
kmod-pinctrl-meson-s4.ko \
kmod-pinctrl-meson.ko \
kmod-pinctrl-meson8-pmx.ko \
kmod-pinctrl-msm.ko \
kmod-pinctrl-msm8916.ko \
kmod-pinctrl-msm8953.ko \
kmod-pinctrl-msm8976.ko \
kmod-pinctrl-msm8998.ko \
kmod-pinctrl-mt6765.ko \
kmod-pinctrl-mt6779.ko \
kmod-pinctrl-mtk-common-v2.ko \
kmod-pinctrl-paris.ko \
kmod-pinctrl-qcm2290.ko \
kmod-pinctrl-qdf2xxx.ko \
kmod-pinctrl-qdu1000.ko \
kmod-pinctrl-rk805.ko \
kmod-pinctrl-rockchip.ko \
kmod-pinctrl-s32g2.ko \
kmod-pinctrl-sa8775p.ko \
kmod-pinctrl-sc7180.ko \
kmod-pinctrl-sc7280-lpass-lpi.ko \
kmod-pinctrl-sc7280.ko \
kmod-pinctrl-sc8180x.ko \
kmod-pinctrl-sc8280xp-lpass-lpi.ko \
kmod-pinctrl-sc8280xp.ko \
kmod-pinctrl-scu.ko \
kmod-pinctrl-sdm845.ko \
kmod-pinctrl-single.ko \
kmod-pinctrl-sm6115.ko \
kmod-pinctrl-sm6125.ko \
kmod-pinctrl-sm6350.ko \
kmod-pinctrl-sm7150.ko \
kmod-pinctrl-sm8150.ko \
kmod-pinctrl-sm8250-lpass-lpi.ko \
kmod-pinctrl-sm8250.ko \
kmod-pinctrl-sm8350.ko \
kmod-pinctrl-sm8450-lpass-lpi.ko \
kmod-pinctrl-sm8450.ko \
kmod-pinctrl-sm8550-lpass-lpi.ko \
kmod-pinctrl-sm8550.ko \
kmod-pinctrl-sprd-sc9860.ko \
kmod-pinctrl-sprd.ko \
kmod-pinctrl-ssbi-gpio.ko \
kmod-pinctrl-ssbi-mpp.ko \
kmod-pinctrl-stmfx.ko \
kmod-pinctrl-zynqmp.ko \
kmod-pinephone-keyboard.ko \
kmod-pkcs7-message.ko \
kmod-pkcs8-key-parser.ko \
kmod-pl111-drm.ko \
kmod-pl172.ko \
kmod-pl330.ko \
kmod-platform-lcd.ko \
kmod-platform-mhu.ko \
kmod-pli1209bc.ko \
kmod-plx-dma.ko \
kmod-pm-notifier-error-inject.ko \
kmod-pm6764tr.ko \
kmod-pmbus-core.ko \
kmod-poly1305-generic.ko \
kmod-poly1305-neon.ko \
kmod-polynomial.ko \
kmod-polyval-ce.ko \
kmod-polyval-generic.ko \
kmod-ppp-deflate.ko \
kmod-ppp-generic.ko \
kmod-ppp-mppe.ko \
kmod-pppoe.ko \
kmod-pppox.ko \
kmod-pptp.ko \
kmod-pretimeout-noop.ko \
kmod-pretimeout-panic.ko \
kmod-processor.ko \
kmod-ps2-gpio.ko \
kmod-psample.ko \
kmod-pse-regulator.ko \
kmod-psmouse.ko \
kmod-psnap.ko \
kmod-pstore-blk.ko \
kmod-pstore-zone.ko \
kmod-pstore.ko \
kmod-public-key.ko \
kmod-pulse8-cec.ko \
kmod-pvpanic-mmio.ko \
kmod-pvpanic-pci.ko \
kmod-pvpanic.ko \
kmod-pwc-rzv2m.ko \
kmod-pwm-apple.ko \
kmod-pwm-atmel-hlcdc.ko \
kmod-pwm-atmel-tcb.ko \
kmod-pwm-bcm-iproc.ko \
kmod-pwm-bcm2835.ko \
kmod-pwm-beeper.ko \
kmod-pwm-berlin.ko \
kmod-pwm-bl.ko \
kmod-pwm-brcmstb.ko \
kmod-pwm-clk.ko \
kmod-pwm-dwc.ko \
kmod-pwm-fan.ko \
kmod-pwm-hibvt.ko \
kmod-pwm-imx-tpm.ko \
kmod-pwm-iqs620a.ko \
kmod-pwm-keembay.ko \
kmod-pwm-mediatek.ko \
kmod-pwm-meson.ko \
kmod-pwm-mtk-disp.ko \
kmod-pwm-raspberrypi-poe.ko \
kmod-pwm-rcar.ko \
kmod-pwm-regulator.ko \
kmod-pwm-renesas-tpu.ko \
kmod-pwm-rockchip.ko \
kmod-pwm-samsung.ko \
kmod-pwm-sprd.ko \
kmod-pwm-sun4i.ko \
kmod-pwm-tegra.ko \
kmod-pwm-vibra.ko \
kmod-pwm-visconti.ko \
kmod-pwm-xilinx.ko \
kmod-q54sj108a2.ko \
kmod-q6sstop-qcs404.ko \
kmod-qaic.ko \
kmod-qcom-aoss.ko \
kmod-qcom-apcs-ipc-mailbox.ko \
kmod-qcom-cpufreq-hw.ko \
kmod-qcom-edac.ko \
kmod-qcom-eud.ko \
kmod-qcom-geni-se.ko \
kmod-qcom-geni-serial.ko \
kmod-qcom-glink-rpm.ko \
kmod-qcom-glink.ko \
kmod-qcom-gsbi.ko \
kmod-qcom-ipcc.ko \
kmod-qcom-pdc.ko \
kmod-qcom-pm8008.ko \
kmod-qcom-rpm-regulator.ko \
kmod-qcom-rpm.ko \
kmod-qcom-rpmh-regulator.ko \
kmod-qcom-rpmh.ko \
kmod-qcom-scm.ko \
kmod-qcom-smd-regulator.ko \
kmod-qcom-sysmon.ko \
kmod-qcom-tsens.ko \
kmod-qcom-wled.ko \
kmod-qemu-fw-cfg.ko \
kmod-qmi-helpers.ko \
kmod-qnoc-msm8916.ko \
kmod-qnoc-msm8939.ko \
kmod-qnoc-msm8974.ko \
kmod-qnoc-msm8996.ko \
kmod-qnoc-qcm2290.ko \
kmod-qnoc-qcs404.ko \
kmod-qnoc-qdu1000.ko \
kmod-qnoc-sa8775p.ko \
kmod-qnoc-sc7180.ko \
kmod-qnoc-sc7280.ko \
kmod-qnoc-sc8180x.ko \
kmod-qnoc-sc8280xp.ko \
kmod-qnoc-sdm660.ko \
kmod-qnoc-sdm670.ko \
kmod-qnoc-sdm845.ko \
kmod-qnoc-sdx55.ko \
kmod-qnoc-sdx65.ko \
kmod-qnoc-sm6350.ko \
kmod-qnoc-sm8150.ko \
kmod-qnoc-sm8250.ko \
kmod-qnoc-sm8350.ko \
kmod-qnoc-sm8450.ko \
kmod-qnoc-sm8550.ko \
kmod-qoriq-cpufreq.ko \
kmod-qoriq-thermal.ko \
kmod-qrtr-mhi.ko \
kmod-qrtr-smd.ko \
kmod-qrtr-tun.ko \
kmod-qrtr.ko \
kmod-quota-tree.ko \
kmod-quota-v1.ko \
kmod-quota-v2.ko \
kmod-qxl.ko \
kmod-r8a779f0-ether-serdes.ko \
kmod-raid-class.ko \
kmod-raid0.ko \
kmod-raid1.ko \
kmod-raid10.ko \
kmod-raid456.ko \
kmod-raid6-pq.ko \
kmod-raid6test.ko \
kmod-rainshadow-cec.ko \
kmod-ramp-controller.ko \
kmod-raspberrypi-cpufreq.ko \
kmod-raspberrypi-hwmon.ko \
kmod-raspberrypi.ko \
kmod-rational.ko \
kmod-raw-diag.ko \
kmod-raw-gadget.ko \
kmod-rbd.ko \
kmod-rbtree-test.ko \
kmod-rcar-cmm.ko \
kmod-rcar-dmac.ko \
kmod-rcar-du-drm.ko \
kmod-rcar-dw-hdmi.ko \
kmod-rcar-gen3-thermal.ko \
kmod-rcar-lvds.ko \
kmod-rcar-mipi-dsi.ko \
kmod-rcar-rproc.ko \
kmod-rcar-thermal.ko \
kmod-rcuscale.ko \
kmod-reboot-mode.ko \
kmod-reed-solomon.ko \
kmod-regmap-i2c.ko \
kmod-regmap-mmio.ko \
kmod-regmap-slimbus.ko \
kmod-regulator-haptic.ko \
kmod-renesas-rpc-if.ko \
kmod-renesas-usb3.ko \
kmod-renesas-usbf.ko \
kmod-renesas-usbhs.ko \
kmod-renesas-wdt.ko \
kmod-reset-berlin.ko \
kmod-reset-brcmstb-rescal.ko \
kmod-reset-brcmstb.ko \
kmod-reset-hi3660.ko \
kmod-reset-imx7.ko \
kmod-reset-meson-audio-arb.ko \
kmod-reset-meson.ko \
kmod-reset-qcom-aoss.ko \
kmod-reset-qcom-pdc.ko \
kmod-reset-raspberrypi.ko \
kmod-reset-rzg2l-usbphy-ctrl.ko \
kmod-reset-scmi.ko \
kmod-reset-ti-syscon.ko \
kmod-reset.ko \
kmod-ring-buffer-benchmark.ko \
kmod-rk3399-dmc.ko \
kmod-rk805-pwrkey.ko \
kmod-rk808-regulator.ko \
kmod-rk808.ko \
kmod-rk817-charger.ko \
kmod-rmd160.ko \
kmod-rmtfs-mem.ko \
kmod-rng-core.ko \
kmod-rng.ko \
kmod-rockchip-dfi.ko \
kmod-rockchip-thermal.ko \
kmod-rockchipdrm.ko \
kmod-rohm-bd71828.ko \
kmod-rohm-bd718x7.ko \
kmod-rohm-bd9576.ko \
kmod-rohm-regulator.ko \
kmod-roles.ko \
kmod-rotary-encoder.ko \
kmod-rpcsec-gss-krb5.ko \
kmod-rpi-panel-attiny-regulator.ko \
kmod-rpmhpd.ko \
kmod-rpmpd.ko \
kmod-rpmsg-char.ko \
kmod-rpmsg-core.ko \
kmod-rpmsg-ctrl.ko \
kmod-rpmsg-ns.ko \
kmod-rpmsg-tty.ko \
kmod-rpmsg-wwan-ctrl.ko \
kmod-rsa-generic.ko \
kmod-rt4801-regulator.ko \
kmod-rt4803.ko \
kmod-rt4831-backlight.ko \
kmod-rt4831-regulator.ko \
kmod-rt4831.ko \
kmod-rt5033-battery.ko \
kmod-rt5190a-regulator.ko \
kmod-rt5739.ko \
kmod-rt5759-regulator.ko \
kmod-rt6160-regulator.ko \
kmod-rt6190-regulator.ko \
kmod-rt6245-regulator.ko \
kmod-rt9455-charger.ko \
kmod-rt9467-charger.ko \
kmod-rt9471.ko \
kmod-rtc-ac100.ko \
kmod-rtc-armada38x.ko \
kmod-rtc-bd70528.ko \
kmod-rtc-brcmstb-waketimer.ko \
kmod-rtc-cadence.ko \
kmod-rtc-ds1685.ko \
kmod-rtc-efi.ko \
kmod-rtc-fsl-ftm-alarm.ko \
kmod-rtc-ftrtc010.ko \
kmod-rtc-goldfish.ko \
kmod-rtc-imx-sc.ko \
kmod-rtc-imxdi.ko \
kmod-rtc-isl12026.ko \
kmod-rtc-max77686.ko \
kmod-rtc-meson-vrtc.ko \
kmod-rtc-mt2712.ko \
kmod-rtc-mt7622.ko \
kmod-rtc-mv.ko \
kmod-rtc-mxc-v2.ko \
kmod-rtc-mxc.ko \
kmod-rtc-nct3018y.ko \
kmod-rtc-nxp-bbnsm.ko \
kmod-rtc-optee.ko \
kmod-rtc-pl030.ko \
kmod-rtc-pl031.ko \
kmod-rtc-r7301.ko \
kmod-rtc-rk808.ko \
kmod-rtc-rv3032.ko \
kmod-rtc-rx8025.ko \
kmod-rtc-s3c.ko \
kmod-rtc-sh.ko \
kmod-rtc-tegra.ko \
kmod-rtc-xgene.ko \
kmod-rtc-zynqmp.ko \
kmod-rtmv20-regulator.ko \
kmod-rtq2134-regulator.ko \
kmod-rtq6752-regulator.ko \
kmod-rz-dmac.ko \
kmod-rza-wdt.ko \
kmod-rzg2l-thermal.ko \
kmod-rzg2l-wdt.ko \
kmod-rzn1-wdt.ko \
kmod-rzv2m-usb3drd.ko \
kmod-s3c2410-wdt.ko \
kmod-s5p-cec.ko \
kmod-samsung-tty.ko \
kmod-sata-dwc-460ex.ko \
kmod-sata-rcar.ko \
kmod-sbrmi.ko \
kmod-sbs-manager.ko \
kmod-sbsa-gwdt.ko \
kmod-sbtsi-temp.ko \
kmod-sc9860-clk.ko \
kmod-sc9863a-clk.ko \
kmod-sclk-div.ko \
kmod-scmi-core.ko \
kmod-scmi-cpufreq.ko \
kmod-scmi-hwmon.ko \
kmod-scmi-module.ko \
kmod-scmi-pm-domain.ko \
kmod-scmi-power-control.ko \
kmod-scmi-regulator.ko \
kmod-scpi-cpufreq.ko \
kmod-scpi-hwmon.ko \
kmod-scpi-pm-domain.ko \
kmod-scsi-common.ko \
kmod-scsi-debug.ko \
kmod-scsi-dh-alua.ko \
kmod-scsi-dh-emc.ko \
kmod-scsi-dh-hp-sw.ko \
kmod-scsi-dh-rdac.ko \
kmod-scsi-mod.ko \
kmod-scsi-transport-fc.ko \
kmod-scsi-transport-iscsi.ko \
kmod-scsi-transport-sas.ko \
kmod-sctp-diag.ko \
kmod-sctp.ko \
kmod-scu-pd.ko \
kmod-sd-mod.ko \
kmod-selftests.ko \
kmod-seqiv.ko \
kmod-serial-core.ko \
kmod-serial-mctrl-gpio.ko \
kmod-serial-tegra.ko \
kmod-serio-raw.ko \
kmod-serio.ko \
kmod-serpent-generic.ko \
kmod-serport.ko \
kmod-sfp.ko \
kmod-sg.ko \
kmod-sh-mobile-lcdcfb.ko \
kmod-sh-sci.ko \
kmod-sha1-ce.ko \
kmod-sha1-generic.ko \
kmod-sha2-ce.ko \
kmod-sha256-arm64.ko \
kmod-sha256-generic.ko \
kmod-sha3-ce.ko \
kmod-sha3-generic.ko \
kmod-sha512-arm64.ko \
kmod-sha512-ce.ko \
kmod-sha512-generic.ko \
kmod-sht15.ko \
kmod-sht4x.ko \
kmod-sii902x.ko \
kmod-sii9234.ko \
kmod-sil-sii8620.ko \
kmod-simple-bridge.ko \
kmod-simple-mfd-i2c.ko \
kmod-simpledrm.ko \
kmod-sit.ko \
kmod-skcipher.ko \
kmod-sky81452-backlight.ko \
kmod-sky81452-regulator.ko \
kmod-sky81452.ko \
kmod-sl28vpd.ko \
kmod-slg51000-regulator.ko \
kmod-slhc.ko \
kmod-slim-qcom-ctrl.ko \
kmod-slimbus.ko \
kmod-sm2-generic.ko \
kmod-sm3-ce.ko \
kmod-sm3-generic.ko \
kmod-sm3-neon.ko \
kmod-sm3.ko \
kmod-sm4-ce-ccm.ko \
kmod-sm4-ce-cipher.ko \
kmod-sm4-ce-gcm.ko \
kmod-sm4-ce.ko \
kmod-sm4-generic.ko \
kmod-sm4-neon.ko \
kmod-sm4.ko \
kmod-smd-rpm.ko \
kmod-smpro-core.ko \
kmod-smpro-errmon.ko \
kmod-smpro-hwmon.ko \
kmod-smpro-misc.ko \
kmod-smsc.ko \
kmod-snet-vdpa.ko \
kmod-snps-udc-core.ko \
kmod-snps-udc-plat.ko \
kmod-snvs-pwrkey.ko \
kmod-soc-button-array.ko \
kmod-soc-imx8m.ko \
kmod-softdog.ko \
kmod-sp805-wdt.ko \
kmod-sparx5-temp.ko \
kmod-spm.ko \
kmod-sprd-dma.ko \
kmod-sprd-drm.ko \
kmod-sprd-iommu.ko \
kmod-sprd-mailbox.ko \
kmod-sprd-serial.ko \
kmod-sprd-thermal.ko \
kmod-sprd-wdt.ko \
kmod-squashfs.ko \
kmod-sr-mod.ko \
kmod-sr-thermal.ko \
kmod-ssd130x-i2c.ko \
kmod-ssd130x.ko \
kmod-ssif-bmc.ko \
kmod-st-drv.ko \
kmod-stm-console.ko \
kmod-stm-core.ko \
kmod-stm-ftrace.ko \
kmod-stm-p-basic.ko \
kmod-stm-p-sys-t.ko \
kmod-stmfx.ko \
kmod-stp.ko \
kmod-stpddc60.ko \
kmod-stpmic1-onkey.ko \
kmod-stpmic1-regulator.ko \
kmod-stpmic1-wdt.ko \
kmod-stpmic1.ko \
kmod-stratix10-rsu.ko \
kmod-stratix10-svc.ko \
kmod-streebog-generic.ko \
kmod-sun4i-drm.ko \
kmod-sun4i-gpadc.ko \
kmod-sun4i-lradc-keys.ko \
kmod-sun4i-tcon.ko \
kmod-sun4i-tv.ko \
kmod-sun50i-a100-ccu.ko \
kmod-sun50i-a100-r-ccu.ko \
kmod-sun50i-a64-ccu.ko \
kmod-sun50i-cpufreq-nvmem.ko \
kmod-sun50i-h6-ccu.ko \
kmod-sun50i-h6-r-ccu.ko \
kmod-sun50i-h616-ccu.ko \
kmod-sun6i-dma.ko \
kmod-sun6i-drc.ko \
kmod-sun6i-mipi-dsi.ko \
kmod-sun6i-msgbox.ko \
kmod-sun6i-rtc-ccu.ko \
kmod-sun8i-a33-mbus.ko \
kmod-sun8i-de2-ccu.ko \
kmod-sun8i-drm-hdmi.ko \
kmod-sun8i-h3-ccu.ko \
kmod-sun8i-mixer.ko \
kmod-sun8i-r-ccu.ko \
kmod-sun8i-tcon-top.ko \
kmod-sun8i-thermal.ko \
kmod-sunrpc.ko \
kmod-sunxi-ccu.ko \
kmod-sunxi-rsb.ko \
kmod-sunxi-wdt.ko \
kmod-surface-gpe.ko \
kmod-surface-hotplug.ko \
kmod-surface3-power.ko \
kmod-surfacepro3-button.ko \
kmod-switchtec.ko \
kmod-sy8106a-regulator.ko \
kmod-sy8824x.ko \
kmod-sy8827n.ko \
kmod-synopsys-edac.ko \
kmod-syscon-reboot-mode.ko \
kmod-syscopyarea.ko \
kmod-sysfillrect.ko \
kmod-sysimgblt.ko \
kmod-t10-pi.ko \
kmod-tap.ko \
kmod-tc358762.ko \
kmod-tc358764.ko \
kmod-tc358767.ko \
kmod-tc358768.ko \
kmod-tc358775.ko \
kmod-tcp-bbr.ko \
kmod-tcp-bic.ko \
kmod-tcp-cdg.ko \
kmod-tcp-cubic.ko \
kmod-tcp-dctcp.ko \
kmod-tcp-diag.ko \
kmod-tcp-highspeed.ko \
kmod-tcp-htcp.ko \
kmod-tcp-hybla.ko \
kmod-tcp-illinois.ko \
kmod-tcp-lp.ko \
kmod-tcp-nv.ko \
kmod-tcp-scalable.ko \
kmod-tcp-vegas.ko \
kmod-tcp-veno.ko \
kmod-tcp-westwood.ko \
kmod-tcp-yeah.ko \
kmod-tcrypt.ko \
kmod-tcsrcc-sm8550.ko \
kmod-tda38640.ko \
kmod-tda998x.ko \
kmod-tee-bnxt-fw.ko \
kmod-tee.ko \
kmod-tegra-aconnect.ko \
kmod-tegra-bpmp-thermal.ko \
kmod-tegra-cec.ko \
kmod-tegra-drm.ko \
kmod-tegra-gmi.ko \
kmod-tegra-kbc.ko \
kmod-tegra-soctherm.ko \
kmod-tegra-tcu.ko \
kmod-tegra-wdt.ko \
kmod-tegra-xudc.ko \
kmod-tegra186-cpufreq.ko \
kmod-tegra186-gpc-dma.ko \
kmod-tegra194-cpufreq.ko \
kmod-tegra20-apb-dma.ko \
kmod-tegra210-adma.ko \
kmod-tegra210-emc.ko \
kmod-tegra30-devfreq.ko \
kmod-thc63lvd1024.ko \
kmod-thermal-mmio.ko \
kmod-thunderbolt-net.ko \
kmod-thunderbolt.ko \
kmod-thunderx-edac.ko \
kmod-thunderx2-pmu.ko \
kmod-ti-dlpc3433.ko \
kmod-ti-sn65dsi83.ko \
kmod-ti-sn65dsi86.ko \
kmod-ti-tfp410.ko \
kmod-ti-tpd12s015.ko \
kmod-tidss.ko \
kmod-timeriomem-rng.ko \
kmod-tiny-power-button.ko \
kmod-tls.ko \
kmod-tm2-touchkey.ko \
kmod-tmp464.ko \
kmod-tmp513.ko \
kmod-torture.ko \
kmod-tpm-crb.ko \
kmod-tpm-ftpm-tee.ko \
kmod-tpm-tis-core.ko \
kmod-tpm-tis-i2c-cr50.ko \
kmod-tpm-tis-i2c.ko \
kmod-tpm-tis-synquacer.ko \
kmod-tpm-tis.ko \
kmod-tpm.ko \
kmod-tps23861.ko \
kmod-tps546d24.ko \
kmod-tps6286x-regulator.ko \
kmod-tps65010.ko \
kmod-tps65132-regulator.ko \
kmod-trusted.ko \
kmod-ts-bm.ko \
kmod-ts-fsm.ko \
kmod-ts-kmp.ko \
kmod-tsnep.ko \
kmod-ttm.ko \
kmod-ttynull.ko \
kmod-tun.ko \
kmod-tunnel4.ko \
kmod-tunnel6.ko \
kmod-turingcc-qcs404.ko \
kmod-turris-mox-rwtm.ko \
kmod-twofish-common.ko \
kmod-twofish-generic.ko \
kmod-txgbe.ko \
kmod-u-ether.ko \
kmod-u-serial.ko \
kmod-uacce.ko \
kmod-ublk-drv.ko \
kmod-ucs1002-power.ko \
kmod-ucs2-string.ko \
kmod-udc-core.ko \
kmod-udc-xilinx.ko \
kmod-udf.ko \
kmod-udp-diag.ko \
kmod-udp-tunnel.ko \
kmod-ug3105-battery.ko \
kmod-uhci-hcd.ko \
kmod-uhid.ko \
kmod-uinput.ko \
kmod-uleds.ko \
kmod-ulpi.ko \
kmod-ultrasoc-smb.ko \
kmod-ums512-clk.ko \
kmod-unix-diag.ko \
kmod-unix.ko \
kmod-usb-common.ko \
kmod-usb-conn-gpio.ko \
kmod-usb-dmac.ko \
kmod-usb-f-acm.ko \
kmod-usb-f-ecm-subset.ko \
kmod-usb-f-ecm.ko \
kmod-usb-f-eem.ko \
kmod-usb-f-fs.ko \
kmod-usb-f-hid.ko \
kmod-usb-f-mass-storage.ko \
kmod-usb-f-ncm.ko \
kmod-usb-f-obex.ko \
kmod-usb-f-printer.ko \
kmod-usb-f-rndis.ko \
kmod-usb-f-serial.ko \
kmod-usb-f-ss-lb.ko \
kmod-usbcore.ko \
kmod-usbdux.ko \
kmod-usbduxfast.ko \
kmod-usbduxsigma.ko \
kmod-usbhid.ko \
kmod-usbmisc-imx.ko \
kmod-utf8data.ko \
kmod-v3d.ko \
kmod-vcpu-stall-detector.ko \
kmod-vctrl-regulator.ko \
kmod-vdpa-sim-blk.ko \
kmod-vdpa-sim-net.ko \
kmod-vdpa-sim.ko \
kmod-vdpa.ko \
kmod-vduse.ko \
kmod-veth.ko \
kmod-vexpress-config.ko \
kmod-vexpress-hwmon.ko \
kmod-vexpress-regulator.ko \
kmod-vexpress-sysreg.ko \
kmod-vfat.ko \
kmod-vhost-iotlb.ko \
kmod-vhost-net.ko \
kmod-vhost-vdpa.ko \
kmod-vhost-vsock.ko \
kmod-vhost.ko \
kmod-vid-pll-div.ko \
kmod-video.ko \
kmod-videocc-sc7180.ko \
kmod-videocc-sc7280.ko \
kmod-videocc-sdm845.ko \
kmod-videocc-sm8150.ko \
kmod-videocc-sm8250.ko \
kmod-virt-dma.ko \
kmod-virtio-balloon.ko \
kmod-virtio-blk.ko \
kmod-virtio-console.ko \
kmod-virtio-dma-buf.ko \
kmod-virtio-gpu.ko \
kmod-virtio-input.ko \
kmod-virtio-iommu.ko \
kmod-virtio-mem.ko \
kmod-virtio-mmio.ko \
kmod-virtio-net.ko \
kmod-virtio-pci-legacy-dev.ko \
kmod-virtio-pci-modern-dev.ko \
kmod-virtio-pci.ko \
kmod-virtio-pmem.ko \
kmod-virtio-ring.ko \
kmod-virtio-rng.ko \
kmod-virtio-scsi.ko \
kmod-virtio-vdpa.ko \
kmod-virtio.ko \
kmod-virtiofs.ko \
kmod-visconti-wdt.ko \
kmod-vivaldi-fmap.ko \
kmod-vmac.ko \
kmod-vmgenid.ko \
kmod-vmk80xx.ko \
kmod-vmw-vmci.ko \
kmod-vmw-vsock-virtio-transport-common.ko \
kmod-vmw-vsock-virtio-transport.ko \
kmod-vmw-vsock-vmci-transport.ko \
kmod-vmwgfx.ko \
kmod-vp-vdpa.ko \
kmod-vqmmc-ipq4019-regulator.ko \
kmod-vrf.ko \
kmod-vringh.ko \
kmod-vsock-diag.ko \
kmod-vsock-loopback.ko \
kmod-vsock.ko \
kmod-vsockmon.ko \
kmod-vx855.ko \
kmod-vxlan.ko \
kmod-watchdog.ko \
kmod-wcd934x.ko \
kmod-wcnss-ctrl.ko \
kmod-wdat-wdt.ko \
kmod-wireguard.ko \
kmod-wm8994-regulator.ko \
kmod-wm8994.ko \
kmod-wp512.ko \
kmod-wpcm450-soc.ko \
kmod-wwan-hwsim.ko \
kmod-wwan.ko \
kmod-x-tables.ko \
kmod-x509-key-parser.ko \
kmod-xcbc.ko \
kmod-xctr.ko \
kmod-xdma.ko \
kmod-xdpe12284.ko \
kmod-xdpe152c4.ko \
kmod-xfrm-algo.ko \
kmod-xfrm-interface.ko \
kmod-xfrm-ipcomp.ko \
kmod-xfrm-user.ko \
kmod-xfrm4-tunnel.ko \
kmod-xfrm6-tunnel.ko \
kmod-xfs.ko \
kmod-xgene-dma.ko \
kmod-xgene-edac.ko \
kmod-xgene-enet-v2.ko \
kmod-xgene-enet.ko \
kmod-xgene-hwmon.ko \
kmod-xgene-rng.ko \
kmod-xgmac-mdio.ko \
kmod-xhci-hcd.ko \
kmod-xhci-histb.ko \
kmod-xhci-mtk-hcd.ko \
kmod-xhci-pci-renesas.ko \
kmod-xhci-pci.ko \
kmod-xhci-plat-hcd.ko \
kmod-xhci-rcar-hcd.ko \
kmod-xhci-tegra.ko \
kmod-xilinx-dma.ko \
kmod-xilinx-dpdma.ko \
kmod-xilinx-gmii2rgmii.ko \
kmod-xilinx-sdfec.ko \
kmod-xilinx-uartps.ko \
kmod-xilinxfb.ko \
kmod-xillybus-class.ko \
kmod-xillyusb.ko \
kmod-xiphera-trng.ko \
kmod-xlnx-vcu.ko \
kmod-xor-neon.ko \
kmod-xor.ko \
kmod-xsk-diag.ko \
kmod-xt-AUDIT.ko \
kmod-xt-CHECKSUM.ko \
kmod-xt-CLASSIFY.ko \
kmod-xt-CONNSECMARK.ko \
kmod-xt-CT.ko \
kmod-xt-DSCP.ko \
kmod-xt-HL.ko \
kmod-xt-HMARK.ko \
kmod-xt-IDLETIMER.ko \
kmod-xt-LED.ko \
kmod-xt-LOG.ko \
kmod-xt-MASQUERADE.ko \
kmod-xt-NETMAP.ko \
kmod-xt-NFLOG.ko \
kmod-xt-NFQUEUE.ko \
kmod-xt-RATEEST.ko \
kmod-xt-REDIRECT.ko \
kmod-xt-SECMARK.ko \
kmod-xt-TCPMSS.ko \
kmod-xt-TCPOPTSTRIP.ko \
kmod-xt-TEE.ko \
kmod-xt-TPROXY.ko \
kmod-xt-TRACE.ko \
kmod-xt-addrtype.ko \
kmod-xt-bpf.ko \
kmod-xt-cgroup.ko \
kmod-xt-cluster.ko \
kmod-xt-comment.ko \
kmod-xt-connbytes.ko \
kmod-xt-connlabel.ko \
kmod-xt-connlimit.ko \
kmod-xt-connmark.ko \
kmod-xt-conntrack.ko \
kmod-xt-cpu.ko \
kmod-xt-dccp.ko \
kmod-xt-devgroup.ko \
kmod-xt-dscp.ko \
kmod-xt-ecn.ko \
kmod-xt-esp.ko \
kmod-xt-hashlimit.ko \
kmod-xt-helper.ko \
kmod-xt-hl.ko \
kmod-xt-ipcomp.ko \
kmod-xt-iprange.ko \
kmod-xt-ipvs.ko \
kmod-xt-l2tp.ko \
kmod-xt-length.ko \
kmod-xt-limit.ko \
kmod-xt-mac.ko \
kmod-xt-mark.ko \
kmod-xt-multiport.ko \
kmod-xt-nat.ko \
kmod-xt-nfacct.ko \
kmod-xt-osf.ko \
kmod-xt-owner.ko \
kmod-xt-physdev.ko \
kmod-xt-pkttype.ko \
kmod-xt-policy.ko \
kmod-xt-quota.ko \
kmod-xt-rateest.ko \
kmod-xt-realm.ko \
kmod-xt-recent.ko \
kmod-xt-sctp.ko \
kmod-xt-set.ko \
kmod-xt-socket.ko \
kmod-xt-state.ko \
kmod-xt-statistic.ko \
kmod-xt-string.ko \
kmod-xt-tcpmss.ko \
kmod-xt-tcpudp.ko \
kmod-xt-time.ko \
kmod-xt-u32.ko \
kmod-xts.ko \
kmod-xxhash-generic.ko \
kmod-xxhash.ko \
kmod-xz-dec.ko \
kmod-z3fold.ko \
kmod-zbud.ko \
kmod-zlib-deflate.ko \
kmod-zlib-inflate.ko \
kmod-zonefs.ko \
kmod-zsmalloc.ko \
kmod-zstd-common.ko \
kmod-zstd-compress.ko \
kmod-zstd-decompress.ko \
kmod-zstd.ko \
kmod-zynqmp-dma.ko \
kmod-zynqmp-dpsub.ko \
kmod-zynqmp-edac.ko \
kmod-zynqmp-ipi-mailbox.ko \
multiversion-kernel"

RDEPENDS:${PN} += "/usr/bin/sh \
awk \
coreutils \
distribution-release \
dracut \
kmod-zstd \
modutils \
perl-Bootloader \
suse-kernel-rpm-scriptlets \
suse-module-tools"

inherit rpm
