SUMMARY = "Support for Technical Reports by US Navy Organizations"
DESCRIPTION = "The navydocs package provides an easy means for creating title \
pages and the following supplementary material pages used in \
technical reports by United States Navy organizations. These \
pages are generated by specifying the page content via a set of \
commands and then calling a macro to create the page at its \
occurence in the document. This package is provided in the hope \
that it proves useful to other Navy organizations, with users \
contributing macros for their organizations."
LICENSE = "LPPL-1.0"

PV = "2023.209.1.1svn41643"

RPM_NAME = "texlive-navydocs-2023.209.1.1svn41643-55.1.noarch.rpm"
RPM_HASH = "9735a3e6b7af2fc3a206767d08ad6f61c50a29e43751f43dc5b6e9c34c90e3d03a5c4cb1f30766f6cf7984b7d0824bb8f817d73b7bf1d5ec9734c6fd8f0717a6"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-navydocs.sty \
texlive-navydocs"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-eso-pic.sty \
tex-fancyhdr.sty \
tex-relsize.sty \
tex-rotating.sty \
tex-setspace.sty \
tex-xparse.sty \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
