SUMMARY = "A two-element sans-serif font"
DESCRIPTION = "Iwona is a two-element sans-serif typeface. It was created as \
an alternative version of the Kurier typeface, which was \
designed in 1975 for a diploma in typeface design at the Warsaw \
Academy of Fine Arts under the supervision of Roman \
Tomaszewski. This distribution contains a significantly \
extended set of characters covering the following modern \
alphabets: latin (including Vietnamese), Cyrillic and Greek as \
well as a number of additional symbols (including mathematical \
symbols). The fonts are prepared in Type 1 and OpenType \
formats. For use with TeX the following encoding files have \
been prepared: T1 (ec), T2 (abc), and OT2--Cyrillic, T5 \
(Vietnamese), OT4, QX, texansi and nonstandard (IL2 for the \
Czech fonts), as well as supporting macros and files defining \
fonts for LaTeX."
LICENSE = "LPPL-1.3c"

PV = "2023.201.0.0.995bsvn19611"

RPM_NAME = "texlive-iwona-2023.201.0.0.995bsvn19611-55.1.noarch.rpm"
RPM_HASH = "8db233a60f97d0e1516e2bafa99753c743f5ca5b944768efbdd2493a8d4a1e944bc486e1739fafd7e36c6c5638f345a31bf9ca3a8b096240010bfd09bc19c0c9"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex(cs-iwona-sc.enc) \
tex(cs-iwona.enc) \
tex(cs-iwonab-sc.tfm) \
tex(cs-iwonab.tfm) \
tex(cs-iwonabi-sc.tfm) \
tex(cs-iwonabi.tfm) \
tex(cs-iwonacb-sc.tfm) \
tex(cs-iwonacb.tfm) \
tex(cs-iwonacbi-sc.tfm) \
tex(cs-iwonacbi.tfm) \
tex(cs-iwonach-sc.tfm) \
tex(cs-iwonach.tfm) \
tex(cs-iwonachi-sc.tfm) \
tex(cs-iwonachi.tfm) \
tex(cs-iwonacl-sc.tfm) \
tex(cs-iwonacl.tfm) \
tex(cs-iwonacli-sc.tfm) \
tex(cs-iwonacli.tfm) \
tex(cs-iwonacm-sc.tfm) \
tex(cs-iwonacm.tfm) \
tex(cs-iwonacmi-sc.tfm) \
tex(cs-iwonacmi.tfm) \
tex(cs-iwonacr-sc.tfm) \
tex(cs-iwonacr.tfm) \
tex(cs-iwonacri-sc.tfm) \
tex(cs-iwonacri.tfm) \
tex(cs-iwonah-sc.tfm) \
tex(cs-iwonah.tfm) \
tex(cs-iwonahi-sc.tfm) \
tex(cs-iwonahi.tfm) \
tex(cs-iwonal-sc.tfm) \
tex(cs-iwonal.tfm) \
tex(cs-iwonali-sc.tfm) \
tex(cs-iwonali.tfm) \
tex(cs-iwonam-sc.tfm) \
tex(cs-iwonam.tfm) \
tex(cs-iwonami-sc.tfm) \
tex(cs-iwonami.tfm) \
tex(cs-iwonar-sc.tfm) \
tex(cs-iwonar.tfm) \
tex(cs-iwonari-sc.tfm) \
tex(cs-iwonari.tfm) \
tex(ec-iwona-sc.enc) \
tex(ec-iwona.enc) \
tex(ec-iwonab-sc.tfm) \
tex(ec-iwonab.tfm) \
tex(ec-iwonabi-sc.tfm) \
tex(ec-iwonabi.tfm) \
tex(ec-iwonacb-sc.tfm) \
tex(ec-iwonacb.tfm) \
tex(ec-iwonacbi-sc.tfm) \
tex(ec-iwonacbi.tfm) \
tex(ec-iwonach-sc.tfm) \
tex(ec-iwonach.tfm) \
tex(ec-iwonachi-sc.tfm) \
tex(ec-iwonachi.tfm) \
tex(ec-iwonacl-sc.tfm) \
tex(ec-iwonacl.tfm) \
tex(ec-iwonacli-sc.tfm) \
tex(ec-iwonacli.tfm) \
tex(ec-iwonacm-sc.tfm) \
tex(ec-iwonacm.tfm) \
tex(ec-iwonacmi-sc.tfm) \
tex(ec-iwonacmi.tfm) \
tex(ec-iwonacr-sc.tfm) \
tex(ec-iwonacr.tfm) \
tex(ec-iwonacri-sc.tfm) \
tex(ec-iwonacri.tfm) \
tex(ec-iwonah-sc.tfm) \
tex(ec-iwonah.tfm) \
tex(ec-iwonahi-sc.tfm) \
tex(ec-iwonahi.tfm) \
tex(ec-iwonal-sc.tfm) \
tex(ec-iwonal.tfm) \
tex(ec-iwonali-sc.tfm) \
tex(ec-iwonali.tfm) \
tex(ec-iwonam-sc.tfm) \
tex(ec-iwonam.tfm) \
tex(ec-iwonami-sc.tfm) \
tex(ec-iwonami.tfm) \
tex(ec-iwonar-sc.tfm) \
tex(ec-iwonar.tfm) \
tex(ec-iwonari-sc.tfm) \
tex(ec-iwonari.tfm) \
tex(ex-iwona.enc) \
tex(ex-iwonab.tfm) \
tex(ex-iwonacb.tfm) \
tex(ex-iwonach.tfm) \
tex(ex-iwonacl.tfm) \
tex(ex-iwonacm.tfm) \
tex(ex-iwonacr.tfm) \
tex(ex-iwonah.tfm) \
tex(ex-iwonal.tfm) \
tex(ex-iwonam.tfm) \
tex(ex-iwonar.tfm) \
tex(greek-iwona.enc) \
tex(greek-iwonab.tfm) \
tex(greek-iwonabi.tfm) \
tex(greek-iwonacb.tfm) \
tex(greek-iwonacbi.tfm) \
tex(greek-iwonach.tfm) \
tex(greek-iwonachi.tfm) \
tex(greek-iwonacl.tfm) \
tex(greek-iwonacli.tfm) \
tex(greek-iwonacm.tfm) \
tex(greek-iwonacmi.tfm) \
tex(greek-iwonacr.tfm) \
tex(greek-iwonacri.tfm) \
tex(greek-iwonah.tfm) \
tex(greek-iwonahi.tfm) \
tex(greek-iwonal.tfm) \
tex(greek-iwonali.tfm) \
tex(greek-iwonam.tfm) \
tex(greek-iwonami.tfm) \
tex(greek-iwonar.tfm) \
tex(greek-iwonari.tfm) \
tex(il2iwona.fd) \
tex(il2iwonac.fd) \
tex(il2iwonal.fd) \
tex(il2iwonalc.fd) \
tex(iwona-cs.map) \
tex(iwona-ec.map) \
tex(iwona-ex.map) \
tex(iwona-greek.map) \
tex(iwona-l7x.map) \
tex(iwona-math.tex) \
tex(iwona-mi.map) \
tex(iwona-qx.map) \
tex(iwona-rm.map) \
tex(iwona-sy.map) \
tex(iwona-t2a.map) \
tex(iwona-t2b.map) \
tex(iwona-t2c.map) \
tex(iwona-t5.map) \
tex(iwona-texnansi.map) \
tex(iwona-ts1.map) \
tex(iwona-wncy.map) \
tex(iwona.map) \
tex(iwona.sty) \
tex(l7x-iwona-sc.enc) \
tex(l7x-iwona.enc) \
tex(l7x-iwonab-sc.tfm) \
tex(l7x-iwonab.tfm) \
tex(l7x-iwonabi-sc.tfm) \
tex(l7x-iwonabi.tfm) \
tex(l7x-iwonacb-sc.tfm) \
tex(l7x-iwonacb.tfm) \
tex(l7x-iwonacbi-sc.tfm) \
tex(l7x-iwonacbi.tfm) \
tex(l7x-iwonach-sc.tfm) \
tex(l7x-iwonach.tfm) \
tex(l7x-iwonachi-sc.tfm) \
tex(l7x-iwonachi.tfm) \
tex(l7x-iwonacl-sc.tfm) \
tex(l7x-iwonacl.tfm) \
tex(l7x-iwonacli-sc.tfm) \
tex(l7x-iwonacli.tfm) \
tex(l7x-iwonacm-sc.tfm) \
tex(l7x-iwonacm.tfm) \
tex(l7x-iwonacmi-sc.tfm) \
tex(l7x-iwonacmi.tfm) \
tex(l7x-iwonacr-sc.tfm) \
tex(l7x-iwonacr.tfm) \
tex(l7x-iwonacri-sc.tfm) \
tex(l7x-iwonacri.tfm) \
tex(l7x-iwonah-sc.tfm) \
tex(l7x-iwonah.tfm) \
tex(l7x-iwonahi-sc.tfm) \
tex(l7x-iwonahi.tfm) \
tex(l7x-iwonal-sc.tfm) \
tex(l7x-iwonal.tfm) \
tex(l7x-iwonali-sc.tfm) \
tex(l7x-iwonali.tfm) \
tex(l7x-iwonam-sc.tfm) \
tex(l7x-iwonam.tfm) \
tex(l7x-iwonami-sc.tfm) \
tex(l7x-iwonami.tfm) \
tex(l7x-iwonar-sc.tfm) \
tex(l7x-iwonar.tfm) \
tex(l7x-iwonari-sc.tfm) \
tex(l7x-iwonari.tfm) \
tex(l7xiwona.fd) \
tex(l7xiwonac.fd) \
tex(l7xiwonal.fd) \
tex(l7xiwonalc.fd) \
tex(ly1iwona.fd) \
tex(ly1iwonac.fd) \
tex(ly1iwonal.fd) \
tex(ly1iwonalc.fd) \
tex(mi-iwona.enc) \
tex(mi-iwonabi.tfm) \
tex(mi-iwonacbi.tfm) \
tex(mi-iwonachi.tfm) \
tex(mi-iwonacli.tfm) \
tex(mi-iwonacmi.tfm) \
tex(mi-iwonacri.tfm) \
tex(mi-iwonahi.tfm) \
tex(mi-iwonali.tfm) \
tex(mi-iwonami.tfm) \
tex(mi-iwonari.tfm) \
tex(omliwona.fd) \
tex(omliwonac.fd) \
tex(omliwonal.fd) \
tex(omliwonalc.fd) \
tex(omsiwona.fd) \
tex(omsiwonac.fd) \
tex(omsiwonal.fd) \
tex(omsiwonalc.fd) \
tex(omxiwona.fd) \
tex(omxiwonac.fd) \
tex(omxiwonal.fd) \
tex(omxiwonalc.fd) \
tex(ot1iwona.fd) \
tex(ot1iwonac.fd) \
tex(ot1iwonacm.fd) \
tex(ot1iwonal.fd) \
tex(ot1iwonalc.fd) \
tex(ot1iwonalcm.fd) \
tex(ot1iwonalm.fd) \
tex(ot1iwonam.fd) \
tex(ot2iwona.fd) \
tex(ot2iwonac.fd) \
tex(ot2iwonal.fd) \
tex(ot2iwonalc.fd) \
tex(ot4iwona.fd) \
tex(ot4iwonac.fd) \
tex(ot4iwonal.fd) \
tex(ot4iwonalc.fd) \
tex(qx-iwona-sc.enc) \
tex(qx-iwona.enc) \
tex(qx-iwonab-sc.tfm) \
tex(qx-iwonab.tfm) \
tex(qx-iwonabi-sc.tfm) \
tex(qx-iwonabi.tfm) \
tex(qx-iwonacb-sc.tfm) \
tex(qx-iwonacb.tfm) \
tex(qx-iwonacbi-sc.tfm) \
tex(qx-iwonacbi.tfm) \
tex(qx-iwonach-sc.tfm) \
tex(qx-iwonach.tfm) \
tex(qx-iwonachi-sc.tfm) \
tex(qx-iwonachi.tfm) \
tex(qx-iwonacl-sc.tfm) \
tex(qx-iwonacl.tfm) \
tex(qx-iwonacli-sc.tfm) \
tex(qx-iwonacli.tfm) \
tex(qx-iwonacm-sc.tfm) \
tex(qx-iwonacm.tfm) \
tex(qx-iwonacmi-sc.tfm) \
tex(qx-iwonacmi.tfm) \
tex(qx-iwonacr-sc.tfm) \
tex(qx-iwonacr.tfm) \
tex(qx-iwonacri-sc.tfm) \
tex(qx-iwonacri.tfm) \
tex(qx-iwonah-sc.tfm) \
tex(qx-iwonah.tfm) \
tex(qx-iwonahi-sc.tfm) \
tex(qx-iwonahi.tfm) \
tex(qx-iwonal-sc.tfm) \
tex(qx-iwonal.tfm) \
tex(qx-iwonali-sc.tfm) \
tex(qx-iwonali.tfm) \
tex(qx-iwonam-sc.tfm) \
tex(qx-iwonam.tfm) \
tex(qx-iwonami-sc.tfm) \
tex(qx-iwonami.tfm) \
tex(qx-iwonar-sc.tfm) \
tex(qx-iwonar.tfm) \
tex(qx-iwonari-sc.tfm) \
tex(qx-iwonari.tfm) \
tex(qxiwona.fd) \
tex(qxiwonac.fd) \
tex(qxiwonal.fd) \
tex(qxiwonalc.fd) \
tex(rm-iwona-sc.enc) \
tex(rm-iwona.enc) \
tex(rm-iwonab-sc.tfm) \
tex(rm-iwonab.tfm) \
tex(rm-iwonabi-sc.tfm) \
tex(rm-iwonabi.tfm) \
tex(rm-iwonacb-sc.tfm) \
tex(rm-iwonacb.tfm) \
tex(rm-iwonacbi-sc.tfm) \
tex(rm-iwonacbi.tfm) \
tex(rm-iwonach-sc.tfm) \
tex(rm-iwonach.tfm) \
tex(rm-iwonachi-sc.tfm) \
tex(rm-iwonachi.tfm) \
tex(rm-iwonacl-sc.tfm) \
tex(rm-iwonacl.tfm) \
tex(rm-iwonacli-sc.tfm) \
tex(rm-iwonacli.tfm) \
tex(rm-iwonacm-sc.tfm) \
tex(rm-iwonacm.tfm) \
tex(rm-iwonacmi-sc.tfm) \
tex(rm-iwonacmi.tfm) \
tex(rm-iwonacr-sc.tfm) \
tex(rm-iwonacr.tfm) \
tex(rm-iwonacri-sc.tfm) \
tex(rm-iwonacri.tfm) \
tex(rm-iwonah-sc.tfm) \
tex(rm-iwonah.tfm) \
tex(rm-iwonahi-sc.tfm) \
tex(rm-iwonahi.tfm) \
tex(rm-iwonal-sc.tfm) \
tex(rm-iwonal.tfm) \
tex(rm-iwonali-sc.tfm) \
tex(rm-iwonali.tfm) \
tex(rm-iwonam-sc.tfm) \
tex(rm-iwonam.tfm) \
tex(rm-iwonami-sc.tfm) \
tex(rm-iwonami.tfm) \
tex(rm-iwonar-sc.tfm) \
tex(rm-iwonar.tfm) \
tex(rm-iwonari-sc.tfm) \
tex(rm-iwonari.tfm) \
tex(sy-iwona.enc) \
tex(sy-iwonabz.tfm) \
tex(sy-iwonacbz.tfm) \
tex(sy-iwonachz.tfm) \
tex(sy-iwonaclz.tfm) \
tex(sy-iwonacmz.tfm) \
tex(sy-iwonacrz.tfm) \
tex(sy-iwonahz.tfm) \
tex(sy-iwonalz.tfm) \
tex(sy-iwonamz.tfm) \
tex(sy-iwonarz.tfm) \
tex(t1iwona.fd) \
tex(t1iwonac.fd) \
tex(t1iwonal.fd) \
tex(t1iwonalc.fd) \
tex(t2a-iwona.enc) \
tex(t2a-iwonab.tfm) \
tex(t2a-iwonabi.tfm) \
tex(t2a-iwonacb.tfm) \
tex(t2a-iwonacbi.tfm) \
tex(t2a-iwonach.tfm) \
tex(t2a-iwonachi.tfm) \
tex(t2a-iwonacl.tfm) \
tex(t2a-iwonacli.tfm) \
tex(t2a-iwonacm.tfm) \
tex(t2a-iwonacmi.tfm) \
tex(t2a-iwonacr.tfm) \
tex(t2a-iwonacri.tfm) \
tex(t2a-iwonah.tfm) \
tex(t2a-iwonahi.tfm) \
tex(t2a-iwonal.tfm) \
tex(t2a-iwonali.tfm) \
tex(t2a-iwonam.tfm) \
tex(t2a-iwonami.tfm) \
tex(t2a-iwonar.tfm) \
tex(t2a-iwonari.tfm) \
tex(t2aiwona.fd) \
tex(t2aiwonac.fd) \
tex(t2aiwonal.fd) \
tex(t2aiwonalc.fd) \
tex(t2b-iwona.enc) \
tex(t2b-iwonab.tfm) \
tex(t2b-iwonabi.tfm) \
tex(t2b-iwonacb.tfm) \
tex(t2b-iwonacbi.tfm) \
tex(t2b-iwonach.tfm) \
tex(t2b-iwonachi.tfm) \
tex(t2b-iwonacl.tfm) \
tex(t2b-iwonacli.tfm) \
tex(t2b-iwonacm.tfm) \
tex(t2b-iwonacmi.tfm) \
tex(t2b-iwonacr.tfm) \
tex(t2b-iwonacri.tfm) \
tex(t2b-iwonah.tfm) \
tex(t2b-iwonahi.tfm) \
tex(t2b-iwonal.tfm) \
tex(t2b-iwonali.tfm) \
tex(t2b-iwonam.tfm) \
tex(t2b-iwonami.tfm) \
tex(t2b-iwonar.tfm) \
tex(t2b-iwonari.tfm) \
tex(t2biwona.fd) \
tex(t2biwonac.fd) \
tex(t2biwonal.fd) \
tex(t2biwonalc.fd) \
tex(t2c-iwona.enc) \
tex(t2c-iwonab.tfm) \
tex(t2c-iwonabi.tfm) \
tex(t2c-iwonacb.tfm) \
tex(t2c-iwonacbi.tfm) \
tex(t2c-iwonach.tfm) \
tex(t2c-iwonachi.tfm) \
tex(t2c-iwonacl.tfm) \
tex(t2c-iwonacli.tfm) \
tex(t2c-iwonacm.tfm) \
tex(t2c-iwonacmi.tfm) \
tex(t2c-iwonacr.tfm) \
tex(t2c-iwonacri.tfm) \
tex(t2c-iwonah.tfm) \
tex(t2c-iwonahi.tfm) \
tex(t2c-iwonal.tfm) \
tex(t2c-iwonali.tfm) \
tex(t2c-iwonam.tfm) \
tex(t2c-iwonami.tfm) \
tex(t2c-iwonar.tfm) \
tex(t2c-iwonari.tfm) \
tex(t2ciwona.fd) \
tex(t2ciwonac.fd) \
tex(t2ciwonal.fd) \
tex(t2ciwonalc.fd) \
tex(t5-iwona-sc.enc) \
tex(t5-iwona.enc) \
tex(t5-iwonab-sc.tfm) \
tex(t5-iwonab.tfm) \
tex(t5-iwonabi-sc.tfm) \
tex(t5-iwonabi.tfm) \
tex(t5-iwonacb-sc.tfm) \
tex(t5-iwonacb.tfm) \
tex(t5-iwonacbi-sc.tfm) \
tex(t5-iwonacbi.tfm) \
tex(t5-iwonach-sc.tfm) \
tex(t5-iwonach.tfm) \
tex(t5-iwonachi-sc.tfm) \
tex(t5-iwonachi.tfm) \
tex(t5-iwonacl-sc.tfm) \
tex(t5-iwonacl.tfm) \
tex(t5-iwonacli-sc.tfm) \
tex(t5-iwonacli.tfm) \
tex(t5-iwonacm-sc.tfm) \
tex(t5-iwonacm.tfm) \
tex(t5-iwonacmi-sc.tfm) \
tex(t5-iwonacmi.tfm) \
tex(t5-iwonacr-sc.tfm) \
tex(t5-iwonacr.tfm) \
tex(t5-iwonacri-sc.tfm) \
tex(t5-iwonacri.tfm) \
tex(t5-iwonah-sc.tfm) \
tex(t5-iwonah.tfm) \
tex(t5-iwonahi-sc.tfm) \
tex(t5-iwonahi.tfm) \
tex(t5-iwonal-sc.tfm) \
tex(t5-iwonal.tfm) \
tex(t5-iwonali-sc.tfm) \
tex(t5-iwonali.tfm) \
tex(t5-iwonam-sc.tfm) \
tex(t5-iwonam.tfm) \
tex(t5-iwonami-sc.tfm) \
tex(t5-iwonami.tfm) \
tex(t5-iwonar-sc.tfm) \
tex(t5-iwonar.tfm) \
tex(t5-iwonari-sc.tfm) \
tex(t5-iwonari.tfm) \
tex(t5iwona.fd) \
tex(t5iwonac.fd) \
tex(t5iwonal.fd) \
tex(t5iwonalc.fd) \
tex(texnansi-iwona-sc.enc) \
tex(texnansi-iwona.enc) \
tex(texnansi-iwonab-sc.tfm) \
tex(texnansi-iwonab.tfm) \
tex(texnansi-iwonabi-sc.tfm) \
tex(texnansi-iwonabi.tfm) \
tex(texnansi-iwonacb-sc.tfm) \
tex(texnansi-iwonacb.tfm) \
tex(texnansi-iwonacbi-sc.tfm) \
tex(texnansi-iwonacbi.tfm) \
tex(texnansi-iwonach-sc.tfm) \
tex(texnansi-iwonach.tfm) \
tex(texnansi-iwonachi-sc.tfm) \
tex(texnansi-iwonachi.tfm) \
tex(texnansi-iwonacl-sc.tfm) \
tex(texnansi-iwonacl.tfm) \
tex(texnansi-iwonacli-sc.tfm) \
tex(texnansi-iwonacli.tfm) \
tex(texnansi-iwonacm-sc.tfm) \
tex(texnansi-iwonacm.tfm) \
tex(texnansi-iwonacmi-sc.tfm) \
tex(texnansi-iwonacmi.tfm) \
tex(texnansi-iwonacr-sc.tfm) \
tex(texnansi-iwonacr.tfm) \
tex(texnansi-iwonacri-sc.tfm) \
tex(texnansi-iwonacri.tfm) \
tex(texnansi-iwonah-sc.tfm) \
tex(texnansi-iwonah.tfm) \
tex(texnansi-iwonahi-sc.tfm) \
tex(texnansi-iwonahi.tfm) \
tex(texnansi-iwonal-sc.tfm) \
tex(texnansi-iwonal.tfm) \
tex(texnansi-iwonali-sc.tfm) \
tex(texnansi-iwonali.tfm) \
tex(texnansi-iwonam-sc.tfm) \
tex(texnansi-iwonam.tfm) \
tex(texnansi-iwonami-sc.tfm) \
tex(texnansi-iwonami.tfm) \
tex(texnansi-iwonar-sc.tfm) \
tex(texnansi-iwonar.tfm) \
tex(texnansi-iwonari-sc.tfm) \
tex(texnansi-iwonari.tfm) \
tex(ts1-iwona.enc) \
tex(ts1-iwonab.tfm) \
tex(ts1-iwonabi.tfm) \
tex(ts1-iwonacb.tfm) \
tex(ts1-iwonacbi.tfm) \
tex(ts1-iwonach.tfm) \
tex(ts1-iwonachi.tfm) \
tex(ts1-iwonacl.tfm) \
tex(ts1-iwonacli.tfm) \
tex(ts1-iwonacm.tfm) \
tex(ts1-iwonacmi.tfm) \
tex(ts1-iwonacr.tfm) \
tex(ts1-iwonacri.tfm) \
tex(ts1-iwonah.tfm) \
tex(ts1-iwonahi.tfm) \
tex(ts1-iwonal.tfm) \
tex(ts1-iwonali.tfm) \
tex(ts1-iwonam.tfm) \
tex(ts1-iwonami.tfm) \
tex(ts1-iwonar.tfm) \
tex(ts1-iwonari.tfm) \
tex(ts1iwona.fd) \
tex(ts1iwonac.fd) \
tex(ts1iwonal.fd) \
tex(ts1iwonalc.fd) \
tex(wncy-iwona.enc) \
tex(wncy-iwonab.tfm) \
tex(wncy-iwonabi.tfm) \
tex(wncy-iwonacb.tfm) \
tex(wncy-iwonacbi.tfm) \
tex(wncy-iwonach.tfm) \
tex(wncy-iwonachi.tfm) \
tex(wncy-iwonacl.tfm) \
tex(wncy-iwonacli.tfm) \
tex(wncy-iwonacm.tfm) \
tex(wncy-iwonacmi.tfm) \
tex(wncy-iwonacr.tfm) \
tex(wncy-iwonacri.tfm) \
tex(wncy-iwonah.tfm) \
tex(wncy-iwonahi.tfm) \
tex(wncy-iwonal.tfm) \
tex(wncy-iwonali.tfm) \
tex(wncy-iwonam.tfm) \
tex(wncy-iwonami.tfm) \
tex(wncy-iwonar.tfm) \
tex(wncy-iwonari.tfm) \
texlive-iwona"

RDEPENDS:${PN} += "/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex(updmap.cfg) \
texlive \
texlive-filesystem \
texlive-iwona-fonts \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
