SUMMARY = "Udev files for libstoragemgmt"
DESCRIPTION = "The libstoragemgmt-udev package contains udev rules and helper utilities for \
uevents generated by the kernel."
LICENSE = "GPL-2.0-or-later & LGPL-2.1-or-later"

PV = "1.9.8"

RPM_NAME = "libstoragemgmt-udev-1.9.8-1.2.aarch64.rpm"
RPM_HASH = "aea32bb0038e919ebb7b3a4ee19416f927b334065dfbf503ea86fb0cebe83f95dfc941d876ac0b355594e3bc5ec08a5a56d9ac6646be497f6754e97049f8a702"

RPROVIDES:${PN} += "libstoragemgmt-udev"

RDEPENDS:${PN} += "/usr/bin/sh \
ld-linux-aarch64.so.1 \
libc.so.6"

inherit rpm
