SUMMARY = "Lua Documentation for lpeg"
DESCRIPTION = "Documentation and examples included with the library, sometimes \
generated by luadoc or ldoc."
LICENSE = "MIT"

PV = "1.0.2"

RPM_NAME = "lua54-lpeg-doc-1.0.2-6.3.noarch.rpm"
RPM_HASH = "62ecd2d4257f4e6680d307ca52017c420cf1131d0ffd185942aba1c105181208f8cbf3f0ebb0bd5a5383e5c952278323dbc8cb77c76cbe9e758813b2343cca20"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "lua54-lpeg-doc"

RDEPENDS:${PN} += "lua54-lpeg"

inherit rpm
