SUMMARY = "Lua Documentation for lpeg"
DESCRIPTION = "Documentation and examples included with the library, sometimes \
generated by luadoc or ldoc."
LICENSE = "MIT"

PV = "1.1.0"

RPM_NAME = "lua54-lpeg-doc-1.1.0-1.1.noarch.rpm"
RPM_HASH = "080558863c855de177d295c1dce3a4dfa1d4d0efdf0b1dc701668d30c1e2b2f78f11161d19b649ae386d0232377e95263978ab2bff4cc596b41b32b86ec6369d"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "lua54-lpeg-doc"

RDEPENDS:${PN} += "lua54-lpeg"

inherit rpm
