SUMMARY = "Printer drivers for CUPS from the Gutenprint project"
DESCRIPTION = "The Gutenprint (formerly Gimp-Print) printer drivers for CUPS. \
See the user's manual at /usr/share/gutenprint/doc/gutenprint-users-manual.pdf"
LICENSE = "GPL-2.0-or-later"

PV = "5.3.4"

RPM_NAME = "gutenprint-5.3.4-1.2.aarch64.rpm"
RPM_HASH = "984876b1a42d5c059d051165a7cfb2dcb5b27fd1994df91e109f33fdb11d16f44fdb1124f12f77259c553eecee23789a9aa9b495b8a71e1ff75f3548c0a461c5"

RPROVIDES:${PN} += "config-gutenprint \
gutenprint \
libgutenprint.so.9 \
libgutenprintui2.so.2 \
postscriptdriver-brother;brother-hl-1450-series; \
postscriptdriver-brother;brother-hl-1470n-series; \
postscriptdriver-brother;brother-hl-2460-series; \
postscriptdriver-brother;brother-hl-5050-series; \
postscriptdriver-brother;brother-hl-5070n-series; \
postscriptdriver-brother;brother-hl-5150d-series; \
postscriptdriver-brother;brother-hl-5170dn-series; \
postscriptdriver-brother;brother-hl-7050-series; \
postscriptdriver-brother;hl-1050-series; \
postscriptdriver-brother;hl-1070-series; \
postscriptdriver-brother;hl-1240-series; \
postscriptdriver-brother;hl-1250-series; \
postscriptdriver-brother;hl-1440-series; \
postscriptdriver-brother;hl-5040-series; \
postscriptdriver-brother;hl-5140-series; \
postscriptdriver-brother;hl-5340d-series; \
postscriptdriver-canon;bjc-1000; \
postscriptdriver-canon;bjc-2100; \
postscriptdriver-canon;bjc-210; \
postscriptdriver-canon;bjc-250; \
postscriptdriver-canon;bjc-3000; \
postscriptdriver-canon;bjc-4300; \
postscriptdriver-canon;bjc-4400; \
postscriptdriver-canon;bjc-50; \
postscriptdriver-canon;bjc-55; \
postscriptdriver-canon;bjc-6000; \
postscriptdriver-canon;bjc-6200; \
postscriptdriver-canon;bjc-80; \
postscriptdriver-canon;bjc-8200; \
postscriptdriver-canon;bjc-85; \
postscriptdriver-canon;cp-100; \
postscriptdriver-canon;cp-10; \
postscriptdriver-canon;cp-200; \
postscriptdriver-canon;cp-220; \
postscriptdriver-canon;cp-300; \
postscriptdriver-canon;cp-330; \
postscriptdriver-canon;cp1000; \
postscriptdriver-canon;cp400; \
postscriptdriver-canon;cp500; \
postscriptdriver-canon;cp510; \
postscriptdriver-canon;cp530; \
postscriptdriver-canon;cp600; \
postscriptdriver-canon;cp710; \
postscriptdriver-canon;cp720; \
postscriptdriver-canon;cp730; \
postscriptdriver-canon;cp750; \
postscriptdriver-canon;cp760; \
postscriptdriver-canon;cp780; \
postscriptdriver-canon;cp790; \
postscriptdriver-canon;cp800; \
postscriptdriver-canon;cp810; \
postscriptdriver-canon;cp820; \
postscriptdriver-canon;cp900; \
postscriptdriver-canon;cp910; \
postscriptdriver-canon;es1; \
postscriptdriver-canon;es2; \
postscriptdriver-canon;es30; \
postscriptdriver-canon;es3; \
postscriptdriver-canon;es40; \
postscriptdriver-canon;ip2700-series; \
postscriptdriver-canon;ip3000; \
postscriptdriver-canon;ip4000; \
postscriptdriver-canon;ip4200; \
postscriptdriver-canon;ip8500; \
postscriptdriver-canon;lbp-1000; \
postscriptdriver-canon;mg5400-series; \
postscriptdriver-canon;mg6800-series; \
postscriptdriver-canon;mp160; \
postscriptdriver-canon;mp230-series; \
postscriptdriver-canon;mp250-series; \
postscriptdriver-canon;mp280-series; \
postscriptdriver-canon;mp450; \
postscriptdriver-canon;mp500; \
postscriptdriver-canon;pro9000ii-series; \
postscriptdriver-canon;s100sp; \
postscriptdriver-canon;s600; \
postscriptdriver-canon;selphy-cp1200; \
postscriptdriver-canon;selphy-cp1300; \
postscriptdriver-ciaat;brava21; \
postscriptdriver-citizen-systems;cx-02; \
postscriptdriver-citizen-systems;cx; \
postscriptdriver-dai-nippon-printing;dp-ds620; \
postscriptdriver-dai-nippon-printing;dp-ds820; \
postscriptdriver-dai-nippon-printing;dp-qw410; \
postscriptdriver-dai-nippon-printing;ds-rx1; \
postscriptdriver-dai-nippon-printing;ds40; \
postscriptdriver-dai-nippon-printing;ds80; \
postscriptdriver-datamax-o'neil;e4204b-mark-iii; \
postscriptdriver-datamax-o'neil;e4205a-mark-iii; \
postscriptdriver-datamax-o'neil;e4206l-mark-iii; \
postscriptdriver-datamax-o'neil;e4206p-mark-iii; \
postscriptdriver-datamax-o'neil;e4304b-mark-iii; \
postscriptdriver-datamax-o'neil;e4305a-mark-iii; \
postscriptdriver-datamax-o'neil;e4305l-mark-iii; \
postscriptdriver-datamax-o'neil;e4305p-mark-iii; \
postscriptdriver-datamax-o'neil;i4212e-mark-ii; \
postscriptdriver-datamax-o'neil;i4310e-mark-ii; \
postscriptdriver-datamax-o'neil;i4606e-mark-ii; \
postscriptdriver-datamax-o'neil;rl3e; \
postscriptdriver-datamax-o'neil;rl4e; \
postscriptdriver-datamax;h4212; \
postscriptdriver-datamax;h4212x; \
postscriptdriver-datamax;h4310; \
postscriptdriver-datamax;h4310x; \
postscriptdriver-datamax;h4408; \
postscriptdriver-datamax;h4606; \
postscriptdriver-datamax;h4606x; \
postscriptdriver-datamax;h6210; \
postscriptdriver-datamax;h6210x; \
postscriptdriver-datamax;h6212; \
postscriptdriver-datamax;h6212x; \
postscriptdriver-datamax;h6308; \
postscriptdriver-datamax;h6310x; \
postscriptdriver-datamax;h8308; \
postscriptdriver-datamax;h8308x; \
postscriptdriver-datamaxoneil-;h8308p; \
postscriptdriver-datamaxoneil-;p1115; \
postscriptdriver-datamaxoneil-;p1115s; \
postscriptdriver-datamaxoneil-;p1120n; \
postscriptdriver-datamaxoneil-;p1125; \
postscriptdriver-datamaxoneil-;p1725; \
postscriptdriver-datamaxoneil-;w1110; \
postscriptdriver-eastman-kodak-company;1400-printer; \
postscriptdriver-eastman-kodak-company;kodak-7000-photo-printer; \
postscriptdriver-eastman-kodak-company;kodak-7010-photo-printer; \
postscriptdriver-eastman-kodak-company;kodak-805-photo-printer; \
postscriptdriver-eastman-kodak-company;kodak-8810-photo-printer; \
postscriptdriver-eastman-kodak-company;kodak-photo-printer-8800; \
postscriptdriver-eastman-kodak-company;photo-printer-6800; \
postscriptdriver-eastman-kodak-company;photo-printer-6850; \
postscriptdriver-epson;al-c2000-ps3; \
postscriptdriver-epson;al-c8600-ps3; \
postscriptdriver-epson;epl-5700; \
postscriptdriver-epson;epl-5900-ps3; \
postscriptdriver-epson;epl-6100-ps3; \
postscriptdriver-epson;epl-n2500-ps3; \
postscriptdriver-epson;epson-stylus-pro-3880; \
postscriptdriver-epson;sc-p400-series; \
postscriptdriver-epson;sc-p600-series; \
postscriptdriver-epson;stylus-c20; \
postscriptdriver-epson;stylus-c40; \
postscriptdriver-epson;stylus-c42; \
postscriptdriver-epson;stylus-c43; \
postscriptdriver-epson;stylus-c44; \
postscriptdriver-epson;stylus-c45; \
postscriptdriver-epson;stylus-c46; \
postscriptdriver-epson;stylus-c48; \
postscriptdriver-epson;stylus-c60; \
postscriptdriver-epson;stylus-c62; \
postscriptdriver-epson;stylus-c65; \
postscriptdriver-epson;stylus-c66; \
postscriptdriver-epson;stylus-c68; \
postscriptdriver-epson;stylus-c80; \
postscriptdriver-epson;stylus-c82; \
postscriptdriver-epson;stylus-c84; \
postscriptdriver-epson;stylus-c85; \
postscriptdriver-epson;stylus-c86; \
postscriptdriver-epson;stylus-c88; \
postscriptdriver-epson;stylus-c92; \
postscriptdriver-epson;stylus-color-1520; \
postscriptdriver-epson;stylus-color-440; \
postscriptdriver-epson;stylus-color-460; \
postscriptdriver-epson;stylus-color-480; \
postscriptdriver-epson;stylus-color-600; \
postscriptdriver-epson;stylus-color-670; \
postscriptdriver-epson;stylus-color-680; \
postscriptdriver-epson;stylus-color-740; \
postscriptdriver-epson;stylus-color-760; \
postscriptdriver-epson;stylus-color-777; \
postscriptdriver-epson;stylus-color-800; \
postscriptdriver-epson;stylus-color-880; \
postscriptdriver-epson;stylus-color-900; \
postscriptdriver-epson;stylus-color-980; \
postscriptdriver-epson;stylus-cx1500; \
postscriptdriver-epson;stylus-cx3100; \
postscriptdriver-epson;stylus-cx3200; \
postscriptdriver-epson;stylus-cx3500; \
postscriptdriver-epson;stylus-cx3600; \
postscriptdriver-epson;stylus-cx3650; \
postscriptdriver-epson;stylus-cx3700; \
postscriptdriver-epson;stylus-cx3800; \
postscriptdriver-epson;stylus-cx3805; \
postscriptdriver-epson;stylus-cx3810; \
postscriptdriver-epson;stylus-cx3900; \
postscriptdriver-epson;stylus-cx4100; \
postscriptdriver-epson;stylus-cx4200; \
postscriptdriver-epson;stylus-cx4500; \
postscriptdriver-epson;stylus-cx4600; \
postscriptdriver-epson;stylus-cx4700; \
postscriptdriver-epson;stylus-cx4800; \
postscriptdriver-epson;stylus-cx5100; \
postscriptdriver-epson;stylus-cx5300; \
postscriptdriver-epson;stylus-cx5400; \
postscriptdriver-epson;stylus-cx5700; \
postscriptdriver-epson;stylus-cx5800; \
postscriptdriver-epson;stylus-cx6300; \
postscriptdriver-epson;stylus-cx6500; \
postscriptdriver-epson;stylus-cx6600; \
postscriptdriver-epson;stylus-cx7700; \
postscriptdriver-epson;stylus-cx7800; \
postscriptdriver-epson;stylus-cx8300; \
postscriptdriver-epson;stylus-cx8400; \
postscriptdriver-epson;stylus-d68; \
postscriptdriver-epson;stylus-d78; \
postscriptdriver-epson;stylus-d88; \
postscriptdriver-epson;stylus-d92; \
postscriptdriver-epson;stylus-dx3800; \
postscriptdriver-epson;stylus-dx3850; \
postscriptdriver-epson;stylus-dx4200; \
postscriptdriver-epson;stylus-dx4250; \
postscriptdriver-epson;stylus-dx4800; \
postscriptdriver-epson;stylus-photo-1270; \
postscriptdriver-epson;stylus-photo-1400; \
postscriptdriver-epson;stylus-photo-700; \
postscriptdriver-epson;stylus-photo-750; \
postscriptdriver-epson;stylus-photo-785epx; \
postscriptdriver-epson;stylus-photo-790; \
postscriptdriver-epson;stylus-photo-820; \
postscriptdriver-epson;stylus-photo-825; \
postscriptdriver-epson;stylus-photo-830u; \
postscriptdriver-epson;stylus-photo-870; \
postscriptdriver-epson;stylus-photo-890; \
postscriptdriver-epson;stylus-photo-895; \
postscriptdriver-epson;stylus-photo-900; \
postscriptdriver-epson;stylus-photo-915; \
postscriptdriver-epson;stylus-photo-935; \
postscriptdriver-epson;stylus-photo-ex; \
postscriptdriver-epson;stylus-photo-r200; \
postscriptdriver-epson;stylus-photo-r210; \
postscriptdriver-epson;stylus-photo-r220; \
postscriptdriver-epson;stylus-photo-r230; \
postscriptdriver-epson;stylus-photo-r2400; \
postscriptdriver-epson;stylus-photo-r300; \
postscriptdriver-epson;stylus-photo-r310; \
postscriptdriver-epson;stylus-photo-r320; \
postscriptdriver-epson;stylus-photo-r340; \
postscriptdriver-epson;stylus-photo-rx400; \
postscriptdriver-epson;stylus-photo-rx420; \
postscriptdriver-epson;stylus-photo-rx425; \
postscriptdriver-epson;stylus-photo-rx430; \
postscriptdriver-epson;stylus-photo-rx500; \
postscriptdriver-epson;stylus-photo-rx510; \
postscriptdriver-epson;stylus-photo-rx620; \
postscriptdriver-epson;stylus-photo-rx630; \
postscriptdriver-epson;stylus-photo-rx700; \
postscriptdriver-epson;stylus-pro-7900; \
postscriptdriver-epson;stylus-pro-9900; \
postscriptdriver-epson;xp-15000-series; \
postscriptdriver-fujifilm;ask-printer; \
postscriptdriver-hewlett-packard;deskjet-1120c; \
postscriptdriver-hewlett-packard;deskjet-1220c; \
postscriptdriver-hewlett-packard;deskjet-3820; \
postscriptdriver-hewlett-packard;deskjet-600; \
postscriptdriver-hewlett-packard;deskjet-610c; \
postscriptdriver-hewlett-packard;deskjet-640c; \
postscriptdriver-hewlett-packard;deskjet-660c; \
postscriptdriver-hewlett-packard;deskjet-670c; \
postscriptdriver-hewlett-packard;deskjet-690c; \
postscriptdriver-hewlett-packard;deskjet-810c; \
postscriptdriver-hewlett-packard;deskjet-815c; \
postscriptdriver-hewlett-packard;deskjet-825c; \
postscriptdriver-hewlett-packard;deskjet-840c; \
postscriptdriver-hewlett-packard;deskjet-841c; \
postscriptdriver-hewlett-packard;deskjet-843c; \
postscriptdriver-hewlett-packard;deskjet-845c; \
postscriptdriver-hewlett-packard;deskjet-850c; \
postscriptdriver-hewlett-packard;deskjet-870c; \
postscriptdriver-hewlett-packard;deskjet-880c; \
postscriptdriver-hewlett-packard;deskjet-890c; \
postscriptdriver-hewlett-packard;deskjet-895c; \
postscriptdriver-hewlett-packard;deskjet-920c; \
postscriptdriver-hewlett-packard;deskjet-930c; \
postscriptdriver-hewlett-packard;deskjet-940c; \
postscriptdriver-hewlett-packard;deskjet-950c; \
postscriptdriver-hewlett-packard;deskjet-960c; \
postscriptdriver-hewlett-packard;deskjet-970c; \
postscriptdriver-hewlett-packard;deskjet-980c; \
postscriptdriver-hewlett-packard;deskjet-990c; \
postscriptdriver-hewlett-packard;hp-business-inkjet-2200; \
postscriptdriver-hewlett-packard;hp-business-inkjet-2230; \
postscriptdriver-hewlett-packard;hp-business-inkjet-2250; \
postscriptdriver-hewlett-packard;hp-business-inkjet-2280; \
postscriptdriver-hewlett-packard;hp-color-inkjet-cp1700; \
postscriptdriver-hewlett-packard;hp-color-laserjet-2500; \
postscriptdriver-hewlett-packard;hp-color-laserjet-4550; \
postscriptdriver-hewlett-packard;hp-color-laserjet-4600; \
postscriptdriver-hewlett-packard;hp-color-laserjet-4610; \
postscriptdriver-hewlett-packard;hp-color-laserjet-4650; \
postscriptdriver-hewlett-packard;hp-deskjet-340; \
postscriptdriver-hewlett-packard;hp-deskjet-400; \
postscriptdriver-hewlett-packard;hp-laserjet-1010; \
postscriptdriver-hewlett-packard;hp-laserjet-1012; \
postscriptdriver-hewlett-packard;hp-laserjet-1015; \
postscriptdriver-hewlett-packard;hp-laserjet-1100; \
postscriptdriver-hewlett-packard;hp-laserjet-1150; \
postscriptdriver-hewlett-packard;hp-laserjet-1160-series; \
postscriptdriver-hewlett-packard;hp-laserjet-1200; \
postscriptdriver-hewlett-packard;hp-laserjet-1220; \
postscriptdriver-hewlett-packard;hp-laserjet-1300; \
postscriptdriver-hewlett-packard;hp-laserjet-1320-series; \
postscriptdriver-hewlett-packard;hp-laserjet-2100-series; \
postscriptdriver-hewlett-packard;hp-laserjet-2200; \
postscriptdriver-hewlett-packard;hp-laserjet-2300-series; \
postscriptdriver-hewlett-packard;hp-laserjet-2420; \
postscriptdriver-hewlett-packard;hp-laserjet-2430; \
postscriptdriver-hewlett-packard;hp-laserjet-3015; \
postscriptdriver-hewlett-packard;hp-laserjet-3020; \
postscriptdriver-hewlett-packard;hp-laserjet-3030; \
postscriptdriver-hewlett-packard;hp-laserjet-3050; \
postscriptdriver-hewlett-packard;hp-laserjet-3052; \
postscriptdriver-hewlett-packard;hp-laserjet-3055; \
postscriptdriver-hewlett-packard;hp-laserjet-3200; \
postscriptdriver-hewlett-packard;hp-laserjet-3200m; \
postscriptdriver-hewlett-packard;hp-laserjet-3300/3310/3320; \
postscriptdriver-hewlett-packard;hp-laserjet-3330; \
postscriptdriver-hewlett-packard;hp-laserjet-3380; \
postscriptdriver-hewlett-packard;hp-laserjet-3390; \
postscriptdriver-hewlett-packard;hp-laserjet-4-plus; \
postscriptdriver-hewlett-packard;hp-laserjet-4000-series; \
postscriptdriver-hewlett-packard;hp-laserjet-4050-series; \
postscriptdriver-hewlett-packard;hp-laserjet-4100-series; \
postscriptdriver-hewlett-packard;hp-laserjet-4200; \
postscriptdriver-hewlett-packard;hp-laserjet-4250; \
postscriptdriver-hewlett-packard;hp-laserjet-4300; \
postscriptdriver-hewlett-packard;hp-laserjet-4350; \
postscriptdriver-hewlett-packard;hp-laserjet-5000-series; \
postscriptdriver-hewlett-packard;hp-laserjet-5100-series; \
postscriptdriver-hewlett-packard;hp-laserjet-5l; \
postscriptdriver-hewlett-packard;hp-laserjet-5mp; \
postscriptdriver-hewlett-packard;hp-laserjet-5n; \
postscriptdriver-hewlett-packard;hp-laserjet-5p; \
postscriptdriver-hewlett-packard;hp-laserjet-5si; \
postscriptdriver-hewlett-packard;hp-laserjet-6l; \
postscriptdriver-hewlett-packard;hp-laserjet-6mp; \
postscriptdriver-hewlett-packard;hp-laserjet-6p; \
postscriptdriver-hewlett-packard;hp-laserjet-8000-series; \
postscriptdriver-hewlett-packard;hp-laserjet-8150-series; \
postscriptdriver-hewlett-packard;hp-laserjet-m3027-mfp; \
postscriptdriver-hewlett-packard;hp-laserjet-m3035-mfp; \
postscriptdriver-hewlett-packard;hp-laserjet-p2010-series; \
postscriptdriver-hewlett-packard;hp-laserjet-p2015-series; \
postscriptdriver-hewlett-packard;hp-laserjet-p3004-series; \
postscriptdriver-hewlett-packard;hp-laserjet-p3005; \
postscriptdriver-hewlett-packard;laserjet-4l; \
postscriptdriver-hewlett-packard;laserjet-color-4500; \
postscriptdriver-hewlett-packard;officejet--k60; \
postscriptdriver-hewlett-packard;officejet--k60xi; \
postscriptdriver-hewlett-packard;officejet--k80; \
postscriptdriver-hewlett-packard;officejet--k80xi; \
postscriptdriver-hewlett-packard;officejet-5105; \
postscriptdriver-hewlett-packard;officejet-5110v; \
postscriptdriver-hewlett-packard;officejet-6100-series; \
postscriptdriver-hewlett-packard;officejet-7100-series; \
postscriptdriver-hewlett-packard;officejet-d-series; \
postscriptdriver-hewlett-packard;officejet-g55; \
postscriptdriver-hewlett-packard;officejet-g85; \
postscriptdriver-hewlett-packard;officejet-g95; \
postscriptdriver-hewlett-packard;officejet-pro-1150c; \
postscriptdriver-hewlett-packard;officejet-pro-1170c-series; \
postscriptdriver-hewlett-packard;officejet-r40; \
postscriptdriver-hewlett-packard;officejet-r60; \
postscriptdriver-hewlett-packard;officejet-r65; \
postscriptdriver-hewlett-packard;officejet-r80; \
postscriptdriver-hewlett-packard;officejet-series-300; \
postscriptdriver-hewlett-packard;officejet-series-500; \
postscriptdriver-hewlett-packard;officejet-series-600; \
postscriptdriver-hewlett-packard;officejet-series-700; \
postscriptdriver-hewlett-packard;officejet-t-series; \
postscriptdriver-hewlett-packard;officejet-v40; \
postscriptdriver-hewlett-packard;officejet-v40xi; \
postscriptdriver-hewlett-packard;officejet; \
postscriptdriver-hewlett-packard;photosmart-p1000; \
postscriptdriver-hewlett-packard;photosmart-p1100; \
postscriptdriver-hewlett-packard;printer/scanner/copier-300; \
postscriptdriver-hewlett-packard;psc-2100-series; \
postscriptdriver-hewlett-packard;psc-2150-series; \
postscriptdriver-hewlett-packard;psc-2200-series; \
postscriptdriver-hewlett-packard;psc-500; \
postscriptdriver-hewlett-packard;psc-750; \
postscriptdriver-hewlett-packard;psc-900-series; \
postscriptdriver-hiti;hiti-p720l; \
postscriptdriver-hiti;p520l; \
postscriptdriver-hiti;p525l; \
postscriptdriver-hiti;p750l; \
postscriptdriver-honeywell;rp2; \
postscriptdriver-honeywell;rp4; \
postscriptdriver-hp;deskjet-5550; \
postscriptdriver-hp;deskjet-6122; \
postscriptdriver-hp;dj450; \
postscriptdriver-hp;photosmart-100; \
postscriptdriver-hp;photosmart-1115; \
postscriptdriver-hp;photosmart-1218; \
postscriptdriver-hp;photosmart-1315; \
postscriptdriver-hp;photosmart-7150; \
postscriptdriver-hp;photosmart-7350; \
postscriptdriver-hp;photosmart-7550; \
postscriptdriver-ibm;infoprint; \
postscriptdriver-kodak-alaris-inc.;kodak-6900-photo-printer; \
postscriptdriver-kodak;305-photo-printer; \
postscriptdriver-kyocera-mita;km-1530; \
postscriptdriver-kyocera-mita;km-1810; \
postscriptdriver-kyocera-mita;km-2030; \
postscriptdriver-kyocera-mita;km-2530; \
postscriptdriver-kyocera-mita;km-3530; \
postscriptdriver-kyocera-mita;km-4230; \
postscriptdriver-kyocera-mita;km-4530; \
postscriptdriver-kyocera-mita;km-5230; \
postscriptdriver-kyocera-mita;km-5530; \
postscriptdriver-kyocera-mita;km-6230; \
postscriptdriver-kyocera-mita;kyocera-mita-fs-1010; \
postscriptdriver-kyocera-mita;kyocera-mita-fs-1050; \
postscriptdriver-kyocera-mita;kyocera-mita-fs-1800; \
postscriptdriver-kyocera-mita;kyocera-mita-fs-1900; \
postscriptdriver-kyocera-mita;kyocera-mita-fs-3800; \
postscriptdriver-kyocera-mita;kyocera-mita-fs-8000c; \
postscriptdriver-kyocera-mita;kyocera-mita-fs-9100dn; \
postscriptdriver-kyocera-mita;kyocera-mita-fs-9500dn; \
postscriptdriver-kyocera;f-1010; \
postscriptdriver-kyocera;fs-1118mfp; \
postscriptdriver-kyocera;fs-1135mfp; \
postscriptdriver-kyocera;fs-1600; \
postscriptdriver-kyocera;fs-3500; \
postscriptdriver-kyocera;fs-3600; \
postscriptdriver-kyocera;fs-6500; \
postscriptdriver-kyocera;kyocera-fs-1000; \
postscriptdriver-kyocera;kyocera-fs-1200; \
postscriptdriver-kyocera;kyocera-fs-1700; \
postscriptdriver-kyocera;kyocera-fs-1750; \
postscriptdriver-kyocera;kyocera-fs-3700; \
postscriptdriver-kyocera;kyocera-fs-3750; \
postscriptdriver-kyocera;kyocera-fs-5800c; \
postscriptdriver-kyocera;kyocera-fs-5900c; \
postscriptdriver-kyocera;kyocera-fs-600; \
postscriptdriver-kyocera;kyocera-fs-6700; \
postscriptdriver-kyocera;kyocera-fs-680; \
postscriptdriver-kyocera;kyocera-fs-7000; \
postscriptdriver-kyocera;kyocera-fs-800; \
postscriptdriver-kyocera;kyocera-fs-9000; \
postscriptdriver-lexmark-international;ibm-3112-page-printer; \
postscriptdriver-lexmark-international;lexmark-e321; \
postscriptdriver-lexmark;lexmark-x73; \
postscriptdriver-lexmark;lexmark-z42; \
postscriptdriver-lexmark;lexmark-z52; \
postscriptdriver-magicard;riotango2d; \
postscriptdriver-minolta;pagepro---6e; \
postscriptdriver-minolta;pagepro-1100; \
postscriptdriver-minolta;pagepro-6; \
postscriptdriver-minolta;pagepro-8; \
postscriptdriver-minolta;pagepro-8l; \
postscriptdriver-mitsubishi;cp-m1; \
postscriptdriver-mitsubishi;cp30d; \
postscriptdriver-mitsubishi;cp60d70d707d; \
postscriptdriver-mitsubishi;cp9550d; \
postscriptdriver-mitsubishi;cp9550dz; \
postscriptdriver-mitsubishi;cp9800dz; \
postscriptdriver-mitsubishi;cpd80d; \
postscriptdriver-mitsubishi;cpd90d; \
postscriptdriver-mitsubishi;p93d; \
postscriptdriver-mitsubishi;p95d; \
postscriptdriver-nec;superscript-1800; \
postscriptdriver-nec;superscript-870; \
postscriptdriver-oki-data-corp;okidata-okipage-6e; \
postscriptdriver-oki-data-corp;okidata-okipage-6ex; \
postscriptdriver-oki-data-corp;okipage-10e; \
postscriptdriver-oki-data-corp;okipage-10ex; \
postscriptdriver-oki-data-corp;okipage-14ex; \
postscriptdriver-oki-data-corp;okipage-8p; \
postscriptdriver-panasonic;kx-p6500; \
postscriptdriver-samsung;6050; \
postscriptdriver-samsung;ml-1450; \
postscriptdriver-samsung;ml-1650; \
postscriptdriver-sharp;ar-160/200-series; \
postscriptdriver-shinko;chc-s2145; \
postscriptdriver-sinfonia;chc-s2245; \
postscriptdriver-sinfonia;chc-s6145; \
postscriptdriver-sony;all-in-one-ijp-v100; \
postscriptdriver-sony;up-cr10l; \
postscriptdriver-sony;up-d895; \
postscriptdriver-sony;up-d897; \
postscriptdriver-sony;up-d898md-x898md; \
postscriptdriver-sony;up-dr150; \
postscriptdriver-sony;up-dr80md; \
postscriptdriver-stryker;sdp1000; \
postscriptdriver-xerox;docuprint-p12; \
postscriptdriver-xerox;docuprint-p8e; \
postscriptdriver-xerox;docuprint; \
postscriptdriver-xerox;workcentre-m118;"

RDEPENDS:${PN} += "/usr/bin/perl \
/usr/bin/sh \
cups \
ghostscript \
ld-linux-aarch64.so.1 \
libc.so.6 \
libcups.so.2 \
libgdk-x11-2.0.so.0 \
libglib-2.0.so.0 \
libgobject-2.0.so.0 \
libgtk-x11-2.0.so.0 \
libm.so.6 \
libusb-1.0.so.0 \
libz.so.1"

inherit rpm
