SUMMARY = "Printer drivers for CUPS from the Gutenprint project"
DESCRIPTION = "The Gutenprint (formerly Gimp-Print) printer drivers for CUPS. \
See the user's manual at /usr/share/gutenprint/doc/gutenprint-users-manual.pdf"
LICENSE = "GPL-2.0-or-later"

PV = "5.3.4"

RPM_NAME = "gutenprint-5.3.4-1.1.aarch64.rpm"
RPM_HASH = "74f558267792669fbc9f16e06bbce40b422b65cb46042265dd6b6781232896c5d35f5ea0bb78c8fb5b3e3f6154796cf940e8a868cd1d9dee4f2f24b5ceaea03b"

RPROVIDES:${PN} += "config(gutenprint) \
gutenprint \
gutenprint(aarch-64) \
libgutenprint.so.9()(64bit) \
libgutenprintui2.so.2()(64bit) \
postscriptdriver(brother;brother_hl-1450_series;) \
postscriptdriver(brother;brother_hl-1470n_series;) \
postscriptdriver(brother;brother_hl-2460_series;) \
postscriptdriver(brother;brother_hl-5050_series;) \
postscriptdriver(brother;brother_hl-5070n_series;) \
postscriptdriver(brother;brother_hl-5150d_series;) \
postscriptdriver(brother;brother_hl-5170dn_series;) \
postscriptdriver(brother;brother_hl-7050_series;) \
postscriptdriver(brother;hl-1050_series;) \
postscriptdriver(brother;hl-1070_series;) \
postscriptdriver(brother;hl-1240_series;) \
postscriptdriver(brother;hl-1250_series;) \
postscriptdriver(brother;hl-1440_series;) \
postscriptdriver(brother;hl-5040_series;) \
postscriptdriver(brother;hl-5140_series;) \
postscriptdriver(brother;hl-5340d_series;) \
postscriptdriver(canon;bjc-1000;) \
postscriptdriver(canon;bjc-2100;) \
postscriptdriver(canon;bjc-210;) \
postscriptdriver(canon;bjc-250;) \
postscriptdriver(canon;bjc-3000;) \
postscriptdriver(canon;bjc-4300;) \
postscriptdriver(canon;bjc-4400;) \
postscriptdriver(canon;bjc-50;) \
postscriptdriver(canon;bjc-55;) \
postscriptdriver(canon;bjc-6000;) \
postscriptdriver(canon;bjc-6200;) \
postscriptdriver(canon;bjc-80;) \
postscriptdriver(canon;bjc-8200;) \
postscriptdriver(canon;bjc-85;) \
postscriptdriver(canon;cp-100;) \
postscriptdriver(canon;cp-10;) \
postscriptdriver(canon;cp-200;) \
postscriptdriver(canon;cp-220;) \
postscriptdriver(canon;cp-300;) \
postscriptdriver(canon;cp-330;) \
postscriptdriver(canon;cp1000;) \
postscriptdriver(canon;cp400;) \
postscriptdriver(canon;cp500;) \
postscriptdriver(canon;cp510;) \
postscriptdriver(canon;cp530;) \
postscriptdriver(canon;cp600;) \
postscriptdriver(canon;cp710;) \
postscriptdriver(canon;cp720;) \
postscriptdriver(canon;cp730;) \
postscriptdriver(canon;cp750;) \
postscriptdriver(canon;cp760;) \
postscriptdriver(canon;cp780;) \
postscriptdriver(canon;cp790;) \
postscriptdriver(canon;cp800;) \
postscriptdriver(canon;cp810;) \
postscriptdriver(canon;cp820;) \
postscriptdriver(canon;cp900;) \
postscriptdriver(canon;cp910;) \
postscriptdriver(canon;es1;) \
postscriptdriver(canon;es2;) \
postscriptdriver(canon;es30;) \
postscriptdriver(canon;es3;) \
postscriptdriver(canon;es40;) \
postscriptdriver(canon;ip2700_series;) \
postscriptdriver(canon;ip3000;) \
postscriptdriver(canon;ip4000;) \
postscriptdriver(canon;ip4200;) \
postscriptdriver(canon;ip8500;) \
postscriptdriver(canon;lbp-1000;) \
postscriptdriver(canon;mg5400_series;) \
postscriptdriver(canon;mg6800_series;) \
postscriptdriver(canon;mp160;) \
postscriptdriver(canon;mp230_series;) \
postscriptdriver(canon;mp250_series;) \
postscriptdriver(canon;mp280_series;) \
postscriptdriver(canon;mp450;) \
postscriptdriver(canon;mp500;) \
postscriptdriver(canon;pro9000ii_series;) \
postscriptdriver(canon;s100sp;) \
postscriptdriver(canon;s600;) \
postscriptdriver(canon;selphy_cp1200;) \
postscriptdriver(canon;selphy_cp1300;) \
postscriptdriver(ciaat;brava21;) \
postscriptdriver(citizen_systems;cx-02;) \
postscriptdriver(citizen_systems;cx;) \
postscriptdriver(dai_nippon_printing;dp-ds620;) \
postscriptdriver(dai_nippon_printing;dp-ds820;) \
postscriptdriver(dai_nippon_printing;dp-qw410;) \
postscriptdriver(dai_nippon_printing;ds-rx1;) \
postscriptdriver(dai_nippon_printing;ds40;) \
postscriptdriver(dai_nippon_printing;ds80;) \
postscriptdriver(datamax-o'neil;e4204b_mark_iii;) \
postscriptdriver(datamax-o'neil;e4205a_mark_iii;) \
postscriptdriver(datamax-o'neil;e4206l_mark_iii;) \
postscriptdriver(datamax-o'neil;e4206p_mark_iii;) \
postscriptdriver(datamax-o'neil;e4304b_mark_iii;) \
postscriptdriver(datamax-o'neil;e4305a_mark_iii;) \
postscriptdriver(datamax-o'neil;e4305l_mark_iii;) \
postscriptdriver(datamax-o'neil;e4305p_mark_iii;) \
postscriptdriver(datamax-o'neil;i4212e_mark_ii;) \
postscriptdriver(datamax-o'neil;i4310e_mark_ii;) \
postscriptdriver(datamax-o'neil;i4606e_mark_ii;) \
postscriptdriver(datamax-o'neil;rl3e;) \
postscriptdriver(datamax-o'neil;rl4e;) \
postscriptdriver(datamax;h4212;) \
postscriptdriver(datamax;h4212x;) \
postscriptdriver(datamax;h4310;) \
postscriptdriver(datamax;h4310x;) \
postscriptdriver(datamax;h4408;) \
postscriptdriver(datamax;h4606;) \
postscriptdriver(datamax;h4606x;) \
postscriptdriver(datamax;h6210;) \
postscriptdriver(datamax;h6210x;) \
postscriptdriver(datamax;h6212;) \
postscriptdriver(datamax;h6212x;) \
postscriptdriver(datamax;h6308;) \
postscriptdriver(datamax;h6310x;) \
postscriptdriver(datamax;h8308;) \
postscriptdriver(datamax;h8308x;) \
postscriptdriver(datamaxoneil_;h8308p;) \
postscriptdriver(datamaxoneil_;p1115;) \
postscriptdriver(datamaxoneil_;p1115s;) \
postscriptdriver(datamaxoneil_;p1120n;) \
postscriptdriver(datamaxoneil_;p1125;) \
postscriptdriver(datamaxoneil_;p1725;) \
postscriptdriver(datamaxoneil_;w1110;) \
postscriptdriver(eastman_kodak_company;1400_printer;) \
postscriptdriver(eastman_kodak_company;kodak_7000_photo_printer;) \
postscriptdriver(eastman_kodak_company;kodak_7010_photo_printer;) \
postscriptdriver(eastman_kodak_company;kodak_805_photo_printer;) \
postscriptdriver(eastman_kodak_company;kodak_8810_photo_printer;) \
postscriptdriver(eastman_kodak_company;kodak_photo_printer_8800;) \
postscriptdriver(eastman_kodak_company;photo_printer_6800;) \
postscriptdriver(eastman_kodak_company;photo_printer_6850;) \
postscriptdriver(epson;al-c2000_ps3;) \
postscriptdriver(epson;al-c8600_ps3;) \
postscriptdriver(epson;epl-5700;) \
postscriptdriver(epson;epl-5900_ps3;) \
postscriptdriver(epson;epl-6100_ps3;) \
postscriptdriver(epson;epl-n2500_ps3;) \
postscriptdriver(epson;epson_stylus_pro_3880;) \
postscriptdriver(epson;sc-p400_series;) \
postscriptdriver(epson;sc-p600_series;) \
postscriptdriver(epson;stylus_c20;) \
postscriptdriver(epson;stylus_c40;) \
postscriptdriver(epson;stylus_c42;) \
postscriptdriver(epson;stylus_c43;) \
postscriptdriver(epson;stylus_c44;) \
postscriptdriver(epson;stylus_c45;) \
postscriptdriver(epson;stylus_c46;) \
postscriptdriver(epson;stylus_c48;) \
postscriptdriver(epson;stylus_c60;) \
postscriptdriver(epson;stylus_c62;) \
postscriptdriver(epson;stylus_c65;) \
postscriptdriver(epson;stylus_c66;) \
postscriptdriver(epson;stylus_c68;) \
postscriptdriver(epson;stylus_c80;) \
postscriptdriver(epson;stylus_c82;) \
postscriptdriver(epson;stylus_c84;) \
postscriptdriver(epson;stylus_c85;) \
postscriptdriver(epson;stylus_c86;) \
postscriptdriver(epson;stylus_c88;) \
postscriptdriver(epson;stylus_c92;) \
postscriptdriver(epson;stylus_color_1520;) \
postscriptdriver(epson;stylus_color_440;) \
postscriptdriver(epson;stylus_color_460;) \
postscriptdriver(epson;stylus_color_480;) \
postscriptdriver(epson;stylus_color_600;) \
postscriptdriver(epson;stylus_color_670;) \
postscriptdriver(epson;stylus_color_680;) \
postscriptdriver(epson;stylus_color_740;) \
postscriptdriver(epson;stylus_color_760;) \
postscriptdriver(epson;stylus_color_777;) \
postscriptdriver(epson;stylus_color_800;) \
postscriptdriver(epson;stylus_color_880;) \
postscriptdriver(epson;stylus_color_900;) \
postscriptdriver(epson;stylus_color_980;) \
postscriptdriver(epson;stylus_cx1500;) \
postscriptdriver(epson;stylus_cx3100;) \
postscriptdriver(epson;stylus_cx3200;) \
postscriptdriver(epson;stylus_cx3500;) \
postscriptdriver(epson;stylus_cx3600;) \
postscriptdriver(epson;stylus_cx3650;) \
postscriptdriver(epson;stylus_cx3700;) \
postscriptdriver(epson;stylus_cx3800;) \
postscriptdriver(epson;stylus_cx3805;) \
postscriptdriver(epson;stylus_cx3810;) \
postscriptdriver(epson;stylus_cx3900;) \
postscriptdriver(epson;stylus_cx4100;) \
postscriptdriver(epson;stylus_cx4200;) \
postscriptdriver(epson;stylus_cx4500;) \
postscriptdriver(epson;stylus_cx4600;) \
postscriptdriver(epson;stylus_cx4700;) \
postscriptdriver(epson;stylus_cx4800;) \
postscriptdriver(epson;stylus_cx5100;) \
postscriptdriver(epson;stylus_cx5300;) \
postscriptdriver(epson;stylus_cx5400;) \
postscriptdriver(epson;stylus_cx5700;) \
postscriptdriver(epson;stylus_cx5800;) \
postscriptdriver(epson;stylus_cx6300;) \
postscriptdriver(epson;stylus_cx6500;) \
postscriptdriver(epson;stylus_cx6600;) \
postscriptdriver(epson;stylus_cx7700;) \
postscriptdriver(epson;stylus_cx7800;) \
postscriptdriver(epson;stylus_cx8300;) \
postscriptdriver(epson;stylus_cx8400;) \
postscriptdriver(epson;stylus_d68;) \
postscriptdriver(epson;stylus_d78;) \
postscriptdriver(epson;stylus_d88;) \
postscriptdriver(epson;stylus_d92;) \
postscriptdriver(epson;stylus_dx3800;) \
postscriptdriver(epson;stylus_dx3850;) \
postscriptdriver(epson;stylus_dx4200;) \
postscriptdriver(epson;stylus_dx4250;) \
postscriptdriver(epson;stylus_dx4800;) \
postscriptdriver(epson;stylus_photo_1270;) \
postscriptdriver(epson;stylus_photo_1400;) \
postscriptdriver(epson;stylus_photo_700;) \
postscriptdriver(epson;stylus_photo_750;) \
postscriptdriver(epson;stylus_photo_785epx;) \
postscriptdriver(epson;stylus_photo_790;) \
postscriptdriver(epson;stylus_photo_820;) \
postscriptdriver(epson;stylus_photo_825;) \
postscriptdriver(epson;stylus_photo_830u;) \
postscriptdriver(epson;stylus_photo_870;) \
postscriptdriver(epson;stylus_photo_890;) \
postscriptdriver(epson;stylus_photo_895;) \
postscriptdriver(epson;stylus_photo_900;) \
postscriptdriver(epson;stylus_photo_915;) \
postscriptdriver(epson;stylus_photo_935;) \
postscriptdriver(epson;stylus_photo_ex;) \
postscriptdriver(epson;stylus_photo_r200;) \
postscriptdriver(epson;stylus_photo_r210;) \
postscriptdriver(epson;stylus_photo_r220;) \
postscriptdriver(epson;stylus_photo_r230;) \
postscriptdriver(epson;stylus_photo_r2400;) \
postscriptdriver(epson;stylus_photo_r300;) \
postscriptdriver(epson;stylus_photo_r310;) \
postscriptdriver(epson;stylus_photo_r320;) \
postscriptdriver(epson;stylus_photo_r340;) \
postscriptdriver(epson;stylus_photo_rx400;) \
postscriptdriver(epson;stylus_photo_rx420;) \
postscriptdriver(epson;stylus_photo_rx425;) \
postscriptdriver(epson;stylus_photo_rx430;) \
postscriptdriver(epson;stylus_photo_rx500;) \
postscriptdriver(epson;stylus_photo_rx510;) \
postscriptdriver(epson;stylus_photo_rx620;) \
postscriptdriver(epson;stylus_photo_rx630;) \
postscriptdriver(epson;stylus_photo_rx700;) \
postscriptdriver(epson;stylus_pro_7900;) \
postscriptdriver(epson;stylus_pro_9900;) \
postscriptdriver(epson;xp-15000_series;) \
postscriptdriver(fujifilm;ask_printer;) \
postscriptdriver(hewlett-packard;deskjet_1120c;) \
postscriptdriver(hewlett-packard;deskjet_1220c;) \
postscriptdriver(hewlett-packard;deskjet_3820;) \
postscriptdriver(hewlett-packard;deskjet_600;) \
postscriptdriver(hewlett-packard;deskjet_610c;) \
postscriptdriver(hewlett-packard;deskjet_640c;) \
postscriptdriver(hewlett-packard;deskjet_660c;) \
postscriptdriver(hewlett-packard;deskjet_670c;) \
postscriptdriver(hewlett-packard;deskjet_690c;) \
postscriptdriver(hewlett-packard;deskjet_810c;) \
postscriptdriver(hewlett-packard;deskjet_815c;) \
postscriptdriver(hewlett-packard;deskjet_825c;) \
postscriptdriver(hewlett-packard;deskjet_840c;) \
postscriptdriver(hewlett-packard;deskjet_841c;) \
postscriptdriver(hewlett-packard;deskjet_843c;) \
postscriptdriver(hewlett-packard;deskjet_845c;) \
postscriptdriver(hewlett-packard;deskjet_850c;) \
postscriptdriver(hewlett-packard;deskjet_870c;) \
postscriptdriver(hewlett-packard;deskjet_880c;) \
postscriptdriver(hewlett-packard;deskjet_890c;) \
postscriptdriver(hewlett-packard;deskjet_895c;) \
postscriptdriver(hewlett-packard;deskjet_920c;) \
postscriptdriver(hewlett-packard;deskjet_930c;) \
postscriptdriver(hewlett-packard;deskjet_940c;) \
postscriptdriver(hewlett-packard;deskjet_950c;) \
postscriptdriver(hewlett-packard;deskjet_960c;) \
postscriptdriver(hewlett-packard;deskjet_970c;) \
postscriptdriver(hewlett-packard;deskjet_980c;) \
postscriptdriver(hewlett-packard;deskjet_990c;) \
postscriptdriver(hewlett-packard;hp_business_inkjet_2200;) \
postscriptdriver(hewlett-packard;hp_business_inkjet_2230;) \
postscriptdriver(hewlett-packard;hp_business_inkjet_2250;) \
postscriptdriver(hewlett-packard;hp_business_inkjet_2280;) \
postscriptdriver(hewlett-packard;hp_color_inkjet_cp1700;) \
postscriptdriver(hewlett-packard;hp_color_laserjet_2500;) \
postscriptdriver(hewlett-packard;hp_color_laserjet_4550;) \
postscriptdriver(hewlett-packard;hp_color_laserjet_4600;) \
postscriptdriver(hewlett-packard;hp_color_laserjet_4610;) \
postscriptdriver(hewlett-packard;hp_color_laserjet_4650;) \
postscriptdriver(hewlett-packard;hp_deskjet_340;) \
postscriptdriver(hewlett-packard;hp_deskjet_400;) \
postscriptdriver(hewlett-packard;hp_laserjet_1010;) \
postscriptdriver(hewlett-packard;hp_laserjet_1012;) \
postscriptdriver(hewlett-packard;hp_laserjet_1015;) \
postscriptdriver(hewlett-packard;hp_laserjet_1100;) \
postscriptdriver(hewlett-packard;hp_laserjet_1150;) \
postscriptdriver(hewlett-packard;hp_laserjet_1160_series;) \
postscriptdriver(hewlett-packard;hp_laserjet_1200;) \
postscriptdriver(hewlett-packard;hp_laserjet_1220;) \
postscriptdriver(hewlett-packard;hp_laserjet_1300;) \
postscriptdriver(hewlett-packard;hp_laserjet_1320_series;) \
postscriptdriver(hewlett-packard;hp_laserjet_2100_series;) \
postscriptdriver(hewlett-packard;hp_laserjet_2200;) \
postscriptdriver(hewlett-packard;hp_laserjet_2300_series;) \
postscriptdriver(hewlett-packard;hp_laserjet_2420;) \
postscriptdriver(hewlett-packard;hp_laserjet_2430;) \
postscriptdriver(hewlett-packard;hp_laserjet_3015;) \
postscriptdriver(hewlett-packard;hp_laserjet_3020;) \
postscriptdriver(hewlett-packard;hp_laserjet_3030;) \
postscriptdriver(hewlett-packard;hp_laserjet_3050;) \
postscriptdriver(hewlett-packard;hp_laserjet_3052;) \
postscriptdriver(hewlett-packard;hp_laserjet_3055;) \
postscriptdriver(hewlett-packard;hp_laserjet_3200;) \
postscriptdriver(hewlett-packard;hp_laserjet_3200m;) \
postscriptdriver(hewlett-packard;hp_laserjet_3300/3310/3320;) \
postscriptdriver(hewlett-packard;hp_laserjet_3330;) \
postscriptdriver(hewlett-packard;hp_laserjet_3380;) \
postscriptdriver(hewlett-packard;hp_laserjet_3390;) \
postscriptdriver(hewlett-packard;hp_laserjet_4000_series;) \
postscriptdriver(hewlett-packard;hp_laserjet_4050_series;) \
postscriptdriver(hewlett-packard;hp_laserjet_4100_series;) \
postscriptdriver(hewlett-packard;hp_laserjet_4200;) \
postscriptdriver(hewlett-packard;hp_laserjet_4250;) \
postscriptdriver(hewlett-packard;hp_laserjet_4300;) \
postscriptdriver(hewlett-packard;hp_laserjet_4350;) \
postscriptdriver(hewlett-packard;hp_laserjet_4_plus;) \
postscriptdriver(hewlett-packard;hp_laserjet_5000_series;) \
postscriptdriver(hewlett-packard;hp_laserjet_5100_series;) \
postscriptdriver(hewlett-packard;hp_laserjet_5l;) \
postscriptdriver(hewlett-packard;hp_laserjet_5mp;) \
postscriptdriver(hewlett-packard;hp_laserjet_5n;) \
postscriptdriver(hewlett-packard;hp_laserjet_5p;) \
postscriptdriver(hewlett-packard;hp_laserjet_5si;) \
postscriptdriver(hewlett-packard;hp_laserjet_6l;) \
postscriptdriver(hewlett-packard;hp_laserjet_6mp;) \
postscriptdriver(hewlett-packard;hp_laserjet_6p;) \
postscriptdriver(hewlett-packard;hp_laserjet_8000_series;) \
postscriptdriver(hewlett-packard;hp_laserjet_8150_series;) \
postscriptdriver(hewlett-packard;hp_laserjet_m3027_mfp;) \
postscriptdriver(hewlett-packard;hp_laserjet_m3035_mfp;) \
postscriptdriver(hewlett-packard;hp_laserjet_p2010_series;) \
postscriptdriver(hewlett-packard;hp_laserjet_p2015_series;) \
postscriptdriver(hewlett-packard;hp_laserjet_p3004_series;) \
postscriptdriver(hewlett-packard;hp_laserjet_p3005;) \
postscriptdriver(hewlett-packard;laserjet_4l;) \
postscriptdriver(hewlett-packard;laserjet_color_4500;) \
postscriptdriver(hewlett-packard;officejet;) \
postscriptdriver(hewlett-packard;officejet_5105;) \
postscriptdriver(hewlett-packard;officejet_5110v;) \
postscriptdriver(hewlett-packard;officejet_6100_series;) \
postscriptdriver(hewlett-packard;officejet_7100_series;) \
postscriptdriver(hewlett-packard;officejet__k60;) \
postscriptdriver(hewlett-packard;officejet__k60xi;) \
postscriptdriver(hewlett-packard;officejet__k80;) \
postscriptdriver(hewlett-packard;officejet__k80xi;) \
postscriptdriver(hewlett-packard;officejet_d_series;) \
postscriptdriver(hewlett-packard;officejet_g55;) \
postscriptdriver(hewlett-packard;officejet_g85;) \
postscriptdriver(hewlett-packard;officejet_g95;) \
postscriptdriver(hewlett-packard;officejet_pro_1150c;) \
postscriptdriver(hewlett-packard;officejet_pro_1170c_series;) \
postscriptdriver(hewlett-packard;officejet_r40;) \
postscriptdriver(hewlett-packard;officejet_r60;) \
postscriptdriver(hewlett-packard;officejet_r65;) \
postscriptdriver(hewlett-packard;officejet_r80;) \
postscriptdriver(hewlett-packard;officejet_series_300;) \
postscriptdriver(hewlett-packard;officejet_series_500;) \
postscriptdriver(hewlett-packard;officejet_series_600;) \
postscriptdriver(hewlett-packard;officejet_series_700;) \
postscriptdriver(hewlett-packard;officejet_t_series;) \
postscriptdriver(hewlett-packard;officejet_v40;) \
postscriptdriver(hewlett-packard;officejet_v40xi;) \
postscriptdriver(hewlett-packard;photosmart_p1000;) \
postscriptdriver(hewlett-packard;photosmart_p1100;) \
postscriptdriver(hewlett-packard;printer/scanner/copier_300;) \
postscriptdriver(hewlett-packard;psc_2100_series;) \
postscriptdriver(hewlett-packard;psc_2150_series;) \
postscriptdriver(hewlett-packard;psc_2200_series;) \
postscriptdriver(hewlett-packard;psc_500;) \
postscriptdriver(hewlett-packard;psc_750;) \
postscriptdriver(hewlett-packard;psc_900_series;) \
postscriptdriver(hiti;hiti_p720l;) \
postscriptdriver(hiti;p520l;) \
postscriptdriver(hiti;p525l;) \
postscriptdriver(hiti;p750l;) \
postscriptdriver(honeywell;rp2;) \
postscriptdriver(honeywell;rp4;) \
postscriptdriver(hp;deskjet_5550;) \
postscriptdriver(hp;deskjet_6122;) \
postscriptdriver(hp;dj450;) \
postscriptdriver(hp;photosmart_100;) \
postscriptdriver(hp;photosmart_1115;) \
postscriptdriver(hp;photosmart_1218;) \
postscriptdriver(hp;photosmart_1315;) \
postscriptdriver(hp;photosmart_7150;) \
postscriptdriver(hp;photosmart_7350;) \
postscriptdriver(hp;photosmart_7550;) \
postscriptdriver(ibm;infoprint;) \
postscriptdriver(kodak;305_photo_printer;) \
postscriptdriver(kodak_alaris_inc.;kodak_6900_photo_printer;) \
postscriptdriver(kyocera;f-1010;) \
postscriptdriver(kyocera;fs-1118mfp;) \
postscriptdriver(kyocera;fs-1135mfp;) \
postscriptdriver(kyocera;fs-1600;) \
postscriptdriver(kyocera;fs-3500;) \
postscriptdriver(kyocera;fs-3600;) \
postscriptdriver(kyocera;fs-6500;) \
postscriptdriver(kyocera;kyocera_fs-1000;) \
postscriptdriver(kyocera;kyocera_fs-1200;) \
postscriptdriver(kyocera;kyocera_fs-1700;) \
postscriptdriver(kyocera;kyocera_fs-1750;) \
postscriptdriver(kyocera;kyocera_fs-3700;) \
postscriptdriver(kyocera;kyocera_fs-3750;) \
postscriptdriver(kyocera;kyocera_fs-5800c;) \
postscriptdriver(kyocera;kyocera_fs-5900c;) \
postscriptdriver(kyocera;kyocera_fs-600;) \
postscriptdriver(kyocera;kyocera_fs-6700;) \
postscriptdriver(kyocera;kyocera_fs-680;) \
postscriptdriver(kyocera;kyocera_fs-7000;) \
postscriptdriver(kyocera;kyocera_fs-800;) \
postscriptdriver(kyocera;kyocera_fs-9000;) \
postscriptdriver(kyocera_mita;km-1530;) \
postscriptdriver(kyocera_mita;km-1810;) \
postscriptdriver(kyocera_mita;km-2030;) \
postscriptdriver(kyocera_mita;km-2530;) \
postscriptdriver(kyocera_mita;km-3530;) \
postscriptdriver(kyocera_mita;km-4230;) \
postscriptdriver(kyocera_mita;km-4530;) \
postscriptdriver(kyocera_mita;km-5230;) \
postscriptdriver(kyocera_mita;km-5530;) \
postscriptdriver(kyocera_mita;km-6230;) \
postscriptdriver(kyocera_mita;kyocera_mita_fs-1010;) \
postscriptdriver(kyocera_mita;kyocera_mita_fs-1050;) \
postscriptdriver(kyocera_mita;kyocera_mita_fs-1800;) \
postscriptdriver(kyocera_mita;kyocera_mita_fs-1900;) \
postscriptdriver(kyocera_mita;kyocera_mita_fs-3800;) \
postscriptdriver(kyocera_mita;kyocera_mita_fs-8000c;) \
postscriptdriver(kyocera_mita;kyocera_mita_fs-9100dn;) \
postscriptdriver(kyocera_mita;kyocera_mita_fs-9500dn;) \
postscriptdriver(lexmark;lexmark_x73;) \
postscriptdriver(lexmark;lexmark_z42;) \
postscriptdriver(lexmark;lexmark_z52;) \
postscriptdriver(lexmark_international;ibm_3112_page_printer;) \
postscriptdriver(lexmark_international;lexmark_e321;) \
postscriptdriver(magicard;riotango2d;) \
postscriptdriver(minolta;pagepro_1100;) \
postscriptdriver(minolta;pagepro_6;) \
postscriptdriver(minolta;pagepro_8;) \
postscriptdriver(minolta;pagepro_8l;) \
postscriptdriver(minolta;pagepro___6e;) \
postscriptdriver(mitsubishi;cp-m1;) \
postscriptdriver(mitsubishi;cp30d;) \
postscriptdriver(mitsubishi;cp60d70d707d;) \
postscriptdriver(mitsubishi;cp9550d;) \
postscriptdriver(mitsubishi;cp9550dz;) \
postscriptdriver(mitsubishi;cp9800dz;) \
postscriptdriver(mitsubishi;cpd80d;) \
postscriptdriver(mitsubishi;cpd90d;) \
postscriptdriver(mitsubishi;p93d;) \
postscriptdriver(mitsubishi;p95d;) \
postscriptdriver(nec;superscript_1800;) \
postscriptdriver(nec;superscript_870;) \
postscriptdriver(oki_data_corp;okidata_okipage_6e;) \
postscriptdriver(oki_data_corp;okidata_okipage_6ex;) \
postscriptdriver(oki_data_corp;okipage_10e;) \
postscriptdriver(oki_data_corp;okipage_10ex;) \
postscriptdriver(oki_data_corp;okipage_14ex;) \
postscriptdriver(oki_data_corp;okipage_8p;) \
postscriptdriver(panasonic;kx-p6500;) \
postscriptdriver(samsung;6050;) \
postscriptdriver(samsung;ml-1450;) \
postscriptdriver(samsung;ml-1650;) \
postscriptdriver(sharp;ar-160/200_series;) \
postscriptdriver(shinko;chc-s2145;) \
postscriptdriver(sinfonia;chc-s2245;) \
postscriptdriver(sinfonia;chc-s6145;) \
postscriptdriver(sony;all-in-one_ijp-v100;) \
postscriptdriver(sony;up-cr10l;) \
postscriptdriver(sony;up-d895;) \
postscriptdriver(sony;up-d897;) \
postscriptdriver(sony;up-d898md_x898md;) \
postscriptdriver(sony;up-dr150;) \
postscriptdriver(sony;up-dr80md;) \
postscriptdriver(stryker;sdp1000;) \
postscriptdriver(xerox;docuprint;) \
postscriptdriver(xerox;docuprint_p12;) \
postscriptdriver(xerox;docuprint_p8e;) \
postscriptdriver(xerox;workcentre_m118;)"

RDEPENDS:${PN} += "/bin/sh \
/usr/bin/perl \
cups \
ghostscript \
ld-linux-aarch64.so.1()(64bit) \
libc.so.6()(64bit) \
libcups.so.2()(64bit) \
libgdk-x11-2.0.so.0()(64bit) \
libglib-2.0.so.0()(64bit) \
libgobject-2.0.so.0()(64bit) \
libgtk-x11-2.0.so.0()(64bit) \
libm.so.6()(64bit) \
libusb-1.0.so.0()(64bit) \
libz.so.1()(64bit)"

inherit rpm
