SUMMARY = "Development files for ocaml-qcheck"
DESCRIPTION = "The ocaml-qcheck-devel package contains libraries and signature files for \
developing applications that use ocaml-qcheck."
LICENSE = "BSD-2-Clause"

PV = "0.21.1"

RPM_NAME = "ocaml-qcheck-devel-0.21.1-1.1.aarch64.rpm"
RPM_HASH = "1ff5cb70abe234e12a69eb2ff5928276ba116b3418c55ed3927feedce3b72584911c0d1918947c67532e78af940978988fbddf1060859e06c20fb6a637e83af5"

RPROVIDES:${PN} += "ocaml-Ppx-deriving-qcheck \
ocaml-Ppx-deriving-qcheck-- \
ocaml-Ppx-deriving-qcheck--Args \
ocaml-Ppx-deriving-qcheck--Attributes \
ocaml-Ppx-deriving-qcheck--QCheck-generators \
ocaml-Ppx-deriving-qcheck--Tuple \
ocaml-QCheck \
ocaml-QCheck-base-runner \
ocaml-QCheck-ounit \
ocaml-QCheck-runner \
ocaml-QCheck2 \
ocaml-qcheck-devel \
ocamlfind-ppx-deriving-qcheck \
ocamlfind-qcheck \
ocamlfind-qcheck-core \
ocamlfind-qcheck-core.runner \
ocamlfind-qcheck-ounit \
ocamlx-Ppx-deriving-qcheck \
ocamlx-Ppx-deriving-qcheck-- \
ocamlx-Ppx-deriving-qcheck--Args \
ocamlx-Ppx-deriving-qcheck--Attributes \
ocamlx-Ppx-deriving-qcheck--QCheck-generators \
ocamlx-Ppx-deriving-qcheck--Tuple \
ocamlx-QCheck \
ocamlx-QCheck-base-runner \
ocamlx-QCheck-ounit \
ocamlx-QCheck-runner \
ocamlx-QCheck2"

RDEPENDS:${PN} += "ocaml-Astlib \
ocaml-Astlib-- \
ocaml-Astlib--Ast-402 \
ocaml-Astlib--Ast-403 \
ocaml-Astlib--Ast-404 \
ocaml-Astlib--Ast-405 \
ocaml-Astlib--Ast-406 \
ocaml-Astlib--Ast-407 \
ocaml-Astlib--Ast-408 \
ocaml-Astlib--Ast-409 \
ocaml-Astlib--Ast-410 \
ocaml-Astlib--Ast-411 \
ocaml-Astlib--Ast-412 \
ocaml-Astlib--Ast-413 \
ocaml-Astlib--Ast-414 \
ocaml-Astlib--Ast-500 \
ocaml-Astlib--Location \
ocaml-Astlib--Longident \
ocaml-Astlib--Parse \
ocaml-Asttypes \
ocaml-Build-path-prefix-map \
ocaml-CamlinternalFormatBasics \
ocaml-CamlinternalLazy \
ocaml-CamlinternalOO \
ocaml-Clflags \
ocaml-Cmi-format \
ocaml-Compmisc \
ocaml-Env \
ocaml-Ident \
ocaml-Identifiable \
ocaml-Load-path \
ocaml-Location \
ocaml-Longident \
ocaml-Misc \
ocaml-OUnit \
ocaml-OUnit2 \
ocaml-OUnitConf \
ocaml-OUnitLogger \
ocaml-OUnitPropList \
ocaml-OUnitShared \
ocaml-OUnitTest \
ocaml-OUnitUtils \
ocaml-Ocaml-common \
ocaml-Ocaml-shadow \
ocaml-Outcometree \
ocaml-Parsetree \
ocaml-Path \
ocaml-Ppxlib \
ocaml-Ppxlib-- \
ocaml-Ppxlib--Ast-builder \
ocaml-Ppxlib--Ast-builder-generated \
ocaml-Ppxlib--Ast-builder-intf \
ocaml-Ppxlib--Ast-pattern \
ocaml-Ppxlib--Ast-pattern-generated \
ocaml-Ppxlib--Ast-pattern0 \
ocaml-Ppxlib--Ast-traverse \
ocaml-Ppxlib--Ast-traverse0 \
ocaml-Ppxlib--Attribute \
ocaml-Ppxlib--Code-path \
ocaml-Ppxlib--Common \
ocaml-Ppxlib--Deriving \
ocaml-Ppxlib--Expansion-context \
ocaml-Ppxlib--Import \
ocaml-Ppxlib--Loc \
ocaml-Ppxlib--Location \
ocaml-Ppxlib--Longident \
ocaml-Ppxlib--Name \
ocaml-Ppxlib--Utils \
ocaml-Ppxlib-ast \
ocaml-Ppxlib-ast-- \
ocaml-Ppxlib-ast--Ast \
ocaml-Ppxlib-ast--Import \
ocaml-Ppxlib-ast--Versions \
ocaml-Ppxlib-traverse-builtins \
ocaml-Primitive \
ocaml-Profile \
ocaml-Sexplib0 \
ocaml-Sexplib0-- \
ocaml-Sexplib0--Sexp \
ocaml-Sexplib0--Sexp-conv \
ocaml-Sexplib0--Sexp-conv-grammar \
ocaml-Sexplib0--Sexp-grammar \
ocaml-Shape \
ocaml-Stdlib \
ocaml-Stdlib--Arg \
ocaml-Stdlib--Array \
ocaml-Stdlib--Bigarray \
ocaml-Stdlib--Buffer \
ocaml-Stdlib--Bytes \
ocaml-Stdlib--BytesLabels \
ocaml-Stdlib--Char \
ocaml-Stdlib--Complex \
ocaml-Stdlib--Digest \
ocaml-Stdlib--Either \
ocaml-Stdlib--Filename \
ocaml-Stdlib--Float \
ocaml-Stdlib--Format \
ocaml-Stdlib--Fun \
ocaml-Stdlib--Hashtbl \
ocaml-Stdlib--Int \
ocaml-Stdlib--Int32 \
ocaml-Stdlib--Int64 \
ocaml-Stdlib--Lazy \
ocaml-Stdlib--Lexing \
ocaml-Stdlib--List \
ocaml-Stdlib--ListLabels \
ocaml-Stdlib--Map \
ocaml-Stdlib--Nativeint \
ocaml-Stdlib--Obj \
ocaml-Stdlib--Oo \
ocaml-Stdlib--Option \
ocaml-Stdlib--Printexc \
ocaml-Stdlib--Printf \
ocaml-Stdlib--Random \
ocaml-Stdlib--Result \
ocaml-Stdlib--Scanf \
ocaml-Stdlib--Seq \
ocaml-Stdlib--Set \
ocaml-Stdlib--StdLabels \
ocaml-Stdlib--String \
ocaml-Stdlib--StringLabels \
ocaml-Stdlib--Sys \
ocaml-Stdlib--Uchar \
ocaml-Stdppx \
ocaml-Subst \
ocaml-Type-immediacy \
ocaml-Types \
ocaml-Unix \
ocaml-Warnings \
ocaml-qcheck \
ocamlfind-bytes \
ocamlfind-ounit2 \
ocamlfind-ppxlib \
ocamlfind-ppxlib.ast \
ocamlfind-unix \
ocamlx-CamlinternalLazy \
ocamlx-CamlinternalOO \
ocamlx-OUnit \
ocamlx-OUnit2 \
ocamlx-Ppxlib--Ast-builder \
ocamlx-Ppxlib--Ast-traverse \
ocamlx-Ppxlib--Deriving \
ocamlx-Ppxlib--Expansion-context \
ocamlx-Ppxlib--Location \
ocamlx-Stdlib \
ocamlx-Stdlib--Arg \
ocamlx-Stdlib--Array \
ocamlx-Stdlib--Buffer \
ocamlx-Stdlib--Bytes \
ocamlx-Stdlib--Char \
ocamlx-Stdlib--Float \
ocamlx-Stdlib--Format \
ocamlx-Stdlib--Hashtbl \
ocamlx-Stdlib--Int \
ocamlx-Stdlib--Int32 \
ocamlx-Stdlib--Int64 \
ocamlx-Stdlib--Lazy \
ocamlx-Stdlib--List \
ocamlx-Stdlib--Option \
ocamlx-Stdlib--Printexc \
ocamlx-Stdlib--Printf \
ocamlx-Stdlib--Random \
ocamlx-Stdlib--Result \
ocamlx-Stdlib--Seq \
ocamlx-Stdlib--Set \
ocamlx-Stdlib--String \
ocamlx-Stdlib--Sys \
ocamlx-Unix"

inherit rpm
