SUMMARY = "A simple Django application to demonstrate RRD plots"
DESCRIPTION = "django-collectd-rest is a simple Django application to demonstrate RRD plots generated by collectd or any other rrd data. \
The application is built on top of django-rest-framework and provides REST API to access the plots."
LICENSE = "BSD-2-Clause"

PV = "0.2.4"

RPM_NAME = "python39-django-collectd-rest-0.2.4-1.5.aarch64.rpm"
RPM_HASH = "effc1ec2e96848f37a1e42072ac8e33aff739ed437c7d2916e2a0173dff16fd72b3792cade1db5c812d5964afbdad3364ef53a2f82347bc065aa4c107f705db5"

RPROVIDES:${PN} += "python3.9dist-django-collectd-rest \
python39-django-collectd-rest \
python3dist-django-collectd-rest"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1 \
libc.so.6 \
librrd.so.8 \
python-abi \
python39-Django \
python39-djangorestframework \
rrdtool"

inherit rpm
