SUMMARY = "Visualize ABI changes timeline of a C/C++ software library"
DESCRIPTION = "This tool visualizes an ABI changes timeline of a C/C++ software library. \
 \
It requires input profile of the library in JSON format. It can be created \
manually or automatically generated by the ABI Monitor."
LICENSE = "GPL-2.0-or-later | LGPL-2.1-or-later"

PV = "1.11"

RPM_NAME = "abi-tracker-1.11-2.10.noarch.rpm"
RPM_HASH = "2a3e7b8dc526aa5191dada45d575294e1a3718fd124c5f25e5b364f75c16307df8d113f20749528f26e86f67c5cebbc12da69b9700ea67a3e07a007121c9efcf"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "abi-tracker \
perl-In"

RDEPENDS:${PN} += "/usr/bin/perl \
abi-compliance-checker \
abi-dumper \
abi-monitor \
binutils \
perl-base \
pkgdiff \
rfcdiff \
vtable-dumper"

inherit rpm
