SUMMARY = "ANTLR 4 Java runtime"
DESCRIPTION = "This package provides Java runtime library used by parsers generated by \
ANTLR 4."
LICENSE = "BSD-3-Clause"

PV = "4.13.0"

RPM_NAME = "antlr4-java-4.13.0-1.2.noarch.rpm"
RPM_HASH = "f098d8aae0ca3be41389a5e87a8385094a71f1a0020140154fb56132f30e5bbbaa4c480537dff5250ca3e6fa3ebf250344393d37a10d2f733751c74655f17ca7"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "antlr4-java \
antlr4-runtime \
mvn-org.antlr-antlr4-master-pom- \
mvn-org.antlr-antlr4-runtime \
mvn-org.antlr-antlr4-runtime-pom- \
osgi-org.antlr.antlr4-runtime"

RDEPENDS:${PN} += "java-headless \
javapackages-filesystem"

inherit rpm
