SUMMARY = "ANTLR 4 Java runtime"
DESCRIPTION = "This package provides Java runtime library used by parsers generated by \
ANTLR 4."
LICENSE = "BSD-3-Clause"

PV = "4.13.0"

RPM_NAME = "antlr4-java-4.13.0-2.1.noarch.rpm"
RPM_HASH = "94ade633c8b840c048daa90d3f8a7c5d196f11763e203c4c817e508b51c36589013711b076cd62e82c5e713a2116ef1e8879cdfb8cc672ff6573ae248df0bbba"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "antlr4-java \
antlr4-runtime \
mvn-org.antlr-antlr4-master-pom- \
mvn-org.antlr-antlr4-runtime \
mvn-org.antlr-antlr4-runtime-pom- \
osgi-org.antlr.antlr4-runtime"

RDEPENDS:${PN} += "java-headless \
javapackages-filesystem"

inherit rpm
