SUMMARY = "Font package derived from Heuristica and Utopia"
DESCRIPTION = "Erewhon is based on the Heuristica package, which is based in \
turn on Utopia. Erewhon adds a number of new features -- small \
caps in all styles rather than just regular, added figure \
styles (proportional, inferior, numerator, denominator) and \
superior letters. The size is 6% smaller than Heuristica, \
matching that of UtopiaStd."
LICENSE = "OFL-1.1"

PV = "2023.201.1.12svn63312"

RPM_NAME = "texlive-erewhon-2023.201.1.12svn63312-53.1.noarch.rpm"
RPM_HASH = "c9442d8d128928bf2f7d498c1cb130927afca0c11bde3c17fc5f628667187fe1625ee162955666dd7e644c4db9ee43b96fa789cb62a2c99af40745d70554b91d"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex(Erewhon-Bold-dnom-ly1.tfm) \
tex(Erewhon-Bold-dnom-ot1.tfm) \
tex(Erewhon-Bold-dnom-t1--base.tfm) \
tex(Erewhon-Bold-dnom-t1.tfm) \
tex(Erewhon-Bold-dnom-t1.vf) \
tex(Erewhon-Bold-dnom-t2a.tfm) \
tex(Erewhon-Bold-dnom-t2b.tfm) \
tex(Erewhon-Bold-dnom-t2c.tfm) \
tex(Erewhon-Bold-inf-ly1.tfm) \
tex(Erewhon-Bold-inf-ot1.tfm) \
tex(Erewhon-Bold-inf-t1--base.tfm) \
tex(Erewhon-Bold-inf-t1.tfm) \
tex(Erewhon-Bold-inf-t1.vf) \
tex(Erewhon-Bold-inf-t2a.tfm) \
tex(Erewhon-Bold-inf-t2b.tfm) \
tex(Erewhon-Bold-inf-t2c.tfm) \
tex(Erewhon-Bold-lf-ly1.tfm) \
tex(Erewhon-Bold-lf-ot1.tfm) \
tex(Erewhon-Bold-lf-sc-ly1--base.tfm) \
tex(Erewhon-Bold-lf-sc-ly1.tfm) \
tex(Erewhon-Bold-lf-sc-ly1.vf) \
tex(Erewhon-Bold-lf-sc-ot1--base.tfm) \
tex(Erewhon-Bold-lf-sc-ot1.tfm) \
tex(Erewhon-Bold-lf-sc-ot1.vf) \
tex(Erewhon-Bold-lf-sc-t1--base.tfm) \
tex(Erewhon-Bold-lf-sc-t1.tfm) \
tex(Erewhon-Bold-lf-sc-t1.vf) \
tex(Erewhon-Bold-lf-sc-t2a--base.tfm) \
tex(Erewhon-Bold-lf-sc-t2a.tfm) \
tex(Erewhon-Bold-lf-sc-t2a.vf) \
tex(Erewhon-Bold-lf-sc-t2b--base.tfm) \
tex(Erewhon-Bold-lf-sc-t2b.tfm) \
tex(Erewhon-Bold-lf-sc-t2b.vf) \
tex(Erewhon-Bold-lf-sc-t2c--base.tfm) \
tex(Erewhon-Bold-lf-sc-t2c.tfm) \
tex(Erewhon-Bold-lf-sc-t2c.vf) \
tex(Erewhon-Bold-lf-t1--base.tfm) \
tex(Erewhon-Bold-lf-t1.tfm) \
tex(Erewhon-Bold-lf-t1.vf) \
tex(Erewhon-Bold-lf-t2a.tfm) \
tex(Erewhon-Bold-lf-t2b.tfm) \
tex(Erewhon-Bold-lf-t2c.tfm) \
tex(Erewhon-Bold-lf-ts1--base.tfm) \
tex(Erewhon-Bold-lf-ts1.tfm) \
tex(Erewhon-Bold-lf-ts1.vf) \
tex(Erewhon-Bold-numr-ly1.tfm) \
tex(Erewhon-Bold-numr-ot1.tfm) \
tex(Erewhon-Bold-numr-t1--base.tfm) \
tex(Erewhon-Bold-numr-t1.tfm) \
tex(Erewhon-Bold-numr-t1.vf) \
tex(Erewhon-Bold-numr-t2a.tfm) \
tex(Erewhon-Bold-numr-t2b.tfm) \
tex(Erewhon-Bold-numr-t2c.tfm) \
tex(Erewhon-Bold-osf-ly1.tfm) \
tex(Erewhon-Bold-osf-ot1.tfm) \
tex(Erewhon-Bold-osf-sc-ly1--base.tfm) \
tex(Erewhon-Bold-osf-sc-ly1.tfm) \
tex(Erewhon-Bold-osf-sc-ly1.vf) \
tex(Erewhon-Bold-osf-sc-ot1--base.tfm) \
tex(Erewhon-Bold-osf-sc-ot1.tfm) \
tex(Erewhon-Bold-osf-sc-ot1.vf) \
tex(Erewhon-Bold-osf-sc-t1--base.tfm) \
tex(Erewhon-Bold-osf-sc-t1.tfm) \
tex(Erewhon-Bold-osf-sc-t1.vf) \
tex(Erewhon-Bold-osf-sc-t2a--base.tfm) \
tex(Erewhon-Bold-osf-sc-t2a.tfm) \
tex(Erewhon-Bold-osf-sc-t2a.vf) \
tex(Erewhon-Bold-osf-sc-t2b--base.tfm) \
tex(Erewhon-Bold-osf-sc-t2b.tfm) \
tex(Erewhon-Bold-osf-sc-t2b.vf) \
tex(Erewhon-Bold-osf-sc-t2c--base.tfm) \
tex(Erewhon-Bold-osf-sc-t2c.tfm) \
tex(Erewhon-Bold-osf-sc-t2c.vf) \
tex(Erewhon-Bold-osf-t1--base.tfm) \
tex(Erewhon-Bold-osf-t1.tfm) \
tex(Erewhon-Bold-osf-t1.vf) \
tex(Erewhon-Bold-osf-t2a.tfm) \
tex(Erewhon-Bold-osf-t2b.tfm) \
tex(Erewhon-Bold-osf-t2c.tfm) \
tex(Erewhon-Bold-osf-ts1--base.tfm) \
tex(Erewhon-Bold-osf-ts1.tfm) \
tex(Erewhon-Bold-osf-ts1.vf) \
tex(Erewhon-Bold-sup-ly1.tfm) \
tex(Erewhon-Bold-sup-ot1.tfm) \
tex(Erewhon-Bold-sup-t1--base.tfm) \
tex(Erewhon-Bold-sup-t1.tfm) \
tex(Erewhon-Bold-sup-t1.vf) \
tex(Erewhon-Bold-sup-t2a.tfm) \
tex(Erewhon-Bold-sup-t2b.tfm) \
tex(Erewhon-Bold-sup-t2c.tfm) \
tex(Erewhon-Bold-tlf-ly1.tfm) \
tex(Erewhon-Bold-tlf-ot1.tfm) \
tex(Erewhon-Bold-tlf-ot2.tfm) \
tex(Erewhon-Bold-tlf-sc-ly1--base.tfm) \
tex(Erewhon-Bold-tlf-sc-ly1.tfm) \
tex(Erewhon-Bold-tlf-sc-ly1.vf) \
tex(Erewhon-Bold-tlf-sc-ot1--base.tfm) \
tex(Erewhon-Bold-tlf-sc-ot1.tfm) \
tex(Erewhon-Bold-tlf-sc-ot1.vf) \
tex(Erewhon-Bold-tlf-sc-t1--base.tfm) \
tex(Erewhon-Bold-tlf-sc-t1.tfm) \
tex(Erewhon-Bold-tlf-sc-t1.vf) \
tex(Erewhon-Bold-tlf-sc-t2a--base.tfm) \
tex(Erewhon-Bold-tlf-sc-t2a.tfm) \
tex(Erewhon-Bold-tlf-sc-t2a.vf) \
tex(Erewhon-Bold-tlf-sc-t2b--base.tfm) \
tex(Erewhon-Bold-tlf-sc-t2b.tfm) \
tex(Erewhon-Bold-tlf-sc-t2b.vf) \
tex(Erewhon-Bold-tlf-sc-t2c--base.tfm) \
tex(Erewhon-Bold-tlf-sc-t2c.tfm) \
tex(Erewhon-Bold-tlf-sc-t2c.vf) \
tex(Erewhon-Bold-tlf-t1--base.tfm) \
tex(Erewhon-Bold-tlf-t1.tfm) \
tex(Erewhon-Bold-tlf-t1.vf) \
tex(Erewhon-Bold-tlf-t2a.tfm) \
tex(Erewhon-Bold-tlf-t2b.tfm) \
tex(Erewhon-Bold-tlf-t2c.tfm) \
tex(Erewhon-Bold-tlf-ts1--base.tfm) \
tex(Erewhon-Bold-tlf-ts1.tfm) \
tex(Erewhon-Bold-tlf-ts1.vf) \
tex(Erewhon-Bold-tosf-ly1.tfm) \
tex(Erewhon-Bold-tosf-ot1.tfm) \
tex(Erewhon-Bold-tosf-sc-ly1--base.tfm) \
tex(Erewhon-Bold-tosf-sc-ly1.tfm) \
tex(Erewhon-Bold-tosf-sc-ly1.vf) \
tex(Erewhon-Bold-tosf-sc-ot1--base.tfm) \
tex(Erewhon-Bold-tosf-sc-ot1.tfm) \
tex(Erewhon-Bold-tosf-sc-ot1.vf) \
tex(Erewhon-Bold-tosf-sc-t1--base.tfm) \
tex(Erewhon-Bold-tosf-sc-t1.tfm) \
tex(Erewhon-Bold-tosf-sc-t1.vf) \
tex(Erewhon-Bold-tosf-sc-t2a--base.tfm) \
tex(Erewhon-Bold-tosf-sc-t2a.tfm) \
tex(Erewhon-Bold-tosf-sc-t2a.vf) \
tex(Erewhon-Bold-tosf-sc-t2b--base.tfm) \
tex(Erewhon-Bold-tosf-sc-t2b.tfm) \
tex(Erewhon-Bold-tosf-sc-t2b.vf) \
tex(Erewhon-Bold-tosf-sc-t2c--base.tfm) \
tex(Erewhon-Bold-tosf-sc-t2c.tfm) \
tex(Erewhon-Bold-tosf-sc-t2c.vf) \
tex(Erewhon-Bold-tosf-t1--base.tfm) \
tex(Erewhon-Bold-tosf-t1.tfm) \
tex(Erewhon-Bold-tosf-t1.vf) \
tex(Erewhon-Bold-tosf-t2a.tfm) \
tex(Erewhon-Bold-tosf-t2b.tfm) \
tex(Erewhon-Bold-tosf-t2c.tfm) \
tex(Erewhon-Bold-tosf-ts1--base.tfm) \
tex(Erewhon-Bold-tosf-ts1.tfm) \
tex(Erewhon-Bold-tosf-ts1.vf) \
tex(Erewhon-BoldItalic-dnom-ly1.tfm) \
tex(Erewhon-BoldItalic-dnom-ot1.tfm) \
tex(Erewhon-BoldItalic-dnom-t1--base.tfm) \
tex(Erewhon-BoldItalic-dnom-t1.tfm) \
tex(Erewhon-BoldItalic-dnom-t1.vf) \
tex(Erewhon-BoldItalic-dnom-t2a.tfm) \
tex(Erewhon-BoldItalic-dnom-t2b.tfm) \
tex(Erewhon-BoldItalic-dnom-t2c.tfm) \
tex(Erewhon-BoldItalic-inf-ly1.tfm) \
tex(Erewhon-BoldItalic-inf-ot1.tfm) \
tex(Erewhon-BoldItalic-inf-t1--base.tfm) \
tex(Erewhon-BoldItalic-inf-t1.tfm) \
tex(Erewhon-BoldItalic-inf-t1.vf) \
tex(Erewhon-BoldItalic-inf-t2a.tfm) \
tex(Erewhon-BoldItalic-inf-t2b.tfm) \
tex(Erewhon-BoldItalic-inf-t2c.tfm) \
tex(Erewhon-BoldItalic-lf-ly1.tfm) \
tex(Erewhon-BoldItalic-lf-ot1.tfm) \
tex(Erewhon-BoldItalic-lf-sc-ly1--base.tfm) \
tex(Erewhon-BoldItalic-lf-sc-ly1.tfm) \
tex(Erewhon-BoldItalic-lf-sc-ly1.vf) \
tex(Erewhon-BoldItalic-lf-sc-ot1--base.tfm) \
tex(Erewhon-BoldItalic-lf-sc-ot1.tfm) \
tex(Erewhon-BoldItalic-lf-sc-ot1.vf) \
tex(Erewhon-BoldItalic-lf-sc-t1--base.tfm) \
tex(Erewhon-BoldItalic-lf-sc-t1.tfm) \
tex(Erewhon-BoldItalic-lf-sc-t1.vf) \
tex(Erewhon-BoldItalic-lf-sc-t2a--base.tfm) \
tex(Erewhon-BoldItalic-lf-sc-t2a.tfm) \
tex(Erewhon-BoldItalic-lf-sc-t2a.vf) \
tex(Erewhon-BoldItalic-lf-sc-t2b--base.tfm) \
tex(Erewhon-BoldItalic-lf-sc-t2b.tfm) \
tex(Erewhon-BoldItalic-lf-sc-t2b.vf) \
tex(Erewhon-BoldItalic-lf-sc-t2c--base.tfm) \
tex(Erewhon-BoldItalic-lf-sc-t2c.tfm) \
tex(Erewhon-BoldItalic-lf-sc-t2c.vf) \
tex(Erewhon-BoldItalic-lf-t1--base.tfm) \
tex(Erewhon-BoldItalic-lf-t1.tfm) \
tex(Erewhon-BoldItalic-lf-t1.vf) \
tex(Erewhon-BoldItalic-lf-t2a.tfm) \
tex(Erewhon-BoldItalic-lf-t2b.tfm) \
tex(Erewhon-BoldItalic-lf-t2c.tfm) \
tex(Erewhon-BoldItalic-lf-ts1--base.tfm) \
tex(Erewhon-BoldItalic-lf-ts1.tfm) \
tex(Erewhon-BoldItalic-lf-ts1.vf) \
tex(Erewhon-BoldItalic-numr-ly1.tfm) \
tex(Erewhon-BoldItalic-numr-ot1.tfm) \
tex(Erewhon-BoldItalic-numr-t1--base.tfm) \
tex(Erewhon-BoldItalic-numr-t1.tfm) \
tex(Erewhon-BoldItalic-numr-t1.vf) \
tex(Erewhon-BoldItalic-numr-t2a.tfm) \
tex(Erewhon-BoldItalic-numr-t2b.tfm) \
tex(Erewhon-BoldItalic-numr-t2c.tfm) \
tex(Erewhon-BoldItalic-osf-ly1.tfm) \
tex(Erewhon-BoldItalic-osf-ot1.tfm) \
tex(Erewhon-BoldItalic-osf-sc-ly1--base.tfm) \
tex(Erewhon-BoldItalic-osf-sc-ly1.tfm) \
tex(Erewhon-BoldItalic-osf-sc-ly1.vf) \
tex(Erewhon-BoldItalic-osf-sc-ot1--base.tfm) \
tex(Erewhon-BoldItalic-osf-sc-ot1.tfm) \
tex(Erewhon-BoldItalic-osf-sc-ot1.vf) \
tex(Erewhon-BoldItalic-osf-sc-t1--base.tfm) \
tex(Erewhon-BoldItalic-osf-sc-t1.tfm) \
tex(Erewhon-BoldItalic-osf-sc-t1.vf) \
tex(Erewhon-BoldItalic-osf-sc-t2a--base.tfm) \
tex(Erewhon-BoldItalic-osf-sc-t2a.tfm) \
tex(Erewhon-BoldItalic-osf-sc-t2a.vf) \
tex(Erewhon-BoldItalic-osf-sc-t2b--base.tfm) \
tex(Erewhon-BoldItalic-osf-sc-t2b.tfm) \
tex(Erewhon-BoldItalic-osf-sc-t2b.vf) \
tex(Erewhon-BoldItalic-osf-sc-t2c--base.tfm) \
tex(Erewhon-BoldItalic-osf-sc-t2c.tfm) \
tex(Erewhon-BoldItalic-osf-sc-t2c.vf) \
tex(Erewhon-BoldItalic-osf-t1--base.tfm) \
tex(Erewhon-BoldItalic-osf-t1.tfm) \
tex(Erewhon-BoldItalic-osf-t1.vf) \
tex(Erewhon-BoldItalic-osf-t2a.tfm) \
tex(Erewhon-BoldItalic-osf-t2b.tfm) \
tex(Erewhon-BoldItalic-osf-t2c.tfm) \
tex(Erewhon-BoldItalic-osf-ts1--base.tfm) \
tex(Erewhon-BoldItalic-osf-ts1.tfm) \
tex(Erewhon-BoldItalic-osf-ts1.vf) \
tex(Erewhon-BoldItalic-sup-ly1.tfm) \
tex(Erewhon-BoldItalic-sup-ot1.tfm) \
tex(Erewhon-BoldItalic-sup-t1--base.tfm) \
tex(Erewhon-BoldItalic-sup-t1.tfm) \
tex(Erewhon-BoldItalic-sup-t1.vf) \
tex(Erewhon-BoldItalic-sup-t2a.tfm) \
tex(Erewhon-BoldItalic-sup-t2b.tfm) \
tex(Erewhon-BoldItalic-sup-t2c.tfm) \
tex(Erewhon-BoldItalic-tlf-ly1.tfm) \
tex(Erewhon-BoldItalic-tlf-ot1.tfm) \
tex(Erewhon-BoldItalic-tlf-ot2.tfm) \
tex(Erewhon-BoldItalic-tlf-sc-ly1--base.tfm) \
tex(Erewhon-BoldItalic-tlf-sc-ly1.tfm) \
tex(Erewhon-BoldItalic-tlf-sc-ly1.vf) \
tex(Erewhon-BoldItalic-tlf-sc-ot1--base.tfm) \
tex(Erewhon-BoldItalic-tlf-sc-ot1.tfm) \
tex(Erewhon-BoldItalic-tlf-sc-ot1.vf) \
tex(Erewhon-BoldItalic-tlf-sc-t1--base.tfm) \
tex(Erewhon-BoldItalic-tlf-sc-t1.tfm) \
tex(Erewhon-BoldItalic-tlf-sc-t1.vf) \
tex(Erewhon-BoldItalic-tlf-sc-t2a--base.tfm) \
tex(Erewhon-BoldItalic-tlf-sc-t2a.tfm) \
tex(Erewhon-BoldItalic-tlf-sc-t2a.vf) \
tex(Erewhon-BoldItalic-tlf-sc-t2b--base.tfm) \
tex(Erewhon-BoldItalic-tlf-sc-t2b.tfm) \
tex(Erewhon-BoldItalic-tlf-sc-t2b.vf) \
tex(Erewhon-BoldItalic-tlf-sc-t2c--base.tfm) \
tex(Erewhon-BoldItalic-tlf-sc-t2c.tfm) \
tex(Erewhon-BoldItalic-tlf-sc-t2c.vf) \
tex(Erewhon-BoldItalic-tlf-t1--base.tfm) \
tex(Erewhon-BoldItalic-tlf-t1.tfm) \
tex(Erewhon-BoldItalic-tlf-t1.vf) \
tex(Erewhon-BoldItalic-tlf-t2a.tfm) \
tex(Erewhon-BoldItalic-tlf-t2b.tfm) \
tex(Erewhon-BoldItalic-tlf-t2c.tfm) \
tex(Erewhon-BoldItalic-tlf-ts1--base.tfm) \
tex(Erewhon-BoldItalic-tlf-ts1.tfm) \
tex(Erewhon-BoldItalic-tlf-ts1.vf) \
tex(Erewhon-BoldItalic-tosf-ly1.tfm) \
tex(Erewhon-BoldItalic-tosf-ot1.tfm) \
tex(Erewhon-BoldItalic-tosf-sc-ly1--base.tfm) \
tex(Erewhon-BoldItalic-tosf-sc-ly1.tfm) \
tex(Erewhon-BoldItalic-tosf-sc-ly1.vf) \
tex(Erewhon-BoldItalic-tosf-sc-ot1--base.tfm) \
tex(Erewhon-BoldItalic-tosf-sc-ot1.tfm) \
tex(Erewhon-BoldItalic-tosf-sc-ot1.vf) \
tex(Erewhon-BoldItalic-tosf-sc-t1--base.tfm) \
tex(Erewhon-BoldItalic-tosf-sc-t1.tfm) \
tex(Erewhon-BoldItalic-tosf-sc-t1.vf) \
tex(Erewhon-BoldItalic-tosf-sc-t2a--base.tfm) \
tex(Erewhon-BoldItalic-tosf-sc-t2a.tfm) \
tex(Erewhon-BoldItalic-tosf-sc-t2a.vf) \
tex(Erewhon-BoldItalic-tosf-sc-t2b--base.tfm) \
tex(Erewhon-BoldItalic-tosf-sc-t2b.tfm) \
tex(Erewhon-BoldItalic-tosf-sc-t2b.vf) \
tex(Erewhon-BoldItalic-tosf-sc-t2c--base.tfm) \
tex(Erewhon-BoldItalic-tosf-sc-t2c.tfm) \
tex(Erewhon-BoldItalic-tosf-sc-t2c.vf) \
tex(Erewhon-BoldItalic-tosf-t1--base.tfm) \
tex(Erewhon-BoldItalic-tosf-t1.tfm) \
tex(Erewhon-BoldItalic-tosf-t1.vf) \
tex(Erewhon-BoldItalic-tosf-t2a.tfm) \
tex(Erewhon-BoldItalic-tosf-t2b.tfm) \
tex(Erewhon-BoldItalic-tosf-t2c.tfm) \
tex(Erewhon-BoldItalic-tosf-ts1--base.tfm) \
tex(Erewhon-BoldItalic-tosf-ts1.tfm) \
tex(Erewhon-BoldItalic-tosf-ts1.vf) \
tex(Erewhon-BoldSlanted-dnom-ly1.tfm) \
tex(Erewhon-BoldSlanted-dnom-ot1.tfm) \
tex(Erewhon-BoldSlanted-dnom-t1--base.tfm) \
tex(Erewhon-BoldSlanted-dnom-t1.tfm) \
tex(Erewhon-BoldSlanted-dnom-t1.vf) \
tex(Erewhon-BoldSlanted-dnom-t2a.tfm) \
tex(Erewhon-BoldSlanted-dnom-t2b.tfm) \
tex(Erewhon-BoldSlanted-dnom-t2c.tfm) \
tex(Erewhon-BoldSlanted-inf-ly1.tfm) \
tex(Erewhon-BoldSlanted-inf-ot1.tfm) \
tex(Erewhon-BoldSlanted-inf-t1--base.tfm) \
tex(Erewhon-BoldSlanted-inf-t1.tfm) \
tex(Erewhon-BoldSlanted-inf-t1.vf) \
tex(Erewhon-BoldSlanted-inf-t2a.tfm) \
tex(Erewhon-BoldSlanted-inf-t2b.tfm) \
tex(Erewhon-BoldSlanted-inf-t2c.tfm) \
tex(Erewhon-BoldSlanted-lf-ly1.tfm) \
tex(Erewhon-BoldSlanted-lf-ot1.tfm) \
tex(Erewhon-BoldSlanted-lf-sc-ly1--base.tfm) \
tex(Erewhon-BoldSlanted-lf-sc-ly1.tfm) \
tex(Erewhon-BoldSlanted-lf-sc-ly1.vf) \
tex(Erewhon-BoldSlanted-lf-sc-ot1--base.tfm) \
tex(Erewhon-BoldSlanted-lf-sc-ot1.tfm) \
tex(Erewhon-BoldSlanted-lf-sc-ot1.vf) \
tex(Erewhon-BoldSlanted-lf-sc-t1--base.tfm) \
tex(Erewhon-BoldSlanted-lf-sc-t1.tfm) \
tex(Erewhon-BoldSlanted-lf-sc-t1.vf) \
tex(Erewhon-BoldSlanted-lf-sc-t2a--base.tfm) \
tex(Erewhon-BoldSlanted-lf-sc-t2a.tfm) \
tex(Erewhon-BoldSlanted-lf-sc-t2a.vf) \
tex(Erewhon-BoldSlanted-lf-sc-t2b--base.tfm) \
tex(Erewhon-BoldSlanted-lf-sc-t2b.tfm) \
tex(Erewhon-BoldSlanted-lf-sc-t2b.vf) \
tex(Erewhon-BoldSlanted-lf-sc-t2c--base.tfm) \
tex(Erewhon-BoldSlanted-lf-sc-t2c.tfm) \
tex(Erewhon-BoldSlanted-lf-sc-t2c.vf) \
tex(Erewhon-BoldSlanted-lf-t1--base.tfm) \
tex(Erewhon-BoldSlanted-lf-t1.tfm) \
tex(Erewhon-BoldSlanted-lf-t1.vf) \
tex(Erewhon-BoldSlanted-lf-t2a.tfm) \
tex(Erewhon-BoldSlanted-lf-t2b.tfm) \
tex(Erewhon-BoldSlanted-lf-t2c.tfm) \
tex(Erewhon-BoldSlanted-lf-ts1--base.tfm) \
tex(Erewhon-BoldSlanted-lf-ts1.tfm) \
tex(Erewhon-BoldSlanted-lf-ts1.vf) \
tex(Erewhon-BoldSlanted-numr-ly1.tfm) \
tex(Erewhon-BoldSlanted-numr-ot1.tfm) \
tex(Erewhon-BoldSlanted-numr-t1--base.tfm) \
tex(Erewhon-BoldSlanted-numr-t1.tfm) \
tex(Erewhon-BoldSlanted-numr-t1.vf) \
tex(Erewhon-BoldSlanted-numr-t2a.tfm) \
tex(Erewhon-BoldSlanted-numr-t2b.tfm) \
tex(Erewhon-BoldSlanted-numr-t2c.tfm) \
tex(Erewhon-BoldSlanted-osf-ly1.tfm) \
tex(Erewhon-BoldSlanted-osf-ot1.tfm) \
tex(Erewhon-BoldSlanted-osf-sc-ly1--base.tfm) \
tex(Erewhon-BoldSlanted-osf-sc-ly1.tfm) \
tex(Erewhon-BoldSlanted-osf-sc-ly1.vf) \
tex(Erewhon-BoldSlanted-osf-sc-ot1--base.tfm) \
tex(Erewhon-BoldSlanted-osf-sc-ot1.tfm) \
tex(Erewhon-BoldSlanted-osf-sc-ot1.vf) \
tex(Erewhon-BoldSlanted-osf-sc-t1--base.tfm) \
tex(Erewhon-BoldSlanted-osf-sc-t1.tfm) \
tex(Erewhon-BoldSlanted-osf-sc-t1.vf) \
tex(Erewhon-BoldSlanted-osf-sc-t2a--base.tfm) \
tex(Erewhon-BoldSlanted-osf-sc-t2a.tfm) \
tex(Erewhon-BoldSlanted-osf-sc-t2a.vf) \
tex(Erewhon-BoldSlanted-osf-sc-t2b--base.tfm) \
tex(Erewhon-BoldSlanted-osf-sc-t2b.tfm) \
tex(Erewhon-BoldSlanted-osf-sc-t2b.vf) \
tex(Erewhon-BoldSlanted-osf-sc-t2c--base.tfm) \
tex(Erewhon-BoldSlanted-osf-sc-t2c.tfm) \
tex(Erewhon-BoldSlanted-osf-sc-t2c.vf) \
tex(Erewhon-BoldSlanted-osf-t1--base.tfm) \
tex(Erewhon-BoldSlanted-osf-t1.tfm) \
tex(Erewhon-BoldSlanted-osf-t1.vf) \
tex(Erewhon-BoldSlanted-osf-t2a.tfm) \
tex(Erewhon-BoldSlanted-osf-t2b.tfm) \
tex(Erewhon-BoldSlanted-osf-t2c.tfm) \
tex(Erewhon-BoldSlanted-osf-ts1--base.tfm) \
tex(Erewhon-BoldSlanted-osf-ts1.tfm) \
tex(Erewhon-BoldSlanted-osf-ts1.vf) \
tex(Erewhon-BoldSlanted-sup-ly1.tfm) \
tex(Erewhon-BoldSlanted-sup-ot1.tfm) \
tex(Erewhon-BoldSlanted-sup-t1--base.tfm) \
tex(Erewhon-BoldSlanted-sup-t1.tfm) \
tex(Erewhon-BoldSlanted-sup-t1.vf) \
tex(Erewhon-BoldSlanted-sup-t2a.tfm) \
tex(Erewhon-BoldSlanted-sup-t2b.tfm) \
tex(Erewhon-BoldSlanted-sup-t2c.tfm) \
tex(Erewhon-BoldSlanted-tlf-ly1.tfm) \
tex(Erewhon-BoldSlanted-tlf-ot1.tfm) \
tex(Erewhon-BoldSlanted-tlf-ot2.tfm) \
tex(Erewhon-BoldSlanted-tlf-sc-ly1--base.tfm) \
tex(Erewhon-BoldSlanted-tlf-sc-ly1.tfm) \
tex(Erewhon-BoldSlanted-tlf-sc-ly1.vf) \
tex(Erewhon-BoldSlanted-tlf-sc-ot1--base.tfm) \
tex(Erewhon-BoldSlanted-tlf-sc-ot1.tfm) \
tex(Erewhon-BoldSlanted-tlf-sc-ot1.vf) \
tex(Erewhon-BoldSlanted-tlf-sc-t1--base.tfm) \
tex(Erewhon-BoldSlanted-tlf-sc-t1.tfm) \
tex(Erewhon-BoldSlanted-tlf-sc-t1.vf) \
tex(Erewhon-BoldSlanted-tlf-sc-t2a--base.tfm) \
tex(Erewhon-BoldSlanted-tlf-sc-t2a.tfm) \
tex(Erewhon-BoldSlanted-tlf-sc-t2a.vf) \
tex(Erewhon-BoldSlanted-tlf-sc-t2b--base.tfm) \
tex(Erewhon-BoldSlanted-tlf-sc-t2b.tfm) \
tex(Erewhon-BoldSlanted-tlf-sc-t2b.vf) \
tex(Erewhon-BoldSlanted-tlf-sc-t2c--base.tfm) \
tex(Erewhon-BoldSlanted-tlf-sc-t2c.tfm) \
tex(Erewhon-BoldSlanted-tlf-sc-t2c.vf) \
tex(Erewhon-BoldSlanted-tlf-t1--base.tfm) \
tex(Erewhon-BoldSlanted-tlf-t1.tfm) \
tex(Erewhon-BoldSlanted-tlf-t1.vf) \
tex(Erewhon-BoldSlanted-tlf-t2a.tfm) \
tex(Erewhon-BoldSlanted-tlf-t2b.tfm) \
tex(Erewhon-BoldSlanted-tlf-t2c.tfm) \
tex(Erewhon-BoldSlanted-tlf-ts1--base.tfm) \
tex(Erewhon-BoldSlanted-tlf-ts1.tfm) \
tex(Erewhon-BoldSlanted-tlf-ts1.vf) \
tex(Erewhon-BoldSlanted-tosf-ly1.tfm) \
tex(Erewhon-BoldSlanted-tosf-ot1.tfm) \
tex(Erewhon-BoldSlanted-tosf-sc-ly1--base.tfm) \
tex(Erewhon-BoldSlanted-tosf-sc-ly1.tfm) \
tex(Erewhon-BoldSlanted-tosf-sc-ly1.vf) \
tex(Erewhon-BoldSlanted-tosf-sc-ot1--base.tfm) \
tex(Erewhon-BoldSlanted-tosf-sc-ot1.tfm) \
tex(Erewhon-BoldSlanted-tosf-sc-ot1.vf) \
tex(Erewhon-BoldSlanted-tosf-sc-t1--base.tfm) \
tex(Erewhon-BoldSlanted-tosf-sc-t1.tfm) \
tex(Erewhon-BoldSlanted-tosf-sc-t1.vf) \
tex(Erewhon-BoldSlanted-tosf-sc-t2a--base.tfm) \
tex(Erewhon-BoldSlanted-tosf-sc-t2a.tfm) \
tex(Erewhon-BoldSlanted-tosf-sc-t2a.vf) \
tex(Erewhon-BoldSlanted-tosf-sc-t2b--base.tfm) \
tex(Erewhon-BoldSlanted-tosf-sc-t2b.tfm) \
tex(Erewhon-BoldSlanted-tosf-sc-t2b.vf) \
tex(Erewhon-BoldSlanted-tosf-sc-t2c--base.tfm) \
tex(Erewhon-BoldSlanted-tosf-sc-t2c.tfm) \
tex(Erewhon-BoldSlanted-tosf-sc-t2c.vf) \
tex(Erewhon-BoldSlanted-tosf-t1--base.tfm) \
tex(Erewhon-BoldSlanted-tosf-t1.tfm) \
tex(Erewhon-BoldSlanted-tosf-t1.vf) \
tex(Erewhon-BoldSlanted-tosf-t2a.tfm) \
tex(Erewhon-BoldSlanted-tosf-t2b.tfm) \
tex(Erewhon-BoldSlanted-tosf-t2c.tfm) \
tex(Erewhon-BoldSlanted-tosf-ts1--base.tfm) \
tex(Erewhon-BoldSlanted-tosf-ts1.tfm) \
tex(Erewhon-BoldSlanted-tosf-ts1.vf) \
tex(Erewhon-Italic-dnom-ly1.tfm) \
tex(Erewhon-Italic-dnom-ot1.tfm) \
tex(Erewhon-Italic-dnom-t1--base.tfm) \
tex(Erewhon-Italic-dnom-t1.tfm) \
tex(Erewhon-Italic-dnom-t1.vf) \
tex(Erewhon-Italic-dnom-t2a.tfm) \
tex(Erewhon-Italic-dnom-t2b.tfm) \
tex(Erewhon-Italic-dnom-t2c.tfm) \
tex(Erewhon-Italic-inf-ly1.tfm) \
tex(Erewhon-Italic-inf-ot1.tfm) \
tex(Erewhon-Italic-inf-t1--base.tfm) \
tex(Erewhon-Italic-inf-t1.tfm) \
tex(Erewhon-Italic-inf-t1.vf) \
tex(Erewhon-Italic-inf-t2a.tfm) \
tex(Erewhon-Italic-inf-t2b.tfm) \
tex(Erewhon-Italic-inf-t2c.tfm) \
tex(Erewhon-Italic-lf-ly1.tfm) \
tex(Erewhon-Italic-lf-ot1.tfm) \
tex(Erewhon-Italic-lf-sc-ly1--base.tfm) \
tex(Erewhon-Italic-lf-sc-ly1.tfm) \
tex(Erewhon-Italic-lf-sc-ly1.vf) \
tex(Erewhon-Italic-lf-sc-ot1--base.tfm) \
tex(Erewhon-Italic-lf-sc-ot1.tfm) \
tex(Erewhon-Italic-lf-sc-ot1.vf) \
tex(Erewhon-Italic-lf-sc-t1--base.tfm) \
tex(Erewhon-Italic-lf-sc-t1.tfm) \
tex(Erewhon-Italic-lf-sc-t1.vf) \
tex(Erewhon-Italic-lf-sc-t2a--base.tfm) \
tex(Erewhon-Italic-lf-sc-t2a.tfm) \
tex(Erewhon-Italic-lf-sc-t2a.vf) \
tex(Erewhon-Italic-lf-sc-t2b--base.tfm) \
tex(Erewhon-Italic-lf-sc-t2b.tfm) \
tex(Erewhon-Italic-lf-sc-t2b.vf) \
tex(Erewhon-Italic-lf-sc-t2c--base.tfm) \
tex(Erewhon-Italic-lf-sc-t2c.tfm) \
tex(Erewhon-Italic-lf-sc-t2c.vf) \
tex(Erewhon-Italic-lf-t1--base.tfm) \
tex(Erewhon-Italic-lf-t1.tfm) \
tex(Erewhon-Italic-lf-t1.vf) \
tex(Erewhon-Italic-lf-t2a.tfm) \
tex(Erewhon-Italic-lf-t2b.tfm) \
tex(Erewhon-Italic-lf-t2c.tfm) \
tex(Erewhon-Italic-lf-ts1--base.tfm) \
tex(Erewhon-Italic-lf-ts1.tfm) \
tex(Erewhon-Italic-lf-ts1.vf) \
tex(Erewhon-Italic-numr-ly1.tfm) \
tex(Erewhon-Italic-numr-ot1.tfm) \
tex(Erewhon-Italic-numr-t1--base.tfm) \
tex(Erewhon-Italic-numr-t1.tfm) \
tex(Erewhon-Italic-numr-t1.vf) \
tex(Erewhon-Italic-numr-t2a.tfm) \
tex(Erewhon-Italic-numr-t2b.tfm) \
tex(Erewhon-Italic-numr-t2c.tfm) \
tex(Erewhon-Italic-osf-ly1.tfm) \
tex(Erewhon-Italic-osf-ot1.tfm) \
tex(Erewhon-Italic-osf-sc-ly1--base.tfm) \
tex(Erewhon-Italic-osf-sc-ly1.tfm) \
tex(Erewhon-Italic-osf-sc-ly1.vf) \
tex(Erewhon-Italic-osf-sc-ot1--base.tfm) \
tex(Erewhon-Italic-osf-sc-ot1.tfm) \
tex(Erewhon-Italic-osf-sc-ot1.vf) \
tex(Erewhon-Italic-osf-sc-t1--base.tfm) \
tex(Erewhon-Italic-osf-sc-t1.tfm) \
tex(Erewhon-Italic-osf-sc-t1.vf) \
tex(Erewhon-Italic-osf-sc-t2a--base.tfm) \
tex(Erewhon-Italic-osf-sc-t2a.tfm) \
tex(Erewhon-Italic-osf-sc-t2a.vf) \
tex(Erewhon-Italic-osf-sc-t2b--base.tfm) \
tex(Erewhon-Italic-osf-sc-t2b.tfm) \
tex(Erewhon-Italic-osf-sc-t2b.vf) \
tex(Erewhon-Italic-osf-sc-t2c--base.tfm) \
tex(Erewhon-Italic-osf-sc-t2c.tfm) \
tex(Erewhon-Italic-osf-sc-t2c.vf) \
tex(Erewhon-Italic-osf-t1--base.tfm) \
tex(Erewhon-Italic-osf-t1.tfm) \
tex(Erewhon-Italic-osf-t1.vf) \
tex(Erewhon-Italic-osf-t2a.tfm) \
tex(Erewhon-Italic-osf-t2b.tfm) \
tex(Erewhon-Italic-osf-t2c.tfm) \
tex(Erewhon-Italic-osf-ts1--base.tfm) \
tex(Erewhon-Italic-osf-ts1.tfm) \
tex(Erewhon-Italic-osf-ts1.vf) \
tex(Erewhon-Italic-sup-ly1.tfm) \
tex(Erewhon-Italic-sup-ot1.tfm) \
tex(Erewhon-Italic-sup-t1--base.tfm) \
tex(Erewhon-Italic-sup-t1.tfm) \
tex(Erewhon-Italic-sup-t1.vf) \
tex(Erewhon-Italic-sup-t2a.tfm) \
tex(Erewhon-Italic-sup-t2b.tfm) \
tex(Erewhon-Italic-sup-t2c.tfm) \
tex(Erewhon-Italic-tlf-ly1.tfm) \
tex(Erewhon-Italic-tlf-ot1.tfm) \
tex(Erewhon-Italic-tlf-ot2.tfm) \
tex(Erewhon-Italic-tlf-sc-ly1--base.tfm) \
tex(Erewhon-Italic-tlf-sc-ly1.tfm) \
tex(Erewhon-Italic-tlf-sc-ly1.vf) \
tex(Erewhon-Italic-tlf-sc-ot1--base.tfm) \
tex(Erewhon-Italic-tlf-sc-ot1.tfm) \
tex(Erewhon-Italic-tlf-sc-ot1.vf) \
tex(Erewhon-Italic-tlf-sc-t1--base.tfm) \
tex(Erewhon-Italic-tlf-sc-t1.tfm) \
tex(Erewhon-Italic-tlf-sc-t1.vf) \
tex(Erewhon-Italic-tlf-sc-t2a--base.tfm) \
tex(Erewhon-Italic-tlf-sc-t2a.tfm) \
tex(Erewhon-Italic-tlf-sc-t2a.vf) \
tex(Erewhon-Italic-tlf-sc-t2b--base.tfm) \
tex(Erewhon-Italic-tlf-sc-t2b.tfm) \
tex(Erewhon-Italic-tlf-sc-t2b.vf) \
tex(Erewhon-Italic-tlf-sc-t2c--base.tfm) \
tex(Erewhon-Italic-tlf-sc-t2c.tfm) \
tex(Erewhon-Italic-tlf-sc-t2c.vf) \
tex(Erewhon-Italic-tlf-t1--base.tfm) \
tex(Erewhon-Italic-tlf-t1.tfm) \
tex(Erewhon-Italic-tlf-t1.vf) \
tex(Erewhon-Italic-tlf-t2a.tfm) \
tex(Erewhon-Italic-tlf-t2b.tfm) \
tex(Erewhon-Italic-tlf-t2c.tfm) \
tex(Erewhon-Italic-tlf-ts1--base.tfm) \
tex(Erewhon-Italic-tlf-ts1.tfm) \
tex(Erewhon-Italic-tlf-ts1.vf) \
tex(Erewhon-Italic-tosf-ly1.tfm) \
tex(Erewhon-Italic-tosf-ot1.tfm) \
tex(Erewhon-Italic-tosf-sc-ly1--base.tfm) \
tex(Erewhon-Italic-tosf-sc-ly1.tfm) \
tex(Erewhon-Italic-tosf-sc-ly1.vf) \
tex(Erewhon-Italic-tosf-sc-ot1--base.tfm) \
tex(Erewhon-Italic-tosf-sc-ot1.tfm) \
tex(Erewhon-Italic-tosf-sc-ot1.vf) \
tex(Erewhon-Italic-tosf-sc-t1--base.tfm) \
tex(Erewhon-Italic-tosf-sc-t1.tfm) \
tex(Erewhon-Italic-tosf-sc-t1.vf) \
tex(Erewhon-Italic-tosf-sc-t2a--base.tfm) \
tex(Erewhon-Italic-tosf-sc-t2a.tfm) \
tex(Erewhon-Italic-tosf-sc-t2a.vf) \
tex(Erewhon-Italic-tosf-sc-t2b--base.tfm) \
tex(Erewhon-Italic-tosf-sc-t2b.tfm) \
tex(Erewhon-Italic-tosf-sc-t2b.vf) \
tex(Erewhon-Italic-tosf-sc-t2c--base.tfm) \
tex(Erewhon-Italic-tosf-sc-t2c.tfm) \
tex(Erewhon-Italic-tosf-sc-t2c.vf) \
tex(Erewhon-Italic-tosf-t1--base.tfm) \
tex(Erewhon-Italic-tosf-t1.tfm) \
tex(Erewhon-Italic-tosf-t1.vf) \
tex(Erewhon-Italic-tosf-t2a.tfm) \
tex(Erewhon-Italic-tosf-t2b.tfm) \
tex(Erewhon-Italic-tosf-t2c.tfm) \
tex(Erewhon-Italic-tosf-ts1--base.tfm) \
tex(Erewhon-Italic-tosf-ts1.tfm) \
tex(Erewhon-Italic-tosf-ts1.vf) \
tex(Erewhon-Regular-dnom-ly1.tfm) \
tex(Erewhon-Regular-dnom-ot1.tfm) \
tex(Erewhon-Regular-dnom-t1--base.tfm) \
tex(Erewhon-Regular-dnom-t1.tfm) \
tex(Erewhon-Regular-dnom-t1.vf) \
tex(Erewhon-Regular-dnom-t2a.tfm) \
tex(Erewhon-Regular-dnom-t2b.tfm) \
tex(Erewhon-Regular-dnom-t2c.tfm) \
tex(Erewhon-Regular-inf-ly1.tfm) \
tex(Erewhon-Regular-inf-ot1.tfm) \
tex(Erewhon-Regular-inf-t1--base.tfm) \
tex(Erewhon-Regular-inf-t1.tfm) \
tex(Erewhon-Regular-inf-t1.vf) \
tex(Erewhon-Regular-inf-t2a.tfm) \
tex(Erewhon-Regular-inf-t2b.tfm) \
tex(Erewhon-Regular-inf-t2c.tfm) \
tex(Erewhon-Regular-lf-ly1.tfm) \
tex(Erewhon-Regular-lf-ot1.tfm) \
tex(Erewhon-Regular-lf-sc-ly1--base.tfm) \
tex(Erewhon-Regular-lf-sc-ly1.tfm) \
tex(Erewhon-Regular-lf-sc-ly1.vf) \
tex(Erewhon-Regular-lf-sc-ot1--base.tfm) \
tex(Erewhon-Regular-lf-sc-ot1.tfm) \
tex(Erewhon-Regular-lf-sc-ot1.vf) \
tex(Erewhon-Regular-lf-sc-t1--base.tfm) \
tex(Erewhon-Regular-lf-sc-t1.tfm) \
tex(Erewhon-Regular-lf-sc-t1.vf) \
tex(Erewhon-Regular-lf-sc-t2a--base.tfm) \
tex(Erewhon-Regular-lf-sc-t2a.tfm) \
tex(Erewhon-Regular-lf-sc-t2a.vf) \
tex(Erewhon-Regular-lf-sc-t2b--base.tfm) \
tex(Erewhon-Regular-lf-sc-t2b.tfm) \
tex(Erewhon-Regular-lf-sc-t2b.vf) \
tex(Erewhon-Regular-lf-sc-t2c--base.tfm) \
tex(Erewhon-Regular-lf-sc-t2c.tfm) \
tex(Erewhon-Regular-lf-sc-t2c.vf) \
tex(Erewhon-Regular-lf-t1--base.tfm) \
tex(Erewhon-Regular-lf-t1.tfm) \
tex(Erewhon-Regular-lf-t1.vf) \
tex(Erewhon-Regular-lf-t2a.tfm) \
tex(Erewhon-Regular-lf-t2b.tfm) \
tex(Erewhon-Regular-lf-t2c.tfm) \
tex(Erewhon-Regular-lf-ts1--base.tfm) \
tex(Erewhon-Regular-lf-ts1.tfm) \
tex(Erewhon-Regular-lf-ts1.vf) \
tex(Erewhon-Regular-numr-ly1.tfm) \
tex(Erewhon-Regular-numr-ot1.tfm) \
tex(Erewhon-Regular-numr-t1--base.tfm) \
tex(Erewhon-Regular-numr-t1.tfm) \
tex(Erewhon-Regular-numr-t1.vf) \
tex(Erewhon-Regular-numr-t2a.tfm) \
tex(Erewhon-Regular-numr-t2b.tfm) \
tex(Erewhon-Regular-numr-t2c.tfm) \
tex(Erewhon-Regular-osf-ly1.tfm) \
tex(Erewhon-Regular-osf-ot1.tfm) \
tex(Erewhon-Regular-osf-sc-ly1--base.tfm) \
tex(Erewhon-Regular-osf-sc-ly1.tfm) \
tex(Erewhon-Regular-osf-sc-ly1.vf) \
tex(Erewhon-Regular-osf-sc-ot1--base.tfm) \
tex(Erewhon-Regular-osf-sc-ot1.tfm) \
tex(Erewhon-Regular-osf-sc-ot1.vf) \
tex(Erewhon-Regular-osf-sc-t1--base.tfm) \
tex(Erewhon-Regular-osf-sc-t1.tfm) \
tex(Erewhon-Regular-osf-sc-t1.vf) \
tex(Erewhon-Regular-osf-sc-t2a--base.tfm) \
tex(Erewhon-Regular-osf-sc-t2a.tfm) \
tex(Erewhon-Regular-osf-sc-t2a.vf) \
tex(Erewhon-Regular-osf-sc-t2b--base.tfm) \
tex(Erewhon-Regular-osf-sc-t2b.tfm) \
tex(Erewhon-Regular-osf-sc-t2b.vf) \
tex(Erewhon-Regular-osf-sc-t2c--base.tfm) \
tex(Erewhon-Regular-osf-sc-t2c.tfm) \
tex(Erewhon-Regular-osf-sc-t2c.vf) \
tex(Erewhon-Regular-osf-t1--base.tfm) \
tex(Erewhon-Regular-osf-t1.tfm) \
tex(Erewhon-Regular-osf-t1.vf) \
tex(Erewhon-Regular-osf-t2a.tfm) \
tex(Erewhon-Regular-osf-t2b.tfm) \
tex(Erewhon-Regular-osf-t2c.tfm) \
tex(Erewhon-Regular-osf-ts1--base.tfm) \
tex(Erewhon-Regular-osf-ts1.tfm) \
tex(Erewhon-Regular-osf-ts1.vf) \
tex(Erewhon-Regular-sup-ly1.tfm) \
tex(Erewhon-Regular-sup-ot1.tfm) \
tex(Erewhon-Regular-sup-t1--base.tfm) \
tex(Erewhon-Regular-sup-t1.tfm) \
tex(Erewhon-Regular-sup-t1.vf) \
tex(Erewhon-Regular-sup-t2a.tfm) \
tex(Erewhon-Regular-sup-t2b.tfm) \
tex(Erewhon-Regular-sup-t2c.tfm) \
tex(Erewhon-Regular-tlf-ly1.tfm) \
tex(Erewhon-Regular-tlf-ot1.tfm) \
tex(Erewhon-Regular-tlf-ot2.tfm) \
tex(Erewhon-Regular-tlf-sc-ly1--base.tfm) \
tex(Erewhon-Regular-tlf-sc-ly1.tfm) \
tex(Erewhon-Regular-tlf-sc-ly1.vf) \
tex(Erewhon-Regular-tlf-sc-ot1--base.tfm) \
tex(Erewhon-Regular-tlf-sc-ot1.tfm) \
tex(Erewhon-Regular-tlf-sc-ot1.vf) \
tex(Erewhon-Regular-tlf-sc-t1--base.tfm) \
tex(Erewhon-Regular-tlf-sc-t1.tfm) \
tex(Erewhon-Regular-tlf-sc-t1.vf) \
tex(Erewhon-Regular-tlf-sc-t2a--base.tfm) \
tex(Erewhon-Regular-tlf-sc-t2a.tfm) \
tex(Erewhon-Regular-tlf-sc-t2a.vf) \
tex(Erewhon-Regular-tlf-sc-t2b--base.tfm) \
tex(Erewhon-Regular-tlf-sc-t2b.tfm) \
tex(Erewhon-Regular-tlf-sc-t2b.vf) \
tex(Erewhon-Regular-tlf-sc-t2c--base.tfm) \
tex(Erewhon-Regular-tlf-sc-t2c.tfm) \
tex(Erewhon-Regular-tlf-sc-t2c.vf) \
tex(Erewhon-Regular-tlf-t1--base.tfm) \
tex(Erewhon-Regular-tlf-t1.tfm) \
tex(Erewhon-Regular-tlf-t1.vf) \
tex(Erewhon-Regular-tlf-t2a.tfm) \
tex(Erewhon-Regular-tlf-t2b.tfm) \
tex(Erewhon-Regular-tlf-t2c.tfm) \
tex(Erewhon-Regular-tlf-ts1--base.tfm) \
tex(Erewhon-Regular-tlf-ts1.tfm) \
tex(Erewhon-Regular-tlf-ts1.vf) \
tex(Erewhon-Regular-tosf-ly1.tfm) \
tex(Erewhon-Regular-tosf-ot1.tfm) \
tex(Erewhon-Regular-tosf-sc-ly1--base.tfm) \
tex(Erewhon-Regular-tosf-sc-ly1.tfm) \
tex(Erewhon-Regular-tosf-sc-ly1.vf) \
tex(Erewhon-Regular-tosf-sc-ot1--base.tfm) \
tex(Erewhon-Regular-tosf-sc-ot1.tfm) \
tex(Erewhon-Regular-tosf-sc-ot1.vf) \
tex(Erewhon-Regular-tosf-sc-t1--base.tfm) \
tex(Erewhon-Regular-tosf-sc-t1.tfm) \
tex(Erewhon-Regular-tosf-sc-t1.vf) \
tex(Erewhon-Regular-tosf-sc-t2a--base.tfm) \
tex(Erewhon-Regular-tosf-sc-t2a.tfm) \
tex(Erewhon-Regular-tosf-sc-t2a.vf) \
tex(Erewhon-Regular-tosf-sc-t2b--base.tfm) \
tex(Erewhon-Regular-tosf-sc-t2b.tfm) \
tex(Erewhon-Regular-tosf-sc-t2b.vf) \
tex(Erewhon-Regular-tosf-sc-t2c--base.tfm) \
tex(Erewhon-Regular-tosf-sc-t2c.tfm) \
tex(Erewhon-Regular-tosf-sc-t2c.vf) \
tex(Erewhon-Regular-tosf-t1--base.tfm) \
tex(Erewhon-Regular-tosf-t1.tfm) \
tex(Erewhon-Regular-tosf-t1.vf) \
tex(Erewhon-Regular-tosf-t2a.tfm) \
tex(Erewhon-Regular-tosf-t2b.tfm) \
tex(Erewhon-Regular-tosf-t2c.tfm) \
tex(Erewhon-Regular-tosf-ts1--base.tfm) \
tex(Erewhon-Regular-tosf-ts1.tfm) \
tex(Erewhon-Regular-tosf-ts1.vf) \
tex(Erewhon-RegularSlanted-dnom-ly1.tfm) \
tex(Erewhon-RegularSlanted-dnom-ot1.tfm) \
tex(Erewhon-RegularSlanted-dnom-t1--base.tfm) \
tex(Erewhon-RegularSlanted-dnom-t1.tfm) \
tex(Erewhon-RegularSlanted-dnom-t1.vf) \
tex(Erewhon-RegularSlanted-dnom-t2a.tfm) \
tex(Erewhon-RegularSlanted-dnom-t2b.tfm) \
tex(Erewhon-RegularSlanted-dnom-t2c.tfm) \
tex(Erewhon-RegularSlanted-inf-ly1.tfm) \
tex(Erewhon-RegularSlanted-inf-ot1.tfm) \
tex(Erewhon-RegularSlanted-inf-t1--base.tfm) \
tex(Erewhon-RegularSlanted-inf-t1.tfm) \
tex(Erewhon-RegularSlanted-inf-t1.vf) \
tex(Erewhon-RegularSlanted-inf-t2a.tfm) \
tex(Erewhon-RegularSlanted-inf-t2b.tfm) \
tex(Erewhon-RegularSlanted-inf-t2c.tfm) \
tex(Erewhon-RegularSlanted-lf-ly1.tfm) \
tex(Erewhon-RegularSlanted-lf-ot1.tfm) \
tex(Erewhon-RegularSlanted-lf-sc-ly1--base.tfm) \
tex(Erewhon-RegularSlanted-lf-sc-ly1.tfm) \
tex(Erewhon-RegularSlanted-lf-sc-ly1.vf) \
tex(Erewhon-RegularSlanted-lf-sc-ot1--base.tfm) \
tex(Erewhon-RegularSlanted-lf-sc-ot1.tfm) \
tex(Erewhon-RegularSlanted-lf-sc-ot1.vf) \
tex(Erewhon-RegularSlanted-lf-sc-t1--base.tfm) \
tex(Erewhon-RegularSlanted-lf-sc-t1.tfm) \
tex(Erewhon-RegularSlanted-lf-sc-t1.vf) \
tex(Erewhon-RegularSlanted-lf-sc-t2a--base.tfm) \
tex(Erewhon-RegularSlanted-lf-sc-t2a.tfm) \
tex(Erewhon-RegularSlanted-lf-sc-t2a.vf) \
tex(Erewhon-RegularSlanted-lf-sc-t2b--base.tfm) \
tex(Erewhon-RegularSlanted-lf-sc-t2b.tfm) \
tex(Erewhon-RegularSlanted-lf-sc-t2b.vf) \
tex(Erewhon-RegularSlanted-lf-sc-t2c--base.tfm) \
tex(Erewhon-RegularSlanted-lf-sc-t2c.tfm) \
tex(Erewhon-RegularSlanted-lf-sc-t2c.vf) \
tex(Erewhon-RegularSlanted-lf-t1--base.tfm) \
tex(Erewhon-RegularSlanted-lf-t1.tfm) \
tex(Erewhon-RegularSlanted-lf-t1.vf) \
tex(Erewhon-RegularSlanted-lf-t2a.tfm) \
tex(Erewhon-RegularSlanted-lf-t2b.tfm) \
tex(Erewhon-RegularSlanted-lf-t2c.tfm) \
tex(Erewhon-RegularSlanted-lf-ts1--base.tfm) \
tex(Erewhon-RegularSlanted-lf-ts1.tfm) \
tex(Erewhon-RegularSlanted-lf-ts1.vf) \
tex(Erewhon-RegularSlanted-numr-ly1.tfm) \
tex(Erewhon-RegularSlanted-numr-ot1.tfm) \
tex(Erewhon-RegularSlanted-numr-t1--base.tfm) \
tex(Erewhon-RegularSlanted-numr-t1.tfm) \
tex(Erewhon-RegularSlanted-numr-t1.vf) \
tex(Erewhon-RegularSlanted-numr-t2a.tfm) \
tex(Erewhon-RegularSlanted-numr-t2b.tfm) \
tex(Erewhon-RegularSlanted-numr-t2c.tfm) \
tex(Erewhon-RegularSlanted-osf-ly1.tfm) \
tex(Erewhon-RegularSlanted-osf-ot1.tfm) \
tex(Erewhon-RegularSlanted-osf-sc-ly1--base.tfm) \
tex(Erewhon-RegularSlanted-osf-sc-ly1.tfm) \
tex(Erewhon-RegularSlanted-osf-sc-ly1.vf) \
tex(Erewhon-RegularSlanted-osf-sc-ot1--base.tfm) \
tex(Erewhon-RegularSlanted-osf-sc-ot1.tfm) \
tex(Erewhon-RegularSlanted-osf-sc-ot1.vf) \
tex(Erewhon-RegularSlanted-osf-sc-t1--base.tfm) \
tex(Erewhon-RegularSlanted-osf-sc-t1.tfm) \
tex(Erewhon-RegularSlanted-osf-sc-t1.vf) \
tex(Erewhon-RegularSlanted-osf-sc-t2a--base.tfm) \
tex(Erewhon-RegularSlanted-osf-sc-t2a.tfm) \
tex(Erewhon-RegularSlanted-osf-sc-t2a.vf) \
tex(Erewhon-RegularSlanted-osf-sc-t2b--base.tfm) \
tex(Erewhon-RegularSlanted-osf-sc-t2b.tfm) \
tex(Erewhon-RegularSlanted-osf-sc-t2b.vf) \
tex(Erewhon-RegularSlanted-osf-sc-t2c--base.tfm) \
tex(Erewhon-RegularSlanted-osf-sc-t2c.tfm) \
tex(Erewhon-RegularSlanted-osf-sc-t2c.vf) \
tex(Erewhon-RegularSlanted-osf-t1--base.tfm) \
tex(Erewhon-RegularSlanted-osf-t1.tfm) \
tex(Erewhon-RegularSlanted-osf-t1.vf) \
tex(Erewhon-RegularSlanted-osf-t2a.tfm) \
tex(Erewhon-RegularSlanted-osf-t2b.tfm) \
tex(Erewhon-RegularSlanted-osf-t2c.tfm) \
tex(Erewhon-RegularSlanted-osf-ts1--base.tfm) \
tex(Erewhon-RegularSlanted-osf-ts1.tfm) \
tex(Erewhon-RegularSlanted-osf-ts1.vf) \
tex(Erewhon-RegularSlanted-sup-ly1.tfm) \
tex(Erewhon-RegularSlanted-sup-ot1.tfm) \
tex(Erewhon-RegularSlanted-sup-t1--base.tfm) \
tex(Erewhon-RegularSlanted-sup-t1.tfm) \
tex(Erewhon-RegularSlanted-sup-t1.vf) \
tex(Erewhon-RegularSlanted-sup-t2a.tfm) \
tex(Erewhon-RegularSlanted-sup-t2b.tfm) \
tex(Erewhon-RegularSlanted-sup-t2c.tfm) \
tex(Erewhon-RegularSlanted-tlf-ly1.tfm) \
tex(Erewhon-RegularSlanted-tlf-ot1.tfm) \
tex(Erewhon-RegularSlanted-tlf-ot2.tfm) \
tex(Erewhon-RegularSlanted-tlf-sc-ly1--base.tfm) \
tex(Erewhon-RegularSlanted-tlf-sc-ly1.tfm) \
tex(Erewhon-RegularSlanted-tlf-sc-ly1.vf) \
tex(Erewhon-RegularSlanted-tlf-sc-ot1--base.tfm) \
tex(Erewhon-RegularSlanted-tlf-sc-ot1.tfm) \
tex(Erewhon-RegularSlanted-tlf-sc-ot1.vf) \
tex(Erewhon-RegularSlanted-tlf-sc-t1--base.tfm) \
tex(Erewhon-RegularSlanted-tlf-sc-t1.tfm) \
tex(Erewhon-RegularSlanted-tlf-sc-t1.vf) \
tex(Erewhon-RegularSlanted-tlf-sc-t2a--base.tfm) \
tex(Erewhon-RegularSlanted-tlf-sc-t2a.tfm) \
tex(Erewhon-RegularSlanted-tlf-sc-t2a.vf) \
tex(Erewhon-RegularSlanted-tlf-sc-t2b--base.tfm) \
tex(Erewhon-RegularSlanted-tlf-sc-t2b.tfm) \
tex(Erewhon-RegularSlanted-tlf-sc-t2b.vf) \
tex(Erewhon-RegularSlanted-tlf-sc-t2c--base.tfm) \
tex(Erewhon-RegularSlanted-tlf-sc-t2c.tfm) \
tex(Erewhon-RegularSlanted-tlf-sc-t2c.vf) \
tex(Erewhon-RegularSlanted-tlf-t1--base.tfm) \
tex(Erewhon-RegularSlanted-tlf-t1.tfm) \
tex(Erewhon-RegularSlanted-tlf-t1.vf) \
tex(Erewhon-RegularSlanted-tlf-t2a.tfm) \
tex(Erewhon-RegularSlanted-tlf-t2b.tfm) \
tex(Erewhon-RegularSlanted-tlf-t2c.tfm) \
tex(Erewhon-RegularSlanted-tlf-ts1--base.tfm) \
tex(Erewhon-RegularSlanted-tlf-ts1.tfm) \
tex(Erewhon-RegularSlanted-tlf-ts1.vf) \
tex(Erewhon-RegularSlanted-tosf-ly1.tfm) \
tex(Erewhon-RegularSlanted-tosf-ot1.tfm) \
tex(Erewhon-RegularSlanted-tosf-sc-ly1--base.tfm) \
tex(Erewhon-RegularSlanted-tosf-sc-ly1.tfm) \
tex(Erewhon-RegularSlanted-tosf-sc-ly1.vf) \
tex(Erewhon-RegularSlanted-tosf-sc-ot1--base.tfm) \
tex(Erewhon-RegularSlanted-tosf-sc-ot1.tfm) \
tex(Erewhon-RegularSlanted-tosf-sc-ot1.vf) \
tex(Erewhon-RegularSlanted-tosf-sc-t1--base.tfm) \
tex(Erewhon-RegularSlanted-tosf-sc-t1.tfm) \
tex(Erewhon-RegularSlanted-tosf-sc-t1.vf) \
tex(Erewhon-RegularSlanted-tosf-sc-t2a--base.tfm) \
tex(Erewhon-RegularSlanted-tosf-sc-t2a.tfm) \
tex(Erewhon-RegularSlanted-tosf-sc-t2a.vf) \
tex(Erewhon-RegularSlanted-tosf-sc-t2b--base.tfm) \
tex(Erewhon-RegularSlanted-tosf-sc-t2b.tfm) \
tex(Erewhon-RegularSlanted-tosf-sc-t2b.vf) \
tex(Erewhon-RegularSlanted-tosf-sc-t2c--base.tfm) \
tex(Erewhon-RegularSlanted-tosf-sc-t2c.tfm) \
tex(Erewhon-RegularSlanted-tosf-sc-t2c.vf) \
tex(Erewhon-RegularSlanted-tosf-t1--base.tfm) \
tex(Erewhon-RegularSlanted-tosf-t1.tfm) \
tex(Erewhon-RegularSlanted-tosf-t1.vf) \
tex(Erewhon-RegularSlanted-tosf-t2a.tfm) \
tex(Erewhon-RegularSlanted-tosf-t2b.tfm) \
tex(Erewhon-RegularSlanted-tosf-t2c.tfm) \
tex(Erewhon-RegularSlanted-tosf-ts1--base.tfm) \
tex(Erewhon-RegularSlanted-tosf-ts1.tfm) \
tex(Erewhon-RegularSlanted-tosf-ts1.vf) \
tex(LY1erewhon-Dnom.fd) \
tex(LY1erewhon-Inf.fd) \
tex(LY1erewhon-LF.fd) \
tex(LY1erewhon-Numr.fd) \
tex(LY1erewhon-OsF.fd) \
tex(LY1erewhon-Sup.fd) \
tex(LY1erewhon-TLF.fd) \
tex(LY1erewhon-TOsF.fd) \
tex(OT1erewhon-Dnom.fd) \
tex(OT1erewhon-Inf.fd) \
tex(OT1erewhon-LF.fd) \
tex(OT1erewhon-Numr.fd) \
tex(OT1erewhon-OsF.fd) \
tex(OT1erewhon-Sup.fd) \
tex(OT1erewhon-TLF.fd) \
tex(OT1erewhon-TOsF.fd) \
tex(OT2erewhon-TLF.fd) \
tex(T1erewhon-Dnom.fd) \
tex(T1erewhon-Inf.fd) \
tex(T1erewhon-LF.fd) \
tex(T1erewhon-Numr.fd) \
tex(T1erewhon-OsF.fd) \
tex(T1erewhon-Sup.fd) \
tex(T1erewhon-TLF.fd) \
tex(T1erewhon-TOsF.fd) \
tex(T2Aerewhon-Dnom.fd) \
tex(T2Aerewhon-Inf.fd) \
tex(T2Aerewhon-LF.fd) \
tex(T2Aerewhon-Numr.fd) \
tex(T2Aerewhon-OsF.fd) \
tex(T2Aerewhon-Sup.fd) \
tex(T2Aerewhon-TLF.fd) \
tex(T2Aerewhon-TOsF.fd) \
tex(T2Berewhon-Dnom.fd) \
tex(T2Berewhon-Inf.fd) \
tex(T2Berewhon-LF.fd) \
tex(T2Berewhon-Numr.fd) \
tex(T2Berewhon-OsF.fd) \
tex(T2Berewhon-Sup.fd) \
tex(T2Berewhon-TLF.fd) \
tex(T2Berewhon-TOsF.fd) \
tex(T2Cerewhon-Dnom.fd) \
tex(T2Cerewhon-Inf.fd) \
tex(T2Cerewhon-LF.fd) \
tex(T2Cerewhon-Numr.fd) \
tex(T2Cerewhon-OsF.fd) \
tex(T2Cerewhon-Sup.fd) \
tex(T2Cerewhon-TLF.fd) \
tex(T2Cerewhon-TOsF.fd) \
tex(TS1erewhon-LF.fd) \
tex(TS1erewhon-OsF.fd) \
tex(TS1erewhon-TLF.fd) \
tex(TS1erewhon-TOsF.fd) \
tex(erewBMI.tfm) \
tex(erewBRM.tfm) \
tex(erewMI.tfm) \
tex(erewMR.tfm) \
tex(erewhon.map) \
tex(erewhon.sty) \
tex(erewhontlf-ot2.enc) \
tex(zut1_24phrd.enc) \
tex(zut1_25oktk.enc) \
tex(zut1_2j6fzl.enc) \
tex(zut1_2objs7.enc) \
tex(zut1_2qulls.enc) \
tex(zut1_2sunpf.enc) \
tex(zut1_36pkgq.enc) \
tex(zut1_3cc3dt.enc) \
tex(zut1_3ss64c.enc) \
tex(zut1_3xl2sl.enc) \
tex(zut1_4ap5la.enc) \
tex(zut1_4b4gx6.enc) \
tex(zut1_4chmhh.enc) \
tex(zut1_4csakl.enc) \
tex(zut1_4j4ux5.enc) \
tex(zut1_4qs3ad.enc) \
tex(zut1_53w3xs.enc) \
tex(zut1_546xgo.enc) \
tex(zut1_5iiyxb.enc) \
tex(zut1_5kulil.enc) \
tex(zut1_5swz3g.enc) \
tex(zut1_5ttobv.enc) \
tex(zut1_5uxmf6.enc) \
tex(zut1_5yzs2d.enc) \
tex(zut1_62fpar.enc) \
tex(zut1_6etwti.enc) \
tex(zut1_6qa5mv.enc) \
tex(zut1_6vm3oy.enc) \
tex(zut1_74cce3.enc) \
tex(zut1_75itn5.enc) \
tex(zut1_7ajsnx.enc) \
tex(zut1_7fkyik.enc) \
tex(zut1_7lebnu.enc) \
tex(zut1_7zfl2i.enc) \
tex(zut1_7zlfno.enc) \
tex(zut1_a27mgr.enc) \
tex(zut1_a4zpim.enc) \
tex(zut1_a7a6j7.enc) \
tex(zut1_acvwor.enc) \
tex(zut1_adckrx.enc) \
tex(zut1_ahzhtu.enc) \
tex(zut1_aj5cq6.enc) \
tex(zut1_aluvmp.enc) \
tex(zut1_amccbu.enc) \
tex(zut1_amjics.enc) \
tex(zut1_ax3b7f.enc) \
tex(zut1_azbcfh.enc) \
tex(zut1_bzygne.enc) \
tex(zut1_chb3ca.enc) \
tex(zut1_cqdyjt.enc) \
tex(zut1_cxj5nb.enc) \
tex(zut1_cyj7pa.enc) \
tex(zut1_d6afaq.enc) \
tex(zut1_dnhvn3.enc) \
tex(zut1_dpee64.enc) \
tex(zut1_dru2ao.enc) \
tex(zut1_dsvoru.enc) \
tex(zut1_dwvmxx.enc) \
tex(zut1_e4qrg7.enc) \
tex(zut1_egk5ui.enc) \
tex(zut1_el2ois.enc) \
tex(zut1_elnhz2.enc) \
tex(zut1_emma2w.enc) \
tex(zut1_etc5hm.enc) \
tex(zut1_fdnkjr.enc) \
tex(zut1_fec52x.enc) \
tex(zut1_fo623s.enc) \
tex(zut1_fojqdn.enc) \
tex(zut1_fomwqp.enc) \
tex(zut1_fp3vw2.enc) \
tex(zut1_fqlf3s.enc) \
tex(zut1_frcrrk.enc) \
tex(zut1_gm2ao2.enc) \
tex(zut1_gxqdb2.enc) \
tex(zut1_hap62j.enc) \
tex(zut1_haucyg.enc) \
tex(zut1_i3xnrn.enc) \
tex(zut1_i6k2d2.enc) \
tex(zut1_iibx3x.enc) \
tex(zut1_irfza6.enc) \
tex(zut1_isszvh.enc) \
tex(zut1_iszlz3.enc) \
tex(zut1_iuc2sz.enc) \
tex(zut1_ivciyi.enc) \
tex(zut1_j6ua73.enc) \
tex(zut1_jajasu.enc) \
tex(zut1_jbzr5t.enc) \
tex(zut1_jdnyy6.enc) \
tex(zut1_jmwubr.enc) \
tex(zut1_jofyrj.enc) \
tex(zut1_jsdebf.enc) \
tex(zut1_k4xd4x.enc) \
tex(zut1_kdakg5.enc) \
tex(zut1_kezgz7.enc) \
tex(zut1_kjdw2u.enc) \
tex(zut1_knq7bi.enc) \
tex(zut1_kpjvx5.enc) \
tex(zut1_kwgi2r.enc) \
tex(zut1_lefook.enc) \
tex(zut1_ljsdwq.enc) \
tex(zut1_lql6bl.enc) \
tex(zut1_lxr6iw.enc) \
tex(zut1_lzkx6u.enc) \
tex(zut1_m62wbz.enc) \
tex(zut1_mb7plm.enc) \
tex(zut1_mieo7u.enc) \
tex(zut1_mkqhoa.enc) \
tex(zut1_mmwqox.enc) \
tex(zut1_mno2dl.enc) \
tex(zut1_mqoft7.enc) \
tex(zut1_mqrime.enc) \
tex(zut1_msodj2.enc) \
tex(zut1_mzhi5i.enc) \
tex(zut1_ncwigg.enc) \
tex(zut1_ncyh3k.enc) \
tex(zut1_ndxvka.enc) \
tex(zut1_nhgbwl.enc) \
tex(zut1_nhu5qm.enc) \
tex(zut1_nlk3tk.enc) \
tex(zut1_nmevy6.enc) \
tex(zut1_nqkiey.enc) \
tex(zut1_nrup2h.enc) \
tex(zut1_ntuunb.enc) \
tex(zut1_nwll5a.enc) \
tex(zut1_oapbtr.enc) \
tex(zut1_odgoid.enc) \
tex(zut1_oed5ww.enc) \
tex(zut1_ojbxlk.enc) \
tex(zut1_p7xglw.enc) \
tex(zut1_peef5q.enc) \
tex(zut1_pj2kv6.enc) \
tex(zut1_pkbtg2.enc) \
tex(zut1_psbgvs.enc) \
tex(zut1_pux3en.enc) \
tex(zut1_qgiqhj.enc) \
tex(zut1_qhk7j3.enc) \
tex(zut1_qltwwe.enc) \
tex(zut1_qprerv.enc) \
tex(zut1_qqbsse.enc) \
tex(zut1_qvbgtd.enc) \
tex(zut1_r3uc5w.enc) \
tex(zut1_r74hdq.enc) \
tex(zut1_ra7von.enc) \
tex(zut1_rajiiv.enc) \
tex(zut1_rp5jpf.enc) \
tex(zut1_rsg4nr.enc) \
tex(zut1_s5ndkw.enc) \
tex(zut1_sim7pz.enc) \
tex(zut1_slg2ik.enc) \
tex(zut1_snzspn.enc) \
tex(zut1_sodton.enc) \
tex(zut1_t32gte.enc) \
tex(zut1_ta3xl2.enc) \
tex(zut1_thrva6.enc) \
tex(zut1_tmatie.enc) \
tex(zut1_tra2uf.enc) \
tex(zut1_uemunl.enc) \
tex(zut1_ufk2cy.enc) \
tex(zut1_uft3lp.enc) \
tex(zut1_ugisnr.enc) \
tex(zut1_uhamxn.enc) \
tex(zut1_uk5nxi.enc) \
tex(zut1_umzzxg.enc) \
tex(zut1_uuvzxd.enc) \
tex(zut1_v2pu2l.enc) \
tex(zut1_v3vc6e.enc) \
tex(zut1_vj42om.enc) \
tex(zut1_vtfujz.enc) \
tex(zut1_vz5ynf.enc) \
tex(zut1_w3f43e.enc) \
tex(zut1_wg4pgf.enc) \
tex(zut1_wrgbks.enc) \
tex(zut1_x3bhkk.enc) \
tex(zut1_x3yqgk.enc) \
tex(zut1_x6t4jr.enc) \
tex(zut1_xd5tcn.enc) \
tex(zut1_xhc3k4.enc) \
tex(zut1_xiqjov.enc) \
tex(zut1_xlud6l.enc) \
tex(zut1_xmqdd4.enc) \
tex(zut1_xsflzz.enc) \
tex(zut1_y5vzao.enc) \
tex(zut1_yjdtdu.enc) \
tex(zut1_yx3dqr.enc) \
tex(zut1_zc3ibv.enc) \
tex(zut1_zhgadb.enc) \
tex(zut1_zkbe5o.enc) \
tex(zut1_zlg4j6.enc) \
tex(zut1_zoqj2o.enc) \
tex(zut1_zt54pz.enc) \
tex(zut1_zx32l7.enc) \
texlive-erewhon"

RDEPENDS:${PN} += "/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex(etoolbox.sty) \
tex(fontaxes.sty) \
tex(fontenc.sty) \
tex(ifthen.sty) \
tex(mweights.sty) \
tex(scalefnt.sty) \
tex(textcomp.sty) \
tex(updmap.cfg) \
tex(xkeyval.sty) \
tex(xstring.sty) \
texlive \
texlive-erewhon-fonts \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
