SUMMARY = "Utilities for working with libt3key terminal descriptions"
DESCRIPTION = "libt3key is library that provides a database of mappings from escape \
sequences as generated by different consoles and terminals or \
emulators, to key symbols. \
 \
This subpackage contains the t3learnkeys and t3keyc programs."
LICENSE = "GPL-3.0-only"

PV = "0.2.10"

RPM_NAME = "libt3key-utils-0.2.10-1.15.aarch64.rpm"
RPM_HASH = "7f69f4cd4380a9c9f0ab565196b5c6363878baa6a2439bd54de2a4f989db986b1524e082dda5a0880065091325b733d199100e63be8412b0424a771e3f2d08d5"

RPROVIDES:${PN} += "libt3key-utils"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1 \
libc.so.6 \
libt3config.so.0 \
libtinfo.so.6 \
libxcb.so.1"

inherit rpm
