SUMMARY = "Utilities for working with libt3key terminal descriptions"
DESCRIPTION = "libt3key is library that provides a database of mappings from escape \
sequences as generated by different consoles and terminals or \
emulators, to key symbols. \
 \
This subpackage contains the t3learnkeys and t3keyc programs."
LICENSE = "GPL-3.0-only"

PV = "0.2.10"

RPM_NAME = "libt3key-utils-0.2.10-1.14.aarch64.rpm"
RPM_HASH = "f269c11a53a8d160beb5c90f78a8917d0f4ac5e7083bef40d70e4c5684f9735e0a68602fa3408c5e33573c678c38f13d742471099102e34e5152931202459e40"

RPROVIDES:${PN} += "libt3key-utils \
libt3key-utils(aarch-64)"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1()(64bit) \
ld-linux-aarch64.so.1(GLIBC_2.17)(64bit) \
libc.so.6(GLIBC_2.34)(64bit) \
libt3config.so.0()(64bit) \
libtinfo.so.6()(64bit) \
libtinfo.so.6(NCURSES6_TINFO_5.0.19991023)(64bit) \
libxcb.so.1()(64bit)"

inherit rpm
