SUMMARY = "DSP infinite impulse response realtime C++ filter library"
DESCRIPTION = " \
An infinite impulse response (IIR) filter library for Linux, Mac OSX and Windows \
which implements Butterworth, RBJ, Chebychev filters and can easily import coefficients generated by Python (scipy). \
The filter processes the data sample by sample for realtime processing. \
It uses templates to allocate the required memory so that it can run without any malloc / new commands. \
Memory is allocated at compile time so that there is never the risk of memory leaks. \
All realtime filter code is in the header files which guarantees efficient integration into the main program \
and the compiler can optimise both filter code and main program at the same time."
LICENSE = "MIT"

PV = "1.9.4"

RPM_NAME = "libiir-devel-1.9.4-1.3.aarch64.rpm"
RPM_HASH = "375f9ac0a50b7295e3b952b768513fd3ec36d9de2f947807849111ec0e146427a6f1e350932a61ab92c3806592c95597ab6025a6690e8936cd7bb24007596755"

RPROVIDES:${PN} += "libiir-devel \
libiir-devel(aarch-64) \
pkgconfig(iir)"

RDEPENDS:${PN} += "/usr/bin/pkg-config \
libiir1"

inherit rpm
