SUMMARY = "DSP infinite impulse response realtime C++ filter library"
DESCRIPTION = " \
An infinite impulse response (IIR) filter library for Linux, Mac OSX and Windows \
which implements Butterworth, RBJ, Chebychev filters and can easily import coefficients generated by Python (scipy). \
The filter processes the data sample by sample for realtime processing. \
It uses templates to allocate the required memory so that it can run without any malloc / new commands. \
Memory is allocated at compile time so that there is never the risk of memory leaks. \
All realtime filter code is in the header files which guarantees efficient integration into the main program \
and the compiler can optimise both filter code and main program at the same time."
LICENSE = "MIT"

PV = "1.9.4"

RPM_NAME = "libiir-devel-1.9.4-1.4.aarch64.rpm"
RPM_HASH = "c5e2e2b2cce4b6994c28fc64ff72ddd9cac4603840309f8f167d840eb75cd422a022b0fbb6602e54c36d7f6f3897cdad70d3b6cc2cd8e9dbdd1ccf89a3b4d81d"

RPROVIDES:${PN} += "libiir-devel \
pkgconfig-iir"

RDEPENDS:${PN} += "/usr/bin/pkg-config \
libiir1"

inherit rpm
