SUMMARY = "Kerkis (Greek) font family"
DESCRIPTION = "Sans-serif Greek fonts to match the URW Bookman set (which are \
distributed with Kerkis). The Kerkis font set has some support \
for mathematics as well as other glyphs missing from the base \
URW Bookman fonts. Macros are provided to use the fonts in OT1, \
T1 (only NG/ng glyphs missing) and LGR encodings, as well as in \
mathematics; small caps and old-style number glyphs are also \
available. The philosophy, and the design process, of the \
Kerkis fonts is discussed in a paper in TUGboat 23(3/4), 2002."
LICENSE = "LPPL-1.0"

PV = "2023.209.1.11svn56271"

RPM_NAME = "texlive-kerkis-2023.209.1.11svn56271-56.1.noarch.rpm"
RPM_HASH = "4c503cf49171ef97e4433576fa86d838c6a76fbee5174fb23e8b0fb58f6f86e8cd4e785ec4f3151b0d47c9e865cdb9f350212e8cc4d47f9edd5111aed8fe04d6"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-ek8a.tfm \
tex-ek8a.vf \
tex-ek8r.tfm \
tex-ekb8a.tfm \
tex-ekb8a.vf \
tex-ekb8r.tfm \
tex-ekbi8a.tfm \
tex-ekbi8a.vf \
tex-ekbi8r.tfm \
tex-ekbo8a.tfm \
tex-ekbo8a.vf \
tex-ekbo8r.tfm \
tex-ekbsc8a.tfm \
tex-ekbsc8a.vf \
tex-ekbsc8r.tfm \
tex-ekbsco8a.tfm \
tex-ekbsco8a.vf \
tex-ekbsco8r.tfm \
tex-ekbui8a.tfm \
tex-ekbui8a.vf \
tex-ekbui8r.tfm \
tex-ekcal8a.tfm \
tex-ekcal8a.vf \
tex-ekcal8r.tfm \
tex-eki8a.tfm \
tex-eki8a.vf \
tex-eki8r.tfm \
tex-eko8a.tfm \
tex-eko8a.vf \
tex-eko8r.tfm \
tex-eksb8a.tfm \
tex-eksb8a.vf \
tex-eksb8r.tfm \
tex-eksbi8a.tfm \
tex-eksbi8a.vf \
tex-eksbi8r.tfm \
tex-eksbo8a.tfm \
tex-eksbo8a.vf \
tex-eksbo8r.tfm \
tex-eksbui8a.tfm \
tex-eksbui8a.vf \
tex-eksbui8r.tfm \
tex-eksc8a.tfm \
tex-eksc8a.vf \
tex-eksc8r.tfm \
tex-eksco8a.tfm \
tex-eksco8a.vf \
tex-eksco8r.tfm \
tex-eksf8a.tfm \
tex-eksf8t.tfm \
tex-eksf8t.vf \
tex-eksfb8a.tfm \
tex-eksfb8t.tfm \
tex-eksfb8t.vf \
tex-eksfbi8a.tfm \
tex-eksfbi8t.tfm \
tex-eksfbi8t.vf \
tex-eksfi8a.tfm \
tex-eksfi8t.tfm \
tex-eksfi8t.vf \
tex-eksfsc8a.tfm \
tex-eksfsc8t.tfm \
tex-eksfsc8t.vf \
tex-ekui8a.tfm \
tex-ekui8a.vf \
tex-ekui8r.tfm \
tex-gk7a.tfm \
tex-gk7t.tfm \
tex-gk7t.vf \
tex-gkb7a.tfm \
tex-gkb7t.tfm \
tex-gkb7t.vf \
tex-gkbi7a.tfm \
tex-gkbi7t.tfm \
tex-gkbi7t.vf \
tex-gkbo7a.tfm \
tex-gkbo7t.tfm \
tex-gkbo7t.vf \
tex-gkbsc8a.tfm \
tex-gkbsc8a.vf \
tex-gkbsc8r.tfm \
tex-gkbsco8a.tfm \
tex-gkbsco8a.vf \
tex-gkbsco8r.tfm \
tex-gkbui7a.tfm \
tex-gkbui7t.tfm \
tex-gkbui7t.vf \
tex-gkcal7a.tfm \
tex-gkcal7t.tfm \
tex-gkcal7t.vf \
tex-gkerkis.enc \
tex-gkerkisc.enc \
tex-gki7a.tfm \
tex-gki7t.tfm \
tex-gki7t.vf \
tex-gko7a.tfm \
tex-gko7t.tfm \
tex-gko7t.vf \
tex-gksb7a.tfm \
tex-gksb7t.tfm \
tex-gksb7t.vf \
tex-gksbi7a.tfm \
tex-gksbi7t.tfm \
tex-gksbi7t.vf \
tex-gksbo7a.tfm \
tex-gksbo7t.tfm \
tex-gksbo7t.vf \
tex-gksbui7a.tfm \
tex-gksbui7t.tfm \
tex-gksbui7t.vf \
tex-gksc7a.tfm \
tex-gksc7t.tfm \
tex-gksc7t.vf \
tex-gksco7a.tfm \
tex-gksco7t.tfm \
tex-gksco7t.vf \
tex-gksf7a.tfm \
tex-gksf7t.tfm \
tex-gksf7t.vf \
tex-gksfb7a.tfm \
tex-gksfb7t.tfm \
tex-gksfb7t.vf \
tex-gksfbi7a.tfm \
tex-gksfbi7t.tfm \
tex-gksfbi7t.vf \
tex-gksfi7a.tfm \
tex-gksfi7t.tfm \
tex-gksfi7t.vf \
tex-gksfsc7a.tfm \
tex-gksfsc7t.tfm \
tex-gksfsc7t.vf \
tex-gkui7a.tfm \
tex-gkui7t.tfm \
tex-gkui7t.vf \
tex-gpkerkis.enc \
tex-gpkerkisc.enc \
tex-k8a.tfm \
tex-k8a.vf \
tex-k8r.tfm \
tex-kb8a.tfm \
tex-kb8a.vf \
tex-kb8r.tfm \
tex-kbi8a.tfm \
tex-kbi8a.vf \
tex-kbi8r.tfm \
tex-kbo8a.tfm \
tex-kbo8a.vf \
tex-kbo8r.tfm \
tex-kbsc8a.tfm \
tex-kbsc8a.vf \
tex-kbsc8r.tfm \
tex-kbsco8a.tfm \
tex-kbsco8a.vf \
tex-kbsco8r.tfm \
tex-kbui8a.tfm \
tex-kbui8a.vf \
tex-kbui8r.tfm \
tex-kcal8a.tfm \
tex-kcal8a.vf \
tex-kcal8r.tfm \
tex-kerkis.enc \
tex-kerkis.map \
tex-kerkis.sty \
tex-kerkisc.enc \
tex-kerkisec.enc \
tex-kerkisecsc.enc \
tex-ki8a.tfm \
tex-ki8a.vf \
tex-ki8r.tfm \
tex-kmath.enc \
tex-kmath.sty \
tex-kmath8a.tfm \
tex-kmath8a.vf \
tex-kmath8r.tfm \
tex-kmex.enc \
tex-kmsym.enc \
tex-ko8a.tfm \
tex-ko8a.vf \
tex-ko8r.tfm \
tex-ksb8a.tfm \
tex-ksb8a.vf \
tex-ksb8r.tfm \
tex-ksbi8a.tfm \
tex-ksbi8a.vf \
tex-ksbi8r.tfm \
tex-ksbo8a.tfm \
tex-ksbo8a.vf \
tex-ksbo8r.tfm \
tex-ksbui8a.tfm \
tex-ksbui8a.vf \
tex-ksbui8r.tfm \
tex-ksc8a.tfm \
tex-ksc8a.vf \
tex-ksc8r.tfm \
tex-ksco8a.tfm \
tex-ksco8a.vf \
tex-ksco8r.tfm \
tex-ksf8a.tfm \
tex-ksf8t.tfm \
tex-ksf8t.vf \
tex-ksfb8a.tfm \
tex-ksfb8t.tfm \
tex-ksfb8t.vf \
tex-ksfbi8a.tfm \
tex-ksfbi8t.tfm \
tex-ksfbi8t.vf \
tex-ksfi8a.tfm \
tex-ksfi8t.tfm \
tex-ksfi8t.vf \
tex-ksfsc8a.tfm \
tex-ksfsc8t.tfm \
tex-ksfsc8t.vf \
tex-ktsy8a.tfm \
tex-ktsy8a.vf \
tex-ktsy8r.tfm \
tex-kui8a.tfm \
tex-kui8a.vf \
tex-kui8r.tfm \
tex-lgrkfn.fd \
tex-lgrmak.fd \
tex-lgrmaksf.fd \
tex-omlmak.fd \
tex-omsmak.fd \
tex-ot1kfn.fd \
tex-ot1mak.fd \
tex-ot1maksf.fd \
tex-t1mak.fd \
tex-t1maksf.fd \
texlive-kerkis"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-txfonts.sty \
tex-updmap.cfg \
texlive \
texlive-filesystem \
texlive-kerkis-fonts \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
