SUMMARY = "Network Disk Archiver"
DESCRIPTION = "AMANDA, the Advanced Maryland Automatic Network Disk Archiver, is a backup \
solution that allows the IT administrator to set up a single master backup \
server to back up multiple hosts over network to tape drives/changers or \
disks or optical media. Amanda uses native utilities and formats (e.g. dump \
and/or GNU tar) and can back up a large number of servers and workstations \
running multiple versions of Linux or Unix."
LICENSE = "GPL-3.0-or-later"

PV = "3.5.4"

RPM_NAME = "amanda-3.5.4-1.1.aarch64.rpm"
RPM_HASH = "424d47a1840828567c88bdb596a5100db78a3c78eb11985d6405bb68286470f11502213debef2df679c014cdb4f044230db2289720213adcf498a355f0212cb4"

RPROVIDES:${PN} += "amanda \
config-amanda \
libApplication.so \
libArchive.so \
libBinary.so \
libCmdfile.so \
libCmdline.so \
libConfig.so \
libDebug.so \
libDevice.so \
libDisklist.so \
libFeature.so \
libHeader.so \
libLogfile.so \
libMainLoop.so \
libNDMP.so \
libTapelist.so \
libTests.so \
libUtil.so \
libXfer.so \
libXferServer.so \
libamanda-3.5.4.so \
libamandad-3.5.4.so \
libamar-3.5.4.so \
libamclient-3.5.4.so \
libamdevice-3.5.4.so \
libamglue-3.5.4.so \
libamserver-3.5.4.so \
libamxfer-3.5.4.so \
libndmjob-3.5.4.so \
libndmlib-3.5.4.so \
perl-Amanda--Amdump \
perl-Amanda--Amdump--Message \
perl-Amanda--Amflush \
perl-Amanda--Amflush--Message \
perl-Amanda--Amservice \
perl-Amanda--Application \
perl-Amanda--Application--Zfs \
perl-Amanda--Applicationc \
perl-Amanda--Archive \
perl-Amanda--Archive--Archive \
perl-Amanda--Archive--Attr \
perl-Amanda--Archive--File \
perl-Amanda--Archivec \
perl-Amanda--BigIntCompat \
perl-Amanda--Changer \
perl-Amanda--Changer--Config \
perl-Amanda--Changer--Error \
perl-Amanda--Changer--Message \
perl-Amanda--Changer--Reservation \
perl-Amanda--Changer--aggregate \
perl-Amanda--Changer--aggregate--Reservation \
perl-Amanda--Changer--disk \
perl-Amanda--Changer--disk--Reservation \
perl-Amanda--Changer--diskflat \
perl-Amanda--Changer--diskflat--Reservation \
perl-Amanda--Changer--multi \
perl-Amanda--Changer--multi--Reservation \
perl-Amanda--Changer--ndmp \
perl-Amanda--Changer--ndmp--Interface \
perl-Amanda--Changer--null \
perl-Amanda--Changer--null--Reservation \
perl-Amanda--Changer--rait \
perl-Amanda--Changer--rait--Reservation \
perl-Amanda--Changer--robot \
perl-Amanda--Changer--robot--Interface \
perl-Amanda--Changer--robot--Interface--MTX \
perl-Amanda--Changer--robot--Reservation \
perl-Amanda--Changer--single \
perl-Amanda--Changer--single--Reservation \
perl-Amanda--CheckDump \
perl-Amanda--CheckDump--Message \
perl-Amanda--Chunker--Controller \
perl-Amanda--Chunker--Protocol \
perl-Amanda--Chunker--Scribe \
perl-Amanda--Chunker--Scribe--Feedback \
perl-Amanda--Cleanup \
perl-Amanda--Cleanup--Message \
perl-Amanda--ClientService \
perl-Amanda--Cmdfile \
perl-Amanda--Cmdfile--Cmddata \
perl-Amanda--Cmdfile--Cmdfile \
perl-Amanda--Cmdfile--Message \
perl-Amanda--Cmdfilec \
perl-Amanda--Cmdline \
perl-Amanda--Cmdline--dumpspec-t \
perl-Amanda--Cmdlinec \
perl-Amanda--Config \
perl-Amanda--Config--FoldingHash \
perl-Amanda--Config--Message \
perl-Amanda--Configc \
perl-Amanda--Constants \
perl-Amanda--Curinfo \
perl-Amanda--Curinfo--History \
perl-Amanda--Curinfo--Info \
perl-Amanda--Curinfo--Message \
perl-Amanda--Curinfo--Perf \
perl-Amanda--Curinfo--Stats \
perl-Amanda--DB \
perl-Amanda--DB--Catalog \
perl-Amanda--DB--Message \
perl-Amanda--Debug \
perl-Amanda--Debugc \
perl-Amanda--Device \
perl-Amanda--Device--Device \
perl-Amanda--Device--DirectTCPConnection \
perl-Amanda--Device--Message \
perl-Amanda--Devicec \
perl-Amanda--Disklist \
perl-Amanda--Disklist--Disk \
perl-Amanda--Disklist--Host \
perl-Amanda--Disklist--Interface \
perl-Amanda--Disklist--Message \
perl-Amanda--Disklistc \
perl-Amanda--Extract \
perl-Amanda--Extract--Message \
perl-Amanda--Feature \
perl-Amanda--Feature--Set \
perl-Amanda--Featurec \
perl-Amanda--FetchDump \
perl-Amanda--FetchDump--Application \
perl-Amanda--FetchDump--ClientApplication \
perl-Amanda--FetchDump--Local \
perl-Amanda--FetchDump--Message \
perl-Amanda--Header \
perl-Amanda--Header--Header \
perl-Amanda--Header--HeaderXML \
perl-Amanda--Headerc \
perl-Amanda--Holding \
perl-Amanda--IPC--Binary \
perl-Amanda--IPC--Binary--Message \
perl-Amanda--IPC--Binaryc \
perl-Amanda--IPC--LineProtocol \
perl-Amanda--Index \
perl-Amanda--Index--Message \
perl-Amanda--Interactivity \
perl-Amanda--Interactivity--email \
perl-Amanda--Interactivity--stdin \
perl-Amanda--Interactivity--tty \
perl-Amanda--Interactivity--tty-email \
perl-Amanda--Label \
perl-Amanda--Label--Message \
perl-Amanda--Logfile \
perl-Amanda--Logfile--find-result-t \
perl-Amanda--Logfilec \
perl-Amanda--MainLoop \
perl-Amanda--MainLoop--Source \
perl-Amanda--MainLoopc \
perl-Amanda--Message \
perl-Amanda--NDMP \
perl-Amanda--NDMP--NDMPConnection \
perl-Amanda--NDMPc \
perl-Amanda--Paths \
perl-Amanda--Policy \
perl-Amanda--Process \
perl-Amanda--Process--Message \
perl-Amanda--Recovery \
perl-Amanda--Recovery--Clerk \
perl-Amanda--Recovery--Clerk--Feedback \
perl-Amanda--Recovery--Message \
perl-Amanda--Recovery--Planner \
perl-Amanda--Recovery--Planner--Plan \
perl-Amanda--Recovery--Scan \
perl-Amanda--Recovery--Scan--Config \
perl-Amanda--Report \
perl-Amanda--Report--Message \
perl-Amanda--Report--human \
perl-Amanda--Report--json \
perl-Amanda--Report--json-raw \
perl-Amanda--Report--postscript \
perl-Amanda--Report--xml \
perl-Amanda--Rest \
perl-Amanda--Rest--Amcheck \
perl-Amanda--Rest--Configs \
perl-Amanda--Rest--Dles \
perl-Amanda--Rest--Dumps \
perl-Amanda--Rest--Labels \
perl-Amanda--Rest--Report \
perl-Amanda--Rest--Runs \
perl-Amanda--Rest--Runs--FetchFeedback \
perl-Amanda--Rest--Services \
perl-Amanda--Rest--Status \
perl-Amanda--Rest--Storages \
perl-Amanda--Rest--Storages--Labels \
perl-Amanda--Rest--Version \
perl-Amanda--Restore \
perl-Amanda--Restore--Message \
perl-Amanda--ScanInventory \
perl-Amanda--ScanInventory--Config \
perl-Amanda--Script \
perl-Amanda--Script-App \
perl-Amanda--Service \
perl-Amanda--Service--Amidxtaped \
perl-Amanda--Service--Message \
perl-Amanda--Service--Restore \
perl-Amanda--Status \
perl-Amanda--Status--Message \
perl-Amanda--Storage \
perl-Amanda--Tapelist \
perl-Amanda--Tapelist--Message \
perl-Amanda--Tapelistc \
perl-Amanda--Taper--Controller \
perl-Amanda--Taper--Protocol \
perl-Amanda--Taper--Scan \
perl-Amanda--Taper--Scan--lexical \
perl-Amanda--Taper--Scan--oldest \
perl-Amanda--Taper--Scan--traditional \
perl-Amanda--Taper--Scribe \
perl-Amanda--Taper--Scribe--DevHandling \
perl-Amanda--Taper--Scribe--Feedback \
perl-Amanda--Taper--Worker \
perl-Amanda--Tests \
perl-Amanda--Testsc \
perl-Amanda--Util \
perl-Amanda--Util--file-lock \
perl-Amanda--Utilc \
perl-Amanda--Vault \
perl-Amanda--Vault--Message \
perl-Amanda--Xfer \
perl-Amanda--Xfer--Dest--Application \
perl-Amanda--Xfer--Dest--Buffer \
perl-Amanda--Xfer--Dest--Device \
perl-Amanda--Xfer--Dest--DirectTCPConnect \
perl-Amanda--Xfer--Dest--DirectTCPListen \
perl-Amanda--Xfer--Dest--Fd \
perl-Amanda--Xfer--Dest--Holding \
perl-Amanda--Xfer--Dest--Null \
perl-Amanda--Xfer--Dest--Taper \
perl-Amanda--Xfer--Dest--Taper--Cacher \
perl-Amanda--Xfer--Dest--Taper--DirectTCP \
perl-Amanda--Xfer--Dest--Taper--Splitter \
perl-Amanda--Xfer--Element \
perl-Amanda--Xfer--Element--Glue \
perl-Amanda--Xfer--Filter--Crc \
perl-Amanda--Xfer--Filter--Process \
perl-Amanda--Xfer--Filter--Xor \
perl-Amanda--Xfer--Msg \
perl-Amanda--Xfer--Source--Device \
perl-Amanda--Xfer--Source--DirectTCPConnect \
perl-Amanda--Xfer--Source--DirectTCPListen \
perl-Amanda--Xfer--Source--Fd \
perl-Amanda--Xfer--Source--File \
perl-Amanda--Xfer--Source--Holding \
perl-Amanda--Xfer--Source--Pattern \
perl-Amanda--Xfer--Source--Random \
perl-Amanda--Xfer--Source--Recovery \
perl-Amanda--Xfer--Source--ShmRing \
perl-Amanda--Xfer--Xfer \
perl-Amanda--XferServer \
perl-Amanda--XferServerc \
perl-Amanda--Xferc"

RDEPENDS:${PN} += "/usr/bin/bash \
/usr/bin/perl \
/usr/bin/sh \
/usr/bin/smbclient \
dump \
grep \
ld-linux-aarch64.so.1 \
libc.so.6 \
libcom-err.so.2 \
libcrypto.so.3 \
libcurl.so.4 \
libglib-2.0.so.0 \
libgobject-2.0.so.0 \
libgssapi-krb5.so.2 \
libgthread-2.0.so.0 \
libkrb5.so.3 \
libreadline.so.8 \
libssl.so.3 \
libtirpc.so.3 \
perl \
permissions \
shadow \
tar"

inherit rpm
