SUMMARY = "User Space Tools for Kernel Auditing"
DESCRIPTION = "The audit package contains the user space utilities for storing and \
processing the audit records generated by the audit subsystem in the \
Linux kernel."
LICENSE = "LGPL-2.1-or-later"

PV = "3.1.1"

RPM_NAME = "audit-3.1.1-1.1.aarch64.rpm"
RPM_HASH = "0e96b06d6f8e8e38ad1c3859b16a5cb6375972e166cb1f66eb7406378fde3a69e4943ae392d8972e225da2ee321a5e17a8213dff22df96e419376c2674fc97fa"

RPROVIDES:${PN} += "audit \
config-audit"

RDEPENDS:${PN} += "/usr/bin/sh \
audit-libs \
coreutils \
group-audit \
ld-linux-aarch64.so.1 \
libaudit.so.1 \
libauparse.so.0 \
libc.so.6 \
libcap-ng.so.0 \
libwrap.so.0"

inherit rpm
