SUMMARY = "Access to formulas in PDF files by assistive technologies"
DESCRIPTION = "PDF documents containing formulas generated by LaTeX are \
usually not accessible by assistive technologies for visually \
impaired people and people with special educational needs \
(i.e., by screen readers and braille displays). The \
axessibility package manages this issue, allowing to create a \
PDF document where the formulas are read by these assistive \
technologies, since it automatically generates hidden comments \
in the PDF document (by means of the /ActualText attribute \
and/or suitable tags) in correspondence to each formula."
LICENSE = "LPPL-1.0"

PV = "2023.209.3.0svn57105"

RPM_NAME = "texlive-axessibility-2023.209.3.0svn57105-54.1.noarch.rpm"
RPM_HASH = "c8a5b7c27f85e18acd3e5d833d8b1851e38ab7c4f2cf9c728cd4208dad392093f2391ee0c126c14d5efe7226d519d4d638a90b90f16936f506c7d8456f110e28"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-axessibility.sty \
texlive-axessibility"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-accsupp.sty \
tex-amsmath.sty \
tex-amssymb.sty \
tex-fontenc.sty \
tex-fontspec.sty \
tex-luacode.sty \
tex-tagpdf.sty \
tex-xstring.sty \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
