SUMMARY = "Ruby bindings for libprelude"
DESCRIPTION = "Ruby bindings for libprelude generated by SWIG."
LICENSE = "LGPL-2.1-only & LGPL-2.1-or-later"

PV = "5.2.0"

RPM_NAME = "ruby-libprelude-5.2.0-2.16.aarch64.rpm"
RPM_HASH = "b3e7369100536492db16ed07973f42a56ac4096bfaa67feffc23bb4492e1ae3652d5696831d486faa92eaa9237d11f60109ccb851b0184e528ce5abbd2ddf50e"

RPROVIDES:${PN} += "ruby-libprelude"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1 \
libc.so.6 \
libgcc-s.so.1 \
libprelude.so.28 \
libprelude28 \
libpreludecpp.so.12 \
libruby3.2.so.3.2 \
libstdc++.so.6 \
ruby"

inherit rpm
