SUMMARY = "Ruby bindings for libprelude"
DESCRIPTION = "Ruby bindings for libprelude generated by SWIG."
LICENSE = "LGPL-2.1-only & LGPL-2.1-or-later"

PV = "5.2.0"

RPM_NAME = "ruby-libprelude-5.2.0-2.14.aarch64.rpm"
RPM_HASH = "0e6dca1b06a4509d104c0b7cd6bcc8d890eaab2ca1a909e66f35ba9ff019c2a6c6db205b5cf9a990645715043e8622e7eff82bab58061e14ace728dfcbf882a0"

RPROVIDES:${PN} += "ruby-libprelude"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1 \
libc.so.6 \
libgcc-s.so.1 \
libprelude.so.28 \
libprelude28 \
libpreludecpp.so.12 \
libruby3.2.so.3.2 \
libstdc++.so.6 \
ruby"

inherit rpm
