SUMMARY = "A secure JavaScript and TypeScript runtime"
DESCRIPTION = "A JavaSript and TypeScript platform built on V8 \
 \
Deno has standard library and has features such as \
a linter, a language server protocol, a code formatter and \
a unit test runner. \
 \
Remote code is fetched and cached on first execution, and only \
updated with the --reload flag."
LICENSE = "MIT"

PV = "1.34.1"

RPM_NAME = "deno-1.34.1-1.1.aarch64.rpm"
RPM_HASH = "4c00708a895ef4a9e3d00f51c845963cf5b8ad40f916734ea4fae96547c2270d0d86aa49c5008f98d47546e80dafd55ba03fdd7374fbdec884825f2c8c4122ec"

RPROVIDES:${PN} += "bundled(rust-crate:Inflector) \
bundled(rust-crate:adler) \
bundled(rust-crate:aead) \
bundled(rust-crate:aes) \
bundled(rust-crate:aes-gcm) \
bundled(rust-crate:aes-kw) \
bundled(rust-crate:ahash) \
bundled(rust-crate:aho-corasick) \
bundled(rust-crate:alloc-no-stdlib) \
bundled(rust-crate:alloc-stdlib) \
bundled(rust-crate:anyhow) \
bundled(rust-crate:arrayvec) \
bundled(rust-crate:asn1-rs) \
bundled(rust-crate:asn1-rs-derive) \
bundled(rust-crate:asn1-rs-impl) \
bundled(rust-crate:ast_node) \
bundled(rust-crate:async-compression) \
bundled(rust-crate:async-trait) \
bundled(rust-crate:atty) \
bundled(rust-crate:auto_impl) \
bundled(rust-crate:autocfg) \
bundled(rust-crate:base16ct) \
bundled(rust-crate:base32) \
bundled(rust-crate:base64) \
bundled(rust-crate:base64-simd) \
bundled(rust-crate:base64ct) \
bundled(rust-crate:better_scoped_tls) \
bundled(rust-crate:bit-set) \
bundled(rust-crate:bit-vec) \
bundled(rust-crate:bitflags) \
bundled(rust-crate:block-buffer) \
bundled(rust-crate:block-modes) \
bundled(rust-crate:block-padding) \
bundled(rust-crate:brotli) \
bundled(rust-crate:brotli-decompressor) \
bundled(rust-crate:bumpalo) \
bundled(rust-crate:byteorder) \
bundled(rust-crate:bytes) \
bundled(rust-crate:cache_control) \
bundled(rust-crate:cbc) \
bundled(rust-crate:cc) \
bundled(rust-crate:cfg-if) \
bundled(rust-crate:chrono) \
bundled(rust-crate:cipher) \
bundled(rust-crate:clap) \
bundled(rust-crate:clap_complete) \
bundled(rust-crate:clap_complete_fig) \
bundled(rust-crate:clap_lex) \
bundled(rust-crate:console_static_text) \
bundled(rust-crate:const-oid) \
bundled(rust-crate:convert_case) \
bundled(rust-crate:cpufeatures) \
bundled(rust-crate:crc) \
bundled(rust-crate:crc-catalog) \
bundled(rust-crate:crc32fast) \
bundled(rust-crate:crossbeam-channel) \
bundled(rust-crate:crossbeam-utils) \
bundled(rust-crate:crypto-bigint) \
bundled(rust-crate:crypto-common) \
bundled(rust-crate:ctr) \
bundled(rust-crate:curve25519-dalek) \
bundled(rust-crate:dashmap) \
bundled(rust-crate:data-encoding) \
bundled(rust-crate:data-url) \
bundled(rust-crate:deno) \
bundled(rust-crate:deno_ast) \
bundled(rust-crate:deno_broadcast_channel) \
bundled(rust-crate:deno_cache) \
bundled(rust-crate:deno_console) \
bundled(rust-crate:deno_core) \
bundled(rust-crate:deno_crypto) \
bundled(rust-crate:deno_doc) \
bundled(rust-crate:deno_emit) \
bundled(rust-crate:deno_fetch) \
bundled(rust-crate:deno_ffi) \
bundled(rust-crate:deno_fs) \
bundled(rust-crate:deno_graph) \
bundled(rust-crate:deno_http) \
bundled(rust-crate:deno_io) \
bundled(rust-crate:deno_kv) \
bundled(rust-crate:deno_lint) \
bundled(rust-crate:deno_lockfile) \
bundled(rust-crate:deno_media_type) \
bundled(rust-crate:deno_napi) \
bundled(rust-crate:deno_net) \
bundled(rust-crate:deno_node) \
bundled(rust-crate:deno_npm) \
bundled(rust-crate:deno_ops) \
bundled(rust-crate:deno_runtime) \
bundled(rust-crate:deno_semver) \
bundled(rust-crate:deno_task_shell) \
bundled(rust-crate:deno_tls) \
bundled(rust-crate:deno_url) \
bundled(rust-crate:deno_web) \
bundled(rust-crate:deno_webidl) \
bundled(rust-crate:deno_websocket) \
bundled(rust-crate:deno_webstorage) \
bundled(rust-crate:der) \
bundled(rust-crate:der-parser) \
bundled(rust-crate:derive_more) \
bundled(rust-crate:digest) \
bundled(rust-crate:displaydoc) \
bundled(rust-crate:dissimilar) \
bundled(rust-crate:dlopen) \
bundled(rust-crate:dlopen_derive) \
bundled(rust-crate:dprint-core) \
bundled(rust-crate:dprint-plugin-json) \
bundled(rust-crate:dprint-plugin-markdown) \
bundled(rust-crate:dprint-plugin-typescript) \
bundled(rust-crate:dprint-swc-ext) \
bundled(rust-crate:dsa) \
bundled(rust-crate:dyn-clone) \
bundled(rust-crate:dynasm) \
bundled(rust-crate:dynasmrt) \
bundled(rust-crate:ecb) \
bundled(rust-crate:ecdsa) \
bundled(rust-crate:either) \
bundled(rust-crate:elliptic-curve) \
bundled(rust-crate:encoding_rs) \
bundled(rust-crate:endian-type) \
bundled(rust-crate:enum-as-inner) \
bundled(rust-crate:env_logger) \
bundled(rust-crate:escape8259) \
bundled(rust-crate:eszip) \
bundled(rust-crate:fallible-iterator) \
bundled(rust-crate:fallible-streaming-iterator) \
bundled(rust-crate:fancy-regex) \
bundled(rust-crate:fastrand) \
bundled(rust-crate:fastwebsockets) \
bundled(rust-crate:fd-lock) \
bundled(rust-crate:ff) \
bundled(rust-crate:filetime) \
bundled(rust-crate:fixedbitset) \
bundled(rust-crate:flate2) \
bundled(rust-crate:fly-accept-encoding) \
bundled(rust-crate:fnv) \
bundled(rust-crate:form_urlencoded) \
bundled(rust-crate:from_variant) \
bundled(rust-crate:fs3) \
bundled(rust-crate:fslock) \
bundled(rust-crate:futures) \
bundled(rust-crate:futures-channel) \
bundled(rust-crate:futures-core) \
bundled(rust-crate:futures-executor) \
bundled(rust-crate:futures-io) \
bundled(rust-crate:futures-macro) \
bundled(rust-crate:futures-sink) \
bundled(rust-crate:futures-task) \
bundled(rust-crate:futures-util) \
bundled(rust-crate:generic-array) \
bundled(rust-crate:getrandom) \
bundled(rust-crate:ghash) \
bundled(rust-crate:glibc_version) \
bundled(rust-crate:glob) \
bundled(rust-crate:group) \
bundled(rust-crate:h2) \
bundled(rust-crate:hashbrown) \
bundled(rust-crate:hashlink) \
bundled(rust-crate:heck) \
bundled(rust-crate:hex) \
bundled(rust-crate:hkdf) \
bundled(rust-crate:hmac) \
bundled(rust-crate:hostname) \
bundled(rust-crate:http) \
bundled(rust-crate:http-body) \
bundled(rust-crate:httparse) \
bundled(rust-crate:httpdate) \
bundled(rust-crate:humantime) \
bundled(rust-crate:hyper) \
bundled(rust-crate:hyper-rustls) \
bundled(rust-crate:idna) \
bundled(rust-crate:if_chain) \
bundled(rust-crate:import_map) \
bundled(rust-crate:indexmap) \
bundled(rust-crate:inotify) \
bundled(rust-crate:inotify-sys) \
bundled(rust-crate:inout) \
bundled(rust-crate:instant) \
bundled(rust-crate:io-lifetimes) \
bundled(rust-crate:ipnet) \
bundled(rust-crate:is-macro) \
bundled(rust-crate:is-terminal) \
bundled(rust-crate:itertools) \
bundled(rust-crate:itoa) \
bundled(rust-crate:jobserver) \
bundled(rust-crate:jsonc-parser) \
bundled(rust-crate:keccak) \
bundled(rust-crate:lazy-regex) \
bundled(rust-crate:lazy-regex-proc_macros) \
bundled(rust-crate:lazy_static) \
bundled(rust-crate:lexical) \
bundled(rust-crate:lexical-core) \
bundled(rust-crate:lexical-parse-float) \
bundled(rust-crate:lexical-parse-integer) \
bundled(rust-crate:lexical-util) \
bundled(rust-crate:lexical-write-float) \
bundled(rust-crate:lexical-write-integer) \
bundled(rust-crate:libc) \
bundled(rust-crate:libffi) \
bundled(rust-crate:libffi-sys) \
bundled(rust-crate:libloading) \
bundled(rust-crate:libm) \
bundled(rust-crate:libsqlite3-sys) \
bundled(rust-crate:libz-sys) \
bundled(rust-crate:linked-hash-map) \
bundled(rust-crate:linux-raw-sys) \
bundled(rust-crate:lock_api) \
bundled(rust-crate:log) \
bundled(rust-crate:lru-cache) \
bundled(rust-crate:lsp-types) \
bundled(rust-crate:match_cfg) \
bundled(rust-crate:matches) \
bundled(rust-crate:md-5) \
bundled(rust-crate:md4) \
bundled(rust-crate:memchr) \
bundled(rust-crate:memmap2) \
bundled(rust-crate:memmem) \
bundled(rust-crate:memoffset) \
bundled(rust-crate:mime) \
bundled(rust-crate:minimal-lexical) \
bundled(rust-crate:miniz_oxide) \
bundled(rust-crate:mio) \
bundled(rust-crate:monch) \
bundled(rust-crate:napi_sym) \
bundled(rust-crate:netif) \
bundled(rust-crate:new_debug_unreachable) \
bundled(rust-crate:nibble_vec) \
bundled(rust-crate:nix) \
bundled(rust-crate:nom) \
bundled(rust-crate:notify) \
bundled(rust-crate:num-bigint) \
bundled(rust-crate:num-bigint-dig) \
bundled(rust-crate:num-integer) \
bundled(rust-crate:num-iter) \
bundled(rust-crate:num-traits) \
bundled(rust-crate:num_cpus) \
bundled(rust-crate:oid-registry) \
bundled(rust-crate:once_cell) \
bundled(rust-crate:opaque-debug) \
bundled(rust-crate:openssl-probe) \
bundled(rust-crate:ordered-float) \
bundled(rust-crate:os_pipe) \
bundled(rust-crate:os_str_bytes) \
bundled(rust-crate:outref) \
bundled(rust-crate:p224) \
bundled(rust-crate:p256) \
bundled(rust-crate:p384) \
bundled(rust-crate:parking_lot) \
bundled(rust-crate:parking_lot_core) \
bundled(rust-crate:password-hash) \
bundled(rust-crate:path-clean) \
bundled(rust-crate:path-dedot) \
bundled(rust-crate:pathdiff) \
bundled(rust-crate:pbkdf2) \
bundled(rust-crate:pem-rfc7468) \
bundled(rust-crate:percent-encoding) \
bundled(rust-crate:petgraph) \
bundled(rust-crate:phf) \
bundled(rust-crate:phf_generator) \
bundled(rust-crate:phf_macros) \
bundled(rust-crate:phf_shared) \
bundled(rust-crate:pin-project) \
bundled(rust-crate:pin-project-internal) \
bundled(rust-crate:pin-project-lite) \
bundled(rust-crate:pin-utils) \
bundled(rust-crate:pkcs1) \
bundled(rust-crate:pkcs8) \
bundled(rust-crate:pkg-config) \
bundled(rust-crate:pmutil) \
bundled(rust-crate:polyval) \
bundled(rust-crate:ppv-lite86) \
bundled(rust-crate:precomputed-hash) \
bundled(rust-crate:primeorder) \
bundled(rust-crate:proc-macro-crate) \
bundled(rust-crate:proc-macro-error) \
bundled(rust-crate:proc-macro-error-attr) \
bundled(rust-crate:proc-macro-hack) \
bundled(rust-crate:proc-macro2) \
bundled(rust-crate:psm) \
bundled(rust-crate:pulldown-cmark) \
bundled(rust-crate:quick-error) \
bundled(rust-crate:quote) \
bundled(rust-crate:radix_fmt) \
bundled(rust-crate:radix_trie) \
bundled(rust-crate:rand) \
bundled(rust-crate:rand_chacha) \
bundled(rust-crate:rand_core) \
bundled(rust-crate:regex) \
bundled(rust-crate:regex-syntax) \
bundled(rust-crate:relative-path) \
bundled(rust-crate:reqwest) \
bundled(rust-crate:resolv-conf) \
bundled(rust-crate:rfc6979) \
bundled(rust-crate:ring) \
bundled(rust-crate:ripemd) \
bundled(rust-crate:rsa) \
bundled(rust-crate:rusqlite) \
bundled(rust-crate:rustc-hash) \
bundled(rust-crate:rustc_version) \
bundled(rust-crate:rusticata-macros) \
bundled(rust-crate:rustix) \
bundled(rust-crate:rustls) \
bundled(rust-crate:rustls-native-certs) \
bundled(rust-crate:rustls-pemfile) \
bundled(rust-crate:rustls-webpki) \
bundled(rust-crate:rustversion) \
bundled(rust-crate:rustyline) \
bundled(rust-crate:rustyline-derive) \
bundled(rust-crate:ryu) \
bundled(rust-crate:salsa20) \
bundled(rust-crate:same-file) \
bundled(rust-crate:scoped-tls) \
bundled(rust-crate:scopeguard) \
bundled(rust-crate:scrypt) \
bundled(rust-crate:sct) \
bundled(rust-crate:sec1) \
bundled(rust-crate:secp256k1) \
bundled(rust-crate:secp256k1-sys) \
bundled(rust-crate:semver) \
bundled(rust-crate:semver-parser) \
bundled(rust-crate:serde) \
bundled(rust-crate:serde-value) \
bundled(rust-crate:serde_bytes) \
bundled(rust-crate:serde_derive) \
bundled(rust-crate:serde_json) \
bundled(rust-crate:serde_repr) \
bundled(rust-crate:serde_urlencoded) \
bundled(rust-crate:serde_v8) \
bundled(rust-crate:sha-1) \
bundled(rust-crate:sha1) \
bundled(rust-crate:sha2) \
bundled(rust-crate:sha3) \
bundled(rust-crate:shell-escape) \
bundled(rust-crate:signal-hook-registry) \
bundled(rust-crate:signature) \
bundled(rust-crate:simdutf8) \
bundled(rust-crate:siphasher) \
bundled(rust-crate:slab) \
bundled(rust-crate:smallvec) \
bundled(rust-crate:smartstring) \
bundled(rust-crate:socket2) \
bundled(rust-crate:sourcemap) \
bundled(rust-crate:spin) \
bundled(rust-crate:spki) \
bundled(rust-crate:stable_deref_trait) \
bundled(rust-crate:stacker) \
bundled(rust-crate:static_assertions) \
bundled(rust-crate:string_cache) \
bundled(rust-crate:string_cache_codegen) \
bundled(rust-crate:string_enum) \
bundled(rust-crate:strsim) \
bundled(rust-crate:subtle) \
bundled(rust-crate:swc_atoms) \
bundled(rust-crate:swc_bundler) \
bundled(rust-crate:swc_common) \
bundled(rust-crate:swc_config) \
bundled(rust-crate:swc_config_macro) \
bundled(rust-crate:swc_ecma_ast) \
bundled(rust-crate:swc_ecma_codegen) \
bundled(rust-crate:swc_ecma_codegen_macros) \
bundled(rust-crate:swc_ecma_dep_graph) \
bundled(rust-crate:swc_ecma_loader) \
bundled(rust-crate:swc_ecma_parser) \
bundled(rust-crate:swc_ecma_transforms_base) \
bundled(rust-crate:swc_ecma_transforms_classes) \
bundled(rust-crate:swc_ecma_transforms_macros) \
bundled(rust-crate:swc_ecma_transforms_optimization) \
bundled(rust-crate:swc_ecma_transforms_proposal) \
bundled(rust-crate:swc_ecma_transforms_react) \
bundled(rust-crate:swc_ecma_transforms_typescript) \
bundled(rust-crate:swc_ecma_utils) \
bundled(rust-crate:swc_ecma_visit) \
bundled(rust-crate:swc_eq_ignore_macros) \
bundled(rust-crate:swc_fast_graph) \
bundled(rust-crate:swc_graph_analyzer) \
bundled(rust-crate:swc_macros_common) \
bundled(rust-crate:swc_visit) \
bundled(rust-crate:swc_visit_macros) \
bundled(rust-crate:syn) \
bundled(rust-crate:synstructure) \
bundled(rust-crate:tar) \
bundled(rust-crate:tempfile) \
bundled(rust-crate:termcolor) \
bundled(rust-crate:text-size) \
bundled(rust-crate:text_lines) \
bundled(rust-crate:thiserror) \
bundled(rust-crate:thiserror-impl) \
bundled(rust-crate:time) \
bundled(rust-crate:time-core) \
bundled(rust-crate:time-macros) \
bundled(rust-crate:tinyvec) \
bundled(rust-crate:tinyvec_macros) \
bundled(rust-crate:tokio) \
bundled(rust-crate:tokio-macros) \
bundled(rust-crate:tokio-rustls) \
bundled(rust-crate:tokio-socks) \
bundled(rust-crate:tokio-stream) \
bundled(rust-crate:tokio-util) \
bundled(rust-crate:toml_datetime) \
bundled(rust-crate:toml_edit) \
bundled(rust-crate:tower) \
bundled(rust-crate:tower-layer) \
bundled(rust-crate:tower-lsp) \
bundled(rust-crate:tower-lsp-macros) \
bundled(rust-crate:tower-service) \
bundled(rust-crate:tracing) \
bundled(rust-crate:tracing-attributes) \
bundled(rust-crate:tracing-core) \
bundled(rust-crate:triomphe) \
bundled(rust-crate:trust-dns-proto) \
bundled(rust-crate:trust-dns-resolver) \
bundled(rust-crate:try-lock) \
bundled(rust-crate:twox-hash) \
bundled(rust-crate:typed-arena) \
bundled(rust-crate:typenum) \
bundled(rust-crate:unic-char-property) \
bundled(rust-crate:unic-char-range) \
bundled(rust-crate:unic-common) \
bundled(rust-crate:unic-ucd-ident) \
bundled(rust-crate:unic-ucd-version) \
bundled(rust-crate:unicase) \
bundled(rust-crate:unicode-bidi) \
bundled(rust-crate:unicode-id) \
bundled(rust-crate:unicode-ident) \
bundled(rust-crate:unicode-normalization) \
bundled(rust-crate:unicode-segmentation) \
bundled(rust-crate:unicode-width) \
bundled(rust-crate:unicode-xid) \
bundled(rust-crate:universal-hash) \
bundled(rust-crate:untrusted) \
bundled(rust-crate:url) \
bundled(rust-crate:urlpattern) \
bundled(rust-crate:utf-8) \
bundled(rust-crate:utf8parse) \
bundled(rust-crate:uuid) \
bundled(rust-crate:v8) \
bundled(rust-crate:vcpkg) \
bundled(rust-crate:version_check) \
bundled(rust-crate:vsimd) \
bundled(rust-crate:vte) \
bundled(rust-crate:vte_generate_state_changes) \
bundled(rust-crate:walkdir) \
bundled(rust-crate:want) \
bundled(rust-crate:webpki) \
bundled(rust-crate:webpki-roots) \
bundled(rust-crate:which) \
bundled(rust-crate:windows-sys) \
bundled(rust-crate:windows-targets) \
bundled(rust-crate:winnow) \
bundled(rust-crate:x25519-dalek) \
bundled(rust-crate:x509-parser) \
bundled(rust-crate:xattr) \
bundled(rust-crate:zeroize) \
bundled(rust-crate:zeroize_derive) \
bundled(rust-crate:zstd) \
bundled(rust-crate:zstd-safe) \
bundled(rust-crate:zstd-sys) \
deno \
deno(aarch-64)"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1()(64bit) \
ld-linux-aarch64.so.1(GLIBC_2.17)(64bit) \
libc.so.6(GLIBC_2.34)(64bit) \
libgcc_s.so.1()(64bit) \
libgcc_s.so.1(GCC_3.0)(64bit) \
libgcc_s.so.1(GCC_3.3)(64bit) \
libgcc_s.so.1(GCC_4.2.0)(64bit) \
libm.so.6()(64bit) \
libm.so.6(GLIBC_2.17)(64bit) \
libm.so.6(GLIBC_2.27)(64bit) \
libm.so.6(GLIBC_2.29)(64bit)"

inherit rpm
