SUMMARY = "Support for using Libertinus fonts with LaTeX/pdfLaTeX"
DESCRIPTION = "This package provides support for use of Libertinus fonts with \
traditional processing engines (LaTeX with dvips or dvipdfmx, \
or pdfLaTeX)."
LICENSE = "GPL-2.0-or-later"

PV = "2023.201.svn64958"

RPM_NAME = "texlive-libertinus-type1-2023.201.svn64958-54.1.noarch.rpm"
RPM_HASH = "7142f22b114e88b162d4e60cf122229f222d76c51219a3c7f83f2711d856cdfde729d30aea2749c42a5ab3eaa34a30848f72ac1b2e61fe52384e3795fadb65b5"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-LGRLibertinusSans-LF.fd \
tex-LGRLibertinusSans-OsF.fd \
tex-LGRLibertinusSans-Sup.fd \
tex-LGRLibertinusSans-TLF.fd \
tex-LGRLibertinusSans-TOsF.fd \
tex-LGRLibertinusSerif-LF.fd \
tex-LGRLibertinusSerif-OsF.fd \
tex-LGRLibertinusSerif-Sup.fd \
tex-LGRLibertinusSerif-TLF.fd \
tex-LGRLibertinusSerif-TOsF.fd \
tex-LGRLibertinusSerifDisplay-LF.fd \
tex-LGRLibertinusSerifDisplay-OsF.fd \
tex-LGRLibertinusSerifDisplay-Sup.fd \
tex-LGRLibertinusSerifDisplay-TLF.fd \
tex-LGRLibertinusSerifDisplay-TOsF.fd \
tex-LGRLibertinusSerifInitials-TLF.fd \
tex-LY1LibertinusMono-TLF.fd \
tex-LY1LibertinusSans-LF.fd \
tex-LY1LibertinusSans-OsF.fd \
tex-LY1LibertinusSans-Sup.fd \
tex-LY1LibertinusSans-TLF.fd \
tex-LY1LibertinusSans-TOsF.fd \
tex-LY1LibertinusSerif-LF.fd \
tex-LY1LibertinusSerif-OsF.fd \
tex-LY1LibertinusSerif-Sup.fd \
tex-LY1LibertinusSerif-TLF.fd \
tex-LY1LibertinusSerif-TOsF.fd \
tex-LY1LibertinusSerifDisplay-LF.fd \
tex-LY1LibertinusSerifDisplay-OsF.fd \
tex-LY1LibertinusSerifDisplay-Sup.fd \
tex-LY1LibertinusSerifDisplay-TLF.fd \
tex-LY1LibertinusSerifDisplay-TOsF.fd \
tex-LY1LibertinusSerifInitials-TLF.fd \
tex-LibertinusMono-Bold-tlf-ly1--base.tfm \
tex-LibertinusMono-Bold-tlf-ly1.tfm \
tex-LibertinusMono-Bold-tlf-ly1.vf \
tex-LibertinusMono-Bold-tlf-ot1.tfm \
tex-LibertinusMono-Bold-tlf-t1--base.tfm \
tex-LibertinusMono-Bold-tlf-t1.tfm \
tex-LibertinusMono-Bold-tlf-t1.vf \
tex-LibertinusMono-Bold-tlf-ts1--base.tfm \
tex-LibertinusMono-Bold-tlf-ts1.tfm \
tex-LibertinusMono-Bold-tlf-ts1.vf \
tex-LibertinusMono-BoldOblique-tlf-ly1--base.tfm \
tex-LibertinusMono-BoldOblique-tlf-ly1.tfm \
tex-LibertinusMono-BoldOblique-tlf-ly1.vf \
tex-LibertinusMono-BoldOblique-tlf-ot1.tfm \
tex-LibertinusMono-BoldOblique-tlf-t1--base.tfm \
tex-LibertinusMono-BoldOblique-tlf-t1.tfm \
tex-LibertinusMono-BoldOblique-tlf-t1.vf \
tex-LibertinusMono-BoldOblique-tlf-ts1--base.tfm \
tex-LibertinusMono-BoldOblique-tlf-ts1.tfm \
tex-LibertinusMono-BoldOblique-tlf-ts1.vf \
tex-LibertinusMono-Oblique-tlf-ly1--base.tfm \
tex-LibertinusMono-Oblique-tlf-ly1.tfm \
tex-LibertinusMono-Oblique-tlf-ly1.vf \
tex-LibertinusMono-Oblique-tlf-ot1.tfm \
tex-LibertinusMono-Oblique-tlf-t1--base.tfm \
tex-LibertinusMono-Oblique-tlf-t1.tfm \
tex-LibertinusMono-Oblique-tlf-t1.vf \
tex-LibertinusMono-Oblique-tlf-ts1--base.tfm \
tex-LibertinusMono-Oblique-tlf-ts1.tfm \
tex-LibertinusMono-Oblique-tlf-ts1.vf \
tex-LibertinusMono-Regular-tlf-ly1--base.tfm \
tex-LibertinusMono-Regular-tlf-ly1.tfm \
tex-LibertinusMono-Regular-tlf-ly1.vf \
tex-LibertinusMono-Regular-tlf-ot1.tfm \
tex-LibertinusMono-Regular-tlf-t1--base.tfm \
tex-LibertinusMono-Regular-tlf-t1.tfm \
tex-LibertinusMono-Regular-tlf-t1.vf \
tex-LibertinusMono-Regular-tlf-ts1--base.tfm \
tex-LibertinusMono-Regular-tlf-ts1.tfm \
tex-LibertinusMono-Regular-tlf-ts1.vf \
tex-LibertinusSans-Bold-lf-lgr.tfm \
tex-LibertinusSans-Bold-lf-ly1.tfm \
tex-LibertinusSans-Bold-lf-ot1.tfm \
tex-LibertinusSans-Bold-lf-sc-lgr.tfm \
tex-LibertinusSans-Bold-lf-sc-ly1--base.tfm \
tex-LibertinusSans-Bold-lf-sc-ly1.tfm \
tex-LibertinusSans-Bold-lf-sc-ly1.vf \
tex-LibertinusSans-Bold-lf-sc-ot1--base.tfm \
tex-LibertinusSans-Bold-lf-sc-ot1.tfm \
tex-LibertinusSans-Bold-lf-sc-ot1.vf \
tex-LibertinusSans-Bold-lf-sc-t1--base.tfm \
tex-LibertinusSans-Bold-lf-sc-t1.tfm \
tex-LibertinusSans-Bold-lf-sc-t1.vf \
tex-LibertinusSans-Bold-lf-sc-t2a--base.tfm \
tex-LibertinusSans-Bold-lf-sc-t2a.tfm \
tex-LibertinusSans-Bold-lf-sc-t2a.vf \
tex-LibertinusSans-Bold-lf-sc-t2b--base.tfm \
tex-LibertinusSans-Bold-lf-sc-t2b.tfm \
tex-LibertinusSans-Bold-lf-sc-t2b.vf \
tex-LibertinusSans-Bold-lf-sc-t2c--base.tfm \
tex-LibertinusSans-Bold-lf-sc-t2c.tfm \
tex-LibertinusSans-Bold-lf-sc-t2c.vf \
tex-LibertinusSans-Bold-lf-t1--base.tfm \
tex-LibertinusSans-Bold-lf-t1.tfm \
tex-LibertinusSans-Bold-lf-t1.vf \
tex-LibertinusSans-Bold-lf-t2a.tfm \
tex-LibertinusSans-Bold-lf-t2b.tfm \
tex-LibertinusSans-Bold-lf-t2c.tfm \
tex-LibertinusSans-Bold-lf-ts1--base.tfm \
tex-LibertinusSans-Bold-lf-ts1.tfm \
tex-LibertinusSans-Bold-lf-ts1.vf \
tex-LibertinusSans-Bold-osf-lgr.tfm \
tex-LibertinusSans-Bold-osf-ly1.tfm \
tex-LibertinusSans-Bold-osf-ot1.tfm \
tex-LibertinusSans-Bold-osf-sc-lgr.tfm \
tex-LibertinusSans-Bold-osf-sc-ly1--base.tfm \
tex-LibertinusSans-Bold-osf-sc-ly1.tfm \
tex-LibertinusSans-Bold-osf-sc-ly1.vf \
tex-LibertinusSans-Bold-osf-sc-ot1--base.tfm \
tex-LibertinusSans-Bold-osf-sc-ot1.tfm \
tex-LibertinusSans-Bold-osf-sc-ot1.vf \
tex-LibertinusSans-Bold-osf-sc-t1--base.tfm \
tex-LibertinusSans-Bold-osf-sc-t1.tfm \
tex-LibertinusSans-Bold-osf-sc-t1.vf \
tex-LibertinusSans-Bold-osf-sc-t2a--base.tfm \
tex-LibertinusSans-Bold-osf-sc-t2a.tfm \
tex-LibertinusSans-Bold-osf-sc-t2a.vf \
tex-LibertinusSans-Bold-osf-sc-t2b--base.tfm \
tex-LibertinusSans-Bold-osf-sc-t2b.tfm \
tex-LibertinusSans-Bold-osf-sc-t2b.vf \
tex-LibertinusSans-Bold-osf-sc-t2c--base.tfm \
tex-LibertinusSans-Bold-osf-sc-t2c.tfm \
tex-LibertinusSans-Bold-osf-sc-t2c.vf \
tex-LibertinusSans-Bold-osf-t1--base.tfm \
tex-LibertinusSans-Bold-osf-t1.tfm \
tex-LibertinusSans-Bold-osf-t1.vf \
tex-LibertinusSans-Bold-osf-t2a.tfm \
tex-LibertinusSans-Bold-osf-t2b.tfm \
tex-LibertinusSans-Bold-osf-t2c.tfm \
tex-LibertinusSans-Bold-osf-ts1--base.tfm \
tex-LibertinusSans-Bold-osf-ts1.tfm \
tex-LibertinusSans-Bold-osf-ts1.vf \
tex-LibertinusSans-Bold-sup-lgr.tfm \
tex-LibertinusSans-Bold-sup-ly1.tfm \
tex-LibertinusSans-Bold-sup-ot1.tfm \
tex-LibertinusSans-Bold-sup-t1--base.tfm \
tex-LibertinusSans-Bold-sup-t1.tfm \
tex-LibertinusSans-Bold-sup-t1.vf \
tex-LibertinusSans-Bold-sup-t2a.tfm \
tex-LibertinusSans-Bold-sup-t2b.tfm \
tex-LibertinusSans-Bold-sup-t2c.tfm \
tex-LibertinusSans-Bold-tlf-lgr.tfm \
tex-LibertinusSans-Bold-tlf-ly1.tfm \
tex-LibertinusSans-Bold-tlf-ot1.tfm \
tex-LibertinusSans-Bold-tlf-sc-lgr.tfm \
tex-LibertinusSans-Bold-tlf-sc-ly1--base.tfm \
tex-LibertinusSans-Bold-tlf-sc-ly1.tfm \
tex-LibertinusSans-Bold-tlf-sc-ly1.vf \
tex-LibertinusSans-Bold-tlf-sc-ot1--base.tfm \
tex-LibertinusSans-Bold-tlf-sc-ot1.tfm \
tex-LibertinusSans-Bold-tlf-sc-ot1.vf \
tex-LibertinusSans-Bold-tlf-sc-t1--base.tfm \
tex-LibertinusSans-Bold-tlf-sc-t1.tfm \
tex-LibertinusSans-Bold-tlf-sc-t1.vf \
tex-LibertinusSans-Bold-tlf-sc-t2a--base.tfm \
tex-LibertinusSans-Bold-tlf-sc-t2a.tfm \
tex-LibertinusSans-Bold-tlf-sc-t2a.vf \
tex-LibertinusSans-Bold-tlf-sc-t2b--base.tfm \
tex-LibertinusSans-Bold-tlf-sc-t2b.tfm \
tex-LibertinusSans-Bold-tlf-sc-t2b.vf \
tex-LibertinusSans-Bold-tlf-sc-t2c--base.tfm \
tex-LibertinusSans-Bold-tlf-sc-t2c.tfm \
tex-LibertinusSans-Bold-tlf-sc-t2c.vf \
tex-LibertinusSans-Bold-tlf-t1--base.tfm \
tex-LibertinusSans-Bold-tlf-t1.tfm \
tex-LibertinusSans-Bold-tlf-t1.vf \
tex-LibertinusSans-Bold-tlf-t2a.tfm \
tex-LibertinusSans-Bold-tlf-t2b.tfm \
tex-LibertinusSans-Bold-tlf-t2c.tfm \
tex-LibertinusSans-Bold-tlf-ts1--base.tfm \
tex-LibertinusSans-Bold-tlf-ts1.tfm \
tex-LibertinusSans-Bold-tlf-ts1.vf \
tex-LibertinusSans-Bold-tosf-lgr.tfm \
tex-LibertinusSans-Bold-tosf-ly1.tfm \
tex-LibertinusSans-Bold-tosf-ot1.tfm \
tex-LibertinusSans-Bold-tosf-sc-lgr.tfm \
tex-LibertinusSans-Bold-tosf-sc-ly1--base.tfm \
tex-LibertinusSans-Bold-tosf-sc-ly1.tfm \
tex-LibertinusSans-Bold-tosf-sc-ly1.vf \
tex-LibertinusSans-Bold-tosf-sc-ot1--base.tfm \
tex-LibertinusSans-Bold-tosf-sc-ot1.tfm \
tex-LibertinusSans-Bold-tosf-sc-ot1.vf \
tex-LibertinusSans-Bold-tosf-sc-t1--base.tfm \
tex-LibertinusSans-Bold-tosf-sc-t1.tfm \
tex-LibertinusSans-Bold-tosf-sc-t1.vf \
tex-LibertinusSans-Bold-tosf-sc-t2a--base.tfm \
tex-LibertinusSans-Bold-tosf-sc-t2a.tfm \
tex-LibertinusSans-Bold-tosf-sc-t2a.vf \
tex-LibertinusSans-Bold-tosf-sc-t2b--base.tfm \
tex-LibertinusSans-Bold-tosf-sc-t2b.tfm \
tex-LibertinusSans-Bold-tosf-sc-t2b.vf \
tex-LibertinusSans-Bold-tosf-sc-t2c--base.tfm \
tex-LibertinusSans-Bold-tosf-sc-t2c.tfm \
tex-LibertinusSans-Bold-tosf-sc-t2c.vf \
tex-LibertinusSans-Bold-tosf-t1--base.tfm \
tex-LibertinusSans-Bold-tosf-t1.tfm \
tex-LibertinusSans-Bold-tosf-t1.vf \
tex-LibertinusSans-Bold-tosf-t2a.tfm \
tex-LibertinusSans-Bold-tosf-t2b.tfm \
tex-LibertinusSans-Bold-tosf-t2c.tfm \
tex-LibertinusSans-Bold-tosf-ts1--base.tfm \
tex-LibertinusSans-Bold-tosf-ts1.tfm \
tex-LibertinusSans-Bold-tosf-ts1.vf \
tex-LibertinusSans-BoldOblique-lf-lgr.tfm \
tex-LibertinusSans-BoldOblique-lf-ly1.tfm \
tex-LibertinusSans-BoldOblique-lf-ot1.tfm \
tex-LibertinusSans-BoldOblique-lf-sc-lgr.tfm \
tex-LibertinusSans-BoldOblique-lf-sc-ly1--base.tfm \
tex-LibertinusSans-BoldOblique-lf-sc-ly1.tfm \
tex-LibertinusSans-BoldOblique-lf-sc-ly1.vf \
tex-LibertinusSans-BoldOblique-lf-sc-ot1--base.tfm \
tex-LibertinusSans-BoldOblique-lf-sc-ot1.tfm \
tex-LibertinusSans-BoldOblique-lf-sc-ot1.vf \
tex-LibertinusSans-BoldOblique-lf-sc-t1--base.tfm \
tex-LibertinusSans-BoldOblique-lf-sc-t1.tfm \
tex-LibertinusSans-BoldOblique-lf-sc-t1.vf \
tex-LibertinusSans-BoldOblique-lf-sc-t2a--base.tfm \
tex-LibertinusSans-BoldOblique-lf-sc-t2a.tfm \
tex-LibertinusSans-BoldOblique-lf-sc-t2a.vf \
tex-LibertinusSans-BoldOblique-lf-sc-t2b--base.tfm \
tex-LibertinusSans-BoldOblique-lf-sc-t2b.tfm \
tex-LibertinusSans-BoldOblique-lf-sc-t2b.vf \
tex-LibertinusSans-BoldOblique-lf-sc-t2c--base.tfm \
tex-LibertinusSans-BoldOblique-lf-sc-t2c.tfm \
tex-LibertinusSans-BoldOblique-lf-sc-t2c.vf \
tex-LibertinusSans-BoldOblique-lf-t1--base.tfm \
tex-LibertinusSans-BoldOblique-lf-t1.tfm \
tex-LibertinusSans-BoldOblique-lf-t1.vf \
tex-LibertinusSans-BoldOblique-lf-t2a.tfm \
tex-LibertinusSans-BoldOblique-lf-t2b.tfm \
tex-LibertinusSans-BoldOblique-lf-t2c.tfm \
tex-LibertinusSans-BoldOblique-lf-ts1--base.tfm \
tex-LibertinusSans-BoldOblique-lf-ts1.tfm \
tex-LibertinusSans-BoldOblique-lf-ts1.vf \
tex-LibertinusSans-BoldOblique-osf-lgr.tfm \
tex-LibertinusSans-BoldOblique-osf-ly1.tfm \
tex-LibertinusSans-BoldOblique-osf-ot1.tfm \
tex-LibertinusSans-BoldOblique-osf-sc-lgr.tfm \
tex-LibertinusSans-BoldOblique-osf-sc-ly1--base.tfm \
tex-LibertinusSans-BoldOblique-osf-sc-ly1.tfm \
tex-LibertinusSans-BoldOblique-osf-sc-ly1.vf \
tex-LibertinusSans-BoldOblique-osf-sc-ot1--base.tfm \
tex-LibertinusSans-BoldOblique-osf-sc-ot1.tfm \
tex-LibertinusSans-BoldOblique-osf-sc-ot1.vf \
tex-LibertinusSans-BoldOblique-osf-sc-t1--base.tfm \
tex-LibertinusSans-BoldOblique-osf-sc-t1.tfm \
tex-LibertinusSans-BoldOblique-osf-sc-t1.vf \
tex-LibertinusSans-BoldOblique-osf-sc-t2a--base.tfm \
tex-LibertinusSans-BoldOblique-osf-sc-t2a.tfm \
tex-LibertinusSans-BoldOblique-osf-sc-t2a.vf \
tex-LibertinusSans-BoldOblique-osf-sc-t2b--base.tfm \
tex-LibertinusSans-BoldOblique-osf-sc-t2b.tfm \
tex-LibertinusSans-BoldOblique-osf-sc-t2b.vf \
tex-LibertinusSans-BoldOblique-osf-sc-t2c--base.tfm \
tex-LibertinusSans-BoldOblique-osf-sc-t2c.tfm \
tex-LibertinusSans-BoldOblique-osf-sc-t2c.vf \
tex-LibertinusSans-BoldOblique-osf-t1--base.tfm \
tex-LibertinusSans-BoldOblique-osf-t1.tfm \
tex-LibertinusSans-BoldOblique-osf-t1.vf \
tex-LibertinusSans-BoldOblique-osf-t2a.tfm \
tex-LibertinusSans-BoldOblique-osf-t2b.tfm \
tex-LibertinusSans-BoldOblique-osf-t2c.tfm \
tex-LibertinusSans-BoldOblique-osf-ts1--base.tfm \
tex-LibertinusSans-BoldOblique-osf-ts1.tfm \
tex-LibertinusSans-BoldOblique-osf-ts1.vf \
tex-LibertinusSans-BoldOblique-sup-lgr.tfm \
tex-LibertinusSans-BoldOblique-sup-ly1.tfm \
tex-LibertinusSans-BoldOblique-sup-ot1.tfm \
tex-LibertinusSans-BoldOblique-sup-t1--base.tfm \
tex-LibertinusSans-BoldOblique-sup-t1.tfm \
tex-LibertinusSans-BoldOblique-sup-t1.vf \
tex-LibertinusSans-BoldOblique-sup-t2a.tfm \
tex-LibertinusSans-BoldOblique-sup-t2b.tfm \
tex-LibertinusSans-BoldOblique-sup-t2c.tfm \
tex-LibertinusSans-BoldOblique-tlf-lgr.tfm \
tex-LibertinusSans-BoldOblique-tlf-ly1.tfm \
tex-LibertinusSans-BoldOblique-tlf-ot1.tfm \
tex-LibertinusSans-BoldOblique-tlf-sc-lgr.tfm \
tex-LibertinusSans-BoldOblique-tlf-sc-ly1--base.tfm \
tex-LibertinusSans-BoldOblique-tlf-sc-ly1.tfm \
tex-LibertinusSans-BoldOblique-tlf-sc-ly1.vf \
tex-LibertinusSans-BoldOblique-tlf-sc-ot1--base.tfm \
tex-LibertinusSans-BoldOblique-tlf-sc-ot1.tfm \
tex-LibertinusSans-BoldOblique-tlf-sc-ot1.vf \
tex-LibertinusSans-BoldOblique-tlf-sc-t1--base.tfm \
tex-LibertinusSans-BoldOblique-tlf-sc-t1.tfm \
tex-LibertinusSans-BoldOblique-tlf-sc-t1.vf \
tex-LibertinusSans-BoldOblique-tlf-sc-t2a--base.tfm \
tex-LibertinusSans-BoldOblique-tlf-sc-t2a.tfm \
tex-LibertinusSans-BoldOblique-tlf-sc-t2a.vf \
tex-LibertinusSans-BoldOblique-tlf-sc-t2b--base.tfm \
tex-LibertinusSans-BoldOblique-tlf-sc-t2b.tfm \
tex-LibertinusSans-BoldOblique-tlf-sc-t2b.vf \
tex-LibertinusSans-BoldOblique-tlf-sc-t2c--base.tfm \
tex-LibertinusSans-BoldOblique-tlf-sc-t2c.tfm \
tex-LibertinusSans-BoldOblique-tlf-sc-t2c.vf \
tex-LibertinusSans-BoldOblique-tlf-t1--base.tfm \
tex-LibertinusSans-BoldOblique-tlf-t1.tfm \
tex-LibertinusSans-BoldOblique-tlf-t1.vf \
tex-LibertinusSans-BoldOblique-tlf-t2a.tfm \
tex-LibertinusSans-BoldOblique-tlf-t2b.tfm \
tex-LibertinusSans-BoldOblique-tlf-t2c.tfm \
tex-LibertinusSans-BoldOblique-tlf-ts1--base.tfm \
tex-LibertinusSans-BoldOblique-tlf-ts1.tfm \
tex-LibertinusSans-BoldOblique-tlf-ts1.vf \
tex-LibertinusSans-BoldOblique-tosf-lgr.tfm \
tex-LibertinusSans-BoldOblique-tosf-ly1.tfm \
tex-LibertinusSans-BoldOblique-tosf-ot1.tfm \
tex-LibertinusSans-BoldOblique-tosf-sc-lgr.tfm \
tex-LibertinusSans-BoldOblique-tosf-sc-ly1--base.tfm \
tex-LibertinusSans-BoldOblique-tosf-sc-ly1.tfm \
tex-LibertinusSans-BoldOblique-tosf-sc-ly1.vf \
tex-LibertinusSans-BoldOblique-tosf-sc-ot1--base.tfm \
tex-LibertinusSans-BoldOblique-tosf-sc-ot1.tfm \
tex-LibertinusSans-BoldOblique-tosf-sc-ot1.vf \
tex-LibertinusSans-BoldOblique-tosf-sc-t1--base.tfm \
tex-LibertinusSans-BoldOblique-tosf-sc-t1.tfm \
tex-LibertinusSans-BoldOblique-tosf-sc-t1.vf \
tex-LibertinusSans-BoldOblique-tosf-sc-t2a--base.tfm \
tex-LibertinusSans-BoldOblique-tosf-sc-t2a.tfm \
tex-LibertinusSans-BoldOblique-tosf-sc-t2a.vf \
tex-LibertinusSans-BoldOblique-tosf-sc-t2b--base.tfm \
tex-LibertinusSans-BoldOblique-tosf-sc-t2b.tfm \
tex-LibertinusSans-BoldOblique-tosf-sc-t2b.vf \
tex-LibertinusSans-BoldOblique-tosf-sc-t2c--base.tfm \
tex-LibertinusSans-BoldOblique-tosf-sc-t2c.tfm \
tex-LibertinusSans-BoldOblique-tosf-sc-t2c.vf \
tex-LibertinusSans-BoldOblique-tosf-t1--base.tfm \
tex-LibertinusSans-BoldOblique-tosf-t1.tfm \
tex-LibertinusSans-BoldOblique-tosf-t1.vf \
tex-LibertinusSans-BoldOblique-tosf-t2a.tfm \
tex-LibertinusSans-BoldOblique-tosf-t2b.tfm \
tex-LibertinusSans-BoldOblique-tosf-t2c.tfm \
tex-LibertinusSans-BoldOblique-tosf-ts1--base.tfm \
tex-LibertinusSans-BoldOblique-tosf-ts1.tfm \
tex-LibertinusSans-BoldOblique-tosf-ts1.vf \
tex-LibertinusSans-Italic-lf-lgr--base.tfm \
tex-LibertinusSans-Italic-lf-lgr.tfm \
tex-LibertinusSans-Italic-lf-lgr.vf \
tex-LibertinusSans-Italic-lf-ly1--base.tfm \
tex-LibertinusSans-Italic-lf-ly1.tfm \
tex-LibertinusSans-Italic-lf-ly1.vf \
tex-LibertinusSans-Italic-lf-ot1.tfm \
tex-LibertinusSans-Italic-lf-sc-lgr--base.tfm \
tex-LibertinusSans-Italic-lf-sc-lgr.tfm \
tex-LibertinusSans-Italic-lf-sc-lgr.vf \
tex-LibertinusSans-Italic-lf-sc-ly1--base.tfm \
tex-LibertinusSans-Italic-lf-sc-ly1.tfm \
tex-LibertinusSans-Italic-lf-sc-ly1.vf \
tex-LibertinusSans-Italic-lf-sc-ot1--base.tfm \
tex-LibertinusSans-Italic-lf-sc-ot1.tfm \
tex-LibertinusSans-Italic-lf-sc-ot1.vf \
tex-LibertinusSans-Italic-lf-sc-t1--base.tfm \
tex-LibertinusSans-Italic-lf-sc-t1.tfm \
tex-LibertinusSans-Italic-lf-sc-t1.vf \
tex-LibertinusSans-Italic-lf-sc-t2a--base.tfm \
tex-LibertinusSans-Italic-lf-sc-t2a.tfm \
tex-LibertinusSans-Italic-lf-sc-t2a.vf \
tex-LibertinusSans-Italic-lf-sc-t2b--base.tfm \
tex-LibertinusSans-Italic-lf-sc-t2b.tfm \
tex-LibertinusSans-Italic-lf-sc-t2b.vf \
tex-LibertinusSans-Italic-lf-sc-t2c--base.tfm \
tex-LibertinusSans-Italic-lf-sc-t2c.tfm \
tex-LibertinusSans-Italic-lf-sc-t2c.vf \
tex-LibertinusSans-Italic-lf-t1--base.tfm \
tex-LibertinusSans-Italic-lf-t1.tfm \
tex-LibertinusSans-Italic-lf-t1.vf \
tex-LibertinusSans-Italic-lf-t2a.tfm \
tex-LibertinusSans-Italic-lf-t2b.tfm \
tex-LibertinusSans-Italic-lf-t2c.tfm \
tex-LibertinusSans-Italic-lf-ts1--base.tfm \
tex-LibertinusSans-Italic-lf-ts1.tfm \
tex-LibertinusSans-Italic-lf-ts1.vf \
tex-LibertinusSans-Italic-osf-lgr--base.tfm \
tex-LibertinusSans-Italic-osf-lgr.tfm \
tex-LibertinusSans-Italic-osf-lgr.vf \
tex-LibertinusSans-Italic-osf-ly1--base.tfm \
tex-LibertinusSans-Italic-osf-ly1.tfm \
tex-LibertinusSans-Italic-osf-ly1.vf \
tex-LibertinusSans-Italic-osf-ot1.tfm \
tex-LibertinusSans-Italic-osf-sc-lgr--base.tfm \
tex-LibertinusSans-Italic-osf-sc-lgr.tfm \
tex-LibertinusSans-Italic-osf-sc-lgr.vf \
tex-LibertinusSans-Italic-osf-sc-ly1--base.tfm \
tex-LibertinusSans-Italic-osf-sc-ly1.tfm \
tex-LibertinusSans-Italic-osf-sc-ly1.vf \
tex-LibertinusSans-Italic-osf-sc-ot1--base.tfm \
tex-LibertinusSans-Italic-osf-sc-ot1.tfm \
tex-LibertinusSans-Italic-osf-sc-ot1.vf \
tex-LibertinusSans-Italic-osf-sc-t1--base.tfm \
tex-LibertinusSans-Italic-osf-sc-t1.tfm \
tex-LibertinusSans-Italic-osf-sc-t1.vf \
tex-LibertinusSans-Italic-osf-sc-t2a--base.tfm \
tex-LibertinusSans-Italic-osf-sc-t2a.tfm \
tex-LibertinusSans-Italic-osf-sc-t2a.vf \
tex-LibertinusSans-Italic-osf-sc-t2b--base.tfm \
tex-LibertinusSans-Italic-osf-sc-t2b.tfm \
tex-LibertinusSans-Italic-osf-sc-t2b.vf \
tex-LibertinusSans-Italic-osf-sc-t2c--base.tfm \
tex-LibertinusSans-Italic-osf-sc-t2c.tfm \
tex-LibertinusSans-Italic-osf-sc-t2c.vf \
tex-LibertinusSans-Italic-osf-t1--base.tfm \
tex-LibertinusSans-Italic-osf-t1.tfm \
tex-LibertinusSans-Italic-osf-t1.vf \
tex-LibertinusSans-Italic-osf-t2a.tfm \
tex-LibertinusSans-Italic-osf-t2b.tfm \
tex-LibertinusSans-Italic-osf-t2c.tfm \
tex-LibertinusSans-Italic-osf-ts1--base.tfm \
tex-LibertinusSans-Italic-osf-ts1.tfm \
tex-LibertinusSans-Italic-osf-ts1.vf \
tex-LibertinusSans-Italic-sup-lgr--base.tfm \
tex-LibertinusSans-Italic-sup-lgr.tfm \
tex-LibertinusSans-Italic-sup-lgr.vf \
tex-LibertinusSans-Italic-sup-ly1--base.tfm \
tex-LibertinusSans-Italic-sup-ly1.tfm \
tex-LibertinusSans-Italic-sup-ly1.vf \
tex-LibertinusSans-Italic-sup-ot1.tfm \
tex-LibertinusSans-Italic-sup-t1--base.tfm \
tex-LibertinusSans-Italic-sup-t1.tfm \
tex-LibertinusSans-Italic-sup-t1.vf \
tex-LibertinusSans-Italic-sup-t2a.tfm \
tex-LibertinusSans-Italic-sup-t2b.tfm \
tex-LibertinusSans-Italic-sup-t2c.tfm \
tex-LibertinusSans-Italic-tlf-lgr--base.tfm \
tex-LibertinusSans-Italic-tlf-lgr.tfm \
tex-LibertinusSans-Italic-tlf-lgr.vf \
tex-LibertinusSans-Italic-tlf-ly1--base.tfm \
tex-LibertinusSans-Italic-tlf-ly1.tfm \
tex-LibertinusSans-Italic-tlf-ly1.vf \
tex-LibertinusSans-Italic-tlf-ot1.tfm \
tex-LibertinusSans-Italic-tlf-sc-lgr--base.tfm \
tex-LibertinusSans-Italic-tlf-sc-lgr.tfm \
tex-LibertinusSans-Italic-tlf-sc-lgr.vf \
tex-LibertinusSans-Italic-tlf-sc-ly1--base.tfm \
tex-LibertinusSans-Italic-tlf-sc-ly1.tfm \
tex-LibertinusSans-Italic-tlf-sc-ly1.vf \
tex-LibertinusSans-Italic-tlf-sc-ot1--base.tfm \
tex-LibertinusSans-Italic-tlf-sc-ot1.tfm \
tex-LibertinusSans-Italic-tlf-sc-ot1.vf \
tex-LibertinusSans-Italic-tlf-sc-t1--base.tfm \
tex-LibertinusSans-Italic-tlf-sc-t1.tfm \
tex-LibertinusSans-Italic-tlf-sc-t1.vf \
tex-LibertinusSans-Italic-tlf-sc-t2a--base.tfm \
tex-LibertinusSans-Italic-tlf-sc-t2a.tfm \
tex-LibertinusSans-Italic-tlf-sc-t2a.vf \
tex-LibertinusSans-Italic-tlf-sc-t2b--base.tfm \
tex-LibertinusSans-Italic-tlf-sc-t2b.tfm \
tex-LibertinusSans-Italic-tlf-sc-t2b.vf \
tex-LibertinusSans-Italic-tlf-sc-t2c--base.tfm \
tex-LibertinusSans-Italic-tlf-sc-t2c.tfm \
tex-LibertinusSans-Italic-tlf-sc-t2c.vf \
tex-LibertinusSans-Italic-tlf-t1--base.tfm \
tex-LibertinusSans-Italic-tlf-t1.tfm \
tex-LibertinusSans-Italic-tlf-t1.vf \
tex-LibertinusSans-Italic-tlf-t2a.tfm \
tex-LibertinusSans-Italic-tlf-t2b.tfm \
tex-LibertinusSans-Italic-tlf-t2c.tfm \
tex-LibertinusSans-Italic-tlf-ts1--base.tfm \
tex-LibertinusSans-Italic-tlf-ts1.tfm \
tex-LibertinusSans-Italic-tlf-ts1.vf \
tex-LibertinusSans-Italic-tosf-lgr--base.tfm \
tex-LibertinusSans-Italic-tosf-lgr.tfm \
tex-LibertinusSans-Italic-tosf-lgr.vf \
tex-LibertinusSans-Italic-tosf-ly1--base.tfm \
tex-LibertinusSans-Italic-tosf-ly1.tfm \
tex-LibertinusSans-Italic-tosf-ly1.vf \
tex-LibertinusSans-Italic-tosf-ot1.tfm \
tex-LibertinusSans-Italic-tosf-sc-lgr--base.tfm \
tex-LibertinusSans-Italic-tosf-sc-lgr.tfm \
tex-LibertinusSans-Italic-tosf-sc-lgr.vf \
tex-LibertinusSans-Italic-tosf-sc-ly1--base.tfm \
tex-LibertinusSans-Italic-tosf-sc-ly1.tfm \
tex-LibertinusSans-Italic-tosf-sc-ly1.vf \
tex-LibertinusSans-Italic-tosf-sc-ot1--base.tfm \
tex-LibertinusSans-Italic-tosf-sc-ot1.tfm \
tex-LibertinusSans-Italic-tosf-sc-ot1.vf \
tex-LibertinusSans-Italic-tosf-sc-t1--base.tfm \
tex-LibertinusSans-Italic-tosf-sc-t1.tfm \
tex-LibertinusSans-Italic-tosf-sc-t1.vf \
tex-LibertinusSans-Italic-tosf-sc-t2a--base.tfm \
tex-LibertinusSans-Italic-tosf-sc-t2a.tfm \
tex-LibertinusSans-Italic-tosf-sc-t2a.vf \
tex-LibertinusSans-Italic-tosf-sc-t2b--base.tfm \
tex-LibertinusSans-Italic-tosf-sc-t2b.tfm \
tex-LibertinusSans-Italic-tosf-sc-t2b.vf \
tex-LibertinusSans-Italic-tosf-sc-t2c--base.tfm \
tex-LibertinusSans-Italic-tosf-sc-t2c.tfm \
tex-LibertinusSans-Italic-tosf-sc-t2c.vf \
tex-LibertinusSans-Italic-tosf-t1--base.tfm \
tex-LibertinusSans-Italic-tosf-t1.tfm \
tex-LibertinusSans-Italic-tosf-t1.vf \
tex-LibertinusSans-Italic-tosf-t2a.tfm \
tex-LibertinusSans-Italic-tosf-t2b.tfm \
tex-LibertinusSans-Italic-tosf-t2c.tfm \
tex-LibertinusSans-Italic-tosf-ts1--base.tfm \
tex-LibertinusSans-Italic-tosf-ts1.tfm \
tex-LibertinusSans-Italic-tosf-ts1.vf \
tex-LibertinusSans-Regular-lf-lgr.tfm \
tex-LibertinusSans-Regular-lf-ly1.tfm \
tex-LibertinusSans-Regular-lf-ot1.tfm \
tex-LibertinusSans-Regular-lf-sc-lgr.tfm \
tex-LibertinusSans-Regular-lf-sc-ly1--base.tfm \
tex-LibertinusSans-Regular-lf-sc-ly1.tfm \
tex-LibertinusSans-Regular-lf-sc-ly1.vf \
tex-LibertinusSans-Regular-lf-sc-ot1--base.tfm \
tex-LibertinusSans-Regular-lf-sc-ot1.tfm \
tex-LibertinusSans-Regular-lf-sc-ot1.vf \
tex-LibertinusSans-Regular-lf-sc-t1--base.tfm \
tex-LibertinusSans-Regular-lf-sc-t1.tfm \
tex-LibertinusSans-Regular-lf-sc-t1.vf \
tex-LibertinusSans-Regular-lf-sc-t2a--base.tfm \
tex-LibertinusSans-Regular-lf-sc-t2a.tfm \
tex-LibertinusSans-Regular-lf-sc-t2a.vf \
tex-LibertinusSans-Regular-lf-sc-t2b--base.tfm \
tex-LibertinusSans-Regular-lf-sc-t2b.tfm \
tex-LibertinusSans-Regular-lf-sc-t2b.vf \
tex-LibertinusSans-Regular-lf-sc-t2c--base.tfm \
tex-LibertinusSans-Regular-lf-sc-t2c.tfm \
tex-LibertinusSans-Regular-lf-sc-t2c.vf \
tex-LibertinusSans-Regular-lf-t1--base.tfm \
tex-LibertinusSans-Regular-lf-t1.tfm \
tex-LibertinusSans-Regular-lf-t1.vf \
tex-LibertinusSans-Regular-lf-t2a.tfm \
tex-LibertinusSans-Regular-lf-t2b.tfm \
tex-LibertinusSans-Regular-lf-t2c.tfm \
tex-LibertinusSans-Regular-lf-ts1--base.tfm \
tex-LibertinusSans-Regular-lf-ts1.tfm \
tex-LibertinusSans-Regular-lf-ts1.vf \
tex-LibertinusSans-Regular-osf-lgr.tfm \
tex-LibertinusSans-Regular-osf-ly1.tfm \
tex-LibertinusSans-Regular-osf-ot1.tfm \
tex-LibertinusSans-Regular-osf-sc-lgr.tfm \
tex-LibertinusSans-Regular-osf-sc-ly1--base.tfm \
tex-LibertinusSans-Regular-osf-sc-ly1.tfm \
tex-LibertinusSans-Regular-osf-sc-ly1.vf \
tex-LibertinusSans-Regular-osf-sc-ot1--base.tfm \
tex-LibertinusSans-Regular-osf-sc-ot1.tfm \
tex-LibertinusSans-Regular-osf-sc-ot1.vf \
tex-LibertinusSans-Regular-osf-sc-t1--base.tfm \
tex-LibertinusSans-Regular-osf-sc-t1.tfm \
tex-LibertinusSans-Regular-osf-sc-t1.vf \
tex-LibertinusSans-Regular-osf-sc-t2a--base.tfm \
tex-LibertinusSans-Regular-osf-sc-t2a.tfm \
tex-LibertinusSans-Regular-osf-sc-t2a.vf \
tex-LibertinusSans-Regular-osf-sc-t2b--base.tfm \
tex-LibertinusSans-Regular-osf-sc-t2b.tfm \
tex-LibertinusSans-Regular-osf-sc-t2b.vf \
tex-LibertinusSans-Regular-osf-sc-t2c--base.tfm \
tex-LibertinusSans-Regular-osf-sc-t2c.tfm \
tex-LibertinusSans-Regular-osf-sc-t2c.vf \
tex-LibertinusSans-Regular-osf-t1--base.tfm \
tex-LibertinusSans-Regular-osf-t1.tfm \
tex-LibertinusSans-Regular-osf-t1.vf \
tex-LibertinusSans-Regular-osf-t2a.tfm \
tex-LibertinusSans-Regular-osf-t2b.tfm \
tex-LibertinusSans-Regular-osf-t2c.tfm \
tex-LibertinusSans-Regular-osf-ts1--base.tfm \
tex-LibertinusSans-Regular-osf-ts1.tfm \
tex-LibertinusSans-Regular-osf-ts1.vf \
tex-LibertinusSans-Regular-sup-lgr.tfm \
tex-LibertinusSans-Regular-sup-ly1.tfm \
tex-LibertinusSans-Regular-sup-ot1.tfm \
tex-LibertinusSans-Regular-sup-t1--base.tfm \
tex-LibertinusSans-Regular-sup-t1.tfm \
tex-LibertinusSans-Regular-sup-t1.vf \
tex-LibertinusSans-Regular-sup-t2a.tfm \
tex-LibertinusSans-Regular-sup-t2b.tfm \
tex-LibertinusSans-Regular-sup-t2c.tfm \
tex-LibertinusSans-Regular-tlf-lgr.tfm \
tex-LibertinusSans-Regular-tlf-ly1.tfm \
tex-LibertinusSans-Regular-tlf-ot1.tfm \
tex-LibertinusSans-Regular-tlf-sc-lgr.tfm \
tex-LibertinusSans-Regular-tlf-sc-ly1--base.tfm \
tex-LibertinusSans-Regular-tlf-sc-ly1.tfm \
tex-LibertinusSans-Regular-tlf-sc-ly1.vf \
tex-LibertinusSans-Regular-tlf-sc-ot1--base.tfm \
tex-LibertinusSans-Regular-tlf-sc-ot1.tfm \
tex-LibertinusSans-Regular-tlf-sc-ot1.vf \
tex-LibertinusSans-Regular-tlf-sc-t1--base.tfm \
tex-LibertinusSans-Regular-tlf-sc-t1.tfm \
tex-LibertinusSans-Regular-tlf-sc-t1.vf \
tex-LibertinusSans-Regular-tlf-sc-t2a--base.tfm \
tex-LibertinusSans-Regular-tlf-sc-t2a.tfm \
tex-LibertinusSans-Regular-tlf-sc-t2a.vf \
tex-LibertinusSans-Regular-tlf-sc-t2b--base.tfm \
tex-LibertinusSans-Regular-tlf-sc-t2b.tfm \
tex-LibertinusSans-Regular-tlf-sc-t2b.vf \
tex-LibertinusSans-Regular-tlf-sc-t2c--base.tfm \
tex-LibertinusSans-Regular-tlf-sc-t2c.tfm \
tex-LibertinusSans-Regular-tlf-sc-t2c.vf \
tex-LibertinusSans-Regular-tlf-t1--base.tfm \
tex-LibertinusSans-Regular-tlf-t1.tfm \
tex-LibertinusSans-Regular-tlf-t1.vf \
tex-LibertinusSans-Regular-tlf-t2a.tfm \
tex-LibertinusSans-Regular-tlf-t2b.tfm \
tex-LibertinusSans-Regular-tlf-t2c.tfm \
tex-LibertinusSans-Regular-tlf-ts1--base.tfm \
tex-LibertinusSans-Regular-tlf-ts1.tfm \
tex-LibertinusSans-Regular-tlf-ts1.vf \
tex-LibertinusSans-Regular-tosf-lgr.tfm \
tex-LibertinusSans-Regular-tosf-ly1.tfm \
tex-LibertinusSans-Regular-tosf-ot1.tfm \
tex-LibertinusSans-Regular-tosf-sc-lgr.tfm \
tex-LibertinusSans-Regular-tosf-sc-ly1--base.tfm \
tex-LibertinusSans-Regular-tosf-sc-ly1.tfm \
tex-LibertinusSans-Regular-tosf-sc-ly1.vf \
tex-LibertinusSans-Regular-tosf-sc-ot1--base.tfm \
tex-LibertinusSans-Regular-tosf-sc-ot1.tfm \
tex-LibertinusSans-Regular-tosf-sc-ot1.vf \
tex-LibertinusSans-Regular-tosf-sc-t1--base.tfm \
tex-LibertinusSans-Regular-tosf-sc-t1.tfm \
tex-LibertinusSans-Regular-tosf-sc-t1.vf \
tex-LibertinusSans-Regular-tosf-sc-t2a--base.tfm \
tex-LibertinusSans-Regular-tosf-sc-t2a.tfm \
tex-LibertinusSans-Regular-tosf-sc-t2a.vf \
tex-LibertinusSans-Regular-tosf-sc-t2b--base.tfm \
tex-LibertinusSans-Regular-tosf-sc-t2b.tfm \
tex-LibertinusSans-Regular-tosf-sc-t2b.vf \
tex-LibertinusSans-Regular-tosf-sc-t2c--base.tfm \
tex-LibertinusSans-Regular-tosf-sc-t2c.tfm \
tex-LibertinusSans-Regular-tosf-sc-t2c.vf \
tex-LibertinusSans-Regular-tosf-t1--base.tfm \
tex-LibertinusSans-Regular-tosf-t1.tfm \
tex-LibertinusSans-Regular-tosf-t1.vf \
tex-LibertinusSans-Regular-tosf-t2a.tfm \
tex-LibertinusSans-Regular-tosf-t2b.tfm \
tex-LibertinusSans-Regular-tosf-t2c.tfm \
tex-LibertinusSans-Regular-tosf-ts1--base.tfm \
tex-LibertinusSans-Regular-tosf-ts1.tfm \
tex-LibertinusSans-Regular-tosf-ts1.vf \
tex-LibertinusSerif-Bold-lf-lgr.tfm \
tex-LibertinusSerif-Bold-lf-ly1.tfm \
tex-LibertinusSerif-Bold-lf-ot1.tfm \
tex-LibertinusSerif-Bold-lf-sc-lgr.tfm \
tex-LibertinusSerif-Bold-lf-sc-ly1--base.tfm \
tex-LibertinusSerif-Bold-lf-sc-ly1.tfm \
tex-LibertinusSerif-Bold-lf-sc-ly1.vf \
tex-LibertinusSerif-Bold-lf-sc-ot1--base.tfm \
tex-LibertinusSerif-Bold-lf-sc-ot1.tfm \
tex-LibertinusSerif-Bold-lf-sc-ot1.vf \
tex-LibertinusSerif-Bold-lf-sc-t1--base.tfm \
tex-LibertinusSerif-Bold-lf-sc-t1.tfm \
tex-LibertinusSerif-Bold-lf-sc-t1.vf \
tex-LibertinusSerif-Bold-lf-sc-t2a--base.tfm \
tex-LibertinusSerif-Bold-lf-sc-t2a.tfm \
tex-LibertinusSerif-Bold-lf-sc-t2a.vf \
tex-LibertinusSerif-Bold-lf-sc-t2b--base.tfm \
tex-LibertinusSerif-Bold-lf-sc-t2b.tfm \
tex-LibertinusSerif-Bold-lf-sc-t2b.vf \
tex-LibertinusSerif-Bold-lf-sc-t2c--base.tfm \
tex-LibertinusSerif-Bold-lf-sc-t2c.tfm \
tex-LibertinusSerif-Bold-lf-sc-t2c.vf \
tex-LibertinusSerif-Bold-lf-t1--base.tfm \
tex-LibertinusSerif-Bold-lf-t1.tfm \
tex-LibertinusSerif-Bold-lf-t1.vf \
tex-LibertinusSerif-Bold-lf-t2a.tfm \
tex-LibertinusSerif-Bold-lf-t2b.tfm \
tex-LibertinusSerif-Bold-lf-t2c.tfm \
tex-LibertinusSerif-Bold-lf-ts1--base.tfm \
tex-LibertinusSerif-Bold-lf-ts1.tfm \
tex-LibertinusSerif-Bold-lf-ts1.vf \
tex-LibertinusSerif-Bold-osf-lgr.tfm \
tex-LibertinusSerif-Bold-osf-ly1.tfm \
tex-LibertinusSerif-Bold-osf-ot1.tfm \
tex-LibertinusSerif-Bold-osf-sc-lgr.tfm \
tex-LibertinusSerif-Bold-osf-sc-ly1--base.tfm \
tex-LibertinusSerif-Bold-osf-sc-ly1.tfm \
tex-LibertinusSerif-Bold-osf-sc-ly1.vf \
tex-LibertinusSerif-Bold-osf-sc-ot1--base.tfm \
tex-LibertinusSerif-Bold-osf-sc-ot1.tfm \
tex-LibertinusSerif-Bold-osf-sc-ot1.vf \
tex-LibertinusSerif-Bold-osf-sc-t1--base.tfm \
tex-LibertinusSerif-Bold-osf-sc-t1.tfm \
tex-LibertinusSerif-Bold-osf-sc-t1.vf \
tex-LibertinusSerif-Bold-osf-sc-t2a--base.tfm \
tex-LibertinusSerif-Bold-osf-sc-t2a.tfm \
tex-LibertinusSerif-Bold-osf-sc-t2a.vf \
tex-LibertinusSerif-Bold-osf-sc-t2b--base.tfm \
tex-LibertinusSerif-Bold-osf-sc-t2b.tfm \
tex-LibertinusSerif-Bold-osf-sc-t2b.vf \
tex-LibertinusSerif-Bold-osf-sc-t2c--base.tfm \
tex-LibertinusSerif-Bold-osf-sc-t2c.tfm \
tex-LibertinusSerif-Bold-osf-sc-t2c.vf \
tex-LibertinusSerif-Bold-osf-t1--base.tfm \
tex-LibertinusSerif-Bold-osf-t1.tfm \
tex-LibertinusSerif-Bold-osf-t1.vf \
tex-LibertinusSerif-Bold-osf-t2a.tfm \
tex-LibertinusSerif-Bold-osf-t2b.tfm \
tex-LibertinusSerif-Bold-osf-t2c.tfm \
tex-LibertinusSerif-Bold-osf-ts1--base.tfm \
tex-LibertinusSerif-Bold-osf-ts1.tfm \
tex-LibertinusSerif-Bold-osf-ts1.vf \
tex-LibertinusSerif-Bold-sup-lgr.tfm \
tex-LibertinusSerif-Bold-sup-ly1.tfm \
tex-LibertinusSerif-Bold-sup-ot1.tfm \
tex-LibertinusSerif-Bold-sup-t1--base.tfm \
tex-LibertinusSerif-Bold-sup-t1.tfm \
tex-LibertinusSerif-Bold-sup-t1.vf \
tex-LibertinusSerif-Bold-sup-t2a.tfm \
tex-LibertinusSerif-Bold-sup-t2b.tfm \
tex-LibertinusSerif-Bold-sup-t2c.tfm \
tex-LibertinusSerif-Bold-tlf-lgr.tfm \
tex-LibertinusSerif-Bold-tlf-ly1.tfm \
tex-LibertinusSerif-Bold-tlf-ot1.tfm \
tex-LibertinusSerif-Bold-tlf-sc-lgr.tfm \
tex-LibertinusSerif-Bold-tlf-sc-ly1--base.tfm \
tex-LibertinusSerif-Bold-tlf-sc-ly1.tfm \
tex-LibertinusSerif-Bold-tlf-sc-ly1.vf \
tex-LibertinusSerif-Bold-tlf-sc-ot1--base.tfm \
tex-LibertinusSerif-Bold-tlf-sc-ot1.tfm \
tex-LibertinusSerif-Bold-tlf-sc-ot1.vf \
tex-LibertinusSerif-Bold-tlf-sc-t1--base.tfm \
tex-LibertinusSerif-Bold-tlf-sc-t1.tfm \
tex-LibertinusSerif-Bold-tlf-sc-t1.vf \
tex-LibertinusSerif-Bold-tlf-sc-t2a--base.tfm \
tex-LibertinusSerif-Bold-tlf-sc-t2a.tfm \
tex-LibertinusSerif-Bold-tlf-sc-t2a.vf \
tex-LibertinusSerif-Bold-tlf-sc-t2b--base.tfm \
tex-LibertinusSerif-Bold-tlf-sc-t2b.tfm \
tex-LibertinusSerif-Bold-tlf-sc-t2b.vf \
tex-LibertinusSerif-Bold-tlf-sc-t2c--base.tfm \
tex-LibertinusSerif-Bold-tlf-sc-t2c.tfm \
tex-LibertinusSerif-Bold-tlf-sc-t2c.vf \
tex-LibertinusSerif-Bold-tlf-t1--base.tfm \
tex-LibertinusSerif-Bold-tlf-t1.tfm \
tex-LibertinusSerif-Bold-tlf-t1.vf \
tex-LibertinusSerif-Bold-tlf-t2a.tfm \
tex-LibertinusSerif-Bold-tlf-t2b.tfm \
tex-LibertinusSerif-Bold-tlf-t2c.tfm \
tex-LibertinusSerif-Bold-tlf-ts1--base.tfm \
tex-LibertinusSerif-Bold-tlf-ts1.tfm \
tex-LibertinusSerif-Bold-tlf-ts1.vf \
tex-LibertinusSerif-Bold-tosf-lgr.tfm \
tex-LibertinusSerif-Bold-tosf-ly1.tfm \
tex-LibertinusSerif-Bold-tosf-ot1.tfm \
tex-LibertinusSerif-Bold-tosf-sc-lgr.tfm \
tex-LibertinusSerif-Bold-tosf-sc-ly1--base.tfm \
tex-LibertinusSerif-Bold-tosf-sc-ly1.tfm \
tex-LibertinusSerif-Bold-tosf-sc-ly1.vf \
tex-LibertinusSerif-Bold-tosf-sc-ot1--base.tfm \
tex-LibertinusSerif-Bold-tosf-sc-ot1.tfm \
tex-LibertinusSerif-Bold-tosf-sc-ot1.vf \
tex-LibertinusSerif-Bold-tosf-sc-t1--base.tfm \
tex-LibertinusSerif-Bold-tosf-sc-t1.tfm \
tex-LibertinusSerif-Bold-tosf-sc-t1.vf \
tex-LibertinusSerif-Bold-tosf-sc-t2a--base.tfm \
tex-LibertinusSerif-Bold-tosf-sc-t2a.tfm \
tex-LibertinusSerif-Bold-tosf-sc-t2a.vf \
tex-LibertinusSerif-Bold-tosf-sc-t2b--base.tfm \
tex-LibertinusSerif-Bold-tosf-sc-t2b.tfm \
tex-LibertinusSerif-Bold-tosf-sc-t2b.vf \
tex-LibertinusSerif-Bold-tosf-sc-t2c--base.tfm \
tex-LibertinusSerif-Bold-tosf-sc-t2c.tfm \
tex-LibertinusSerif-Bold-tosf-sc-t2c.vf \
tex-LibertinusSerif-Bold-tosf-t1--base.tfm \
tex-LibertinusSerif-Bold-tosf-t1.tfm \
tex-LibertinusSerif-Bold-tosf-t1.vf \
tex-LibertinusSerif-Bold-tosf-t2a.tfm \
tex-LibertinusSerif-Bold-tosf-t2b.tfm \
tex-LibertinusSerif-Bold-tosf-t2c.tfm \
tex-LibertinusSerif-Bold-tosf-ts1--base.tfm \
tex-LibertinusSerif-Bold-tosf-ts1.tfm \
tex-LibertinusSerif-Bold-tosf-ts1.vf \
tex-LibertinusSerif-BoldItalic-lf-lgr.tfm \
tex-LibertinusSerif-BoldItalic-lf-ly1.tfm \
tex-LibertinusSerif-BoldItalic-lf-ot1.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-lgr.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-ly1--base.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-ly1.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-ly1.vf \
tex-LibertinusSerif-BoldItalic-lf-sc-ot1--base.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-ot1.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-ot1.vf \
tex-LibertinusSerif-BoldItalic-lf-sc-t1--base.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-t1.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-t1.vf \
tex-LibertinusSerif-BoldItalic-lf-sc-t2a--base.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-t2a.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-t2a.vf \
tex-LibertinusSerif-BoldItalic-lf-sc-t2b--base.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-t2b.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-t2b.vf \
tex-LibertinusSerif-BoldItalic-lf-sc-t2c--base.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-t2c.tfm \
tex-LibertinusSerif-BoldItalic-lf-sc-t2c.vf \
tex-LibertinusSerif-BoldItalic-lf-t1--base.tfm \
tex-LibertinusSerif-BoldItalic-lf-t1.tfm \
tex-LibertinusSerif-BoldItalic-lf-t1.vf \
tex-LibertinusSerif-BoldItalic-lf-t2a.tfm \
tex-LibertinusSerif-BoldItalic-lf-t2b.tfm \
tex-LibertinusSerif-BoldItalic-lf-t2c.tfm \
tex-LibertinusSerif-BoldItalic-lf-ts1--base.tfm \
tex-LibertinusSerif-BoldItalic-lf-ts1.tfm \
tex-LibertinusSerif-BoldItalic-lf-ts1.vf \
tex-LibertinusSerif-BoldItalic-osf-lgr.tfm \
tex-LibertinusSerif-BoldItalic-osf-ly1.tfm \
tex-LibertinusSerif-BoldItalic-osf-ot1.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-lgr.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-ly1--base.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-ly1.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-ly1.vf \
tex-LibertinusSerif-BoldItalic-osf-sc-ot1--base.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-ot1.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-ot1.vf \
tex-LibertinusSerif-BoldItalic-osf-sc-t1--base.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-t1.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-t1.vf \
tex-LibertinusSerif-BoldItalic-osf-sc-t2a--base.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-t2a.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-t2a.vf \
tex-LibertinusSerif-BoldItalic-osf-sc-t2b--base.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-t2b.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-t2b.vf \
tex-LibertinusSerif-BoldItalic-osf-sc-t2c--base.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-t2c.tfm \
tex-LibertinusSerif-BoldItalic-osf-sc-t2c.vf \
tex-LibertinusSerif-BoldItalic-osf-t1--base.tfm \
tex-LibertinusSerif-BoldItalic-osf-t1.tfm \
tex-LibertinusSerif-BoldItalic-osf-t1.vf \
tex-LibertinusSerif-BoldItalic-osf-t2a.tfm \
tex-LibertinusSerif-BoldItalic-osf-t2b.tfm \
tex-LibertinusSerif-BoldItalic-osf-t2c.tfm \
tex-LibertinusSerif-BoldItalic-osf-ts1--base.tfm \
tex-LibertinusSerif-BoldItalic-osf-ts1.tfm \
tex-LibertinusSerif-BoldItalic-osf-ts1.vf \
tex-LibertinusSerif-BoldItalic-sup-lgr.tfm \
tex-LibertinusSerif-BoldItalic-sup-ly1.tfm \
tex-LibertinusSerif-BoldItalic-sup-ot1.tfm \
tex-LibertinusSerif-BoldItalic-sup-t1--base.tfm \
tex-LibertinusSerif-BoldItalic-sup-t1.tfm \
tex-LibertinusSerif-BoldItalic-sup-t1.vf \
tex-LibertinusSerif-BoldItalic-sup-t2a.tfm \
tex-LibertinusSerif-BoldItalic-sup-t2b.tfm \
tex-LibertinusSerif-BoldItalic-sup-t2c.tfm \
tex-LibertinusSerif-BoldItalic-tlf-lgr.tfm \
tex-LibertinusSerif-BoldItalic-tlf-ly1.tfm \
tex-LibertinusSerif-BoldItalic-tlf-ot1.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-lgr.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-ly1--base.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-ly1.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-ly1.vf \
tex-LibertinusSerif-BoldItalic-tlf-sc-ot1--base.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-ot1.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-ot1.vf \
tex-LibertinusSerif-BoldItalic-tlf-sc-t1--base.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-t1.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-t1.vf \
tex-LibertinusSerif-BoldItalic-tlf-sc-t2a--base.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-t2a.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-t2a.vf \
tex-LibertinusSerif-BoldItalic-tlf-sc-t2b--base.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-t2b.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-t2b.vf \
tex-LibertinusSerif-BoldItalic-tlf-sc-t2c--base.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-t2c.tfm \
tex-LibertinusSerif-BoldItalic-tlf-sc-t2c.vf \
tex-LibertinusSerif-BoldItalic-tlf-t1--base.tfm \
tex-LibertinusSerif-BoldItalic-tlf-t1.tfm \
tex-LibertinusSerif-BoldItalic-tlf-t1.vf \
tex-LibertinusSerif-BoldItalic-tlf-t2a.tfm \
tex-LibertinusSerif-BoldItalic-tlf-t2b.tfm \
tex-LibertinusSerif-BoldItalic-tlf-t2c.tfm \
tex-LibertinusSerif-BoldItalic-tlf-ts1--base.tfm \
tex-LibertinusSerif-BoldItalic-tlf-ts1.tfm \
tex-LibertinusSerif-BoldItalic-tlf-ts1.vf \
tex-LibertinusSerif-BoldItalic-tosf-lgr.tfm \
tex-LibertinusSerif-BoldItalic-tosf-ly1.tfm \
tex-LibertinusSerif-BoldItalic-tosf-ot1.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-lgr.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-ly1--base.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-ly1.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-ly1.vf \
tex-LibertinusSerif-BoldItalic-tosf-sc-ot1--base.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-ot1.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-ot1.vf \
tex-LibertinusSerif-BoldItalic-tosf-sc-t1--base.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-t1.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-t1.vf \
tex-LibertinusSerif-BoldItalic-tosf-sc-t2a--base.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-t2a.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-t2a.vf \
tex-LibertinusSerif-BoldItalic-tosf-sc-t2b--base.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-t2b.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-t2b.vf \
tex-LibertinusSerif-BoldItalic-tosf-sc-t2c--base.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-t2c.tfm \
tex-LibertinusSerif-BoldItalic-tosf-sc-t2c.vf \
tex-LibertinusSerif-BoldItalic-tosf-t1--base.tfm \
tex-LibertinusSerif-BoldItalic-tosf-t1.tfm \
tex-LibertinusSerif-BoldItalic-tosf-t1.vf \
tex-LibertinusSerif-BoldItalic-tosf-t2a.tfm \
tex-LibertinusSerif-BoldItalic-tosf-t2b.tfm \
tex-LibertinusSerif-BoldItalic-tosf-t2c.tfm \
tex-LibertinusSerif-BoldItalic-tosf-ts1--base.tfm \
tex-LibertinusSerif-BoldItalic-tosf-ts1.tfm \
tex-LibertinusSerif-BoldItalic-tosf-ts1.vf \
tex-LibertinusSerif-Italic-lf-lgr.tfm \
tex-LibertinusSerif-Italic-lf-ly1.tfm \
tex-LibertinusSerif-Italic-lf-ot1.tfm \
tex-LibertinusSerif-Italic-lf-sc-lgr.tfm \
tex-LibertinusSerif-Italic-lf-sc-ly1--base.tfm \
tex-LibertinusSerif-Italic-lf-sc-ly1.tfm \
tex-LibertinusSerif-Italic-lf-sc-ly1.vf \
tex-LibertinusSerif-Italic-lf-sc-ot1--base.tfm \
tex-LibertinusSerif-Italic-lf-sc-ot1.tfm \
tex-LibertinusSerif-Italic-lf-sc-ot1.vf \
tex-LibertinusSerif-Italic-lf-sc-t1--base.tfm \
tex-LibertinusSerif-Italic-lf-sc-t1.tfm \
tex-LibertinusSerif-Italic-lf-sc-t1.vf \
tex-LibertinusSerif-Italic-lf-sc-t2a--base.tfm \
tex-LibertinusSerif-Italic-lf-sc-t2a.tfm \
tex-LibertinusSerif-Italic-lf-sc-t2a.vf \
tex-LibertinusSerif-Italic-lf-sc-t2b--base.tfm \
tex-LibertinusSerif-Italic-lf-sc-t2b.tfm \
tex-LibertinusSerif-Italic-lf-sc-t2b.vf \
tex-LibertinusSerif-Italic-lf-sc-t2c--base.tfm \
tex-LibertinusSerif-Italic-lf-sc-t2c.tfm \
tex-LibertinusSerif-Italic-lf-sc-t2c.vf \
tex-LibertinusSerif-Italic-lf-t1--base.tfm \
tex-LibertinusSerif-Italic-lf-t1.tfm \
tex-LibertinusSerif-Italic-lf-t1.vf \
tex-LibertinusSerif-Italic-lf-t2a.tfm \
tex-LibertinusSerif-Italic-lf-t2b.tfm \
tex-LibertinusSerif-Italic-lf-t2c.tfm \
tex-LibertinusSerif-Italic-lf-ts1--base.tfm \
tex-LibertinusSerif-Italic-lf-ts1.tfm \
tex-LibertinusSerif-Italic-lf-ts1.vf \
tex-LibertinusSerif-Italic-osf-lgr.tfm \
tex-LibertinusSerif-Italic-osf-ly1.tfm \
tex-LibertinusSerif-Italic-osf-ot1.tfm \
tex-LibertinusSerif-Italic-osf-sc-lgr.tfm \
tex-LibertinusSerif-Italic-osf-sc-ly1--base.tfm \
tex-LibertinusSerif-Italic-osf-sc-ly1.tfm \
tex-LibertinusSerif-Italic-osf-sc-ly1.vf \
tex-LibertinusSerif-Italic-osf-sc-ot1--base.tfm \
tex-LibertinusSerif-Italic-osf-sc-ot1.tfm \
tex-LibertinusSerif-Italic-osf-sc-ot1.vf \
tex-LibertinusSerif-Italic-osf-sc-t1--base.tfm \
tex-LibertinusSerif-Italic-osf-sc-t1.tfm \
tex-LibertinusSerif-Italic-osf-sc-t1.vf \
tex-LibertinusSerif-Italic-osf-sc-t2a--base.tfm \
tex-LibertinusSerif-Italic-osf-sc-t2a.tfm \
tex-LibertinusSerif-Italic-osf-sc-t2a.vf \
tex-LibertinusSerif-Italic-osf-sc-t2b--base.tfm \
tex-LibertinusSerif-Italic-osf-sc-t2b.tfm \
tex-LibertinusSerif-Italic-osf-sc-t2b.vf \
tex-LibertinusSerif-Italic-osf-sc-t2c--base.tfm \
tex-LibertinusSerif-Italic-osf-sc-t2c.tfm \
tex-LibertinusSerif-Italic-osf-sc-t2c.vf \
tex-LibertinusSerif-Italic-osf-t1--base.tfm \
tex-LibertinusSerif-Italic-osf-t1.tfm \
tex-LibertinusSerif-Italic-osf-t1.vf \
tex-LibertinusSerif-Italic-osf-t2a.tfm \
tex-LibertinusSerif-Italic-osf-t2b.tfm \
tex-LibertinusSerif-Italic-osf-t2c.tfm \
tex-LibertinusSerif-Italic-osf-ts1--base.tfm \
tex-LibertinusSerif-Italic-osf-ts1.tfm \
tex-LibertinusSerif-Italic-osf-ts1.vf \
tex-LibertinusSerif-Italic-sup-lgr.tfm \
tex-LibertinusSerif-Italic-sup-ly1.tfm \
tex-LibertinusSerif-Italic-sup-ot1.tfm \
tex-LibertinusSerif-Italic-sup-t1--base.tfm \
tex-LibertinusSerif-Italic-sup-t1.tfm \
tex-LibertinusSerif-Italic-sup-t1.vf \
tex-LibertinusSerif-Italic-sup-t2a.tfm \
tex-LibertinusSerif-Italic-sup-t2b.tfm \
tex-LibertinusSerif-Italic-sup-t2c.tfm \
tex-LibertinusSerif-Italic-tlf-lgr.tfm \
tex-LibertinusSerif-Italic-tlf-ly1.tfm \
tex-LibertinusSerif-Italic-tlf-ot1.tfm \
tex-LibertinusSerif-Italic-tlf-sc-lgr.tfm \
tex-LibertinusSerif-Italic-tlf-sc-ly1--base.tfm \
tex-LibertinusSerif-Italic-tlf-sc-ly1.tfm \
tex-LibertinusSerif-Italic-tlf-sc-ly1.vf \
tex-LibertinusSerif-Italic-tlf-sc-ot1--base.tfm \
tex-LibertinusSerif-Italic-tlf-sc-ot1.tfm \
tex-LibertinusSerif-Italic-tlf-sc-ot1.vf \
tex-LibertinusSerif-Italic-tlf-sc-t1--base.tfm \
tex-LibertinusSerif-Italic-tlf-sc-t1.tfm \
tex-LibertinusSerif-Italic-tlf-sc-t1.vf \
tex-LibertinusSerif-Italic-tlf-sc-t2a--base.tfm \
tex-LibertinusSerif-Italic-tlf-sc-t2a.tfm \
tex-LibertinusSerif-Italic-tlf-sc-t2a.vf \
tex-LibertinusSerif-Italic-tlf-sc-t2b--base.tfm \
tex-LibertinusSerif-Italic-tlf-sc-t2b.tfm \
tex-LibertinusSerif-Italic-tlf-sc-t2b.vf \
tex-LibertinusSerif-Italic-tlf-sc-t2c--base.tfm \
tex-LibertinusSerif-Italic-tlf-sc-t2c.tfm \
tex-LibertinusSerif-Italic-tlf-sc-t2c.vf \
tex-LibertinusSerif-Italic-tlf-t1--base.tfm \
tex-LibertinusSerif-Italic-tlf-t1.tfm \
tex-LibertinusSerif-Italic-tlf-t1.vf \
tex-LibertinusSerif-Italic-tlf-t2a.tfm \
tex-LibertinusSerif-Italic-tlf-t2b.tfm \
tex-LibertinusSerif-Italic-tlf-t2c.tfm \
tex-LibertinusSerif-Italic-tlf-ts1--base.tfm \
tex-LibertinusSerif-Italic-tlf-ts1.tfm \
tex-LibertinusSerif-Italic-tlf-ts1.vf \
tex-LibertinusSerif-Italic-tosf-lgr.tfm \
tex-LibertinusSerif-Italic-tosf-ly1.tfm \
tex-LibertinusSerif-Italic-tosf-ot1.tfm \
tex-LibertinusSerif-Italic-tosf-sc-lgr.tfm \
tex-LibertinusSerif-Italic-tosf-sc-ly1--base.tfm \
tex-LibertinusSerif-Italic-tosf-sc-ly1.tfm \
tex-LibertinusSerif-Italic-tosf-sc-ly1.vf \
tex-LibertinusSerif-Italic-tosf-sc-ot1--base.tfm \
tex-LibertinusSerif-Italic-tosf-sc-ot1.tfm \
tex-LibertinusSerif-Italic-tosf-sc-ot1.vf \
tex-LibertinusSerif-Italic-tosf-sc-t1--base.tfm \
tex-LibertinusSerif-Italic-tosf-sc-t1.tfm \
tex-LibertinusSerif-Italic-tosf-sc-t1.vf \
tex-LibertinusSerif-Italic-tosf-sc-t2a--base.tfm \
tex-LibertinusSerif-Italic-tosf-sc-t2a.tfm \
tex-LibertinusSerif-Italic-tosf-sc-t2a.vf \
tex-LibertinusSerif-Italic-tosf-sc-t2b--base.tfm \
tex-LibertinusSerif-Italic-tosf-sc-t2b.tfm \
tex-LibertinusSerif-Italic-tosf-sc-t2b.vf \
tex-LibertinusSerif-Italic-tosf-sc-t2c--base.tfm \
tex-LibertinusSerif-Italic-tosf-sc-t2c.tfm \
tex-LibertinusSerif-Italic-tosf-sc-t2c.vf \
tex-LibertinusSerif-Italic-tosf-t1--base.tfm \
tex-LibertinusSerif-Italic-tosf-t1.tfm \
tex-LibertinusSerif-Italic-tosf-t1.vf \
tex-LibertinusSerif-Italic-tosf-t2a.tfm \
tex-LibertinusSerif-Italic-tosf-t2b.tfm \
tex-LibertinusSerif-Italic-tosf-t2c.tfm \
tex-LibertinusSerif-Italic-tosf-ts1--base.tfm \
tex-LibertinusSerif-Italic-tosf-ts1.tfm \
tex-LibertinusSerif-Italic-tosf-ts1.vf \
tex-LibertinusSerif-Regular-lf-lgr.tfm \
tex-LibertinusSerif-Regular-lf-ly1.tfm \
tex-LibertinusSerif-Regular-lf-ot1.tfm \
tex-LibertinusSerif-Regular-lf-sc-lgr.tfm \
tex-LibertinusSerif-Regular-lf-sc-ly1--base.tfm \
tex-LibertinusSerif-Regular-lf-sc-ly1.tfm \
tex-LibertinusSerif-Regular-lf-sc-ly1.vf \
tex-LibertinusSerif-Regular-lf-sc-ot1--base.tfm \
tex-LibertinusSerif-Regular-lf-sc-ot1.tfm \
tex-LibertinusSerif-Regular-lf-sc-ot1.vf \
tex-LibertinusSerif-Regular-lf-sc-t1--base.tfm \
tex-LibertinusSerif-Regular-lf-sc-t1.tfm \
tex-LibertinusSerif-Regular-lf-sc-t1.vf \
tex-LibertinusSerif-Regular-lf-sc-t2a--base.tfm \
tex-LibertinusSerif-Regular-lf-sc-t2a.tfm \
tex-LibertinusSerif-Regular-lf-sc-t2a.vf \
tex-LibertinusSerif-Regular-lf-sc-t2b--base.tfm \
tex-LibertinusSerif-Regular-lf-sc-t2b.tfm \
tex-LibertinusSerif-Regular-lf-sc-t2b.vf \
tex-LibertinusSerif-Regular-lf-sc-t2c--base.tfm \
tex-LibertinusSerif-Regular-lf-sc-t2c.tfm \
tex-LibertinusSerif-Regular-lf-sc-t2c.vf \
tex-LibertinusSerif-Regular-lf-t1--base.tfm \
tex-LibertinusSerif-Regular-lf-t1.tfm \
tex-LibertinusSerif-Regular-lf-t1.vf \
tex-LibertinusSerif-Regular-lf-t2a.tfm \
tex-LibertinusSerif-Regular-lf-t2b.tfm \
tex-LibertinusSerif-Regular-lf-t2c.tfm \
tex-LibertinusSerif-Regular-lf-ts1--base.tfm \
tex-LibertinusSerif-Regular-lf-ts1.tfm \
tex-LibertinusSerif-Regular-lf-ts1.vf \
tex-LibertinusSerif-Regular-osf-lgr.tfm \
tex-LibertinusSerif-Regular-osf-ly1.tfm \
tex-LibertinusSerif-Regular-osf-ot1.tfm \
tex-LibertinusSerif-Regular-osf-sc-lgr.tfm \
tex-LibertinusSerif-Regular-osf-sc-ly1--base.tfm \
tex-LibertinusSerif-Regular-osf-sc-ly1.tfm \
tex-LibertinusSerif-Regular-osf-sc-ly1.vf \
tex-LibertinusSerif-Regular-osf-sc-ot1--base.tfm \
tex-LibertinusSerif-Regular-osf-sc-ot1.tfm \
tex-LibertinusSerif-Regular-osf-sc-ot1.vf \
tex-LibertinusSerif-Regular-osf-sc-t1--base.tfm \
tex-LibertinusSerif-Regular-osf-sc-t1.tfm \
tex-LibertinusSerif-Regular-osf-sc-t1.vf \
tex-LibertinusSerif-Regular-osf-sc-t2a--base.tfm \
tex-LibertinusSerif-Regular-osf-sc-t2a.tfm \
tex-LibertinusSerif-Regular-osf-sc-t2a.vf \
tex-LibertinusSerif-Regular-osf-sc-t2b--base.tfm \
tex-LibertinusSerif-Regular-osf-sc-t2b.tfm \
tex-LibertinusSerif-Regular-osf-sc-t2b.vf \
tex-LibertinusSerif-Regular-osf-sc-t2c--base.tfm \
tex-LibertinusSerif-Regular-osf-sc-t2c.tfm \
tex-LibertinusSerif-Regular-osf-sc-t2c.vf \
tex-LibertinusSerif-Regular-osf-t1--base.tfm \
tex-LibertinusSerif-Regular-osf-t1.tfm \
tex-LibertinusSerif-Regular-osf-t1.vf \
tex-LibertinusSerif-Regular-osf-t2a.tfm \
tex-LibertinusSerif-Regular-osf-t2b.tfm \
tex-LibertinusSerif-Regular-osf-t2c.tfm \
tex-LibertinusSerif-Regular-osf-ts1--base.tfm \
tex-LibertinusSerif-Regular-osf-ts1.tfm \
tex-LibertinusSerif-Regular-osf-ts1.vf \
tex-LibertinusSerif-Regular-sup-lgr.tfm \
tex-LibertinusSerif-Regular-sup-ly1.tfm \
tex-LibertinusSerif-Regular-sup-ot1.tfm \
tex-LibertinusSerif-Regular-sup-t1--base.tfm \
tex-LibertinusSerif-Regular-sup-t1.tfm \
tex-LibertinusSerif-Regular-sup-t1.vf \
tex-LibertinusSerif-Regular-sup-t2a.tfm \
tex-LibertinusSerif-Regular-sup-t2b.tfm \
tex-LibertinusSerif-Regular-sup-t2c.tfm \
tex-LibertinusSerif-Regular-tlf-lgr.tfm \
tex-LibertinusSerif-Regular-tlf-ly1.tfm \
tex-LibertinusSerif-Regular-tlf-ot1.tfm \
tex-LibertinusSerif-Regular-tlf-sc-lgr.tfm \
tex-LibertinusSerif-Regular-tlf-sc-ly1--base.tfm \
tex-LibertinusSerif-Regular-tlf-sc-ly1.tfm \
tex-LibertinusSerif-Regular-tlf-sc-ly1.vf \
tex-LibertinusSerif-Regular-tlf-sc-ot1--base.tfm \
tex-LibertinusSerif-Regular-tlf-sc-ot1.tfm \
tex-LibertinusSerif-Regular-tlf-sc-ot1.vf \
tex-LibertinusSerif-Regular-tlf-sc-t1--base.tfm \
tex-LibertinusSerif-Regular-tlf-sc-t1.tfm \
tex-LibertinusSerif-Regular-tlf-sc-t1.vf \
tex-LibertinusSerif-Regular-tlf-sc-t2a--base.tfm \
tex-LibertinusSerif-Regular-tlf-sc-t2a.tfm \
tex-LibertinusSerif-Regular-tlf-sc-t2a.vf \
tex-LibertinusSerif-Regular-tlf-sc-t2b--base.tfm \
tex-LibertinusSerif-Regular-tlf-sc-t2b.tfm \
tex-LibertinusSerif-Regular-tlf-sc-t2b.vf \
tex-LibertinusSerif-Regular-tlf-sc-t2c--base.tfm \
tex-LibertinusSerif-Regular-tlf-sc-t2c.tfm \
tex-LibertinusSerif-Regular-tlf-sc-t2c.vf \
tex-LibertinusSerif-Regular-tlf-t1--base.tfm \
tex-LibertinusSerif-Regular-tlf-t1.tfm \
tex-LibertinusSerif-Regular-tlf-t1.vf \
tex-LibertinusSerif-Regular-tlf-t2a.tfm \
tex-LibertinusSerif-Regular-tlf-t2b.tfm \
tex-LibertinusSerif-Regular-tlf-t2c.tfm \
tex-LibertinusSerif-Regular-tlf-ts1--base.tfm \
tex-LibertinusSerif-Regular-tlf-ts1.tfm \
tex-LibertinusSerif-Regular-tlf-ts1.vf \
tex-LibertinusSerif-Regular-tosf-lgr.tfm \
tex-LibertinusSerif-Regular-tosf-ly1.tfm \
tex-LibertinusSerif-Regular-tosf-ot1.tfm \
tex-LibertinusSerif-Regular-tosf-sc-lgr.tfm \
tex-LibertinusSerif-Regular-tosf-sc-ly1--base.tfm \
tex-LibertinusSerif-Regular-tosf-sc-ly1.tfm \
tex-LibertinusSerif-Regular-tosf-sc-ly1.vf \
tex-LibertinusSerif-Regular-tosf-sc-ot1--base.tfm \
tex-LibertinusSerif-Regular-tosf-sc-ot1.tfm \
tex-LibertinusSerif-Regular-tosf-sc-ot1.vf \
tex-LibertinusSerif-Regular-tosf-sc-t1--base.tfm \
tex-LibertinusSerif-Regular-tosf-sc-t1.tfm \
tex-LibertinusSerif-Regular-tosf-sc-t1.vf \
tex-LibertinusSerif-Regular-tosf-sc-t2a--base.tfm \
tex-LibertinusSerif-Regular-tosf-sc-t2a.tfm \
tex-LibertinusSerif-Regular-tosf-sc-t2a.vf \
tex-LibertinusSerif-Regular-tosf-sc-t2b--base.tfm \
tex-LibertinusSerif-Regular-tosf-sc-t2b.tfm \
tex-LibertinusSerif-Regular-tosf-sc-t2b.vf \
tex-LibertinusSerif-Regular-tosf-sc-t2c--base.tfm \
tex-LibertinusSerif-Regular-tosf-sc-t2c.tfm \
tex-LibertinusSerif-Regular-tosf-sc-t2c.vf \
tex-LibertinusSerif-Regular-tosf-t1--base.tfm \
tex-LibertinusSerif-Regular-tosf-t1.tfm \
tex-LibertinusSerif-Regular-tosf-t1.vf \
tex-LibertinusSerif-Regular-tosf-t2a.tfm \
tex-LibertinusSerif-Regular-tosf-t2b.tfm \
tex-LibertinusSerif-Regular-tosf-t2c.tfm \
tex-LibertinusSerif-Regular-tosf-ts1--base.tfm \
tex-LibertinusSerif-Regular-tosf-ts1.tfm \
tex-LibertinusSerif-Regular-tosf-ts1.vf \
tex-LibertinusSerif-Semibold-lf-lgr.tfm \
tex-LibertinusSerif-Semibold-lf-ly1.tfm \
tex-LibertinusSerif-Semibold-lf-ot1.tfm \
tex-LibertinusSerif-Semibold-lf-sc-lgr.tfm \
tex-LibertinusSerif-Semibold-lf-sc-ly1--base.tfm \
tex-LibertinusSerif-Semibold-lf-sc-ly1.tfm \
tex-LibertinusSerif-Semibold-lf-sc-ly1.vf \
tex-LibertinusSerif-Semibold-lf-sc-ot1--base.tfm \
tex-LibertinusSerif-Semibold-lf-sc-ot1.tfm \
tex-LibertinusSerif-Semibold-lf-sc-ot1.vf \
tex-LibertinusSerif-Semibold-lf-sc-t1--base.tfm \
tex-LibertinusSerif-Semibold-lf-sc-t1.tfm \
tex-LibertinusSerif-Semibold-lf-sc-t1.vf \
tex-LibertinusSerif-Semibold-lf-sc-t2a--base.tfm \
tex-LibertinusSerif-Semibold-lf-sc-t2a.tfm \
tex-LibertinusSerif-Semibold-lf-sc-t2a.vf \
tex-LibertinusSerif-Semibold-lf-sc-t2b--base.tfm \
tex-LibertinusSerif-Semibold-lf-sc-t2b.tfm \
tex-LibertinusSerif-Semibold-lf-sc-t2b.vf \
tex-LibertinusSerif-Semibold-lf-sc-t2c--base.tfm \
tex-LibertinusSerif-Semibold-lf-sc-t2c.tfm \
tex-LibertinusSerif-Semibold-lf-sc-t2c.vf \
tex-LibertinusSerif-Semibold-lf-t1--base.tfm \
tex-LibertinusSerif-Semibold-lf-t1.tfm \
tex-LibertinusSerif-Semibold-lf-t1.vf \
tex-LibertinusSerif-Semibold-lf-t2a.tfm \
tex-LibertinusSerif-Semibold-lf-t2b.tfm \
tex-LibertinusSerif-Semibold-lf-t2c.tfm \
tex-LibertinusSerif-Semibold-lf-ts1--base.tfm \
tex-LibertinusSerif-Semibold-lf-ts1.tfm \
tex-LibertinusSerif-Semibold-lf-ts1.vf \
tex-LibertinusSerif-Semibold-osf-lgr.tfm \
tex-LibertinusSerif-Semibold-osf-ly1.tfm \
tex-LibertinusSerif-Semibold-osf-ot1.tfm \
tex-LibertinusSerif-Semibold-osf-sc-lgr.tfm \
tex-LibertinusSerif-Semibold-osf-sc-ly1--base.tfm \
tex-LibertinusSerif-Semibold-osf-sc-ly1.tfm \
tex-LibertinusSerif-Semibold-osf-sc-ly1.vf \
tex-LibertinusSerif-Semibold-osf-sc-ot1--base.tfm \
tex-LibertinusSerif-Semibold-osf-sc-ot1.tfm \
tex-LibertinusSerif-Semibold-osf-sc-ot1.vf \
tex-LibertinusSerif-Semibold-osf-sc-t1--base.tfm \
tex-LibertinusSerif-Semibold-osf-sc-t1.tfm \
tex-LibertinusSerif-Semibold-osf-sc-t1.vf \
tex-LibertinusSerif-Semibold-osf-sc-t2a--base.tfm \
tex-LibertinusSerif-Semibold-osf-sc-t2a.tfm \
tex-LibertinusSerif-Semibold-osf-sc-t2a.vf \
tex-LibertinusSerif-Semibold-osf-sc-t2b--base.tfm \
tex-LibertinusSerif-Semibold-osf-sc-t2b.tfm \
tex-LibertinusSerif-Semibold-osf-sc-t2b.vf \
tex-LibertinusSerif-Semibold-osf-sc-t2c--base.tfm \
tex-LibertinusSerif-Semibold-osf-sc-t2c.tfm \
tex-LibertinusSerif-Semibold-osf-sc-t2c.vf \
tex-LibertinusSerif-Semibold-osf-t1--base.tfm \
tex-LibertinusSerif-Semibold-osf-t1.tfm \
tex-LibertinusSerif-Semibold-osf-t1.vf \
tex-LibertinusSerif-Semibold-osf-t2a.tfm \
tex-LibertinusSerif-Semibold-osf-t2b.tfm \
tex-LibertinusSerif-Semibold-osf-t2c.tfm \
tex-LibertinusSerif-Semibold-osf-ts1--base.tfm \
tex-LibertinusSerif-Semibold-osf-ts1.tfm \
tex-LibertinusSerif-Semibold-osf-ts1.vf \
tex-LibertinusSerif-Semibold-sup-lgr.tfm \
tex-LibertinusSerif-Semibold-sup-ly1.tfm \
tex-LibertinusSerif-Semibold-sup-ot1.tfm \
tex-LibertinusSerif-Semibold-sup-t1--base.tfm \
tex-LibertinusSerif-Semibold-sup-t1.tfm \
tex-LibertinusSerif-Semibold-sup-t1.vf \
tex-LibertinusSerif-Semibold-sup-t2a.tfm \
tex-LibertinusSerif-Semibold-sup-t2b.tfm \
tex-LibertinusSerif-Semibold-sup-t2c.tfm \
tex-LibertinusSerif-Semibold-tlf-lgr.tfm \
tex-LibertinusSerif-Semibold-tlf-ly1.tfm \
tex-LibertinusSerif-Semibold-tlf-ot1.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-lgr.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-ly1--base.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-ly1.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-ly1.vf \
tex-LibertinusSerif-Semibold-tlf-sc-ot1--base.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-ot1.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-ot1.vf \
tex-LibertinusSerif-Semibold-tlf-sc-t1--base.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-t1.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-t1.vf \
tex-LibertinusSerif-Semibold-tlf-sc-t2a--base.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-t2a.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-t2a.vf \
tex-LibertinusSerif-Semibold-tlf-sc-t2b--base.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-t2b.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-t2b.vf \
tex-LibertinusSerif-Semibold-tlf-sc-t2c--base.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-t2c.tfm \
tex-LibertinusSerif-Semibold-tlf-sc-t2c.vf \
tex-LibertinusSerif-Semibold-tlf-t1--base.tfm \
tex-LibertinusSerif-Semibold-tlf-t1.tfm \
tex-LibertinusSerif-Semibold-tlf-t1.vf \
tex-LibertinusSerif-Semibold-tlf-t2a.tfm \
tex-LibertinusSerif-Semibold-tlf-t2b.tfm \
tex-LibertinusSerif-Semibold-tlf-t2c.tfm \
tex-LibertinusSerif-Semibold-tlf-ts1--base.tfm \
tex-LibertinusSerif-Semibold-tlf-ts1.tfm \
tex-LibertinusSerif-Semibold-tlf-ts1.vf \
tex-LibertinusSerif-Semibold-tosf-lgr.tfm \
tex-LibertinusSerif-Semibold-tosf-ly1.tfm \
tex-LibertinusSerif-Semibold-tosf-ot1.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-lgr.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-ly1--base.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-ly1.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-ly1.vf \
tex-LibertinusSerif-Semibold-tosf-sc-ot1--base.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-ot1.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-ot1.vf \
tex-LibertinusSerif-Semibold-tosf-sc-t1--base.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-t1.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-t1.vf \
tex-LibertinusSerif-Semibold-tosf-sc-t2a--base.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-t2a.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-t2a.vf \
tex-LibertinusSerif-Semibold-tosf-sc-t2b--base.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-t2b.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-t2b.vf \
tex-LibertinusSerif-Semibold-tosf-sc-t2c--base.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-t2c.tfm \
tex-LibertinusSerif-Semibold-tosf-sc-t2c.vf \
tex-LibertinusSerif-Semibold-tosf-t1--base.tfm \
tex-LibertinusSerif-Semibold-tosf-t1.tfm \
tex-LibertinusSerif-Semibold-tosf-t1.vf \
tex-LibertinusSerif-Semibold-tosf-t2a.tfm \
tex-LibertinusSerif-Semibold-tosf-t2b.tfm \
tex-LibertinusSerif-Semibold-tosf-t2c.tfm \
tex-LibertinusSerif-Semibold-tosf-ts1--base.tfm \
tex-LibertinusSerif-Semibold-tosf-ts1.tfm \
tex-LibertinusSerif-Semibold-tosf-ts1.vf \
tex-LibertinusSerif-SemiboldItalic-lf-lgr.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-ly1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-ly1.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-ly1.vf \
tex-LibertinusSerif-SemiboldItalic-lf-ot1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-ot1.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-ot1.vf \
tex-LibertinusSerif-SemiboldItalic-lf-sc-lgr.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-ly1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-ly1.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-ly1.vf \
tex-LibertinusSerif-SemiboldItalic-lf-sc-ot1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-ot1.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-ot1.vf \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t1.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t1.vf \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t2a--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t2a.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t2a.vf \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t2b--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t2b.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t2b.vf \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t2c--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t2c.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-sc-t2c.vf \
tex-LibertinusSerif-SemiboldItalic-lf-t1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-t1.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-t1.vf \
tex-LibertinusSerif-SemiboldItalic-lf-t2a--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-t2a.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-t2a.vf \
tex-LibertinusSerif-SemiboldItalic-lf-t2b--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-t2b.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-t2b.vf \
tex-LibertinusSerif-SemiboldItalic-lf-t2c--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-t2c.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-t2c.vf \
tex-LibertinusSerif-SemiboldItalic-lf-ts1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-ts1.tfm \
tex-LibertinusSerif-SemiboldItalic-lf-ts1.vf \
tex-LibertinusSerif-SemiboldItalic-osf-lgr.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-ly1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-ly1.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-ly1.vf \
tex-LibertinusSerif-SemiboldItalic-osf-ot1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-ot1.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-ot1.vf \
tex-LibertinusSerif-SemiboldItalic-osf-sc-lgr.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-ly1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-ly1.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-ly1.vf \
tex-LibertinusSerif-SemiboldItalic-osf-sc-ot1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-ot1.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-ot1.vf \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t1.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t1.vf \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t2a--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t2a.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t2a.vf \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t2b--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t2b.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t2b.vf \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t2c--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t2c.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-sc-t2c.vf \
tex-LibertinusSerif-SemiboldItalic-osf-t1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-t1.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-t1.vf \
tex-LibertinusSerif-SemiboldItalic-osf-t2a--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-t2a.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-t2a.vf \
tex-LibertinusSerif-SemiboldItalic-osf-t2b--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-t2b.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-t2b.vf \
tex-LibertinusSerif-SemiboldItalic-osf-t2c--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-t2c.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-t2c.vf \
tex-LibertinusSerif-SemiboldItalic-osf-ts1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-ts1.tfm \
tex-LibertinusSerif-SemiboldItalic-osf-ts1.vf \
tex-LibertinusSerif-SemiboldItalic-sup-lgr.tfm \
tex-LibertinusSerif-SemiboldItalic-sup-ly1.tfm \
tex-LibertinusSerif-SemiboldItalic-sup-ot1.tfm \
tex-LibertinusSerif-SemiboldItalic-sup-t1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-sup-t1.tfm \
tex-LibertinusSerif-SemiboldItalic-sup-t1.vf \
tex-LibertinusSerif-SemiboldItalic-sup-t2a.tfm \
tex-LibertinusSerif-SemiboldItalic-sup-t2b.tfm \
tex-LibertinusSerif-SemiboldItalic-sup-t2c.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-lgr.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-ly1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-ly1.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-ly1.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-ot1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-ot1.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-ot1.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-lgr.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-ly1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-ly1.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-ly1.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-ot1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-ot1.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-ot1.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t1.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t1.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t2a--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t2a.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t2a.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t2b--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t2b.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t2b.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t2c--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t2c.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-sc-t2c.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-t1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-t1.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-t1.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-t2a--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-t2a.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-t2a.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-t2b--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-t2b.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-t2b.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-t2c--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-t2c.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-t2c.vf \
tex-LibertinusSerif-SemiboldItalic-tlf-ts1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-ts1.tfm \
tex-LibertinusSerif-SemiboldItalic-tlf-ts1.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-lgr.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-ly1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-ly1.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-ly1.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-ot1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-ot1.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-ot1.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-lgr.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-ly1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-ly1.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-ly1.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-ot1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-ot1.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-ot1.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t1.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t1.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t2a--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t2a.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t2a.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t2b--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t2b.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t2b.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t2c--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t2c.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-sc-t2c.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-t1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-t1.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-t1.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-t2a--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-t2a.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-t2a.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-t2b--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-t2b.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-t2b.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-t2c--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-t2c.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-t2c.vf \
tex-LibertinusSerif-SemiboldItalic-tosf-ts1--base.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-ts1.tfm \
tex-LibertinusSerif-SemiboldItalic-tosf-ts1.vf \
tex-LibertinusSerifDisplay-Regular-lf-lgr--base.tfm \
tex-LibertinusSerifDisplay-Regular-lf-lgr.tfm \
tex-LibertinusSerifDisplay-Regular-lf-lgr.vf \
tex-LibertinusSerifDisplay-Regular-lf-ly1--base.tfm \
tex-LibertinusSerifDisplay-Regular-lf-ly1.tfm \
tex-LibertinusSerifDisplay-Regular-lf-ly1.vf \
tex-LibertinusSerifDisplay-Regular-lf-ot1.tfm \
tex-LibertinusSerifDisplay-Regular-lf-t1--base.tfm \
tex-LibertinusSerifDisplay-Regular-lf-t1.tfm \
tex-LibertinusSerifDisplay-Regular-lf-t1.vf \
tex-LibertinusSerifDisplay-Regular-lf-t2a.tfm \
tex-LibertinusSerifDisplay-Regular-lf-t2b.tfm \
tex-LibertinusSerifDisplay-Regular-lf-t2c.tfm \
tex-LibertinusSerifDisplay-Regular-lf-ts1--base.tfm \
tex-LibertinusSerifDisplay-Regular-lf-ts1.tfm \
tex-LibertinusSerifDisplay-Regular-lf-ts1.vf \
tex-LibertinusSerifDisplay-Regular-osf-lgr--base.tfm \
tex-LibertinusSerifDisplay-Regular-osf-lgr.tfm \
tex-LibertinusSerifDisplay-Regular-osf-lgr.vf \
tex-LibertinusSerifDisplay-Regular-osf-ly1--base.tfm \
tex-LibertinusSerifDisplay-Regular-osf-ly1.tfm \
tex-LibertinusSerifDisplay-Regular-osf-ly1.vf \
tex-LibertinusSerifDisplay-Regular-osf-ot1.tfm \
tex-LibertinusSerifDisplay-Regular-osf-t1--base.tfm \
tex-LibertinusSerifDisplay-Regular-osf-t1.tfm \
tex-LibertinusSerifDisplay-Regular-osf-t1.vf \
tex-LibertinusSerifDisplay-Regular-osf-t2a.tfm \
tex-LibertinusSerifDisplay-Regular-osf-t2b.tfm \
tex-LibertinusSerifDisplay-Regular-osf-t2c.tfm \
tex-LibertinusSerifDisplay-Regular-osf-ts1--base.tfm \
tex-LibertinusSerifDisplay-Regular-osf-ts1.tfm \
tex-LibertinusSerifDisplay-Regular-osf-ts1.vf \
tex-LibertinusSerifDisplay-Regular-sup-lgr--base.tfm \
tex-LibertinusSerifDisplay-Regular-sup-lgr.tfm \
tex-LibertinusSerifDisplay-Regular-sup-lgr.vf \
tex-LibertinusSerifDisplay-Regular-sup-ly1--base.tfm \
tex-LibertinusSerifDisplay-Regular-sup-ly1.tfm \
tex-LibertinusSerifDisplay-Regular-sup-ly1.vf \
tex-LibertinusSerifDisplay-Regular-sup-ot1.tfm \
tex-LibertinusSerifDisplay-Regular-sup-t1--base.tfm \
tex-LibertinusSerifDisplay-Regular-sup-t1.tfm \
tex-LibertinusSerifDisplay-Regular-sup-t1.vf \
tex-LibertinusSerifDisplay-Regular-sup-t2a.tfm \
tex-LibertinusSerifDisplay-Regular-sup-t2b.tfm \
tex-LibertinusSerifDisplay-Regular-sup-t2c.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-lgr--base.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-lgr.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-lgr.vf \
tex-LibertinusSerifDisplay-Regular-tlf-ly1--base.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-ly1.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-ly1.vf \
tex-LibertinusSerifDisplay-Regular-tlf-ot1.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-t1--base.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-t1.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-t1.vf \
tex-LibertinusSerifDisplay-Regular-tlf-t2a.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-t2b.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-t2c.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-ts1--base.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-ts1.tfm \
tex-LibertinusSerifDisplay-Regular-tlf-ts1.vf \
tex-LibertinusSerifDisplay-Regular-tosf-lgr--base.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-lgr.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-lgr.vf \
tex-LibertinusSerifDisplay-Regular-tosf-ly1--base.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-ly1.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-ly1.vf \
tex-LibertinusSerifDisplay-Regular-tosf-ot1.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-t1--base.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-t1.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-t1.vf \
tex-LibertinusSerifDisplay-Regular-tosf-t2a.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-t2b.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-t2c.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-ts1--base.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-ts1.tfm \
tex-LibertinusSerifDisplay-Regular-tosf-ts1.vf \
tex-LibertinusSerifInitials-Regular-tlf-lgr--base.tfm \
tex-LibertinusSerifInitials-Regular-tlf-lgr.tfm \
tex-LibertinusSerifInitials-Regular-tlf-lgr.vf \
tex-LibertinusSerifInitials-Regular-tlf-ly1--base.tfm \
tex-LibertinusSerifInitials-Regular-tlf-ly1.tfm \
tex-LibertinusSerifInitials-Regular-tlf-ly1.vf \
tex-LibertinusSerifInitials-Regular-tlf-ot1.tfm \
tex-LibertinusSerifInitials-Regular-tlf-t1--base.tfm \
tex-LibertinusSerifInitials-Regular-tlf-t1.tfm \
tex-LibertinusSerifInitials-Regular-tlf-t1.vf \
tex-LibertinusSerifInitials-Regular-tlf-t2a.tfm \
tex-LibertinusSerifInitials-Regular-tlf-t2b.tfm \
tex-LibertinusSerifInitials-Regular-tlf-t2c.tfm \
tex-LibertinusSerifInitials-Regular-tlf-ts1.tfm \
tex-LibertinusSerifInitials-Regular-tlf-ts1.vf \
tex-OT1LibertinusMono-TLF.fd \
tex-OT1LibertinusSans-LF.fd \
tex-OT1LibertinusSans-OsF.fd \
tex-OT1LibertinusSans-Sup.fd \
tex-OT1LibertinusSans-TLF.fd \
tex-OT1LibertinusSans-TOsF.fd \
tex-OT1LibertinusSerif-LF.fd \
tex-OT1LibertinusSerif-OsF.fd \
tex-OT1LibertinusSerif-Sup.fd \
tex-OT1LibertinusSerif-TLF.fd \
tex-OT1LibertinusSerif-TOsF.fd \
tex-OT1LibertinusSerifDisplay-LF.fd \
tex-OT1LibertinusSerifDisplay-OsF.fd \
tex-OT1LibertinusSerifDisplay-Sup.fd \
tex-OT1LibertinusSerifDisplay-TLF.fd \
tex-OT1LibertinusSerifDisplay-TOsF.fd \
tex-OT1LibertinusSerifInitials-TLF.fd \
tex-T1LibertinusMono-TLF.fd \
tex-T1LibertinusSans-LF.fd \
tex-T1LibertinusSans-OsF.fd \
tex-T1LibertinusSans-Sup.fd \
tex-T1LibertinusSans-TLF.fd \
tex-T1LibertinusSans-TOsF.fd \
tex-T1LibertinusSerif-LF.fd \
tex-T1LibertinusSerif-OsF.fd \
tex-T1LibertinusSerif-Sup.fd \
tex-T1LibertinusSerif-TLF.fd \
tex-T1LibertinusSerif-TOsF.fd \
tex-T1LibertinusSerifDisplay-LF.fd \
tex-T1LibertinusSerifDisplay-OsF.fd \
tex-T1LibertinusSerifDisplay-Sup.fd \
tex-T1LibertinusSerifDisplay-TLF.fd \
tex-T1LibertinusSerifDisplay-TOsF.fd \
tex-T1LibertinusSerifInitials-TLF.fd \
tex-T2ALibertinusSans-LF.fd \
tex-T2ALibertinusSans-OsF.fd \
tex-T2ALibertinusSans-Sup.fd \
tex-T2ALibertinusSans-TLF.fd \
tex-T2ALibertinusSans-TOsF.fd \
tex-T2ALibertinusSerif-LF.fd \
tex-T2ALibertinusSerif-OsF.fd \
tex-T2ALibertinusSerif-Sup.fd \
tex-T2ALibertinusSerif-TLF.fd \
tex-T2ALibertinusSerif-TOsF.fd \
tex-T2ALibertinusSerifDisplay-LF.fd \
tex-T2ALibertinusSerifDisplay-OsF.fd \
tex-T2ALibertinusSerifDisplay-Sup.fd \
tex-T2ALibertinusSerifDisplay-TLF.fd \
tex-T2ALibertinusSerifDisplay-TOsF.fd \
tex-T2ALibertinusSerifInitials-TLF.fd \
tex-T2BLibertinusSans-LF.fd \
tex-T2BLibertinusSans-OsF.fd \
tex-T2BLibertinusSans-Sup.fd \
tex-T2BLibertinusSans-TLF.fd \
tex-T2BLibertinusSans-TOsF.fd \
tex-T2BLibertinusSerif-LF.fd \
tex-T2BLibertinusSerif-OsF.fd \
tex-T2BLibertinusSerif-Sup.fd \
tex-T2BLibertinusSerif-TLF.fd \
tex-T2BLibertinusSerif-TOsF.fd \
tex-T2BLibertinusSerifDisplay-LF.fd \
tex-T2BLibertinusSerifDisplay-OsF.fd \
tex-T2BLibertinusSerifDisplay-Sup.fd \
tex-T2BLibertinusSerifDisplay-TLF.fd \
tex-T2BLibertinusSerifDisplay-TOsF.fd \
tex-T2BLibertinusSerifInitials-TLF.fd \
tex-T2CLibertinusSans-LF.fd \
tex-T2CLibertinusSans-OsF.fd \
tex-T2CLibertinusSans-Sup.fd \
tex-T2CLibertinusSans-TLF.fd \
tex-T2CLibertinusSans-TOsF.fd \
tex-T2CLibertinusSerif-LF.fd \
tex-T2CLibertinusSerif-OsF.fd \
tex-T2CLibertinusSerif-Sup.fd \
tex-T2CLibertinusSerif-TLF.fd \
tex-T2CLibertinusSerif-TOsF.fd \
tex-T2CLibertinusSerifDisplay-LF.fd \
tex-T2CLibertinusSerifDisplay-OsF.fd \
tex-T2CLibertinusSerifDisplay-Sup.fd \
tex-T2CLibertinusSerifDisplay-TLF.fd \
tex-T2CLibertinusSerifDisplay-TOsF.fd \
tex-T2CLibertinusSerifInitials-TLF.fd \
tex-TS1LibertinusMono-TLF.fd \
tex-TS1LibertinusSans-LF.fd \
tex-TS1LibertinusSans-OsF.fd \
tex-TS1LibertinusSans-TLF.fd \
tex-TS1LibertinusSans-TOsF.fd \
tex-TS1LibertinusSerif-LF.fd \
tex-TS1LibertinusSerif-OsF.fd \
tex-TS1LibertinusSerif-TLF.fd \
tex-TS1LibertinusSerif-TOsF.fd \
tex-TS1LibertinusSerifDisplay-LF.fd \
tex-TS1LibertinusSerifDisplay-OsF.fd \
tex-TS1LibertinusSerifDisplay-TLF.fd \
tex-TS1LibertinusSerifDisplay-TOsF.fd \
tex-TS1LibertinusSerifInitials-TLF.fd \
tex-lbts-2dnbtf.enc \
tex-lbts-2fcdyd.enc \
tex-lbts-2ojay3.enc \
tex-lbts-2tlncs.enc \
tex-lbts-2u3q4p.enc \
tex-lbts-2vfnnw.enc \
tex-lbts-2y652m.enc \
tex-lbts-2yds7f.enc \
tex-lbts-35favc.enc \
tex-lbts-36t55i.enc \
tex-lbts-37i5h5.enc \
tex-lbts-3d54jy.enc \
tex-lbts-3j5xjf.enc \
tex-lbts-3jolak.enc \
tex-lbts-3kirmv.enc \
tex-lbts-3kmpct.enc \
tex-lbts-3m644f.enc \
tex-lbts-3qta4x.enc \
tex-lbts-3ssu23.enc \
tex-lbts-3un72f.enc \
tex-lbts-3vqmyw.enc \
tex-lbts-3yrfnt.enc \
tex-lbts-4crdwc.enc \
tex-lbts-4d42wm.enc \
tex-lbts-4gaomz.enc \
tex-lbts-4hcz3c.enc \
tex-lbts-4mrx7q.enc \
tex-lbts-4q6kep.enc \
tex-lbts-4sdcjk.enc \
tex-lbts-4uwsiq.enc \
tex-lbts-4wbnoe.enc \
tex-lbts-4xoyfg.enc \
tex-lbts-4zqa2g.enc \
tex-lbts-57bjkg.enc \
tex-lbts-5acxeg.enc \
tex-lbts-5cy3nd.enc \
tex-lbts-5h7qbk.enc \
tex-lbts-5jnf2k.enc \
tex-lbts-5xa72p.enc \
tex-lbts-63ftwl.enc \
tex-lbts-674lrv.enc \
tex-lbts-6caxtj.enc \
tex-lbts-6ewxxu.enc \
tex-lbts-6gletg.enc \
tex-lbts-6h6srf.enc \
tex-lbts-6hdezz.enc \
tex-lbts-6l4fbc.enc \
tex-lbts-6lk76t.enc \
tex-lbts-6wmeer.enc \
tex-lbts-72youc.enc \
tex-lbts-75t36g.enc \
tex-lbts-76xdns.enc \
tex-lbts-77jah4.enc \
tex-lbts-77t54r.enc \
tex-lbts-7aen2t.enc \
tex-lbts-7bccbz.enc \
tex-lbts-7d2mhk.enc \
tex-lbts-7hmj2z.enc \
tex-lbts-7lwjes.enc \
tex-lbts-7mm7zy.enc \
tex-lbts-7oodvn.enc \
tex-lbts-7vsebg.enc \
tex-lbts-7yclm6.enc \
tex-lbts-a3f66t.enc \
tex-lbts-aidrin.enc \
tex-lbts-arfinu.enc \
tex-lbts-at32ur.enc \
tex-lbts-avlujb.enc \
tex-lbts-avlydd.enc \
tex-lbts-ayzaac.enc \
tex-lbts-b4oezt.enc \
tex-lbts-b5fzbp.enc \
tex-lbts-b7xqh5.enc \
tex-lbts-bgegdt.enc \
tex-lbts-bjbyqz.enc \
tex-lbts-bn2i3n.enc \
tex-lbts-bvhzzu.enc \
tex-lbts-bxwrog.enc \
tex-lbts-c3bv3f.enc \
tex-lbts-c4i7ev.enc \
tex-lbts-c4nx3a.enc \
tex-lbts-c6vmpn.enc \
tex-lbts-c7grr2.enc \
tex-lbts-calslh.enc \
tex-lbts-cb34qf.enc \
tex-lbts-cefqwa.enc \
tex-lbts-ckbdgg.enc \
tex-lbts-ckenly.enc \
tex-lbts-cpinjp.enc \
tex-lbts-cslza4.enc \
tex-lbts-cykel7.enc \
tex-lbts-d2pxsd.enc \
tex-lbts-d37b7c.enc \
tex-lbts-dgc4ye.enc \
tex-lbts-dhtsou.enc \
tex-lbts-dkknmm.enc \
tex-lbts-dn22no.enc \
tex-lbts-dsfsze.enc \
tex-lbts-dzyoth.enc \
tex-lbts-e35iwk.enc \
tex-lbts-e5lu6a.enc \
tex-lbts-ecxtyf.enc \
tex-lbts-ed5ai4.enc \
tex-lbts-eejjqw.enc \
tex-lbts-ep5pfz.enc \
tex-lbts-epdddg.enc \
tex-lbts-ercrba.enc \
tex-lbts-erdvwd.enc \
tex-lbts-esgnlu.enc \
tex-lbts-et5tau.enc \
tex-lbts-exfok6.enc \
tex-lbts-f2r76x.enc \
tex-lbts-f3pcwn.enc \
tex-lbts-fili27.enc \
tex-lbts-fmdp7p.enc \
tex-lbts-fmriqv.enc \
tex-lbts-fph2zj.enc \
tex-lbts-fszxp3.enc \
tex-lbts-fujx3h.enc \
tex-lbts-fuyass.enc \
tex-lbts-fy3had.enc \
tex-lbts-g3dkmi.enc \
tex-lbts-g6etas.enc \
tex-lbts-gazpeh.enc \
tex-lbts-gc5t3w.enc \
tex-lbts-gekugp.enc \
tex-lbts-gh4gmp.enc \
tex-lbts-goqnek.enc \
tex-lbts-gp3nhm.enc \
tex-lbts-gq67ga.enc \
tex-lbts-gr4hit.enc \
tex-lbts-gz554e.enc \
tex-lbts-gz7arp.enc \
tex-lbts-hahfqq.enc \
tex-lbts-hboyu3.enc \
tex-lbts-hej6xm.enc \
tex-lbts-hhbt6z.enc \
tex-lbts-hhmpft.enc \
tex-lbts-hjeuwr.enc \
tex-lbts-hrrrjq.enc \
tex-lbts-hvvyjb.enc \
tex-lbts-hxvdny.enc \
tex-lbts-hzjkgg.enc \
tex-lbts-i52ngl.enc \
tex-lbts-iadd5v.enc \
tex-lbts-iaq24h.enc \
tex-lbts-ibb6ig.enc \
tex-lbts-icmtyb.enc \
tex-lbts-ighl2q.enc \
tex-lbts-igmfoi.enc \
tex-lbts-ihsp6n.enc \
tex-lbts-iknsvo.enc \
tex-lbts-inpbes.enc \
tex-lbts-ipd343.enc \
tex-lbts-is673m.enc \
tex-lbts-iv4zj2.enc \
tex-lbts-j6sgbi.enc \
tex-lbts-jb5pke.enc \
tex-lbts-jdjwkh.enc \
tex-lbts-jfamas.enc \
tex-lbts-jrenuz.enc \
tex-lbts-jwzfsl.enc \
tex-lbts-k62zaj.enc \
tex-lbts-kbhblx.enc \
tex-lbts-kehxxc.enc \
tex-lbts-koaj57.enc \
tex-lbts-komy7m.enc \
tex-lbts-kq3xmd.enc \
tex-lbts-kwkowq.enc \
tex-lbts-l5raak.enc \
tex-lbts-l5ujiv.enc \
tex-lbts-l5vej2.enc \
tex-lbts-l6vzgi.enc \
tex-lbts-l74upk.enc \
tex-lbts-laenbp.enc \
tex-lbts-lafzha.enc \
tex-lbts-lhntva.enc \
tex-lbts-lkanbr.enc \
tex-lbts-llns2d.enc \
tex-lbts-llzec3.enc \
tex-lbts-lsubum.enc \
tex-lbts-lwzthx.enc \
tex-lbts-lyzgu3.enc \
tex-lbts-lzae2z.enc \
tex-lbts-lzywtf.enc \
tex-lbts-m254rf.enc \
tex-lbts-m2klan.enc \
tex-lbts-m3c2oj.enc \
tex-lbts-m3l6fs.enc \
tex-lbts-m5c6xi.enc \
tex-lbts-m7sqdm.enc \
tex-lbts-mbfmc4.enc \
tex-lbts-mfadfl.enc \
tex-lbts-mi54ls.enc \
tex-lbts-mll6fo.enc \
tex-lbts-mlwm27.enc \
tex-lbts-mmgovh.enc \
tex-lbts-mphtgh.enc \
tex-lbts-mrbizy.enc \
tex-lbts-mvzwgg.enc \
tex-lbts-mxiee2.enc \
tex-lbts-mzxlpf.enc \
tex-lbts-n3cifc.enc \
tex-lbts-n3dtgz.enc \
tex-lbts-n4gj6t.enc \
tex-lbts-n4tewx.enc \
tex-lbts-nl47lc.enc \
tex-lbts-nufysp.enc \
tex-lbts-nv3oiw.enc \
tex-lbts-o7mh5o.enc \
tex-lbts-oaaihm.enc \
tex-lbts-obkmrl.enc \
tex-lbts-obzz72.enc \
tex-lbts-of47id.enc \
tex-lbts-of4nbw.enc \
tex-lbts-olw3tj.enc \
tex-lbts-onayya.enc \
tex-lbts-opzo24.enc \
tex-lbts-ork5hb.enc \
tex-lbts-orvmfm.enc \
tex-lbts-osdvzf.enc \
tex-lbts-oxank3.enc \
tex-lbts-p5b3to.enc \
tex-lbts-p7snj6.enc \
tex-lbts-pa7fun.enc \
tex-lbts-pag3gg.enc \
tex-lbts-pb7os7.enc \
tex-lbts-pdot6l.enc \
tex-lbts-peeabe.enc \
tex-lbts-pkzsom.enc \
tex-lbts-poicuj.enc \
tex-lbts-ponsko.enc \
tex-lbts-ppaygs.enc \
tex-lbts-pquqdo.enc \
tex-lbts-ptnx64.enc \
tex-lbts-pydski.enc \
tex-lbts-q2cvbs.enc \
tex-lbts-q2ibpc.enc \
tex-lbts-q4imkx.enc \
tex-lbts-q4q2yp.enc \
tex-lbts-qcfvgl.enc \
tex-lbts-qe2yqv.enc \
tex-lbts-qpph5c.enc \
tex-lbts-qqnp2h.enc \
tex-lbts-qsv3bx.enc \
tex-lbts-quwwcn.enc \
tex-lbts-qylzkl.enc \
tex-lbts-qzwhi6.enc \
tex-lbts-r37ntu.enc \
tex-lbts-r4goj2.enc \
tex-lbts-r7yss2.enc \
tex-lbts-rcarnw.enc \
tex-lbts-rchowm.enc \
tex-lbts-rfuadt.enc \
tex-lbts-ridgvo.enc \
tex-lbts-rlktsf.enc \
tex-lbts-rpeiua.enc \
tex-lbts-rqhkdi.enc \
tex-lbts-rtitj6.enc \
tex-lbts-rv4ogi.enc \
tex-lbts-sceraq.enc \
tex-lbts-segm3u.enc \
tex-lbts-sewfus.enc \
tex-lbts-sfissr.enc \
tex-lbts-sihybe.enc \
tex-lbts-sjlxxx.enc \
tex-lbts-slsqbu.enc \
tex-lbts-snijqp.enc \
tex-lbts-sppvmf.enc \
tex-lbts-srwzhm.enc \
tex-lbts-st5lk5.enc \
tex-lbts-sut3w7.enc \
tex-lbts-szn4yf.enc \
tex-lbts-szwnvb.enc \
tex-lbts-tevnlg.enc \
tex-lbts-tll2u3.enc \
tex-lbts-trmgk4.enc \
tex-lbts-trxlme.enc \
tex-lbts-tzl7op.enc \
tex-lbts-u2zr7g.enc \
tex-lbts-u7nqae.enc \
tex-lbts-ucipzb.enc \
tex-lbts-ucscsg.enc \
tex-lbts-ugujza.enc \
tex-lbts-uhqgc3.enc \
tex-lbts-uhwxqu.enc \
tex-lbts-uoecuf.enc \
tex-lbts-usfuuy.enc \
tex-lbts-usl52j.enc \
tex-lbts-usz5ut.enc \
tex-lbts-utifxg.enc \
tex-lbts-uwmf7x.enc \
tex-lbts-uxbjn5.enc \
tex-lbts-uxf4m5.enc \
tex-lbts-v5z4kv.enc \
tex-lbts-vafbri.enc \
tex-lbts-vejg7h.enc \
tex-lbts-vftr22.enc \
tex-lbts-vgw5na.enc \
tex-lbts-vhmker.enc \
tex-lbts-vizicw.enc \
tex-lbts-vjxogo.enc \
tex-lbts-vkm6ln.enc \
tex-lbts-vmhi4g.enc \
tex-lbts-vmjjgq.enc \
tex-lbts-vtz4pu.enc \
tex-lbts-vu5j2r.enc \
tex-lbts-vvzoei.enc \
tex-lbts-w5ro75.enc \
tex-lbts-waqoej.enc \
tex-lbts-wm6att.enc \
tex-lbts-wogi6j.enc \
tex-lbts-wozmdw.enc \
tex-lbts-wrg6fm.enc \
tex-lbts-x7beke.enc \
tex-lbts-xaezkf.enc \
tex-lbts-xfy7gm.enc \
tex-lbts-xh3iko.enc \
tex-lbts-xhfw3j.enc \
tex-lbts-xjb3td.enc \
tex-lbts-xpehld.enc \
tex-lbts-xrj6hp.enc \
tex-lbts-ya3yeu.enc \
tex-lbts-ya7mbv.enc \
tex-lbts-yaf6wf.enc \
tex-lbts-yahecb.enc \
tex-lbts-ygr64v.enc \
tex-lbts-yki2t7.enc \
tex-lbts-ynfuvy.enc \
tex-lbts-ysaokq.enc \
tex-lbts-yt5vb5.enc \
tex-lbts-yuwgqp.enc \
tex-lbts-yzuq4p.enc \
tex-lbts-z6ew44.enc \
tex-lbts-z6nnva.enc \
tex-lbts-zh5q6t.enc \
tex-lbts-zjhiql.enc \
tex-lbts-znslmj.enc \
tex-lbts-zpwads.enc \
tex-lbts-zqzvht.enc \
tex-libertinus-type1.sty \
tex-libertinus.map \
texlive-libertinus-type1"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontaxes.sty \
tex-fontenc.sty \
tex-ifluatex.sty \
tex-ifxetex.sty \
tex-textcomp.sty \
tex-updmap.cfg \
tex-xkeyval.sty \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-libertinus-type1-fonts \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
