SUMMARY = "Python 3 bindings for libprelude"
DESCRIPTION = "Python 3 bindings for libprelude generated by SWIG."
LICENSE = "LGPL-2.1-only & LGPL-2.1-or-later"

PV = "5.2.0"

RPM_NAME = "python3-libprelude-5.2.0-2.16.aarch64.rpm"
RPM_HASH = "aad816d352c618ac652530b5ab57cdcfcb6315f9aac62358a1351fa676bf14514b624c75906de5fd3dd8096fc1ad4a018ba7a8e45352c22ef5abd3b059227a78"

RPROVIDES:${PN} += "python3-libprelude \
python3.11dist-prelude \
python3dist-prelude"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1 \
libc.so.6 \
libgcc-s.so.1 \
libprelude.so.28 \
libprelude28 \
libpreludecpp.so.12 \
libstdc++.so.6 \
python-abi"

inherit rpm
