SUMMARY = "Helper for correctly compacting PDF files created by TeX"
DESCRIPTION = "This tool helps compacting PDF files generated by the TeX \
typesetting system by extracting meta data like page mode and named \
destinations (link targets) and saving them in a PDFmark file. The \
PDFmark file can then be used by ghostscript when processing the \
TeX-generated PDF to make sure that the final output contains correct \
page mode and link targets. Such post-processing of TeX-generated PDF \
output is often useful to reduce the size of the final PDF document, \
e.g. by removing duplicate font sets."
LICENSE = "GPL-3.0-or-later"

PV = "1.1.1"

RPM_NAME = "extractpdfmark-1.1.1-1.3.aarch64.rpm"
RPM_HASH = "6566c830f9d1a53034832b9bccd342127672e1d36e753cd0b3391ad018524ba9ac1af86ba9bea7e7e1ab9265dad418d9107fe1c2341464f563ad28af113cbbe7"

RPROVIDES:${PN} += "extractpdfmark \
extractpdfmark(aarch-64)"

RDEPENDS:${PN} += "ld-linux-aarch64.so.1()(64bit) \
ld-linux-aarch64.so.1(GLIBC_2.17)(64bit) \
libc.so.6(GLIBC_2.34)(64bit) \
libgcc_s.so.1()(64bit) \
libgcc_s.so.1(GCC_3.0)(64bit) \
libgcc_s.so.1(GCC_3.3.1)(64bit) \
libpoppler-cpp.so.0()(64bit) \
libstdc++.so.6()(64bit) \
libstdc++.so.6(CXXABI_1.3)(64bit) \
libstdc++.so.6(GLIBCXX_3.4)(64bit) \
libstdc++.so.6(GLIBCXX_3.4.11)(64bit) \
libstdc++.so.6(GLIBCXX_3.4.14)(64bit) \
libstdc++.so.6(GLIBCXX_3.4.20)(64bit) \
libstdc++.so.6(GLIBCXX_3.4.21)(64bit) \
libstdc++.so.6(GLIBCXX_3.4.26)(64bit) \
libstdc++.so.6(GLIBCXX_3.4.9)(64bit)"

inherit rpm
