SUMMARY = "Cormorant Garamond family of fonts"
DESCRIPTION = "This package provides LaTeX, pdfLaTeX, XeLaTeX and LuaLaTeX \
support for the Cormorant Garamond family of fonts, designed by \
Christian Thalman of Catharsis Fonts. The family includes \
light, regular, medium, semi-bold, and bold weights, with \
italics."
LICENSE = "OFL-1.1"

PV = "2023.204.3.601svn64411"

RPM_NAME = "texlive-cormorantgaramond-2023.204.3.601svn64411-54.1.noarch.rpm"
RPM_HASH = "7486797b10078b5863f2f8a434baeaa37c5e1b63e99c728a76c81fd4d057c5e52a75870f77d2ec32d53d47a440e5b2f095753af22c047b31ffd6aaa707af1a10"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-CormorantGaramond-Bold-inf-ly1.tfm \
tex-CormorantGaramond-Bold-inf-ot1.tfm \
tex-CormorantGaramond-Bold-inf-t1--base.tfm \
tex-CormorantGaramond-Bold-inf-t1.tfm \
tex-CormorantGaramond-Bold-inf-t1.vf \
tex-CormorantGaramond-Bold-inf-t2a.tfm \
tex-CormorantGaramond-Bold-inf-t2b.tfm \
tex-CormorantGaramond-Bold-inf-t2c.tfm \
tex-CormorantGaramond-Bold-lf-ly1.tfm \
tex-CormorantGaramond-Bold-lf-ot1.tfm \
tex-CormorantGaramond-Bold-lf-sc-ly1--base.tfm \
tex-CormorantGaramond-Bold-lf-sc-ly1.tfm \
tex-CormorantGaramond-Bold-lf-sc-ly1.vf \
tex-CormorantGaramond-Bold-lf-sc-ot1--base.tfm \
tex-CormorantGaramond-Bold-lf-sc-ot1.tfm \
tex-CormorantGaramond-Bold-lf-sc-ot1.vf \
tex-CormorantGaramond-Bold-lf-sc-t1--base.tfm \
tex-CormorantGaramond-Bold-lf-sc-t1.tfm \
tex-CormorantGaramond-Bold-lf-sc-t1.vf \
tex-CormorantGaramond-Bold-lf-sc-t2a.tfm \
tex-CormorantGaramond-Bold-lf-sc-t2b.tfm \
tex-CormorantGaramond-Bold-lf-sc-t2c.tfm \
tex-CormorantGaramond-Bold-lf-t1--base.tfm \
tex-CormorantGaramond-Bold-lf-t1.tfm \
tex-CormorantGaramond-Bold-lf-t1.vf \
tex-CormorantGaramond-Bold-lf-t2a.tfm \
tex-CormorantGaramond-Bold-lf-t2b.tfm \
tex-CormorantGaramond-Bold-lf-t2c.tfm \
tex-CormorantGaramond-Bold-lf-ts1--base.tfm \
tex-CormorantGaramond-Bold-lf-ts1.tfm \
tex-CormorantGaramond-Bold-lf-ts1.vf \
tex-CormorantGaramond-Bold-osf-ly1.tfm \
tex-CormorantGaramond-Bold-osf-ot1.tfm \
tex-CormorantGaramond-Bold-osf-sc-ly1--base.tfm \
tex-CormorantGaramond-Bold-osf-sc-ly1.tfm \
tex-CormorantGaramond-Bold-osf-sc-ly1.vf \
tex-CormorantGaramond-Bold-osf-sc-ot1--base.tfm \
tex-CormorantGaramond-Bold-osf-sc-ot1.tfm \
tex-CormorantGaramond-Bold-osf-sc-ot1.vf \
tex-CormorantGaramond-Bold-osf-sc-t1--base.tfm \
tex-CormorantGaramond-Bold-osf-sc-t1.tfm \
tex-CormorantGaramond-Bold-osf-sc-t1.vf \
tex-CormorantGaramond-Bold-osf-sc-t2a.tfm \
tex-CormorantGaramond-Bold-osf-sc-t2b.tfm \
tex-CormorantGaramond-Bold-osf-sc-t2c.tfm \
tex-CormorantGaramond-Bold-osf-t1--base.tfm \
tex-CormorantGaramond-Bold-osf-t1.tfm \
tex-CormorantGaramond-Bold-osf-t1.vf \
tex-CormorantGaramond-Bold-osf-t2a.tfm \
tex-CormorantGaramond-Bold-osf-t2b.tfm \
tex-CormorantGaramond-Bold-osf-t2c.tfm \
tex-CormorantGaramond-Bold-osf-ts1--base.tfm \
tex-CormorantGaramond-Bold-osf-ts1.tfm \
tex-CormorantGaramond-Bold-osf-ts1.vf \
tex-CormorantGaramond-Bold-sup-ly1.tfm \
tex-CormorantGaramond-Bold-sup-ot1.tfm \
tex-CormorantGaramond-Bold-sup-t1--base.tfm \
tex-CormorantGaramond-Bold-sup-t1.tfm \
tex-CormorantGaramond-Bold-sup-t1.vf \
tex-CormorantGaramond-Bold-sup-t2a.tfm \
tex-CormorantGaramond-Bold-sup-t2b.tfm \
tex-CormorantGaramond-Bold-sup-t2c.tfm \
tex-CormorantGaramond-Bold-tlf-ly1.tfm \
tex-CormorantGaramond-Bold-tlf-ot1.tfm \
tex-CormorantGaramond-Bold-tlf-sc-ly1--base.tfm \
tex-CormorantGaramond-Bold-tlf-sc-ly1.tfm \
tex-CormorantGaramond-Bold-tlf-sc-ly1.vf \
tex-CormorantGaramond-Bold-tlf-sc-ot1--base.tfm \
tex-CormorantGaramond-Bold-tlf-sc-ot1.tfm \
tex-CormorantGaramond-Bold-tlf-sc-ot1.vf \
tex-CormorantGaramond-Bold-tlf-sc-t1--base.tfm \
tex-CormorantGaramond-Bold-tlf-sc-t1.tfm \
tex-CormorantGaramond-Bold-tlf-sc-t1.vf \
tex-CormorantGaramond-Bold-tlf-sc-t2a.tfm \
tex-CormorantGaramond-Bold-tlf-sc-t2b.tfm \
tex-CormorantGaramond-Bold-tlf-sc-t2c.tfm \
tex-CormorantGaramond-Bold-tlf-t1--base.tfm \
tex-CormorantGaramond-Bold-tlf-t1.tfm \
tex-CormorantGaramond-Bold-tlf-t1.vf \
tex-CormorantGaramond-Bold-tlf-t2a.tfm \
tex-CormorantGaramond-Bold-tlf-t2b.tfm \
tex-CormorantGaramond-Bold-tlf-t2c.tfm \
tex-CormorantGaramond-Bold-tlf-ts1--base.tfm \
tex-CormorantGaramond-Bold-tlf-ts1.tfm \
tex-CormorantGaramond-Bold-tlf-ts1.vf \
tex-CormorantGaramond-Bold-tosf-ly1.tfm \
tex-CormorantGaramond-Bold-tosf-ot1.tfm \
tex-CormorantGaramond-Bold-tosf-sc-ly1--base.tfm \
tex-CormorantGaramond-Bold-tosf-sc-ly1.tfm \
tex-CormorantGaramond-Bold-tosf-sc-ly1.vf \
tex-CormorantGaramond-Bold-tosf-sc-ot1--base.tfm \
tex-CormorantGaramond-Bold-tosf-sc-ot1.tfm \
tex-CormorantGaramond-Bold-tosf-sc-ot1.vf \
tex-CormorantGaramond-Bold-tosf-sc-t1--base.tfm \
tex-CormorantGaramond-Bold-tosf-sc-t1.tfm \
tex-CormorantGaramond-Bold-tosf-sc-t1.vf \
tex-CormorantGaramond-Bold-tosf-sc-t2a.tfm \
tex-CormorantGaramond-Bold-tosf-sc-t2b.tfm \
tex-CormorantGaramond-Bold-tosf-sc-t2c.tfm \
tex-CormorantGaramond-Bold-tosf-t1--base.tfm \
tex-CormorantGaramond-Bold-tosf-t1.tfm \
tex-CormorantGaramond-Bold-tosf-t1.vf \
tex-CormorantGaramond-Bold-tosf-t2a.tfm \
tex-CormorantGaramond-Bold-tosf-t2b.tfm \
tex-CormorantGaramond-Bold-tosf-t2c.tfm \
tex-CormorantGaramond-Bold-tosf-ts1--base.tfm \
tex-CormorantGaramond-Bold-tosf-ts1.tfm \
tex-CormorantGaramond-Bold-tosf-ts1.vf \
tex-CormorantGaramond-BoldItalic-inf-ly1.tfm \
tex-CormorantGaramond-BoldItalic-inf-ot1.tfm \
tex-CormorantGaramond-BoldItalic-inf-t1--base.tfm \
tex-CormorantGaramond-BoldItalic-inf-t1.tfm \
tex-CormorantGaramond-BoldItalic-inf-t1.vf \
tex-CormorantGaramond-BoldItalic-inf-t2a.tfm \
tex-CormorantGaramond-BoldItalic-inf-t2b.tfm \
tex-CormorantGaramond-BoldItalic-inf-t2c.tfm \
tex-CormorantGaramond-BoldItalic-lf-ly1.tfm \
tex-CormorantGaramond-BoldItalic-lf-ot1.tfm \
tex-CormorantGaramond-BoldItalic-lf-t1--base.tfm \
tex-CormorantGaramond-BoldItalic-lf-t1.tfm \
tex-CormorantGaramond-BoldItalic-lf-t1.vf \
tex-CormorantGaramond-BoldItalic-lf-t2a.tfm \
tex-CormorantGaramond-BoldItalic-lf-t2b.tfm \
tex-CormorantGaramond-BoldItalic-lf-t2c.tfm \
tex-CormorantGaramond-BoldItalic-lf-ts1--base.tfm \
tex-CormorantGaramond-BoldItalic-lf-ts1.tfm \
tex-CormorantGaramond-BoldItalic-lf-ts1.vf \
tex-CormorantGaramond-BoldItalic-osf-ly1.tfm \
tex-CormorantGaramond-BoldItalic-osf-ot1.tfm \
tex-CormorantGaramond-BoldItalic-osf-t1--base.tfm \
tex-CormorantGaramond-BoldItalic-osf-t1.tfm \
tex-CormorantGaramond-BoldItalic-osf-t1.vf \
tex-CormorantGaramond-BoldItalic-osf-t2a.tfm \
tex-CormorantGaramond-BoldItalic-osf-t2b.tfm \
tex-CormorantGaramond-BoldItalic-osf-t2c.tfm \
tex-CormorantGaramond-BoldItalic-osf-ts1--base.tfm \
tex-CormorantGaramond-BoldItalic-osf-ts1.tfm \
tex-CormorantGaramond-BoldItalic-osf-ts1.vf \
tex-CormorantGaramond-BoldItalic-sup-ly1.tfm \
tex-CormorantGaramond-BoldItalic-sup-ot1.tfm \
tex-CormorantGaramond-BoldItalic-sup-t1--base.tfm \
tex-CormorantGaramond-BoldItalic-sup-t1.tfm \
tex-CormorantGaramond-BoldItalic-sup-t1.vf \
tex-CormorantGaramond-BoldItalic-sup-t2a.tfm \
tex-CormorantGaramond-BoldItalic-sup-t2b.tfm \
tex-CormorantGaramond-BoldItalic-sup-t2c.tfm \
tex-CormorantGaramond-BoldItalic-tlf-ly1.tfm \
tex-CormorantGaramond-BoldItalic-tlf-ot1.tfm \
tex-CormorantGaramond-BoldItalic-tlf-t1--base.tfm \
tex-CormorantGaramond-BoldItalic-tlf-t1.tfm \
tex-CormorantGaramond-BoldItalic-tlf-t1.vf \
tex-CormorantGaramond-BoldItalic-tlf-t2a.tfm \
tex-CormorantGaramond-BoldItalic-tlf-t2b.tfm \
tex-CormorantGaramond-BoldItalic-tlf-t2c.tfm \
tex-CormorantGaramond-BoldItalic-tlf-ts1--base.tfm \
tex-CormorantGaramond-BoldItalic-tlf-ts1.tfm \
tex-CormorantGaramond-BoldItalic-tlf-ts1.vf \
tex-CormorantGaramond-BoldItalic-tosf-ly1.tfm \
tex-CormorantGaramond-BoldItalic-tosf-ot1.tfm \
tex-CormorantGaramond-BoldItalic-tosf-t1--base.tfm \
tex-CormorantGaramond-BoldItalic-tosf-t1.tfm \
tex-CormorantGaramond-BoldItalic-tosf-t1.vf \
tex-CormorantGaramond-BoldItalic-tosf-t2a.tfm \
tex-CormorantGaramond-BoldItalic-tosf-t2b.tfm \
tex-CormorantGaramond-BoldItalic-tosf-t2c.tfm \
tex-CormorantGaramond-BoldItalic-tosf-ts1--base.tfm \
tex-CormorantGaramond-BoldItalic-tosf-ts1.tfm \
tex-CormorantGaramond-BoldItalic-tosf-ts1.vf \
tex-CormorantGaramond-Italic-inf-ly1.tfm \
tex-CormorantGaramond-Italic-inf-ot1.tfm \
tex-CormorantGaramond-Italic-inf-t1--base.tfm \
tex-CormorantGaramond-Italic-inf-t1.tfm \
tex-CormorantGaramond-Italic-inf-t1.vf \
tex-CormorantGaramond-Italic-inf-t2a.tfm \
tex-CormorantGaramond-Italic-inf-t2b.tfm \
tex-CormorantGaramond-Italic-inf-t2c.tfm \
tex-CormorantGaramond-Italic-lf-ly1.tfm \
tex-CormorantGaramond-Italic-lf-ot1.tfm \
tex-CormorantGaramond-Italic-lf-t1--base.tfm \
tex-CormorantGaramond-Italic-lf-t1.tfm \
tex-CormorantGaramond-Italic-lf-t1.vf \
tex-CormorantGaramond-Italic-lf-t2a.tfm \
tex-CormorantGaramond-Italic-lf-t2b.tfm \
tex-CormorantGaramond-Italic-lf-t2c.tfm \
tex-CormorantGaramond-Italic-lf-ts1--base.tfm \
tex-CormorantGaramond-Italic-lf-ts1.tfm \
tex-CormorantGaramond-Italic-lf-ts1.vf \
tex-CormorantGaramond-Italic-osf-ly1.tfm \
tex-CormorantGaramond-Italic-osf-ot1.tfm \
tex-CormorantGaramond-Italic-osf-t1--base.tfm \
tex-CormorantGaramond-Italic-osf-t1.tfm \
tex-CormorantGaramond-Italic-osf-t1.vf \
tex-CormorantGaramond-Italic-osf-t2a.tfm \
tex-CormorantGaramond-Italic-osf-t2b.tfm \
tex-CormorantGaramond-Italic-osf-t2c.tfm \
tex-CormorantGaramond-Italic-osf-ts1--base.tfm \
tex-CormorantGaramond-Italic-osf-ts1.tfm \
tex-CormorantGaramond-Italic-osf-ts1.vf \
tex-CormorantGaramond-Italic-sup-ly1.tfm \
tex-CormorantGaramond-Italic-sup-ot1.tfm \
tex-CormorantGaramond-Italic-sup-t1--base.tfm \
tex-CormorantGaramond-Italic-sup-t1.tfm \
tex-CormorantGaramond-Italic-sup-t1.vf \
tex-CormorantGaramond-Italic-sup-t2a.tfm \
tex-CormorantGaramond-Italic-sup-t2b.tfm \
tex-CormorantGaramond-Italic-sup-t2c.tfm \
tex-CormorantGaramond-Italic-tlf-ly1.tfm \
tex-CormorantGaramond-Italic-tlf-ot1.tfm \
tex-CormorantGaramond-Italic-tlf-t1--base.tfm \
tex-CormorantGaramond-Italic-tlf-t1.tfm \
tex-CormorantGaramond-Italic-tlf-t1.vf \
tex-CormorantGaramond-Italic-tlf-t2a.tfm \
tex-CormorantGaramond-Italic-tlf-t2b.tfm \
tex-CormorantGaramond-Italic-tlf-t2c.tfm \
tex-CormorantGaramond-Italic-tlf-ts1--base.tfm \
tex-CormorantGaramond-Italic-tlf-ts1.tfm \
tex-CormorantGaramond-Italic-tlf-ts1.vf \
tex-CormorantGaramond-Italic-tosf-ly1.tfm \
tex-CormorantGaramond-Italic-tosf-ot1.tfm \
tex-CormorantGaramond-Italic-tosf-t1--base.tfm \
tex-CormorantGaramond-Italic-tosf-t1.tfm \
tex-CormorantGaramond-Italic-tosf-t1.vf \
tex-CormorantGaramond-Italic-tosf-t2a.tfm \
tex-CormorantGaramond-Italic-tosf-t2b.tfm \
tex-CormorantGaramond-Italic-tosf-t2c.tfm \
tex-CormorantGaramond-Italic-tosf-ts1--base.tfm \
tex-CormorantGaramond-Italic-tosf-ts1.tfm \
tex-CormorantGaramond-Italic-tosf-ts1.vf \
tex-CormorantGaramond-Light-inf-ly1.tfm \
tex-CormorantGaramond-Light-inf-ot1.tfm \
tex-CormorantGaramond-Light-inf-t1--base.tfm \
tex-CormorantGaramond-Light-inf-t1.tfm \
tex-CormorantGaramond-Light-inf-t1.vf \
tex-CormorantGaramond-Light-inf-t2a.tfm \
tex-CormorantGaramond-Light-inf-t2b.tfm \
tex-CormorantGaramond-Light-inf-t2c.tfm \
tex-CormorantGaramond-Light-lf-ly1.tfm \
tex-CormorantGaramond-Light-lf-ot1.tfm \
tex-CormorantGaramond-Light-lf-sc-ly1--base.tfm \
tex-CormorantGaramond-Light-lf-sc-ly1.tfm \
tex-CormorantGaramond-Light-lf-sc-ly1.vf \
tex-CormorantGaramond-Light-lf-sc-ot1--base.tfm \
tex-CormorantGaramond-Light-lf-sc-ot1.tfm \
tex-CormorantGaramond-Light-lf-sc-ot1.vf \
tex-CormorantGaramond-Light-lf-sc-t1--base.tfm \
tex-CormorantGaramond-Light-lf-sc-t1.tfm \
tex-CormorantGaramond-Light-lf-sc-t1.vf \
tex-CormorantGaramond-Light-lf-sc-t2a.tfm \
tex-CormorantGaramond-Light-lf-sc-t2b.tfm \
tex-CormorantGaramond-Light-lf-sc-t2c.tfm \
tex-CormorantGaramond-Light-lf-t1--base.tfm \
tex-CormorantGaramond-Light-lf-t1.tfm \
tex-CormorantGaramond-Light-lf-t1.vf \
tex-CormorantGaramond-Light-lf-t2a.tfm \
tex-CormorantGaramond-Light-lf-t2b.tfm \
tex-CormorantGaramond-Light-lf-t2c.tfm \
tex-CormorantGaramond-Light-lf-ts1--base.tfm \
tex-CormorantGaramond-Light-lf-ts1.tfm \
tex-CormorantGaramond-Light-lf-ts1.vf \
tex-CormorantGaramond-Light-osf-ly1.tfm \
tex-CormorantGaramond-Light-osf-ot1.tfm \
tex-CormorantGaramond-Light-osf-sc-ly1--base.tfm \
tex-CormorantGaramond-Light-osf-sc-ly1.tfm \
tex-CormorantGaramond-Light-osf-sc-ly1.vf \
tex-CormorantGaramond-Light-osf-sc-ot1--base.tfm \
tex-CormorantGaramond-Light-osf-sc-ot1.tfm \
tex-CormorantGaramond-Light-osf-sc-ot1.vf \
tex-CormorantGaramond-Light-osf-sc-t1--base.tfm \
tex-CormorantGaramond-Light-osf-sc-t1.tfm \
tex-CormorantGaramond-Light-osf-sc-t1.vf \
tex-CormorantGaramond-Light-osf-sc-t2a.tfm \
tex-CormorantGaramond-Light-osf-sc-t2b.tfm \
tex-CormorantGaramond-Light-osf-sc-t2c.tfm \
tex-CormorantGaramond-Light-osf-t1--base.tfm \
tex-CormorantGaramond-Light-osf-t1.tfm \
tex-CormorantGaramond-Light-osf-t1.vf \
tex-CormorantGaramond-Light-osf-t2a.tfm \
tex-CormorantGaramond-Light-osf-t2b.tfm \
tex-CormorantGaramond-Light-osf-t2c.tfm \
tex-CormorantGaramond-Light-osf-ts1--base.tfm \
tex-CormorantGaramond-Light-osf-ts1.tfm \
tex-CormorantGaramond-Light-osf-ts1.vf \
tex-CormorantGaramond-Light-sup-ly1.tfm \
tex-CormorantGaramond-Light-sup-ot1.tfm \
tex-CormorantGaramond-Light-sup-t1--base.tfm \
tex-CormorantGaramond-Light-sup-t1.tfm \
tex-CormorantGaramond-Light-sup-t1.vf \
tex-CormorantGaramond-Light-sup-t2a.tfm \
tex-CormorantGaramond-Light-sup-t2b.tfm \
tex-CormorantGaramond-Light-sup-t2c.tfm \
tex-CormorantGaramond-Light-tlf-ly1.tfm \
tex-CormorantGaramond-Light-tlf-ot1.tfm \
tex-CormorantGaramond-Light-tlf-sc-ly1--base.tfm \
tex-CormorantGaramond-Light-tlf-sc-ly1.tfm \
tex-CormorantGaramond-Light-tlf-sc-ly1.vf \
tex-CormorantGaramond-Light-tlf-sc-ot1--base.tfm \
tex-CormorantGaramond-Light-tlf-sc-ot1.tfm \
tex-CormorantGaramond-Light-tlf-sc-ot1.vf \
tex-CormorantGaramond-Light-tlf-sc-t1--base.tfm \
tex-CormorantGaramond-Light-tlf-sc-t1.tfm \
tex-CormorantGaramond-Light-tlf-sc-t1.vf \
tex-CormorantGaramond-Light-tlf-sc-t2a.tfm \
tex-CormorantGaramond-Light-tlf-sc-t2b.tfm \
tex-CormorantGaramond-Light-tlf-sc-t2c.tfm \
tex-CormorantGaramond-Light-tlf-t1--base.tfm \
tex-CormorantGaramond-Light-tlf-t1.tfm \
tex-CormorantGaramond-Light-tlf-t1.vf \
tex-CormorantGaramond-Light-tlf-t2a.tfm \
tex-CormorantGaramond-Light-tlf-t2b.tfm \
tex-CormorantGaramond-Light-tlf-t2c.tfm \
tex-CormorantGaramond-Light-tlf-ts1--base.tfm \
tex-CormorantGaramond-Light-tlf-ts1.tfm \
tex-CormorantGaramond-Light-tlf-ts1.vf \
tex-CormorantGaramond-Light-tosf-ly1.tfm \
tex-CormorantGaramond-Light-tosf-ot1.tfm \
tex-CormorantGaramond-Light-tosf-sc-ly1--base.tfm \
tex-CormorantGaramond-Light-tosf-sc-ly1.tfm \
tex-CormorantGaramond-Light-tosf-sc-ly1.vf \
tex-CormorantGaramond-Light-tosf-sc-ot1--base.tfm \
tex-CormorantGaramond-Light-tosf-sc-ot1.tfm \
tex-CormorantGaramond-Light-tosf-sc-ot1.vf \
tex-CormorantGaramond-Light-tosf-sc-t1--base.tfm \
tex-CormorantGaramond-Light-tosf-sc-t1.tfm \
tex-CormorantGaramond-Light-tosf-sc-t1.vf \
tex-CormorantGaramond-Light-tosf-sc-t2a.tfm \
tex-CormorantGaramond-Light-tosf-sc-t2b.tfm \
tex-CormorantGaramond-Light-tosf-sc-t2c.tfm \
tex-CormorantGaramond-Light-tosf-t1--base.tfm \
tex-CormorantGaramond-Light-tosf-t1.tfm \
tex-CormorantGaramond-Light-tosf-t1.vf \
tex-CormorantGaramond-Light-tosf-t2a.tfm \
tex-CormorantGaramond-Light-tosf-t2b.tfm \
tex-CormorantGaramond-Light-tosf-t2c.tfm \
tex-CormorantGaramond-Light-tosf-ts1--base.tfm \
tex-CormorantGaramond-Light-tosf-ts1.tfm \
tex-CormorantGaramond-Light-tosf-ts1.vf \
tex-CormorantGaramond-LightItalic-inf-ly1.tfm \
tex-CormorantGaramond-LightItalic-inf-ot1.tfm \
tex-CormorantGaramond-LightItalic-inf-t1--base.tfm \
tex-CormorantGaramond-LightItalic-inf-t1.tfm \
tex-CormorantGaramond-LightItalic-inf-t1.vf \
tex-CormorantGaramond-LightItalic-inf-t2a.tfm \
tex-CormorantGaramond-LightItalic-inf-t2b.tfm \
tex-CormorantGaramond-LightItalic-inf-t2c.tfm \
tex-CormorantGaramond-LightItalic-lf-ly1.tfm \
tex-CormorantGaramond-LightItalic-lf-ot1.tfm \
tex-CormorantGaramond-LightItalic-lf-t1--base.tfm \
tex-CormorantGaramond-LightItalic-lf-t1.tfm \
tex-CormorantGaramond-LightItalic-lf-t1.vf \
tex-CormorantGaramond-LightItalic-lf-t2a.tfm \
tex-CormorantGaramond-LightItalic-lf-t2b.tfm \
tex-CormorantGaramond-LightItalic-lf-t2c.tfm \
tex-CormorantGaramond-LightItalic-lf-ts1--base.tfm \
tex-CormorantGaramond-LightItalic-lf-ts1.tfm \
tex-CormorantGaramond-LightItalic-lf-ts1.vf \
tex-CormorantGaramond-LightItalic-osf-ly1.tfm \
tex-CormorantGaramond-LightItalic-osf-ot1.tfm \
tex-CormorantGaramond-LightItalic-osf-t1--base.tfm \
tex-CormorantGaramond-LightItalic-osf-t1.tfm \
tex-CormorantGaramond-LightItalic-osf-t1.vf \
tex-CormorantGaramond-LightItalic-osf-t2a.tfm \
tex-CormorantGaramond-LightItalic-osf-t2b.tfm \
tex-CormorantGaramond-LightItalic-osf-t2c.tfm \
tex-CormorantGaramond-LightItalic-osf-ts1--base.tfm \
tex-CormorantGaramond-LightItalic-osf-ts1.tfm \
tex-CormorantGaramond-LightItalic-osf-ts1.vf \
tex-CormorantGaramond-LightItalic-sup-ly1.tfm \
tex-CormorantGaramond-LightItalic-sup-ot1.tfm \
tex-CormorantGaramond-LightItalic-sup-t1--base.tfm \
tex-CormorantGaramond-LightItalic-sup-t1.tfm \
tex-CormorantGaramond-LightItalic-sup-t1.vf \
tex-CormorantGaramond-LightItalic-sup-t2a.tfm \
tex-CormorantGaramond-LightItalic-sup-t2b.tfm \
tex-CormorantGaramond-LightItalic-sup-t2c.tfm \
tex-CormorantGaramond-LightItalic-tlf-ly1.tfm \
tex-CormorantGaramond-LightItalic-tlf-ot1.tfm \
tex-CormorantGaramond-LightItalic-tlf-t1--base.tfm \
tex-CormorantGaramond-LightItalic-tlf-t1.tfm \
tex-CormorantGaramond-LightItalic-tlf-t1.vf \
tex-CormorantGaramond-LightItalic-tlf-t2a.tfm \
tex-CormorantGaramond-LightItalic-tlf-t2b.tfm \
tex-CormorantGaramond-LightItalic-tlf-t2c.tfm \
tex-CormorantGaramond-LightItalic-tlf-ts1--base.tfm \
tex-CormorantGaramond-LightItalic-tlf-ts1.tfm \
tex-CormorantGaramond-LightItalic-tlf-ts1.vf \
tex-CormorantGaramond-LightItalic-tosf-ly1.tfm \
tex-CormorantGaramond-LightItalic-tosf-ot1.tfm \
tex-CormorantGaramond-LightItalic-tosf-t1--base.tfm \
tex-CormorantGaramond-LightItalic-tosf-t1.tfm \
tex-CormorantGaramond-LightItalic-tosf-t1.vf \
tex-CormorantGaramond-LightItalic-tosf-t2a.tfm \
tex-CormorantGaramond-LightItalic-tosf-t2b.tfm \
tex-CormorantGaramond-LightItalic-tosf-t2c.tfm \
tex-CormorantGaramond-LightItalic-tosf-ts1--base.tfm \
tex-CormorantGaramond-LightItalic-tosf-ts1.tfm \
tex-CormorantGaramond-LightItalic-tosf-ts1.vf \
tex-CormorantGaramond-Medium-inf-ly1.tfm \
tex-CormorantGaramond-Medium-inf-ot1.tfm \
tex-CormorantGaramond-Medium-inf-t1--base.tfm \
tex-CormorantGaramond-Medium-inf-t1.tfm \
tex-CormorantGaramond-Medium-inf-t1.vf \
tex-CormorantGaramond-Medium-inf-t2a.tfm \
tex-CormorantGaramond-Medium-inf-t2b.tfm \
tex-CormorantGaramond-Medium-inf-t2c.tfm \
tex-CormorantGaramond-Medium-lf-ly1.tfm \
tex-CormorantGaramond-Medium-lf-ot1.tfm \
tex-CormorantGaramond-Medium-lf-sc-ly1--base.tfm \
tex-CormorantGaramond-Medium-lf-sc-ly1.tfm \
tex-CormorantGaramond-Medium-lf-sc-ly1.vf \
tex-CormorantGaramond-Medium-lf-sc-ot1--base.tfm \
tex-CormorantGaramond-Medium-lf-sc-ot1.tfm \
tex-CormorantGaramond-Medium-lf-sc-ot1.vf \
tex-CormorantGaramond-Medium-lf-sc-t1--base.tfm \
tex-CormorantGaramond-Medium-lf-sc-t1.tfm \
tex-CormorantGaramond-Medium-lf-sc-t1.vf \
tex-CormorantGaramond-Medium-lf-sc-t2a.tfm \
tex-CormorantGaramond-Medium-lf-sc-t2b.tfm \
tex-CormorantGaramond-Medium-lf-sc-t2c.tfm \
tex-CormorantGaramond-Medium-lf-t1--base.tfm \
tex-CormorantGaramond-Medium-lf-t1.tfm \
tex-CormorantGaramond-Medium-lf-t1.vf \
tex-CormorantGaramond-Medium-lf-t2a.tfm \
tex-CormorantGaramond-Medium-lf-t2b.tfm \
tex-CormorantGaramond-Medium-lf-t2c.tfm \
tex-CormorantGaramond-Medium-lf-ts1--base.tfm \
tex-CormorantGaramond-Medium-lf-ts1.tfm \
tex-CormorantGaramond-Medium-lf-ts1.vf \
tex-CormorantGaramond-Medium-osf-ly1.tfm \
tex-CormorantGaramond-Medium-osf-ot1.tfm \
tex-CormorantGaramond-Medium-osf-sc-ly1--base.tfm \
tex-CormorantGaramond-Medium-osf-sc-ly1.tfm \
tex-CormorantGaramond-Medium-osf-sc-ly1.vf \
tex-CormorantGaramond-Medium-osf-sc-ot1--base.tfm \
tex-CormorantGaramond-Medium-osf-sc-ot1.tfm \
tex-CormorantGaramond-Medium-osf-sc-ot1.vf \
tex-CormorantGaramond-Medium-osf-sc-t1--base.tfm \
tex-CormorantGaramond-Medium-osf-sc-t1.tfm \
tex-CormorantGaramond-Medium-osf-sc-t1.vf \
tex-CormorantGaramond-Medium-osf-sc-t2a.tfm \
tex-CormorantGaramond-Medium-osf-sc-t2b.tfm \
tex-CormorantGaramond-Medium-osf-sc-t2c.tfm \
tex-CormorantGaramond-Medium-osf-t1--base.tfm \
tex-CormorantGaramond-Medium-osf-t1.tfm \
tex-CormorantGaramond-Medium-osf-t1.vf \
tex-CormorantGaramond-Medium-osf-t2a.tfm \
tex-CormorantGaramond-Medium-osf-t2b.tfm \
tex-CormorantGaramond-Medium-osf-t2c.tfm \
tex-CormorantGaramond-Medium-osf-ts1--base.tfm \
tex-CormorantGaramond-Medium-osf-ts1.tfm \
tex-CormorantGaramond-Medium-osf-ts1.vf \
tex-CormorantGaramond-Medium-sup-ly1.tfm \
tex-CormorantGaramond-Medium-sup-ot1.tfm \
tex-CormorantGaramond-Medium-sup-t1--base.tfm \
tex-CormorantGaramond-Medium-sup-t1.tfm \
tex-CormorantGaramond-Medium-sup-t1.vf \
tex-CormorantGaramond-Medium-sup-t2a.tfm \
tex-CormorantGaramond-Medium-sup-t2b.tfm \
tex-CormorantGaramond-Medium-sup-t2c.tfm \
tex-CormorantGaramond-Medium-tlf-ly1.tfm \
tex-CormorantGaramond-Medium-tlf-ot1.tfm \
tex-CormorantGaramond-Medium-tlf-sc-ly1--base.tfm \
tex-CormorantGaramond-Medium-tlf-sc-ly1.tfm \
tex-CormorantGaramond-Medium-tlf-sc-ly1.vf \
tex-CormorantGaramond-Medium-tlf-sc-ot1--base.tfm \
tex-CormorantGaramond-Medium-tlf-sc-ot1.tfm \
tex-CormorantGaramond-Medium-tlf-sc-ot1.vf \
tex-CormorantGaramond-Medium-tlf-sc-t1--base.tfm \
tex-CormorantGaramond-Medium-tlf-sc-t1.tfm \
tex-CormorantGaramond-Medium-tlf-sc-t1.vf \
tex-CormorantGaramond-Medium-tlf-sc-t2a.tfm \
tex-CormorantGaramond-Medium-tlf-sc-t2b.tfm \
tex-CormorantGaramond-Medium-tlf-sc-t2c.tfm \
tex-CormorantGaramond-Medium-tlf-t1--base.tfm \
tex-CormorantGaramond-Medium-tlf-t1.tfm \
tex-CormorantGaramond-Medium-tlf-t1.vf \
tex-CormorantGaramond-Medium-tlf-t2a.tfm \
tex-CormorantGaramond-Medium-tlf-t2b.tfm \
tex-CormorantGaramond-Medium-tlf-t2c.tfm \
tex-CormorantGaramond-Medium-tlf-ts1--base.tfm \
tex-CormorantGaramond-Medium-tlf-ts1.tfm \
tex-CormorantGaramond-Medium-tlf-ts1.vf \
tex-CormorantGaramond-Medium-tosf-ly1.tfm \
tex-CormorantGaramond-Medium-tosf-ot1.tfm \
tex-CormorantGaramond-Medium-tosf-sc-ly1--base.tfm \
tex-CormorantGaramond-Medium-tosf-sc-ly1.tfm \
tex-CormorantGaramond-Medium-tosf-sc-ly1.vf \
tex-CormorantGaramond-Medium-tosf-sc-ot1--base.tfm \
tex-CormorantGaramond-Medium-tosf-sc-ot1.tfm \
tex-CormorantGaramond-Medium-tosf-sc-ot1.vf \
tex-CormorantGaramond-Medium-tosf-sc-t1--base.tfm \
tex-CormorantGaramond-Medium-tosf-sc-t1.tfm \
tex-CormorantGaramond-Medium-tosf-sc-t1.vf \
tex-CormorantGaramond-Medium-tosf-sc-t2a.tfm \
tex-CormorantGaramond-Medium-tosf-sc-t2b.tfm \
tex-CormorantGaramond-Medium-tosf-sc-t2c.tfm \
tex-CormorantGaramond-Medium-tosf-t1--base.tfm \
tex-CormorantGaramond-Medium-tosf-t1.tfm \
tex-CormorantGaramond-Medium-tosf-t1.vf \
tex-CormorantGaramond-Medium-tosf-t2a.tfm \
tex-CormorantGaramond-Medium-tosf-t2b.tfm \
tex-CormorantGaramond-Medium-tosf-t2c.tfm \
tex-CormorantGaramond-Medium-tosf-ts1--base.tfm \
tex-CormorantGaramond-Medium-tosf-ts1.tfm \
tex-CormorantGaramond-Medium-tosf-ts1.vf \
tex-CormorantGaramond-MediumItalic-inf-ly1.tfm \
tex-CormorantGaramond-MediumItalic-inf-ot1.tfm \
tex-CormorantGaramond-MediumItalic-inf-t1--base.tfm \
tex-CormorantGaramond-MediumItalic-inf-t1.tfm \
tex-CormorantGaramond-MediumItalic-inf-t1.vf \
tex-CormorantGaramond-MediumItalic-inf-t2a.tfm \
tex-CormorantGaramond-MediumItalic-inf-t2b.tfm \
tex-CormorantGaramond-MediumItalic-inf-t2c.tfm \
tex-CormorantGaramond-MediumItalic-lf-ly1.tfm \
tex-CormorantGaramond-MediumItalic-lf-ot1.tfm \
tex-CormorantGaramond-MediumItalic-lf-t1--base.tfm \
tex-CormorantGaramond-MediumItalic-lf-t1.tfm \
tex-CormorantGaramond-MediumItalic-lf-t1.vf \
tex-CormorantGaramond-MediumItalic-lf-t2a.tfm \
tex-CormorantGaramond-MediumItalic-lf-t2b.tfm \
tex-CormorantGaramond-MediumItalic-lf-t2c.tfm \
tex-CormorantGaramond-MediumItalic-lf-ts1--base.tfm \
tex-CormorantGaramond-MediumItalic-lf-ts1.tfm \
tex-CormorantGaramond-MediumItalic-lf-ts1.vf \
tex-CormorantGaramond-MediumItalic-osf-ly1.tfm \
tex-CormorantGaramond-MediumItalic-osf-ot1.tfm \
tex-CormorantGaramond-MediumItalic-osf-t1--base.tfm \
tex-CormorantGaramond-MediumItalic-osf-t1.tfm \
tex-CormorantGaramond-MediumItalic-osf-t1.vf \
tex-CormorantGaramond-MediumItalic-osf-t2a.tfm \
tex-CormorantGaramond-MediumItalic-osf-t2b.tfm \
tex-CormorantGaramond-MediumItalic-osf-t2c.tfm \
tex-CormorantGaramond-MediumItalic-osf-ts1--base.tfm \
tex-CormorantGaramond-MediumItalic-osf-ts1.tfm \
tex-CormorantGaramond-MediumItalic-osf-ts1.vf \
tex-CormorantGaramond-MediumItalic-sup-ly1.tfm \
tex-CormorantGaramond-MediumItalic-sup-ot1.tfm \
tex-CormorantGaramond-MediumItalic-sup-t1--base.tfm \
tex-CormorantGaramond-MediumItalic-sup-t1.tfm \
tex-CormorantGaramond-MediumItalic-sup-t1.vf \
tex-CormorantGaramond-MediumItalic-sup-t2a.tfm \
tex-CormorantGaramond-MediumItalic-sup-t2b.tfm \
tex-CormorantGaramond-MediumItalic-sup-t2c.tfm \
tex-CormorantGaramond-MediumItalic-tlf-ly1.tfm \
tex-CormorantGaramond-MediumItalic-tlf-ot1.tfm \
tex-CormorantGaramond-MediumItalic-tlf-t1--base.tfm \
tex-CormorantGaramond-MediumItalic-tlf-t1.tfm \
tex-CormorantGaramond-MediumItalic-tlf-t1.vf \
tex-CormorantGaramond-MediumItalic-tlf-t2a.tfm \
tex-CormorantGaramond-MediumItalic-tlf-t2b.tfm \
tex-CormorantGaramond-MediumItalic-tlf-t2c.tfm \
tex-CormorantGaramond-MediumItalic-tlf-ts1--base.tfm \
tex-CormorantGaramond-MediumItalic-tlf-ts1.tfm \
tex-CormorantGaramond-MediumItalic-tlf-ts1.vf \
tex-CormorantGaramond-MediumItalic-tosf-ly1.tfm \
tex-CormorantGaramond-MediumItalic-tosf-ot1.tfm \
tex-CormorantGaramond-MediumItalic-tosf-t1--base.tfm \
tex-CormorantGaramond-MediumItalic-tosf-t1.tfm \
tex-CormorantGaramond-MediumItalic-tosf-t1.vf \
tex-CormorantGaramond-MediumItalic-tosf-t2a.tfm \
tex-CormorantGaramond-MediumItalic-tosf-t2b.tfm \
tex-CormorantGaramond-MediumItalic-tosf-t2c.tfm \
tex-CormorantGaramond-MediumItalic-tosf-ts1--base.tfm \
tex-CormorantGaramond-MediumItalic-tosf-ts1.tfm \
tex-CormorantGaramond-MediumItalic-tosf-ts1.vf \
tex-CormorantGaramond-Regular-inf-ly1.tfm \
tex-CormorantGaramond-Regular-inf-ot1.tfm \
tex-CormorantGaramond-Regular-inf-t1--base.tfm \
tex-CormorantGaramond-Regular-inf-t1.tfm \
tex-CormorantGaramond-Regular-inf-t1.vf \
tex-CormorantGaramond-Regular-inf-t2a.tfm \
tex-CormorantGaramond-Regular-inf-t2b.tfm \
tex-CormorantGaramond-Regular-inf-t2c.tfm \
tex-CormorantGaramond-Regular-lf-ly1.tfm \
tex-CormorantGaramond-Regular-lf-ot1.tfm \
tex-CormorantGaramond-Regular-lf-sc-ly1--base.tfm \
tex-CormorantGaramond-Regular-lf-sc-ly1.tfm \
tex-CormorantGaramond-Regular-lf-sc-ly1.vf \
tex-CormorantGaramond-Regular-lf-sc-ot1--base.tfm \
tex-CormorantGaramond-Regular-lf-sc-ot1.tfm \
tex-CormorantGaramond-Regular-lf-sc-ot1.vf \
tex-CormorantGaramond-Regular-lf-sc-t1--base.tfm \
tex-CormorantGaramond-Regular-lf-sc-t1.tfm \
tex-CormorantGaramond-Regular-lf-sc-t1.vf \
tex-CormorantGaramond-Regular-lf-sc-t2a.tfm \
tex-CormorantGaramond-Regular-lf-sc-t2b.tfm \
tex-CormorantGaramond-Regular-lf-sc-t2c.tfm \
tex-CormorantGaramond-Regular-lf-t1--base.tfm \
tex-CormorantGaramond-Regular-lf-t1.tfm \
tex-CormorantGaramond-Regular-lf-t1.vf \
tex-CormorantGaramond-Regular-lf-t2a.tfm \
tex-CormorantGaramond-Regular-lf-t2b.tfm \
tex-CormorantGaramond-Regular-lf-t2c.tfm \
tex-CormorantGaramond-Regular-lf-ts1--base.tfm \
tex-CormorantGaramond-Regular-lf-ts1.tfm \
tex-CormorantGaramond-Regular-lf-ts1.vf \
tex-CormorantGaramond-Regular-osf-ly1.tfm \
tex-CormorantGaramond-Regular-osf-ot1.tfm \
tex-CormorantGaramond-Regular-osf-sc-ly1--base.tfm \
tex-CormorantGaramond-Regular-osf-sc-ly1.tfm \
tex-CormorantGaramond-Regular-osf-sc-ly1.vf \
tex-CormorantGaramond-Regular-osf-sc-ot1--base.tfm \
tex-CormorantGaramond-Regular-osf-sc-ot1.tfm \
tex-CormorantGaramond-Regular-osf-sc-ot1.vf \
tex-CormorantGaramond-Regular-osf-sc-t1--base.tfm \
tex-CormorantGaramond-Regular-osf-sc-t1.tfm \
tex-CormorantGaramond-Regular-osf-sc-t1.vf \
tex-CormorantGaramond-Regular-osf-sc-t2a.tfm \
tex-CormorantGaramond-Regular-osf-sc-t2b.tfm \
tex-CormorantGaramond-Regular-osf-sc-t2c.tfm \
tex-CormorantGaramond-Regular-osf-t1--base.tfm \
tex-CormorantGaramond-Regular-osf-t1.tfm \
tex-CormorantGaramond-Regular-osf-t1.vf \
tex-CormorantGaramond-Regular-osf-t2a.tfm \
tex-CormorantGaramond-Regular-osf-t2b.tfm \
tex-CormorantGaramond-Regular-osf-t2c.tfm \
tex-CormorantGaramond-Regular-osf-ts1--base.tfm \
tex-CormorantGaramond-Regular-osf-ts1.tfm \
tex-CormorantGaramond-Regular-osf-ts1.vf \
tex-CormorantGaramond-Regular-sup-ly1.tfm \
tex-CormorantGaramond-Regular-sup-ot1.tfm \
tex-CormorantGaramond-Regular-sup-t1--base.tfm \
tex-CormorantGaramond-Regular-sup-t1.tfm \
tex-CormorantGaramond-Regular-sup-t1.vf \
tex-CormorantGaramond-Regular-sup-t2a.tfm \
tex-CormorantGaramond-Regular-sup-t2b.tfm \
tex-CormorantGaramond-Regular-sup-t2c.tfm \
tex-CormorantGaramond-Regular-tlf-ly1.tfm \
tex-CormorantGaramond-Regular-tlf-ot1.tfm \
tex-CormorantGaramond-Regular-tlf-sc-ly1--base.tfm \
tex-CormorantGaramond-Regular-tlf-sc-ly1.tfm \
tex-CormorantGaramond-Regular-tlf-sc-ly1.vf \
tex-CormorantGaramond-Regular-tlf-sc-ot1--base.tfm \
tex-CormorantGaramond-Regular-tlf-sc-ot1.tfm \
tex-CormorantGaramond-Regular-tlf-sc-ot1.vf \
tex-CormorantGaramond-Regular-tlf-sc-t1--base.tfm \
tex-CormorantGaramond-Regular-tlf-sc-t1.tfm \
tex-CormorantGaramond-Regular-tlf-sc-t1.vf \
tex-CormorantGaramond-Regular-tlf-sc-t2a.tfm \
tex-CormorantGaramond-Regular-tlf-sc-t2b.tfm \
tex-CormorantGaramond-Regular-tlf-sc-t2c.tfm \
tex-CormorantGaramond-Regular-tlf-t1--base.tfm \
tex-CormorantGaramond-Regular-tlf-t1.tfm \
tex-CormorantGaramond-Regular-tlf-t1.vf \
tex-CormorantGaramond-Regular-tlf-t2a.tfm \
tex-CormorantGaramond-Regular-tlf-t2b.tfm \
tex-CormorantGaramond-Regular-tlf-t2c.tfm \
tex-CormorantGaramond-Regular-tlf-ts1--base.tfm \
tex-CormorantGaramond-Regular-tlf-ts1.tfm \
tex-CormorantGaramond-Regular-tlf-ts1.vf \
tex-CormorantGaramond-Regular-tosf-ly1.tfm \
tex-CormorantGaramond-Regular-tosf-ot1.tfm \
tex-CormorantGaramond-Regular-tosf-sc-ly1--base.tfm \
tex-CormorantGaramond-Regular-tosf-sc-ly1.tfm \
tex-CormorantGaramond-Regular-tosf-sc-ly1.vf \
tex-CormorantGaramond-Regular-tosf-sc-ot1--base.tfm \
tex-CormorantGaramond-Regular-tosf-sc-ot1.tfm \
tex-CormorantGaramond-Regular-tosf-sc-ot1.vf \
tex-CormorantGaramond-Regular-tosf-sc-t1--base.tfm \
tex-CormorantGaramond-Regular-tosf-sc-t1.tfm \
tex-CormorantGaramond-Regular-tosf-sc-t1.vf \
tex-CormorantGaramond-Regular-tosf-sc-t2a.tfm \
tex-CormorantGaramond-Regular-tosf-sc-t2b.tfm \
tex-CormorantGaramond-Regular-tosf-sc-t2c.tfm \
tex-CormorantGaramond-Regular-tosf-t1--base.tfm \
tex-CormorantGaramond-Regular-tosf-t1.tfm \
tex-CormorantGaramond-Regular-tosf-t1.vf \
tex-CormorantGaramond-Regular-tosf-t2a.tfm \
tex-CormorantGaramond-Regular-tosf-t2b.tfm \
tex-CormorantGaramond-Regular-tosf-t2c.tfm \
tex-CormorantGaramond-Regular-tosf-ts1--base.tfm \
tex-CormorantGaramond-Regular-tosf-ts1.tfm \
tex-CormorantGaramond-Regular-tosf-ts1.vf \
tex-CormorantGaramond-SemiBold-inf-ly1.tfm \
tex-CormorantGaramond-SemiBold-inf-ot1.tfm \
tex-CormorantGaramond-SemiBold-inf-t1--base.tfm \
tex-CormorantGaramond-SemiBold-inf-t1.tfm \
tex-CormorantGaramond-SemiBold-inf-t1.vf \
tex-CormorantGaramond-SemiBold-inf-t2a.tfm \
tex-CormorantGaramond-SemiBold-inf-t2b.tfm \
tex-CormorantGaramond-SemiBold-inf-t2c.tfm \
tex-CormorantGaramond-SemiBold-lf-ly1.tfm \
tex-CormorantGaramond-SemiBold-lf-ot1.tfm \
tex-CormorantGaramond-SemiBold-lf-sc-ly1--base.tfm \
tex-CormorantGaramond-SemiBold-lf-sc-ly1.tfm \
tex-CormorantGaramond-SemiBold-lf-sc-ly1.vf \
tex-CormorantGaramond-SemiBold-lf-sc-ot1--base.tfm \
tex-CormorantGaramond-SemiBold-lf-sc-ot1.tfm \
tex-CormorantGaramond-SemiBold-lf-sc-ot1.vf \
tex-CormorantGaramond-SemiBold-lf-sc-t1--base.tfm \
tex-CormorantGaramond-SemiBold-lf-sc-t1.tfm \
tex-CormorantGaramond-SemiBold-lf-sc-t1.vf \
tex-CormorantGaramond-SemiBold-lf-sc-t2a.tfm \
tex-CormorantGaramond-SemiBold-lf-sc-t2b.tfm \
tex-CormorantGaramond-SemiBold-lf-sc-t2c.tfm \
tex-CormorantGaramond-SemiBold-lf-t1--base.tfm \
tex-CormorantGaramond-SemiBold-lf-t1.tfm \
tex-CormorantGaramond-SemiBold-lf-t1.vf \
tex-CormorantGaramond-SemiBold-lf-t2a.tfm \
tex-CormorantGaramond-SemiBold-lf-t2b.tfm \
tex-CormorantGaramond-SemiBold-lf-t2c.tfm \
tex-CormorantGaramond-SemiBold-lf-ts1--base.tfm \
tex-CormorantGaramond-SemiBold-lf-ts1.tfm \
tex-CormorantGaramond-SemiBold-lf-ts1.vf \
tex-CormorantGaramond-SemiBold-osf-ly1.tfm \
tex-CormorantGaramond-SemiBold-osf-ot1.tfm \
tex-CormorantGaramond-SemiBold-osf-sc-ly1--base.tfm \
tex-CormorantGaramond-SemiBold-osf-sc-ly1.tfm \
tex-CormorantGaramond-SemiBold-osf-sc-ly1.vf \
tex-CormorantGaramond-SemiBold-osf-sc-ot1--base.tfm \
tex-CormorantGaramond-SemiBold-osf-sc-ot1.tfm \
tex-CormorantGaramond-SemiBold-osf-sc-ot1.vf \
tex-CormorantGaramond-SemiBold-osf-sc-t1--base.tfm \
tex-CormorantGaramond-SemiBold-osf-sc-t1.tfm \
tex-CormorantGaramond-SemiBold-osf-sc-t1.vf \
tex-CormorantGaramond-SemiBold-osf-sc-t2a.tfm \
tex-CormorantGaramond-SemiBold-osf-sc-t2b.tfm \
tex-CormorantGaramond-SemiBold-osf-sc-t2c.tfm \
tex-CormorantGaramond-SemiBold-osf-t1--base.tfm \
tex-CormorantGaramond-SemiBold-osf-t1.tfm \
tex-CormorantGaramond-SemiBold-osf-t1.vf \
tex-CormorantGaramond-SemiBold-osf-t2a.tfm \
tex-CormorantGaramond-SemiBold-osf-t2b.tfm \
tex-CormorantGaramond-SemiBold-osf-t2c.tfm \
tex-CormorantGaramond-SemiBold-osf-ts1--base.tfm \
tex-CormorantGaramond-SemiBold-osf-ts1.tfm \
tex-CormorantGaramond-SemiBold-osf-ts1.vf \
tex-CormorantGaramond-SemiBold-sup-ly1.tfm \
tex-CormorantGaramond-SemiBold-sup-ot1.tfm \
tex-CormorantGaramond-SemiBold-sup-t1--base.tfm \
tex-CormorantGaramond-SemiBold-sup-t1.tfm \
tex-CormorantGaramond-SemiBold-sup-t1.vf \
tex-CormorantGaramond-SemiBold-sup-t2a.tfm \
tex-CormorantGaramond-SemiBold-sup-t2b.tfm \
tex-CormorantGaramond-SemiBold-sup-t2c.tfm \
tex-CormorantGaramond-SemiBold-tlf-ly1.tfm \
tex-CormorantGaramond-SemiBold-tlf-ot1.tfm \
tex-CormorantGaramond-SemiBold-tlf-sc-ly1--base.tfm \
tex-CormorantGaramond-SemiBold-tlf-sc-ly1.tfm \
tex-CormorantGaramond-SemiBold-tlf-sc-ly1.vf \
tex-CormorantGaramond-SemiBold-tlf-sc-ot1--base.tfm \
tex-CormorantGaramond-SemiBold-tlf-sc-ot1.tfm \
tex-CormorantGaramond-SemiBold-tlf-sc-ot1.vf \
tex-CormorantGaramond-SemiBold-tlf-sc-t1--base.tfm \
tex-CormorantGaramond-SemiBold-tlf-sc-t1.tfm \
tex-CormorantGaramond-SemiBold-tlf-sc-t1.vf \
tex-CormorantGaramond-SemiBold-tlf-sc-t2a.tfm \
tex-CormorantGaramond-SemiBold-tlf-sc-t2b.tfm \
tex-CormorantGaramond-SemiBold-tlf-sc-t2c.tfm \
tex-CormorantGaramond-SemiBold-tlf-t1--base.tfm \
tex-CormorantGaramond-SemiBold-tlf-t1.tfm \
tex-CormorantGaramond-SemiBold-tlf-t1.vf \
tex-CormorantGaramond-SemiBold-tlf-t2a.tfm \
tex-CormorantGaramond-SemiBold-tlf-t2b.tfm \
tex-CormorantGaramond-SemiBold-tlf-t2c.tfm \
tex-CormorantGaramond-SemiBold-tlf-ts1--base.tfm \
tex-CormorantGaramond-SemiBold-tlf-ts1.tfm \
tex-CormorantGaramond-SemiBold-tlf-ts1.vf \
tex-CormorantGaramond-SemiBold-tosf-ly1.tfm \
tex-CormorantGaramond-SemiBold-tosf-ot1.tfm \
tex-CormorantGaramond-SemiBold-tosf-sc-ly1--base.tfm \
tex-CormorantGaramond-SemiBold-tosf-sc-ly1.tfm \
tex-CormorantGaramond-SemiBold-tosf-sc-ly1.vf \
tex-CormorantGaramond-SemiBold-tosf-sc-ot1--base.tfm \
tex-CormorantGaramond-SemiBold-tosf-sc-ot1.tfm \
tex-CormorantGaramond-SemiBold-tosf-sc-ot1.vf \
tex-CormorantGaramond-SemiBold-tosf-sc-t1--base.tfm \
tex-CormorantGaramond-SemiBold-tosf-sc-t1.tfm \
tex-CormorantGaramond-SemiBold-tosf-sc-t1.vf \
tex-CormorantGaramond-SemiBold-tosf-sc-t2a.tfm \
tex-CormorantGaramond-SemiBold-tosf-sc-t2b.tfm \
tex-CormorantGaramond-SemiBold-tosf-sc-t2c.tfm \
tex-CormorantGaramond-SemiBold-tosf-t1--base.tfm \
tex-CormorantGaramond-SemiBold-tosf-t1.tfm \
tex-CormorantGaramond-SemiBold-tosf-t1.vf \
tex-CormorantGaramond-SemiBold-tosf-t2a.tfm \
tex-CormorantGaramond-SemiBold-tosf-t2b.tfm \
tex-CormorantGaramond-SemiBold-tosf-t2c.tfm \
tex-CormorantGaramond-SemiBold-tosf-ts1--base.tfm \
tex-CormorantGaramond-SemiBold-tosf-ts1.tfm \
tex-CormorantGaramond-SemiBold-tosf-ts1.vf \
tex-CormorantGaramond-SemiBoldItalic-inf-ly1.tfm \
tex-CormorantGaramond-SemiBoldItalic-inf-ot1.tfm \
tex-CormorantGaramond-SemiBoldItalic-inf-t1--base.tfm \
tex-CormorantGaramond-SemiBoldItalic-inf-t1.tfm \
tex-CormorantGaramond-SemiBoldItalic-inf-t1.vf \
tex-CormorantGaramond-SemiBoldItalic-inf-t2a.tfm \
tex-CormorantGaramond-SemiBoldItalic-inf-t2b.tfm \
tex-CormorantGaramond-SemiBoldItalic-inf-t2c.tfm \
tex-CormorantGaramond-SemiBoldItalic-lf-ly1.tfm \
tex-CormorantGaramond-SemiBoldItalic-lf-ot1.tfm \
tex-CormorantGaramond-SemiBoldItalic-lf-t1--base.tfm \
tex-CormorantGaramond-SemiBoldItalic-lf-t1.tfm \
tex-CormorantGaramond-SemiBoldItalic-lf-t1.vf \
tex-CormorantGaramond-SemiBoldItalic-lf-t2a.tfm \
tex-CormorantGaramond-SemiBoldItalic-lf-t2b.tfm \
tex-CormorantGaramond-SemiBoldItalic-lf-t2c.tfm \
tex-CormorantGaramond-SemiBoldItalic-lf-ts1--base.tfm \
tex-CormorantGaramond-SemiBoldItalic-lf-ts1.tfm \
tex-CormorantGaramond-SemiBoldItalic-lf-ts1.vf \
tex-CormorantGaramond-SemiBoldItalic-osf-ly1.tfm \
tex-CormorantGaramond-SemiBoldItalic-osf-ot1.tfm \
tex-CormorantGaramond-SemiBoldItalic-osf-t1--base.tfm \
tex-CormorantGaramond-SemiBoldItalic-osf-t1.tfm \
tex-CormorantGaramond-SemiBoldItalic-osf-t1.vf \
tex-CormorantGaramond-SemiBoldItalic-osf-t2a.tfm \
tex-CormorantGaramond-SemiBoldItalic-osf-t2b.tfm \
tex-CormorantGaramond-SemiBoldItalic-osf-t2c.tfm \
tex-CormorantGaramond-SemiBoldItalic-osf-ts1--base.tfm \
tex-CormorantGaramond-SemiBoldItalic-osf-ts1.tfm \
tex-CormorantGaramond-SemiBoldItalic-osf-ts1.vf \
tex-CormorantGaramond-SemiBoldItalic-sup-ly1.tfm \
tex-CormorantGaramond-SemiBoldItalic-sup-ot1.tfm \
tex-CormorantGaramond-SemiBoldItalic-sup-t1--base.tfm \
tex-CormorantGaramond-SemiBoldItalic-sup-t1.tfm \
tex-CormorantGaramond-SemiBoldItalic-sup-t1.vf \
tex-CormorantGaramond-SemiBoldItalic-sup-t2a.tfm \
tex-CormorantGaramond-SemiBoldItalic-sup-t2b.tfm \
tex-CormorantGaramond-SemiBoldItalic-sup-t2c.tfm \
tex-CormorantGaramond-SemiBoldItalic-tlf-ly1.tfm \
tex-CormorantGaramond-SemiBoldItalic-tlf-ot1.tfm \
tex-CormorantGaramond-SemiBoldItalic-tlf-t1--base.tfm \
tex-CormorantGaramond-SemiBoldItalic-tlf-t1.tfm \
tex-CormorantGaramond-SemiBoldItalic-tlf-t1.vf \
tex-CormorantGaramond-SemiBoldItalic-tlf-t2a.tfm \
tex-CormorantGaramond-SemiBoldItalic-tlf-t2b.tfm \
tex-CormorantGaramond-SemiBoldItalic-tlf-t2c.tfm \
tex-CormorantGaramond-SemiBoldItalic-tlf-ts1--base.tfm \
tex-CormorantGaramond-SemiBoldItalic-tlf-ts1.tfm \
tex-CormorantGaramond-SemiBoldItalic-tlf-ts1.vf \
tex-CormorantGaramond-SemiBoldItalic-tosf-ly1.tfm \
tex-CormorantGaramond-SemiBoldItalic-tosf-ot1.tfm \
tex-CormorantGaramond-SemiBoldItalic-tosf-t1--base.tfm \
tex-CormorantGaramond-SemiBoldItalic-tosf-t1.tfm \
tex-CormorantGaramond-SemiBoldItalic-tosf-t1.vf \
tex-CormorantGaramond-SemiBoldItalic-tosf-t2a.tfm \
tex-CormorantGaramond-SemiBoldItalic-tosf-t2b.tfm \
tex-CormorantGaramond-SemiBoldItalic-tosf-t2c.tfm \
tex-CormorantGaramond-SemiBoldItalic-tosf-ts1--base.tfm \
tex-CormorantGaramond-SemiBoldItalic-tosf-ts1.tfm \
tex-CormorantGaramond-SemiBoldItalic-tosf-ts1.vf \
tex-CormorantGaramond.map \
tex-CormorantGaramond.sty \
tex-LY1CormorantGaramond-Inf.fd \
tex-LY1CormorantGaramond-LF.fd \
tex-LY1CormorantGaramond-OsF.fd \
tex-LY1CormorantGaramond-Sup.fd \
tex-LY1CormorantGaramond-TLF.fd \
tex-LY1CormorantGaramond-TOsF.fd \
tex-OT1CormorantGaramond-Inf.fd \
tex-OT1CormorantGaramond-LF.fd \
tex-OT1CormorantGaramond-OsF.fd \
tex-OT1CormorantGaramond-Sup.fd \
tex-OT1CormorantGaramond-TLF.fd \
tex-OT1CormorantGaramond-TOsF.fd \
tex-T1CormorantGaramond-Inf.fd \
tex-T1CormorantGaramond-LF.fd \
tex-T1CormorantGaramond-OsF.fd \
tex-T1CormorantGaramond-Sup.fd \
tex-T1CormorantGaramond-TLF.fd \
tex-T1CormorantGaramond-TOsF.fd \
tex-T2ACormorantGaramond-Inf.fd \
tex-T2ACormorantGaramond-LF.fd \
tex-T2ACormorantGaramond-OsF.fd \
tex-T2ACormorantGaramond-Sup.fd \
tex-T2ACormorantGaramond-TLF.fd \
tex-T2ACormorantGaramond-TOsF.fd \
tex-T2BCormorantGaramond-Inf.fd \
tex-T2BCormorantGaramond-LF.fd \
tex-T2BCormorantGaramond-OsF.fd \
tex-T2BCormorantGaramond-Sup.fd \
tex-T2BCormorantGaramond-TLF.fd \
tex-T2BCormorantGaramond-TOsF.fd \
tex-T2CCormorantGaramond-Inf.fd \
tex-T2CCormorantGaramond-LF.fd \
tex-T2CCormorantGaramond-OsF.fd \
tex-T2CCormorantGaramond-Sup.fd \
tex-T2CCormorantGaramond-TLF.fd \
tex-T2CCormorantGaramond-TOsF.fd \
tex-TS1CormorantGaramond-LF.fd \
tex-TS1CormorantGaramond-OsF.fd \
tex-TS1CormorantGaramond-TLF.fd \
tex-TS1CormorantGaramond-TOsF.fd \
tex-cgrm-2ahxjn.enc \
tex-cgrm-2fszuh.enc \
tex-cgrm-2qzove.enc \
tex-cgrm-2woykf.enc \
tex-cgrm-2xvhcw.enc \
tex-cgrm-33cvom.enc \
tex-cgrm-36gbzh.enc \
tex-cgrm-45xxtj.enc \
tex-cgrm-4fize4.enc \
tex-cgrm-554p77.enc \
tex-cgrm-575fly.enc \
tex-cgrm-5ezmem.enc \
tex-cgrm-5zuknm.enc \
tex-cgrm-6cgyqp.enc \
tex-cgrm-726bjo.enc \
tex-cgrm-7l65a5.enc \
tex-cgrm-ahqoow.enc \
tex-cgrm-baamnb.enc \
tex-cgrm-bndooo.enc \
tex-cgrm-cjaria.enc \
tex-cgrm-cpu34x.enc \
tex-cgrm-ctw2ju.enc \
tex-cgrm-czjvuz.enc \
tex-cgrm-edlrwy.enc \
tex-cgrm-ehskq2.enc \
tex-cgrm-ezmsqi.enc \
tex-cgrm-fnl4sj.enc \
tex-cgrm-fqbaih.enc \
tex-cgrm-g7ehha.enc \
tex-cgrm-gfgzzm.enc \
tex-cgrm-ggoxrw.enc \
tex-cgrm-goqtbf.enc \
tex-cgrm-hnmd4t.enc \
tex-cgrm-ho7x2y.enc \
tex-cgrm-i4ztt6.enc \
tex-cgrm-imua2m.enc \
tex-cgrm-ira4mj.enc \
tex-cgrm-iuhjfz.enc \
tex-cgrm-iyf2ai.enc \
tex-cgrm-j2hlib.enc \
tex-cgrm-j5xrmg.enc \
tex-cgrm-jg7lls.enc \
tex-cgrm-jwbavo.enc \
tex-cgrm-k54atz.enc \
tex-cgrm-kbv5uy.enc \
tex-cgrm-ksmxc6.enc \
tex-cgrm-kwxzcp.enc \
tex-cgrm-l5f566.enc \
tex-cgrm-ldw23p.enc \
tex-cgrm-lksf3x.enc \
tex-cgrm-mcvd3c.enc \
tex-cgrm-mq3pk7.enc \
tex-cgrm-myrl74.enc \
tex-cgrm-nniu67.enc \
tex-cgrm-nswxfs.enc \
tex-cgrm-nxkups.enc \
tex-cgrm-nxzswi.enc \
tex-cgrm-od3ly4.enc \
tex-cgrm-olzkph.enc \
tex-cgrm-p4fks4.enc \
tex-cgrm-p5fsj2.enc \
tex-cgrm-payxmf.enc \
tex-cgrm-pm4rjs.enc \
tex-cgrm-qaa67y.enc \
tex-cgrm-qco72e.enc \
tex-cgrm-qnkxku.enc \
tex-cgrm-qrc2n2.enc \
tex-cgrm-rnb5y6.enc \
tex-cgrm-rohdbu.enc \
tex-cgrm-ry5pl7.enc \
tex-cgrm-s2pyjf.enc \
tex-cgrm-s4zbbx.enc \
tex-cgrm-sfoqzm.enc \
tex-cgrm-sowbon.enc \
tex-cgrm-txosmw.enc \
tex-cgrm-tzoazu.enc \
tex-cgrm-usix3v.enc \
tex-cgrm-uys5qk.enc \
tex-cgrm-v2z4dl.enc \
tex-cgrm-v7t4yx.enc \
tex-cgrm-vabk2p.enc \
tex-cgrm-vdpe4c.enc \
tex-cgrm-vnv5uk.enc \
tex-cgrm-vqhfd3.enc \
tex-cgrm-vs5evg.enc \
tex-cgrm-vuc6nl.enc \
tex-cgrm-xrzidp.enc \
tex-cgrm-xwhmgi.enc \
tex-cgrm-xzjjkx.enc \
tex-cgrm-y22u7a.enc \
tex-cgrm-yah5fp.enc \
tex-cgrm-ycbsw5.enc \
tex-cgrm-ye4dng.enc \
tex-cgrm-yifvzr.enc \
tex-cgrm-yksu3h.enc \
tex-cgrm-yo6qap.enc \
tex-cgrm-zc6byq.enc \
tex-cgrm-zcfdr3.enc \
tex-cgrm-zkhuis.enc \
tex-cgrm-zzgqip.enc \
texlive-cormorantgaramond"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontaxes.sty \
tex-fontenc.sty \
tex-fontspec.sty \
tex-ifluatex.sty \
tex-ifxetex.sty \
tex-mweights.sty \
tex-textcomp.sty \
tex-updmap.cfg \
tex-xkeyval.sty \
texlive \
texlive-cormorantgaramond-fonts \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
