SUMMARY = "Dynamically typeset numbers and values in LaTeX through 'symbolic links'"
DESCRIPTION = "This package dynamically typesets values generated by different \
kinds of scripts in LaTeX through the use of 'symbolic links' \
(which are not in any way related to the 'symbolic links' used \
in UNIX systems!). The aim is to reduce errors resulting from \
out-of-date numbers by directly setting them in the number \
generating file and importing a 'symbolic link' into the LaTeX \
source file. It can be used to import not only numerical \
values, but strings and pieces of code are also possible. \
Currently only MATLAB and Python are supported to produce \
Dynamic Number list files."
LICENSE = "LPPL-1.0"

PV = "2023.209.0.0.1.3svn38726"

RPM_NAME = "texlive-dynamicnumber-2023.209.0.0.1.3svn38726-54.2.noarch.rpm"
RPM_HASH = "f344be2375036f6724aa15ee78b4f32e274d0b21de90b0e14c26259daeb6882b3c7a256e7ec6aff3674cb22ba474c9c7472ce7921e88dbb6617244badf0f182c"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-dynamicnumber.sty \
texlive-dynamicnumber"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-pgfkeys.sty \
tex-xparse.sty \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
