SUMMARY = "Using the free Chivo fonts with LaTeX"
DESCRIPTION = "This work provides the necessary files to use the Chivo fonts \
with LaTeX. Chivo is a set of eight fonts provided by Hector \
Gatti & Omnibus Team under the Open Font License (OFL), version \
1.1. The fonts are copyright (c) 2011-2019, Omnibus-Type."
LICENSE = "OFL-1.1"

PV = "2023.201.2.2svn65029"

RPM_NAME = "texlive-chivo-2023.201.2.2svn65029-53.1.noarch.rpm"
RPM_HASH = "e49d3a750874087ee578eab9d6088e2aa711b5b1aff8e538b0f7f1a1ae7dffcba5bec586416c49f00d998d036f6fd0f1782095e58d908a54a9b17c86fbe25bad"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-Chivo-Black-dnom-ly1--base.tfm \
tex-Chivo-Black-dnom-ly1.tfm \
tex-Chivo-Black-dnom-ly1.vf \
tex-Chivo-Black-dnom-ot1--base.tfm \
tex-Chivo-Black-dnom-ot1.tfm \
tex-Chivo-Black-dnom-ot1.vf \
tex-Chivo-Black-dnom-t1--base.tfm \
tex-Chivo-Black-dnom-t1.tfm \
tex-Chivo-Black-dnom-t1.vf \
tex-Chivo-Black-inf-ly1--base.tfm \
tex-Chivo-Black-inf-ly1.tfm \
tex-Chivo-Black-inf-ly1.vf \
tex-Chivo-Black-inf-ot1--base.tfm \
tex-Chivo-Black-inf-ot1.tfm \
tex-Chivo-Black-inf-ot1.vf \
tex-Chivo-Black-inf-t1--base.tfm \
tex-Chivo-Black-inf-t1.tfm \
tex-Chivo-Black-inf-t1.vf \
tex-Chivo-Black-lf-ly1--base.tfm \
tex-Chivo-Black-lf-ly1.tfm \
tex-Chivo-Black-lf-ly1.vf \
tex-Chivo-Black-lf-ot1--base.tfm \
tex-Chivo-Black-lf-ot1.tfm \
tex-Chivo-Black-lf-ot1.vf \
tex-Chivo-Black-lf-t1--base.tfm \
tex-Chivo-Black-lf-t1.tfm \
tex-Chivo-Black-lf-t1.vf \
tex-Chivo-Black-lf-ts1--base.tfm \
tex-Chivo-Black-lf-ts1.tfm \
tex-Chivo-Black-lf-ts1.vf \
tex-Chivo-Black-numr-ly1--base.tfm \
tex-Chivo-Black-numr-ly1.tfm \
tex-Chivo-Black-numr-ly1.vf \
tex-Chivo-Black-numr-ot1--base.tfm \
tex-Chivo-Black-numr-ot1.tfm \
tex-Chivo-Black-numr-ot1.vf \
tex-Chivo-Black-numr-t1--base.tfm \
tex-Chivo-Black-numr-t1.tfm \
tex-Chivo-Black-numr-t1.vf \
tex-Chivo-Black-osf-ly1--base.tfm \
tex-Chivo-Black-osf-ly1.tfm \
tex-Chivo-Black-osf-ly1.vf \
tex-Chivo-Black-osf-ot1--base.tfm \
tex-Chivo-Black-osf-ot1.tfm \
tex-Chivo-Black-osf-ot1.vf \
tex-Chivo-Black-osf-t1--base.tfm \
tex-Chivo-Black-osf-t1.tfm \
tex-Chivo-Black-osf-t1.vf \
tex-Chivo-Black-osf-ts1--base.tfm \
tex-Chivo-Black-osf-ts1.tfm \
tex-Chivo-Black-osf-ts1.vf \
tex-Chivo-Black-sup-ly1--base.tfm \
tex-Chivo-Black-sup-ly1.tfm \
tex-Chivo-Black-sup-ly1.vf \
tex-Chivo-Black-sup-ot1--base.tfm \
tex-Chivo-Black-sup-ot1.tfm \
tex-Chivo-Black-sup-ot1.vf \
tex-Chivo-Black-sup-t1--base.tfm \
tex-Chivo-Black-sup-t1.tfm \
tex-Chivo-Black-sup-t1.vf \
tex-Chivo-Black-tlf-ly1--base.tfm \
tex-Chivo-Black-tlf-ly1.tfm \
tex-Chivo-Black-tlf-ly1.vf \
tex-Chivo-Black-tlf-ot1--base.tfm \
tex-Chivo-Black-tlf-ot1.tfm \
tex-Chivo-Black-tlf-ot1.vf \
tex-Chivo-Black-tlf-t1--base.tfm \
tex-Chivo-Black-tlf-t1.tfm \
tex-Chivo-Black-tlf-t1.vf \
tex-Chivo-Black-tlf-ts1--base.tfm \
tex-Chivo-Black-tlf-ts1.tfm \
tex-Chivo-Black-tlf-ts1.vf \
tex-Chivo-Black-tosf-ly1--base.tfm \
tex-Chivo-Black-tosf-ly1.tfm \
tex-Chivo-Black-tosf-ly1.vf \
tex-Chivo-Black-tosf-ot1--base.tfm \
tex-Chivo-Black-tosf-ot1.tfm \
tex-Chivo-Black-tosf-ot1.vf \
tex-Chivo-Black-tosf-t1--base.tfm \
tex-Chivo-Black-tosf-t1.tfm \
tex-Chivo-Black-tosf-t1.vf \
tex-Chivo-Black-tosf-ts1--base.tfm \
tex-Chivo-Black-tosf-ts1.tfm \
tex-Chivo-Black-tosf-ts1.vf \
tex-Chivo-BlackItalic-dnom-ly1--base.tfm \
tex-Chivo-BlackItalic-dnom-ly1.tfm \
tex-Chivo-BlackItalic-dnom-ly1.vf \
tex-Chivo-BlackItalic-dnom-ot1--base.tfm \
tex-Chivo-BlackItalic-dnom-ot1.tfm \
tex-Chivo-BlackItalic-dnom-ot1.vf \
tex-Chivo-BlackItalic-dnom-t1--base.tfm \
tex-Chivo-BlackItalic-dnom-t1.tfm \
tex-Chivo-BlackItalic-dnom-t1.vf \
tex-Chivo-BlackItalic-inf-ly1--base.tfm \
tex-Chivo-BlackItalic-inf-ly1.tfm \
tex-Chivo-BlackItalic-inf-ly1.vf \
tex-Chivo-BlackItalic-inf-ot1--base.tfm \
tex-Chivo-BlackItalic-inf-ot1.tfm \
tex-Chivo-BlackItalic-inf-ot1.vf \
tex-Chivo-BlackItalic-inf-t1--base.tfm \
tex-Chivo-BlackItalic-inf-t1.tfm \
tex-Chivo-BlackItalic-inf-t1.vf \
tex-Chivo-BlackItalic-lf-ly1--base.tfm \
tex-Chivo-BlackItalic-lf-ly1.tfm \
tex-Chivo-BlackItalic-lf-ly1.vf \
tex-Chivo-BlackItalic-lf-ot1--base.tfm \
tex-Chivo-BlackItalic-lf-ot1.tfm \
tex-Chivo-BlackItalic-lf-ot1.vf \
tex-Chivo-BlackItalic-lf-t1--base.tfm \
tex-Chivo-BlackItalic-lf-t1.tfm \
tex-Chivo-BlackItalic-lf-t1.vf \
tex-Chivo-BlackItalic-lf-ts1--base.tfm \
tex-Chivo-BlackItalic-lf-ts1.tfm \
tex-Chivo-BlackItalic-lf-ts1.vf \
tex-Chivo-BlackItalic-numr-ly1--base.tfm \
tex-Chivo-BlackItalic-numr-ly1.tfm \
tex-Chivo-BlackItalic-numr-ly1.vf \
tex-Chivo-BlackItalic-numr-ot1--base.tfm \
tex-Chivo-BlackItalic-numr-ot1.tfm \
tex-Chivo-BlackItalic-numr-ot1.vf \
tex-Chivo-BlackItalic-numr-t1--base.tfm \
tex-Chivo-BlackItalic-numr-t1.tfm \
tex-Chivo-BlackItalic-numr-t1.vf \
tex-Chivo-BlackItalic-osf-ly1--base.tfm \
tex-Chivo-BlackItalic-osf-ly1.tfm \
tex-Chivo-BlackItalic-osf-ly1.vf \
tex-Chivo-BlackItalic-osf-ot1--base.tfm \
tex-Chivo-BlackItalic-osf-ot1.tfm \
tex-Chivo-BlackItalic-osf-ot1.vf \
tex-Chivo-BlackItalic-osf-t1--base.tfm \
tex-Chivo-BlackItalic-osf-t1.tfm \
tex-Chivo-BlackItalic-osf-t1.vf \
tex-Chivo-BlackItalic-osf-ts1--base.tfm \
tex-Chivo-BlackItalic-osf-ts1.tfm \
tex-Chivo-BlackItalic-osf-ts1.vf \
tex-Chivo-BlackItalic-sup-ly1--base.tfm \
tex-Chivo-BlackItalic-sup-ly1.tfm \
tex-Chivo-BlackItalic-sup-ly1.vf \
tex-Chivo-BlackItalic-sup-ot1--base.tfm \
tex-Chivo-BlackItalic-sup-ot1.tfm \
tex-Chivo-BlackItalic-sup-ot1.vf \
tex-Chivo-BlackItalic-sup-t1--base.tfm \
tex-Chivo-BlackItalic-sup-t1.tfm \
tex-Chivo-BlackItalic-sup-t1.vf \
tex-Chivo-BlackItalic-tlf-ly1--base.tfm \
tex-Chivo-BlackItalic-tlf-ly1.tfm \
tex-Chivo-BlackItalic-tlf-ly1.vf \
tex-Chivo-BlackItalic-tlf-ot1--base.tfm \
tex-Chivo-BlackItalic-tlf-ot1.tfm \
tex-Chivo-BlackItalic-tlf-ot1.vf \
tex-Chivo-BlackItalic-tlf-t1--base.tfm \
tex-Chivo-BlackItalic-tlf-t1.tfm \
tex-Chivo-BlackItalic-tlf-t1.vf \
tex-Chivo-BlackItalic-tlf-ts1--base.tfm \
tex-Chivo-BlackItalic-tlf-ts1.tfm \
tex-Chivo-BlackItalic-tlf-ts1.vf \
tex-Chivo-BlackItalic-tosf-ly1--base.tfm \
tex-Chivo-BlackItalic-tosf-ly1.tfm \
tex-Chivo-BlackItalic-tosf-ly1.vf \
tex-Chivo-BlackItalic-tosf-ot1--base.tfm \
tex-Chivo-BlackItalic-tosf-ot1.tfm \
tex-Chivo-BlackItalic-tosf-ot1.vf \
tex-Chivo-BlackItalic-tosf-t1--base.tfm \
tex-Chivo-BlackItalic-tosf-t1.tfm \
tex-Chivo-BlackItalic-tosf-t1.vf \
tex-Chivo-BlackItalic-tosf-ts1--base.tfm \
tex-Chivo-BlackItalic-tosf-ts1.tfm \
tex-Chivo-BlackItalic-tosf-ts1.vf \
tex-Chivo-Bold-dnom-ly1--base.tfm \
tex-Chivo-Bold-dnom-ly1.tfm \
tex-Chivo-Bold-dnom-ly1.vf \
tex-Chivo-Bold-dnom-ot1--base.tfm \
tex-Chivo-Bold-dnom-ot1.tfm \
tex-Chivo-Bold-dnom-ot1.vf \
tex-Chivo-Bold-dnom-t1--base.tfm \
tex-Chivo-Bold-dnom-t1.tfm \
tex-Chivo-Bold-dnom-t1.vf \
tex-Chivo-Bold-inf-ly1--base.tfm \
tex-Chivo-Bold-inf-ly1.tfm \
tex-Chivo-Bold-inf-ly1.vf \
tex-Chivo-Bold-inf-ot1--base.tfm \
tex-Chivo-Bold-inf-ot1.tfm \
tex-Chivo-Bold-inf-ot1.vf \
tex-Chivo-Bold-inf-t1--base.tfm \
tex-Chivo-Bold-inf-t1.tfm \
tex-Chivo-Bold-inf-t1.vf \
tex-Chivo-Bold-lf-ly1--base.tfm \
tex-Chivo-Bold-lf-ly1.tfm \
tex-Chivo-Bold-lf-ly1.vf \
tex-Chivo-Bold-lf-ot1--base.tfm \
tex-Chivo-Bold-lf-ot1.tfm \
tex-Chivo-Bold-lf-ot1.vf \
tex-Chivo-Bold-lf-t1--base.tfm \
tex-Chivo-Bold-lf-t1.tfm \
tex-Chivo-Bold-lf-t1.vf \
tex-Chivo-Bold-lf-ts1--base.tfm \
tex-Chivo-Bold-lf-ts1.tfm \
tex-Chivo-Bold-lf-ts1.vf \
tex-Chivo-Bold-numr-ly1--base.tfm \
tex-Chivo-Bold-numr-ly1.tfm \
tex-Chivo-Bold-numr-ly1.vf \
tex-Chivo-Bold-numr-ot1--base.tfm \
tex-Chivo-Bold-numr-ot1.tfm \
tex-Chivo-Bold-numr-ot1.vf \
tex-Chivo-Bold-numr-t1--base.tfm \
tex-Chivo-Bold-numr-t1.tfm \
tex-Chivo-Bold-numr-t1.vf \
tex-Chivo-Bold-osf-ly1--base.tfm \
tex-Chivo-Bold-osf-ly1.tfm \
tex-Chivo-Bold-osf-ly1.vf \
tex-Chivo-Bold-osf-ot1--base.tfm \
tex-Chivo-Bold-osf-ot1.tfm \
tex-Chivo-Bold-osf-ot1.vf \
tex-Chivo-Bold-osf-t1--base.tfm \
tex-Chivo-Bold-osf-t1.tfm \
tex-Chivo-Bold-osf-t1.vf \
tex-Chivo-Bold-osf-ts1--base.tfm \
tex-Chivo-Bold-osf-ts1.tfm \
tex-Chivo-Bold-osf-ts1.vf \
tex-Chivo-Bold-sup-ly1--base.tfm \
tex-Chivo-Bold-sup-ly1.tfm \
tex-Chivo-Bold-sup-ly1.vf \
tex-Chivo-Bold-sup-ot1--base.tfm \
tex-Chivo-Bold-sup-ot1.tfm \
tex-Chivo-Bold-sup-ot1.vf \
tex-Chivo-Bold-sup-t1--base.tfm \
tex-Chivo-Bold-sup-t1.tfm \
tex-Chivo-Bold-sup-t1.vf \
tex-Chivo-Bold-tlf-ly1--base.tfm \
tex-Chivo-Bold-tlf-ly1.tfm \
tex-Chivo-Bold-tlf-ly1.vf \
tex-Chivo-Bold-tlf-ot1--base.tfm \
tex-Chivo-Bold-tlf-ot1.tfm \
tex-Chivo-Bold-tlf-ot1.vf \
tex-Chivo-Bold-tlf-t1--base.tfm \
tex-Chivo-Bold-tlf-t1.tfm \
tex-Chivo-Bold-tlf-t1.vf \
tex-Chivo-Bold-tlf-ts1--base.tfm \
tex-Chivo-Bold-tlf-ts1.tfm \
tex-Chivo-Bold-tlf-ts1.vf \
tex-Chivo-Bold-tosf-ly1--base.tfm \
tex-Chivo-Bold-tosf-ly1.tfm \
tex-Chivo-Bold-tosf-ly1.vf \
tex-Chivo-Bold-tosf-ot1--base.tfm \
tex-Chivo-Bold-tosf-ot1.tfm \
tex-Chivo-Bold-tosf-ot1.vf \
tex-Chivo-Bold-tosf-t1--base.tfm \
tex-Chivo-Bold-tosf-t1.tfm \
tex-Chivo-Bold-tosf-t1.vf \
tex-Chivo-Bold-tosf-ts1--base.tfm \
tex-Chivo-Bold-tosf-ts1.tfm \
tex-Chivo-Bold-tosf-ts1.vf \
tex-Chivo-BoldItalic-dnom-ly1--base.tfm \
tex-Chivo-BoldItalic-dnom-ly1.tfm \
tex-Chivo-BoldItalic-dnom-ly1.vf \
tex-Chivo-BoldItalic-dnom-ot1--base.tfm \
tex-Chivo-BoldItalic-dnom-ot1.tfm \
tex-Chivo-BoldItalic-dnom-ot1.vf \
tex-Chivo-BoldItalic-dnom-t1--base.tfm \
tex-Chivo-BoldItalic-dnom-t1.tfm \
tex-Chivo-BoldItalic-dnom-t1.vf \
tex-Chivo-BoldItalic-inf-ly1--base.tfm \
tex-Chivo-BoldItalic-inf-ly1.tfm \
tex-Chivo-BoldItalic-inf-ly1.vf \
tex-Chivo-BoldItalic-inf-ot1--base.tfm \
tex-Chivo-BoldItalic-inf-ot1.tfm \
tex-Chivo-BoldItalic-inf-ot1.vf \
tex-Chivo-BoldItalic-inf-t1--base.tfm \
tex-Chivo-BoldItalic-inf-t1.tfm \
tex-Chivo-BoldItalic-inf-t1.vf \
tex-Chivo-BoldItalic-lf-ly1--base.tfm \
tex-Chivo-BoldItalic-lf-ly1.tfm \
tex-Chivo-BoldItalic-lf-ly1.vf \
tex-Chivo-BoldItalic-lf-ot1--base.tfm \
tex-Chivo-BoldItalic-lf-ot1.tfm \
tex-Chivo-BoldItalic-lf-ot1.vf \
tex-Chivo-BoldItalic-lf-t1--base.tfm \
tex-Chivo-BoldItalic-lf-t1.tfm \
tex-Chivo-BoldItalic-lf-t1.vf \
tex-Chivo-BoldItalic-lf-ts1--base.tfm \
tex-Chivo-BoldItalic-lf-ts1.tfm \
tex-Chivo-BoldItalic-lf-ts1.vf \
tex-Chivo-BoldItalic-numr-ly1--base.tfm \
tex-Chivo-BoldItalic-numr-ly1.tfm \
tex-Chivo-BoldItalic-numr-ly1.vf \
tex-Chivo-BoldItalic-numr-ot1--base.tfm \
tex-Chivo-BoldItalic-numr-ot1.tfm \
tex-Chivo-BoldItalic-numr-ot1.vf \
tex-Chivo-BoldItalic-numr-t1--base.tfm \
tex-Chivo-BoldItalic-numr-t1.tfm \
tex-Chivo-BoldItalic-numr-t1.vf \
tex-Chivo-BoldItalic-osf-ly1--base.tfm \
tex-Chivo-BoldItalic-osf-ly1.tfm \
tex-Chivo-BoldItalic-osf-ly1.vf \
tex-Chivo-BoldItalic-osf-ot1--base.tfm \
tex-Chivo-BoldItalic-osf-ot1.tfm \
tex-Chivo-BoldItalic-osf-ot1.vf \
tex-Chivo-BoldItalic-osf-t1--base.tfm \
tex-Chivo-BoldItalic-osf-t1.tfm \
tex-Chivo-BoldItalic-osf-t1.vf \
tex-Chivo-BoldItalic-osf-ts1--base.tfm \
tex-Chivo-BoldItalic-osf-ts1.tfm \
tex-Chivo-BoldItalic-osf-ts1.vf \
tex-Chivo-BoldItalic-sup-ly1--base.tfm \
tex-Chivo-BoldItalic-sup-ly1.tfm \
tex-Chivo-BoldItalic-sup-ly1.vf \
tex-Chivo-BoldItalic-sup-ot1--base.tfm \
tex-Chivo-BoldItalic-sup-ot1.tfm \
tex-Chivo-BoldItalic-sup-ot1.vf \
tex-Chivo-BoldItalic-sup-t1--base.tfm \
tex-Chivo-BoldItalic-sup-t1.tfm \
tex-Chivo-BoldItalic-sup-t1.vf \
tex-Chivo-BoldItalic-tlf-ly1--base.tfm \
tex-Chivo-BoldItalic-tlf-ly1.tfm \
tex-Chivo-BoldItalic-tlf-ly1.vf \
tex-Chivo-BoldItalic-tlf-ot1--base.tfm \
tex-Chivo-BoldItalic-tlf-ot1.tfm \
tex-Chivo-BoldItalic-tlf-ot1.vf \
tex-Chivo-BoldItalic-tlf-t1--base.tfm \
tex-Chivo-BoldItalic-tlf-t1.tfm \
tex-Chivo-BoldItalic-tlf-t1.vf \
tex-Chivo-BoldItalic-tlf-ts1--base.tfm \
tex-Chivo-BoldItalic-tlf-ts1.tfm \
tex-Chivo-BoldItalic-tlf-ts1.vf \
tex-Chivo-BoldItalic-tosf-ly1--base.tfm \
tex-Chivo-BoldItalic-tosf-ly1.tfm \
tex-Chivo-BoldItalic-tosf-ly1.vf \
tex-Chivo-BoldItalic-tosf-ot1--base.tfm \
tex-Chivo-BoldItalic-tosf-ot1.tfm \
tex-Chivo-BoldItalic-tosf-ot1.vf \
tex-Chivo-BoldItalic-tosf-t1--base.tfm \
tex-Chivo-BoldItalic-tosf-t1.tfm \
tex-Chivo-BoldItalic-tosf-t1.vf \
tex-Chivo-BoldItalic-tosf-ts1--base.tfm \
tex-Chivo-BoldItalic-tosf-ts1.tfm \
tex-Chivo-BoldItalic-tosf-ts1.vf \
tex-Chivo-ExtraBold-dnom-ly1--base.tfm \
tex-Chivo-ExtraBold-dnom-ly1.tfm \
tex-Chivo-ExtraBold-dnom-ly1.vf \
tex-Chivo-ExtraBold-dnom-ot1--base.tfm \
tex-Chivo-ExtraBold-dnom-ot1.tfm \
tex-Chivo-ExtraBold-dnom-ot1.vf \
tex-Chivo-ExtraBold-dnom-t1--base.tfm \
tex-Chivo-ExtraBold-dnom-t1.tfm \
tex-Chivo-ExtraBold-dnom-t1.vf \
tex-Chivo-ExtraBold-inf-ly1--base.tfm \
tex-Chivo-ExtraBold-inf-ly1.tfm \
tex-Chivo-ExtraBold-inf-ly1.vf \
tex-Chivo-ExtraBold-inf-ot1--base.tfm \
tex-Chivo-ExtraBold-inf-ot1.tfm \
tex-Chivo-ExtraBold-inf-ot1.vf \
tex-Chivo-ExtraBold-inf-t1--base.tfm \
tex-Chivo-ExtraBold-inf-t1.tfm \
tex-Chivo-ExtraBold-inf-t1.vf \
tex-Chivo-ExtraBold-lf-ly1--base.tfm \
tex-Chivo-ExtraBold-lf-ly1.tfm \
tex-Chivo-ExtraBold-lf-ly1.vf \
tex-Chivo-ExtraBold-lf-ot1--base.tfm \
tex-Chivo-ExtraBold-lf-ot1.tfm \
tex-Chivo-ExtraBold-lf-ot1.vf \
tex-Chivo-ExtraBold-lf-t1--base.tfm \
tex-Chivo-ExtraBold-lf-t1.tfm \
tex-Chivo-ExtraBold-lf-t1.vf \
tex-Chivo-ExtraBold-lf-ts1--base.tfm \
tex-Chivo-ExtraBold-lf-ts1.tfm \
tex-Chivo-ExtraBold-lf-ts1.vf \
tex-Chivo-ExtraBold-numr-ly1--base.tfm \
tex-Chivo-ExtraBold-numr-ly1.tfm \
tex-Chivo-ExtraBold-numr-ly1.vf \
tex-Chivo-ExtraBold-numr-ot1--base.tfm \
tex-Chivo-ExtraBold-numr-ot1.tfm \
tex-Chivo-ExtraBold-numr-ot1.vf \
tex-Chivo-ExtraBold-numr-t1--base.tfm \
tex-Chivo-ExtraBold-numr-t1.tfm \
tex-Chivo-ExtraBold-numr-t1.vf \
tex-Chivo-ExtraBold-osf-ly1--base.tfm \
tex-Chivo-ExtraBold-osf-ly1.tfm \
tex-Chivo-ExtraBold-osf-ly1.vf \
tex-Chivo-ExtraBold-osf-ot1--base.tfm \
tex-Chivo-ExtraBold-osf-ot1.tfm \
tex-Chivo-ExtraBold-osf-ot1.vf \
tex-Chivo-ExtraBold-osf-t1--base.tfm \
tex-Chivo-ExtraBold-osf-t1.tfm \
tex-Chivo-ExtraBold-osf-t1.vf \
tex-Chivo-ExtraBold-osf-ts1--base.tfm \
tex-Chivo-ExtraBold-osf-ts1.tfm \
tex-Chivo-ExtraBold-osf-ts1.vf \
tex-Chivo-ExtraBold-sup-ly1--base.tfm \
tex-Chivo-ExtraBold-sup-ly1.tfm \
tex-Chivo-ExtraBold-sup-ly1.vf \
tex-Chivo-ExtraBold-sup-ot1--base.tfm \
tex-Chivo-ExtraBold-sup-ot1.tfm \
tex-Chivo-ExtraBold-sup-ot1.vf \
tex-Chivo-ExtraBold-sup-t1--base.tfm \
tex-Chivo-ExtraBold-sup-t1.tfm \
tex-Chivo-ExtraBold-sup-t1.vf \
tex-Chivo-ExtraBold-tlf-ly1--base.tfm \
tex-Chivo-ExtraBold-tlf-ly1.tfm \
tex-Chivo-ExtraBold-tlf-ly1.vf \
tex-Chivo-ExtraBold-tlf-ot1--base.tfm \
tex-Chivo-ExtraBold-tlf-ot1.tfm \
tex-Chivo-ExtraBold-tlf-ot1.vf \
tex-Chivo-ExtraBold-tlf-t1--base.tfm \
tex-Chivo-ExtraBold-tlf-t1.tfm \
tex-Chivo-ExtraBold-tlf-t1.vf \
tex-Chivo-ExtraBold-tlf-ts1--base.tfm \
tex-Chivo-ExtraBold-tlf-ts1.tfm \
tex-Chivo-ExtraBold-tlf-ts1.vf \
tex-Chivo-ExtraBold-tosf-ly1--base.tfm \
tex-Chivo-ExtraBold-tosf-ly1.tfm \
tex-Chivo-ExtraBold-tosf-ly1.vf \
tex-Chivo-ExtraBold-tosf-ot1--base.tfm \
tex-Chivo-ExtraBold-tosf-ot1.tfm \
tex-Chivo-ExtraBold-tosf-ot1.vf \
tex-Chivo-ExtraBold-tosf-t1--base.tfm \
tex-Chivo-ExtraBold-tosf-t1.tfm \
tex-Chivo-ExtraBold-tosf-t1.vf \
tex-Chivo-ExtraBold-tosf-ts1--base.tfm \
tex-Chivo-ExtraBold-tosf-ts1.tfm \
tex-Chivo-ExtraBold-tosf-ts1.vf \
tex-Chivo-ExtraBoldItalic-dnom-ly1--base.tfm \
tex-Chivo-ExtraBoldItalic-dnom-ly1.tfm \
tex-Chivo-ExtraBoldItalic-dnom-ly1.vf \
tex-Chivo-ExtraBoldItalic-dnom-ot1--base.tfm \
tex-Chivo-ExtraBoldItalic-dnom-ot1.tfm \
tex-Chivo-ExtraBoldItalic-dnom-ot1.vf \
tex-Chivo-ExtraBoldItalic-dnom-t1--base.tfm \
tex-Chivo-ExtraBoldItalic-dnom-t1.tfm \
tex-Chivo-ExtraBoldItalic-dnom-t1.vf \
tex-Chivo-ExtraBoldItalic-inf-ly1--base.tfm \
tex-Chivo-ExtraBoldItalic-inf-ly1.tfm \
tex-Chivo-ExtraBoldItalic-inf-ly1.vf \
tex-Chivo-ExtraBoldItalic-inf-ot1--base.tfm \
tex-Chivo-ExtraBoldItalic-inf-ot1.tfm \
tex-Chivo-ExtraBoldItalic-inf-ot1.vf \
tex-Chivo-ExtraBoldItalic-inf-t1--base.tfm \
tex-Chivo-ExtraBoldItalic-inf-t1.tfm \
tex-Chivo-ExtraBoldItalic-inf-t1.vf \
tex-Chivo-ExtraBoldItalic-lf-ly1--base.tfm \
tex-Chivo-ExtraBoldItalic-lf-ly1.tfm \
tex-Chivo-ExtraBoldItalic-lf-ly1.vf \
tex-Chivo-ExtraBoldItalic-lf-ot1--base.tfm \
tex-Chivo-ExtraBoldItalic-lf-ot1.tfm \
tex-Chivo-ExtraBoldItalic-lf-ot1.vf \
tex-Chivo-ExtraBoldItalic-lf-t1--base.tfm \
tex-Chivo-ExtraBoldItalic-lf-t1.tfm \
tex-Chivo-ExtraBoldItalic-lf-t1.vf \
tex-Chivo-ExtraBoldItalic-lf-ts1--base.tfm \
tex-Chivo-ExtraBoldItalic-lf-ts1.tfm \
tex-Chivo-ExtraBoldItalic-lf-ts1.vf \
tex-Chivo-ExtraBoldItalic-numr-ly1--base.tfm \
tex-Chivo-ExtraBoldItalic-numr-ly1.tfm \
tex-Chivo-ExtraBoldItalic-numr-ly1.vf \
tex-Chivo-ExtraBoldItalic-numr-ot1--base.tfm \
tex-Chivo-ExtraBoldItalic-numr-ot1.tfm \
tex-Chivo-ExtraBoldItalic-numr-ot1.vf \
tex-Chivo-ExtraBoldItalic-numr-t1--base.tfm \
tex-Chivo-ExtraBoldItalic-numr-t1.tfm \
tex-Chivo-ExtraBoldItalic-numr-t1.vf \
tex-Chivo-ExtraBoldItalic-osf-ly1--base.tfm \
tex-Chivo-ExtraBoldItalic-osf-ly1.tfm \
tex-Chivo-ExtraBoldItalic-osf-ly1.vf \
tex-Chivo-ExtraBoldItalic-osf-ot1--base.tfm \
tex-Chivo-ExtraBoldItalic-osf-ot1.tfm \
tex-Chivo-ExtraBoldItalic-osf-ot1.vf \
tex-Chivo-ExtraBoldItalic-osf-t1--base.tfm \
tex-Chivo-ExtraBoldItalic-osf-t1.tfm \
tex-Chivo-ExtraBoldItalic-osf-t1.vf \
tex-Chivo-ExtraBoldItalic-osf-ts1--base.tfm \
tex-Chivo-ExtraBoldItalic-osf-ts1.tfm \
tex-Chivo-ExtraBoldItalic-osf-ts1.vf \
tex-Chivo-ExtraBoldItalic-sup-ly1--base.tfm \
tex-Chivo-ExtraBoldItalic-sup-ly1.tfm \
tex-Chivo-ExtraBoldItalic-sup-ly1.vf \
tex-Chivo-ExtraBoldItalic-sup-ot1--base.tfm \
tex-Chivo-ExtraBoldItalic-sup-ot1.tfm \
tex-Chivo-ExtraBoldItalic-sup-ot1.vf \
tex-Chivo-ExtraBoldItalic-sup-t1--base.tfm \
tex-Chivo-ExtraBoldItalic-sup-t1.tfm \
tex-Chivo-ExtraBoldItalic-sup-t1.vf \
tex-Chivo-ExtraBoldItalic-tlf-ly1--base.tfm \
tex-Chivo-ExtraBoldItalic-tlf-ly1.tfm \
tex-Chivo-ExtraBoldItalic-tlf-ly1.vf \
tex-Chivo-ExtraBoldItalic-tlf-ot1--base.tfm \
tex-Chivo-ExtraBoldItalic-tlf-ot1.tfm \
tex-Chivo-ExtraBoldItalic-tlf-ot1.vf \
tex-Chivo-ExtraBoldItalic-tlf-t1--base.tfm \
tex-Chivo-ExtraBoldItalic-tlf-t1.tfm \
tex-Chivo-ExtraBoldItalic-tlf-t1.vf \
tex-Chivo-ExtraBoldItalic-tlf-ts1--base.tfm \
tex-Chivo-ExtraBoldItalic-tlf-ts1.tfm \
tex-Chivo-ExtraBoldItalic-tlf-ts1.vf \
tex-Chivo-ExtraBoldItalic-tosf-ly1--base.tfm \
tex-Chivo-ExtraBoldItalic-tosf-ly1.tfm \
tex-Chivo-ExtraBoldItalic-tosf-ly1.vf \
tex-Chivo-ExtraBoldItalic-tosf-ot1--base.tfm \
tex-Chivo-ExtraBoldItalic-tosf-ot1.tfm \
tex-Chivo-ExtraBoldItalic-tosf-ot1.vf \
tex-Chivo-ExtraBoldItalic-tosf-t1--base.tfm \
tex-Chivo-ExtraBoldItalic-tosf-t1.tfm \
tex-Chivo-ExtraBoldItalic-tosf-t1.vf \
tex-Chivo-ExtraBoldItalic-tosf-ts1--base.tfm \
tex-Chivo-ExtraBoldItalic-tosf-ts1.tfm \
tex-Chivo-ExtraBoldItalic-tosf-ts1.vf \
tex-Chivo-ExtraLight-dnom-ly1--base.tfm \
tex-Chivo-ExtraLight-dnom-ly1.tfm \
tex-Chivo-ExtraLight-dnom-ly1.vf \
tex-Chivo-ExtraLight-dnom-ot1--base.tfm \
tex-Chivo-ExtraLight-dnom-ot1.tfm \
tex-Chivo-ExtraLight-dnom-ot1.vf \
tex-Chivo-ExtraLight-dnom-t1--base.tfm \
tex-Chivo-ExtraLight-dnom-t1.tfm \
tex-Chivo-ExtraLight-dnom-t1.vf \
tex-Chivo-ExtraLight-inf-ly1--base.tfm \
tex-Chivo-ExtraLight-inf-ly1.tfm \
tex-Chivo-ExtraLight-inf-ly1.vf \
tex-Chivo-ExtraLight-inf-ot1--base.tfm \
tex-Chivo-ExtraLight-inf-ot1.tfm \
tex-Chivo-ExtraLight-inf-ot1.vf \
tex-Chivo-ExtraLight-inf-t1--base.tfm \
tex-Chivo-ExtraLight-inf-t1.tfm \
tex-Chivo-ExtraLight-inf-t1.vf \
tex-Chivo-ExtraLight-lf-ly1--base.tfm \
tex-Chivo-ExtraLight-lf-ly1.tfm \
tex-Chivo-ExtraLight-lf-ly1.vf \
tex-Chivo-ExtraLight-lf-ot1--base.tfm \
tex-Chivo-ExtraLight-lf-ot1.tfm \
tex-Chivo-ExtraLight-lf-ot1.vf \
tex-Chivo-ExtraLight-lf-t1--base.tfm \
tex-Chivo-ExtraLight-lf-t1.tfm \
tex-Chivo-ExtraLight-lf-t1.vf \
tex-Chivo-ExtraLight-lf-ts1--base.tfm \
tex-Chivo-ExtraLight-lf-ts1.tfm \
tex-Chivo-ExtraLight-lf-ts1.vf \
tex-Chivo-ExtraLight-numr-ly1--base.tfm \
tex-Chivo-ExtraLight-numr-ly1.tfm \
tex-Chivo-ExtraLight-numr-ly1.vf \
tex-Chivo-ExtraLight-numr-ot1--base.tfm \
tex-Chivo-ExtraLight-numr-ot1.tfm \
tex-Chivo-ExtraLight-numr-ot1.vf \
tex-Chivo-ExtraLight-numr-t1--base.tfm \
tex-Chivo-ExtraLight-numr-t1.tfm \
tex-Chivo-ExtraLight-numr-t1.vf \
tex-Chivo-ExtraLight-osf-ly1--base.tfm \
tex-Chivo-ExtraLight-osf-ly1.tfm \
tex-Chivo-ExtraLight-osf-ly1.vf \
tex-Chivo-ExtraLight-osf-ot1--base.tfm \
tex-Chivo-ExtraLight-osf-ot1.tfm \
tex-Chivo-ExtraLight-osf-ot1.vf \
tex-Chivo-ExtraLight-osf-t1--base.tfm \
tex-Chivo-ExtraLight-osf-t1.tfm \
tex-Chivo-ExtraLight-osf-t1.vf \
tex-Chivo-ExtraLight-osf-ts1--base.tfm \
tex-Chivo-ExtraLight-osf-ts1.tfm \
tex-Chivo-ExtraLight-osf-ts1.vf \
tex-Chivo-ExtraLight-sup-ly1--base.tfm \
tex-Chivo-ExtraLight-sup-ly1.tfm \
tex-Chivo-ExtraLight-sup-ly1.vf \
tex-Chivo-ExtraLight-sup-ot1--base.tfm \
tex-Chivo-ExtraLight-sup-ot1.tfm \
tex-Chivo-ExtraLight-sup-ot1.vf \
tex-Chivo-ExtraLight-sup-t1--base.tfm \
tex-Chivo-ExtraLight-sup-t1.tfm \
tex-Chivo-ExtraLight-sup-t1.vf \
tex-Chivo-ExtraLight-tlf-ly1--base.tfm \
tex-Chivo-ExtraLight-tlf-ly1.tfm \
tex-Chivo-ExtraLight-tlf-ly1.vf \
tex-Chivo-ExtraLight-tlf-ot1--base.tfm \
tex-Chivo-ExtraLight-tlf-ot1.tfm \
tex-Chivo-ExtraLight-tlf-ot1.vf \
tex-Chivo-ExtraLight-tlf-t1--base.tfm \
tex-Chivo-ExtraLight-tlf-t1.tfm \
tex-Chivo-ExtraLight-tlf-t1.vf \
tex-Chivo-ExtraLight-tlf-ts1--base.tfm \
tex-Chivo-ExtraLight-tlf-ts1.tfm \
tex-Chivo-ExtraLight-tlf-ts1.vf \
tex-Chivo-ExtraLight-tosf-ly1--base.tfm \
tex-Chivo-ExtraLight-tosf-ly1.tfm \
tex-Chivo-ExtraLight-tosf-ly1.vf \
tex-Chivo-ExtraLight-tosf-ot1--base.tfm \
tex-Chivo-ExtraLight-tosf-ot1.tfm \
tex-Chivo-ExtraLight-tosf-ot1.vf \
tex-Chivo-ExtraLight-tosf-t1--base.tfm \
tex-Chivo-ExtraLight-tosf-t1.tfm \
tex-Chivo-ExtraLight-tosf-t1.vf \
tex-Chivo-ExtraLight-tosf-ts1--base.tfm \
tex-Chivo-ExtraLight-tosf-ts1.tfm \
tex-Chivo-ExtraLight-tosf-ts1.vf \
tex-Chivo-ExtraLightItalic-dnom-ly1--base.tfm \
tex-Chivo-ExtraLightItalic-dnom-ly1.tfm \
tex-Chivo-ExtraLightItalic-dnom-ly1.vf \
tex-Chivo-ExtraLightItalic-dnom-ot1--base.tfm \
tex-Chivo-ExtraLightItalic-dnom-ot1.tfm \
tex-Chivo-ExtraLightItalic-dnom-ot1.vf \
tex-Chivo-ExtraLightItalic-dnom-t1--base.tfm \
tex-Chivo-ExtraLightItalic-dnom-t1.tfm \
tex-Chivo-ExtraLightItalic-dnom-t1.vf \
tex-Chivo-ExtraLightItalic-inf-ly1--base.tfm \
tex-Chivo-ExtraLightItalic-inf-ly1.tfm \
tex-Chivo-ExtraLightItalic-inf-ly1.vf \
tex-Chivo-ExtraLightItalic-inf-ot1--base.tfm \
tex-Chivo-ExtraLightItalic-inf-ot1.tfm \
tex-Chivo-ExtraLightItalic-inf-ot1.vf \
tex-Chivo-ExtraLightItalic-inf-t1--base.tfm \
tex-Chivo-ExtraLightItalic-inf-t1.tfm \
tex-Chivo-ExtraLightItalic-inf-t1.vf \
tex-Chivo-ExtraLightItalic-lf-ly1--base.tfm \
tex-Chivo-ExtraLightItalic-lf-ly1.tfm \
tex-Chivo-ExtraLightItalic-lf-ly1.vf \
tex-Chivo-ExtraLightItalic-lf-ot1--base.tfm \
tex-Chivo-ExtraLightItalic-lf-ot1.tfm \
tex-Chivo-ExtraLightItalic-lf-ot1.vf \
tex-Chivo-ExtraLightItalic-lf-t1--base.tfm \
tex-Chivo-ExtraLightItalic-lf-t1.tfm \
tex-Chivo-ExtraLightItalic-lf-t1.vf \
tex-Chivo-ExtraLightItalic-lf-ts1--base.tfm \
tex-Chivo-ExtraLightItalic-lf-ts1.tfm \
tex-Chivo-ExtraLightItalic-lf-ts1.vf \
tex-Chivo-ExtraLightItalic-numr-ly1--base.tfm \
tex-Chivo-ExtraLightItalic-numr-ly1.tfm \
tex-Chivo-ExtraLightItalic-numr-ly1.vf \
tex-Chivo-ExtraLightItalic-numr-ot1--base.tfm \
tex-Chivo-ExtraLightItalic-numr-ot1.tfm \
tex-Chivo-ExtraLightItalic-numr-ot1.vf \
tex-Chivo-ExtraLightItalic-numr-t1--base.tfm \
tex-Chivo-ExtraLightItalic-numr-t1.tfm \
tex-Chivo-ExtraLightItalic-numr-t1.vf \
tex-Chivo-ExtraLightItalic-osf-ly1--base.tfm \
tex-Chivo-ExtraLightItalic-osf-ly1.tfm \
tex-Chivo-ExtraLightItalic-osf-ly1.vf \
tex-Chivo-ExtraLightItalic-osf-ot1--base.tfm \
tex-Chivo-ExtraLightItalic-osf-ot1.tfm \
tex-Chivo-ExtraLightItalic-osf-ot1.vf \
tex-Chivo-ExtraLightItalic-osf-t1--base.tfm \
tex-Chivo-ExtraLightItalic-osf-t1.tfm \
tex-Chivo-ExtraLightItalic-osf-t1.vf \
tex-Chivo-ExtraLightItalic-osf-ts1--base.tfm \
tex-Chivo-ExtraLightItalic-osf-ts1.tfm \
tex-Chivo-ExtraLightItalic-osf-ts1.vf \
tex-Chivo-ExtraLightItalic-sup-ly1--base.tfm \
tex-Chivo-ExtraLightItalic-sup-ly1.tfm \
tex-Chivo-ExtraLightItalic-sup-ly1.vf \
tex-Chivo-ExtraLightItalic-sup-ot1--base.tfm \
tex-Chivo-ExtraLightItalic-sup-ot1.tfm \
tex-Chivo-ExtraLightItalic-sup-ot1.vf \
tex-Chivo-ExtraLightItalic-sup-t1--base.tfm \
tex-Chivo-ExtraLightItalic-sup-t1.tfm \
tex-Chivo-ExtraLightItalic-sup-t1.vf \
tex-Chivo-ExtraLightItalic-tlf-ly1--base.tfm \
tex-Chivo-ExtraLightItalic-tlf-ly1.tfm \
tex-Chivo-ExtraLightItalic-tlf-ly1.vf \
tex-Chivo-ExtraLightItalic-tlf-ot1--base.tfm \
tex-Chivo-ExtraLightItalic-tlf-ot1.tfm \
tex-Chivo-ExtraLightItalic-tlf-ot1.vf \
tex-Chivo-ExtraLightItalic-tlf-t1--base.tfm \
tex-Chivo-ExtraLightItalic-tlf-t1.tfm \
tex-Chivo-ExtraLightItalic-tlf-t1.vf \
tex-Chivo-ExtraLightItalic-tlf-ts1--base.tfm \
tex-Chivo-ExtraLightItalic-tlf-ts1.tfm \
tex-Chivo-ExtraLightItalic-tlf-ts1.vf \
tex-Chivo-ExtraLightItalic-tosf-ly1--base.tfm \
tex-Chivo-ExtraLightItalic-tosf-ly1.tfm \
tex-Chivo-ExtraLightItalic-tosf-ly1.vf \
tex-Chivo-ExtraLightItalic-tosf-ot1--base.tfm \
tex-Chivo-ExtraLightItalic-tosf-ot1.tfm \
tex-Chivo-ExtraLightItalic-tosf-ot1.vf \
tex-Chivo-ExtraLightItalic-tosf-t1--base.tfm \
tex-Chivo-ExtraLightItalic-tosf-t1.tfm \
tex-Chivo-ExtraLightItalic-tosf-t1.vf \
tex-Chivo-ExtraLightItalic-tosf-ts1--base.tfm \
tex-Chivo-ExtraLightItalic-tosf-ts1.tfm \
tex-Chivo-ExtraLightItalic-tosf-ts1.vf \
tex-Chivo-Italic-dnom-ly1--base.tfm \
tex-Chivo-Italic-dnom-ly1.tfm \
tex-Chivo-Italic-dnom-ly1.vf \
tex-Chivo-Italic-dnom-ot1--base.tfm \
tex-Chivo-Italic-dnom-ot1.tfm \
tex-Chivo-Italic-dnom-ot1.vf \
tex-Chivo-Italic-dnom-t1--base.tfm \
tex-Chivo-Italic-dnom-t1.tfm \
tex-Chivo-Italic-dnom-t1.vf \
tex-Chivo-Italic-inf-ly1--base.tfm \
tex-Chivo-Italic-inf-ly1.tfm \
tex-Chivo-Italic-inf-ly1.vf \
tex-Chivo-Italic-inf-ot1--base.tfm \
tex-Chivo-Italic-inf-ot1.tfm \
tex-Chivo-Italic-inf-ot1.vf \
tex-Chivo-Italic-inf-t1--base.tfm \
tex-Chivo-Italic-inf-t1.tfm \
tex-Chivo-Italic-inf-t1.vf \
tex-Chivo-Italic-lf-ly1--base.tfm \
tex-Chivo-Italic-lf-ly1.tfm \
tex-Chivo-Italic-lf-ly1.vf \
tex-Chivo-Italic-lf-ot1--base.tfm \
tex-Chivo-Italic-lf-ot1.tfm \
tex-Chivo-Italic-lf-ot1.vf \
tex-Chivo-Italic-lf-t1--base.tfm \
tex-Chivo-Italic-lf-t1.tfm \
tex-Chivo-Italic-lf-t1.vf \
tex-Chivo-Italic-lf-ts1--base.tfm \
tex-Chivo-Italic-lf-ts1.tfm \
tex-Chivo-Italic-lf-ts1.vf \
tex-Chivo-Italic-numr-ly1--base.tfm \
tex-Chivo-Italic-numr-ly1.tfm \
tex-Chivo-Italic-numr-ly1.vf \
tex-Chivo-Italic-numr-ot1--base.tfm \
tex-Chivo-Italic-numr-ot1.tfm \
tex-Chivo-Italic-numr-ot1.vf \
tex-Chivo-Italic-numr-t1--base.tfm \
tex-Chivo-Italic-numr-t1.tfm \
tex-Chivo-Italic-numr-t1.vf \
tex-Chivo-Italic-osf-ly1--base.tfm \
tex-Chivo-Italic-osf-ly1.tfm \
tex-Chivo-Italic-osf-ly1.vf \
tex-Chivo-Italic-osf-ot1--base.tfm \
tex-Chivo-Italic-osf-ot1.tfm \
tex-Chivo-Italic-osf-ot1.vf \
tex-Chivo-Italic-osf-t1--base.tfm \
tex-Chivo-Italic-osf-t1.tfm \
tex-Chivo-Italic-osf-t1.vf \
tex-Chivo-Italic-osf-ts1--base.tfm \
tex-Chivo-Italic-osf-ts1.tfm \
tex-Chivo-Italic-osf-ts1.vf \
tex-Chivo-Italic-sup-ly1--base.tfm \
tex-Chivo-Italic-sup-ly1.tfm \
tex-Chivo-Italic-sup-ly1.vf \
tex-Chivo-Italic-sup-ot1--base.tfm \
tex-Chivo-Italic-sup-ot1.tfm \
tex-Chivo-Italic-sup-ot1.vf \
tex-Chivo-Italic-sup-t1--base.tfm \
tex-Chivo-Italic-sup-t1.tfm \
tex-Chivo-Italic-sup-t1.vf \
tex-Chivo-Italic-tlf-ly1--base.tfm \
tex-Chivo-Italic-tlf-ly1.tfm \
tex-Chivo-Italic-tlf-ly1.vf \
tex-Chivo-Italic-tlf-ot1--base.tfm \
tex-Chivo-Italic-tlf-ot1.tfm \
tex-Chivo-Italic-tlf-ot1.vf \
tex-Chivo-Italic-tlf-t1--base.tfm \
tex-Chivo-Italic-tlf-t1.tfm \
tex-Chivo-Italic-tlf-t1.vf \
tex-Chivo-Italic-tlf-ts1--base.tfm \
tex-Chivo-Italic-tlf-ts1.tfm \
tex-Chivo-Italic-tlf-ts1.vf \
tex-Chivo-Italic-tosf-ly1--base.tfm \
tex-Chivo-Italic-tosf-ly1.tfm \
tex-Chivo-Italic-tosf-ly1.vf \
tex-Chivo-Italic-tosf-ot1--base.tfm \
tex-Chivo-Italic-tosf-ot1.tfm \
tex-Chivo-Italic-tosf-ot1.vf \
tex-Chivo-Italic-tosf-t1--base.tfm \
tex-Chivo-Italic-tosf-t1.tfm \
tex-Chivo-Italic-tosf-t1.vf \
tex-Chivo-Italic-tosf-ts1--base.tfm \
tex-Chivo-Italic-tosf-ts1.tfm \
tex-Chivo-Italic-tosf-ts1.vf \
tex-Chivo-Light-dnom-ly1--base.tfm \
tex-Chivo-Light-dnom-ly1.tfm \
tex-Chivo-Light-dnom-ly1.vf \
tex-Chivo-Light-dnom-ot1--base.tfm \
tex-Chivo-Light-dnom-ot1.tfm \
tex-Chivo-Light-dnom-ot1.vf \
tex-Chivo-Light-dnom-t1--base.tfm \
tex-Chivo-Light-dnom-t1.tfm \
tex-Chivo-Light-dnom-t1.vf \
tex-Chivo-Light-inf-ly1--base.tfm \
tex-Chivo-Light-inf-ly1.tfm \
tex-Chivo-Light-inf-ly1.vf \
tex-Chivo-Light-inf-ot1--base.tfm \
tex-Chivo-Light-inf-ot1.tfm \
tex-Chivo-Light-inf-ot1.vf \
tex-Chivo-Light-inf-t1--base.tfm \
tex-Chivo-Light-inf-t1.tfm \
tex-Chivo-Light-inf-t1.vf \
tex-Chivo-Light-lf-ly1--base.tfm \
tex-Chivo-Light-lf-ly1.tfm \
tex-Chivo-Light-lf-ly1.vf \
tex-Chivo-Light-lf-ot1--base.tfm \
tex-Chivo-Light-lf-ot1.tfm \
tex-Chivo-Light-lf-ot1.vf \
tex-Chivo-Light-lf-t1--base.tfm \
tex-Chivo-Light-lf-t1.tfm \
tex-Chivo-Light-lf-t1.vf \
tex-Chivo-Light-lf-ts1--base.tfm \
tex-Chivo-Light-lf-ts1.tfm \
tex-Chivo-Light-lf-ts1.vf \
tex-Chivo-Light-numr-ly1--base.tfm \
tex-Chivo-Light-numr-ly1.tfm \
tex-Chivo-Light-numr-ly1.vf \
tex-Chivo-Light-numr-ot1--base.tfm \
tex-Chivo-Light-numr-ot1.tfm \
tex-Chivo-Light-numr-ot1.vf \
tex-Chivo-Light-numr-t1--base.tfm \
tex-Chivo-Light-numr-t1.tfm \
tex-Chivo-Light-numr-t1.vf \
tex-Chivo-Light-osf-ly1--base.tfm \
tex-Chivo-Light-osf-ly1.tfm \
tex-Chivo-Light-osf-ly1.vf \
tex-Chivo-Light-osf-ot1--base.tfm \
tex-Chivo-Light-osf-ot1.tfm \
tex-Chivo-Light-osf-ot1.vf \
tex-Chivo-Light-osf-t1--base.tfm \
tex-Chivo-Light-osf-t1.tfm \
tex-Chivo-Light-osf-t1.vf \
tex-Chivo-Light-osf-ts1--base.tfm \
tex-Chivo-Light-osf-ts1.tfm \
tex-Chivo-Light-osf-ts1.vf \
tex-Chivo-Light-sup-ly1--base.tfm \
tex-Chivo-Light-sup-ly1.tfm \
tex-Chivo-Light-sup-ly1.vf \
tex-Chivo-Light-sup-ot1--base.tfm \
tex-Chivo-Light-sup-ot1.tfm \
tex-Chivo-Light-sup-ot1.vf \
tex-Chivo-Light-sup-t1--base.tfm \
tex-Chivo-Light-sup-t1.tfm \
tex-Chivo-Light-sup-t1.vf \
tex-Chivo-Light-tlf-ly1--base.tfm \
tex-Chivo-Light-tlf-ly1.tfm \
tex-Chivo-Light-tlf-ly1.vf \
tex-Chivo-Light-tlf-ot1--base.tfm \
tex-Chivo-Light-tlf-ot1.tfm \
tex-Chivo-Light-tlf-ot1.vf \
tex-Chivo-Light-tlf-t1--base.tfm \
tex-Chivo-Light-tlf-t1.tfm \
tex-Chivo-Light-tlf-t1.vf \
tex-Chivo-Light-tlf-ts1--base.tfm \
tex-Chivo-Light-tlf-ts1.tfm \
tex-Chivo-Light-tlf-ts1.vf \
tex-Chivo-Light-tosf-ly1--base.tfm \
tex-Chivo-Light-tosf-ly1.tfm \
tex-Chivo-Light-tosf-ly1.vf \
tex-Chivo-Light-tosf-ot1--base.tfm \
tex-Chivo-Light-tosf-ot1.tfm \
tex-Chivo-Light-tosf-ot1.vf \
tex-Chivo-Light-tosf-t1--base.tfm \
tex-Chivo-Light-tosf-t1.tfm \
tex-Chivo-Light-tosf-t1.vf \
tex-Chivo-Light-tosf-ts1--base.tfm \
tex-Chivo-Light-tosf-ts1.tfm \
tex-Chivo-Light-tosf-ts1.vf \
tex-Chivo-LightItalic-dnom-ly1--base.tfm \
tex-Chivo-LightItalic-dnom-ly1.tfm \
tex-Chivo-LightItalic-dnom-ly1.vf \
tex-Chivo-LightItalic-dnom-ot1--base.tfm \
tex-Chivo-LightItalic-dnom-ot1.tfm \
tex-Chivo-LightItalic-dnom-ot1.vf \
tex-Chivo-LightItalic-dnom-t1--base.tfm \
tex-Chivo-LightItalic-dnom-t1.tfm \
tex-Chivo-LightItalic-dnom-t1.vf \
tex-Chivo-LightItalic-inf-ly1--base.tfm \
tex-Chivo-LightItalic-inf-ly1.tfm \
tex-Chivo-LightItalic-inf-ly1.vf \
tex-Chivo-LightItalic-inf-ot1--base.tfm \
tex-Chivo-LightItalic-inf-ot1.tfm \
tex-Chivo-LightItalic-inf-ot1.vf \
tex-Chivo-LightItalic-inf-t1--base.tfm \
tex-Chivo-LightItalic-inf-t1.tfm \
tex-Chivo-LightItalic-inf-t1.vf \
tex-Chivo-LightItalic-lf-ly1--base.tfm \
tex-Chivo-LightItalic-lf-ly1.tfm \
tex-Chivo-LightItalic-lf-ly1.vf \
tex-Chivo-LightItalic-lf-ot1--base.tfm \
tex-Chivo-LightItalic-lf-ot1.tfm \
tex-Chivo-LightItalic-lf-ot1.vf \
tex-Chivo-LightItalic-lf-t1--base.tfm \
tex-Chivo-LightItalic-lf-t1.tfm \
tex-Chivo-LightItalic-lf-t1.vf \
tex-Chivo-LightItalic-lf-ts1--base.tfm \
tex-Chivo-LightItalic-lf-ts1.tfm \
tex-Chivo-LightItalic-lf-ts1.vf \
tex-Chivo-LightItalic-numr-ly1--base.tfm \
tex-Chivo-LightItalic-numr-ly1.tfm \
tex-Chivo-LightItalic-numr-ly1.vf \
tex-Chivo-LightItalic-numr-ot1--base.tfm \
tex-Chivo-LightItalic-numr-ot1.tfm \
tex-Chivo-LightItalic-numr-ot1.vf \
tex-Chivo-LightItalic-numr-t1--base.tfm \
tex-Chivo-LightItalic-numr-t1.tfm \
tex-Chivo-LightItalic-numr-t1.vf \
tex-Chivo-LightItalic-osf-ly1--base.tfm \
tex-Chivo-LightItalic-osf-ly1.tfm \
tex-Chivo-LightItalic-osf-ly1.vf \
tex-Chivo-LightItalic-osf-ot1--base.tfm \
tex-Chivo-LightItalic-osf-ot1.tfm \
tex-Chivo-LightItalic-osf-ot1.vf \
tex-Chivo-LightItalic-osf-t1--base.tfm \
tex-Chivo-LightItalic-osf-t1.tfm \
tex-Chivo-LightItalic-osf-t1.vf \
tex-Chivo-LightItalic-osf-ts1--base.tfm \
tex-Chivo-LightItalic-osf-ts1.tfm \
tex-Chivo-LightItalic-osf-ts1.vf \
tex-Chivo-LightItalic-sup-ly1--base.tfm \
tex-Chivo-LightItalic-sup-ly1.tfm \
tex-Chivo-LightItalic-sup-ly1.vf \
tex-Chivo-LightItalic-sup-ot1--base.tfm \
tex-Chivo-LightItalic-sup-ot1.tfm \
tex-Chivo-LightItalic-sup-ot1.vf \
tex-Chivo-LightItalic-sup-t1--base.tfm \
tex-Chivo-LightItalic-sup-t1.tfm \
tex-Chivo-LightItalic-sup-t1.vf \
tex-Chivo-LightItalic-tlf-ly1--base.tfm \
tex-Chivo-LightItalic-tlf-ly1.tfm \
tex-Chivo-LightItalic-tlf-ly1.vf \
tex-Chivo-LightItalic-tlf-ot1--base.tfm \
tex-Chivo-LightItalic-tlf-ot1.tfm \
tex-Chivo-LightItalic-tlf-ot1.vf \
tex-Chivo-LightItalic-tlf-t1--base.tfm \
tex-Chivo-LightItalic-tlf-t1.tfm \
tex-Chivo-LightItalic-tlf-t1.vf \
tex-Chivo-LightItalic-tlf-ts1--base.tfm \
tex-Chivo-LightItalic-tlf-ts1.tfm \
tex-Chivo-LightItalic-tlf-ts1.vf \
tex-Chivo-LightItalic-tosf-ly1--base.tfm \
tex-Chivo-LightItalic-tosf-ly1.tfm \
tex-Chivo-LightItalic-tosf-ly1.vf \
tex-Chivo-LightItalic-tosf-ot1--base.tfm \
tex-Chivo-LightItalic-tosf-ot1.tfm \
tex-Chivo-LightItalic-tosf-ot1.vf \
tex-Chivo-LightItalic-tosf-t1--base.tfm \
tex-Chivo-LightItalic-tosf-t1.tfm \
tex-Chivo-LightItalic-tosf-t1.vf \
tex-Chivo-LightItalic-tosf-ts1--base.tfm \
tex-Chivo-LightItalic-tosf-ts1.tfm \
tex-Chivo-LightItalic-tosf-ts1.vf \
tex-Chivo-Medium-dnom-ly1--base.tfm \
tex-Chivo-Medium-dnom-ly1.tfm \
tex-Chivo-Medium-dnom-ly1.vf \
tex-Chivo-Medium-dnom-ot1--base.tfm \
tex-Chivo-Medium-dnom-ot1.tfm \
tex-Chivo-Medium-dnom-ot1.vf \
tex-Chivo-Medium-dnom-t1--base.tfm \
tex-Chivo-Medium-dnom-t1.tfm \
tex-Chivo-Medium-dnom-t1.vf \
tex-Chivo-Medium-inf-ly1--base.tfm \
tex-Chivo-Medium-inf-ly1.tfm \
tex-Chivo-Medium-inf-ly1.vf \
tex-Chivo-Medium-inf-ot1--base.tfm \
tex-Chivo-Medium-inf-ot1.tfm \
tex-Chivo-Medium-inf-ot1.vf \
tex-Chivo-Medium-inf-t1--base.tfm \
tex-Chivo-Medium-inf-t1.tfm \
tex-Chivo-Medium-inf-t1.vf \
tex-Chivo-Medium-lf-ly1--base.tfm \
tex-Chivo-Medium-lf-ly1.tfm \
tex-Chivo-Medium-lf-ly1.vf \
tex-Chivo-Medium-lf-ot1--base.tfm \
tex-Chivo-Medium-lf-ot1.tfm \
tex-Chivo-Medium-lf-ot1.vf \
tex-Chivo-Medium-lf-t1--base.tfm \
tex-Chivo-Medium-lf-t1.tfm \
tex-Chivo-Medium-lf-t1.vf \
tex-Chivo-Medium-lf-ts1--base.tfm \
tex-Chivo-Medium-lf-ts1.tfm \
tex-Chivo-Medium-lf-ts1.vf \
tex-Chivo-Medium-numr-ly1--base.tfm \
tex-Chivo-Medium-numr-ly1.tfm \
tex-Chivo-Medium-numr-ly1.vf \
tex-Chivo-Medium-numr-ot1--base.tfm \
tex-Chivo-Medium-numr-ot1.tfm \
tex-Chivo-Medium-numr-ot1.vf \
tex-Chivo-Medium-numr-t1--base.tfm \
tex-Chivo-Medium-numr-t1.tfm \
tex-Chivo-Medium-numr-t1.vf \
tex-Chivo-Medium-osf-ly1--base.tfm \
tex-Chivo-Medium-osf-ly1.tfm \
tex-Chivo-Medium-osf-ly1.vf \
tex-Chivo-Medium-osf-ot1--base.tfm \
tex-Chivo-Medium-osf-ot1.tfm \
tex-Chivo-Medium-osf-ot1.vf \
tex-Chivo-Medium-osf-t1--base.tfm \
tex-Chivo-Medium-osf-t1.tfm \
tex-Chivo-Medium-osf-t1.vf \
tex-Chivo-Medium-osf-ts1--base.tfm \
tex-Chivo-Medium-osf-ts1.tfm \
tex-Chivo-Medium-osf-ts1.vf \
tex-Chivo-Medium-sup-ly1--base.tfm \
tex-Chivo-Medium-sup-ly1.tfm \
tex-Chivo-Medium-sup-ly1.vf \
tex-Chivo-Medium-sup-ot1--base.tfm \
tex-Chivo-Medium-sup-ot1.tfm \
tex-Chivo-Medium-sup-ot1.vf \
tex-Chivo-Medium-sup-t1--base.tfm \
tex-Chivo-Medium-sup-t1.tfm \
tex-Chivo-Medium-sup-t1.vf \
tex-Chivo-Medium-tlf-ly1--base.tfm \
tex-Chivo-Medium-tlf-ly1.tfm \
tex-Chivo-Medium-tlf-ly1.vf \
tex-Chivo-Medium-tlf-ot1--base.tfm \
tex-Chivo-Medium-tlf-ot1.tfm \
tex-Chivo-Medium-tlf-ot1.vf \
tex-Chivo-Medium-tlf-t1--base.tfm \
tex-Chivo-Medium-tlf-t1.tfm \
tex-Chivo-Medium-tlf-t1.vf \
tex-Chivo-Medium-tlf-ts1--base.tfm \
tex-Chivo-Medium-tlf-ts1.tfm \
tex-Chivo-Medium-tlf-ts1.vf \
tex-Chivo-Medium-tosf-ly1--base.tfm \
tex-Chivo-Medium-tosf-ly1.tfm \
tex-Chivo-Medium-tosf-ly1.vf \
tex-Chivo-Medium-tosf-ot1--base.tfm \
tex-Chivo-Medium-tosf-ot1.tfm \
tex-Chivo-Medium-tosf-ot1.vf \
tex-Chivo-Medium-tosf-t1--base.tfm \
tex-Chivo-Medium-tosf-t1.tfm \
tex-Chivo-Medium-tosf-t1.vf \
tex-Chivo-Medium-tosf-ts1--base.tfm \
tex-Chivo-Medium-tosf-ts1.tfm \
tex-Chivo-Medium-tosf-ts1.vf \
tex-Chivo-MediumItalic-dnom-ly1--base.tfm \
tex-Chivo-MediumItalic-dnom-ly1.tfm \
tex-Chivo-MediumItalic-dnom-ly1.vf \
tex-Chivo-MediumItalic-dnom-ot1--base.tfm \
tex-Chivo-MediumItalic-dnom-ot1.tfm \
tex-Chivo-MediumItalic-dnom-ot1.vf \
tex-Chivo-MediumItalic-dnom-t1--base.tfm \
tex-Chivo-MediumItalic-dnom-t1.tfm \
tex-Chivo-MediumItalic-dnom-t1.vf \
tex-Chivo-MediumItalic-inf-ly1--base.tfm \
tex-Chivo-MediumItalic-inf-ly1.tfm \
tex-Chivo-MediumItalic-inf-ly1.vf \
tex-Chivo-MediumItalic-inf-ot1--base.tfm \
tex-Chivo-MediumItalic-inf-ot1.tfm \
tex-Chivo-MediumItalic-inf-ot1.vf \
tex-Chivo-MediumItalic-inf-t1--base.tfm \
tex-Chivo-MediumItalic-inf-t1.tfm \
tex-Chivo-MediumItalic-inf-t1.vf \
tex-Chivo-MediumItalic-lf-ly1--base.tfm \
tex-Chivo-MediumItalic-lf-ly1.tfm \
tex-Chivo-MediumItalic-lf-ly1.vf \
tex-Chivo-MediumItalic-lf-ot1--base.tfm \
tex-Chivo-MediumItalic-lf-ot1.tfm \
tex-Chivo-MediumItalic-lf-ot1.vf \
tex-Chivo-MediumItalic-lf-t1--base.tfm \
tex-Chivo-MediumItalic-lf-t1.tfm \
tex-Chivo-MediumItalic-lf-t1.vf \
tex-Chivo-MediumItalic-lf-ts1--base.tfm \
tex-Chivo-MediumItalic-lf-ts1.tfm \
tex-Chivo-MediumItalic-lf-ts1.vf \
tex-Chivo-MediumItalic-numr-ly1--base.tfm \
tex-Chivo-MediumItalic-numr-ly1.tfm \
tex-Chivo-MediumItalic-numr-ly1.vf \
tex-Chivo-MediumItalic-numr-ot1--base.tfm \
tex-Chivo-MediumItalic-numr-ot1.tfm \
tex-Chivo-MediumItalic-numr-ot1.vf \
tex-Chivo-MediumItalic-numr-t1--base.tfm \
tex-Chivo-MediumItalic-numr-t1.tfm \
tex-Chivo-MediumItalic-numr-t1.vf \
tex-Chivo-MediumItalic-osf-ly1--base.tfm \
tex-Chivo-MediumItalic-osf-ly1.tfm \
tex-Chivo-MediumItalic-osf-ly1.vf \
tex-Chivo-MediumItalic-osf-ot1--base.tfm \
tex-Chivo-MediumItalic-osf-ot1.tfm \
tex-Chivo-MediumItalic-osf-ot1.vf \
tex-Chivo-MediumItalic-osf-t1--base.tfm \
tex-Chivo-MediumItalic-osf-t1.tfm \
tex-Chivo-MediumItalic-osf-t1.vf \
tex-Chivo-MediumItalic-osf-ts1--base.tfm \
tex-Chivo-MediumItalic-osf-ts1.tfm \
tex-Chivo-MediumItalic-osf-ts1.vf \
tex-Chivo-MediumItalic-sup-ly1--base.tfm \
tex-Chivo-MediumItalic-sup-ly1.tfm \
tex-Chivo-MediumItalic-sup-ly1.vf \
tex-Chivo-MediumItalic-sup-ot1--base.tfm \
tex-Chivo-MediumItalic-sup-ot1.tfm \
tex-Chivo-MediumItalic-sup-ot1.vf \
tex-Chivo-MediumItalic-sup-t1--base.tfm \
tex-Chivo-MediumItalic-sup-t1.tfm \
tex-Chivo-MediumItalic-sup-t1.vf \
tex-Chivo-MediumItalic-tlf-ly1--base.tfm \
tex-Chivo-MediumItalic-tlf-ly1.tfm \
tex-Chivo-MediumItalic-tlf-ly1.vf \
tex-Chivo-MediumItalic-tlf-ot1--base.tfm \
tex-Chivo-MediumItalic-tlf-ot1.tfm \
tex-Chivo-MediumItalic-tlf-ot1.vf \
tex-Chivo-MediumItalic-tlf-t1--base.tfm \
tex-Chivo-MediumItalic-tlf-t1.tfm \
tex-Chivo-MediumItalic-tlf-t1.vf \
tex-Chivo-MediumItalic-tlf-ts1--base.tfm \
tex-Chivo-MediumItalic-tlf-ts1.tfm \
tex-Chivo-MediumItalic-tlf-ts1.vf \
tex-Chivo-MediumItalic-tosf-ly1--base.tfm \
tex-Chivo-MediumItalic-tosf-ly1.tfm \
tex-Chivo-MediumItalic-tosf-ly1.vf \
tex-Chivo-MediumItalic-tosf-ot1--base.tfm \
tex-Chivo-MediumItalic-tosf-ot1.tfm \
tex-Chivo-MediumItalic-tosf-ot1.vf \
tex-Chivo-MediumItalic-tosf-t1--base.tfm \
tex-Chivo-MediumItalic-tosf-t1.tfm \
tex-Chivo-MediumItalic-tosf-t1.vf \
tex-Chivo-MediumItalic-tosf-ts1--base.tfm \
tex-Chivo-MediumItalic-tosf-ts1.tfm \
tex-Chivo-MediumItalic-tosf-ts1.vf \
tex-Chivo-Regular-dnom-ly1--base.tfm \
tex-Chivo-Regular-dnom-ly1.tfm \
tex-Chivo-Regular-dnom-ly1.vf \
tex-Chivo-Regular-dnom-ot1--base.tfm \
tex-Chivo-Regular-dnom-ot1.tfm \
tex-Chivo-Regular-dnom-ot1.vf \
tex-Chivo-Regular-dnom-t1--base.tfm \
tex-Chivo-Regular-dnom-t1.tfm \
tex-Chivo-Regular-dnom-t1.vf \
tex-Chivo-Regular-inf-ly1--base.tfm \
tex-Chivo-Regular-inf-ly1.tfm \
tex-Chivo-Regular-inf-ly1.vf \
tex-Chivo-Regular-inf-ot1--base.tfm \
tex-Chivo-Regular-inf-ot1.tfm \
tex-Chivo-Regular-inf-ot1.vf \
tex-Chivo-Regular-inf-t1--base.tfm \
tex-Chivo-Regular-inf-t1.tfm \
tex-Chivo-Regular-inf-t1.vf \
tex-Chivo-Regular-lf-ly1--base.tfm \
tex-Chivo-Regular-lf-ly1.tfm \
tex-Chivo-Regular-lf-ly1.vf \
tex-Chivo-Regular-lf-ot1--base.tfm \
tex-Chivo-Regular-lf-ot1.tfm \
tex-Chivo-Regular-lf-ot1.vf \
tex-Chivo-Regular-lf-t1--base.tfm \
tex-Chivo-Regular-lf-t1.tfm \
tex-Chivo-Regular-lf-t1.vf \
tex-Chivo-Regular-lf-ts1--base.tfm \
tex-Chivo-Regular-lf-ts1.tfm \
tex-Chivo-Regular-lf-ts1.vf \
tex-Chivo-Regular-numr-ly1--base.tfm \
tex-Chivo-Regular-numr-ly1.tfm \
tex-Chivo-Regular-numr-ly1.vf \
tex-Chivo-Regular-numr-ot1--base.tfm \
tex-Chivo-Regular-numr-ot1.tfm \
tex-Chivo-Regular-numr-ot1.vf \
tex-Chivo-Regular-numr-t1--base.tfm \
tex-Chivo-Regular-numr-t1.tfm \
tex-Chivo-Regular-numr-t1.vf \
tex-Chivo-Regular-osf-ly1--base.tfm \
tex-Chivo-Regular-osf-ly1.tfm \
tex-Chivo-Regular-osf-ly1.vf \
tex-Chivo-Regular-osf-ot1--base.tfm \
tex-Chivo-Regular-osf-ot1.tfm \
tex-Chivo-Regular-osf-ot1.vf \
tex-Chivo-Regular-osf-t1--base.tfm \
tex-Chivo-Regular-osf-t1.tfm \
tex-Chivo-Regular-osf-t1.vf \
tex-Chivo-Regular-osf-ts1--base.tfm \
tex-Chivo-Regular-osf-ts1.tfm \
tex-Chivo-Regular-osf-ts1.vf \
tex-Chivo-Regular-sup-ly1--base.tfm \
tex-Chivo-Regular-sup-ly1.tfm \
tex-Chivo-Regular-sup-ly1.vf \
tex-Chivo-Regular-sup-ot1--base.tfm \
tex-Chivo-Regular-sup-ot1.tfm \
tex-Chivo-Regular-sup-ot1.vf \
tex-Chivo-Regular-sup-t1--base.tfm \
tex-Chivo-Regular-sup-t1.tfm \
tex-Chivo-Regular-sup-t1.vf \
tex-Chivo-Regular-tlf-ly1--base.tfm \
tex-Chivo-Regular-tlf-ly1.tfm \
tex-Chivo-Regular-tlf-ly1.vf \
tex-Chivo-Regular-tlf-ot1--base.tfm \
tex-Chivo-Regular-tlf-ot1.tfm \
tex-Chivo-Regular-tlf-ot1.vf \
tex-Chivo-Regular-tlf-t1--base.tfm \
tex-Chivo-Regular-tlf-t1.tfm \
tex-Chivo-Regular-tlf-t1.vf \
tex-Chivo-Regular-tlf-ts1--base.tfm \
tex-Chivo-Regular-tlf-ts1.tfm \
tex-Chivo-Regular-tlf-ts1.vf \
tex-Chivo-Regular-tosf-ly1--base.tfm \
tex-Chivo-Regular-tosf-ly1.tfm \
tex-Chivo-Regular-tosf-ly1.vf \
tex-Chivo-Regular-tosf-ot1--base.tfm \
tex-Chivo-Regular-tosf-ot1.tfm \
tex-Chivo-Regular-tosf-ot1.vf \
tex-Chivo-Regular-tosf-t1--base.tfm \
tex-Chivo-Regular-tosf-t1.tfm \
tex-Chivo-Regular-tosf-t1.vf \
tex-Chivo-Regular-tosf-ts1--base.tfm \
tex-Chivo-Regular-tosf-ts1.tfm \
tex-Chivo-Regular-tosf-ts1.vf \
tex-Chivo-SemiBold-dnom-ly1--base.tfm \
tex-Chivo-SemiBold-dnom-ly1.tfm \
tex-Chivo-SemiBold-dnom-ly1.vf \
tex-Chivo-SemiBold-dnom-ot1--base.tfm \
tex-Chivo-SemiBold-dnom-ot1.tfm \
tex-Chivo-SemiBold-dnom-ot1.vf \
tex-Chivo-SemiBold-dnom-t1--base.tfm \
tex-Chivo-SemiBold-dnom-t1.tfm \
tex-Chivo-SemiBold-dnom-t1.vf \
tex-Chivo-SemiBold-inf-ly1--base.tfm \
tex-Chivo-SemiBold-inf-ly1.tfm \
tex-Chivo-SemiBold-inf-ly1.vf \
tex-Chivo-SemiBold-inf-ot1--base.tfm \
tex-Chivo-SemiBold-inf-ot1.tfm \
tex-Chivo-SemiBold-inf-ot1.vf \
tex-Chivo-SemiBold-inf-t1--base.tfm \
tex-Chivo-SemiBold-inf-t1.tfm \
tex-Chivo-SemiBold-inf-t1.vf \
tex-Chivo-SemiBold-lf-ly1--base.tfm \
tex-Chivo-SemiBold-lf-ly1.tfm \
tex-Chivo-SemiBold-lf-ly1.vf \
tex-Chivo-SemiBold-lf-ot1--base.tfm \
tex-Chivo-SemiBold-lf-ot1.tfm \
tex-Chivo-SemiBold-lf-ot1.vf \
tex-Chivo-SemiBold-lf-t1--base.tfm \
tex-Chivo-SemiBold-lf-t1.tfm \
tex-Chivo-SemiBold-lf-t1.vf \
tex-Chivo-SemiBold-lf-ts1--base.tfm \
tex-Chivo-SemiBold-lf-ts1.tfm \
tex-Chivo-SemiBold-lf-ts1.vf \
tex-Chivo-SemiBold-numr-ly1--base.tfm \
tex-Chivo-SemiBold-numr-ly1.tfm \
tex-Chivo-SemiBold-numr-ly1.vf \
tex-Chivo-SemiBold-numr-ot1--base.tfm \
tex-Chivo-SemiBold-numr-ot1.tfm \
tex-Chivo-SemiBold-numr-ot1.vf \
tex-Chivo-SemiBold-numr-t1--base.tfm \
tex-Chivo-SemiBold-numr-t1.tfm \
tex-Chivo-SemiBold-numr-t1.vf \
tex-Chivo-SemiBold-osf-ly1--base.tfm \
tex-Chivo-SemiBold-osf-ly1.tfm \
tex-Chivo-SemiBold-osf-ly1.vf \
tex-Chivo-SemiBold-osf-ot1--base.tfm \
tex-Chivo-SemiBold-osf-ot1.tfm \
tex-Chivo-SemiBold-osf-ot1.vf \
tex-Chivo-SemiBold-osf-t1--base.tfm \
tex-Chivo-SemiBold-osf-t1.tfm \
tex-Chivo-SemiBold-osf-t1.vf \
tex-Chivo-SemiBold-osf-ts1--base.tfm \
tex-Chivo-SemiBold-osf-ts1.tfm \
tex-Chivo-SemiBold-osf-ts1.vf \
tex-Chivo-SemiBold-sup-ly1--base.tfm \
tex-Chivo-SemiBold-sup-ly1.tfm \
tex-Chivo-SemiBold-sup-ly1.vf \
tex-Chivo-SemiBold-sup-ot1--base.tfm \
tex-Chivo-SemiBold-sup-ot1.tfm \
tex-Chivo-SemiBold-sup-ot1.vf \
tex-Chivo-SemiBold-sup-t1--base.tfm \
tex-Chivo-SemiBold-sup-t1.tfm \
tex-Chivo-SemiBold-sup-t1.vf \
tex-Chivo-SemiBold-tlf-ly1--base.tfm \
tex-Chivo-SemiBold-tlf-ly1.tfm \
tex-Chivo-SemiBold-tlf-ly1.vf \
tex-Chivo-SemiBold-tlf-ot1--base.tfm \
tex-Chivo-SemiBold-tlf-ot1.tfm \
tex-Chivo-SemiBold-tlf-ot1.vf \
tex-Chivo-SemiBold-tlf-t1--base.tfm \
tex-Chivo-SemiBold-tlf-t1.tfm \
tex-Chivo-SemiBold-tlf-t1.vf \
tex-Chivo-SemiBold-tlf-ts1--base.tfm \
tex-Chivo-SemiBold-tlf-ts1.tfm \
tex-Chivo-SemiBold-tlf-ts1.vf \
tex-Chivo-SemiBold-tosf-ly1--base.tfm \
tex-Chivo-SemiBold-tosf-ly1.tfm \
tex-Chivo-SemiBold-tosf-ly1.vf \
tex-Chivo-SemiBold-tosf-ot1--base.tfm \
tex-Chivo-SemiBold-tosf-ot1.tfm \
tex-Chivo-SemiBold-tosf-ot1.vf \
tex-Chivo-SemiBold-tosf-t1--base.tfm \
tex-Chivo-SemiBold-tosf-t1.tfm \
tex-Chivo-SemiBold-tosf-t1.vf \
tex-Chivo-SemiBold-tosf-ts1--base.tfm \
tex-Chivo-SemiBold-tosf-ts1.tfm \
tex-Chivo-SemiBold-tosf-ts1.vf \
tex-Chivo-SemiBoldItalic-dnom-ly1--base.tfm \
tex-Chivo-SemiBoldItalic-dnom-ly1.tfm \
tex-Chivo-SemiBoldItalic-dnom-ly1.vf \
tex-Chivo-SemiBoldItalic-dnom-ot1--base.tfm \
tex-Chivo-SemiBoldItalic-dnom-ot1.tfm \
tex-Chivo-SemiBoldItalic-dnom-ot1.vf \
tex-Chivo-SemiBoldItalic-dnom-t1--base.tfm \
tex-Chivo-SemiBoldItalic-dnom-t1.tfm \
tex-Chivo-SemiBoldItalic-dnom-t1.vf \
tex-Chivo-SemiBoldItalic-inf-ly1--base.tfm \
tex-Chivo-SemiBoldItalic-inf-ly1.tfm \
tex-Chivo-SemiBoldItalic-inf-ly1.vf \
tex-Chivo-SemiBoldItalic-inf-ot1--base.tfm \
tex-Chivo-SemiBoldItalic-inf-ot1.tfm \
tex-Chivo-SemiBoldItalic-inf-ot1.vf \
tex-Chivo-SemiBoldItalic-inf-t1--base.tfm \
tex-Chivo-SemiBoldItalic-inf-t1.tfm \
tex-Chivo-SemiBoldItalic-inf-t1.vf \
tex-Chivo-SemiBoldItalic-lf-ly1--base.tfm \
tex-Chivo-SemiBoldItalic-lf-ly1.tfm \
tex-Chivo-SemiBoldItalic-lf-ly1.vf \
tex-Chivo-SemiBoldItalic-lf-ot1--base.tfm \
tex-Chivo-SemiBoldItalic-lf-ot1.tfm \
tex-Chivo-SemiBoldItalic-lf-ot1.vf \
tex-Chivo-SemiBoldItalic-lf-t1--base.tfm \
tex-Chivo-SemiBoldItalic-lf-t1.tfm \
tex-Chivo-SemiBoldItalic-lf-t1.vf \
tex-Chivo-SemiBoldItalic-lf-ts1--base.tfm \
tex-Chivo-SemiBoldItalic-lf-ts1.tfm \
tex-Chivo-SemiBoldItalic-lf-ts1.vf \
tex-Chivo-SemiBoldItalic-numr-ly1--base.tfm \
tex-Chivo-SemiBoldItalic-numr-ly1.tfm \
tex-Chivo-SemiBoldItalic-numr-ly1.vf \
tex-Chivo-SemiBoldItalic-numr-ot1--base.tfm \
tex-Chivo-SemiBoldItalic-numr-ot1.tfm \
tex-Chivo-SemiBoldItalic-numr-ot1.vf \
tex-Chivo-SemiBoldItalic-numr-t1--base.tfm \
tex-Chivo-SemiBoldItalic-numr-t1.tfm \
tex-Chivo-SemiBoldItalic-numr-t1.vf \
tex-Chivo-SemiBoldItalic-osf-ly1--base.tfm \
tex-Chivo-SemiBoldItalic-osf-ly1.tfm \
tex-Chivo-SemiBoldItalic-osf-ly1.vf \
tex-Chivo-SemiBoldItalic-osf-ot1--base.tfm \
tex-Chivo-SemiBoldItalic-osf-ot1.tfm \
tex-Chivo-SemiBoldItalic-osf-ot1.vf \
tex-Chivo-SemiBoldItalic-osf-t1--base.tfm \
tex-Chivo-SemiBoldItalic-osf-t1.tfm \
tex-Chivo-SemiBoldItalic-osf-t1.vf \
tex-Chivo-SemiBoldItalic-osf-ts1--base.tfm \
tex-Chivo-SemiBoldItalic-osf-ts1.tfm \
tex-Chivo-SemiBoldItalic-osf-ts1.vf \
tex-Chivo-SemiBoldItalic-sup-ly1--base.tfm \
tex-Chivo-SemiBoldItalic-sup-ly1.tfm \
tex-Chivo-SemiBoldItalic-sup-ly1.vf \
tex-Chivo-SemiBoldItalic-sup-ot1--base.tfm \
tex-Chivo-SemiBoldItalic-sup-ot1.tfm \
tex-Chivo-SemiBoldItalic-sup-ot1.vf \
tex-Chivo-SemiBoldItalic-sup-t1--base.tfm \
tex-Chivo-SemiBoldItalic-sup-t1.tfm \
tex-Chivo-SemiBoldItalic-sup-t1.vf \
tex-Chivo-SemiBoldItalic-tlf-ly1--base.tfm \
tex-Chivo-SemiBoldItalic-tlf-ly1.tfm \
tex-Chivo-SemiBoldItalic-tlf-ly1.vf \
tex-Chivo-SemiBoldItalic-tlf-ot1--base.tfm \
tex-Chivo-SemiBoldItalic-tlf-ot1.tfm \
tex-Chivo-SemiBoldItalic-tlf-ot1.vf \
tex-Chivo-SemiBoldItalic-tlf-t1--base.tfm \
tex-Chivo-SemiBoldItalic-tlf-t1.tfm \
tex-Chivo-SemiBoldItalic-tlf-t1.vf \
tex-Chivo-SemiBoldItalic-tlf-ts1--base.tfm \
tex-Chivo-SemiBoldItalic-tlf-ts1.tfm \
tex-Chivo-SemiBoldItalic-tlf-ts1.vf \
tex-Chivo-SemiBoldItalic-tosf-ly1--base.tfm \
tex-Chivo-SemiBoldItalic-tosf-ly1.tfm \
tex-Chivo-SemiBoldItalic-tosf-ly1.vf \
tex-Chivo-SemiBoldItalic-tosf-ot1--base.tfm \
tex-Chivo-SemiBoldItalic-tosf-ot1.tfm \
tex-Chivo-SemiBoldItalic-tosf-ot1.vf \
tex-Chivo-SemiBoldItalic-tosf-t1--base.tfm \
tex-Chivo-SemiBoldItalic-tosf-t1.tfm \
tex-Chivo-SemiBoldItalic-tosf-t1.vf \
tex-Chivo-SemiBoldItalic-tosf-ts1--base.tfm \
tex-Chivo-SemiBoldItalic-tosf-ts1.tfm \
tex-Chivo-SemiBoldItalic-tosf-ts1.vf \
tex-Chivo-Thin-dnom-ly1--base.tfm \
tex-Chivo-Thin-dnom-ly1.tfm \
tex-Chivo-Thin-dnom-ly1.vf \
tex-Chivo-Thin-dnom-ot1--base.tfm \
tex-Chivo-Thin-dnom-ot1.tfm \
tex-Chivo-Thin-dnom-ot1.vf \
tex-Chivo-Thin-dnom-t1--base.tfm \
tex-Chivo-Thin-dnom-t1.tfm \
tex-Chivo-Thin-dnom-t1.vf \
tex-Chivo-Thin-inf-ly1--base.tfm \
tex-Chivo-Thin-inf-ly1.tfm \
tex-Chivo-Thin-inf-ly1.vf \
tex-Chivo-Thin-inf-ot1--base.tfm \
tex-Chivo-Thin-inf-ot1.tfm \
tex-Chivo-Thin-inf-ot1.vf \
tex-Chivo-Thin-inf-t1--base.tfm \
tex-Chivo-Thin-inf-t1.tfm \
tex-Chivo-Thin-inf-t1.vf \
tex-Chivo-Thin-lf-ly1--base.tfm \
tex-Chivo-Thin-lf-ly1.tfm \
tex-Chivo-Thin-lf-ly1.vf \
tex-Chivo-Thin-lf-ot1--base.tfm \
tex-Chivo-Thin-lf-ot1.tfm \
tex-Chivo-Thin-lf-ot1.vf \
tex-Chivo-Thin-lf-t1--base.tfm \
tex-Chivo-Thin-lf-t1.tfm \
tex-Chivo-Thin-lf-t1.vf \
tex-Chivo-Thin-lf-ts1--base.tfm \
tex-Chivo-Thin-lf-ts1.tfm \
tex-Chivo-Thin-lf-ts1.vf \
tex-Chivo-Thin-numr-ly1--base.tfm \
tex-Chivo-Thin-numr-ly1.tfm \
tex-Chivo-Thin-numr-ly1.vf \
tex-Chivo-Thin-numr-ot1--base.tfm \
tex-Chivo-Thin-numr-ot1.tfm \
tex-Chivo-Thin-numr-ot1.vf \
tex-Chivo-Thin-numr-t1--base.tfm \
tex-Chivo-Thin-numr-t1.tfm \
tex-Chivo-Thin-numr-t1.vf \
tex-Chivo-Thin-osf-ly1--base.tfm \
tex-Chivo-Thin-osf-ly1.tfm \
tex-Chivo-Thin-osf-ly1.vf \
tex-Chivo-Thin-osf-ot1--base.tfm \
tex-Chivo-Thin-osf-ot1.tfm \
tex-Chivo-Thin-osf-ot1.vf \
tex-Chivo-Thin-osf-t1--base.tfm \
tex-Chivo-Thin-osf-t1.tfm \
tex-Chivo-Thin-osf-t1.vf \
tex-Chivo-Thin-osf-ts1--base.tfm \
tex-Chivo-Thin-osf-ts1.tfm \
tex-Chivo-Thin-osf-ts1.vf \
tex-Chivo-Thin-sup-ly1--base.tfm \
tex-Chivo-Thin-sup-ly1.tfm \
tex-Chivo-Thin-sup-ly1.vf \
tex-Chivo-Thin-sup-ot1--base.tfm \
tex-Chivo-Thin-sup-ot1.tfm \
tex-Chivo-Thin-sup-ot1.vf \
tex-Chivo-Thin-sup-t1--base.tfm \
tex-Chivo-Thin-sup-t1.tfm \
tex-Chivo-Thin-sup-t1.vf \
tex-Chivo-Thin-tlf-ly1--base.tfm \
tex-Chivo-Thin-tlf-ly1.tfm \
tex-Chivo-Thin-tlf-ly1.vf \
tex-Chivo-Thin-tlf-ot1--base.tfm \
tex-Chivo-Thin-tlf-ot1.tfm \
tex-Chivo-Thin-tlf-ot1.vf \
tex-Chivo-Thin-tlf-t1--base.tfm \
tex-Chivo-Thin-tlf-t1.tfm \
tex-Chivo-Thin-tlf-t1.vf \
tex-Chivo-Thin-tlf-ts1--base.tfm \
tex-Chivo-Thin-tlf-ts1.tfm \
tex-Chivo-Thin-tlf-ts1.vf \
tex-Chivo-Thin-tosf-ly1--base.tfm \
tex-Chivo-Thin-tosf-ly1.tfm \
tex-Chivo-Thin-tosf-ly1.vf \
tex-Chivo-Thin-tosf-ot1--base.tfm \
tex-Chivo-Thin-tosf-ot1.tfm \
tex-Chivo-Thin-tosf-ot1.vf \
tex-Chivo-Thin-tosf-t1--base.tfm \
tex-Chivo-Thin-tosf-t1.tfm \
tex-Chivo-Thin-tosf-t1.vf \
tex-Chivo-Thin-tosf-ts1--base.tfm \
tex-Chivo-Thin-tosf-ts1.tfm \
tex-Chivo-Thin-tosf-ts1.vf \
tex-Chivo-ThinItalic-dnom-ly1--base.tfm \
tex-Chivo-ThinItalic-dnom-ly1.tfm \
tex-Chivo-ThinItalic-dnom-ly1.vf \
tex-Chivo-ThinItalic-dnom-ot1--base.tfm \
tex-Chivo-ThinItalic-dnom-ot1.tfm \
tex-Chivo-ThinItalic-dnom-ot1.vf \
tex-Chivo-ThinItalic-dnom-t1--base.tfm \
tex-Chivo-ThinItalic-dnom-t1.tfm \
tex-Chivo-ThinItalic-dnom-t1.vf \
tex-Chivo-ThinItalic-inf-ly1--base.tfm \
tex-Chivo-ThinItalic-inf-ly1.tfm \
tex-Chivo-ThinItalic-inf-ly1.vf \
tex-Chivo-ThinItalic-inf-ot1--base.tfm \
tex-Chivo-ThinItalic-inf-ot1.tfm \
tex-Chivo-ThinItalic-inf-ot1.vf \
tex-Chivo-ThinItalic-inf-t1--base.tfm \
tex-Chivo-ThinItalic-inf-t1.tfm \
tex-Chivo-ThinItalic-inf-t1.vf \
tex-Chivo-ThinItalic-lf-ly1--base.tfm \
tex-Chivo-ThinItalic-lf-ly1.tfm \
tex-Chivo-ThinItalic-lf-ly1.vf \
tex-Chivo-ThinItalic-lf-ot1--base.tfm \
tex-Chivo-ThinItalic-lf-ot1.tfm \
tex-Chivo-ThinItalic-lf-ot1.vf \
tex-Chivo-ThinItalic-lf-t1--base.tfm \
tex-Chivo-ThinItalic-lf-t1.tfm \
tex-Chivo-ThinItalic-lf-t1.vf \
tex-Chivo-ThinItalic-lf-ts1--base.tfm \
tex-Chivo-ThinItalic-lf-ts1.tfm \
tex-Chivo-ThinItalic-lf-ts1.vf \
tex-Chivo-ThinItalic-numr-ly1--base.tfm \
tex-Chivo-ThinItalic-numr-ly1.tfm \
tex-Chivo-ThinItalic-numr-ly1.vf \
tex-Chivo-ThinItalic-numr-ot1--base.tfm \
tex-Chivo-ThinItalic-numr-ot1.tfm \
tex-Chivo-ThinItalic-numr-ot1.vf \
tex-Chivo-ThinItalic-numr-t1--base.tfm \
tex-Chivo-ThinItalic-numr-t1.tfm \
tex-Chivo-ThinItalic-numr-t1.vf \
tex-Chivo-ThinItalic-osf-ly1--base.tfm \
tex-Chivo-ThinItalic-osf-ly1.tfm \
tex-Chivo-ThinItalic-osf-ly1.vf \
tex-Chivo-ThinItalic-osf-ot1--base.tfm \
tex-Chivo-ThinItalic-osf-ot1.tfm \
tex-Chivo-ThinItalic-osf-ot1.vf \
tex-Chivo-ThinItalic-osf-t1--base.tfm \
tex-Chivo-ThinItalic-osf-t1.tfm \
tex-Chivo-ThinItalic-osf-t1.vf \
tex-Chivo-ThinItalic-osf-ts1--base.tfm \
tex-Chivo-ThinItalic-osf-ts1.tfm \
tex-Chivo-ThinItalic-osf-ts1.vf \
tex-Chivo-ThinItalic-sup-ly1--base.tfm \
tex-Chivo-ThinItalic-sup-ly1.tfm \
tex-Chivo-ThinItalic-sup-ly1.vf \
tex-Chivo-ThinItalic-sup-ot1--base.tfm \
tex-Chivo-ThinItalic-sup-ot1.tfm \
tex-Chivo-ThinItalic-sup-ot1.vf \
tex-Chivo-ThinItalic-sup-t1--base.tfm \
tex-Chivo-ThinItalic-sup-t1.tfm \
tex-Chivo-ThinItalic-sup-t1.vf \
tex-Chivo-ThinItalic-tlf-ly1--base.tfm \
tex-Chivo-ThinItalic-tlf-ly1.tfm \
tex-Chivo-ThinItalic-tlf-ly1.vf \
tex-Chivo-ThinItalic-tlf-ot1--base.tfm \
tex-Chivo-ThinItalic-tlf-ot1.tfm \
tex-Chivo-ThinItalic-tlf-ot1.vf \
tex-Chivo-ThinItalic-tlf-t1--base.tfm \
tex-Chivo-ThinItalic-tlf-t1.tfm \
tex-Chivo-ThinItalic-tlf-t1.vf \
tex-Chivo-ThinItalic-tlf-ts1--base.tfm \
tex-Chivo-ThinItalic-tlf-ts1.tfm \
tex-Chivo-ThinItalic-tlf-ts1.vf \
tex-Chivo-ThinItalic-tosf-ly1--base.tfm \
tex-Chivo-ThinItalic-tosf-ly1.tfm \
tex-Chivo-ThinItalic-tosf-ly1.vf \
tex-Chivo-ThinItalic-tosf-ot1--base.tfm \
tex-Chivo-ThinItalic-tosf-ot1.tfm \
tex-Chivo-ThinItalic-tosf-ot1.vf \
tex-Chivo-ThinItalic-tosf-t1--base.tfm \
tex-Chivo-ThinItalic-tosf-t1.tfm \
tex-Chivo-ThinItalic-tosf-t1.vf \
tex-Chivo-ThinItalic-tosf-ts1--base.tfm \
tex-Chivo-ThinItalic-tosf-ts1.tfm \
tex-Chivo-ThinItalic-tosf-ts1.vf \
tex-Chivo.map \
tex-Chivo.sty \
tex-LY1Chivo-Dnom.fd \
tex-LY1Chivo-Inf.fd \
tex-LY1Chivo-LF.fd \
tex-LY1Chivo-Numr.fd \
tex-LY1Chivo-OsF.fd \
tex-LY1Chivo-Sup.fd \
tex-LY1Chivo-TLF.fd \
tex-LY1Chivo-TOsF.fd \
tex-OT1Chivo-Dnom.fd \
tex-OT1Chivo-Inf.fd \
tex-OT1Chivo-LF.fd \
tex-OT1Chivo-Numr.fd \
tex-OT1Chivo-OsF.fd \
tex-OT1Chivo-Sup.fd \
tex-OT1Chivo-TLF.fd \
tex-OT1Chivo-TOsF.fd \
tex-T1Chivo-Dnom.fd \
tex-T1Chivo-Inf.fd \
tex-T1Chivo-LF.fd \
tex-T1Chivo-Numr.fd \
tex-T1Chivo-OsF.fd \
tex-T1Chivo-Sup.fd \
tex-T1Chivo-TLF.fd \
tex-T1Chivo-TOsF.fd \
tex-TS1Chivo-LF.fd \
tex-TS1Chivo-OsF.fd \
tex-TS1Chivo-TLF.fd \
tex-TS1Chivo-TOsF.fd \
tex-chi-24xxsv.enc \
tex-chi-2lqlus.enc \
tex-chi-3avctt.enc \
tex-chi-bpya7g.enc \
tex-chi-bv7x5e.enc \
tex-chi-e6xqta.enc \
tex-chi-enwuwl.enc \
tex-chi-fiyauo.enc \
tex-chi-flfbvu.enc \
tex-chi-g5vh6e.enc \
tex-chi-h6jra2.enc \
tex-chi-hlkxho.enc \
tex-chi-htgzz3.enc \
tex-chi-k3a3gz.enc \
tex-chi-krtxg6.enc \
tex-chi-ksf2oq.enc \
tex-chi-lad3zv.enc \
tex-chi-mwxmvo.enc \
tex-chi-oreysz.enc \
tex-chi-phg2dy.enc \
tex-chi-qszeh7.enc \
tex-chi-qxdnz3.enc \
tex-chi-rymxky.enc \
tex-chi-s4nbci.enc \
tex-chi-skmp7i.enc \
tex-chi-sol2hx.enc \
tex-chi-wxmaut.enc \
tex-chi-zvnssh.enc \
texlive-chivo"

RDEPENDS:${PN} += "/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontaxes.sty \
tex-fontspec.sty \
tex-iftex.sty \
tex-kvoptions.sty \
tex-updmap.cfg \
texlive \
texlive-chivo-fonts \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
