SUMMARY = "Lato font family and LaTeX support"
DESCRIPTION = "Lato is a sanserif typeface family designed in the Summer 2010 \
by Warsaw-based designer Lukasz Dziedzic for the tyPoland \
foundry. This font, which includes five weights (hairline, \
light, regular, bold and black), is available from the Google \
Font Directory as TrueType files under the Open Font License \
version 1.1. The package provides support for this font in \
LaTeX. It includes the original TrueType fonts, as well as Type \
1 versions, converted for this package using FontForge for full \
support with Dvips."
LICENSE = "OFL-1.1"

PV = "2023.209.3.3svn54512"

RPM_NAME = "texlive-lato-2023.209.3.3svn54512-55.1.noarch.rpm"
RPM_HASH = "445f9e2dbf27d222248a8c54d9728b90cd22f8730bdf0aeaf011aa6189094f13ff37eb148bc0623073830149f14555d3a2a36c62b7ca02d7d24d5a3284dd61d2"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-LGRlato-LF.fd \
tex-LGRlato-OsF.fd \
tex-LGRlato-TLF.fd \
tex-LGRlato-TOsF.fd \
tex-Lato-Black-LGR-LF--base.tfm \
tex-Lato-Black-LGR-LF.tfm \
tex-Lato-Black-LGR-LF.vf \
tex-Lato-Black-LGR-OsF--base.tfm \
tex-Lato-Black-LGR-OsF.tfm \
tex-Lato-Black-LGR-OsF.vf \
tex-Lato-Black-LGR-TLF--base.tfm \
tex-Lato-Black-LGR-TLF.tfm \
tex-Lato-Black-LGR-TLF.vf \
tex-Lato-Black-LGR-TOsF--base.tfm \
tex-Lato-Black-LGR-TOsF.tfm \
tex-Lato-Black-LGR-TOsF.vf \
tex-Lato-Black-OT1-LF--base.tfm \
tex-Lato-Black-OT1-LF.tfm \
tex-Lato-Black-OT1-LF.vf \
tex-Lato-Black-OT1-OsF--base.tfm \
tex-Lato-Black-OT1-OsF.tfm \
tex-Lato-Black-OT1-OsF.vf \
tex-Lato-Black-OT1-TLF--base.tfm \
tex-Lato-Black-OT1-TLF.tfm \
tex-Lato-Black-OT1-TLF.vf \
tex-Lato-Black-OT1-TOsF--base.tfm \
tex-Lato-Black-OT1-TOsF.tfm \
tex-Lato-Black-OT1-TOsF.vf \
tex-Lato-Black-T1-LF--base.tfm \
tex-Lato-Black-T1-LF.tfm \
tex-Lato-Black-T1-LF.vf \
tex-Lato-Black-T1-OsF--base.tfm \
tex-Lato-Black-T1-OsF.tfm \
tex-Lato-Black-T1-OsF.vf \
tex-Lato-Black-T1-TLF--base.tfm \
tex-Lato-Black-T1-TLF.tfm \
tex-Lato-Black-T1-TLF.vf \
tex-Lato-Black-T1-TOsF--base.tfm \
tex-Lato-Black-T1-TOsF.tfm \
tex-Lato-Black-T1-TOsF.vf \
tex-Lato-Black-T2A-LF--base.tfm \
tex-Lato-Black-T2A-LF.tfm \
tex-Lato-Black-T2A-LF.vf \
tex-Lato-Black-T2A-OsF--base.tfm \
tex-Lato-Black-T2A-OsF.tfm \
tex-Lato-Black-T2A-OsF.vf \
tex-Lato-Black-T2A-TLF--base.tfm \
tex-Lato-Black-T2A-TLF.tfm \
tex-Lato-Black-T2A-TLF.vf \
tex-Lato-Black-T2A-TOsF--base.tfm \
tex-Lato-Black-T2A-TOsF.tfm \
tex-Lato-Black-T2A-TOsF.vf \
tex-Lato-Black-T2B-LF--base.tfm \
tex-Lato-Black-T2B-LF.tfm \
tex-Lato-Black-T2B-LF.vf \
tex-Lato-Black-T2B-OsF--base.tfm \
tex-Lato-Black-T2B-OsF.tfm \
tex-Lato-Black-T2B-OsF.vf \
tex-Lato-Black-T2B-TLF--base.tfm \
tex-Lato-Black-T2B-TLF.tfm \
tex-Lato-Black-T2B-TLF.vf \
tex-Lato-Black-T2B-TOsF--base.tfm \
tex-Lato-Black-T2B-TOsF.tfm \
tex-Lato-Black-T2B-TOsF.vf \
tex-Lato-Black-T2C-LF--base.tfm \
tex-Lato-Black-T2C-LF.tfm \
tex-Lato-Black-T2C-LF.vf \
tex-Lato-Black-T2C-OsF--base.tfm \
tex-Lato-Black-T2C-OsF.tfm \
tex-Lato-Black-T2C-OsF.vf \
tex-Lato-Black-T2C-TLF--base.tfm \
tex-Lato-Black-T2C-TLF.tfm \
tex-Lato-Black-T2C-TLF.vf \
tex-Lato-Black-T2C-TOsF--base.tfm \
tex-Lato-Black-T2C-TOsF.tfm \
tex-Lato-Black-T2C-TOsF.vf \
tex-Lato-Black-TS1-LF--base.tfm \
tex-Lato-Black-TS1-LF.tfm \
tex-Lato-Black-TS1-LF.vf \
tex-Lato-Black-TS1-OsF--base.tfm \
tex-Lato-Black-TS1-OsF.tfm \
tex-Lato-Black-TS1-OsF.vf \
tex-Lato-Black-TS1-TLF--base.tfm \
tex-Lato-Black-TS1-TLF.tfm \
tex-Lato-Black-TS1-TLF.vf \
tex-Lato-Black-TS1-TOsF--base.tfm \
tex-Lato-Black-TS1-TOsF.tfm \
tex-Lato-Black-TS1-TOsF.vf \
tex-Lato-Black-X2-LF--base.tfm \
tex-Lato-Black-X2-LF.tfm \
tex-Lato-Black-X2-LF.vf \
tex-Lato-Black-X2-OsF--base.tfm \
tex-Lato-Black-X2-OsF.tfm \
tex-Lato-Black-X2-OsF.vf \
tex-Lato-Black-X2-TLF--base.tfm \
tex-Lato-Black-X2-TLF.tfm \
tex-Lato-Black-X2-TLF.vf \
tex-Lato-Black-X2-TOsF--base.tfm \
tex-Lato-Black-X2-TOsF.tfm \
tex-Lato-Black-X2-TOsF.vf \
tex-Lato-BlackItalic-LGR-LF--base.tfm \
tex-Lato-BlackItalic-LGR-LF.tfm \
tex-Lato-BlackItalic-LGR-LF.vf \
tex-Lato-BlackItalic-LGR-OsF--base.tfm \
tex-Lato-BlackItalic-LGR-OsF.tfm \
tex-Lato-BlackItalic-LGR-OsF.vf \
tex-Lato-BlackItalic-LGR-TLF--base.tfm \
tex-Lato-BlackItalic-LGR-TLF.tfm \
tex-Lato-BlackItalic-LGR-TLF.vf \
tex-Lato-BlackItalic-LGR-TOsF--base.tfm \
tex-Lato-BlackItalic-LGR-TOsF.tfm \
tex-Lato-BlackItalic-LGR-TOsF.vf \
tex-Lato-BlackItalic-OT1-LF--base.tfm \
tex-Lato-BlackItalic-OT1-LF.tfm \
tex-Lato-BlackItalic-OT1-LF.vf \
tex-Lato-BlackItalic-OT1-OsF--base.tfm \
tex-Lato-BlackItalic-OT1-OsF.tfm \
tex-Lato-BlackItalic-OT1-OsF.vf \
tex-Lato-BlackItalic-OT1-TLF--base.tfm \
tex-Lato-BlackItalic-OT1-TLF.tfm \
tex-Lato-BlackItalic-OT1-TLF.vf \
tex-Lato-BlackItalic-OT1-TOsF--base.tfm \
tex-Lato-BlackItalic-OT1-TOsF.tfm \
tex-Lato-BlackItalic-OT1-TOsF.vf \
tex-Lato-BlackItalic-T1-LF--base.tfm \
tex-Lato-BlackItalic-T1-LF.tfm \
tex-Lato-BlackItalic-T1-LF.vf \
tex-Lato-BlackItalic-T1-OsF--base.tfm \
tex-Lato-BlackItalic-T1-OsF.tfm \
tex-Lato-BlackItalic-T1-OsF.vf \
tex-Lato-BlackItalic-T1-TLF--base.tfm \
tex-Lato-BlackItalic-T1-TLF.tfm \
tex-Lato-BlackItalic-T1-TLF.vf \
tex-Lato-BlackItalic-T1-TOsF--base.tfm \
tex-Lato-BlackItalic-T1-TOsF.tfm \
tex-Lato-BlackItalic-T1-TOsF.vf \
tex-Lato-BlackItalic-T2A-LF--base.tfm \
tex-Lato-BlackItalic-T2A-LF.tfm \
tex-Lato-BlackItalic-T2A-LF.vf \
tex-Lato-BlackItalic-T2A-OsF--base.tfm \
tex-Lato-BlackItalic-T2A-OsF.tfm \
tex-Lato-BlackItalic-T2A-OsF.vf \
tex-Lato-BlackItalic-T2A-TLF--base.tfm \
tex-Lato-BlackItalic-T2A-TLF.tfm \
tex-Lato-BlackItalic-T2A-TLF.vf \
tex-Lato-BlackItalic-T2A-TOsF--base.tfm \
tex-Lato-BlackItalic-T2A-TOsF.tfm \
tex-Lato-BlackItalic-T2A-TOsF.vf \
tex-Lato-BlackItalic-T2B-LF--base.tfm \
tex-Lato-BlackItalic-T2B-LF.tfm \
tex-Lato-BlackItalic-T2B-LF.vf \
tex-Lato-BlackItalic-T2B-OsF--base.tfm \
tex-Lato-BlackItalic-T2B-OsF.tfm \
tex-Lato-BlackItalic-T2B-OsF.vf \
tex-Lato-BlackItalic-T2B-TLF--base.tfm \
tex-Lato-BlackItalic-T2B-TLF.tfm \
tex-Lato-BlackItalic-T2B-TLF.vf \
tex-Lato-BlackItalic-T2B-TOsF--base.tfm \
tex-Lato-BlackItalic-T2B-TOsF.tfm \
tex-Lato-BlackItalic-T2B-TOsF.vf \
tex-Lato-BlackItalic-T2C-LF--base.tfm \
tex-Lato-BlackItalic-T2C-LF.tfm \
tex-Lato-BlackItalic-T2C-LF.vf \
tex-Lato-BlackItalic-T2C-OsF--base.tfm \
tex-Lato-BlackItalic-T2C-OsF.tfm \
tex-Lato-BlackItalic-T2C-OsF.vf \
tex-Lato-BlackItalic-T2C-TLF--base.tfm \
tex-Lato-BlackItalic-T2C-TLF.tfm \
tex-Lato-BlackItalic-T2C-TLF.vf \
tex-Lato-BlackItalic-T2C-TOsF--base.tfm \
tex-Lato-BlackItalic-T2C-TOsF.tfm \
tex-Lato-BlackItalic-T2C-TOsF.vf \
tex-Lato-BlackItalic-TS1-LF--base.tfm \
tex-Lato-BlackItalic-TS1-LF.tfm \
tex-Lato-BlackItalic-TS1-LF.vf \
tex-Lato-BlackItalic-TS1-OsF--base.tfm \
tex-Lato-BlackItalic-TS1-OsF.tfm \
tex-Lato-BlackItalic-TS1-OsF.vf \
tex-Lato-BlackItalic-TS1-TLF--base.tfm \
tex-Lato-BlackItalic-TS1-TLF.tfm \
tex-Lato-BlackItalic-TS1-TLF.vf \
tex-Lato-BlackItalic-TS1-TOsF--base.tfm \
tex-Lato-BlackItalic-TS1-TOsF.tfm \
tex-Lato-BlackItalic-TS1-TOsF.vf \
tex-Lato-BlackItalic-X2-LF--base.tfm \
tex-Lato-BlackItalic-X2-LF.tfm \
tex-Lato-BlackItalic-X2-LF.vf \
tex-Lato-BlackItalic-X2-OsF--base.tfm \
tex-Lato-BlackItalic-X2-OsF.tfm \
tex-Lato-BlackItalic-X2-OsF.vf \
tex-Lato-BlackItalic-X2-TLF--base.tfm \
tex-Lato-BlackItalic-X2-TLF.tfm \
tex-Lato-BlackItalic-X2-TLF.vf \
tex-Lato-BlackItalic-X2-TOsF--base.tfm \
tex-Lato-BlackItalic-X2-TOsF.tfm \
tex-Lato-BlackItalic-X2-TOsF.vf \
tex-Lato-Bold-LGR-LF--base.tfm \
tex-Lato-Bold-LGR-LF.tfm \
tex-Lato-Bold-LGR-LF.vf \
tex-Lato-Bold-LGR-OsF--base.tfm \
tex-Lato-Bold-LGR-OsF.tfm \
tex-Lato-Bold-LGR-OsF.vf \
tex-Lato-Bold-LGR-TLF--base.tfm \
tex-Lato-Bold-LGR-TLF.tfm \
tex-Lato-Bold-LGR-TLF.vf \
tex-Lato-Bold-LGR-TOsF--base.tfm \
tex-Lato-Bold-LGR-TOsF.tfm \
tex-Lato-Bold-LGR-TOsF.vf \
tex-Lato-Bold-OT1-LF--base.tfm \
tex-Lato-Bold-OT1-LF.tfm \
tex-Lato-Bold-OT1-LF.vf \
tex-Lato-Bold-OT1-OsF--base.tfm \
tex-Lato-Bold-OT1-OsF.tfm \
tex-Lato-Bold-OT1-OsF.vf \
tex-Lato-Bold-OT1-TLF--base.tfm \
tex-Lato-Bold-OT1-TLF.tfm \
tex-Lato-Bold-OT1-TLF.vf \
tex-Lato-Bold-OT1-TOsF--base.tfm \
tex-Lato-Bold-OT1-TOsF.tfm \
tex-Lato-Bold-OT1-TOsF.vf \
tex-Lato-Bold-T1-LF--base.tfm \
tex-Lato-Bold-T1-LF.tfm \
tex-Lato-Bold-T1-LF.vf \
tex-Lato-Bold-T1-OsF--base.tfm \
tex-Lato-Bold-T1-OsF.tfm \
tex-Lato-Bold-T1-OsF.vf \
tex-Lato-Bold-T1-TLF--base.tfm \
tex-Lato-Bold-T1-TLF.tfm \
tex-Lato-Bold-T1-TLF.vf \
tex-Lato-Bold-T1-TOsF--base.tfm \
tex-Lato-Bold-T1-TOsF.tfm \
tex-Lato-Bold-T1-TOsF.vf \
tex-Lato-Bold-T2A-LF--base.tfm \
tex-Lato-Bold-T2A-LF.tfm \
tex-Lato-Bold-T2A-LF.vf \
tex-Lato-Bold-T2A-OsF--base.tfm \
tex-Lato-Bold-T2A-OsF.tfm \
tex-Lato-Bold-T2A-OsF.vf \
tex-Lato-Bold-T2A-TLF--base.tfm \
tex-Lato-Bold-T2A-TLF.tfm \
tex-Lato-Bold-T2A-TLF.vf \
tex-Lato-Bold-T2A-TOsF--base.tfm \
tex-Lato-Bold-T2A-TOsF.tfm \
tex-Lato-Bold-T2A-TOsF.vf \
tex-Lato-Bold-T2B-LF--base.tfm \
tex-Lato-Bold-T2B-LF.tfm \
tex-Lato-Bold-T2B-LF.vf \
tex-Lato-Bold-T2B-OsF--base.tfm \
tex-Lato-Bold-T2B-OsF.tfm \
tex-Lato-Bold-T2B-OsF.vf \
tex-Lato-Bold-T2B-TLF--base.tfm \
tex-Lato-Bold-T2B-TLF.tfm \
tex-Lato-Bold-T2B-TLF.vf \
tex-Lato-Bold-T2B-TOsF--base.tfm \
tex-Lato-Bold-T2B-TOsF.tfm \
tex-Lato-Bold-T2B-TOsF.vf \
tex-Lato-Bold-T2C-LF--base.tfm \
tex-Lato-Bold-T2C-LF.tfm \
tex-Lato-Bold-T2C-LF.vf \
tex-Lato-Bold-T2C-OsF--base.tfm \
tex-Lato-Bold-T2C-OsF.tfm \
tex-Lato-Bold-T2C-OsF.vf \
tex-Lato-Bold-T2C-TLF--base.tfm \
tex-Lato-Bold-T2C-TLF.tfm \
tex-Lato-Bold-T2C-TLF.vf \
tex-Lato-Bold-T2C-TOsF--base.tfm \
tex-Lato-Bold-T2C-TOsF.tfm \
tex-Lato-Bold-T2C-TOsF.vf \
tex-Lato-Bold-TS1-LF--base.tfm \
tex-Lato-Bold-TS1-LF.tfm \
tex-Lato-Bold-TS1-LF.vf \
tex-Lato-Bold-TS1-OsF--base.tfm \
tex-Lato-Bold-TS1-OsF.tfm \
tex-Lato-Bold-TS1-OsF.vf \
tex-Lato-Bold-TS1-TLF--base.tfm \
tex-Lato-Bold-TS1-TLF.tfm \
tex-Lato-Bold-TS1-TLF.vf \
tex-Lato-Bold-TS1-TOsF--base.tfm \
tex-Lato-Bold-TS1-TOsF.tfm \
tex-Lato-Bold-TS1-TOsF.vf \
tex-Lato-Bold-X2-LF--base.tfm \
tex-Lato-Bold-X2-LF.tfm \
tex-Lato-Bold-X2-LF.vf \
tex-Lato-Bold-X2-OsF--base.tfm \
tex-Lato-Bold-X2-OsF.tfm \
tex-Lato-Bold-X2-OsF.vf \
tex-Lato-Bold-X2-TLF--base.tfm \
tex-Lato-Bold-X2-TLF.tfm \
tex-Lato-Bold-X2-TLF.vf \
tex-Lato-Bold-X2-TOsF--base.tfm \
tex-Lato-Bold-X2-TOsF.tfm \
tex-Lato-Bold-X2-TOsF.vf \
tex-Lato-BoldItalic-LGR-LF--base.tfm \
tex-Lato-BoldItalic-LGR-LF.tfm \
tex-Lato-BoldItalic-LGR-LF.vf \
tex-Lato-BoldItalic-LGR-OsF--base.tfm \
tex-Lato-BoldItalic-LGR-OsF.tfm \
tex-Lato-BoldItalic-LGR-OsF.vf \
tex-Lato-BoldItalic-LGR-TLF--base.tfm \
tex-Lato-BoldItalic-LGR-TLF.tfm \
tex-Lato-BoldItalic-LGR-TLF.vf \
tex-Lato-BoldItalic-LGR-TOsF--base.tfm \
tex-Lato-BoldItalic-LGR-TOsF.tfm \
tex-Lato-BoldItalic-LGR-TOsF.vf \
tex-Lato-BoldItalic-OT1-LF--base.tfm \
tex-Lato-BoldItalic-OT1-LF.tfm \
tex-Lato-BoldItalic-OT1-LF.vf \
tex-Lato-BoldItalic-OT1-OsF--base.tfm \
tex-Lato-BoldItalic-OT1-OsF.tfm \
tex-Lato-BoldItalic-OT1-OsF.vf \
tex-Lato-BoldItalic-OT1-TLF--base.tfm \
tex-Lato-BoldItalic-OT1-TLF.tfm \
tex-Lato-BoldItalic-OT1-TLF.vf \
tex-Lato-BoldItalic-OT1-TOsF--base.tfm \
tex-Lato-BoldItalic-OT1-TOsF.tfm \
tex-Lato-BoldItalic-OT1-TOsF.vf \
tex-Lato-BoldItalic-T1-LF--base.tfm \
tex-Lato-BoldItalic-T1-LF.tfm \
tex-Lato-BoldItalic-T1-LF.vf \
tex-Lato-BoldItalic-T1-OsF--base.tfm \
tex-Lato-BoldItalic-T1-OsF.tfm \
tex-Lato-BoldItalic-T1-OsF.vf \
tex-Lato-BoldItalic-T1-TLF--base.tfm \
tex-Lato-BoldItalic-T1-TLF.tfm \
tex-Lato-BoldItalic-T1-TLF.vf \
tex-Lato-BoldItalic-T1-TOsF--base.tfm \
tex-Lato-BoldItalic-T1-TOsF.tfm \
tex-Lato-BoldItalic-T1-TOsF.vf \
tex-Lato-BoldItalic-T2A-LF--base.tfm \
tex-Lato-BoldItalic-T2A-LF.tfm \
tex-Lato-BoldItalic-T2A-LF.vf \
tex-Lato-BoldItalic-T2A-OsF--base.tfm \
tex-Lato-BoldItalic-T2A-OsF.tfm \
tex-Lato-BoldItalic-T2A-OsF.vf \
tex-Lato-BoldItalic-T2A-TLF--base.tfm \
tex-Lato-BoldItalic-T2A-TLF.tfm \
tex-Lato-BoldItalic-T2A-TLF.vf \
tex-Lato-BoldItalic-T2A-TOsF--base.tfm \
tex-Lato-BoldItalic-T2A-TOsF.tfm \
tex-Lato-BoldItalic-T2A-TOsF.vf \
tex-Lato-BoldItalic-T2B-LF--base.tfm \
tex-Lato-BoldItalic-T2B-LF.tfm \
tex-Lato-BoldItalic-T2B-LF.vf \
tex-Lato-BoldItalic-T2B-OsF--base.tfm \
tex-Lato-BoldItalic-T2B-OsF.tfm \
tex-Lato-BoldItalic-T2B-OsF.vf \
tex-Lato-BoldItalic-T2B-TLF--base.tfm \
tex-Lato-BoldItalic-T2B-TLF.tfm \
tex-Lato-BoldItalic-T2B-TLF.vf \
tex-Lato-BoldItalic-T2B-TOsF--base.tfm \
tex-Lato-BoldItalic-T2B-TOsF.tfm \
tex-Lato-BoldItalic-T2B-TOsF.vf \
tex-Lato-BoldItalic-T2C-LF--base.tfm \
tex-Lato-BoldItalic-T2C-LF.tfm \
tex-Lato-BoldItalic-T2C-LF.vf \
tex-Lato-BoldItalic-T2C-OsF--base.tfm \
tex-Lato-BoldItalic-T2C-OsF.tfm \
tex-Lato-BoldItalic-T2C-OsF.vf \
tex-Lato-BoldItalic-T2C-TLF--base.tfm \
tex-Lato-BoldItalic-T2C-TLF.tfm \
tex-Lato-BoldItalic-T2C-TLF.vf \
tex-Lato-BoldItalic-T2C-TOsF--base.tfm \
tex-Lato-BoldItalic-T2C-TOsF.tfm \
tex-Lato-BoldItalic-T2C-TOsF.vf \
tex-Lato-BoldItalic-TS1-LF--base.tfm \
tex-Lato-BoldItalic-TS1-LF.tfm \
tex-Lato-BoldItalic-TS1-LF.vf \
tex-Lato-BoldItalic-TS1-OsF--base.tfm \
tex-Lato-BoldItalic-TS1-OsF.tfm \
tex-Lato-BoldItalic-TS1-OsF.vf \
tex-Lato-BoldItalic-TS1-TLF--base.tfm \
tex-Lato-BoldItalic-TS1-TLF.tfm \
tex-Lato-BoldItalic-TS1-TLF.vf \
tex-Lato-BoldItalic-TS1-TOsF--base.tfm \
tex-Lato-BoldItalic-TS1-TOsF.tfm \
tex-Lato-BoldItalic-TS1-TOsF.vf \
tex-Lato-BoldItalic-X2-LF--base.tfm \
tex-Lato-BoldItalic-X2-LF.tfm \
tex-Lato-BoldItalic-X2-LF.vf \
tex-Lato-BoldItalic-X2-OsF--base.tfm \
tex-Lato-BoldItalic-X2-OsF.tfm \
tex-Lato-BoldItalic-X2-OsF.vf \
tex-Lato-BoldItalic-X2-TLF--base.tfm \
tex-Lato-BoldItalic-X2-TLF.tfm \
tex-Lato-BoldItalic-X2-TLF.vf \
tex-Lato-BoldItalic-X2-TOsF--base.tfm \
tex-Lato-BoldItalic-X2-TOsF.tfm \
tex-Lato-BoldItalic-X2-TOsF.vf \
tex-Lato-Hairline-LGR-LF--base.tfm \
tex-Lato-Hairline-LGR-LF.tfm \
tex-Lato-Hairline-LGR-LF.vf \
tex-Lato-Hairline-LGR-OsF--base.tfm \
tex-Lato-Hairline-LGR-OsF.tfm \
tex-Lato-Hairline-LGR-OsF.vf \
tex-Lato-Hairline-LGR-TLF--base.tfm \
tex-Lato-Hairline-LGR-TLF.tfm \
tex-Lato-Hairline-LGR-TLF.vf \
tex-Lato-Hairline-LGR-TOsF--base.tfm \
tex-Lato-Hairline-LGR-TOsF.tfm \
tex-Lato-Hairline-LGR-TOsF.vf \
tex-Lato-Hairline-OT1-LF--base.tfm \
tex-Lato-Hairline-OT1-LF.tfm \
tex-Lato-Hairline-OT1-LF.vf \
tex-Lato-Hairline-OT1-OsF--base.tfm \
tex-Lato-Hairline-OT1-OsF.tfm \
tex-Lato-Hairline-OT1-OsF.vf \
tex-Lato-Hairline-OT1-TLF--base.tfm \
tex-Lato-Hairline-OT1-TLF.tfm \
tex-Lato-Hairline-OT1-TLF.vf \
tex-Lato-Hairline-OT1-TOsF--base.tfm \
tex-Lato-Hairline-OT1-TOsF.tfm \
tex-Lato-Hairline-OT1-TOsF.vf \
tex-Lato-Hairline-T1-LF--base.tfm \
tex-Lato-Hairline-T1-LF.tfm \
tex-Lato-Hairline-T1-LF.vf \
tex-Lato-Hairline-T1-OsF--base.tfm \
tex-Lato-Hairline-T1-OsF.tfm \
tex-Lato-Hairline-T1-OsF.vf \
tex-Lato-Hairline-T1-TLF--base.tfm \
tex-Lato-Hairline-T1-TLF.tfm \
tex-Lato-Hairline-T1-TLF.vf \
tex-Lato-Hairline-T1-TOsF--base.tfm \
tex-Lato-Hairline-T1-TOsF.tfm \
tex-Lato-Hairline-T1-TOsF.vf \
tex-Lato-Hairline-T2A-LF--base.tfm \
tex-Lato-Hairline-T2A-LF.tfm \
tex-Lato-Hairline-T2A-LF.vf \
tex-Lato-Hairline-T2A-OsF--base.tfm \
tex-Lato-Hairline-T2A-OsF.tfm \
tex-Lato-Hairline-T2A-OsF.vf \
tex-Lato-Hairline-T2A-TLF--base.tfm \
tex-Lato-Hairline-T2A-TLF.tfm \
tex-Lato-Hairline-T2A-TLF.vf \
tex-Lato-Hairline-T2A-TOsF--base.tfm \
tex-Lato-Hairline-T2A-TOsF.tfm \
tex-Lato-Hairline-T2A-TOsF.vf \
tex-Lato-Hairline-T2B-LF--base.tfm \
tex-Lato-Hairline-T2B-LF.tfm \
tex-Lato-Hairline-T2B-LF.vf \
tex-Lato-Hairline-T2B-OsF--base.tfm \
tex-Lato-Hairline-T2B-OsF.tfm \
tex-Lato-Hairline-T2B-OsF.vf \
tex-Lato-Hairline-T2B-TLF--base.tfm \
tex-Lato-Hairline-T2B-TLF.tfm \
tex-Lato-Hairline-T2B-TLF.vf \
tex-Lato-Hairline-T2B-TOsF--base.tfm \
tex-Lato-Hairline-T2B-TOsF.tfm \
tex-Lato-Hairline-T2B-TOsF.vf \
tex-Lato-Hairline-T2C-LF--base.tfm \
tex-Lato-Hairline-T2C-LF.tfm \
tex-Lato-Hairline-T2C-LF.vf \
tex-Lato-Hairline-T2C-OsF--base.tfm \
tex-Lato-Hairline-T2C-OsF.tfm \
tex-Lato-Hairline-T2C-OsF.vf \
tex-Lato-Hairline-T2C-TLF--base.tfm \
tex-Lato-Hairline-T2C-TLF.tfm \
tex-Lato-Hairline-T2C-TLF.vf \
tex-Lato-Hairline-T2C-TOsF--base.tfm \
tex-Lato-Hairline-T2C-TOsF.tfm \
tex-Lato-Hairline-T2C-TOsF.vf \
tex-Lato-Hairline-TS1-LF--base.tfm \
tex-Lato-Hairline-TS1-LF.tfm \
tex-Lato-Hairline-TS1-LF.vf \
tex-Lato-Hairline-TS1-OsF--base.tfm \
tex-Lato-Hairline-TS1-OsF.tfm \
tex-Lato-Hairline-TS1-OsF.vf \
tex-Lato-Hairline-TS1-TLF--base.tfm \
tex-Lato-Hairline-TS1-TLF.tfm \
tex-Lato-Hairline-TS1-TLF.vf \
tex-Lato-Hairline-TS1-TOsF--base.tfm \
tex-Lato-Hairline-TS1-TOsF.tfm \
tex-Lato-Hairline-TS1-TOsF.vf \
tex-Lato-Hairline-X2-LF--base.tfm \
tex-Lato-Hairline-X2-LF.tfm \
tex-Lato-Hairline-X2-LF.vf \
tex-Lato-Hairline-X2-OsF--base.tfm \
tex-Lato-Hairline-X2-OsF.tfm \
tex-Lato-Hairline-X2-OsF.vf \
tex-Lato-Hairline-X2-TLF--base.tfm \
tex-Lato-Hairline-X2-TLF.tfm \
tex-Lato-Hairline-X2-TLF.vf \
tex-Lato-Hairline-X2-TOsF--base.tfm \
tex-Lato-Hairline-X2-TOsF.tfm \
tex-Lato-Hairline-X2-TOsF.vf \
tex-Lato-HairlineItalic-LGR-LF--base.tfm \
tex-Lato-HairlineItalic-LGR-LF.tfm \
tex-Lato-HairlineItalic-LGR-LF.vf \
tex-Lato-HairlineItalic-LGR-OsF--base.tfm \
tex-Lato-HairlineItalic-LGR-OsF.tfm \
tex-Lato-HairlineItalic-LGR-OsF.vf \
tex-Lato-HairlineItalic-LGR-TLF--base.tfm \
tex-Lato-HairlineItalic-LGR-TLF.tfm \
tex-Lato-HairlineItalic-LGR-TLF.vf \
tex-Lato-HairlineItalic-LGR-TOsF--base.tfm \
tex-Lato-HairlineItalic-LGR-TOsF.tfm \
tex-Lato-HairlineItalic-LGR-TOsF.vf \
tex-Lato-HairlineItalic-OT1-LF--base.tfm \
tex-Lato-HairlineItalic-OT1-LF.tfm \
tex-Lato-HairlineItalic-OT1-LF.vf \
tex-Lato-HairlineItalic-OT1-OsF--base.tfm \
tex-Lato-HairlineItalic-OT1-OsF.tfm \
tex-Lato-HairlineItalic-OT1-OsF.vf \
tex-Lato-HairlineItalic-OT1-TLF--base.tfm \
tex-Lato-HairlineItalic-OT1-TLF.tfm \
tex-Lato-HairlineItalic-OT1-TLF.vf \
tex-Lato-HairlineItalic-OT1-TOsF--base.tfm \
tex-Lato-HairlineItalic-OT1-TOsF.tfm \
tex-Lato-HairlineItalic-OT1-TOsF.vf \
tex-Lato-HairlineItalic-T1-LF--base.tfm \
tex-Lato-HairlineItalic-T1-LF.tfm \
tex-Lato-HairlineItalic-T1-LF.vf \
tex-Lato-HairlineItalic-T1-OsF--base.tfm \
tex-Lato-HairlineItalic-T1-OsF.tfm \
tex-Lato-HairlineItalic-T1-OsF.vf \
tex-Lato-HairlineItalic-T1-TLF--base.tfm \
tex-Lato-HairlineItalic-T1-TLF.tfm \
tex-Lato-HairlineItalic-T1-TLF.vf \
tex-Lato-HairlineItalic-T1-TOsF--base.tfm \
tex-Lato-HairlineItalic-T1-TOsF.tfm \
tex-Lato-HairlineItalic-T1-TOsF.vf \
tex-Lato-HairlineItalic-T2A-LF--base.tfm \
tex-Lato-HairlineItalic-T2A-LF.tfm \
tex-Lato-HairlineItalic-T2A-LF.vf \
tex-Lato-HairlineItalic-T2A-OsF--base.tfm \
tex-Lato-HairlineItalic-T2A-OsF.tfm \
tex-Lato-HairlineItalic-T2A-OsF.vf \
tex-Lato-HairlineItalic-T2A-TLF--base.tfm \
tex-Lato-HairlineItalic-T2A-TLF.tfm \
tex-Lato-HairlineItalic-T2A-TLF.vf \
tex-Lato-HairlineItalic-T2A-TOsF--base.tfm \
tex-Lato-HairlineItalic-T2A-TOsF.tfm \
tex-Lato-HairlineItalic-T2A-TOsF.vf \
tex-Lato-HairlineItalic-T2B-LF--base.tfm \
tex-Lato-HairlineItalic-T2B-LF.tfm \
tex-Lato-HairlineItalic-T2B-LF.vf \
tex-Lato-HairlineItalic-T2B-OsF--base.tfm \
tex-Lato-HairlineItalic-T2B-OsF.tfm \
tex-Lato-HairlineItalic-T2B-OsF.vf \
tex-Lato-HairlineItalic-T2B-TLF--base.tfm \
tex-Lato-HairlineItalic-T2B-TLF.tfm \
tex-Lato-HairlineItalic-T2B-TLF.vf \
tex-Lato-HairlineItalic-T2B-TOsF--base.tfm \
tex-Lato-HairlineItalic-T2B-TOsF.tfm \
tex-Lato-HairlineItalic-T2B-TOsF.vf \
tex-Lato-HairlineItalic-T2C-LF--base.tfm \
tex-Lato-HairlineItalic-T2C-LF.tfm \
tex-Lato-HairlineItalic-T2C-LF.vf \
tex-Lato-HairlineItalic-T2C-OsF--base.tfm \
tex-Lato-HairlineItalic-T2C-OsF.tfm \
tex-Lato-HairlineItalic-T2C-OsF.vf \
tex-Lato-HairlineItalic-T2C-TLF--base.tfm \
tex-Lato-HairlineItalic-T2C-TLF.tfm \
tex-Lato-HairlineItalic-T2C-TLF.vf \
tex-Lato-HairlineItalic-T2C-TOsF--base.tfm \
tex-Lato-HairlineItalic-T2C-TOsF.tfm \
tex-Lato-HairlineItalic-T2C-TOsF.vf \
tex-Lato-HairlineItalic-TS1-LF--base.tfm \
tex-Lato-HairlineItalic-TS1-LF.tfm \
tex-Lato-HairlineItalic-TS1-LF.vf \
tex-Lato-HairlineItalic-TS1-OsF--base.tfm \
tex-Lato-HairlineItalic-TS1-OsF.tfm \
tex-Lato-HairlineItalic-TS1-OsF.vf \
tex-Lato-HairlineItalic-TS1-TLF--base.tfm \
tex-Lato-HairlineItalic-TS1-TLF.tfm \
tex-Lato-HairlineItalic-TS1-TLF.vf \
tex-Lato-HairlineItalic-TS1-TOsF--base.tfm \
tex-Lato-HairlineItalic-TS1-TOsF.tfm \
tex-Lato-HairlineItalic-TS1-TOsF.vf \
tex-Lato-HairlineItalic-X2-LF--base.tfm \
tex-Lato-HairlineItalic-X2-LF.tfm \
tex-Lato-HairlineItalic-X2-LF.vf \
tex-Lato-HairlineItalic-X2-OsF--base.tfm \
tex-Lato-HairlineItalic-X2-OsF.tfm \
tex-Lato-HairlineItalic-X2-OsF.vf \
tex-Lato-HairlineItalic-X2-TLF--base.tfm \
tex-Lato-HairlineItalic-X2-TLF.tfm \
tex-Lato-HairlineItalic-X2-TLF.vf \
tex-Lato-HairlineItalic-X2-TOsF--base.tfm \
tex-Lato-HairlineItalic-X2-TOsF.tfm \
tex-Lato-HairlineItalic-X2-TOsF.vf \
tex-Lato-Heavy-LGR-LF--base.tfm \
tex-Lato-Heavy-LGR-LF.tfm \
tex-Lato-Heavy-LGR-LF.vf \
tex-Lato-Heavy-LGR-OsF--base.tfm \
tex-Lato-Heavy-LGR-OsF.tfm \
tex-Lato-Heavy-LGR-OsF.vf \
tex-Lato-Heavy-LGR-TLF--base.tfm \
tex-Lato-Heavy-LGR-TLF.tfm \
tex-Lato-Heavy-LGR-TLF.vf \
tex-Lato-Heavy-LGR-TOsF--base.tfm \
tex-Lato-Heavy-LGR-TOsF.tfm \
tex-Lato-Heavy-LGR-TOsF.vf \
tex-Lato-Heavy-OT1-LF--base.tfm \
tex-Lato-Heavy-OT1-LF.tfm \
tex-Lato-Heavy-OT1-LF.vf \
tex-Lato-Heavy-OT1-OsF--base.tfm \
tex-Lato-Heavy-OT1-OsF.tfm \
tex-Lato-Heavy-OT1-OsF.vf \
tex-Lato-Heavy-OT1-TLF--base.tfm \
tex-Lato-Heavy-OT1-TLF.tfm \
tex-Lato-Heavy-OT1-TLF.vf \
tex-Lato-Heavy-OT1-TOsF--base.tfm \
tex-Lato-Heavy-OT1-TOsF.tfm \
tex-Lato-Heavy-OT1-TOsF.vf \
tex-Lato-Heavy-T1-LF--base.tfm \
tex-Lato-Heavy-T1-LF.tfm \
tex-Lato-Heavy-T1-LF.vf \
tex-Lato-Heavy-T1-OsF--base.tfm \
tex-Lato-Heavy-T1-OsF.tfm \
tex-Lato-Heavy-T1-OsF.vf \
tex-Lato-Heavy-T1-TLF--base.tfm \
tex-Lato-Heavy-T1-TLF.tfm \
tex-Lato-Heavy-T1-TLF.vf \
tex-Lato-Heavy-T1-TOsF--base.tfm \
tex-Lato-Heavy-T1-TOsF.tfm \
tex-Lato-Heavy-T1-TOsF.vf \
tex-Lato-Heavy-T2A-LF--base.tfm \
tex-Lato-Heavy-T2A-LF.tfm \
tex-Lato-Heavy-T2A-LF.vf \
tex-Lato-Heavy-T2A-OsF--base.tfm \
tex-Lato-Heavy-T2A-OsF.tfm \
tex-Lato-Heavy-T2A-OsF.vf \
tex-Lato-Heavy-T2A-TLF--base.tfm \
tex-Lato-Heavy-T2A-TLF.tfm \
tex-Lato-Heavy-T2A-TLF.vf \
tex-Lato-Heavy-T2A-TOsF--base.tfm \
tex-Lato-Heavy-T2A-TOsF.tfm \
tex-Lato-Heavy-T2A-TOsF.vf \
tex-Lato-Heavy-T2B-LF--base.tfm \
tex-Lato-Heavy-T2B-LF.tfm \
tex-Lato-Heavy-T2B-LF.vf \
tex-Lato-Heavy-T2B-OsF--base.tfm \
tex-Lato-Heavy-T2B-OsF.tfm \
tex-Lato-Heavy-T2B-OsF.vf \
tex-Lato-Heavy-T2B-TLF--base.tfm \
tex-Lato-Heavy-T2B-TLF.tfm \
tex-Lato-Heavy-T2B-TLF.vf \
tex-Lato-Heavy-T2B-TOsF--base.tfm \
tex-Lato-Heavy-T2B-TOsF.tfm \
tex-Lato-Heavy-T2B-TOsF.vf \
tex-Lato-Heavy-T2C-LF--base.tfm \
tex-Lato-Heavy-T2C-LF.tfm \
tex-Lato-Heavy-T2C-LF.vf \
tex-Lato-Heavy-T2C-OsF--base.tfm \
tex-Lato-Heavy-T2C-OsF.tfm \
tex-Lato-Heavy-T2C-OsF.vf \
tex-Lato-Heavy-T2C-TLF--base.tfm \
tex-Lato-Heavy-T2C-TLF.tfm \
tex-Lato-Heavy-T2C-TLF.vf \
tex-Lato-Heavy-T2C-TOsF--base.tfm \
tex-Lato-Heavy-T2C-TOsF.tfm \
tex-Lato-Heavy-T2C-TOsF.vf \
tex-Lato-Heavy-TS1-LF--base.tfm \
tex-Lato-Heavy-TS1-LF.tfm \
tex-Lato-Heavy-TS1-LF.vf \
tex-Lato-Heavy-TS1-OsF--base.tfm \
tex-Lato-Heavy-TS1-OsF.tfm \
tex-Lato-Heavy-TS1-OsF.vf \
tex-Lato-Heavy-TS1-TLF--base.tfm \
tex-Lato-Heavy-TS1-TLF.tfm \
tex-Lato-Heavy-TS1-TLF.vf \
tex-Lato-Heavy-TS1-TOsF--base.tfm \
tex-Lato-Heavy-TS1-TOsF.tfm \
tex-Lato-Heavy-TS1-TOsF.vf \
tex-Lato-Heavy-X2-LF--base.tfm \
tex-Lato-Heavy-X2-LF.tfm \
tex-Lato-Heavy-X2-LF.vf \
tex-Lato-Heavy-X2-OsF--base.tfm \
tex-Lato-Heavy-X2-OsF.tfm \
tex-Lato-Heavy-X2-OsF.vf \
tex-Lato-Heavy-X2-TLF--base.tfm \
tex-Lato-Heavy-X2-TLF.tfm \
tex-Lato-Heavy-X2-TLF.vf \
tex-Lato-Heavy-X2-TOsF--base.tfm \
tex-Lato-Heavy-X2-TOsF.tfm \
tex-Lato-Heavy-X2-TOsF.vf \
tex-Lato-HeavyItalic-LGR-LF--base.tfm \
tex-Lato-HeavyItalic-LGR-LF.tfm \
tex-Lato-HeavyItalic-LGR-LF.vf \
tex-Lato-HeavyItalic-LGR-OsF--base.tfm \
tex-Lato-HeavyItalic-LGR-OsF.tfm \
tex-Lato-HeavyItalic-LGR-OsF.vf \
tex-Lato-HeavyItalic-LGR-TLF--base.tfm \
tex-Lato-HeavyItalic-LGR-TLF.tfm \
tex-Lato-HeavyItalic-LGR-TLF.vf \
tex-Lato-HeavyItalic-LGR-TOsF--base.tfm \
tex-Lato-HeavyItalic-LGR-TOsF.tfm \
tex-Lato-HeavyItalic-LGR-TOsF.vf \
tex-Lato-HeavyItalic-OT1-LF--base.tfm \
tex-Lato-HeavyItalic-OT1-LF.tfm \
tex-Lato-HeavyItalic-OT1-LF.vf \
tex-Lato-HeavyItalic-OT1-OsF--base.tfm \
tex-Lato-HeavyItalic-OT1-OsF.tfm \
tex-Lato-HeavyItalic-OT1-OsF.vf \
tex-Lato-HeavyItalic-OT1-TLF--base.tfm \
tex-Lato-HeavyItalic-OT1-TLF.tfm \
tex-Lato-HeavyItalic-OT1-TLF.vf \
tex-Lato-HeavyItalic-OT1-TOsF--base.tfm \
tex-Lato-HeavyItalic-OT1-TOsF.tfm \
tex-Lato-HeavyItalic-OT1-TOsF.vf \
tex-Lato-HeavyItalic-T1-LF--base.tfm \
tex-Lato-HeavyItalic-T1-LF.tfm \
tex-Lato-HeavyItalic-T1-LF.vf \
tex-Lato-HeavyItalic-T1-OsF--base.tfm \
tex-Lato-HeavyItalic-T1-OsF.tfm \
tex-Lato-HeavyItalic-T1-OsF.vf \
tex-Lato-HeavyItalic-T1-TLF--base.tfm \
tex-Lato-HeavyItalic-T1-TLF.tfm \
tex-Lato-HeavyItalic-T1-TLF.vf \
tex-Lato-HeavyItalic-T1-TOsF--base.tfm \
tex-Lato-HeavyItalic-T1-TOsF.tfm \
tex-Lato-HeavyItalic-T1-TOsF.vf \
tex-Lato-HeavyItalic-T2A-LF--base.tfm \
tex-Lato-HeavyItalic-T2A-LF.tfm \
tex-Lato-HeavyItalic-T2A-LF.vf \
tex-Lato-HeavyItalic-T2A-OsF--base.tfm \
tex-Lato-HeavyItalic-T2A-OsF.tfm \
tex-Lato-HeavyItalic-T2A-OsF.vf \
tex-Lato-HeavyItalic-T2A-TLF--base.tfm \
tex-Lato-HeavyItalic-T2A-TLF.tfm \
tex-Lato-HeavyItalic-T2A-TLF.vf \
tex-Lato-HeavyItalic-T2A-TOsF--base.tfm \
tex-Lato-HeavyItalic-T2A-TOsF.tfm \
tex-Lato-HeavyItalic-T2A-TOsF.vf \
tex-Lato-HeavyItalic-T2B-LF--base.tfm \
tex-Lato-HeavyItalic-T2B-LF.tfm \
tex-Lato-HeavyItalic-T2B-LF.vf \
tex-Lato-HeavyItalic-T2B-OsF--base.tfm \
tex-Lato-HeavyItalic-T2B-OsF.tfm \
tex-Lato-HeavyItalic-T2B-OsF.vf \
tex-Lato-HeavyItalic-T2B-TLF--base.tfm \
tex-Lato-HeavyItalic-T2B-TLF.tfm \
tex-Lato-HeavyItalic-T2B-TLF.vf \
tex-Lato-HeavyItalic-T2B-TOsF--base.tfm \
tex-Lato-HeavyItalic-T2B-TOsF.tfm \
tex-Lato-HeavyItalic-T2B-TOsF.vf \
tex-Lato-HeavyItalic-T2C-LF--base.tfm \
tex-Lato-HeavyItalic-T2C-LF.tfm \
tex-Lato-HeavyItalic-T2C-LF.vf \
tex-Lato-HeavyItalic-T2C-OsF--base.tfm \
tex-Lato-HeavyItalic-T2C-OsF.tfm \
tex-Lato-HeavyItalic-T2C-OsF.vf \
tex-Lato-HeavyItalic-T2C-TLF--base.tfm \
tex-Lato-HeavyItalic-T2C-TLF.tfm \
tex-Lato-HeavyItalic-T2C-TLF.vf \
tex-Lato-HeavyItalic-T2C-TOsF--base.tfm \
tex-Lato-HeavyItalic-T2C-TOsF.tfm \
tex-Lato-HeavyItalic-T2C-TOsF.vf \
tex-Lato-HeavyItalic-TS1-LF--base.tfm \
tex-Lato-HeavyItalic-TS1-LF.tfm \
tex-Lato-HeavyItalic-TS1-LF.vf \
tex-Lato-HeavyItalic-TS1-OsF--base.tfm \
tex-Lato-HeavyItalic-TS1-OsF.tfm \
tex-Lato-HeavyItalic-TS1-OsF.vf \
tex-Lato-HeavyItalic-TS1-TLF--base.tfm \
tex-Lato-HeavyItalic-TS1-TLF.tfm \
tex-Lato-HeavyItalic-TS1-TLF.vf \
tex-Lato-HeavyItalic-TS1-TOsF--base.tfm \
tex-Lato-HeavyItalic-TS1-TOsF.tfm \
tex-Lato-HeavyItalic-TS1-TOsF.vf \
tex-Lato-HeavyItalic-X2-LF--base.tfm \
tex-Lato-HeavyItalic-X2-LF.tfm \
tex-Lato-HeavyItalic-X2-LF.vf \
tex-Lato-HeavyItalic-X2-OsF--base.tfm \
tex-Lato-HeavyItalic-X2-OsF.tfm \
tex-Lato-HeavyItalic-X2-OsF.vf \
tex-Lato-HeavyItalic-X2-TLF--base.tfm \
tex-Lato-HeavyItalic-X2-TLF.tfm \
tex-Lato-HeavyItalic-X2-TLF.vf \
tex-Lato-HeavyItalic-X2-TOsF--base.tfm \
tex-Lato-HeavyItalic-X2-TOsF.tfm \
tex-Lato-HeavyItalic-X2-TOsF.vf \
tex-Lato-Italic-LGR-LF--base.tfm \
tex-Lato-Italic-LGR-LF.tfm \
tex-Lato-Italic-LGR-LF.vf \
tex-Lato-Italic-LGR-OsF--base.tfm \
tex-Lato-Italic-LGR-OsF.tfm \
tex-Lato-Italic-LGR-OsF.vf \
tex-Lato-Italic-LGR-TLF--base.tfm \
tex-Lato-Italic-LGR-TLF.tfm \
tex-Lato-Italic-LGR-TLF.vf \
tex-Lato-Italic-LGR-TOsF--base.tfm \
tex-Lato-Italic-LGR-TOsF.tfm \
tex-Lato-Italic-LGR-TOsF.vf \
tex-Lato-Italic-OT1-LF--base.tfm \
tex-Lato-Italic-OT1-LF.tfm \
tex-Lato-Italic-OT1-LF.vf \
tex-Lato-Italic-OT1-OsF--base.tfm \
tex-Lato-Italic-OT1-OsF.tfm \
tex-Lato-Italic-OT1-OsF.vf \
tex-Lato-Italic-OT1-TLF--base.tfm \
tex-Lato-Italic-OT1-TLF.tfm \
tex-Lato-Italic-OT1-TLF.vf \
tex-Lato-Italic-OT1-TOsF--base.tfm \
tex-Lato-Italic-OT1-TOsF.tfm \
tex-Lato-Italic-OT1-TOsF.vf \
tex-Lato-Italic-T1-LF--base.tfm \
tex-Lato-Italic-T1-LF.tfm \
tex-Lato-Italic-T1-LF.vf \
tex-Lato-Italic-T1-OsF--base.tfm \
tex-Lato-Italic-T1-OsF.tfm \
tex-Lato-Italic-T1-OsF.vf \
tex-Lato-Italic-T1-TLF--base.tfm \
tex-Lato-Italic-T1-TLF.tfm \
tex-Lato-Italic-T1-TLF.vf \
tex-Lato-Italic-T1-TOsF--base.tfm \
tex-Lato-Italic-T1-TOsF.tfm \
tex-Lato-Italic-T1-TOsF.vf \
tex-Lato-Italic-T2A-LF--base.tfm \
tex-Lato-Italic-T2A-LF.tfm \
tex-Lato-Italic-T2A-LF.vf \
tex-Lato-Italic-T2A-OsF--base.tfm \
tex-Lato-Italic-T2A-OsF.tfm \
tex-Lato-Italic-T2A-OsF.vf \
tex-Lato-Italic-T2A-TLF--base.tfm \
tex-Lato-Italic-T2A-TLF.tfm \
tex-Lato-Italic-T2A-TLF.vf \
tex-Lato-Italic-T2A-TOsF--base.tfm \
tex-Lato-Italic-T2A-TOsF.tfm \
tex-Lato-Italic-T2A-TOsF.vf \
tex-Lato-Italic-T2B-LF--base.tfm \
tex-Lato-Italic-T2B-LF.tfm \
tex-Lato-Italic-T2B-LF.vf \
tex-Lato-Italic-T2B-OsF--base.tfm \
tex-Lato-Italic-T2B-OsF.tfm \
tex-Lato-Italic-T2B-OsF.vf \
tex-Lato-Italic-T2B-TLF--base.tfm \
tex-Lato-Italic-T2B-TLF.tfm \
tex-Lato-Italic-T2B-TLF.vf \
tex-Lato-Italic-T2B-TOsF--base.tfm \
tex-Lato-Italic-T2B-TOsF.tfm \
tex-Lato-Italic-T2B-TOsF.vf \
tex-Lato-Italic-T2C-LF--base.tfm \
tex-Lato-Italic-T2C-LF.tfm \
tex-Lato-Italic-T2C-LF.vf \
tex-Lato-Italic-T2C-OsF--base.tfm \
tex-Lato-Italic-T2C-OsF.tfm \
tex-Lato-Italic-T2C-OsF.vf \
tex-Lato-Italic-T2C-TLF--base.tfm \
tex-Lato-Italic-T2C-TLF.tfm \
tex-Lato-Italic-T2C-TLF.vf \
tex-Lato-Italic-T2C-TOsF--base.tfm \
tex-Lato-Italic-T2C-TOsF.tfm \
tex-Lato-Italic-T2C-TOsF.vf \
tex-Lato-Italic-TS1-LF--base.tfm \
tex-Lato-Italic-TS1-LF.tfm \
tex-Lato-Italic-TS1-LF.vf \
tex-Lato-Italic-TS1-OsF--base.tfm \
tex-Lato-Italic-TS1-OsF.tfm \
tex-Lato-Italic-TS1-OsF.vf \
tex-Lato-Italic-TS1-TLF--base.tfm \
tex-Lato-Italic-TS1-TLF.tfm \
tex-Lato-Italic-TS1-TLF.vf \
tex-Lato-Italic-TS1-TOsF--base.tfm \
tex-Lato-Italic-TS1-TOsF.tfm \
tex-Lato-Italic-TS1-TOsF.vf \
tex-Lato-Italic-X2-LF--base.tfm \
tex-Lato-Italic-X2-LF.tfm \
tex-Lato-Italic-X2-LF.vf \
tex-Lato-Italic-X2-OsF--base.tfm \
tex-Lato-Italic-X2-OsF.tfm \
tex-Lato-Italic-X2-OsF.vf \
tex-Lato-Italic-X2-TLF--base.tfm \
tex-Lato-Italic-X2-TLF.tfm \
tex-Lato-Italic-X2-TLF.vf \
tex-Lato-Italic-X2-TOsF--base.tfm \
tex-Lato-Italic-X2-TOsF.tfm \
tex-Lato-Italic-X2-TOsF.vf \
tex-Lato-Light-LGR-LF--base.tfm \
tex-Lato-Light-LGR-LF.tfm \
tex-Lato-Light-LGR-LF.vf \
tex-Lato-Light-LGR-OsF--base.tfm \
tex-Lato-Light-LGR-OsF.tfm \
tex-Lato-Light-LGR-OsF.vf \
tex-Lato-Light-LGR-TLF--base.tfm \
tex-Lato-Light-LGR-TLF.tfm \
tex-Lato-Light-LGR-TLF.vf \
tex-Lato-Light-LGR-TOsF--base.tfm \
tex-Lato-Light-LGR-TOsF.tfm \
tex-Lato-Light-LGR-TOsF.vf \
tex-Lato-Light-OT1-LF--base.tfm \
tex-Lato-Light-OT1-LF.tfm \
tex-Lato-Light-OT1-LF.vf \
tex-Lato-Light-OT1-OsF--base.tfm \
tex-Lato-Light-OT1-OsF.tfm \
tex-Lato-Light-OT1-OsF.vf \
tex-Lato-Light-OT1-TLF--base.tfm \
tex-Lato-Light-OT1-TLF.tfm \
tex-Lato-Light-OT1-TLF.vf \
tex-Lato-Light-OT1-TOsF--base.tfm \
tex-Lato-Light-OT1-TOsF.tfm \
tex-Lato-Light-OT1-TOsF.vf \
tex-Lato-Light-T1-LF--base.tfm \
tex-Lato-Light-T1-LF.tfm \
tex-Lato-Light-T1-LF.vf \
tex-Lato-Light-T1-OsF--base.tfm \
tex-Lato-Light-T1-OsF.tfm \
tex-Lato-Light-T1-OsF.vf \
tex-Lato-Light-T1-TLF--base.tfm \
tex-Lato-Light-T1-TLF.tfm \
tex-Lato-Light-T1-TLF.vf \
tex-Lato-Light-T1-TOsF--base.tfm \
tex-Lato-Light-T1-TOsF.tfm \
tex-Lato-Light-T1-TOsF.vf \
tex-Lato-Light-T2A-LF--base.tfm \
tex-Lato-Light-T2A-LF.tfm \
tex-Lato-Light-T2A-LF.vf \
tex-Lato-Light-T2A-OsF--base.tfm \
tex-Lato-Light-T2A-OsF.tfm \
tex-Lato-Light-T2A-OsF.vf \
tex-Lato-Light-T2A-TLF--base.tfm \
tex-Lato-Light-T2A-TLF.tfm \
tex-Lato-Light-T2A-TLF.vf \
tex-Lato-Light-T2A-TOsF--base.tfm \
tex-Lato-Light-T2A-TOsF.tfm \
tex-Lato-Light-T2A-TOsF.vf \
tex-Lato-Light-T2B-LF--base.tfm \
tex-Lato-Light-T2B-LF.tfm \
tex-Lato-Light-T2B-LF.vf \
tex-Lato-Light-T2B-OsF--base.tfm \
tex-Lato-Light-T2B-OsF.tfm \
tex-Lato-Light-T2B-OsF.vf \
tex-Lato-Light-T2B-TLF--base.tfm \
tex-Lato-Light-T2B-TLF.tfm \
tex-Lato-Light-T2B-TLF.vf \
tex-Lato-Light-T2B-TOsF--base.tfm \
tex-Lato-Light-T2B-TOsF.tfm \
tex-Lato-Light-T2B-TOsF.vf \
tex-Lato-Light-T2C-LF--base.tfm \
tex-Lato-Light-T2C-LF.tfm \
tex-Lato-Light-T2C-LF.vf \
tex-Lato-Light-T2C-OsF--base.tfm \
tex-Lato-Light-T2C-OsF.tfm \
tex-Lato-Light-T2C-OsF.vf \
tex-Lato-Light-T2C-TLF--base.tfm \
tex-Lato-Light-T2C-TLF.tfm \
tex-Lato-Light-T2C-TLF.vf \
tex-Lato-Light-T2C-TOsF--base.tfm \
tex-Lato-Light-T2C-TOsF.tfm \
tex-Lato-Light-T2C-TOsF.vf \
tex-Lato-Light-TS1-LF--base.tfm \
tex-Lato-Light-TS1-LF.tfm \
tex-Lato-Light-TS1-LF.vf \
tex-Lato-Light-TS1-OsF--base.tfm \
tex-Lato-Light-TS1-OsF.tfm \
tex-Lato-Light-TS1-OsF.vf \
tex-Lato-Light-TS1-TLF--base.tfm \
tex-Lato-Light-TS1-TLF.tfm \
tex-Lato-Light-TS1-TLF.vf \
tex-Lato-Light-TS1-TOsF--base.tfm \
tex-Lato-Light-TS1-TOsF.tfm \
tex-Lato-Light-TS1-TOsF.vf \
tex-Lato-Light-X2-LF--base.tfm \
tex-Lato-Light-X2-LF.tfm \
tex-Lato-Light-X2-LF.vf \
tex-Lato-Light-X2-OsF--base.tfm \
tex-Lato-Light-X2-OsF.tfm \
tex-Lato-Light-X2-OsF.vf \
tex-Lato-Light-X2-TLF--base.tfm \
tex-Lato-Light-X2-TLF.tfm \
tex-Lato-Light-X2-TLF.vf \
tex-Lato-Light-X2-TOsF--base.tfm \
tex-Lato-Light-X2-TOsF.tfm \
tex-Lato-Light-X2-TOsF.vf \
tex-Lato-LightItalic-LGR-LF--base.tfm \
tex-Lato-LightItalic-LGR-LF.tfm \
tex-Lato-LightItalic-LGR-LF.vf \
tex-Lato-LightItalic-LGR-OsF--base.tfm \
tex-Lato-LightItalic-LGR-OsF.tfm \
tex-Lato-LightItalic-LGR-OsF.vf \
tex-Lato-LightItalic-LGR-TLF--base.tfm \
tex-Lato-LightItalic-LGR-TLF.tfm \
tex-Lato-LightItalic-LGR-TLF.vf \
tex-Lato-LightItalic-LGR-TOsF--base.tfm \
tex-Lato-LightItalic-LGR-TOsF.tfm \
tex-Lato-LightItalic-LGR-TOsF.vf \
tex-Lato-LightItalic-OT1-LF--base.tfm \
tex-Lato-LightItalic-OT1-LF.tfm \
tex-Lato-LightItalic-OT1-LF.vf \
tex-Lato-LightItalic-OT1-OsF--base.tfm \
tex-Lato-LightItalic-OT1-OsF.tfm \
tex-Lato-LightItalic-OT1-OsF.vf \
tex-Lato-LightItalic-OT1-TLF--base.tfm \
tex-Lato-LightItalic-OT1-TLF.tfm \
tex-Lato-LightItalic-OT1-TLF.vf \
tex-Lato-LightItalic-OT1-TOsF--base.tfm \
tex-Lato-LightItalic-OT1-TOsF.tfm \
tex-Lato-LightItalic-OT1-TOsF.vf \
tex-Lato-LightItalic-T1-LF--base.tfm \
tex-Lato-LightItalic-T1-LF.tfm \
tex-Lato-LightItalic-T1-LF.vf \
tex-Lato-LightItalic-T1-OsF--base.tfm \
tex-Lato-LightItalic-T1-OsF.tfm \
tex-Lato-LightItalic-T1-OsF.vf \
tex-Lato-LightItalic-T1-TLF--base.tfm \
tex-Lato-LightItalic-T1-TLF.tfm \
tex-Lato-LightItalic-T1-TLF.vf \
tex-Lato-LightItalic-T1-TOsF--base.tfm \
tex-Lato-LightItalic-T1-TOsF.tfm \
tex-Lato-LightItalic-T1-TOsF.vf \
tex-Lato-LightItalic-T2A-LF--base.tfm \
tex-Lato-LightItalic-T2A-LF.tfm \
tex-Lato-LightItalic-T2A-LF.vf \
tex-Lato-LightItalic-T2A-OsF--base.tfm \
tex-Lato-LightItalic-T2A-OsF.tfm \
tex-Lato-LightItalic-T2A-OsF.vf \
tex-Lato-LightItalic-T2A-TLF--base.tfm \
tex-Lato-LightItalic-T2A-TLF.tfm \
tex-Lato-LightItalic-T2A-TLF.vf \
tex-Lato-LightItalic-T2A-TOsF--base.tfm \
tex-Lato-LightItalic-T2A-TOsF.tfm \
tex-Lato-LightItalic-T2A-TOsF.vf \
tex-Lato-LightItalic-T2B-LF--base.tfm \
tex-Lato-LightItalic-T2B-LF.tfm \
tex-Lato-LightItalic-T2B-LF.vf \
tex-Lato-LightItalic-T2B-OsF--base.tfm \
tex-Lato-LightItalic-T2B-OsF.tfm \
tex-Lato-LightItalic-T2B-OsF.vf \
tex-Lato-LightItalic-T2B-TLF--base.tfm \
tex-Lato-LightItalic-T2B-TLF.tfm \
tex-Lato-LightItalic-T2B-TLF.vf \
tex-Lato-LightItalic-T2B-TOsF--base.tfm \
tex-Lato-LightItalic-T2B-TOsF.tfm \
tex-Lato-LightItalic-T2B-TOsF.vf \
tex-Lato-LightItalic-T2C-LF--base.tfm \
tex-Lato-LightItalic-T2C-LF.tfm \
tex-Lato-LightItalic-T2C-LF.vf \
tex-Lato-LightItalic-T2C-OsF--base.tfm \
tex-Lato-LightItalic-T2C-OsF.tfm \
tex-Lato-LightItalic-T2C-OsF.vf \
tex-Lato-LightItalic-T2C-TLF--base.tfm \
tex-Lato-LightItalic-T2C-TLF.tfm \
tex-Lato-LightItalic-T2C-TLF.vf \
tex-Lato-LightItalic-T2C-TOsF--base.tfm \
tex-Lato-LightItalic-T2C-TOsF.tfm \
tex-Lato-LightItalic-T2C-TOsF.vf \
tex-Lato-LightItalic-TS1-LF--base.tfm \
tex-Lato-LightItalic-TS1-LF.tfm \
tex-Lato-LightItalic-TS1-LF.vf \
tex-Lato-LightItalic-TS1-OsF--base.tfm \
tex-Lato-LightItalic-TS1-OsF.tfm \
tex-Lato-LightItalic-TS1-OsF.vf \
tex-Lato-LightItalic-TS1-TLF--base.tfm \
tex-Lato-LightItalic-TS1-TLF.tfm \
tex-Lato-LightItalic-TS1-TLF.vf \
tex-Lato-LightItalic-TS1-TOsF--base.tfm \
tex-Lato-LightItalic-TS1-TOsF.tfm \
tex-Lato-LightItalic-TS1-TOsF.vf \
tex-Lato-LightItalic-X2-LF--base.tfm \
tex-Lato-LightItalic-X2-LF.tfm \
tex-Lato-LightItalic-X2-LF.vf \
tex-Lato-LightItalic-X2-OsF--base.tfm \
tex-Lato-LightItalic-X2-OsF.tfm \
tex-Lato-LightItalic-X2-OsF.vf \
tex-Lato-LightItalic-X2-TLF--base.tfm \
tex-Lato-LightItalic-X2-TLF.tfm \
tex-Lato-LightItalic-X2-TLF.vf \
tex-Lato-LightItalic-X2-TOsF--base.tfm \
tex-Lato-LightItalic-X2-TOsF.tfm \
tex-Lato-LightItalic-X2-TOsF.vf \
tex-Lato-Medium-LGR-LF--base.tfm \
tex-Lato-Medium-LGR-LF.tfm \
tex-Lato-Medium-LGR-LF.vf \
tex-Lato-Medium-LGR-OsF--base.tfm \
tex-Lato-Medium-LGR-OsF.tfm \
tex-Lato-Medium-LGR-OsF.vf \
tex-Lato-Medium-LGR-TLF--base.tfm \
tex-Lato-Medium-LGR-TLF.tfm \
tex-Lato-Medium-LGR-TLF.vf \
tex-Lato-Medium-LGR-TOsF--base.tfm \
tex-Lato-Medium-LGR-TOsF.tfm \
tex-Lato-Medium-LGR-TOsF.vf \
tex-Lato-Medium-OT1-LF--base.tfm \
tex-Lato-Medium-OT1-LF.tfm \
tex-Lato-Medium-OT1-LF.vf \
tex-Lato-Medium-OT1-OsF--base.tfm \
tex-Lato-Medium-OT1-OsF.tfm \
tex-Lato-Medium-OT1-OsF.vf \
tex-Lato-Medium-OT1-TLF--base.tfm \
tex-Lato-Medium-OT1-TLF.tfm \
tex-Lato-Medium-OT1-TLF.vf \
tex-Lato-Medium-OT1-TOsF--base.tfm \
tex-Lato-Medium-OT1-TOsF.tfm \
tex-Lato-Medium-OT1-TOsF.vf \
tex-Lato-Medium-T1-LF--base.tfm \
tex-Lato-Medium-T1-LF.tfm \
tex-Lato-Medium-T1-LF.vf \
tex-Lato-Medium-T1-OsF--base.tfm \
tex-Lato-Medium-T1-OsF.tfm \
tex-Lato-Medium-T1-OsF.vf \
tex-Lato-Medium-T1-TLF--base.tfm \
tex-Lato-Medium-T1-TLF.tfm \
tex-Lato-Medium-T1-TLF.vf \
tex-Lato-Medium-T1-TOsF--base.tfm \
tex-Lato-Medium-T1-TOsF.tfm \
tex-Lato-Medium-T1-TOsF.vf \
tex-Lato-Medium-T2A-LF--base.tfm \
tex-Lato-Medium-T2A-LF.tfm \
tex-Lato-Medium-T2A-LF.vf \
tex-Lato-Medium-T2A-OsF--base.tfm \
tex-Lato-Medium-T2A-OsF.tfm \
tex-Lato-Medium-T2A-OsF.vf \
tex-Lato-Medium-T2A-TLF--base.tfm \
tex-Lato-Medium-T2A-TLF.tfm \
tex-Lato-Medium-T2A-TLF.vf \
tex-Lato-Medium-T2A-TOsF--base.tfm \
tex-Lato-Medium-T2A-TOsF.tfm \
tex-Lato-Medium-T2A-TOsF.vf \
tex-Lato-Medium-T2B-LF--base.tfm \
tex-Lato-Medium-T2B-LF.tfm \
tex-Lato-Medium-T2B-LF.vf \
tex-Lato-Medium-T2B-OsF--base.tfm \
tex-Lato-Medium-T2B-OsF.tfm \
tex-Lato-Medium-T2B-OsF.vf \
tex-Lato-Medium-T2B-TLF--base.tfm \
tex-Lato-Medium-T2B-TLF.tfm \
tex-Lato-Medium-T2B-TLF.vf \
tex-Lato-Medium-T2B-TOsF--base.tfm \
tex-Lato-Medium-T2B-TOsF.tfm \
tex-Lato-Medium-T2B-TOsF.vf \
tex-Lato-Medium-T2C-LF--base.tfm \
tex-Lato-Medium-T2C-LF.tfm \
tex-Lato-Medium-T2C-LF.vf \
tex-Lato-Medium-T2C-OsF--base.tfm \
tex-Lato-Medium-T2C-OsF.tfm \
tex-Lato-Medium-T2C-OsF.vf \
tex-Lato-Medium-T2C-TLF--base.tfm \
tex-Lato-Medium-T2C-TLF.tfm \
tex-Lato-Medium-T2C-TLF.vf \
tex-Lato-Medium-T2C-TOsF--base.tfm \
tex-Lato-Medium-T2C-TOsF.tfm \
tex-Lato-Medium-T2C-TOsF.vf \
tex-Lato-Medium-TS1-LF--base.tfm \
tex-Lato-Medium-TS1-LF.tfm \
tex-Lato-Medium-TS1-LF.vf \
tex-Lato-Medium-TS1-OsF--base.tfm \
tex-Lato-Medium-TS1-OsF.tfm \
tex-Lato-Medium-TS1-OsF.vf \
tex-Lato-Medium-TS1-TLF--base.tfm \
tex-Lato-Medium-TS1-TLF.tfm \
tex-Lato-Medium-TS1-TLF.vf \
tex-Lato-Medium-TS1-TOsF--base.tfm \
tex-Lato-Medium-TS1-TOsF.tfm \
tex-Lato-Medium-TS1-TOsF.vf \
tex-Lato-Medium-X2-LF--base.tfm \
tex-Lato-Medium-X2-LF.tfm \
tex-Lato-Medium-X2-LF.vf \
tex-Lato-Medium-X2-OsF--base.tfm \
tex-Lato-Medium-X2-OsF.tfm \
tex-Lato-Medium-X2-OsF.vf \
tex-Lato-Medium-X2-TLF--base.tfm \
tex-Lato-Medium-X2-TLF.tfm \
tex-Lato-Medium-X2-TLF.vf \
tex-Lato-Medium-X2-TOsF--base.tfm \
tex-Lato-Medium-X2-TOsF.tfm \
tex-Lato-Medium-X2-TOsF.vf \
tex-Lato-MediumItalic-LGR-LF--base.tfm \
tex-Lato-MediumItalic-LGR-LF.tfm \
tex-Lato-MediumItalic-LGR-LF.vf \
tex-Lato-MediumItalic-LGR-OsF--base.tfm \
tex-Lato-MediumItalic-LGR-OsF.tfm \
tex-Lato-MediumItalic-LGR-OsF.vf \
tex-Lato-MediumItalic-LGR-TLF--base.tfm \
tex-Lato-MediumItalic-LGR-TLF.tfm \
tex-Lato-MediumItalic-LGR-TLF.vf \
tex-Lato-MediumItalic-LGR-TOsF--base.tfm \
tex-Lato-MediumItalic-LGR-TOsF.tfm \
tex-Lato-MediumItalic-LGR-TOsF.vf \
tex-Lato-MediumItalic-OT1-LF--base.tfm \
tex-Lato-MediumItalic-OT1-LF.tfm \
tex-Lato-MediumItalic-OT1-LF.vf \
tex-Lato-MediumItalic-OT1-OsF--base.tfm \
tex-Lato-MediumItalic-OT1-OsF.tfm \
tex-Lato-MediumItalic-OT1-OsF.vf \
tex-Lato-MediumItalic-OT1-TLF--base.tfm \
tex-Lato-MediumItalic-OT1-TLF.tfm \
tex-Lato-MediumItalic-OT1-TLF.vf \
tex-Lato-MediumItalic-OT1-TOsF--base.tfm \
tex-Lato-MediumItalic-OT1-TOsF.tfm \
tex-Lato-MediumItalic-OT1-TOsF.vf \
tex-Lato-MediumItalic-T1-LF--base.tfm \
tex-Lato-MediumItalic-T1-LF.tfm \
tex-Lato-MediumItalic-T1-LF.vf \
tex-Lato-MediumItalic-T1-OsF--base.tfm \
tex-Lato-MediumItalic-T1-OsF.tfm \
tex-Lato-MediumItalic-T1-OsF.vf \
tex-Lato-MediumItalic-T1-TLF--base.tfm \
tex-Lato-MediumItalic-T1-TLF.tfm \
tex-Lato-MediumItalic-T1-TLF.vf \
tex-Lato-MediumItalic-T1-TOsF--base.tfm \
tex-Lato-MediumItalic-T1-TOsF.tfm \
tex-Lato-MediumItalic-T1-TOsF.vf \
tex-Lato-MediumItalic-T2A-LF--base.tfm \
tex-Lato-MediumItalic-T2A-LF.tfm \
tex-Lato-MediumItalic-T2A-LF.vf \
tex-Lato-MediumItalic-T2A-OsF--base.tfm \
tex-Lato-MediumItalic-T2A-OsF.tfm \
tex-Lato-MediumItalic-T2A-OsF.vf \
tex-Lato-MediumItalic-T2A-TLF--base.tfm \
tex-Lato-MediumItalic-T2A-TLF.tfm \
tex-Lato-MediumItalic-T2A-TLF.vf \
tex-Lato-MediumItalic-T2A-TOsF--base.tfm \
tex-Lato-MediumItalic-T2A-TOsF.tfm \
tex-Lato-MediumItalic-T2A-TOsF.vf \
tex-Lato-MediumItalic-T2B-LF--base.tfm \
tex-Lato-MediumItalic-T2B-LF.tfm \
tex-Lato-MediumItalic-T2B-LF.vf \
tex-Lato-MediumItalic-T2B-OsF--base.tfm \
tex-Lato-MediumItalic-T2B-OsF.tfm \
tex-Lato-MediumItalic-T2B-OsF.vf \
tex-Lato-MediumItalic-T2B-TLF--base.tfm \
tex-Lato-MediumItalic-T2B-TLF.tfm \
tex-Lato-MediumItalic-T2B-TLF.vf \
tex-Lato-MediumItalic-T2B-TOsF--base.tfm \
tex-Lato-MediumItalic-T2B-TOsF.tfm \
tex-Lato-MediumItalic-T2B-TOsF.vf \
tex-Lato-MediumItalic-T2C-LF--base.tfm \
tex-Lato-MediumItalic-T2C-LF.tfm \
tex-Lato-MediumItalic-T2C-LF.vf \
tex-Lato-MediumItalic-T2C-OsF--base.tfm \
tex-Lato-MediumItalic-T2C-OsF.tfm \
tex-Lato-MediumItalic-T2C-OsF.vf \
tex-Lato-MediumItalic-T2C-TLF--base.tfm \
tex-Lato-MediumItalic-T2C-TLF.tfm \
tex-Lato-MediumItalic-T2C-TLF.vf \
tex-Lato-MediumItalic-T2C-TOsF--base.tfm \
tex-Lato-MediumItalic-T2C-TOsF.tfm \
tex-Lato-MediumItalic-T2C-TOsF.vf \
tex-Lato-MediumItalic-TS1-LF--base.tfm \
tex-Lato-MediumItalic-TS1-LF.tfm \
tex-Lato-MediumItalic-TS1-LF.vf \
tex-Lato-MediumItalic-TS1-OsF--base.tfm \
tex-Lato-MediumItalic-TS1-OsF.tfm \
tex-Lato-MediumItalic-TS1-OsF.vf \
tex-Lato-MediumItalic-TS1-TLF--base.tfm \
tex-Lato-MediumItalic-TS1-TLF.tfm \
tex-Lato-MediumItalic-TS1-TLF.vf \
tex-Lato-MediumItalic-TS1-TOsF--base.tfm \
tex-Lato-MediumItalic-TS1-TOsF.tfm \
tex-Lato-MediumItalic-TS1-TOsF.vf \
tex-Lato-MediumItalic-X2-LF--base.tfm \
tex-Lato-MediumItalic-X2-LF.tfm \
tex-Lato-MediumItalic-X2-LF.vf \
tex-Lato-MediumItalic-X2-OsF--base.tfm \
tex-Lato-MediumItalic-X2-OsF.tfm \
tex-Lato-MediumItalic-X2-OsF.vf \
tex-Lato-MediumItalic-X2-TLF--base.tfm \
tex-Lato-MediumItalic-X2-TLF.tfm \
tex-Lato-MediumItalic-X2-TLF.vf \
tex-Lato-MediumItalic-X2-TOsF--base.tfm \
tex-Lato-MediumItalic-X2-TOsF.tfm \
tex-Lato-MediumItalic-X2-TOsF.vf \
tex-Lato-Regular-LGR-LF--base.tfm \
tex-Lato-Regular-LGR-LF.tfm \
tex-Lato-Regular-LGR-LF.vf \
tex-Lato-Regular-LGR-OsF--base.tfm \
tex-Lato-Regular-LGR-OsF.tfm \
tex-Lato-Regular-LGR-OsF.vf \
tex-Lato-Regular-LGR-TLF--base.tfm \
tex-Lato-Regular-LGR-TLF.tfm \
tex-Lato-Regular-LGR-TLF.vf \
tex-Lato-Regular-LGR-TOsF--base.tfm \
tex-Lato-Regular-LGR-TOsF.tfm \
tex-Lato-Regular-LGR-TOsF.vf \
tex-Lato-Regular-OT1-LF--base.tfm \
tex-Lato-Regular-OT1-LF.tfm \
tex-Lato-Regular-OT1-LF.vf \
tex-Lato-Regular-OT1-OsF--base.tfm \
tex-Lato-Regular-OT1-OsF.tfm \
tex-Lato-Regular-OT1-OsF.vf \
tex-Lato-Regular-OT1-TLF--base.tfm \
tex-Lato-Regular-OT1-TLF.tfm \
tex-Lato-Regular-OT1-TLF.vf \
tex-Lato-Regular-OT1-TOsF--base.tfm \
tex-Lato-Regular-OT1-TOsF.tfm \
tex-Lato-Regular-OT1-TOsF.vf \
tex-Lato-Regular-T1-LF--base.tfm \
tex-Lato-Regular-T1-LF.tfm \
tex-Lato-Regular-T1-LF.vf \
tex-Lato-Regular-T1-OsF--base.tfm \
tex-Lato-Regular-T1-OsF.tfm \
tex-Lato-Regular-T1-OsF.vf \
tex-Lato-Regular-T1-TLF--base.tfm \
tex-Lato-Regular-T1-TLF.tfm \
tex-Lato-Regular-T1-TLF.vf \
tex-Lato-Regular-T1-TOsF--base.tfm \
tex-Lato-Regular-T1-TOsF.tfm \
tex-Lato-Regular-T1-TOsF.vf \
tex-Lato-Regular-T2A-LF--base.tfm \
tex-Lato-Regular-T2A-LF.tfm \
tex-Lato-Regular-T2A-LF.vf \
tex-Lato-Regular-T2A-OsF--base.tfm \
tex-Lato-Regular-T2A-OsF.tfm \
tex-Lato-Regular-T2A-OsF.vf \
tex-Lato-Regular-T2A-TLF--base.tfm \
tex-Lato-Regular-T2A-TLF.tfm \
tex-Lato-Regular-T2A-TLF.vf \
tex-Lato-Regular-T2A-TOsF--base.tfm \
tex-Lato-Regular-T2A-TOsF.tfm \
tex-Lato-Regular-T2A-TOsF.vf \
tex-Lato-Regular-T2B-LF--base.tfm \
tex-Lato-Regular-T2B-LF.tfm \
tex-Lato-Regular-T2B-LF.vf \
tex-Lato-Regular-T2B-OsF--base.tfm \
tex-Lato-Regular-T2B-OsF.tfm \
tex-Lato-Regular-T2B-OsF.vf \
tex-Lato-Regular-T2B-TLF--base.tfm \
tex-Lato-Regular-T2B-TLF.tfm \
tex-Lato-Regular-T2B-TLF.vf \
tex-Lato-Regular-T2B-TOsF--base.tfm \
tex-Lato-Regular-T2B-TOsF.tfm \
tex-Lato-Regular-T2B-TOsF.vf \
tex-Lato-Regular-T2C-LF--base.tfm \
tex-Lato-Regular-T2C-LF.tfm \
tex-Lato-Regular-T2C-LF.vf \
tex-Lato-Regular-T2C-OsF--base.tfm \
tex-Lato-Regular-T2C-OsF.tfm \
tex-Lato-Regular-T2C-OsF.vf \
tex-Lato-Regular-T2C-TLF--base.tfm \
tex-Lato-Regular-T2C-TLF.tfm \
tex-Lato-Regular-T2C-TLF.vf \
tex-Lato-Regular-T2C-TOsF--base.tfm \
tex-Lato-Regular-T2C-TOsF.tfm \
tex-Lato-Regular-T2C-TOsF.vf \
tex-Lato-Regular-TS1-LF--base.tfm \
tex-Lato-Regular-TS1-LF.tfm \
tex-Lato-Regular-TS1-LF.vf \
tex-Lato-Regular-TS1-OsF--base.tfm \
tex-Lato-Regular-TS1-OsF.tfm \
tex-Lato-Regular-TS1-OsF.vf \
tex-Lato-Regular-TS1-TLF--base.tfm \
tex-Lato-Regular-TS1-TLF.tfm \
tex-Lato-Regular-TS1-TLF.vf \
tex-Lato-Regular-TS1-TOsF--base.tfm \
tex-Lato-Regular-TS1-TOsF.tfm \
tex-Lato-Regular-TS1-TOsF.vf \
tex-Lato-Regular-X2-LF--base.tfm \
tex-Lato-Regular-X2-LF.tfm \
tex-Lato-Regular-X2-LF.vf \
tex-Lato-Regular-X2-OsF--base.tfm \
tex-Lato-Regular-X2-OsF.tfm \
tex-Lato-Regular-X2-OsF.vf \
tex-Lato-Regular-X2-TLF--base.tfm \
tex-Lato-Regular-X2-TLF.tfm \
tex-Lato-Regular-X2-TLF.vf \
tex-Lato-Regular-X2-TOsF--base.tfm \
tex-Lato-Regular-X2-TOsF.tfm \
tex-Lato-Regular-X2-TOsF.vf \
tex-Lato-Semibold-LGR-LF--base.tfm \
tex-Lato-Semibold-LGR-LF.tfm \
tex-Lato-Semibold-LGR-LF.vf \
tex-Lato-Semibold-LGR-OsF--base.tfm \
tex-Lato-Semibold-LGR-OsF.tfm \
tex-Lato-Semibold-LGR-OsF.vf \
tex-Lato-Semibold-LGR-TLF--base.tfm \
tex-Lato-Semibold-LGR-TLF.tfm \
tex-Lato-Semibold-LGR-TLF.vf \
tex-Lato-Semibold-LGR-TOsF--base.tfm \
tex-Lato-Semibold-LGR-TOsF.tfm \
tex-Lato-Semibold-LGR-TOsF.vf \
tex-Lato-Semibold-OT1-LF--base.tfm \
tex-Lato-Semibold-OT1-LF.tfm \
tex-Lato-Semibold-OT1-LF.vf \
tex-Lato-Semibold-OT1-OsF--base.tfm \
tex-Lato-Semibold-OT1-OsF.tfm \
tex-Lato-Semibold-OT1-OsF.vf \
tex-Lato-Semibold-OT1-TLF--base.tfm \
tex-Lato-Semibold-OT1-TLF.tfm \
tex-Lato-Semibold-OT1-TLF.vf \
tex-Lato-Semibold-OT1-TOsF--base.tfm \
tex-Lato-Semibold-OT1-TOsF.tfm \
tex-Lato-Semibold-OT1-TOsF.vf \
tex-Lato-Semibold-T1-LF--base.tfm \
tex-Lato-Semibold-T1-LF.tfm \
tex-Lato-Semibold-T1-LF.vf \
tex-Lato-Semibold-T1-OsF--base.tfm \
tex-Lato-Semibold-T1-OsF.tfm \
tex-Lato-Semibold-T1-OsF.vf \
tex-Lato-Semibold-T1-TLF--base.tfm \
tex-Lato-Semibold-T1-TLF.tfm \
tex-Lato-Semibold-T1-TLF.vf \
tex-Lato-Semibold-T1-TOsF--base.tfm \
tex-Lato-Semibold-T1-TOsF.tfm \
tex-Lato-Semibold-T1-TOsF.vf \
tex-Lato-Semibold-T2A-LF--base.tfm \
tex-Lato-Semibold-T2A-LF.tfm \
tex-Lato-Semibold-T2A-LF.vf \
tex-Lato-Semibold-T2A-OsF--base.tfm \
tex-Lato-Semibold-T2A-OsF.tfm \
tex-Lato-Semibold-T2A-OsF.vf \
tex-Lato-Semibold-T2A-TLF--base.tfm \
tex-Lato-Semibold-T2A-TLF.tfm \
tex-Lato-Semibold-T2A-TLF.vf \
tex-Lato-Semibold-T2A-TOsF--base.tfm \
tex-Lato-Semibold-T2A-TOsF.tfm \
tex-Lato-Semibold-T2A-TOsF.vf \
tex-Lato-Semibold-T2B-LF--base.tfm \
tex-Lato-Semibold-T2B-LF.tfm \
tex-Lato-Semibold-T2B-LF.vf \
tex-Lato-Semibold-T2B-OsF--base.tfm \
tex-Lato-Semibold-T2B-OsF.tfm \
tex-Lato-Semibold-T2B-OsF.vf \
tex-Lato-Semibold-T2B-TLF--base.tfm \
tex-Lato-Semibold-T2B-TLF.tfm \
tex-Lato-Semibold-T2B-TLF.vf \
tex-Lato-Semibold-T2B-TOsF--base.tfm \
tex-Lato-Semibold-T2B-TOsF.tfm \
tex-Lato-Semibold-T2B-TOsF.vf \
tex-Lato-Semibold-T2C-LF--base.tfm \
tex-Lato-Semibold-T2C-LF.tfm \
tex-Lato-Semibold-T2C-LF.vf \
tex-Lato-Semibold-T2C-OsF--base.tfm \
tex-Lato-Semibold-T2C-OsF.tfm \
tex-Lato-Semibold-T2C-OsF.vf \
tex-Lato-Semibold-T2C-TLF--base.tfm \
tex-Lato-Semibold-T2C-TLF.tfm \
tex-Lato-Semibold-T2C-TLF.vf \
tex-Lato-Semibold-T2C-TOsF--base.tfm \
tex-Lato-Semibold-T2C-TOsF.tfm \
tex-Lato-Semibold-T2C-TOsF.vf \
tex-Lato-Semibold-TS1-LF--base.tfm \
tex-Lato-Semibold-TS1-LF.tfm \
tex-Lato-Semibold-TS1-LF.vf \
tex-Lato-Semibold-TS1-OsF--base.tfm \
tex-Lato-Semibold-TS1-OsF.tfm \
tex-Lato-Semibold-TS1-OsF.vf \
tex-Lato-Semibold-TS1-TLF--base.tfm \
tex-Lato-Semibold-TS1-TLF.tfm \
tex-Lato-Semibold-TS1-TLF.vf \
tex-Lato-Semibold-TS1-TOsF--base.tfm \
tex-Lato-Semibold-TS1-TOsF.tfm \
tex-Lato-Semibold-TS1-TOsF.vf \
tex-Lato-Semibold-X2-LF--base.tfm \
tex-Lato-Semibold-X2-LF.tfm \
tex-Lato-Semibold-X2-LF.vf \
tex-Lato-Semibold-X2-OsF--base.tfm \
tex-Lato-Semibold-X2-OsF.tfm \
tex-Lato-Semibold-X2-OsF.vf \
tex-Lato-Semibold-X2-TLF--base.tfm \
tex-Lato-Semibold-X2-TLF.tfm \
tex-Lato-Semibold-X2-TLF.vf \
tex-Lato-Semibold-X2-TOsF--base.tfm \
tex-Lato-Semibold-X2-TOsF.tfm \
tex-Lato-Semibold-X2-TOsF.vf \
tex-Lato-SemiboldItalic-LGR-LF--base.tfm \
tex-Lato-SemiboldItalic-LGR-LF.tfm \
tex-Lato-SemiboldItalic-LGR-LF.vf \
tex-Lato-SemiboldItalic-LGR-OsF--base.tfm \
tex-Lato-SemiboldItalic-LGR-OsF.tfm \
tex-Lato-SemiboldItalic-LGR-OsF.vf \
tex-Lato-SemiboldItalic-LGR-TLF--base.tfm \
tex-Lato-SemiboldItalic-LGR-TLF.tfm \
tex-Lato-SemiboldItalic-LGR-TLF.vf \
tex-Lato-SemiboldItalic-LGR-TOsF--base.tfm \
tex-Lato-SemiboldItalic-LGR-TOsF.tfm \
tex-Lato-SemiboldItalic-LGR-TOsF.vf \
tex-Lato-SemiboldItalic-OT1-LF--base.tfm \
tex-Lato-SemiboldItalic-OT1-LF.tfm \
tex-Lato-SemiboldItalic-OT1-LF.vf \
tex-Lato-SemiboldItalic-OT1-OsF--base.tfm \
tex-Lato-SemiboldItalic-OT1-OsF.tfm \
tex-Lato-SemiboldItalic-OT1-OsF.vf \
tex-Lato-SemiboldItalic-OT1-TLF--base.tfm \
tex-Lato-SemiboldItalic-OT1-TLF.tfm \
tex-Lato-SemiboldItalic-OT1-TLF.vf \
tex-Lato-SemiboldItalic-OT1-TOsF--base.tfm \
tex-Lato-SemiboldItalic-OT1-TOsF.tfm \
tex-Lato-SemiboldItalic-OT1-TOsF.vf \
tex-Lato-SemiboldItalic-T1-LF--base.tfm \
tex-Lato-SemiboldItalic-T1-LF.tfm \
tex-Lato-SemiboldItalic-T1-LF.vf \
tex-Lato-SemiboldItalic-T1-OsF--base.tfm \
tex-Lato-SemiboldItalic-T1-OsF.tfm \
tex-Lato-SemiboldItalic-T1-OsF.vf \
tex-Lato-SemiboldItalic-T1-TLF--base.tfm \
tex-Lato-SemiboldItalic-T1-TLF.tfm \
tex-Lato-SemiboldItalic-T1-TLF.vf \
tex-Lato-SemiboldItalic-T1-TOsF--base.tfm \
tex-Lato-SemiboldItalic-T1-TOsF.tfm \
tex-Lato-SemiboldItalic-T1-TOsF.vf \
tex-Lato-SemiboldItalic-T2A-LF--base.tfm \
tex-Lato-SemiboldItalic-T2A-LF.tfm \
tex-Lato-SemiboldItalic-T2A-LF.vf \
tex-Lato-SemiboldItalic-T2A-OsF--base.tfm \
tex-Lato-SemiboldItalic-T2A-OsF.tfm \
tex-Lato-SemiboldItalic-T2A-OsF.vf \
tex-Lato-SemiboldItalic-T2A-TLF--base.tfm \
tex-Lato-SemiboldItalic-T2A-TLF.tfm \
tex-Lato-SemiboldItalic-T2A-TLF.vf \
tex-Lato-SemiboldItalic-T2A-TOsF--base.tfm \
tex-Lato-SemiboldItalic-T2A-TOsF.tfm \
tex-Lato-SemiboldItalic-T2A-TOsF.vf \
tex-Lato-SemiboldItalic-T2B-LF--base.tfm \
tex-Lato-SemiboldItalic-T2B-LF.tfm \
tex-Lato-SemiboldItalic-T2B-LF.vf \
tex-Lato-SemiboldItalic-T2B-OsF--base.tfm \
tex-Lato-SemiboldItalic-T2B-OsF.tfm \
tex-Lato-SemiboldItalic-T2B-OsF.vf \
tex-Lato-SemiboldItalic-T2B-TLF--base.tfm \
tex-Lato-SemiboldItalic-T2B-TLF.tfm \
tex-Lato-SemiboldItalic-T2B-TLF.vf \
tex-Lato-SemiboldItalic-T2B-TOsF--base.tfm \
tex-Lato-SemiboldItalic-T2B-TOsF.tfm \
tex-Lato-SemiboldItalic-T2B-TOsF.vf \
tex-Lato-SemiboldItalic-T2C-LF--base.tfm \
tex-Lato-SemiboldItalic-T2C-LF.tfm \
tex-Lato-SemiboldItalic-T2C-LF.vf \
tex-Lato-SemiboldItalic-T2C-OsF--base.tfm \
tex-Lato-SemiboldItalic-T2C-OsF.tfm \
tex-Lato-SemiboldItalic-T2C-OsF.vf \
tex-Lato-SemiboldItalic-T2C-TLF--base.tfm \
tex-Lato-SemiboldItalic-T2C-TLF.tfm \
tex-Lato-SemiboldItalic-T2C-TLF.vf \
tex-Lato-SemiboldItalic-T2C-TOsF--base.tfm \
tex-Lato-SemiboldItalic-T2C-TOsF.tfm \
tex-Lato-SemiboldItalic-T2C-TOsF.vf \
tex-Lato-SemiboldItalic-TS1-LF--base.tfm \
tex-Lato-SemiboldItalic-TS1-LF.tfm \
tex-Lato-SemiboldItalic-TS1-LF.vf \
tex-Lato-SemiboldItalic-TS1-OsF--base.tfm \
tex-Lato-SemiboldItalic-TS1-OsF.tfm \
tex-Lato-SemiboldItalic-TS1-OsF.vf \
tex-Lato-SemiboldItalic-TS1-TLF--base.tfm \
tex-Lato-SemiboldItalic-TS1-TLF.tfm \
tex-Lato-SemiboldItalic-TS1-TLF.vf \
tex-Lato-SemiboldItalic-TS1-TOsF--base.tfm \
tex-Lato-SemiboldItalic-TS1-TOsF.tfm \
tex-Lato-SemiboldItalic-TS1-TOsF.vf \
tex-Lato-SemiboldItalic-X2-LF--base.tfm \
tex-Lato-SemiboldItalic-X2-LF.tfm \
tex-Lato-SemiboldItalic-X2-LF.vf \
tex-Lato-SemiboldItalic-X2-OsF--base.tfm \
tex-Lato-SemiboldItalic-X2-OsF.tfm \
tex-Lato-SemiboldItalic-X2-OsF.vf \
tex-Lato-SemiboldItalic-X2-TLF--base.tfm \
tex-Lato-SemiboldItalic-X2-TLF.tfm \
tex-Lato-SemiboldItalic-X2-TLF.vf \
tex-Lato-SemiboldItalic-X2-TOsF--base.tfm \
tex-Lato-SemiboldItalic-X2-TOsF.tfm \
tex-Lato-SemiboldItalic-X2-TOsF.vf \
tex-Lato-Thin-LGR-LF--base.tfm \
tex-Lato-Thin-LGR-LF.tfm \
tex-Lato-Thin-LGR-LF.vf \
tex-Lato-Thin-LGR-OsF--base.tfm \
tex-Lato-Thin-LGR-OsF.tfm \
tex-Lato-Thin-LGR-OsF.vf \
tex-Lato-Thin-LGR-TLF--base.tfm \
tex-Lato-Thin-LGR-TLF.tfm \
tex-Lato-Thin-LGR-TLF.vf \
tex-Lato-Thin-LGR-TOsF--base.tfm \
tex-Lato-Thin-LGR-TOsF.tfm \
tex-Lato-Thin-LGR-TOsF.vf \
tex-Lato-Thin-OT1-LF--base.tfm \
tex-Lato-Thin-OT1-LF.tfm \
tex-Lato-Thin-OT1-LF.vf \
tex-Lato-Thin-OT1-OsF--base.tfm \
tex-Lato-Thin-OT1-OsF.tfm \
tex-Lato-Thin-OT1-OsF.vf \
tex-Lato-Thin-OT1-TLF--base.tfm \
tex-Lato-Thin-OT1-TLF.tfm \
tex-Lato-Thin-OT1-TLF.vf \
tex-Lato-Thin-OT1-TOsF--base.tfm \
tex-Lato-Thin-OT1-TOsF.tfm \
tex-Lato-Thin-OT1-TOsF.vf \
tex-Lato-Thin-T1-LF--base.tfm \
tex-Lato-Thin-T1-LF.tfm \
tex-Lato-Thin-T1-LF.vf \
tex-Lato-Thin-T1-OsF--base.tfm \
tex-Lato-Thin-T1-OsF.tfm \
tex-Lato-Thin-T1-OsF.vf \
tex-Lato-Thin-T1-TLF--base.tfm \
tex-Lato-Thin-T1-TLF.tfm \
tex-Lato-Thin-T1-TLF.vf \
tex-Lato-Thin-T1-TOsF--base.tfm \
tex-Lato-Thin-T1-TOsF.tfm \
tex-Lato-Thin-T1-TOsF.vf \
tex-Lato-Thin-T2A-LF--base.tfm \
tex-Lato-Thin-T2A-LF.tfm \
tex-Lato-Thin-T2A-LF.vf \
tex-Lato-Thin-T2A-OsF--base.tfm \
tex-Lato-Thin-T2A-OsF.tfm \
tex-Lato-Thin-T2A-OsF.vf \
tex-Lato-Thin-T2A-TLF--base.tfm \
tex-Lato-Thin-T2A-TLF.tfm \
tex-Lato-Thin-T2A-TLF.vf \
tex-Lato-Thin-T2A-TOsF--base.tfm \
tex-Lato-Thin-T2A-TOsF.tfm \
tex-Lato-Thin-T2A-TOsF.vf \
tex-Lato-Thin-T2B-LF--base.tfm \
tex-Lato-Thin-T2B-LF.tfm \
tex-Lato-Thin-T2B-LF.vf \
tex-Lato-Thin-T2B-OsF--base.tfm \
tex-Lato-Thin-T2B-OsF.tfm \
tex-Lato-Thin-T2B-OsF.vf \
tex-Lato-Thin-T2B-TLF--base.tfm \
tex-Lato-Thin-T2B-TLF.tfm \
tex-Lato-Thin-T2B-TLF.vf \
tex-Lato-Thin-T2B-TOsF--base.tfm \
tex-Lato-Thin-T2B-TOsF.tfm \
tex-Lato-Thin-T2B-TOsF.vf \
tex-Lato-Thin-T2C-LF--base.tfm \
tex-Lato-Thin-T2C-LF.tfm \
tex-Lato-Thin-T2C-LF.vf \
tex-Lato-Thin-T2C-OsF--base.tfm \
tex-Lato-Thin-T2C-OsF.tfm \
tex-Lato-Thin-T2C-OsF.vf \
tex-Lato-Thin-T2C-TLF--base.tfm \
tex-Lato-Thin-T2C-TLF.tfm \
tex-Lato-Thin-T2C-TLF.vf \
tex-Lato-Thin-T2C-TOsF--base.tfm \
tex-Lato-Thin-T2C-TOsF.tfm \
tex-Lato-Thin-T2C-TOsF.vf \
tex-Lato-Thin-TS1-LF--base.tfm \
tex-Lato-Thin-TS1-LF.tfm \
tex-Lato-Thin-TS1-LF.vf \
tex-Lato-Thin-TS1-OsF--base.tfm \
tex-Lato-Thin-TS1-OsF.tfm \
tex-Lato-Thin-TS1-OsF.vf \
tex-Lato-Thin-TS1-TLF--base.tfm \
tex-Lato-Thin-TS1-TLF.tfm \
tex-Lato-Thin-TS1-TLF.vf \
tex-Lato-Thin-TS1-TOsF--base.tfm \
tex-Lato-Thin-TS1-TOsF.tfm \
tex-Lato-Thin-TS1-TOsF.vf \
tex-Lato-Thin-X2-LF--base.tfm \
tex-Lato-Thin-X2-LF.tfm \
tex-Lato-Thin-X2-LF.vf \
tex-Lato-Thin-X2-OsF--base.tfm \
tex-Lato-Thin-X2-OsF.tfm \
tex-Lato-Thin-X2-OsF.vf \
tex-Lato-Thin-X2-TLF--base.tfm \
tex-Lato-Thin-X2-TLF.tfm \
tex-Lato-Thin-X2-TLF.vf \
tex-Lato-Thin-X2-TOsF--base.tfm \
tex-Lato-Thin-X2-TOsF.tfm \
tex-Lato-Thin-X2-TOsF.vf \
tex-Lato-ThinItalic-LGR-LF--base.tfm \
tex-Lato-ThinItalic-LGR-LF.tfm \
tex-Lato-ThinItalic-LGR-LF.vf \
tex-Lato-ThinItalic-LGR-OsF--base.tfm \
tex-Lato-ThinItalic-LGR-OsF.tfm \
tex-Lato-ThinItalic-LGR-OsF.vf \
tex-Lato-ThinItalic-LGR-TLF--base.tfm \
tex-Lato-ThinItalic-LGR-TLF.tfm \
tex-Lato-ThinItalic-LGR-TLF.vf \
tex-Lato-ThinItalic-LGR-TOsF--base.tfm \
tex-Lato-ThinItalic-LGR-TOsF.tfm \
tex-Lato-ThinItalic-LGR-TOsF.vf \
tex-Lato-ThinItalic-OT1-LF--base.tfm \
tex-Lato-ThinItalic-OT1-LF.tfm \
tex-Lato-ThinItalic-OT1-LF.vf \
tex-Lato-ThinItalic-OT1-OsF--base.tfm \
tex-Lato-ThinItalic-OT1-OsF.tfm \
tex-Lato-ThinItalic-OT1-OsF.vf \
tex-Lato-ThinItalic-OT1-TLF--base.tfm \
tex-Lato-ThinItalic-OT1-TLF.tfm \
tex-Lato-ThinItalic-OT1-TLF.vf \
tex-Lato-ThinItalic-OT1-TOsF--base.tfm \
tex-Lato-ThinItalic-OT1-TOsF.tfm \
tex-Lato-ThinItalic-OT1-TOsF.vf \
tex-Lato-ThinItalic-T1-LF--base.tfm \
tex-Lato-ThinItalic-T1-LF.tfm \
tex-Lato-ThinItalic-T1-LF.vf \
tex-Lato-ThinItalic-T1-OsF--base.tfm \
tex-Lato-ThinItalic-T1-OsF.tfm \
tex-Lato-ThinItalic-T1-OsF.vf \
tex-Lato-ThinItalic-T1-TLF--base.tfm \
tex-Lato-ThinItalic-T1-TLF.tfm \
tex-Lato-ThinItalic-T1-TLF.vf \
tex-Lato-ThinItalic-T1-TOsF--base.tfm \
tex-Lato-ThinItalic-T1-TOsF.tfm \
tex-Lato-ThinItalic-T1-TOsF.vf \
tex-Lato-ThinItalic-T2A-LF--base.tfm \
tex-Lato-ThinItalic-T2A-LF.tfm \
tex-Lato-ThinItalic-T2A-LF.vf \
tex-Lato-ThinItalic-T2A-OsF--base.tfm \
tex-Lato-ThinItalic-T2A-OsF.tfm \
tex-Lato-ThinItalic-T2A-OsF.vf \
tex-Lato-ThinItalic-T2A-TLF--base.tfm \
tex-Lato-ThinItalic-T2A-TLF.tfm \
tex-Lato-ThinItalic-T2A-TLF.vf \
tex-Lato-ThinItalic-T2A-TOsF--base.tfm \
tex-Lato-ThinItalic-T2A-TOsF.tfm \
tex-Lato-ThinItalic-T2A-TOsF.vf \
tex-Lato-ThinItalic-T2B-LF--base.tfm \
tex-Lato-ThinItalic-T2B-LF.tfm \
tex-Lato-ThinItalic-T2B-LF.vf \
tex-Lato-ThinItalic-T2B-OsF--base.tfm \
tex-Lato-ThinItalic-T2B-OsF.tfm \
tex-Lato-ThinItalic-T2B-OsF.vf \
tex-Lato-ThinItalic-T2B-TLF--base.tfm \
tex-Lato-ThinItalic-T2B-TLF.tfm \
tex-Lato-ThinItalic-T2B-TLF.vf \
tex-Lato-ThinItalic-T2B-TOsF--base.tfm \
tex-Lato-ThinItalic-T2B-TOsF.tfm \
tex-Lato-ThinItalic-T2B-TOsF.vf \
tex-Lato-ThinItalic-T2C-LF--base.tfm \
tex-Lato-ThinItalic-T2C-LF.tfm \
tex-Lato-ThinItalic-T2C-LF.vf \
tex-Lato-ThinItalic-T2C-OsF--base.tfm \
tex-Lato-ThinItalic-T2C-OsF.tfm \
tex-Lato-ThinItalic-T2C-OsF.vf \
tex-Lato-ThinItalic-T2C-TLF--base.tfm \
tex-Lato-ThinItalic-T2C-TLF.tfm \
tex-Lato-ThinItalic-T2C-TLF.vf \
tex-Lato-ThinItalic-T2C-TOsF--base.tfm \
tex-Lato-ThinItalic-T2C-TOsF.tfm \
tex-Lato-ThinItalic-T2C-TOsF.vf \
tex-Lato-ThinItalic-TS1-LF--base.tfm \
tex-Lato-ThinItalic-TS1-LF.tfm \
tex-Lato-ThinItalic-TS1-LF.vf \
tex-Lato-ThinItalic-TS1-OsF--base.tfm \
tex-Lato-ThinItalic-TS1-OsF.tfm \
tex-Lato-ThinItalic-TS1-OsF.vf \
tex-Lato-ThinItalic-TS1-TLF--base.tfm \
tex-Lato-ThinItalic-TS1-TLF.tfm \
tex-Lato-ThinItalic-TS1-TLF.vf \
tex-Lato-ThinItalic-TS1-TOsF--base.tfm \
tex-Lato-ThinItalic-TS1-TOsF.tfm \
tex-Lato-ThinItalic-TS1-TOsF.vf \
tex-Lato-ThinItalic-X2-LF--base.tfm \
tex-Lato-ThinItalic-X2-LF.tfm \
tex-Lato-ThinItalic-X2-LF.vf \
tex-Lato-ThinItalic-X2-OsF--base.tfm \
tex-Lato-ThinItalic-X2-OsF.tfm \
tex-Lato-ThinItalic-X2-OsF.vf \
tex-Lato-ThinItalic-X2-TLF--base.tfm \
tex-Lato-ThinItalic-X2-TLF.tfm \
tex-Lato-ThinItalic-X2-TLF.vf \
tex-Lato-ThinItalic-X2-TOsF--base.tfm \
tex-Lato-ThinItalic-X2-TOsF.tfm \
tex-Lato-ThinItalic-X2-TOsF.vf \
tex-OT1lato-LF.fd \
tex-OT1lato-OsF.fd \
tex-OT1lato-TLF.fd \
tex-OT1lato-TOsF.fd \
tex-T1lato-LF.fd \
tex-T1lato-OsF.fd \
tex-T1lato-TLF.fd \
tex-T1lato-TOsF.fd \
tex-T2Alato-LF.fd \
tex-T2Alato-OsF.fd \
tex-T2Alato-TLF.fd \
tex-T2Alato-TOsF.fd \
tex-T2Blato-LF.fd \
tex-T2Blato-OsF.fd \
tex-T2Blato-TLF.fd \
tex-T2Blato-TOsF.fd \
tex-T2Clato-LF.fd \
tex-T2Clato-OsF.fd \
tex-T2Clato-TLF.fd \
tex-T2Clato-TOsF.fd \
tex-TS1lato-LF.fd \
tex-TS1lato-OsF.fd \
tex-TS1lato-TLF.fd \
tex-TS1lato-TOsF.fd \
tex-X2lato-LF.fd \
tex-X2lato-OsF.fd \
tex-X2lato-TLF.fd \
tex-X2lato-TOsF.fd \
tex-a-25nmxu.enc \
tex-a-3qgqav.enc \
tex-a-4vt5lz.enc \
tex-a-5qkav4.enc \
tex-a-6aejyg.enc \
tex-a-6rhh47.enc \
tex-a-cje5wf.enc \
tex-a-cl4kdn.enc \
tex-a-dakysd.enc \
tex-a-eu4zf2.enc \
tex-a-ggdek5.enc \
tex-a-glk7jc.enc \
tex-a-gxztqc.enc \
tex-a-hgebqg.enc \
tex-a-jdumzv.enc \
tex-a-ju6eua.enc \
tex-a-jzblmk.enc \
tex-a-khaflp.enc \
tex-a-l7s2m2.enc \
tex-a-lqirpk.enc \
tex-a-nqwozw.enc \
tex-a-o6jpkv.enc \
tex-a-oolqad.enc \
tex-a-rt66h3.enc \
tex-a-t3w74u.enc \
tex-a-t6qg2v.enc \
tex-a-v5zdec.enc \
tex-a-v7r724.enc \
tex-a-vc7epu.enc \
tex-a-vrqych.enc \
tex-a-wd5mfa.enc \
tex-a-y2bxm4.enc \
tex-a-y72t7m.enc \
tex-a-ycjpon.enc \
tex-a-yl3wnd.enc \
tex-a-yoxmuz.enc \
tex-lato.map \
tex-lato.sty \
texlive-lato"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
tex-fontaxes.sty \
tex-fontspec.sty \
tex-ifluatex.sty \
tex-ifxetex.sty \
tex-updmap.cfg \
tex-xkeyval.sty \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-lato-fonts \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
