SUMMARY = "Severed fonts for texlive-montserrat"
DESCRIPTION = "The  separated fonts package for texlive-montserrat"
LICENSE = "OFL-1.1"

PV = "2023.209.1.03svn54512"

RPM_NAME = "texlive-montserrat-fonts-2023.209.1.03svn54512-55.1.noarch.rpm"
RPM_HASH = "e3488638a0b4facb1a9d537fceffa296608b06a378a007084725be09c0f8e495da0e3126bc9ef5458691596fd4d9a5f2e1ae6dfc2d27635366fb9dcca823277a"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "config-texlive-montserrat-fonts \
font--lang=aa \
font--lang=af \
font--lang=an \
font--lang=ast \
font--lang=av \
font--lang=ay \
font--lang=az-az \
font--lang=ba \
font--lang=be \
font--lang=bg \
font--lang=bi \
font--lang=bin \
font--lang=br \
font--lang=bs \
font--lang=bua \
font--lang=ca \
font--lang=ce \
font--lang=ch \
font--lang=chm \
font--lang=co \
font--lang=crh \
font--lang=cs \
font--lang=csb \
font--lang=cv \
font--lang=cy \
font--lang=da \
font--lang=de \
font--lang=en \
font--lang=eo \
font--lang=es \
font--lang=et \
font--lang=eu \
font--lang=fi \
font--lang=fil \
font--lang=fj \
font--lang=fo \
font--lang=fr \
font--lang=fur \
font--lang=fy \
font--lang=gd \
font--lang=gl \
font--lang=gn \
font--lang=gv \
font--lang=haw \
font--lang=ho \
font--lang=hr \
font--lang=hsb \
font--lang=ht \
font--lang=hu \
font--lang=ia \
font--lang=id \
font--lang=ie \
font--lang=ig \
font--lang=ik \
font--lang=io \
font--lang=is \
font--lang=it \
font--lang=jv \
font--lang=kaa \
font--lang=ki \
font--lang=kj \
font--lang=kk \
font--lang=kl \
font--lang=ku-am \
font--lang=ku-tr \
font--lang=kum \
font--lang=kv \
font--lang=kw \
font--lang=kwm \
font--lang=ky \
font--lang=la \
font--lang=lb \
font--lang=lez \
font--lang=lg \
font--lang=li \
font--lang=lt \
font--lang=lv \
font--lang=mg \
font--lang=mh \
font--lang=mk \
font--lang=mn-mn \
font--lang=mo \
font--lang=ms \
font--lang=mt \
font--lang=na \
font--lang=nb \
font--lang=nds \
font--lang=ng \
font--lang=nl \
font--lang=nn \
font--lang=no \
font--lang=nr \
font--lang=nso \
font--lang=nv \
font--lang=ny \
font--lang=oc \
font--lang=om \
font--lang=os \
font--lang=pap-an \
font--lang=pap-aw \
font--lang=pl \
font--lang=pt \
font--lang=qu \
font--lang=quz \
font--lang=rm \
font--lang=rn \
font--lang=ro \
font--lang=ru \
font--lang=rw \
font--lang=sah \
font--lang=sc \
font--lang=se \
font--lang=sel \
font--lang=sg \
font--lang=sh \
font--lang=sk \
font--lang=sl \
font--lang=sm \
font--lang=sma \
font--lang=smj \
font--lang=smn \
font--lang=sms \
font--lang=sn \
font--lang=so \
font--lang=sq \
font--lang=sr \
font--lang=ss \
font--lang=st \
font--lang=su \
font--lang=sv \
font--lang=sw \
font--lang=tg \
font--lang=tk \
font--lang=tl \
font--lang=tn \
font--lang=to \
font--lang=tr \
font--lang=ts \
font--lang=tt \
font--lang=ty \
font--lang=tyv \
font--lang=uk \
font--lang=uz \
font--lang=vi \
font--lang=vo \
font--lang=vot \
font--lang=wa \
font--lang=wen \
font--lang=wo \
font--lang=xh \
font--lang=yap \
font--lang=za \
font--lang=zu \
font-montserrat \
font-montserrat-black \
font-montserrat-blackitalic \
font-montserrat-bold \
font-montserrat-bolditalic \
font-montserrat-extrabold \
font-montserrat-extrabolditalic \
font-montserrat-extralight \
font-montserrat-extralightitalic \
font-montserrat-italic \
font-montserrat-light \
font-montserrat-lightitalic \
font-montserrat-medium \
font-montserrat-mediumitalic \
font-montserrat-regular \
font-montserrat-semibold \
font-montserrat-semibolditalic \
font-montserrat-thin \
font-montserrat-thinitalic \
font-montserratalternates \
font-montserratalternates-black \
font-montserratalternates-blackitalic \
font-montserratalternates-bold \
font-montserratalternates-bolditalic \
font-montserratalternates-extrabold \
font-montserratalternates-extrabolditalic \
font-montserratalternates-extralight \
font-montserratalternates-extralightitalic \
font-montserratalternates-italic \
font-montserratalternates-light \
font-montserratalternates-lightitalic \
font-montserratalternates-medium \
font-montserratalternates-mediumitalic \
font-montserratalternates-regular \
font-montserratalternates-semibold \
font-montserratalternates-semibolditalic \
font-montserratalternates-thin \
font-montserratalternates-thinitalic \
font-montserratalternatesblack \
font-montserratalternatesexlight \
font-montserratalternatesextrabold \
font-montserratalternateslight \
font-montserratalternatesmedium \
font-montserratalternatessemibold \
font-montserratalternatesthin \
font-montserratblack \
font-montserratextrabold \
font-montserratextralight \
font-montserratlight \
font-montserratmedium \
font-montserratsemibold \
font-montserratthin \
texlive-montserrat-fonts"

RDEPENDS:${PN} += "/usr/bin/sh \
aaa-base \
coreutils \
fontconfig \
ghostscript-fonts-std \
perl"

inherit rpm
