SUMMARY = "Python 3 bindings for libprelude"
DESCRIPTION = "Python 3 bindings for libprelude generated by SWIG."
LICENSE = "LGPL-2.1-only & LGPL-2.1-or-later"

PV = "5.2.0"

RPM_NAME = "python3-libprelude-5.2.0-2.14.aarch64.rpm"
RPM_HASH = "4e2d9cb9ab5f0114c51d4c57e99cf8ecaedbcbbda3df59ae3ff2a231ef374c449b59ffe4f3ccf85085f09c97363858c4889a4f05ee3987ae0dded3c6a49bf2bd"

RPROVIDES:${PN} += "python3-libprelude \
python3-libprelude(aarch-64) \
python3.10dist(prelude) \
python3dist(prelude)"
RDEPENDS:${PN} += "ld-linux-aarch64.so.1()(64bit) \
ld-linux-aarch64.so.1(GLIBC_2.17)(64bit) \
libc.so.6(GLIBC_2.22)(64bit) \
libgcc_s.so.1()(64bit) \
libgcc_s.so.1(GCC_3.0)(64bit) \
libgcc_s.so.1(GCC_3.3.1)(64bit) \
libprelude.so.28()(64bit) \
libprelude28 \
libpreludecpp.so.12()(64bit) \
libstdc++.so.6()(64bit) \
libstdc++.so.6(CXXABI_1.3)(64bit) \
libstdc++.so.6(CXXABI_1.3.9)(64bit) \
libstdc++.so.6(GLIBCXX_3.4)(64bit) \
libstdc++.so.6(GLIBCXX_3.4.21)(64bit) \
libstdc++.so.6(GLIBCXX_3.4.29)(64bit) \
python(abi)"

inherit rpm
