SUMMARY = "Trees and other linguists' macros"
DESCRIPTION = "The package defines a mechanism for specifying connected trees \
that uses a tabular environment to generate node positions. The \
package uses PostScript code, loaded by dvips, so output can \
only be generated by use of dvips. The package lingmacros.sty \
defines a few macros for linguists: \\enumsentence for \
enumerating sentence examples, simple tabular-based \
non-connected tree macros, and gloss macros."
LICENSE = "LPPL-1.0"

PV = "2023.209.0.0.91svn21751"

RPM_NAME = "texlive-tree-dvips-2023.209.0.0.91svn21751-53.1.noarch.rpm"
RPM_HASH = "fc95791697ac5f2c0c89dd6019553dfc92a39a5859c8b95396c339476c1aa6039680db7031473f7fa5af081880e5d8505cffb5b13453131aea1cd0c3bfdd6c02"
REPO_ARCH = "noarch"

RPROVIDES:${PN} += "tex-lingmacros.sty \
tex-tree-dvips.sty \
texlive-tree-dvips"

RDEPENDS:${PN} += "/usr/bin/sh \
coreutils \
ed \
findutils \
grep \
sed \
texlive \
texlive-filesystem \
texlive-kpathsea \
texlive-kpathsea-bin \
texlive-scripts \
texlive-scripts-bin"

inherit rpm
