SUMMARY = "Development files for ocaml-camlp5"
DESCRIPTION = "Camlp5 is a preprocessor-pretty-printer of OCaml, parsing a source file and printing some result on standard output. \
 \
This package contains the development files."
LICENSE = "BSD-3-Clause"

PV = "8.01.00"

RPM_NAME = "ocaml-camlp5-devel-8.01.00-1.1.aarch64.rpm"
RPM_HASH = "794bc9e05399babb86dc84149e3d44603428948724e493e83f1ef7d7e5ec451ff189ecd3254725231fa29269b0550a174879c560f07c544a7f735cbd577f9717"

RPROVIDES:${PN} += "ocaml(Argl) \
ocaml(Ast2pt) \
ocaml(Asttools) \
ocaml(Camlp5_top) \
ocaml(Camlp5_top_funs) \
ocaml(Diff) \
ocaml(Dynlink) \
ocaml(Dynlink_common) \
ocaml(Dynlink_compilerlibs) \
ocaml(Dynlink_platform_intf) \
ocaml(Dynlink_types) \
ocaml(Eprinter) \
ocaml(Exparser) \
ocaml(Extfold) \
ocaml(Extfun) \
ocaml(Fstream) \
ocaml(Gramext) \
ocaml(Grammar) \
ocaml(MLast) \
ocaml(Main) \
ocaml(Mlsyntax) \
ocaml(Ocpp) \
ocaml(Odyl) \
ocaml(Odyl_config) \
ocaml(Odyl_main) \
ocaml(Pa_extend) \
ocaml(Pa_extend_m) \
ocaml(Pa_extfold) \
ocaml(Pa_extfun) \
ocaml(Pa_extprint) \
ocaml(Pa_fstream) \
ocaml(Pa_lefteval) \
ocaml(Pa_lexer) \
ocaml(Pa_lisp) \
ocaml(Pa_macro) \
ocaml(Pa_macro_gram) \
ocaml(Pa_macro_print) \
ocaml(Pa_mkast) \
ocaml(Pa_mktest) \
ocaml(Pa_o) \
ocaml(Pa_oop) \
ocaml(Pa_op) \
ocaml(Pa_pprintf) \
ocaml(Pa_pragma) \
ocaml(Pa_r) \
ocaml(Pa_reloc) \
ocaml(Pa_rp) \
ocaml(Pa_scheme) \
ocaml(Pa_schemer) \
ocaml(Pa_sml) \
ocaml(Papr_phony_macro) \
ocaml(Parserify) \
ocaml(Pcaml) \
ocaml(Pconfig) \
ocaml(Plexer) \
ocaml(Plexing) \
ocaml(Ploc) \
ocaml(Pp_debug) \
ocaml(Pprintf) \
ocaml(Pr_depend) \
ocaml(Pr_dump) \
ocaml(Pr_extend) \
ocaml(Pr_extfun) \
ocaml(Pr_extprint) \
ocaml(Pr_null) \
ocaml(Pr_o) \
ocaml(Pr_official) \
ocaml(Pr_op) \
ocaml(Pr_r) \
ocaml(Pr_ro) \
ocaml(Pr_rp) \
ocaml(Pr_scheme) \
ocaml(Pr_schemep) \
ocaml(Pretty) \
ocaml(Prtools) \
ocaml(Q_MLast) \
ocaml(Q_ast) \
ocaml(Q_ast_base) \
ocaml(Q_phony) \
ocaml(Quotation) \
ocaml(Reloc) \
ocaml(Rprint) \
ocaml(Stdpp) \
ocaml(Token) \
ocaml(Versdep) \
ocaml-camlp5-devel \
ocaml-camlp5-devel(aarch-64) \
ocamlfind(camlp5) \
ocamlfind(camlp5.extend) \
ocamlfind(camlp5.extend.link) \
ocamlfind(camlp5.extend_m) \
ocamlfind(camlp5.extend_m.link) \
ocamlfind(camlp5.extfold) \
ocamlfind(camlp5.extfold.link) \
ocamlfind(camlp5.extfun) \
ocamlfind(camlp5.extfun.link) \
ocamlfind(camlp5.extprint) \
ocamlfind(camlp5.extprint.link) \
ocamlfind(camlp5.fstream) \
ocamlfind(camlp5.gramlib) \
ocamlfind(camlp5.macro) \
ocamlfind(camlp5.macro_gram) \
ocamlfind(camlp5.pa_lexer) \
ocamlfind(camlp5.pa_lexer.link) \
ocamlfind(camlp5.pa_o) \
ocamlfind(camlp5.pa_o.link) \
ocamlfind(camlp5.pa_op) \
ocamlfind(camlp5.pa_op.link) \
ocamlfind(camlp5.pa_r) \
ocamlfind(camlp5.pa_r.link) \
ocamlfind(camlp5.pa_scheme) \
ocamlfind(camlp5.pa_scheme.link) \
ocamlfind(camlp5.pa_schemer) \
ocamlfind(camlp5.parser_quotations) \
ocamlfind(camlp5.parser_quotations.link) \
ocamlfind(camlp5.parser_quotations_base) \
ocamlfind(camlp5.parser_quotations_base.link) \
ocamlfind(camlp5.phony_quotations) \
ocamlfind(camlp5.phony_quotations.link) \
ocamlfind(camlp5.pprintf) \
ocamlfind(camlp5.pprintf.link) \
ocamlfind(camlp5.pr_depend) \
ocamlfind(camlp5.pr_depend.link) \
ocamlfind(camlp5.pr_dump) \
ocamlfind(camlp5.pr_dump.link) \
ocamlfind(camlp5.pr_o) \
ocamlfind(camlp5.pr_o.link) \
ocamlfind(camlp5.pr_official) \
ocamlfind(camlp5.pr_official.link) \
ocamlfind(camlp5.pr_r) \
ocamlfind(camlp5.pr_r.link) \
ocamlfind(camlp5.pr_scheme) \
ocamlfind(camlp5.pr_scheme.link) \
ocamlfind(camlp5.pragma) \
ocamlfind(camlp5.quotations) \
ocamlfind(camlp5.quotations.link) \
ocamlfind(camlp5.streams) \
ocamlfind(camlp5.toploop) \
ocamlfind(camlp5.toploop.link) \
ocamlx(Argl) \
ocamlx(Ast2pt) \
ocamlx(Asttools) \
ocamlx(Diff) \
ocamlx(Eprinter) \
ocamlx(Exparser) \
ocamlx(Extfold) \
ocamlx(Extfun) \
ocamlx(Fstream) \
ocamlx(Gramext) \
ocamlx(Grammar) \
ocamlx(Main) \
ocamlx(Mlsyntax) \
ocamlx(Odyl) \
ocamlx(Odyl_config) \
ocamlx(Odyl_main) \
ocamlx(Pa_extend) \
ocamlx(Pa_extend_m) \
ocamlx(Pa_extfold) \
ocamlx(Pa_extfun) \
ocamlx(Pa_extprint) \
ocamlx(Pa_fstream) \
ocamlx(Pa_lefteval) \
ocamlx(Pa_lexer) \
ocamlx(Pa_lisp) \
ocamlx(Pa_macro) \
ocamlx(Pa_macro_gram) \
ocamlx(Pa_macro_print) \
ocamlx(Pa_mkast) \
ocamlx(Pa_mktest) \
ocamlx(Pa_o) \
ocamlx(Pa_oop) \
ocamlx(Pa_op) \
ocamlx(Pa_pprintf) \
ocamlx(Pa_pragma) \
ocamlx(Pa_r) \
ocamlx(Pa_reloc) \
ocamlx(Pa_rp) \
ocamlx(Pa_scheme) \
ocamlx(Pa_schemer) \
ocamlx(Pa_sml) \
ocamlx(Papr_phony_macro) \
ocamlx(Parserify) \
ocamlx(Pcaml) \
ocamlx(Pconfig) \
ocamlx(Plexer) \
ocamlx(Plexing) \
ocamlx(Ploc) \
ocamlx(Pp_debug) \
ocamlx(Pprintf) \
ocamlx(Pr_depend) \
ocamlx(Pr_dump) \
ocamlx(Pr_extend) \
ocamlx(Pr_extfun) \
ocamlx(Pr_extprint) \
ocamlx(Pr_null) \
ocamlx(Pr_o) \
ocamlx(Pr_official) \
ocamlx(Pr_op) \
ocamlx(Pr_r) \
ocamlx(Pr_ro) \
ocamlx(Pr_rp) \
ocamlx(Pr_scheme) \
ocamlx(Pr_schemep) \
ocamlx(Pretty) \
ocamlx(Prtools) \
ocamlx(Q_MLast) \
ocamlx(Q_ast) \
ocamlx(Q_ast_base) \
ocamlx(Q_phony) \
ocamlx(Quotation) \
ocamlx(Reloc) \
ocamlx(Stdpp) \
ocamlx(Token) \
ocamlx(Versdep)"

RDEPENDS:${PN} += "ocaml(Asttypes) \
ocaml(Build_path_prefix_map) \
ocaml(CamlinternalFormatBasics) \
ocaml(CamlinternalLazy) \
ocaml(Cmi_format) \
ocaml(Env) \
ocaml(Ident) \
ocaml(Identifiable) \
ocaml(Load_path) \
ocaml(Location) \
ocaml(Longident) \
ocaml(Misc) \
ocaml(Outcometree) \
ocaml(Parsetree) \
ocaml(Path) \
ocaml(Pprintast) \
ocaml(Primitive) \
ocaml(Shape) \
ocaml(Stdlib) \
ocaml(Stdlib__Arg) \
ocaml(Stdlib__Array) \
ocaml(Stdlib__Buffer) \
ocaml(Stdlib__Bytes) \
ocaml(Stdlib__Char) \
ocaml(Stdlib__Digest) \
ocaml(Stdlib__Either) \
ocaml(Stdlib__Filename) \
ocaml(Stdlib__Float) \
ocaml(Stdlib__Format) \
ocaml(Stdlib__Fun) \
ocaml(Stdlib__Gc) \
ocaml(Stdlib__Hashtbl) \
ocaml(Stdlib__Int) \
ocaml(Stdlib__Int32) \
ocaml(Stdlib__Int64) \
ocaml(Stdlib__Lazy) \
ocaml(Stdlib__Lexing) \
ocaml(Stdlib__List) \
ocaml(Stdlib__Map) \
ocaml(Stdlib__Nativeint) \
ocaml(Stdlib__Obj) \
ocaml(Stdlib__Option) \
ocaml(Stdlib__Parsing) \
ocaml(Stdlib__Printexc) \
ocaml(Stdlib__Printf) \
ocaml(Stdlib__Result) \
ocaml(Stdlib__Seq) \
ocaml(Stdlib__Set) \
ocaml(Stdlib__Stream) \
ocaml(Stdlib__String) \
ocaml(Stdlib__Sys) \
ocaml(Stdlib__Uchar) \
ocaml(Stream) \
ocaml(Subst) \
ocaml(Topdirs) \
ocaml(Toploop) \
ocaml(Type_immediacy) \
ocaml(Types) \
ocaml(Warnings) \
ocaml-camlp5 \
ocamlfind(camlp-streams) \
ocamlfind(compiler-libs.common) \
ocamlfind(pcre) \
ocamlx(Pprintast) \
ocamlx(Stdlib) \
ocamlx(Stdlib__Arg) \
ocamlx(Stdlib__Array) \
ocamlx(Stdlib__Buffer) \
ocamlx(Stdlib__Bytes) \
ocamlx(Stdlib__Char) \
ocamlx(Stdlib__Filename) \
ocamlx(Stdlib__Float) \
ocamlx(Stdlib__Format) \
ocamlx(Stdlib__Hashtbl) \
ocamlx(Stdlib__Int32) \
ocamlx(Stdlib__Int64) \
ocamlx(Stdlib__Lexing) \
ocamlx(Stdlib__List) \
ocamlx(Stdlib__Nativeint) \
ocamlx(Stdlib__Obj) \
ocamlx(Stdlib__Printexc) \
ocamlx(Stdlib__Printf) \
ocamlx(Stdlib__Set) \
ocamlx(Stdlib__String) \
ocamlx(Stdlib__Sys) \
ocamlx(Stream)"

inherit rpm
